### ISSUE TITLE
do not ping any host just because I opened the editor

### ISSUE THREAD

**Issue by nyxnor** [VSCodium/vscodium#1000]
**Describe the bug**
I don't want vercel and vsx to know I just opened my editor. I can see this connections by just opening VSCodium.
```
StreamId StreamPurpose StreamTarget CircuitId CircuitPurpose
--------------------------------------------------------------------------------------------------------------
3025 DNS_REQUEST vscodium.now.sh-(76.76.21.164:0) 4591  GENERAL
3027 DNS_REQUEST vscodium.vercel.app-(76.76.21.123:0) 4591  GENERAL
3029 DNS_REQUEST open-vsx.org-(198.41.30.195:0) 4591  GENERAL
3030 USER open-vsx.org-(198.41.30.195:443) 4590  GENERAL
```
This is not like I have request a marketplace application, this simply happens by just opening the editor.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
Not sure, I don't use VSCode, and pinging MS would be worse.

**Please confirm that the issue/resolution isn't already documented**
- [ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**

Open the editor. Watch DNS requests.

**Expected behavior**

Disable this. It may not be telemetry or just checking if it is up to date, but I don't want these connections to happen.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS, Ubuntu 20.04, etc]
 - Architecture [e.g. x64, ia32, arm64]
 - Version [e.g. 1.33.0]

Debian
amd64, x86_64
VSCodium 1.64.2

**Additional context**

**Comment by daiyam** [comment]
To deactivate the update checkup, you will need to deactivate it with "update.mode": "none" in your settings.

**Comment by nyxnor** [comment]
Thanks, it is not pinging vercel anymore.

```sh
4173 DNS_REQUEST open-vsx.org-(198.41.30.195:0) 5071  GENERAL
4174 USER open-vsx.org-(198.41.30.195:443) 5073  GENERAL
```
I don't have any extensions currently.

Unchecked, set to false and to none everything available with `@tag:usesOnlineServices`

**Comment by sydbarrett74** [comment]
How about setting 'update.mode' to 'none' by default in release versions?

**Comment by bigbenzh** [comment]
> I don't have any extensions currently.

I think this is due to the design of built-in marketplace function in vscode, and there is no easy way to disable the ping to the marketplace server (which is `open-vsx.org` in vscodium) without breaking the whole marketplace function.

(probably) related: #623 #732 

if you don't want the plugin update and prefer install plugins manually, you can modify `product.json` and replace `open-vsx.org` to `127.0.0.1` or an invalid domain

**Comment by nyxnor** [comment]
Thanks.
It is related to that issue and I endorse the idea of disabling network of the IDE, but I do not endorse the rudeness of the author of that post.
As that issue is waiting for a pull request, will close this one.
