### ISSUE TITLE
AppImage binary support

### ISSUE THREAD

**Issue by tyu1996** [VSCodium/vscodium#101]
I tried to build VSCodium AppImage from deb binary package by myself, but no avail (Suppose I'm missing something). 

Would like to have an official AppImage build here, I'll gladly help to use it for daily basis.

**Comment by tyu1996** [comment]
@probonopd Have you known this before? This is VS Code binary without Microsoft proprietary things.

**Comment by probonopd** [comment]
Since this project already gets built on Travis CI it might be best to run it through `linuxdeployqt `like shown in https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci to produce AppImages. What does @stripedpajamas think?

**Comment by msdobrescu** [comment]
+1

**Comment by stripedpajamas** [comment]
Thanks for the info @probonopd! Currently I believe Microsoft does not provide AppImages of their build of `vscode`, but it does sound like it would be a great thing for VSCodium to provide. They have recently started providing snap packages, so my goal would be to first support VSCodium in the snap format and then, if it is feasible, to support VSCodium in AppImage format. Any help toward either end is welcome.

**Comment by probonopd** [comment]
On a deb-based system, e.g., as part of your Travis CI build, run

```
wget -c "https://github.com/AppImage/pkg2appimage/raw/master/pkg2appimage"
bash -ex pkg2appimage VSCodium
```

This will convert the deb into an AppImage.

Here is the recipe:
https://github.com/AppImage/pkg2appimage/blob/master/recipes/VSCodium.yml

If you want to make the AppImage generation part of your Travis CI build, you should store a local copy of the recipe and change

https://github.com/AppImage/pkg2appimage/blob/c7ed83bb539358f25c4a3cd0d10017ebf2ce9f9a/recipes/VSCodium.yml#L20-L21

to

`cp vscode/.build/linux/deb/amd64/deb/*.deb .` so that the deb does not get downloaded, but the one from the currently running Travis CI job is used.

**Comment by stripedpajamas** [comment]
Wow thanks so much @probonopd 

I will work on getting this into Travis.

🎉 🎉 🎉 

Would it then be helpful for everyone if this AppImage was uploaded as another file in the release to Github Releases?

**Comment by probonopd** [comment]
> Would it then be helpful for everyone if the outputted AppImage was uploaded as another file in the release to Github Releases?

Absolutely. 👍

**Comment by stripedpajamas** [comment]
Any comments on #108 welcome, or if all looks good I will merge in tomorrow. AppImage would be generated on next release from MS.

**Comment by probonopd** [comment]
Currently it does not pass our automated tests:

```
/tmp/.mount_BeingTiZw5ff/vscodium.desktop: hint: value "Utility;TextEditor;Development;IDE;" for key "Categories" in group "Desktop Entry" contains more than one main category; application might appear more than once in the application menu
FATAL: Key Icon is not in .desktop file exactly once
```

If those are fixed, it should hopefully pass the tests. (The test checks that `Icon=` is in the desktop file exactly once, which is probably a bit oversimplistic.)

**Comment by stripedpajamas** [comment]
@probonopd could it be related to this https://github.com/AppImage/appimage.github.io/issues/35 ? Only wondering because I know pkg2appimage runs `desktop-file-validate` itself and it isn't throwing the FATAL message there. During build I'm running `sudo apt-get install desktop-file-utils` because when I ran it the first time pkg2appimage failed `desktop-file-validate` not being installed. So I'm probably using the latest version and maybe the automated tests aren't?

**Comment by tyu1996** [comment]
Thanks a lot @probonopd ! I am just a week new to AppImage and no much experience on building AppImage, as the program like VSCodium will be too hard for me. 

I will dig deeper on building AppImage as long as I have free time!

**Comment by stripedpajamas** [comment]
```
+desktop-file-validate ./usr/share/applications/vscodium.desktop
./usr/share/applications/vscodium.desktop: hint: value "Utility;TextEditor;Development;IDE;" for key "Categories" in group "Desktop Entry" contains more than one main category; application might appear more than once in the application menu
```

is what I see in the build log https://api.travis-ci.com/v3/job/191646710/log.txt

**Comment by probonopd** [comment]
> @probonopd could it be related to this AppImage/appimage.github.io#35?

No, it's a test I coded... to ensure that there is exactly one `Icon=:`

https://github.com/AppImage/pkg2appimage/blob/3168d7ce787246feb697a950005fbffec0533def/appdir-lint.sh#L58-L63

**Comment by stripedpajamas** [comment]
@probonopd how do I fix this? And why wouldn't `vscode` experience this? We aren't doing icons differently as far as I know.

**Comment by probonopd** [comment]
This may do the trick:

https://github.com/AppImage/pkg2appimage/commit/8a23e2bd3c184fc75c94526440b554643e7f84f8

**Comment by stripedpajamas** [comment]
Hmm alright that actually broke things because `Actions` references `new-empty-window` which that `for` loop deletes. 

Comparing VSCodium and Code's resulting `.desktop` files and they look very similar -- is VSCode's AppImage passing lint?

```
[Desktop Entry]
Name=VSCodium
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=vscodium --unity-launch %F
Icon=vscodium
Type=Application
StartupNotify=false
StartupWMClass=VSCodium
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;
Actions=new-empty-window;
Keywords=vscode;

X-AppImage-Version=1.33.1-1555005058.glibc2.17

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=vscodium --new-window %F
Icon=vscodium
```

```
[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --unity-launch %F
Icon=com.visualstudio.code
Type=Application
StartupNotify=false
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;
Actions=new-empty-window;
Keywords=vscode;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/usr/share/code/code --new-window %F
Icon=com.visualstudio.code
```

**Comment by probonopd** [comment]
Yes, I wanted to get rid of the `[Desktop Action new-empty-window]` block because it contains a second `Icon=` line which makes my test fail (because the test is a bit too simplistic).

**Comment by stripedpajamas** [comment]
Yeah I understand that, but I'm seeing that VSCode's `desktop` file has the block in there. Was that lint rule added after VSCode's recipe? Does VSCode's current recipe->AppImage fail current linting like VSCodium's does?

**Comment by probonopd** [comment]
I don't know whether recent versions of VSCode have a `[Desktop Action new-empty-window]` these days. Back when I created that recipe it was working for me.

**Comment by stripedpajamas** [comment]
The `desktop` file I pasted in from VSCode was from their latest version 1.33.1 and it has the `new-empty-window` thing. 

Does it make sense perhaps for the linter to only care if there is more than one Icon key per Action instead of globally?

**Comment by probonopd** [comment]
Sure but I don't know how to do this in bash.

https://github.com/AppImage/pkg2appimage/blob/3168d7ce787246feb697a950005fbffec0533def/appdir-lint.sh#L58-L63

**Comment by stripedpajamas** [comment]
I don't know if it will be missed, but I'm trying my best to make as few changes as possible to the build/post-build to keep things in line with VSCode.

I wrote up some bash to check keys in each section separately and opened a [PR](https://github.com/AppImage/pkg2appimage/pull/367).

**Comment by probonopd** [comment]
Thanks, please see my comment there.

**Comment by probonopd** [comment]
When will it show up on https://github.com/VSCodium/vscodium/releases?

**Comment by stripedpajamas** [comment]
@probonopd on Microsoft's next release, so probably the beginning of May. The AppImage build process runs at the end of the Linux build script which won't run as the latest release already contains the Linux artifacts.

**Comment by Bkucera** [comment]
> Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate

@probonopd is this currently possible?

**Comment by probonopd** [comment]
It is currently not enabled for this AppImage, one would need to embed update information and publish a zsync file.

**Comment by Bkucera** [comment]
@probonopd thanks. Also, is there a way to use the cli via AppImage? https://code.visualstudio.com/docs/editor/command-line

**Comment by probonopd** [comment]
Sure, why not?
