### ISSUE TITLE
VSCodium now marked as Unsupported by M$

### ISSUE THREAD

**Issue by Razique** [VSCodium/vscodium#1012]
After installing the 1.65.2, I see a brief pop-up on the corner that tells me that my installation of VSCodium is corrupt.
I get redirected to [the following link](https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt-unsupported).
The header shows that the software is in an unsupported` state. Curious to know if there will be any technical impact or if this is an attempt from Microsoft to slowly close in on non-official builds :(

This is the top bar:
<img width="536" alt="Screenshot 2022-03-11 at 15 39 29" src="https://user-images.githubusercontent.com/1027278/157990266-0d4b2c59-f5a3-45ba-ab17-79b5ddca38b6.png">

Notification:
<img width="600" alt="Screenshot 2022-03-11 at 15 53 35" src="https://user-images.githubusercontent.com/1027278/157993230-ca9f423e-cbb3-49b6-9013-78aaf68a2d21.png">

```
Version: 1.65.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-11T00:14:59.732Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.12-300.fc34.x86_64
```

**Comment by JakeHL** [comment]
Not sure if this helps but I experienced the same issue on VSCodium and VSCode proper after installing some pretty (aggressive)[https://marketplace.visualstudio.com/items?itemName=leandro-rodrigues.fluent-ui-vscode] extensions.

**Comment by Razique** [comment]
On my end, I don't use many extensions, and most of them are the most-used ones (Python support, YAML, and so on)
