### ISSUE TITLE
When I open terminal it gives some errors

### ISSUE THREAD

**Issue by karam72** [VSCodium/vscodium#1015]
Hi,

When I open terminal tab inside VSCodium on the terminal it prints this errors:

```
/home/my_current_user/appimage_files/VSCodium-1.65.2-1646957649.glibc2.17-x86_64.AppImage: /tmp/.mount_VSCodil5Gyfh/lib/x86_64-linux-gnu/liblzma.so.5: version `XZ_5.2' not found (required by /lib64/libarchive.so.13)
/home/my_current_user/appimage_files/VSCodium-1.65.2-1646957649.glibc2.17-x86_64.AppImage: /tmp/.mount_VSCodil5Gyfh/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by /lib64/libostree-1.so.1)
/home/my_current_user/appimage_files/VSCodium-1.65.2-1646957649.glibc2.17-x86_64.AppImage: /tmp/.mount_VSCodil5Gyfh/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by /lib64/libgio-2.0.so.0)
/home/my_current_user/appimage_files/VSCodium-1.65.2-1646957649.glibc2.17-x86_64.AppImage: /tmp/.mount_VSCodil5Gyfh/lib/x86_64-linux-gnu/liblzma.so.5: version `XZ_5.2' not found (required by /lib64/librpmio.so.9)
/home/my_current_user/appimage_files/VSCodium-1.65.2-1646957649.glibc2.17-x86_64.AppImage: /tmp/.mount_VSCodil5Gyfh/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by /lib64/libmount.so.1)
/home/my_current_user/appimage_files/VSCodium-1.65.2-1646957649.glibc2.17-x86_64.AppImage: /tmp/.mount_VSCodil5Gyfh/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by /lib64/libkrb5support.so.0)
/home/my_current_user/appimage_files/VSCodium-1.65.2-1646957649.glibc2.17-x86_64.AppImage: /tmp/.mount_VSCodil5Gyfh/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by /home/my_current_user/appimage_files/VSCodium-1.65.2-1646957649.glibc2.17-x86_64.AppImage)
```

More tails about case:
- It does not matter if I open the zsh or bash or tmux.
- I can run properly any command on that terminal.
- On my native terminal (gnome-terminal) of Fedora, I don't have any kind of problem.
- Until now all other features of VSCodium works properly.

**Detail of my system:**
- VSCodium-1.65.2-1646957649.glibc2.17-x86_64.AppImage

**Operating system:**
Fedora Linux 35 (Workstation Edition) 64 bit (which has default Gnome version 41.3 + Windows system: Wayland as default)

**Note 1:**
I have nothing installed or removed on system yet (except those: I installed VLC, ZSH and KVM from official repositories). Fedora is just new installed on my machine.

Please let me know If you need more details.

Thanks in advance.

**Comment by Nidrop** [comment]
I confirm the problem. This is appimage issue. It seems to be a compatibility problem with the system programs and libraries that come with appimage. You can fix this for the current session and only for the terminal (i.e. it does not affect the build button and everything else): 
```
unset LD_LIBRARY_PATH
```
Vscodium from tar.gz archive works fine.
