### ISSUE TITLE
VScode is offering a new feature which makes it easy to disable telemtry. Is there still a need for vscodium?

### ISSUE THREAD

**Issue by elieobeid7** [VSCodium/vscodium#1018]
I use vscodium on pretty much all my projects and I keep vscode for when I need to work on a project which requires extensions that I cannot find on vscodium store, like Shopify Liquid template support.

Today I was installing Vscode on my new work laptop and I noticed that now vscode asks you if you want to disable telemetry when it starts.

If disabling telemetry is that easy as of today on vscode,  does vscodium still serve a purpose? I'm asking here because you guys review vscode source code, so there might be some features that are still enabled that I don't know of.

**Comment by paulcarroty** [comment]
Sure.

**Comment by elieobeid7** [comment]
@paulcarroty  Why? could you elaborate?

**Comment by stripedpajamas** [comment]
The telemetry was a secondary purpose to the project. The primary purpose was releasing a VSCode binary that's MIT-licensed.

**Comment by G2G2G2G** [comment]
I'd honestly not use anything vscode related if vscodium didn't exist.
@elieobeid7 close threads when they are done
