### ISSUE TITLE
Terminal CTRL-CLICK open file twice

### ISSUE THREAD

**Issue by nicohell** [VSCodium/vscodium#1019]
On a Linux box, CTRL+CLICK on a file relative path in a terminal, opens a second editor even if file already opened.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
- [x] did not test in Visual Studio Code 

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open a terminal in VSCodium
2. Open a file via CTRL+P  
3. In terminal search for file to display relative path (ex : ./app/Http/Controllers/MyAwsomeController.php)
4. CTRL+CLICK on relative path displayed in terminal
5. File is opened in a second editor

**Expected behavior**
Switch to editor already editing file

**Desktop (please complete the following information):**
 - OS: Rocky Linux 
 - Architecture X64
 - Version :  8.5

**Additional context**
My project directory has been added in VScodium via a symlink and the new editor uses realpath
project directory : /web/project 
/web is a symlink to /home/data/wwww
first editor tab shows : /web/project/file
second editor tab shows : /home/data/www/projedt/file

**Comment by daiyam** [comment]
I don't have the issue on macOS. I will try on other systems.

**Comment by nicohell** [comment]
Looks like on lastest versions (since 1.70.x ??) all files open on full path and even if already opened with relative path.

**Comment by nicohell** [comment]
Hi 
Maybe I made some modifications in Settings but on V1.71.2,  today CTRL+SHIFT+P displays both relative and  fullPath

CTRL+CLICK in terminal always open on fullPath.

Any help appreciated. 
Regards
