### ISSUE TITLE
Not able to install github copilot

### ISSUE THREAD

**Issue by tusharhero** [VSCodium/vscodium#1020]
**Describe the bug**
I am not able to follow " instructions for installing copilot on vscode" on vscodium.
It shows me the extension doesn't exist when i run `ext install GitHub.copilot`

**Please confirm that this problem is VSCodium-specific**
- [ I don't know about this, but probably it is Codium specific] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ Yes, I think it is not mentioned there.] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to 'https://marketplace.visualstudio.com/items?itemName=GitHub.copilot'
2. Copy Install command
3. Ctrl + P
4. Paste the command and hit enter
5. See extension not found message

**Expected behavior**
I want to start installing Codium

**Screenshots**
![image](https://user-images.githubusercontent.com/54012021/160034355-6a0d93df-aab6-493a-8982-66612153cd8f.png)**Desktop (please complete the following information):**
 - OS: Elementary OS 6.1 Jólnir
 - Architecture x86_64
 - Version 1.65.2

**Comment by BobIsMyManager** [comment]
you can download the vsix file by pressing the download button on the right of the marketplace site

**Comment by BobIsMyManager** [comment]
The extension wont work anyway as it seems that it relys on something microsoft adds when building VSCode

**Comment by JakeHL** [comment]
This isn't a bug and is documented in the readme [here](https://github.com/VSCodium/vscodium#extensions-and-the-marketplace). If an extension doesn't exist on the open-vsx.org registry it can't be installed through traditional means.

**Comment by JakeHL** [comment]
By using workarounds you are not installing it via traditional means so the statement is true. The Open VSIX registry is the only *supported* method as far as I'm aware. But more to the point, the docs I linked to also state:
> Please note that some Visual Studio Code extensions have licenses that restrict their use to the official Visual Studio Code builds and therefore do not work with VSCodium. See [this note](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#proprietary-debugging-tools) on the Docs page for what's been found so far and possible workarounds.

So while I agree it would be good to get it working, I'm not sure its an issue for Codium?

**Comment by BobIsMyManager** [comment]
Yep, thats not really an issue that can be fixed by the codium team
