### ISSUE TITLE
Suggestion: I'd like to sponsor VSCodium with an M1 build agent & update server

### ISSUE THREAD

**Issue by JakeHL** [VSCodium/vscodium#1023]
Hi there,

I'm a big fan of VSCodium & currently I build it myself for my M1 machine. I'm looking to source in the near future a mac mini for some software development projects and would be glad to dedicate some of it's resources as an M1 build agent. I understand that Apple Silicon isn't officially supported with github actions however it [seems](https://github.com/actions/runner/issues/805) like there have been successful [attempts](https://github.com/mas-cli/m1-github-actions-runner) at DIY'ing it. Is this something the maintainers of the project would be interested in?

I can't make any guarantees in terms of timescales, however I thought I'd ask early on as it will affect the spec of the machine I get. (I'm also saving for a wedding so funds are tight 😄)

I also have several small dedicated self hosted linux servers with plenty of resources that I would be glad to run the update server on as it seems to have not been running for some time as far as I can tell.

Thanks for your consideration.

**Comment by daiyam** [comment]
Yes, any help is welcome!
The best would be that you make a PR with the updated workflow that you have tested on your fork.
If you can't do it, I can help setup the workflow but I will need help to test if the binary is fine.

**Comment by JakeHL** [comment]
Brilliant thanks! Feel free to close this if necessary. As I say, it could be a while before I get going with this. 👍🏻

**Comment by daiyam** [comment]
@JakeHL I've discover that MacStadium offers free vm for open source project. I will try it. But even if I cane make the workflow working, I would need your help to test the binary on M1 ;)

**Comment by daiyam** [comment]
@JakeHL About the update servers, @paulcarroty won't that be useful for the deb/rpm repositories?

**Comment by paulcarroty** [comment]
yeah, check their traffic limits first.

**Comment by JakeHL** [comment]
> @JakeHL I've discover that MacStadium offers free vm for open source project. I will try it. But even if I can make the workflow working, I would need your help to test the binary on M1 ;)

Absolutely! I'll do anything I can to help get first class support on m1. If you ever struggle to reach me on here, feel free to ping me at codium@twilsoft.uk, it'll come through to my main inbox.

**Comment by JakeHL** [comment]
Great work man! I'll test the builds later on today. I've been using Helix editor lately to test it so it'll be refreshing to come back to codium.
