### ISSUE TITLE
suggestion: Drop the 'VS' from the name. "Codium"

### ISSUE THREAD

**Issue by JakeHL** [VSCodium/vscodium#1024]
Sorry if this comes across as rude. It's completely not intended to be that way.

As far as I understand, the name of the application is a nod to 'Chromium' being the OSS version of 'Google Chrome'. I think it would be fitting to drop the VS from the name, similar to how 'Google' is missing from 'Chromium'.

In my opinion I think it would be a great way to distance the product from Microsoft.

If any other names are up for consideration, I've taken to calling it 'cody'. My aliases in the terminal are all named as such. `cody -r .` is probably my most used command. 😄

**Comment by paulcarroty** [comment]
You're late 😅 https://github.com/VSCodium/vscodium/pull/293

**Comment by JakeHL** [comment]
Aha sorry! I did a search but obviously not well enough. Thanks for closing!
