### ISSUE TITLE
vscodium.com and download.vscodium.com are down 

### ISSUE THREAD

**Issue by brakhane** [VSCodium/vscodium#1026]
Both just show a default NameCheap page

**Comment by MrAidanlw97** [comment]
The vscodium.com domain name expired today
![Screenshot from 2022-03-30 20-59-04](https://user-images.githubusercontent.com/34199154/160920669-f43ef2bc-e5e6-46b7-b101-cbe108f11fa7.png)

**Comment by daiyam** [comment]
pinging @stripedpajamas

**Comment by sigaloid** [comment]
Uh oh. That means someone else owns it. The repo is signed, right?

**Comment by paulcarroty** [comment]
> Edit "enabled=1" to "enabled=0"

You don't need to disable it, just use Gitlab repository: https://github.com/VSCodium/vscodium#install-with-package-manager

**Comment by stripedpajamas** [comment]
I don't own the domain. Pinging @PalinuroSec who I believe is/was the owner.

**Comment by daiyam** [comment]
It seems to have been fixed.
