### ISSUE TITLE
Fresh-build VSCodium shows up eletron default icon, while downloaded release is fine

### ISSUE THREAD

**Issue by ziyike** [VSCodium/vscodium#1031]
**Describe the bug**
When building VSCodium locally, the resulting VSCodium.exe shows up eletron icon, instead of the vscodium one.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
   > Well, vscode dev build uses an ugly icon much different from any of the market ones.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. `cd .\vscodium\`
2. `powershell -ExecutionPolicy ByPass -File .\build\build_windows.ps1`
3. wait quite a while
4. See the out dir, say `.\VSCode-win32-x64\`, the VSCodium.exe shows electron icon

**Expected behavior**
Not showing electron default icon.

**Screenshots**
![image](https://i.imgur.com/GpLkKkf.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11 21H2 22000.556]
 - Architecture [x64]
 - Version [1.66.0] *1.65.2 as well*, *haven't tried any earlier version*

**Additional context**
Is this an electron thing?
Cuz I did find some information saying that electron might keep wrongly cache of app, then points to an invalid path of icon resources, resulting back to default electron icon.
However, I did not find a valid solution yet, except for telling me to clean up everything in the environment, which sounds like a desperate resort.
Any thoughts or possible solutions? Please elaborate.
Thanks.

**Comment by daiyam** [comment]
I don't have the issue on Windows 10.

**Comment by bigfatmoon** [comment]
Same problem on Windows 10. Also in context menu for file "Electron" app appears (if I use checkbox to add command to context menu then there are two commands to open VSCodium - this and normal)
