### ISSUE TITLE
Double-clic on title bar doesn't maximise window

### ISSUE THREAD

**Issue by cy-altern** [VSCodium/vscodium#1032]
**Describe the bug**
Since VSCodium version 1.66.0 a double-click on the title bar of a VSCodium window no longer maximizes the window.
The "Enlarge" button and the keyboard shortcut "Windows + up arrow" are still OK.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
- [x] I don't have Microsoft's Visual Studio Code for testing if the bug happen on it...

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. open a VSCodium window as normal size
2. double click on the title bar to maximize it
3. the window don't maximise

**Expected behavior**
As of all Windows window, a double-clic on title bar must maximise the window

**Desktop :**
 - OS: Windows 10 pro
 - Architecture : x64
 - Version : version 21H2, build 19044.1586

**Comment by daiyam** [comment]
I can also confirm the bug on Windows 10.

**Comment by JInfantesC** [comment]
Same problem. Also, im unable to resize the window using the mouse dragging the corners.

If you click any of the new top buttons, im able to resize or maximize, but only once.
![imagen](https://user-images.githubusercontent.com/7262829/161528151-fc12dcce-2ed5-4d2e-b414-1e9c2f955dcb.png)

If i need to resize again, i need to click those buttons again.

Versión: 1.66.0 (system setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Fecha: 2022-03-31T10:00:15.105Z
Electrón: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by daiyam** [comment]
The issue might be fixed with electron v17.3.0. Some Visual Studio Code users are experiencing the issue...

**Comment by daiyam** [comment]
The issue has been fix in `v1.67`.
