### ISSUE TITLE
Codium can't be found by typing "codium"

### ISSUE THREAD

**Issue by DuckDuckWhale** [VSCodium/vscodium#1033]
**Describe the bug**
On Gnome, Only the search term `VSCodium` can bring it up and not `Codium` which is the same as the command to launch it, which is somewhat annoying.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
~~Not sure, do not have VSCode installed so not sure if it can be found by typing `Code`.~~ It only happens to VSCodium because it has a different name.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Press the super key
2. Type `Codium`
3. Nothing shows up

**Expected behavior**
VSCodium shows up.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Architecture: AMD64
 - Version: 1.65.2

**Comment by strider72** [comment]
Yes, with VS Code, it comes up when you type "code". (for example, in the Start Menu on Win 10)

**Comment by DuckDuckWhale** [comment]
Interestingly, typing `code` also summons VSCodium... But I didn't know that before experimenting and only knew to type `codium` because the command is also `codium`. It might be a good idea to add it as an extra search term.

**Comment by red5h4d0w** [comment]
to get the functionality on your machine, you can look at `usr/share/applications`. There should be a desktop file for vscodium. If you change the keyword field it should do what you want.
To specify many keywords use the syntax
`Keywords=vscode;codium;code;etc...`

**Comment by red5h4d0w** [comment]
Will try to see whether adding the keyword in the repo can be done easily

**Comment by DuckDuckWhale** [comment]
keep alive

**Comment by DuckDuckWhale** [comment]
keep alive
