### ISSUE TITLE
Jupyter not working ("Play" button is missing)

### ISSUE THREAD

**Issue by ttronas** [VSCodium/vscodium#1034]
**Describe the bug**
Since the update to VSCodium v.1.66.0 Jupyter is not working anymore. The "Play" button as well as any other Jupyter kernel-related features don't show up. Instead, a notification pops up:
![grafik](https://user-images.githubusercontent.com/78816242/161494578-30323ee8-c735-42fe-a408-8626f2e26992.png)
When opening the dev panel, it reads:
![grafik](https://user-images.githubusercontent.com/78816242/161497041-edfc9e2e-9ad2-4c9e-9a46-992dcdc3fc61.png)

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code with the same version. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Have Jupyter installed (my version is v2022.3.1000901801 but it still happens in the dev version)
2. Create a new ".ipynb"-file
3. Wait for a few seconds
4. See notification and missing "Play" buttons

**Expected behavior**
I would have expected Jupyter to work properly - just as before. But something broke during the latest update...

**Screenshots**
This is in VSCodium:
![grafik](https://user-images.githubusercontent.com/78816242/161495279-cca25411-9798-4309-b00a-de22342998df.png)
This is in VS Code:
![grafik](https://user-images.githubusercontent.com/78816242/161496621-4b20c18a-3150-4cf5-b330-6d719dd1a404.png)

**Desktop (please complete the following information):**

*VSCodium:*
Version: 1.66.0 (system setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Datum: 2022-03-31T10:00:15.105Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
Betriebssystem: Windows_NT x64 10.0.19044

*VS Code:*
Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

**Additional context**
Thanks for helping me out! And btw: Thanks a lot for the great effort in making VSCodium such a great project!
If I can help you with more detailed information, just let me know!

Jonas

*Edit:*
I can also add, that Python itself is working, though I cannot change to a different interpreter in VSCodium (VS Code works as expected). Maybe these Problems are caused by the same root, so I won't open a new Issue here.

**Comment by Kytie** [comment]
Getting the same issue with my vscodium.
vscodium: 1.66.0
jupyter: v2022.3.1000901801
OS: Linux x64 5.16.0-12parrot1-amd64

Looking at the runtime status of the jupyter plugin I get this error.
"interactive/toolbar is a proposed menu identifier. It requires 'package.json#enabledApiProposals: ["notebookEditor"]' and is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-toolsai.jupyter"

**Comment by daiyam** [comment]
It seems like missing api in the `project.json`. Can you test and contribute a PR?

**Comment by nemonein** [comment]
vscoduim : 1.66.0
OS : ArchLinux (by [aur package](https://aur.archlinux.org/packages/vscodium-bin))

`ms-toolsai.jupyter` is already located in `product.json`.

```
  "extensionAllowedProposedApi": ["ms-vscode.cpptools",
         "ms-azuretools.vscode-docker",
         "visualstudioexptteam.vscodeintellicode",
         "GitHub.codespaces",
         "GitHub.vscode-pull-request-github-insiders",
         "GitHub.vscode-pull-request-github",
         "Microsoft.vscode-nmake-tools",
         "ms-ai-tools.notebook-renderers",
         "ms-dotnettools.dotnet-interactive-vscode",
         "ms-python.gather",
         "ms-python.python",
         "ms-toolsai.jupyter",
         "ms-toolsai.vscode-ai",
         "ms-toolsai.vscode-ai-remote",
         "ms-vscode-remote.remote-containers-nightly",
         "ms-vscode-remote.remote-containers",
         "ms-vscode-remote.remote-ssh-edit-nightly",
         "ms-vscode-remote.remote-ssh-edit",
         "ms-vscode-remote.remote-ssh-nightly",
         "ms-vscode-remote.remote-ssh",
         "ms-vscode-remote.remote-wsl-nightly",
         "ms-vscode-remote.remote-wsl",
         "ms-vscode-remote.remote-wsl-recommender",
         "ms-vscode-remote.vscode-remote-extensionpack-nightly",
         "ms-vscode-remote.vscode-remote-extensionpack",
         "ms-vscode.azure-account",
         "ms-vscode.azure-sphere-tools-ui",
         "ms-vscode.azure-sphere-tools",
         "ms-vscode.github-browser",
         "ms-vscode.github-richnav",
         "ms-vscode.js-debug-nightly",
         "ms-vscode.js-debug",
         "ms-vscode.lsif-browser",
         "ms-vscode.vscode-js-profile-flame",
         "ms-vscode.vscode-js-profile-table",
         "ms-vscode.vscode-selfhost-test-provider",
         "ms-vsliveshare.cloudenv-explorer",
         "ms-vsliveshare.cloudenv",
         "ms-vsliveshare.vsliveshare",
         "ms-vsonline.vsonline",
         "dbaeumer.vscode-eslint"],
```
If Codium is run through `/usr/bin/codium --enable-proposed-api ms-toolsai.jupyter`, then it works fine. However, before 1.66.0 I could run Codium without this option (and there were no errors for Jupyter plugin).

**Comment by nemonein** [comment]
I've check the `product.json` of VS Code.
They changed the format as well as the contents.
`extensionAllowedProposedApi` ➙ `extensionEnabledApiProposals`

```
"extensionEnabledApiProposals": {
        "ms-vscode.vscode-selfhost-test-provider": ["testObserver"],
        "VisualStudioExptTeam.vscodeintellicode-completions": ["inlineCompletions"],
        "ms-vsliveshare.vsliveshare": ["contribMenuBarHome", "diffCommand", "documentFiltersExclusive", "fileSearchProvider", "findTextInFiles", "notebookCellExecutionState", "notebookContentProvider", "notebookDocumentEvents", "notebookEditor", "notebookEditorEdit", "notebookLiveShare", "terminalDimensions", "terminalDataWriteEvent", "textDocumentNotebook", "textSearchProvider"],
        "ms-vscode.js-debug": ["portsAttributes", "findTextInFiles", "workspaceTrust", "resolvers"],
        "ms-toolsai.vscode-ai-remote": ["resolvers", "notebookEditor"],
        "ms-python.python": ["quickPickSortByLabel", "testObserver", "notebookEditor"],
        "ms-dotnettools.dotnet-interactive-vscode": ["notebookConcatTextDocument", "notebookContentProvider", "notebookCellExecutionState", "notebookControllerKind", "notebookDebugOptions", "notebookDeprecated", "notebookEditor", "notebookEditorDecorationType", "notebookEditorEdit", "notebookLiveShare", "notebookMessaging", "notebookMime", "textDocumentNotebook"],
        "GitHub.codespaces": ["contribMenuBarHome", "contribRemoteHelp", "contribViewsRemote", "notebookEditor", "resolvers", "terminalDataWriteEvent", "treeViewReveal"],
        "ms-vscode.azure-repos": ["extensionRuntime", "fileSearchProvider", "resolvers", "textSearchProvider"],
        "ms-vscode.remote-repositories": ["contribRemoteHelp", "contribMenuBarHome", "contribViewsRemote", "contribViewsWelcome", "documentFiltersExclusive", "extensionRuntime", "fileSearchProvider", "quickPickSortByLabel", "workspaceTrust", "scmSelectedProvider", "scmValidation", "textSearchProvider", "timeline", "notebookEditor"],
        "ms-vscode.vscode-github-issue-notebooks": ["notebookEditor"],
        "tanhakabir.rest-book": ["notebookEditor"],
        "ms-vscode-remote.remote-wsl": ["resolvers", "contribViewsRemote", "telemetry"],
        "ms-vscode-remote.remote-ssh": ["resolvers", "terminalDataWriteEvent", "contribViewsRemote", "telemetry"],
        "ms-vscode-remote.remote-containers": ["resolvers", "workspaceTrust", "terminalDimensions", "contribViewsRemote"],
        "ms-vscode.js-debug-nightly": ["portsAttributes", "findTextInFiles", "workspaceTrust", "resolvers"],
        "ms-vscode.lsif-browser": ["documentFiltersExclusive"],
        "GitHub.vscode-pull-request-github": ["tokenInformation"],
        "GitHub.copilot": ["inlineCompletions", "textDocumentNotebook"],
        "GitHub.copilot-nightly": ["inlineCompletions", "textDocumentNotebook"],
        "GitHub.remotehub": ["contribRemoteHelp", "contribMenuBarHome", "contribViewsRemote", "contribViewsWelcome", "documentFiltersExclusive", "extensionRuntime", "fileSearchProvider", "quickPickSortByLabel", "workspaceTrust", "resolvers", "scmSelectedProvider", "scmValidation", "textSearchProvider", "timeline", "notebookEditor"],
        "GitHub.remotehub-insiders": ["contribRemoteHelp", "contribMenuBarHome", "contribViewsRemote", "contribViewsWelcome", "documentFiltersExclusive", "extensionRuntime", "fileSearchProvider", "quickPickSortByLabel", "workspaceTrust", "resolvers", "scmSelectedProvider", "scmValidation", "textSearchProvider", "timeline", "notebookEditor"],
        "ms-python.gather": ["notebookEditor", "notebookCellExecutionState"],
        "ms-python.vscode-pylance": ["notebookDocumentEvents", "notebookEditor", "notebookCellExecutionState"],
        "ms-toolsai.jupyter": ["notebookConcatTextDocument", "notebookControllerKind", "notebookDebugOptions", "notebookDeprecated", "notebookEditor", "notebookDocumentEvents", "notebookEditorDecorationType", "notebookEditorEdit", "notebookMessaging", "notebookMime", "notebookCellExecutionState", "portsAttributes", "textDocumentNotebook", "quickPickSortByLabel"],
        "dbaeumer.vscode-eslint": ["tabs", "notebookDocumentEvents", "notebookEditor", "notebookCellExecutionState"],
        "ms-vscode.azure-sphere-tools-ui": ["resolvers"],
        "ms-azuretools.vscode-azureappservice": ["terminalDataWriteEvent"]
},

```

I think Codium's `product.json` has to be re-written.

**Comment by daiyam** [comment]
The upcoming `1.66.1` will have the missing extensions properties. I've tested with a `.ipynb` and has the expected buttons.

**Comment by nemonein** [comment]
Problem fixed on 1.66.1 (ArchLinux).
Thank you all!

**Comment by daiyam** [comment]
@ttronas Can you test with the new version? Thx

**Comment by ttronas** [comment]
It's working flawlessly! Thanks so much for fixing it that fast! 😊🎉🙏

**Comment by nemonein** [comment]
Reinstall Jupyter and Python extensions.

**Comment by ttronas** [comment]
Seems to be solved again through restart and/or reinstalling. Thanks again :)
