### ISSUE TITLE
Git extension does not work

### ISSUE THREAD

**Issue by istvnurbn** [VSCodium/vscodium#1037]
**Describe the bug**
Git extension gives the error messages that command "git.commit" cannot be found etc.

git is in my PATH also I've set the git.path parameter to pick up the homebrew version of git. I see the following log in the git console:

`> git rev-parse --git-dir
Opening repository for path='REDACTED' failed; ex=Error: Extension 'vscode.git' CANNOT use API proposal: scmValidation.
Its package.json#enabledApiProposals-property declares: [] but NOT scmValidation.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api vscode.git`

Visual Studio Code on the other hand picks up everything without any manual tuning, even with a fresh install.

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open a folder with a git repository
2. Make changes
3. Changes are not picked up (the sidebar does not show changes)
4. Click on 'Commit All' gives the error above.

**Expected behavior**
VSCodium should pick up changes in the repository and commit accordingly.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Architecture arm64
 - Version 12.3.1 (21E258)

**Additional context**
N/A

**Comment by daiyam** [comment]
@istvnurbn I will close it in favor of #1038. ;)
