### ISSUE TITLE
Windows Build Titlebar Icon

### ISSUE THREAD

**Issue by bentinata** [VSCodium/vscodium#104]
Titlebar icon is not the same as taskbar.

![image](https://user-images.githubusercontent.com/3183661/55677459-0209f080-5912-11e9-9ca1-38dd1f2c92f4.png)

Installed using [VSCodiumSetup-x64-1.33.0.exe](https://github.com/VSCodium/vscodium/releases/tag/1.33.0).

**Comment by stripedpajamas** [comment]
Good catch!! Thanks for reporting this @bentinata. I will investigate if MS changed how icons work in recent versions.

**Comment by stripedpajamas** [comment]
I've tracked down the places we missed when replacing the default icons -- there are 3 svg files pulled in by CSS in the app:
```
vscode/src/vs/workbench/contrib/update/electron-browser/media/code-icon.svg
vscode/src/vs/workbench/contrib/welcome/code-icon.svg
vscode/src/vs/workbench/browser/parts/titlebar/media/code-icon.svg
```

I'll open a PR to swap those out with the VSCodium icon.
