### ISSUE TITLE
Can't find some executables from /usr/bin

### ISSUE THREAD

**Issue by andrewlalis** [VSCodium/vscodium#1045]
**Describe the bug**
Within the bash terminal of VSCodium, I try to execute `dmd` which is an executable located in `/usr/bin`, but for some reason VSCodium doesn't think it exists.

**Please confirm that this problem is VSCodium-specific**
This is specific to VSCodium, because `ls /usr/bin | grep dmd` returns nothing, while in a normal terminal, it returns the executable that actually does exist there.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3 Cinnamon
 - Architecture x64
 - Version 1.66.0

**Comment by Olathuss** [comment]
I have the same problem and am also using Linux Mint, for some reason some executables don't work within the VSCodium terminal although they work perfectly fine in a normal terminal.

Normal terminal:
$ php --version
PHP 7.4.30 (cli) (built: Aug  1 2022 15:06:35) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.30, Copyright (c), by Zend Technologies
$ which php
/usr/bin/php


Inside VSCodium terminal:
$ php --version
bash: php: command not found
$ which php
which: no php in (/app/bin:/usr/bin:/home/XX/.var/app/com.vscodium.codium/data/node/bin:/home/XX/.var/app/com.vscodium.codium/data/cargo/bin:/home/XX/.var/app/com.vscodium.codium/data/python/bin:/home/XX/.var/app/com.vscodium.codium/data/gem/ruby/3.1.0/bin)

- OS: Linux Mint 21 Cinnamon
- Architecture x64
- Version 1.70.0

**Comment by paulcarroty** [comment]
`which: no php in (/app/bin:` it's flatpak, move this issue to flathub.
