### ISSUE TITLE
Never ending amount of subtabs in the Source Control tab

### ISSUE THREAD

**Issue by AceKiron** [VSCodium/vscodium#1048]
**Describe the bug**
The Source Control tab is filled with these subtabs that just continue appearing when scrolling down and I can't get rid of them

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Sorry, but unfortunately I have no idea how this happened, but restarting doesn't fix it.

**Expected behavior**
To have the regular source control tab that actually works:
![image](https://user-images.githubusercontent.com/39498818/163624914-04082d00-9853-466f-a967-fa9ea4e4fa16.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/39498818/163624517-b71bec65-10ca-4e86-9092-e963374515d9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Architecture: x64
 - OS Version: 21H2 (Build 19044.1645)
 - Git version: 2.32.0.windows.2

**Comment by daiyam** [comment]
This issue is being tracked at #1041.

You need to delete `~/.vscode-oss/extensions/vscode.git-*` until a definitive fix.
