### ISSUE TITLE
Certification verification failed in deb release

### ISSUE THREAD

**Issue by LONEWALKER01** [VSCodium/vscodium#1049]
I got this issue today while I was updating ppas in my Linux Mint 20.03. 
![2022-04-17_22-21](https://user-images.githubusercontent.com/86109244/163724591-fe010e6f-27fd-4cd4-9eed-614462dc6903.png)
![2022-04-17_22-25](https://user-images.githubusercontent.com/86109244/163724593-3fdd0725-c00f-434d-8699-c4e2a56dee77.png)

**Comment by orderzer0** [comment]
Looks like issue with CDN provider. When I go to https://download.vscodium.com/debs from my browser (Mozilla Firefox, 99.0), I have got this:
![image](https://user-images.githubusercontent.com/92581724/164010331-320724af-eea9-435d-b4a7-3a0e8bd72e74.png)

**Comment by LONEWALKER01** [comment]
Well, the issue is fixed, thanks devs. I am getting regular updates again.
