### ISSUE TITLE
Add hash digest

### ISSUE THREAD

**Issue by MaxdSre** [VSCodium/vscodium#105]
Would it be possible to add hash digest for release packages, such as sha256sum.

**Comment by stripedpajamas** [comment]
Hi @MaxdSre -- where would these digests live? In the notes associated with each release?

**Comment by asterizk** [comment]
Agreed, this would be nice, since (at least on the Mac side of things) the build isn't signed.

**Comment by asterizk** [comment]
> Hi @MaxdSre -- where would these digests live? In the notes associated with each release?

At least for me that would be perfectly fine (assuming release notes are controlled in someway against write access from the outside (I'm assuming changing them would require a PR))

**Comment by linsui** [comment]
How about a `SHA256.txt` in GitHub realease?

**Comment by borgstrom** [comment]
My preference would be that for each file that a build produces the build script should do a:

```
shasum -a 256 ${file} > ${file}.sha256
```

Then the `deploy` step in the travis file should just use `*.sha256` along with all the other files.

**Comment by stripedpajamas** [comment]
Sounds easy enough to implement 👍
