### ISSUE TITLE
confusing/duplicate release assets for macos

### ISSUE THREAD

**Issue by notEthan** [VSCodium/vscodium#1058]
looking for the latest release for mac, I see`VSCodium-darwin-x64-1.66.2.zip` (104MB) and `VSCodium.x64.1.66.2.dmg` (103MB). having no indication the difference between the two, I grab both. both contain a `VSCodium.app` -  still no apparent difference, so I compare the apps with a recursive diff. they seem to be identical. why are there two? 

this is mentioned in passing, but not addressed, in https://github.com/VSCodium/vscodium/issues/643

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**Comment by daiyam** [comment]
I might be crude but some users prefer a `.zip`, some others a `.dmg`. No differences in the app, just different packaging.

**Comment by notEthan** [comment]
could some explanatory text be added to the text accompanying the release? I think for most users the packaging does not matter but the ambiguity of having two options without anything to distinguish them is just confusing. at least it was for me.
