### ISSUE TITLE
Debian Repo 404

### ISSUE THREAD

**Issue by BrokenGabe** [VSCodium/vscodium#1059]
**Describe the bug**
Attempting to update vscodium via apt update and apt returns 
Ign:5 https://download.vscodium.com/debs vscodium InRelease                 
Err:6 https://download.vscodium.com/debs vscodium Release
  404  Not Found [IP: 185.93.1.246 443]
Reading package lists... Done
E: The repository 'https://download.vscodium.com/debs vscodium Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Please confirm that this problem is VSCodium-specific**
- [ ] 

**Please confirm that the issue/resolution isn't already documented**
- [ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to 'terminal'
2. Type 'sudo apt update'

**Expected behavior**
APT to complete update

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 11 "bullseye"
 - Architecture amd64
 - Version 

**Additional context**
Atempted to check the repo url directly and site returns 404.

**Comment by joan-aluja** [comment]
A similar issue also happens in Fedora

```download.vscodium.com                                                                         6.8 kB/s | 3.0 kB     00:00    
download.vscodium.com                                                                         9.5 kB/s | 3.1 kB     00:00    
download.vscodium.com                                                                         6.5 kB/s | 3.0 kB     00:00    
Errors during downloading metadata for repository 'gitlab.com_paulcarroty_vscodium_repo':
  - Status code: 404 for https://download.vscodium.com/rpms/repodata/repomd.xml.asc (IP: 185.93.2.241)
Error: Failed to download metadata for repo 'gitlab.com_paulcarroty_vscodium_repo': GPG verification is enabled, but GPG signature is not available. This may be an error or the repository does not support GPG verification: Status code: 404 for https://download.vscodium.com/rpms/repodata/repomd.xml.asc (IP: 185.93.2.241)
Ignoring repositories: gitlab.com_paulcarroty_vscodium_repo
Last metadata expiration check: 2:15:32 ago on Sat 23 Apr 2022 09:51:14 AM CEST.```

**Comment by silktown-software** [comment]
I am also having this issue.

![image](https://user-images.githubusercontent.com/76234339/164890346-4eb15c97-e555-46f0-8ad1-26ca0076c135.png)

**Comment by paulcarroty** [comment]
Fixed.

**Comment by azzamsa** [comment]
I still get the same issue

```shell
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following held packages will be changed:
  codium
The following packages will be upgraded:
  codium
1 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 84.3 MB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 https://download.vscodium.com/debs vscodium/main amd64 codium amd64 1.66.2-1649809017
  404  Not Found [IP: 212.102.43.81 443]
E: Failed to fetch https://download.vscodium.com/debs/pool/main/c/codium/codium_1.66.2-1649809017_amd64.deb  404  Not Found [IP: 212.102.43.81 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
