### ISSUE TITLE
Can't update VSCodium on CentOS 7 sytem

### ISSUE THREAD

**Issue by jleafey** [VSCodium/vscodium#1064]
When I try to update to the current release of VSCodium the package manager returns an errorabout the version of libstdcc++:

Error: Package: codium-1.66.2-1649809117.el7.x86_64 (gitlab.com_paulcarroty_vscodium_repo)
           Requires: libstdc++.so.6(CXXABI_1.3.9)(64bit)
Error: Package: codium-1.66.2-1649809117.el7.x86_64 (gitlab.com_paulcarroty_vscodium_repo)
           Requires: libstdc++.so.6(GLIBCXX_3.4.20)(64bit)
Error: Package: codium-1.66.2-1649809117.el7.x86_64 (gitlab.com_paulcarroty_vscodium_repo)
           Requires: libstdc++.so.6(CXXABI_1.3.8)(64bit)
Error: Package: codium-1.66.2-1649809117.el7.x86_64 (gitlab.com_paulcarroty_vscodium_repo)
           Requires: libstdc++.so.6(GLIBCXX_3.4.22)(64bit)
Error: Package: codium-1.66.2-1649809117.el7.x86_64 (gitlab.com_paulcarroty_vscodium_repo)
           Requires: libstdc++.so.6(GLIBCXX_3.4.21)(64bit)

The system is running CentOS 7 with all current updates.  The running version of VSCodium is 1.65.2 from the paulcarroty repo, the version of libstdc++ is 4.8.5.

Note that I started getting a similar error some time back with VSCode, which is one of the reasons I switched to VSCodium.

**Comment by paulcarroty** [comment]
#1043

> Fixed in VSC insiders, will be available in next (v1.67) release.
