### ISSUE TITLE
'Auto Closing Quotes/Brackets: always' not working

### ISSUE THREAD

**Issue by cyclonejet** [VSCodium/vscodium#1065]
**Describe the bug**
editor.autoClosingQuotes: always
editor.autoClosingBrackets: always

Both of them doesn't work. At the ending quotes/brackets, instead of closing the current ending quotes/brackets, the editor creates new one. This didn't happen in previous install (I don't know which version that was).

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Set editor.autoClosingBrackets and editor.autoClosingQuotes to always in settings
2. Move your insert cursor to somewhere like this
```
'react|'                      // the pipe indicates the cursor
```
3. Press " ' "
4. It creates new set of quotes like this
```
'react'|''
```

**Expected behavior**
After Step 3 above, this should happen like in previous builds:
```
'react'|
```

**Info**
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-13T00:16:29.523Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.10.109-1-MANJARO

**Comment by daiyam** [comment]
What's your language? Can you reproduce it on https://vscode.dev/ or Visual Studio Code?

**Comment by cyclonejet** [comment]
@daiyam JavaScript

Yes, I can't reproduce in the site you linked. I don't even have to set the mentioned configs to 'always'. Oppositely, I had to set the given configs to 'always' when the default settings seemed to work on vscode.dev

**Comment by daiyam** [comment]
I can't reproduce the issue.

**Comment by cyclonejet** [comment]
"editor.autoClosingOvertype": "always"

This worked
