### ISSUE TITLE
Codium set itself as my file manager.

### ISSUE THREAD

**Issue by pluc** [VSCodium/vscodium#1078]
**Describe the bug**
`xdg-open .` opens Codium. It's not my file manager, it should not open Codium when trying to open inode/directory.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Using Codium 1.67.0 on Debian x64, I didn't do anything beyond updating through the package manager.

```
pluc@hq:/usr/share/applications$ cat mimeinfo.cache  | grep inode
inode/directory=codium.desktop;org.gnome.Nautilus.desktop;org.gnome.baobab.desktop;thunar.desktop;
```

**Expected behavior**
Codium should not mess with my settings and set itself as a file manager of all things.

**Desktop (please complete the following information):**
 - OS: Debian bookworm
 - Architecture x64
 - Version 1.67.0

**Comment by daiyam** [comment]
It's a known issue that can't be fixed by VSCodium. To know more and fix it, please read: https://github.com/VSCodium/vscodium/blob/master/DOCS.md#file-manager
