### ISSUE TITLE
Installed Files have date 12/31/1979

### ISSUE THREAD

**Issue by trolley78** [VSCodium/vscodium#1080]
When I installed the latest version of VS Codium on Linux Mint 20.3, the files have a date of 12/31/1979.

I have a concern that there is a virus in the install package.

Trolley78

**Comment by daiyam** [comment]
No, it's known bug. I have to fix it...

**Comment by trolley78** [comment]
Thank you for your quick response.

Trolley78

**Comment by daiyam** [comment]
I will keep the issue so I can keep track.

**Comment by hilary** [comment]
When I install extensions in the latest version of VS Codium on Ubuntu 20.4, the "released on" and "last updated" dates show as "Invalid Date" once installed. Is this a symptom of the same bug, or should I file a separate issue? I'm replicating my VS Code setup, so I'm confident it's a Codium issue.

**Comment by daiyam** [comment]
@hilary It's a separate issue. Could you indicate the extensions? Thx
