### ISSUE TITLE
How to migrate from Visual Studio Code to VSCodium⁉︎

### ISSUE THREAD

**Issue by Skeeve** [VSCodium/vscodium#109]
I'm so glad a colleague pointed me to VSCodium.

However I was already using VSC for about 6 month so it was already tweaked with extensions.

This is how I tried to copy over all extensions and settings on my Mac.

Is it correct? Are there better ways?

```shell
cd $HOME
rm -rf .vscode-oss
cp -r .vscode .vscode-oss
rm -rf 'Library/Application Support/VSCodium'
mkdir -p 'Library/Application Support/VSCodium'
( cd 'Library/Application Support/Code'
  find . -type f |
  tar cBpf - -T - \
    --exclude ./Cache/\* \
    --exclude ./logs/\* \
    --exclude ./CachedData/\* \
    --exclude ./GPUCache/\* \
    --exclude ./CachedExtensions/\*
) |
( cd 'Library/Application Support/VSCodium'
  tar xvBpf -
)
```

**Comment by cbluth** [comment]
https://github.com/VSCodium/vscodium/blob/a02839b466d8d01b8a61ea9611f0b74039538eae/DOCS.md#migrating-from-visual-studio-code-to-vscodium

**Comment by Skeeve** [comment]
Didn't find what you linked to. Thanks for that.

So I did (a bit more than) what is required.

**Comment by stripedpajamas** [comment]
Thanks for using VSCodium @Skeeve 😊

I've also seen some people use the `code-settings-sync` extension to accomplish the same thing. 

If you have any ideas about how to make that Docs page more visible to new users let me know! One idea I just had is to make a GH Issue Template. That way when someone makes a new issue there could be a checkbox in the body of the issue for "My issue is not documented in the Docs page (link)".

**Comment by Skeeve** [comment]
Maybe put it into the README.md? As last point under Download/Install or maybe as a separate point at the end.

**Comment by edouard-lopez** [comment]
Pinning this issue on top of the issues list would make it more visible

**Comment by C-Duv** [comment]
A fews weeks ago, the migration procedure was available at https://vscodium.com/#migrate but it's not anymore.
Thanks _cbluth_ for the direct pointer to the documentation.

**Comment by karlingen** [comment]
```bash
# Copy all extensions
cp -R ~/.vscode/extensions ~/.vscode-oss/

# Copy keybindings.json and settings.json files
cp ~/Library/Application\ Support/Code/User/keybindings.json ~/Library/Application\ Support/VSCodium/User
cp ~/Library/Application\ Support/Code/User/settings.json ~/Library/Application\ Support/VSCodium/User
```

You're welcome 😺

**Comment by hulous** [comment]
> ```shell
> # Copy all extensions
> cp -R ~/.vscode/extensions ~/.vscode-oss/
> 
> # Copy keybindings.json and settings.json files
> cp ~/Library/Application\ Support/Code/User/keybindings.json ~/Library/Application\ Support/VSCodium/User
> cp ~/Library/Application\ Support/Code/User/settings.json ~/Library/Application\ Support/VSCodium/User
> ```
> 
> You're welcome smiley_cat

For linux this is similar, only little path changes for `settings.json` and `keybinding.json`:
```shell
# Copy all extensions
cp -R ~/.vscode/extensions ~/.vscode-oss/

# Copy keybindings.json and settings.json files
cp ~/.config/Code/User/settings.json ~/.config/VSCodium/User/settings.json
cp ~/.config/Code/User/keybindings.json ~/.config/VSCodium/User/keybindings.json
```
thx :wink:
