### ISSUE TITLE
Vscodium starts unkown org.bluez service via systemd?

### ISSUE THREAD

**Issue by vwas2** [VSCodium/vscodium#1091]
While skimming the journalctl  deb11 & starting the latest codium.deb release (1.67.2 c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5 x64) i found:

```
Ma...2:49 tp1 dbus-daemon[702]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service' requested by ':1.383' (uid=1000 pid=58826 comm="/usr/share/codium/codium --ms-enable-electron-run-")
Ma..2:49 tp1 systemd[1]: Condition check resulted in Bluetooth service being skipped.

Ma..14 tp1 dbus-daemon[702]: [system] Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)
```
Why is codium checking connectivity like that?

**Comment by daiyam** [comment]
It's an Electron issue: https://github.com/electron/electron/blob/22ae945311a96080b83566f40c8576b700ee339a/shell/browser/electron_browser_main_parts.cc#L482-L484
