### ISSUE TITLE
VSCodium apparently ignores product.json

### ISSUE THREAD

**Issue by Udinanon** [VSCodium/vscodium#1096]
Issue Type: <b>Bug</b>

I wanted to install some extensions, i search "Shaders" and nothing relevant comes out
I check on the webpage of the Microsoft extension store, adn they exist
What VSCodium returns is what OVSX shows, not what the Microsoft store returns
But i already edited my product.json to search the store and not OVSX.
I checked it, restarted the program multiple times, also as an administrator and restarted the machine
Is it ignoring the json file? Why?

VS Code version: VSCodium 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-19T00:47:04.590Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (12.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
git-graph|mhu|1.30.0
python|ms-|2022.6.2
vscode-pylance|ms-|2022.4.0
jupyter|ms-|2022.5.1001290443
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
markdown-preview-enhanced|shd|0.6.3

</details>

**Comment by daiyam** [comment]
Have you followed: https://github.com/VSCodium/vscodium/blob/master/DOCS.md#howto-vscode-marketplace

**Comment by Udinanon** [comment]
Yes, i checked the `product.json` file multiple times

**Comment by nocturnalmc** [comment]
> Yes, i checked the `product.json` file multiple times

Where did you place your product.json file?

**Comment by Udinanon** [comment]
The file is located in `%APPDATA%\VSCodium`, same as all my other windows machines, but this is the only case where this issue comes up.

**Comment by Udinanon** [comment]
This apparently a fault on my part, with a typo of the coma between the `extension gallery` and the approved experimental apis makes only these last ones work, while the extension gallery is silently ignored, and after reinstalling, cleaning the cache and noticing the typo it seems to work correctly
