### ISSUE TITLE
Gentoo package

### ISSUE THREAD

**Issue by wolviecb** [VSCodium/vscodium#111]
**Describe the bug**
Sorry this is not exactly a bug, I've created a Gentoo ebuild for the x64 binaries the I do use on my overlay (gentoo specific terms just in case someone is wandering), so fell free to checkout/link/whatever :)
You can find the ebuild [here](https://github.com/wolviecb/overlay/tree/master/app-editors/vscodium)

Again sorry for the non-issue issue

**Comment by stripedpajamas** [comment]
Cool @wolviecb 👍 👍 👍

I don't really understand overlays but it wouldn't hurt to put a link to your ebuild on the Docs.md page. PRs welcome.
