### ISSUE TITLE
Command line flags.conf file equivalent

### ISSUE THREAD

**Issue by jurisbu** [VSCodium/vscodium#1114]
**Describe the bug**
There seems to be no config file that VSCodium would read to get a default set of commandline flags. FOr instance Chromium supports setting custom commandline flags in `.config/chromium-flags.conf`. It also seems that VSCode does the same with `.config/code-flags.conf`. Also VSCodium does not read `.config/electron-flags.conf`.

Is there any mechanism supported to provide default commandline flags in config file?

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Architecture amd64
 - Version 
 - Version: 1.67.2

**Additional context**

**Comment by daiyam** [comment]
The support of `.config/code-flags.conf` has been added directly into the AUR (https://aur.archlinux.org/cgit/aur.git/commit/?h=visual-studio-code-bin&id=a0595836467bb205fcabb7e6d44ad7da82b29ed2).
So it isn't directly supported by VSCode...

**Comment by jurisbu** [comment]
@daiyam OK, thanks for clarification.

Still, I think it would make sense to expose some way to provide default flag set either via config file or environment variable. Otherwise one is left with mangling `.desktop` files or creating own wrapper script.

**Comment by daiyam** [comment]
You could make a PR 😉

**Comment by jurisbu** [comment]
So be it.

**Comment by arjunnnnnnn** [comment]
Any updates on this issue? Has a PR been made?

For me, VSCodium doesn't seem to read `code-flags.conf` or `electron-flags.conf`

**Comment by a-priestley** [comment]
> Any updates on this issue? Has a PR been made?
> 
> For me, VSCodium doesn't seem to read `code-flags.conf` or `electron-flags.conf`

Still looks like a solution has not been merged but for the time being I'm editing the [Desktop Files](https://wiki.archlinux.org/title/Desktop_entries) for Codium.

```desktop
[Desktop Entry]
Name=VSCodium
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/opt/vscodium-bin/bin/codium --enable-features=UseOzonePlatform --ozone-platform=wayland --no-sandbox --unity-launch %F
Icon=vscodium
Type=Application
StartupNotify=true
StartupWMClass=VSCodium
Categories=Utility;Development;IDE;
MimeType=text/plain;inode/directory;
Actions=new-empty-window;
Keywords=vscode;

X-Desktop-File-Install-Version=0.26

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/opt/vscodium-bin/bin/codium --enable-features=UseOzonePlatform --ozone-platform=wayland --no-sandbox --new-window %F
Icon=vscodium
```
