### ISSUE TITLE
Not able to install on Linux with Homebrew

### ISSUE THREAD

**Issue by aphive** [VSCodium/vscodium#1121]
I have brew installed on my Ubuntu laptop and trying to install with brew I get this error:

```
❯ brew install --cask vscodium
Error: Cask 'vscodium' is unavailable: No Cask with this name exists.
```

Have tried without the `--cask` as well and same error.

I can install with normal apt but I'd prefer to manage it with brew if I can. No issues if this is expected however.

**Comment by paulcarroty** [comment]
Ask here: https://github.com/Homebrew/brew/issues
