### ISSUE TITLE
Ability to open binary files

### ISSUE THREAD

**Issue by johans3** [VSCodium/vscodium#1124]
**Describe the bug**
we can install many nice extensions, but cannot open binary files. 
Example the Applescript extension for Mac. I suggested a workaround to open binary files as tmp - text documents that could be saved back to the original binary file, but the author wants to open binary files at all cost. This is what i call meaningless perfectionism and feels very annoying. So i am asking here if you could implement that feature to open binary files to prevent the cant-open-binary-file dialog 

**Please confirm that this problem is VSCodium-specific**
this issue is present both on VSCode and VSCodium

**Please confirm that the issue/resolution isn't already documented**
no results 

**To Reproduce**
just try to open a "scpt" file - Applescript on Mac - you can, but the result is a mess

**Expected behavior**
extensions should be able to read binary files so we can work with such files too

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Architecture x64
 - Version 10.14.6

**Additional context**

**Comment by daiyam** [comment]
https://open-vsx.org/extension/idleberg/applescript

**Comment by johans3** [comment]
> https://open-vsx.org/extension/idleberg/applescript

this does not answer nor satisfy my report about binary files. 
i was talking about that extension to make an example as well. Why should i need a link for it?
And yes, i also use that extension  too

The team of VSCodium can cook its own soup too, like, add support for binary files
