### ISSUE TITLE
Using Codespaces in/via VSCodium

### ISSUE THREAD

**Issue by yashpalgoyal1304** [VSCodium/vscodium#1126]
### Describe the bug
Unable to open Github Codespaces in VSCodium

### Check list
Please confirm that this problem is:
- [ ] VSCodium-specific
This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
I cant confirm this as i dont use VS Code, but i am 95% sure of this.

- [x] Not already documented
I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

### Details
**To Reproduce**
1. Open any Github codespaces that you have access to
2. Click on the "Application Menu" (hamburger icon) on the "Activity Bar"
(visible only when "Menu Bar" is not visible)
3. See the button of "Open in VS Code"

**Expected behavior:**
Some way to open it in VSCode is there. Which currently, seems none or unknown.

### Screenshots
<img src="https://user-images.githubusercontent.com/19423063/173871148-9d2f4ba7-1335-455b-abc1-e8d5f510fc53.png" height=350>

### Desktop
 - OS: Win 10 20H2
 - Architecture: x64
 - Version: 1.64.2 f80445acd5a3dadef24aa209168452a3d97cc326

### Additional context
* Links for learning about Github Codespaces:
    * Github official Docs: https://docs.github.com/codespaces/overview (remove the "overview" --> docs homepage)
    * Feature page: https://github.com/features/codespaces#can-i-run-a-codespace-locally
    * Found on the internet: https://cs50.readthedocs.io/code/#using-vs-code-locally

* The extension required for this is : [github.codespaces](https://marketplace.visualstudio.com/items?itemName=github.codespaces) by Github which I have sideloaded in VSCodium

* I tried taking help of inspect element in web dev tools in the browser to maybe figure out the intent behind the button and proceed accordingly (as in https://github.com/VSCodium/vscodium/issues/933#issuecomment-993933198 ). But I was unable to find any intent or any useful information in this regard.

* Searching the youtube didn't fetch any results either, I think as Codespaces is an online thing - people generally dont try to open it on anything other than their browsers, and those that do, do so in VS Code which is probably dumb-straight enough to do.

**Comment by daiyam** [comment]
From the license of the Github Codespaces extension: `You may install and use any number of copies of the extension only with Visual Studio Code to connect to the Codespaces service. `.
Due to the limitation in the license, I don't think we can provide any support for the Codespaces unless an open source extension is developed.

If you have a `vscode://`, you can try to change it to `vscodium://`.

**Comment by yashpalgoyal1304** [comment]
> _You may install and use any number of copies of the extension only with Visual Studio Code to connect to the Codespaces service._

ohkay, well thanks a lot for pointing this out. at least i got a conclusive end now to move on.
