### ISSUE TITLE
VSCODIUM theme not available

### ISSUE THREAD

**Issue by CoderZ90** [VSCodium/vscodium#1127]
Is there material theme in vscodium ?

**Comment by K4rakara** [comment]
Check the standard vscode marketplace in your browser and download the .vsix file

**Comment by paulcarroty** [comment]
Yes: https://open-vsx.org/?search=material%20theme&category=&sortBy=relevance&sortOrder=desc

You can always submit a theme to open-vsx or install locally from VSC marketplace.
