### ISSUE TITLE
Extensions files

### ISSUE THREAD

**Issue by democraz20** [VSCodium/vscodium#1135]
Where do vscodium keeps the files for extensions? For example vscode stores them in the home directory

I'm trying to install monokai pro but it's not on the marketplace 
I tried looking for the .vsix file for it but cannot find that 

I thought I could just copy the files for it from vscode to vscodium if that works but I cannot find vscodium's folder 

Although, if someone has the link/file to the .vsix, sending it here would work also

**Comment by daiyam** [comment]
You will find the infos at https://github.com/VSCodium/vscodium/blob/master/DOCS.md#migrating-from-visual-studio-code-to-vscodium
