### ISSUE TITLE
[proposal] A less manual approach to managing the patch set.

### ISSUE THREAD

**Issue by xaberus** [VSCodium/vscodium#1137]
As documented in [#1136](https://github.com/VSCodium/vscodium/pull/1136) the managing the patch set right now involves a couple of manual steps. Some of them can be automated while others can potentially benefit from using the tooling provided by `git rebase`.

I have recycled a patch script from my other project to create a [script](https://gist.github.com/xaberus/2f4a9988e26d99bd4907782e282a3486) to manage the patch set.

The intended workflow is like this:
- Place the script in a directory where the vscode and vscodium trees are living (or specify the paths on the command line):
 ```
some-dir
    manage-patch-set.py
    vscodium/...
    vscode/...
```
- Run `python manage-patch-set.py -c <old commit> import -f` where `<old commit>` is a known good ref for which the path will apply without errors. This will create a shallow repository at `/tmp/vscode-patched` starting from the specified commit. Then the script will import each patch (from `vscodium/patches`) and create a corresponding commit for it.
- Go to the directory `/tmp/vscode-patched` where the temporary repository was created.
- Now run `git fetch <new-commit>` to add the new release commit to the temporary repository.
- Follow up with `git rebase <new-commit>` to rebase the patch set to the new  release. Follow the steps in [#1136](https://github.com/VSCodium/vscodium/pull/1136) to make sure the patches are working as you going through the rebase process.
- Run `python manage-patch-set.py -c <new commit> export` where ` <new commit>` is the new commit the patch set was rebased on to export the patch set back to the VSCodium.

Will this make working with the patch set easier? @daiyam What do you think?
If you are interested I will create a PR to add this script to the tree. Right now it only depends on `GitPython` and `python3`.

**Comment by paulcarroty** [comment]
I don't think we need to maintain Python code for task like this, also not sure about "easier" syntax like `python manage-patch-set.py -c <new commit> export`.

**Comment by xaberus** [comment]
@paulcarroty The easier part it that the patch set is regenerated automatically. You do not have to run `git diff` manually several times in a row to recreate the patches. (Assuming of course more than one changed.) And I guess I like using `git rebase` and `git bisect` because it frees my mind to concentrate on the code and not the patching process. This is mostly the argument why Linus decided to write Git...

As for `bash` vs `python`, this script is only for maintaining the patch set and not for CI. The build already depends on `python3`, so people have it installed anyway. I wrote it in `python` mostly because I can write much better quality python code than I can write `bash` code.

**Comment by daiyam** [comment]
@xaberus I find that your solution has also a lot of manual steps, a bit complex and might not work with Windows or remote repository (due to `/tmp/vscode-patched`)

I've made the script #1138 which I had in mind for some times...

**Comment by xaberus** [comment]
@paulcarroty, @daiyam, Feel free to close this, if it does not suit your work flows.
