### ISSUE TITLE
enabledApiProposals has no effect

### ISSUE THREAD

**Issue by acheong08** [VSCodium/vscodium#1141]
**Describe the bug**
I am trying to run GitHub copilot but it throws the error:
```
editor/inlineCompletions/actions is a proposed menu identifier. It requires 'package.json#enabledApiProposals: ["inlineCompletionsAdditions"]' and is only available when running out of dev or with the following command line switch: --enable-proposed-api GitHub.copilot
```
*Attempted fixes*
I ran `codium --enable-proposed-api GitHub.copilot`, the same error shows up

**Please confirm that this problem is VSCodium-specific**
- [ x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install GitHub copilot from .vsix
2. Run `codium --enable-proposed-api GitHub.copilot`
3. Go to extensions

**Expected behavior**
Run properly

**Desktop (please complete the following information):**
Codium:
1.68.1
30d9c6cd9483b2cc586687151bcbcd635f373630
x64
System:
OS: Ubuntu 22.04 LTS x86_64 
Host: MacBookPro15,2 1.0 
Kernel: 5.17.4-t2

**Comment by paulcarroty** [comment]
#1097
