### ISSUE TITLE
Please provide static url to download releases in programmatic way 

### ISSUE THREAD

**Issue by chukynax** [VSCodium/vscodium#1142]

**Comment by daiyam** [comment]
@chukynax You can use https://api.github.com/repos/VSCodium/vscodium/releases or https://api.github.com/repos/VSCodium/vscodium/tags
More info at https://docs.github.com/en/rest/repos

**Comment by chukynax** [comment]
Your making packages names with some hash, and its changing from release to release ... im already using releases link and parsing latest one and the i use grep to parse package name from html ... probably you could make releases names without any hash and only with versions, that would be cool
