### ISSUE TITLE
Pylance's semantic highlighting doesn't work properly on VSCodium

### ISSUE THREAD

**Issue by burritosoftware** [VSCodium/vscodium#1143]
**Describe the bug**
Whilst code completions and other features of Pylance seem to work correctly in VSCode, the semantic highlighting (where imports are highlighted amongst others) doesn't seem to function.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to a Python file with imports whilst using the Pylance language server.
2. Observe a difference between the same file with same setup on VSCode and VSCodium.

**Expected behavior**
Imports would be highlighted.

**Screenshots**
VSCodium:  
![image](https://user-images.githubusercontent.com/37681398/175858285-80e86757-16ee-42d3-a3b0-5d85c137618e.png)

VSCode:  
![image](https://user-images.githubusercontent.com/37681398/175858307-a7c914aa-fed3-4888-942f-dbb3460414b5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Architecture x64
 - Version 1.68.1

**Additional context**
N/A

**Comment by paulcarroty** [comment]
https://github.com/VSCodium/vscodium/pull/935

**Comment by burritosoftware** [comment]
> #935

I already tried this workaround and it doesn't seem to fix semantic highlighting. I can try one more time to be sure.
