### ISSUE TITLE
Authenticate with OAuth

### ISSUE THREAD

**Issue by rotu** [VSCodium/vscodium#1144]
When authenticating to GitHub, VSCodium prompts for a personal access token. This is suboptimal because:
1. It involves [additional manual steps](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#signin-github) to generate such a token
2. The token prompt does not provide enough guidance (e.g. the requested permissions aren't listed)

It would be nice if it supported the [OAuth Web Application Flow](https://docs.github.com/en/developers/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps) provided by GitHub.

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**Comment by softorangetech11** [comment]
> I did not intend to add the bug label and I don't know how to remove it

Hi,
A collaborator can attend to remove it. If you want, you can create a blank issue by clicking on "Open a Blank issue" on the side, and that will not create bug label in there.
The bug label is present because of the template VSCodium uses for issues.

**Comment by softorangetech11** [comment]
> > I did not intend to add the bug label and I don't know how to remove it
> 
> Hi, A collaborator can attend to remove the label. If you want, you can create a blank issue by clicking on "Open a Blank issue" on the side, and that will not create the label in there. The bug label is present because of the template VSCodium uses for issues.

UPDATE: I could repost this and you could edit this to close.

**Comment by tackynugget** [comment]
@rotu 
I ran into the same issue running VSCodium v1.68.1 and GitHub Pull Requests and Issues v0.46.1

I played around with it attempting to follow the principle of least privilege. I found the following permissions were sufficient for being able to update my repos:
- All repo permissions (repo:status, repo_deployment, public_repo, repo:invite, security_events)
- read:user
- user:email

It still threw the error when I pasted the Personal Access Token, BUT I noticed that my user icon in the left navigation indicated I was signed in.

I was able to sync and delete a test file to test functionality.

It's not great, but it works.

I'd be happy to provide logs @daiyam if it would help.

**Comment by daiyam** [comment]
@tackynugget Yes a log would be helpful

In https://github.com/VSCodium/vscodium/issues/1152#issuecomment-1209236938, I replied:
> With `read:user, repo, user:email, workflow`, the extension is connecting with any issues....

I have to test without `workflow` but it should work anyway

**Comment by tackynugget** [comment]
Ah. I didn't see your reply in #1152 @daiyam 
I'm still finding my way around VSCodium and want to make sure I get you the right log. I couldn't find any log export options, folders, or events in Event Viewer. Where should I go and how should I get it to you?

**Comment by daiyam** [comment]
menu `View`/`Output` then select `Github Auth...`

**Comment by tackynugget** [comment]
Thanks for that. I had no idea this was here.

I logged out and created a repo-only token and saw this error
>[Error  - 14:05:04.396] Error: The provided token does not match the requested scopes: read:user repo user:email workflow

I created a token with the requested scopes the error message and your #1152 comment referenced and it worked perfectly.

Re-reading this thread, however, I agree with @rotu that it would be great to have a better way to authenticate VSCodium to GitHub.

**Comment by daiyam** [comment]
I will add the correct scopes (`read:user repo user:email`) to an FAQ

If you can make a PR, it would be very welcome :wink:

**Comment by tackynugget** [comment]
Ah. I would if I could. 

I'm not sure how VSCodium was ported over from Visual Studio Code, but I would hope that mechanism could be replicated somehow. Would we be able to loop in the folks with the required skills? 

I'm happy to help any way I can, but I'm just an aspiring developer.

**Comment by kuwaitbinary** [comment]
I am not sure if it related to login in sourcegraph .. But I cannot log in using sourcegraph extension 


[](https://marketplace.visualstudio.com/items?itemName=sourcegraph.sourcegraph)
