### ISSUE TITLE
Markdown Viewer (Preview)

### ISSUE THREAD

**Issue by tomasdurham** [VSCodium/vscodium#1149]
# Description
I am using Markdown for my notes. For that I have one big text file. Right now: 3406 lines.

When I am using the preview-mode next to the editor, then it getting buggy. I see some weird texts that pops up, when I am writing or making headers. Mostly the same word is popping up or sometimes the icon for a missing picture. 
After the writing I need to refresh the viewer to have the exact view of my note. 
With time it becomes annoying. That's why I am writing this problem. 

Thanks for helping and hope I am not the only one with this problem. 

---

# Further information

CPUs | Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)
-- | --
GPU Status | 2d_canvas: unavailable_software canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: disabled_software multiple_raster_threads: enabled_on oop_rasterization: disabled_off opengl: disabled_off rasterization: disabled_software raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: disabled_software video_encode: disabled_software vulkan: disabled_off webgl: unavailable_software webgl2: unavailable_software
Load (avg) | 1, 1, 1
Memory (System) | 15.27GB (0.92GB free)
Process Argv | --ms-enable-electron-run-as-node --no-sandbox --unity-launch
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
todotxt-mode | dav | 1.4.25
dendron-markdown-shortcuts | den | 0.12.1
vscode-sshfs | Kel | 1.25.0
vscode-docker | ms- | 1.22.0
vscode-language-pack-de | MS- | 1.68.3
python | ms- | 2022.8.1
jupyter | ms- | 2022.5.1001610507
vscode-yaml | red | 1.8.0
code-spell-checker | str | 2.2.5
markdown-all-in-one | yzh | 3.5.0

And no experimental features.

**Comment by paulcarroty** [comment]
Does it work in VSCode?

**Comment by GitMensch** [comment]
There were a bunch of changes to the Markdown Preview in the last versions, see https://code.visualstudio.com/blogs/2022/08/16/markdown-language-server, so I suggest to:

* first update, then retry
* if it still happens: send a report to the appropriate markdown feature provider

As this is more than unlikely to be vscodium specific I'm closing this issue - but an update post would still be welcomed. In the unlikely case that this _is_ vscodium specific we can reopen this issue.
