### ISSUE TITLE
VSCodium asks for Location Services on macOS

### ISSUE THREAD

**Issue by nfam** [VSCodium/vscodium#1150]
As stated in the title, I wonder why VSCodium needs my location. And once I start VSCodium, some DNS requests show on my network monitor. Are those only for VSCodium and Plugin in Marketplace update checking? I am not sure if Telemetry is totally disabled. But it is still much better than VSCode which floods my network monitor with hundred or more DNS requests right after I open it.

 - OS: macOS 12.4 Monterey 
 - Architecture: x64
 - Version: 1.68.1
 
<img width="655" alt="location-services" src="https://user-images.githubusercontent.com/35899503/176852770-cab76dcb-6af2-4334-8693-33fc766b636c.png">
<img width="543" alt="dns-request" src="https://user-images.githubusercontent.com/35899503/176852817-79b548e7-e4dc-4f33-b277-a69b4fc48813.png">

**Comment by daiyam** [comment]
The telemetry is disabled in VSCodium but some extensions can include their own telemetry which we can't control.

`vscodium.vercel.app` and `vscodium.now.sh` are use by the update process.
`open-vsx.org` is use for the extensions.

**Comment by daiyam** [comment]
For the Location service, maybe, it's an electron thing, not sure. Even Theia Blueprint appears in my list...

**Comment by nfam** [comment]
Thank you for the information. Except for `vscodium.vercel.app`, `vscodium.now.sh`, and `open-vsx.org`; I guess I will block other domains.
