### ISSUE TITLE
Linux super user issue

### ISSUE THREAD

**Issue by Kbz-8** [VSCodium/vscodium#1151]
Hi, for an extension I need to run VScodium as super user on Linux (to enable an option) but when I do it with this command 
`sudo codium --no-sandbox --user-data-dir=~/` 
I just have a blank window. VScodium works perfectly when I run it as a normal user but does that when I run it with this command.

![image](https://user-images.githubusercontent.com/71275324/177010255-9786080a-d594-4242-8635-3534ffc683cb.png)

This command always worked but not anymore. 

(PS: I used Sublime text for a few months and I just switched back to VScodium and I can't remember which version it last worked on).

 - I'm on Ubuntu 20.04
 - x86_64
 - My VScodium is on 1.68.1

**Comment by paulcarroty** [comment]
Do VSC even support run from super user?

**Comment by Kbz-8** [comment]
It does yes

**Comment by corentinbettiol** [comment]
I used to have Neon Dream activated in the Synthwave 84' theme, but recently it's not working anymore. I can't re-enable it due to this bug, and I really love the text-shadow effect it gives :P

I try to launch it using this command (which worked before):

```bash
sudo codium --no-sandbox --user-data-dir="~/.config/VSCodium/"
```

Here's the content of the "about" infobox:

```
Version: 1.69.1
Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
Date: 2022-07-13T00:42:29.084Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.4.0-122-generic
```

**Comment by corentinbettiol** [comment]
I think the issue still occurs? I need to try to reinstall Synthwave 84' to confirm it.

**Comment by D3vil0p3r** [comment]
This issue affectes also me on Arch Linux.

**Comment by MasterMach50** [comment]
Issue affects me NixOS (Budgie Desktop)

**Comment by SadmanSyfe** [comment]
This issue is also affecting me.

OS:Endeavour OS

**Comment by Murazaki** [comment]
It takes a lot of time to build the config folder. Make sure you're to give a correct folder or it will screw up your home folder.

Another issue though : `sudo codium --no-sandbox --user-data-dir="~/.config/VSCodium/ file` does not open the file.

**Comment by corentinbettiol** [comment]
Still relevant.
