### ISSUE TITLE
github sign in

### ISSUE THREAD

**Issue by adirz** [VSCodium/vscodium#1152]
**Describe the bug**
Codium Version 1.68.1, I installed GitHub extensions (GitHub, GitHub Pull Requests and Issues, GitHub Authentication, copilot), and to use them I need to sign in. after adding the auth token, it doesn't log in' and doesn't show any error. Unlike most of those with login issues here, I don't even see a browser authorization (which for most issues I saw was the problem), just the personal auth token, and after pressing Enter, just nothing happens.
I saw issues `https://github.com/microsoft/vscode-pull-request-github/issues/1778` and `https://github.com/VSCodium/vscodium/issues/401` and the proposed solutions, but it is not the same, the issue is I can't see an issue.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.
- [ ] I saw issues `https://github.com/microsoft/vscode-pull-request-github/issues/1778` and `https://github.com/VSCodium/vscodium/issues/401` and the proposed solutions, but it is not the same, the issue is I can't see an issue.

**To Reproduce**
1. install github extension on vscodium
2. in github add personal auth token
3. in vscodium press on the icon as attached
4. in the prompt (as attached) file the auth token
5. press 'Enter'
6. nothing happens

**Expected behavior**

**Screenshots**
pressed on the icon, filled in the token, pressed enter
![github](https://user-images.githubusercontent.com/12210685/177581927-20091888-6e37-48a0-99c4-5a5ce5a64dc7.png)
![token](https://user-images.githubusercontent.com/12210685/177581933-8e24c5ca-9344-4eca-84f5-22b4fab73b90.png)

**Desktop :**
 - OS: Ubuntu 22.04
 - Architecture x64
 - Version 1.68.1

**Comment by Kazephil** [comment]
I have almost the same problem, except that in my case clicking the Accounts icon does nothing, and hovering over it shows me a "You are not signed into any accounts" message.

If I try the "Sign in" from the _GitHub Pull Requests and Issues extensions_, I get the dialog asking me to allow access, then the same GitHub Personal Access Token box as above (showing up in the same top middle area as the Command Palette). Entering the token and pressing enter brings up an "Error signing in to GitHub" ("Source: GitHub Pull Requests and Issues (Extension)") message at the bottom right of the screen with "Try again" and "Cancel" buttons.

None of the workarounds/fixes in related issues have worked, and I do have gnome keyring (and qtkeychain) installed.

System:
- OS: Arch Linux
- Architecture: x64
- Version: 1.69.1

**Comment by colingourlay** [comment]
Also experiencing this issue, including the error popup @Kazephil mentioned when trying the Sign In feature of the _GitHub Pull Requests and Issues_ extension. I'm on MacOS 12.4.

**Comment by snelling-a** [comment]
similar issue. tried the fix in #401, but i can't even get that far. there is no option to sign in

<img width="293" alt="Screenshot 2022-08-01 at 8 09 13" src="https://user-images.githubusercontent.com/72226000/182083125-02981d91-9419-45e6-aea0-b6cd5d7e2bfb.png">

**Comment by ZebulanStanphill** [comment]
I'm having similar issues. I'll try doing a `git push ...` in the terminal, then be prompted:

"The extension 'GitHub' wants to sign in using GitHub."

I choose "Allow", and I'm then prompted to enter a personal access token. I do so, and then I'm prompted for username, then password, and then it still fails. (I tried using both my email and my actual username in the username prompt.)

```
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/REPO_PATH'
```

**Comment by TriAttack238** [comment]
I'm having the same issue as ardiz when trying to log into on the left sidebar, as in literally nothing happens.

**Comment by daiyam** [comment]
Ok, what are the scopes given to the token?

With `read:user, repo, user:email, workflow`, the extension is connecting with any issues....

**Comment by TriAttack238** [comment]
I only did `repo`, as I was following the Readme instructions.

**Comment by Kazephil** [comment]
> Ok, what are the scopes given to the token?
> 
> With `read:user, repo, user:email, workflow`, the extension is connecting with any issues....

I finally got a chance to try this out.
Creating a new token with the above scopes worked for me.

Thanks!

**Comment by daiyam** [comment]
I will add the list (`read:user, repo, user:email`, only those should be necessary) to the prompt so it will be better...

**Comment by alechemy** [comment]
@daiyam FYI, I was having the same issue, and creating a PAT with only `read:user, repo, user:email` did not resolve it for me. I had to additionally add `workflow` to successfully log in.

**Comment by TriAttack238** [comment]
Sadly, it's still not working for Me

**Comment by TriAttack238** [comment]
Never mind, when I uninstalled the GitHub extension and used GitHub Pull Requests instead it now works.

**Comment by daiyam** [comment]
The requested scopes will be shown when the PAT is asked: `GitHub Personal Access Token (...scopes)`.
It will be available in the next release.

**Comment by colingourlay** [comment]
> The requested scopes will be shown when the PAT is asked: `GitHub Personal Access Token (...scopes)`.
> It will be available in the next release.

Thanks so much!
