### ISSUE TITLE
Weird Highlighting in integrated terminal

### ISSUE THREAD

**Issue by 2shaar2059** [VSCodium/vscodium#1175]
**Describe the bug**
Despite the find bar being blank in the integrated terminal, there is some random highlighting going on in

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Seems to happen randomly

**Expected behavior**
nothing should be highlighted if the search bar is blank

**Screenshots**
![image](https://user-images.githubusercontent.com/33207092/181863686-817831b4-a179-46cd-bc9f-781c39912419.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 (but the terminal is a launched docker container)
 - Architecture x64
 - Version ?
 - 
**Additional context**

**Comment by GitMensch** [comment]
Please specify version information (Menu Help->Info) and possibly consider updating vscodium.
Also: does this happen when you user a plain terminal and start gdb there, instead of a docker shell?
