### ISSUE TITLE
Names of go1.18 generic functions are not highlighted

### ISSUE THREAD

**Issue by telephrag** [VSCodium/vscodium#1176]
Issue Type: <b>Bug</b>

To reproduce try writing generic function with go1.18. For example, take a look at functions `Set()` and `GetData()` on screenshot bellow.
![Screenshot from 2022-08-01 18-06-31](https://user-images.githubusercontent.com/26183558/182167228-ad3d39d5-f178-40b1-ae2f-8b8229781645.png)

VS Code version: VSCodium 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-19T00:58:08.152Z)
OS version: Linux x64 5.18.10-100.fc35.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx (8 x 1995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.31GB (0.40GB free)|
|Process Argv|--ms-enable-electron-run-as-node --disable-extensions|
|Screen Reader|no|

|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled

**Comment by intact** [comment]
Default Textmate coloring do not support generics. You can try to enable [semantic tokens](https://github.com/golang/tools/blob/master/gopls/doc/settings.md#semantictokens-bool) for gopls.

**Comment by telephrag** [comment]
Didn't work, unfortunately.
