### ISSUE TITLE
Why is there no deb-package for version 1.70?

### ISSUE THREAD

**Issue by in-in** [VSCodium/vscodium#1177]
**Describe the bug**
There are deb-packages for the previous version 1.69.2, but not for 1.70.
![22217060914](https://user-images.githubusercontent.com/8797432/182994011-14c62794-b37b-44af-90a2-ec3a03195744.png)

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to https://github.com/VSCodium/vscodium/releases/tag/1.70.0
2. Search for `.deb`

**Expected behavior**
I was expecting to find a deb package.

**Comment by paulcarroty** [comment]
[1178](https://github.com/VSCodium/vscodium/issues/1178)
