### ISSUE TITLE
new Linux build dependencies in v1.70

### ISSUE THREAD

**Issue by paulcarroty** [VSCodium/vscodium#1178]
https://github.com/VSCodium/vscodium/runs/7683080192?check_suite_focus=true#step:13:1253

```
libc6 (>= 2.4)
libcups2 (>= 1.6.0)
libstdc++6 (>= 5)
```

**Comment by paulcarroty** [comment]
Time to drop Bionic-x64 (libc 2.27) and move to Alpine.

**Comment by daiyam** [comment]
@paulcarroty I've look at `/vscode/build/azure-pipelines/product-build.yml` and found out that:
- they are still building with Bionic (x64) or Stretch (arm)
- they publish the binaries from the Alpine image

So no migration to do even if it might have helped me for the issue in #1170...

**Comment by daiyam** [comment]
I've updated a patch which was fixing the same issue for rpm build. (#1180)

I'm waiting to complete #1170 (I've reverted to grep on armhf) to release the new version. It's fixing to the build time issue of 2 hours back to 20 min for linux or 40 min for windows...

**Comment by paulcarroty** [comment]
OK, hope downgrading the dependencies will not bring new bugs.
[Tried](https://github.com/VSCodium/vscode-linux-build-agent/pull/11) to update Alpine dockerfile, just in case.

**Comment by daiyam** [comment]
It's done
