### ISSUE TITLE
Missing donate button or Bitcoin address

### ISSUE THREAD

**Issue by MarkMura** [VSCodium/vscodium#118]
**Describe the bug**
You deserve some beer money for this. Let me send you some BTC

**Please confirm that this problem is VSCodium-specific**
- This bug absolutely doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- I checked the Readme, Help menu and Docs page and no Bitcoin address is mentioned there.

**To Reproduce**
1. Go to VSCodium github project
3. Scroll down to 'Donate Bitcoin'
4. See no 'Donate Bitcoin'

**Expected behavior**
Shut up and take my money

**Screenshots**
![shut-up-and-take-my-bitcoin](https://user-images.githubusercontent.com/43094396/56083914-acf73e80-5e2b-11e9-93de-331c4ba483e5.jpg)

**Desktop (please complete the following information):**
 - OS: any
 - Architecture: all
 - Version: every

**Additional context**
You made my day with this project

**Comment by sterlingbeason** [comment]
I feel so relieved this project exists and was happy to see a BTC address for donations. Can you accept Bitcoin Cash (BCH) donations to this address as well? If not, I'd be the first to donate with BCH to your new address. Cheers
