### ISSUE TITLE
VSCodium as Unity 3d C# Editor on Win10

### ISSUE THREAD

**Issue by zenhund74** [VSCodium/vscodium#1181]
Dear Forum members (sorry for calling this an Issue)

I'm pretty new to VSCodium on Windows, but it installed well using the Wget method in Windows Powershell.
I even found the path to the executable file : C:\Users\*yourusername*\AppData\Local\Programs\VSCodium
And I can choose that executable in Unity 3d under external editors, but the C# Scripts aren't opening.
I obviously miss out on the right arguments like: -n{line} -f{file}

Can anyone give me hint on how to fix this?

**Comment by GitMensch** [comment]
Not 100% sure what you're asking for, so I may answer something else...
I've searched for "vscode command line arguments" on the net, the first result pointed to https://code.visualstudio.com/docs/editor/command-line , it's very good first point was that you can execute the executable once with the `--help` option to see more information and it also has specific notes on files.

So I guess you search for something like `%LOCALAPPDATA%\Programs\VSCodium -n -w {file}:{line}`? (if the caller cannot resolve environment variables replace it with the appropriate path)

**Comment by robertwahler** [comment]
The VSCode Unity extension hard codes the editor names to `code.exe`, `code.cmd`, or `code.app`, among others. I tried symlinks and hard links to those, but the extension always resolves the link to the executable on macOS. The only thing that worked for me was to rename the entire bundle `VSCodium.app` to `Code.app`. I'm assuming a similar rename will work on Windows.

**Comment by GitMensch** [comment]
@robertwahler Can you please fill an upstream issue in the vscode unity extension for this (the editor name should at least be configurable)?

**Comment by robertwahler** [comment]
@GitMensch I'm afraid that Unity has given up on the extension. The version here on GitHub is out of date with the release version. This thread explains a bit https://forum.unity.com/threads/update-on-the-visual-studio-code-package.1302621/

Hopefully, someone will fork the extension and bring the code up to date or maybe Unity will rethink their current strategy...but I don't expect that to happen any time soon.

**Comment by daiyam** [comment]
> If you’re using VSCode, and you’ve experienced quality issues, we recommend that you switch to using an IDE that Microsoft is helping us provide support for, such as from Visual Studio Community. 

I'm not sure on how to read that paragraph...

**Comment by GitMensch** [comment]
Possible "translation": use the full blown Visual Studio (which for commercial use you'd need a paid license), we don't support vscode any more, now that our extension works in the fat IDE.

**Comment by tears-in-rain** [comment]
Windows 11. 
Unity 2021.3.25f1.

Version: 1.78.2 (system setup)
Release: 23132

**Solution**

Clean:
select codium exe, and change "Editor args" to `"$(ProjectPath)" -g "$(File)":$(Line):$(Column)`

![image](https://github.com/VSCodium/vscodium/assets/113452664/e53fd907-2258-4e81-bd17-afa39e87e74c)

Dirt:
just copy and rename it to `code.exe` file, then select it in unity.
![image](https://github.com/VSCodium/vscodium/assets/113452664/0c59ecd2-f72b-430f-8b1a-9a6d776d37b4)

@daiyam, suppose issue could be marked as "solved"
