### ISSUE TITLE
No view is registered with id: <extension id> with `github.vscode-pull-request-github` enabled

### ISSUE THREAD

**Issue by manuth** [VSCodium/vscodium#1184]
**Describe the bug**
When starting VSCodium, I'm getting flooded with errors in the notification area which state the following:

`No view is registered with id: <extension id>`

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install `GitHub.vscode-pull-request-github`
2. Make sure you have extensions installed which provide custom views - some of the extensions causing errors include:
    - `eamodio.gitlens`
    - `streetsidesoftware.code-spell-checker`
    - `GitHub.vscode-pull-request-github`
    - `hbenl.vscode-test-explorer`
    - `mtxr.sqltools`
2. Open up VSCodium (you might have to restart VSCodium in order to trigger the issue)
3. Notice that there is a huge load of notifications concerning missing views

**Expected behavior**
The extensions should work properly

**Screenshots**
![image](https://user-images.githubusercontent.com/7085564/183307720-4eeed3ee-4da9-4eb1-9d85-f9c535631622.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Version 21H2
 - Architecture x64
 - Version 1.70.0

**Additional context**
You can work around this issue by either downgrading to `1.69.2` (thanks @Maykin-99) or by disabling the "GitHub Pull Requests and Issues" (`github.vscode-pull-request-github`) extension.

**Comment by Wizibeer** [comment]
I think I found those few you were looking for... LMK if I got it.

**Comment by Maykin-99** [comment]
Also happens on Linux.
A workaround is to downgrade to `1.69.2`.

**Comment by daiyam** [comment]
Have you tried with only GitLens? I can't reproduce the issue...

**Comment by manuth** [comment]
> Have you tried with only GitLens? I can't reproduce the issue...

I can confirm that it doesn't seem to happen with a fresh installation with nothing but GitLens installed.
I'll try to find out what's causing the error, then.

**Comment by manuth** [comment]
I just ran through an Extension Bisect and it looks like this issue is caused by `github.vscode-pull-request-github`.
However, it might be important to mention that this issue doesn't occur in Visual Studio Code.

**Comment by daiyam** [comment]
Ok! I'm planning to look into that extension for #1152. So I guess I will also look into this issue :wink:

**Comment by manuth** [comment]
Awesome! Thank you so much 😄

**Comment by daiyam** [comment]
Issue found, fix on the way. But the deployment would need to wait the next release...
