### ISSUE TITLE
Should this Microsoft online service be disabled by default?

### ISSUE THREAD

**Issue by Redsandro** [VSCodium/vscodium#1185]
Avid Atom user here, switching after discovering VSCodium is telemetry-free.

**Describe the bug**

In Settings, I encounter this (enabled) option:

![image](https://user-images.githubusercontent.com/1702193/183470370-050d4ef9-375e-4a5c-8a5c-5f66399ddb68.png)

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to Settings
2. Search for "natural"
3. See option enabled

**Expected behavior**

Any options that contact Microsoft services to be disabled by default.

**Desktop (please complete the following information):**
 - OS: Linux Mint 21 (i.e. Ubuntu 22.04)
 - Arch: x64
 - Version 1.70

**Additional context**

Am new here. Could be that I am misunderstanding the project.

**Comment by paulcarroty** [comment]
The natural language search backed by Bing, hard to call it telemetry. Can be disabled by default, but I can't get it working anyway 😱

**Comment by Redsandro** [comment]
Arguably one can search without knowing it's backed by Microsoft/Bing. Not too big of a deal (for me), as I disabled it now. A colleague "sold" me into moving from Atom to VSCodium by saying all possible telemetry avenues were disabled by default, and then I saw this, making me raise an eyebrow. But the README words it slightly milder than my colleague so I'm not sure if I should drop my eyebrow back to be level with the other one. I thought it might be helpful to share this observation.

**Comment by daiyam** [comment]
@Redsandro Extensions can also have telemetry... so you might want to use your firewall to filter the outgoing connections.

For the natural language search, it can be disabled by default.

**Comment by GitMensch** [comment]
> For the natural language search, it can be disabled by default.

It can, and the issue was "do we want to do this" (which possibly means some documentation for users to add this to their user config to enable it if needed) @stripedpajamas any thought about that?

**Comment by stripedpajamas** [comment]
I'm not sure where I land on this. What's the user experience of NLS disabled? Do we know what "search" is affected by the setting (extensions search, code search, etc.)? I don't see it as telemetry, but I do understand the sentiment that for anyone coming to VSCodium for telemetry/tracking reasons, this looks like a miss on our part. 

If the UX of NLS disabled is still a decently functioning search (I'm assuming it has nothing to do with searching code), then I'd certainly be in favor of disabling it by default and updating our docs to tell how to enable it for interested users.

**Comment by Redsandro** [comment]
> I do understand the sentiment that for anyone coming to VSCodium for telemetry/tracking reasons, this looks like a miss on our part.

Exactly. It was my understanding that VSCodium is configured to not send or leak any revealing data to Microsoft _by default_. Arguably I understood wrong and VSCodium exists to remove global telemetry, but in my opinion it would fit VSCodium's mission and reputation to extend this treatment to any and all transmission of data that can be used to profile user behavior (such as searches). 

Deviating slightly from this specific issue: In my personal opinion this includes everything, even a ping, because every contact reveals your IP address which is PII under CCPA and GDPR. It should always be your conscious choice to use such services or enable such options (opt-in), not something that happens without you knowing (opt-out).

> If the UX of NLS disabled is still a decently functioning search (I'm assuming it has nothing to do with searching code)

I'm skeptical that any developer actually [searches like this](https://code.visualstudio.com/blogs/2018/04/25/bing-settings-search), so I am tempted to think NLS is a poor excuse for sending your searches with your IP address to Bing. I do a lot of code and setting searches, and it works as expected without NLS.

**Comment by GitMensch** [comment]
🤣 yes, most of that is unlikely to be used by programmers, but the very last sample (typos) is actually useful.
Still, after knowing what this is about I'm all for disabling it by default.

... any volunteers?

**Comment by GitMensch** [comment]
Note: for myself vscodium is foremost a way to get vscode without any binary proprietary parts of Microsoft where it isn't clear at all what is happening, and a known way to actually build the vscode repo to something that works.
The "disabled telemetry by default" is quite nice, but that is something I actually _can_ disable by user settings.

@Redsandro: if you want a "silent" vscode then a firewall is likely the best solution, otherwise you will likely want to disable the extension provider [in our case open-vsx instead of the ms marketplace] (only installing/update manually) and the auto-update, too. And possibly check all extensions before use that they don't send anything without asking.
