### ISSUE TITLE
Wont install or uprade via Winget in terminal

### ISSUE THREAD

**Issue by SirTwsted** [VSCodium/vscodium#1188]
When using Winget to install VSCodium or upgrading VSCodium  the software stops in mid-install from installing for some odd reason,
through Winget, even though I tried several times.

It WILL download and recognizes the install as well as recognizes the upgrade,
it just wont complete in mid-install for some odd reason.
I am forced to manually download the software and manually install it. When I could have just used (winget upgrade vscodium)
via terminal in Windows 10.

Also I just noticed that its not digitally signed.  So microsoft is having a fit.
alerts as "Unknown publisher"
.

**Comment by daiyam** [comment]
Yeah! We don't have any certificates (for windows or macos)...

**Comment by daiyam** [comment]
@SirTwsted I've tried on Win10, I'm not getting any errors...

@vedantmgoyal2009 Do you have any feedback on this? Thx
