### ISSUE TITLE
Jupyter extension always reports "This file could potentially override an existing Python package and interfere with kernel execution, consider renaming it."

### ISSUE THREAD

**Issue by FantasqueX** [VSCodium/vscodium#1190]
**Describe the bug**
When I create a ".py" file whatever its name is e.g. "my_random.py", Jupyter will throw this error. I have tried to reproduce with code-oss in ArchLinux official repository, code-oss behaves well. I have also tried with a new created user, the warning still appears. So, the reason is not my user configuration. And Windows version of Vscodium works well. It's a problem specific to Linux.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. install the python extension
2. Create a python file with name "my_random.py"
3. The warning will appear.

**Expected behavior**
No warning.

**Screenshots**
![image](https://user-images.githubusercontent.com/46747123/184294005-f5f7394c-7c44-46b3-85be-3be37b71e343.png)

**Desktop (please complete the following information):**
 - OS: [ArchLinux]
 - Architecture [x64]
 - Version [1.70.1]

**Comment by Tiago-Minuzzi** [comment]
I'm facing the same issue. Also on Arch Linux, x64, version 1.70.1.

**Comment by dsagman** [comment]
I have the same problem, but it is occurring in code-oss for me. Just started happening recently.

**Comment by BenoitPerron** [comment]
Same here, 1.70.1 on Kubuntu 20.04

**Comment by dswarbrick** [comment]
Also just ran into this. As a workaround (since I don't need Jupyter support), I simply disabled the Jupyter extension. Now I can see my code again, instead of a giant mess of squiggly lines.

**Comment by presentformyfriends** [comment]
Same issue, 1.70.1 on Linux Mint 20.3

**Comment by grisu48** [comment]
Same issue, 1.70.2 on openSUSE Tumbleweed.

However you can ignore those errors by going to Problems, right click on one of the warnings and then select "Always ignore warnings about overriding Python packages":

![workaround](https://user-images.githubusercontent.com/1527829/185883049-ac61c8aa-c701-48e2-b5fe-3d0d89f89631.png)

**Comment by Sean-of-Van** [comment]
I had this issue. Updating the Jupyter extension to v2022.8.1002460559 resolved it for me.

**Comment by DavidPesticcio** [comment]
YMMMV: but, downgrading to previous version of Jupyter fixed the problem for me, so it look like it could well be an issue with Jupyter...

VSCodium: 1.70.2

Working OK:
  Jupyter: v2022.7.1001890528

NOT Working OK:
  Jupyter: v2022.8.1002170547
