### ISSUE TITLE
Can't write files in .var folder, even if I have enough permissions

### ISSUE THREAD

**Issue by Zughy** [VSCodium/vscodium#1194]
**Describe the bug**
I have files in `.var/app/net.minetest.Minetest` I can't overwrite. I've also run `chmod +w -R net.minetest.Minetest` and `+o:w` but it doesn't change anything

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium. (I don't really want to install that)

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install Minetest as flatpak
2. Download some mods
3. Try to edit them on vscodium

**Expected behavior**
Save the file

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS
 - Architecture: amd64
 - Version: 1.70.1

**Comment by daiyam** [comment]
> 4. See error

What's the error?

**Comment by paulcarroty** [comment]
Flatpak sandbox.
