### ISSUE TITLE
Custom Version Numbers Aren't Supported by Some Extensions

### ISSUE THREAD

**Issue by manuth** [VSCodium/vscodium#1199]
**Describe the bug**
The JSON Language Server isn't working and thus, no autocompletion is provided.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Update VSCodium to a custom version number (for example v1.70.22228)
2. Make sure the `JSON Language Server` output panel is visible
3. Open up a json file with autocompletion (for example a `tsconfig.json` file)
4. Take note that there is an error messsage in the output panel saying:
    ```
    No valid VS Code version detected. Version string is: 1.70.1.22228
    ```

**Expected behavior**
The `vscode.json-language-features` extension should run normally

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows
 - Architecture x64
 - Version 21H2

**Additional context**
Since `vscode.json-language-features` is a built-in extension, I don't really know how to handle this.
However, I thought it might be worth to create an issue concerning this matter.

**Comment by daiyam** [comment]
Damn!

**Comment by manuth** [comment]
True that 😂
Quite weird that the built-in JSON extension wouldn't use semver for comparing versions 😅

**Comment by daiyam** [comment]
`1.70.1.22228` isn't semver compatible but `1.70.1+22228` isn't compatible with rpm, deb or msi...

**Comment by albmar** [comment]
Same for rust-analyzer and ESLint like I mentioned in #1200 which a kind person should mark as duplicated. I started writing it when this issue haven't existed yet. Sorry for the circumstances.

**Comment by manuth** [comment]
> `1.70.1.22228` isn't semver compatible but `1.70.1+22228` isn't compatible with rpm, deb or msi...

Oooh that's fair... Ouch - fixing this sure will be puzzling 🥲
Thanks a ton for your effort

**Comment by daiyam** [comment]
At the issue, the version `1.70.1.22228` was given to vscode as one. Then when vscode was checking the version for extension matching, I was removing the release number.
But the issue is that some extensions are double checking the vscode version which was failing due to the release number.

Now, the version `1.70.1.22228` is given to vscode as the version `1.70.1` and release `22228` (a new attribute, only used in the about or issue pages)

PS: I was running the initial code for 10 months, and I hadn't found any issues...

**Comment by daiyam** [comment]
Normally, for Windows, the new version should be up in about 1 hour.

**Comment by daiyam** [comment]
For Linux, I need to test how the artifacts will be generated...

**Comment by daiyam** [comment]
The Windows version are up. Can you test?

**Comment by manuth** [comment]
> The Windows version are up. Can you test?

Thanks for the rapid fix 😄
I'll be able to give it a go in about 20min

**Comment by manuth** [comment]
@daiyam I have tested it now!
All extensions named in both issues (`vscode.json-language-features`, ESLint and rust-analyzer) are working now

Great job 😄

**Comment by gfsd3v** [comment]
@daiyam not working for linux I guess, getting this error on all extensions, could I do something to help?

![image](https://user-images.githubusercontent.com/36668882/184976608-9156a900-2519-4d79-97a1-bed73872ef5b.png)

**Comment by daiyam** [comment]
Yep, the linux versions have not been updated yet. I had trouble to compile it to check if things were ok. Should be up soon. Sorry.

**Comment by gfsd3v** [comment]
> Yep, the linux versions have not been updated yet. I had trouble to compile it to check if things were ok. Should be up soon. Sorry.

no worries, lmk when u need help testing :)

**Comment by daiyam** [comment]
@gfsd3v The update is available ;)

**Comment by Heliozoa** [comment]
I downloaded the latest release and the issue is fixed, but it seems like the snap didn't get updated.

**Comment by gfsd3v** [comment]
also can confirm that the new version it's working, but also didn't get the update on arch yet

**Comment by daiyam** [comment]
@Heliozoa Ya, I knew for snap but I was waiting for a new day since the new syntax allows only 1 new release per day ([MSI](https://docs.microsoft.com/en-us/windows/win32/msi/productversion) requires a number less than 65,535, cf [#1192](https://github.com/VSCodium/vscodium/pull/1192#issue-1338172859))
