### ISSUE TITLE
Extension rust-analyzer doesn't run due to failing version validation

### ISSUE THREAD

**Issue by albmar** [VSCodium/vscodium#1200]
**Describe the bug**
An error appears with the message: "Cannot activate rust-analyzer: No valid VS Code version detected. Version string is: 1.70.1.22228"

**Please confirm that this problem is VSCodium-specific**
- [x]  This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I searched for other existing issues and my issue is not mentioned there.

**To Reproduce**
1. Install the extension 'rust-analyzer' if not already installed
2. Open a rust project or create a new one by entering the command line `cargo new project-name`
3. Open a rust file (i.e. main.rs)

**Expected behavior**
The extension should start and run without problems.

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19044
 - Architecture x64
 - Version 1.70.1.22228
 - Version of rust-analyzer : v0.2.853

**Additional context**
The extension ESLint also has this problem. Maybe some others, too.

**Comment by daiyam** [comment]
@albmar sorry, I will fix ASAP

duplicate #1199
