### ISSUE TITLE
Version splitting seems to break extensions

### ISSUE THREAD

**Issue by matthme** [VSCodium/vscodium#1209]
**Describe the bug**
Rust-analyzer does not run in VSCodium version 1.70.1.22228 because it complains about an invalid version of VSCode.

**Please confirm that this problem is VSCodium-specific**
It only appeared after the last update of my VSCodium to 1.70.1.22228. The rust-analyzer works fine in VSCode and has worked fine up to my latest update in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
It seems to be very new and I haven't seen an issue about this yet.

**To Reproduce**
1. Open VSCodium of version 1.70.1.22228
2. If rust-analyzer is not installed yet install it.
3. rust-analyzer will complain about an invalid version of VSCode.

**Expected behavior**
I can continue using rust-analyzer within VSCodium as I could in earlier versions of VSCodium.

**Screenshots**
![image](https://user-images.githubusercontent.com/36768177/185057866-9709010e-9546-41d7-a387-7db7161dcd1b.png)

**Desktop (please complete the following information):**
Version: 1.70.1.22228
Commit: a077184e238e7601fb685cf83f41a2f7f2aad0d9
Date: 2022-08-16T12:48:20.778Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.15.0-46-generic snap

**Additional context**
It may have been introduced by this commit: 81d304fa373978f4bfc72ef08710ccdc0adca9d0
The version of rust-analyzer I am using is 8 months old so it cannot be caused by change of the rust-analyzer extension.

**Comment by daiyam** [comment]
`1.70.1.22229` is fixing the issue.

**Comment by daiyam** [comment]
I've just tested, the `1.70.1.22229` is available. Please update.

Sorry for the trouble.

**Comment by matthme** [comment]
Oh great! I just updated and it works :). Thanks you!
