### ISSUE TITLE
Flutter Plugin cannot find the Flutter SDK

### ISSUE THREAD

**Issue by dvilcode** [VSCodium/vscodium#1210]
Hello,
I have been updated my VsCodium to the last version:

> Version: 1.70.1.22228 (system setup)
> Commit: a077184e238e7601fb685cf83f41a2f7f2aad0d9
> Date: 2022-08-16T13:07:04.381Z
> Electron: 18.3.5
> Chromium: 100.0.4896.160
> Node.js: 16.13.2
> V8: 10.0.139.17-electron.0
> OS: Windows_NT x64 10.0.18363

and the Flutter plugin to `3.46.0`. But it seems like cannot find the Flutter SDK path anymore:

![Screenshot 2022-08-17 082517](https://user-images.githubusercontent.com/48808625/185154731-981d8a87-dbd7-456d-b940-8b7355bb5041.jpg)

I have the same setup on VsCode and It works.
Regards,

**Comment by GitMensch** [comment]
What is the output of the logs?
