### ISSUE TITLE
VScodium and Fortran files

### ISSUE THREAD

**Issue by angelog0** [VSCodium/vscodium#1215]
I Installed VSCodium on GNU/Linux Mint in portable mode from the tar.gz archive and tried to work with Fortran files (`.f90`) but VSCodium shows them always in `Plain text`. I Installed also the `code runner` extension but the `.f90` files are always in text mode.

When I click on `Plain Text` (bottom right) it displays many programming modes but not for Fortran.

On the web, I find [this](https://marketplace.visualstudio.com/items?itemName=Gimly81.fortran) but when I try to install it following the instructions, VSCodium shows Code Runner end OpenVMS extensions not the `Gimly81.fortran`...

I tried also to change `.f90` to `.f95`, `.f` etc. but they are all rendered in `Plain Text`...

**Comment by daiyam** [comment]
Use the `Download Extension` link on the page then `Extensions: Install from VSIX...` in VSCodium

**Comment by angelog0** [comment]
Thanks, now I was able to install that extension. Thank you!!!
