### ISSUE TITLE
Remove telemetry in "vscode-cpptools" extension.

### ISSUE THREAD

**Issue by DeveloperKev** [VSCodium/vscodium#1216]
Hi team,
it's been a year or so, i'm using vscodium. its good.
As a c++ coder, i'm in love with this extension: https://github.com/microsoft/vscode-cpptools
is there any possibility to completely remove telemetry from that? so, the extension repos could be made much broader.

**Comment by daiyam** [comment]
The best would be to fork the extension and remove the telemetry from it.

But the license is weird. It's a MIT but at the begin you can read:
```
Additional binary files may be downloaded at runtime after the initial installation; these are governed by the more restrictive proprietary license terms found at [RuntimeLicenses](https://github.com/microsoft/vscode-cpptools/blob/main/RuntimeLicenses).
```
RuntimeLicenses state:
```
All VS Marketplace extensions, including this C/C++ Extension for Visual Studio
Code, must also be used consistent with the VS Marketplace Terms of Use at
http://aka.ms/VSMarketplace-TOU
```
which exclude to run those files on VSCodium...

**Comment by daiyam** [comment]
In general, VSCodium do not remove/disable any telemetry found in an extension from the marketplace.
So yes, the telemetry still works for `vscode-cpptools` and use the lib `@vscode/extension-telemetry`.
A quick search for `sendTelemetry` in the source will indicate you the files to modify.

**Comment by pm4rcin** [comment]
> > In general, VSCodium do not remove/disable any telemetry found in an extension from the marketplace. So yes, the telemetry still works for `vscode-cpptools` and use the lib `@vscode/extension-telemetry`. A quick search for `sendTelemetry` in the source will indicate you the files to modify.
> 
> i did find a bunch of telemetry functions on extension source. I was curious if its possible to remove the telemetry lib from core (by modifying build jsons, then creating custom builds) as if it wasnt there. pls let me know.

Maybe [that repository](https://github.com/muhammadsammy/free-omnisharp-vscode) will help you understand how to to de-blob and remove telemetry because I think the situation is very similiar (the debugger is closed source). In here the debugger was replaced by samsung's MIT licensed one.
