### ISSUE TITLE
Markdown preview stopped showing images on 1.70.2

### ISSUE THREAD

**Issue by staticdev** [VSCodium/vscodium#1220]
**Describe the bug**
Markdown preview stopped showing PNG images.

It stopped working after latest update.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Same happens on VSCode based on 1.70.2, but as I understand VSCode is built on top of Codium so this normal to happen, right?**

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Create an MD file with the content (sorry Github is also not escaping properly the code):

# Test

```{image} name.png

```

2. Save as test.md
3. Click on preview button.

**Expected behavior**
Image show on preview.

**Screenshots**
![image](https://user-images.githubusercontent.com/1446633/187127550-bede6bde-59af-41a7-a511-e0af8938cf61.png)

**Desktop (please complete the following information):**
 - OS: Debian 11.3
 - Architecture x64
 - Version: 1.70.2

**Additional context**
I tried also adding the `All in one markdown` extension but made no difference.

**Comment by daiyam** [comment]
~~~
```(image) name.png
```
~~~

won't work with most markdown parsers. I don't know any which support that syntax.

**Comment by staticdev** [comment]
> ```
> ```(image) name.png
> ```
> ```
> 
> won't work with most markdown parsers. I don't know any which support that syntax.

I use myst_parser.. forgot to mention, this is relevant.

**Comment by daiyam** [comment]
So not the standard markdown...

You should use the extension MyST-Markdown bur it's not available on OpenVSX. You can download the extension from [the marketplace](https://marketplace.visualstudio.com/items?itemName=ExecutableBookProject.myst-highlight) and install it.

**Comment by staticdev** [comment]
@daiyam what is needed to have it on OpenVSX?

**Comment by daiyam** [comment]
Due to MS licensing, extensions from the Visual Studio marketplace should only run on Visual Studio Code or other MS products.
Since vscodium isn't a MS product, ...

**Comment by staticdev** [comment]
@daiyam but it has MIT license https://github.com/executablebooks/myst-vs-code

**Comment by daiyam** [comment]
I made a mistake, to be more precise vscodium isn't allowed to access the Visual Studio marketplace. So the license doesn't stop you to download the extension and install it in vscodium.
