### ISSUE TITLE
Remainder operator is not working

### ISSUE THREAD

**Issue by analistamarcio** [VSCodium/vscodium#1222]
Type: <b>Bug</b>

Hi there,
When I use the following commands into integrated terminal, I get an error message:
1) expr 99 % 3
or
2) echo $(( 99 % 3 ))

Kind regards,
Marcio Ferreira.

VS Code version: VSCodium 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-05T11:26:33.437Z)
OS version: Linux x64 4.18.0-372.19.1.el8_6.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD EPYC 7763 64-Core Processor (48 x 2767)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|377.63GB (326.87GB free)|
|Process Argv|--ms-enable-electron-run-as-node|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details>Extensions: none

**Comment by GitMensch** [comment]
I can copy+paste that in the internal terminal, press enter and get the expected "0" result...
You may want to try to update vscodium and if it still does not work provide the error message as text, possibly together with a screenshot.
