### ISSUE TITLE
VsCodium v1.71.0.22245 gets detected as a threat on Windows 10

### ISSUE THREAD

**Issue by Niv-Mizzet-lab** [VSCodium/vscodium#1232]
Hi, 
I updated vscodium today to 1.17.0 and now, everytime it starts, I get a notification from windows defender that a threat was neutralized.
Protection history shows this:
![Capture](https://user-images.githubusercontent.com/89451707/188320914-65752be4-734b-4705-884c-9c20fc8f87be.JPG)
It doesn't show an executable, it just says that it's blocked by the behaviour.

This happens with or without having third party plugins enabled. In order to troubleshoot I uninstalled vscodium and installed it again from [here](https://github.com/VSCodium/vscodium/releases/download/1.71.0.22245/VSCodium-x64-1.71.0.22245.msi)

Other than the notification it works as expected.

What should I do?

**Comment by timebotdon** [comment]
This is a worldwide issue affecting other apps that use electron.its a false positive by Microsoft's Windows defender.

https://www.bleepingcomputer.com/news/microsoft/microsoft-defender-falsely-detects-win32-hivezy-in-google-chrome-electron-apps/

**Comment by Niv-Mizzet-lab** [comment]
> This is a worldwide issue affecting other appa that uses electron. It's a false positive by Microsoft's Windows defender.
> 
> https://www.bleepingcomputer.com/news/microsoft/microsoft-defender-falsely-detects-win32-hivezy-in-google-chrome-electron-apps/

I was completely unaware of that, thank you very much.

**Comment by daiyam** [comment]
@timebotdon Thx
