### ISSUE TITLE
VSCodium wants to reinstall 1.71.0 update after every restart

### ISSUE THREAD

**Issue by brakhane** [VSCodium/vscodium#1233]
**Describe the bug**
Since the 1.71.0 update, whenever I open VSCodium, it asks me to install a new update. It's always 1.71.0, and it's been more than 2 restarts now.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
Sorry, I'm not going to install vscode, I use vscodium for a reason.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Click "Later" on the update prompt (not sure if that's necessary, but I remember I did it the first time and it might have triggered the bug)
2. Close all instances of VSCodium
3. Open a new instance of Codium
4. Click "Update now"
5. after the update is through, close all instances again
6. open a new instance

**Expected behavior**
The update prompt is not shown again

**Actual behavoir**
The update prompt is shown again

**Desktop (please complete the following information):**
 - OS: Win 10, 21H2 (19044.1889)
 - Architecture amd64
 - Version 1.71.0, commit 22245

I haven't tried completely uninstalling vscodium yet, as I'm afraid my settings will get reset, too. But if necessary, I can try it.

**Comment by daiyam** [comment]
@brakhane You can uninstall, you settings won't be reseted. But if you are worried, you can try https://open-vsx.org/extension/zokugun/sync-settings to backup them.

**Comment by brakhane** [comment]
So I gave uninstalling a try and noticed that I had two entries in the uninstall list, one for 1.70, one for 1.71, deleting the 1.70 also deleted the 1.71, so I guess it was something with my local installation, maybe I installed it with scoop as well as the MSI, who knows.

I can't reproduce it after reinstalling, so I'll close it. Should the problem reappear, I will reopen.

**Comment by daiyam** [comment]
The 2 uninstall entries are due to an oversight of mine when preparing the insider version... You can find more details at https://github.com/VSCodium/vscodium/issues/1227
