### ISSUE TITLE
Latest release 1.71.1.22256 missing amd64 DEB file

### ISSUE THREAD

**Issue by solarchemist** [VSCodium/vscodium#1248]
The latest stable release 1.71.1.22256 appears to be missing the amd64 DEB file (along with its checksums).
This is the case both via the web or via the Github API.

For comparison, previous releases did include this file.
Probably just a simple oversight? Thanks for all your work making an awesome editor!

**Desktop:**
 - OS: Ubuntu 22.04
 - Architecture x64
 - Version 1.71.1.22256

**Comment by daiyam** [comment]
An error has occurred in the build: https://github.com/VSCodium/vscodium/actions/runs/3047319477/jobs/4911176665

**Comment by daiyam** [comment]
I had to make a quick fix: https://github.com/VSCodium/vscodium/pull/1249 (It was working just a few hours ago)
