### ISSUE TITLE
Add-on badges don't work

### ISSUE THREAD

**Issue by JPabloLassala** [VSCodium/vscodium#125]
Here are the badges on VSCodium
![image](https://user-images.githubusercontent.com/13321697/56111655-29bf1100-5f2f-11e9-8605-cdf206c05053.png)

While here are the same badges on VSCode
![image](https://user-images.githubusercontent.com/13321697/56111643-190e9b00-5f2f-11e9-82ec-107f4a063c78.png)

(I call it badges because the VSCode site uses that name)
It's just a detail, but I found nothing after a search so I thought it doesn't hurt to list it.

**Comment by ealap** [comment]
I have the same issue. I think this has something to do VSCode's restriction on viewing SVG in markdown files.

**Comment by Golotvinov** [comment]
Same problem here.

**VSCodium version: 1.33**

![Screenshot_1](https://user-images.githubusercontent.com/39648288/57164060-3aa6c800-6df3-11e9-8907-9fdb13151258.png)

Seems to be the case in every extension that uses the shields.

**Comment by stripedpajamas** [comment]
I found the problem -- MS only renders badges from "allowed" domains. The allowed domains list is specified in the product.json file, but we are not currently populating that field. When I add the below to my local product.json file, the badges render properly. We will need to update `build.sh` to add this field to product.json pre-build.

```
"extensionAllowedBadgeProviders": ["api.bintray.com", "api.travis-ci.com", "api.travis-ci.org", "app.fossa.io", "badge.fury.io", "badge.waffle.io", "badgen.net", "badges.frapsoft.com", "badges.gitter.im", "badges.greenkeeper.io", "cdn.travis-ci.com", "cdn.travis-ci.org", "ci.appveyor.com", "circleci.com", "cla.opensource.microsoft.com", "codacy.com", "codeclimate.com", "codecov.io", "coveralls.io", "david-dm.org", "deepscan.io", "dev.azure.com", "flat.badgen.net", "gemnasium.com", "githost.io", "gitlab.com", "godoc.org", "goreportcard.com", "img.shields.io", "isitmaintained.com", "marketplace.visualstudio.com", "nodesecurity.io", "opencollective.com", "snyk.io", "travis-ci.com", "travis-ci.org", "visualstudio.com", "vsmarketplacebadge.apphb.com", "www.bithound.io", "www.versioneye.com"]
```
