### ISSUE TITLE
Insane FTP activity

### ISSUE THREAD

**Issue by mapsedge** [VSCodium/vscodium#1250]
**Describe the bug**
Using PCManFM-QT and Codium to work against my FTP server, once a connection is made with a javascript file, the ftp activity increases greatly, sending the CWD command over and over and over up to 20 times a second. It's looking for node_modules, tsconfig.json, jsconfig.js; the ftp server returns 550 File not found.

Using Dolphin, Thunar, or Krusader (nethogs = kioslave5) the ftp activity is normal. Why use PCManFM-QT, then? Because it doesn't prompt to save, then to overwrite. All the other file managers do.

I have run VSCodium with all plugins disabled (there's only one) and sync off. That didn't help.

Kate, KWrite, gedit, and Bluefish do not have this issue with any file manager.

The issue appears to be exclusively when using PCManFM or PCManFM-QT with VSCodium.

**Please confirm that this problem is VSCodium-specific**
- [ ? ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

I don't use Microsoft's Visual Studio Code.

**Please confirm that the issue/resolution isn't already documented**
- [ x ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open an FTP session using PCManFM-QT.
2. Open a .js file from the remote server in VSCodium.
3. Watch server activity on the FTP server.

**Expected behavior**
 Not this. Save the file and stop.

**Screenshots**
![Screenshot_20220914_150446](https://user-images.githubusercontent.com/41483625/190251810-dced4250-d4cd-421c-bffc-c19306d84eca.png)

**Desktop (please complete the following information):**
Operating System: Ubuntu Studio 22.04
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-46-lowlatency (64-bit)
VSCodium: every version for the last year or so, including the most current.

**Additional context**
I am able to stop this happening on the .deb installation by renaming the node_modules folder in /usr/share/codium/resources/app/extensions to [something else], but doing so I lose javascript formatting.

**Comment by daiyam** [comment]
I'm not surprised. Have you tried FTP extensions to access to your server? Maybe they will limit the requests. Or maybe you can try to disable some builtin extensions (`@builtin`).

**Comment by mapsedge** [comment]
I have tried FTP extensions in VSCodium, and that's why I use PCManFM-QT.  I have run tests with _all_ extensions disabled, and it still exhibits the behavior. I know the problem probably exists in the node_modules folder, but I don't know what to look for or how to "watch" what VSCodium is doing.

**Comment by GitMensch** [comment]
I highly suggest to take that upstream as it is 99,5% no vscodium issue.

For logging and inspecting what vscode is doing I suggest to check out https://github.com/microsoft/vscode/wiki/File-Watcher-Issues (you know, there must be some reasoning for them to create a wiki article on that).

**Comment by mapsedge** [comment]
I would like to agree, but the fact that it only happens in VSCodium and only when a particular VSCodium folder exists suggests otherwise.

**Comment by GitMensch** [comment]
The point is: this seems to not be VSCodium but vscode (the basis for both VSCodium [pure] and "Visual Studio Code" [vscode + x, with x being not even completely clear]). vscode issues should be send upstream "where the devs are" (which is the main reason for the point in the bug template "This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.").

Did you checked the file watcher logs already?
