### ISSUE TITLE
VSCodium didn't run on Windows 7 x64 v6.1 (Build 7601: SP1)

### ISSUE THREAD

**Issue by musadarj** [VSCodium/vscodium#1256]
I've installed:
Offline installer of [MS .NET 4.5.2](https://www.microsoft.com/en-us/download/details.aspx?id=42642)
[PowerShell v5.1](https://www.microsoft.com/en-us/download/details.aspx?id=54616)
[Scoop](https://scoop.sh) via PS
then the VSCodium exacly like in the Instruction [here](https://github.com/VSCodium/vscodium#install-with-scoop)

There's no issue in the installation process.
But after it finished, I clicked the VSCodium icon from the Start menu, the app did't showed up.
It just like executing a silent Registry code from a .reg file. Still the app did't showed up.

![vsc](https://user-images.githubusercontent.com/33863355/190838145-e2b00234-1449-448e-9365-5a46ee354357.jpg)

Is I'm doing something wrong here?
Anyway I haven't tried VS Code in this device.

**Laptop:**
 - OS: Windows 7
 - Architecture: x64
 - Version: 6.1
 - Build: 7601 (SP1)

**Comment by paulcarroty** [comment]
[Prerequisites](https://www.electronjs.org/docs/latest/development/build-instructions-windows#prerequisites): Windows 10 / Server 2012 R2 or higher.

**Comment by daiyam** [comment]
Ah! We need to update the readme...

**Comment by paulcarroty** [comment]
Done.

**Comment by GitMensch** [comment]
For the current version the change to the docs https://github.com/VSCodium/vscodium/commit/6562d7d4a4a39dff45f92b0c092ee2d553f3b535 is correct. As Electron is in the process of re-adding Windows 7 support (see "kind of " duplicate issue #1264) VSCodium may work again on Win 7 in the future.

**Comment by musadarj** [comment]
Just tested [VSCodium-x64-updates-disabled-1.69.1.msi](https://github.com/VSCodium/vscodium/releases/tag/1.69.1) and hey.. it works perfectly!
![vscodium](https://user-images.githubusercontent.com/33863355/191700383-4ed853cd-df1e-4e03-b55c-bba1abf0af1c.jpg)
But recently I'm noticed a bug (I guess), after spending some hours the IDE showing white rectangles randomly like I demonstrated below.
![bug](https://user-images.githubusercontent.com/33863355/191701900-3470fc6b-4914-4cac-ab5d-b87af206b97d.jpg)
Note: The pic above is just for demonstration only, because I just woke up and booting my device so the bug didn't shown up.

**Comment by GitMensch** [comment]
I'd wait for an updated version (see other issue) - and if you see that strange bug then work around with "Reload Window" command.

**Comment by musadarj** [comment]
Ah right I almost forgot to include _Reload Window_ thanks for that.
anyway, can you update the _readme_ file to add support for Win 7? or just wait for Electron to be compatible with Win 7?

**Comment by GitMensch** [comment]
The README has Win10 which is what the current version is supporting; for Win 7 we'll wait on Wlectron news.
