### ISSUE TITLE
Download Update downloads the TAR package (Linux)

### ISSUE THREAD

**Issue by 0xEAB** [VSCodium/vscodium#1258]
**Describe the bug**

VSCodium’s updater has no clue how it was installed.
Even if I installed the DEB package, it will direct me to the TAR one.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

> MS does not publish ready-to-use packages on their GitHub releases page.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Make sure to have an outdated version installed
2. Click on the bottom gear icon
3. Click “Download Update (1)”
4. You’ll end up downloading the tarball (currently [this one](https://github.com/VSCodium/vscodium/releases/download/1.71.2.22258/VSCodium-linux-x64-1.71.2.22258.tar.gz))

**Expected behavior**

- Either direct me to the downloads overview
- or directly to the same variant I’ve currently installed

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Architecture amd64
 - Version 1.71.0 (installed as .deb-package)

**Additional context**
Don’t know how the MS version handles this exactly. But I think it used to redirect you to their downloads page.

**Comment by paulcarroty** [comment]
> Auto-updates are not supported for Linux.

> Updating on Linux
> Download the VS Code zip file: [64-bit](http://go.microsoft.com/fwlink/?LinkID=534108) or [32-bit](http://go.microsoft.com/fwlink/?LinkID=615206).
> Open the zip and run Code

https://vscode-docs.readthedocs.io/en/stable/supporting/howtoupdate/
