### ISSUE TITLE
Trouble with "Open in new windows"

### ISSUE THREAD

**Issue by cleoo** [VSCodium/vscodium#1266]
**Describe the bug**
When a second window is open, the application menus on the second cannot be used, something is blocking them.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug appeared recently maybe in 1.70 

**Desktop (please complete the following information):**
 - OS: ArchLinux 
 - Architecture x64
 - Version 1.71.2

**Additional context**
Gnome 42.5
X.org 1.21.1.4
Xwayland 22.1.3

**Comment by GitMensch** [comment]
I can't reproduce this on Ubuntu x64 (the .deb package, Snap created a bunch of permission errors).

How did you install it in Arch? Given https://github.com/VSCodium/vscodium/pull/1317/files there are at least three options (+ manual build), which one did you use - and does it improve if you update to 1.73 and/or install it different?
