### ISSUE TITLE
Enable Wayland in the snap

### ISSUE THREAD

**Issue by miromarszal** [VSCodium/vscodium#1267]
I rushed to open a PR at the snapcrafters repo: https://github.com/snapcrafters/codium/pull/18, but now can I see that the snap is maintained here too, which is slightly confusing to the ignorant me. I thought I'd drop a line here so that it doesn't get lost. Should I open a PR here too / remove that one at snapcrafters?

This was merged in vscode here: https://github.com/microsoft/vscode/pull/156551

**Comment by daiyam** [comment]
@miromarszal Can you move the PR here? The files are in `stores/snapcraft`. Thx

**Comment by daiyam** [comment]
The Insiders version has your fix. You can test it at https://github.com/VSCodium/vscodium-insiders/releases/tag/1.72.0.22269-insider
