### ISSUE TITLE
Rust extension fail to boot

### ISSUE THREAD

**Issue by Cyber-Talleyrand** [VSCodium/vscodium#1269]
**Describe the bug**
Problem with rust extensions, rustup missing for rust-lang and error bootstrap for rust-analyzer

**Please confirm that this problem is VSCodium-specific**
I installed VSCode and the extensions work

**Please confirm that the issue/resolution isn't already documented**
There is no mention on Docs.md

**To Reproduce**

1. Install rustup and make sure you added .cargo/bin to $PATH
2. Add rust-lang extension
3. Open .rs archive to load extension
4. See error "There is no rustup" and "RLS failed"

**Expected behavior**
Rust widgets such as run and debug appear in the screen without errors

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora
 - Architecture x86
 - Version 36

**Additional context**

**Comment by Taza53** [comment]
[Rust vscode](https://github.com/rust-lang/vscode-rust) has been deprecated and the [new rust-analyzer](https://github.com/rust-lang/rust-analyzer) extension is out-of-date(9 months).

**Comment by pentamassiv** [comment]
https://github.com/rust-lang/rust-analyzer/issues/13543 was fixed so now there is a new version of rust-analyzer available on open-vsx that does not have an error. It should work without a problem now

**Comment by Taza53** [comment]
I have tried the new version, it is still broken.
