### ISSUE TITLE
extensions search hangs

### ISSUE THREAD

**Issue by magowiz** [VSCodium/vscodium#1271]
Type: <b>Bug</b>

while in extension tab I search for extension, for example using "python" word, the search starts but never ends

I'm running vscodium on ubuntu via snap package

VS Code version: VSCodium 1.71.2 (cea9d1a4b17966719d8c5f3cdd914480f7cec47c, 2022-09-15T18:19:31.017Z)
OS version: Linux x64 5.15.0-48-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 3288)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|15.32GB (11.33GB free)|
|Process Argv|--ms-enable-electron-run-as-node --no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details>Extensions: none

**Comment by Schlomon** [comment]
I get: `Error while fetching extensions. Server returned 503`

VSCodium installed via official deb package.
Version: 1.71.2 (cea9d)

**Comment by daiyam** [comment]
It's an issue with https://open-vsx.org/: https://github.com/eclipse/openvsx/issues/539

**Comment by scottfurry** [comment]
Error seemed to disappear but getting 503 error again after updating to 1.72.0-22279.

**Comment by bruxr** [comment]
Just updated to 1.72.0 and getting the 503 error as well. This is in MacOS

**Comment by daiyam** [comment]
yep, open-vsx.org is down again!

**Comment by GitMensch** [comment]
... and back again; I think those issues should be placed in the open-vsx repo.
