### ISSUE TITLE
VS code written in some places

### ISSUE THREAD

**Issue by lakshyagithub** [VSCodium/vscodium#1273]
Here are the some places where vs code is written:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/85747258/193325195-12f665df-db0a-4aab-b784-db245879e8ca.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/85747258/193325579-a4d9a616-2a3b-4ece-bddf-09716ad75408.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/85747258/193325701-908b5c1b-0fd3-4fd2-8129-8e661b826c6a.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/85747258/193764757-461c8d1c-38cf-49ae-a354-3e335b67bc7f.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/85747258/193764844-9c8e5d7a-2c12-4aa1-812d-d76b2819d7da.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/85747258/193765700-85c616b1-5443-48c1-9a0c-d7dc6c7aead3.png">

**Comment by BoseSj** [comment]
I would like to work on this one.😄

**Comment by daiyam** [comment]
@BoseSj that [doc](https://github.com/VSCodium/vscodium/blob/master/docs/build.md) might help you.

**Comment by BoseSj** [comment]
Okay, working on it. Can you please assign this issue to me?

**Comment by BoseSj** [comment]
> @BoseSj that [doc](https://github.com/VSCodium/vscodium/blob/master/docs/build.md) might help you.

Yes, it contains instructions on how to build this in the local system. Can you please guide me on how can I get started with the given issue, where to start looking for etc?

**Comment by lakshyagithub** [comment]
Hi, I can see that the issue is still there can someone please fix it ASBP?

**Comment by lakshyagithub** [comment]
@BoseSj I gave the screenshots in the issue it self.

**Comment by ProDeSquare** [comment]
Isn't this issue fixed, shouldn't this be closed?

**Comment by lakshyagithub** [comment]
> Isn't this issue fixed, shouldn't this be closed?

No, I recently updated it but still I see the same thing.
It is VERY disturbing.

**Comment by lakshyagithub** [comment]
Reopen ping

**Comment by lakshyagithub** [comment]
This seems to be fixed. Thank you.
