### ISSUE TITLE
terminal error not show icon

### ISSUE THREAD

**Issue by newyorkthink** [VSCodium/vscodium#1275]
![image](https://user-images.githubusercontent.com/87791643/193416565-b1587993-3d34-4062-82dc-8f9a10d581c9.png)

it is appimage file format

**Comment by BoseSj** [comment]
are you using oh-my-posh for prompt customization?

**Comment by czorkol** [comment]
You have to change terminal font family. Default font family not support font icons in terminal. You may try "MesloLGS NF" font family in terminal.

**Comment by BoseSj** [comment]
Yes, only you can choose from one of these selected [fonts](https://www.nerdfonts.com/font-downloads) for the terminal. Using one of these will enable u to see the icons.
