### ISSUE TITLE
GitHub Copilot not working in VSCodium. FOSS alternatives? Other working alternatives?

### ISSUE THREAD

**Issue by GKeppler** [VSCodium/vscodium#1276]
**Describe the bug**
[Not able to install github copilot #1020 ](https://github.com/VSCodium/vscodium/issues/1020)
It is still not working today. Do you know working alternatives, FOSS or closed source?

**Comment by gebeer** [comment]
> **Describe the bug** [Not able to install github copilot #1020 ](https://github.com/VSCodium/vscodium/issues/1020) It is still not working today. Do you know working alternatives, FOSS or closed source?

As for alternatives, I'm using https://codeium.com/ successfully with no issues.
