### ISSUE TITLE
macOS: - keeps asking restart to update

### ISSUE THREAD

**Issue by ajiteb** [VSCodium/vscodium#1280]
**Describe the bug**
VSCodium is already up-to-date but the little icon keeps asking for `restart to update`.

**Screenshots**
![image](https://user-images.githubusercontent.com/88331595/194537820-6a5b9fb4-6350-4011-a701-5436e0236309.png)

![image](https://user-images.githubusercontent.com/88331595/194537842-23467543-52a1-4e8f-86e5-e7050dc8e660.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Architecture M1 chip

**Comment by daiyam** [comment]
Yes, I can reproduce the issue on M1 but not on x64...

**Comment by daiyam** [comment]
OK, I found and fixed the issue with https://github.com/VSCodium/versions/commit/b36c24b12f76104e003b390ad8c20fa2b817b589
The cache is updated every 4 hours so it can take a couple of hours for the issue to be fully fixed for the user.
I will have to make some changes to avoid that issue to re-occur.

**Comment by daiyam** [comment]
@ajiteb Can you try? I don't have the update loop anymore...

**Comment by ajiteb** [comment]
@daiyam Thanks for fixing it so quick.
Confirmed it's resolved. 🎉 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/88331595/194771683-5e171556-c019-4465-9455-469745d8c483.png">
