### ISSUE TITLE
Wrong information shown into "About" dialog after install russian language pack

### ISSUE THREAD

**Issue by sergey-dryabzhinsky** [VSCodium/vscodium#1281]
**Describe the bug**
After VSC moved to release+commit verioning lines in About dialog shifted and now shown wrong information.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
0. Setup language pack. In my case - russian.
1. Go to main menu 'Help/Помощь'
2. Click on 'About/О программе'
3. See wrong info in dialog

**Expected behavior**
Build date in Date info, etc.
Seems like russian lang pack does not have "Release:" line. And all other lines shifted.

**Screenshots**
![Снимок экрана_2022-10-07_20-52-11](https://user-images.githubusercontent.com/717597/194621873-1dc11dc8-5f2f-43bf-aacf-9a30ed6462aa.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 18.04
 - Architecture: amd64
 - Version: since 1.70.1+
 - App Manager: tar.gz

**Additional context**
If I remove language pack - all info got in right lines.
![Снимок экрана_2022-10-07_21-06-32](https://user-images.githubusercontent.com/717597/194621848-83c3f486-54ab-4c3d-83cd-5609b6260c5d.png)

**Comment by daiyam** [comment]
@sergey-dryabzhinsky This issue is specific to VSCodium since the release number isn't available on VSCode.

**Comment by Crystal-RainSlide** [comment]
Also see:

https://github.com/VSCodium/vscodium/issues/1301

https://github.com/VSCodium/vscodium/blob/10582b3c86c800f43dbe7836203420dde9862c60/patches/build-version.patch#L145

https://github.com/microsoft/vscode/blob/c07b428d7db4662a1f45e8e57e41d44167f2e11a/src/vs/workbench/electron-sandbox/parts/dialogs/dialogHandler.ts#L169

**Comment by daiyam** [comment]
@Crystal-RainSlide Feel free to make a PR to fix the issue 😉

**Comment by Crystal-RainSlide** [comment]
> Honestly, I don't know...
> - Should we hide the Release version?
> - Should we merge the Release version into the "Version:"?
> - Should we patch the language packs instead?

@daiyam You have to choose one first! 😆

**Comment by daiyam** [comment]
- Should we hide the Release version? **No**
- Should we merge the Release version into the "Version:"? **No**
- Should we patch the language packs instead? **No**

Oh! I see the issue... The text needs to be patched after it has been localized. Insert the new line (`Release: {1}`) after the line 1.
What about the text `Release`? Should we keep it in english or have the translations for all the languages?

**Comment by daiyam** [comment]
Could you make a PR? Thx

**Comment by Crystal-RainSlide** [comment]
@sergey-dryabzhinsky Can you provide Russian translation of `Release` or `Release version` for us, to add it together?

**Comment by sergey-dryabzhinsky** [comment]
it's `Релиз` and `Версия релиза`

**Comment by Crystal-RainSlide** [comment]
@sergey-dryabzhinsky Sorry for not ask them at once, but: Is the word `Релиз` good for represent `Release version`, which means a version number?

**Comment by daiyam** [comment]
@Crystal-RainSlide You have to make the PR on VSCodium/vscodium so we can merge it :wink:

**Comment by Crystal-RainSlide** [comment]
OH NO NOT AGAIN

Got fooled by GitHub's commit to a new branch and start a PR again.

**Comment by sergey-dryabzhinsky** [comment]
> @sergey-dryabzhinsky Sorry for not ask them at once, but: Is the word `Релиз` good for represent `Release version`, which means a version number?

Yes
