### ISSUE TITLE
missing MacOS dependencies

### ISSUE THREAD

**Issue by BoseSj** [VSCodium/vscodium#1282]
### Description 
Missing MacOS dependencies in [build.md](https://github.com/VSCodium/vscodium/blob/bba3e7481512321a9cf22a11d1a099721bf4be37/docs/build.md) file.

**_I would like to fix this. Please let me know what changes I need to make, and what dependencies I need to add._**

**Comment by BoseSj** [comment]
I think only the headings `Linux` and `MacOS` are misplaced 

![image](https://user-images.githubusercontent.com/58129377/194635943-644c8ebd-a160-42f0-98e1-00f2c2f6af38.png)

Stiil let me know if fixing that will do or if any more changes to make.

**Comment by daiyam** [comment]
Not, not misplaced but some dependencies might be missing for macOS.

**Comment by BoseSj** [comment]
Yeah,, should I add them? If you let me know what to add.
