### ISSUE TITLE
'More' button popup menu covers button and executes last menu item

### ISSUE THREAD

**Issue by cyclopticnerve** [VSCodium/vscodium#1283]
Type: <b>Bug</b>

Add source control repositories view to panel (any similar view with a '...' button on the far right of the view will also work)
Close secondary side panel
Maximize window
The '...' button in source control list should be very close to right/bottom edge of screen (THIS IS KEY!)
click the '...' button in source control list
the popup menu shows for a split second and the 'show git output'  (last menu item) command is executed

Actual results:
This happens because the popup menu is anchored always to the bottom right of the '...' button, so when shown, covers the '...' with the popup menu, and the click action is propagated to the last item in the popup menu.

Expected results:
The button action should determine if the context menu will show up/left, and if so, anchor it to the bottom LEFT of the '...' button, clearing the '...' button.

Also I have noticed LOTS of inconsistencies as to where different '...' context menus are anchored, even if they fit in the screen, i.e.:
Explorer:  bottom left
Outline: bottom right
Editors that are split down and very close to bottom of screen: sometimes works, sometimes executes last item

VSCodium version: VSCodium 1.72.0 (9f4a41aac91eb148c23b6956be66db333af2d3a2, 2022-10-06T20:36:13.723Z)
OS version: Linux x64 5.15.0-48-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) N4020 CPU @ 1.10GHz (2 x 2717)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|0, 1, 1|
|Memory (System)|3.66GB (1.38GB free)|
|Process Argv|--ms-enable-electron-run-as-node --no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
todo-tree|Gru|0.0.215
git-graph|mhu|1.30.0
python|ms-|2022.14.0
jupyter|ms-|2022.8.1002460559
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
linux-desktop-file|nic|0.0.21
even-better-toml|tam|0.18.1

</details>

**Comment by danahynes** [comment]
![Screenshot from 2022-10-07 15-10-20](https://user-images.githubusercontent.com/46582023/194637205-80f09438-8764-4553-8d57-000cab116fdf.png)
![Screenshot from 2022-10-07 15-11-20](https://user-images.githubusercontent.com/46582023/194637207-0471363d-db14-46fc-847f-8b54f11ce5ac.png)
