### ISSUE TITLE
vscode rust-analyzer inlay hints not showing

### ISSUE THREAD

**Issue by eliasjonsson023** [VSCodium/vscodium#1285]
**Describe the bug**
Even if inlay hints are enabled by checkbox, no hints are showing.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install the rust-analyzer extension
2. now inlay hints ought to show, but they don't.

**Expected behavior**
binding types ought to be displayed in code

**Desktop (please complete the following information):**
 - OS: Debian Bullseye
 - Architecture x64

Version: 1.72.0
Release: 22279
Commit: 9f4a41aac91eb148c23b6956be66db333af2d3a2
Date: 2022-10-06T20:36:13.723Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.10.0-18-amd64

Sandboxed: No
 - App Manager: apt

**Comment by appelgriebsch** [comment]
Also happens on macOS.

**Comment by IceWreck** [comment]
How did you install rust analyzer ? The one from the default VSX repo is years old.

https://github.com/rust-lang/rust-analyzer/issues/11080

**Comment by appelgriebsch** [comment]
Thanks for this hint @IceWreck. Loading the version from the rust-analyzer GH page and install it manually did the trick on my Mac.

**Comment by eliasjonsson023** [comment]
Also I installed the newest version from GitHub page but it didn't matter, still no Inlay hints despite enabling them in the settings.

**Comment by eliasjonsson023** [comment]
After a few days I rebooted my system, entered Vscodium, still running the nightly release of rust-analyzer, and now binding types are now showing. Case closed.
