### ISSUE TITLE
can't install ext install ms-vscode-remote.remote-ssh

### ISSUE THREAD

**Issue by Goddard** [VSCodium/vscodium#1288]
I know its probably for good reason it isn't in the extension search, but consider adding ext install ms-vscode-remote.remote-ssh or https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh

It works pretty well.

**Comment by daiyam** [comment]
That extension can't run on anything that isn't a Microsoft product.
Please consider the alternative https://open-vsx.org/extension/jeanp413/open-remote-ssh
