### ISSUE TITLE
[Question] About DirectWrite

### ISSUE THREAD

**Issue by ddzy** [VSCodium/vscodium#129]
## Current Feature
Guys, VSCodium's font get blurry, how to disabled `DirectWrite`?

## Expected Feature
![1](https://user-images.githubusercontent.com/33921398/56280548-02d62a00-613d-11e9-9086-045f5ab87674.png)

**Comment by stripedpajamas** [comment]
Hi @ddzy 👋 

Can you provide some more info as to what this feature would look like? Is this something that VSCode supports that VSCodium doesn't support? 

I found this open issue about blurry text (https://github.com/Microsoft/vscode/issues/1896) with some workarounds for different operating systems; I'm not sure if that is helpful or not.

**Comment by stripedpajamas** [comment]
Closing as abandoned
