### ISSUE TITLE
Stuck downloading update

### ISSUE THREAD

**Issue by ecoant** [VSCodium/vscodium#1291]
Type: <b>Bug</b>

I am a few minor versions behind and can't seem to update successfully, it just hangs "downloading update"

VSCodium version: VSCodium 1.70.2 22230 (6c122d9b2d1af2c37bd55caad614321eb53b342f, 2022-08-18T00:40:55.241Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 8, 6|
|Memory (System)|32.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
dart-code|Dar|3.50.0
flutter|Dar|3.50.0
gitlens|eam|12.2.2
prettier-vscode|esb|9.9.0
bloc|Fel|6.6.2
code-streaming|git|0.4.11
vscode-graphql|Gra|0.3.53
live-server|ms-|0.4.1
vscode-coverage-gutters|rya|2.10.1
errorlens|use|3.6.0

(1 theme extensions excluded)

</details>

**Comment by daiyam** [comment]
Please read https://github.com/VSCodium/vscodium/issues/1227
Sorry about the issue.

**Comment by ecoant** [comment]
Thank you! (In case anyone finds this, manual download is required for this version).
