### ISSUE TITLE
VSCodium installer overrides and changes icons of lots of file extensions on my system.

### ISSUE THREAD

**Issue by Alluseri** [VSCodium/vscodium#1292]
**Describe the bug**
When I update VSCodium through the "Update Now" button, the installer overrides a lot of extensions(such as .cs, .java, .sh) and changes their icons. I don't want either of that behavior. If I have .cs be opened by nothing, it should stay like that. And I don't even like the icons. Already happened twice to me.

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Click "Update Now" in VSCodium's notification
2. Wait until the installer finishes
3. Congratulations, a lot of file extensions are now overridden by VSCodium.

**Expected behavior**
This shouldn't happen.

**Screenshots**
<img src="https://cdn.nest.rip/uploads/740cddcc-cd49-405c-be21-0958e95c1652.png">

**Desktop:**
 - OS: Windows 8.1
 - x64
 - (older version) -> 1.72.2
- N/A

**Comment by daiyam** [comment]
Does it happens on an install (not an update)?
If I'm not wrong, when updating, it reapply the settings you have selected when installing.

**Comment by Alluseri** [comment]
> Does it happens on an install (not an update)? If I'm not wrong, when updating, it reapply the settings you have selected when installing.

I'm not sure. Would I have to reinstall VSCodium or install it on top of an existing installation to find out? When I first installed it, that didn't happen nor I saw any setting to allow/disallow that.

**Comment by Crystal-RainSlide** [comment]
Are you using the portable version?

Fore recent versions, I got updated to a installed version while using portable version.

VSCodium downloads a setup into `%TEMP%\codium-update-undefined-x64\CodeSetup-stable-<hash>.exe` and notify for update. This happens even after I set `"update.enableWindowsBackgroundUpdates": false`. I disabled update checking and forget about it for a while, then today I re-confirmed this.

**Comment by Alluseri** [comment]
> Are you using the portable version?

@Crystal-RainSlide No, I installed it using the admin mode installer.

**Comment by Crystal-RainSlide** [comment]
I feel this can be the same problem: Portable version got updated to a setup which will override the saved installer settings anyway, while setup installation only got updated to override the saved installer settings.

**Comment by Alluseri** [comment]
Issue is irrelevant anymore and dead anyway, I just never update and it works. Technology.
