### ISSUE TITLE
Folding and unfolding code blocks

### ISSUE THREAD

**Issue by ajrworkprojects** [VSCodium/vscodium#1296]
Type: <b>Bug</b>

Expected results -- Each code block should have arrows to the right of the line number.  The arrows should be clickable.  When I click an arrow and it points to the right, then the code becomes folded.  When I click an arrow and it points down, then the codde becomes unfolded.

Actual results -- the arrows don't appear at all.

----

Expected behavior -- when I open the Command Palette and click "Fold All", all of the code blocks shoud get folded.  When I open the Command Palette and click "Unfold All," all of the code blocks should get unfolded.

Actual behavior -- nothing happens when I open the Command Palette and click "Fold All" and "Unfold All."

----

I've checked my system for updates.  I've restarted VSCodium and my VM several times (I'm running VSCodim inside a Debian VM; it's been working fine so far).

I've also replicated this error in two different codebases in my VM.

VSCodium version: VSCodium 1.72.2 (378660f7dd07287aa34acf90e8fec157425c1ac8, 2022-10-16T23:03:19.989Z)
OS version: Linux x64 5.10.0-18-amd64
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (3 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|3, 2, 1|
|Memory (System)|3.81GB (0.65GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|lightdm-xsession|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.16.1
jupyter|ms-|2022.10.110
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
material-theme|zhu|3.15.6

</details>

**Comment by Crystal-RainSlide** [comment]
Can you provide some screenshot(s), along with your folding-related settings, like `editor.folding` and `editor.showFoldingControls`?

**Comment by ajrworkprojects** [comment]
Below is a video of the issue, as well as screenshots of the two settings.

https://user-images.githubusercontent.com/82987707/196725367-67981740-a31f-4938-a593-99282190063f.mp4
<img width="1280" alt="2022-10-19_09-38-11" src="https://user-images.githubusercontent.com/82987707/196725423-b2cf6226-fdd4-4daa-a47e-7ec383167038.png">
<img width="1280" alt="2022-10-19_09-34-14" src="https://user-images.githubusercontent.com/82987707/196725446-ba5a6b6e-553d-43be-818c-fdbb0e5fecac.png">

**Comment by ajrworkprojects** [comment]
Thanks so much for any assistance you're able to provide!  And no rush on this either -- this isn't a critical issue for me.

**Comment by Crystal-RainSlide** [comment]
Seems like a VSCode / Python Language Support / Jupyter related problem:
- https://stackoverflow.com/q/74117813
- https://github.com/microsoft/vscode/issues/75726
- https://github.com/microsoft/vscode-jupyter/issues/11703

You may try other programming language and see if their folding is affected, try disable Jupyter extension...
And see if it's Jupyter, Python language support, or VSCode itself, and **report this issue to them** instead.

---

I can find folding related code for Python source in Jupyter and Python Language Support - where Python Language Support only touches the folding of doc string - but not VS Code's Python Language Basic, Basic only have some folding infomation in `language-configuration.json` to enable VSCode's region folding:

- https://github.com/microsoft/vscode-jupyter/blob/c99ff0ad4a995f942564632b7cd1432a05c1cdee/src/interactive-window/editor-integration/pythonCellFoldingProvider.ts
- https://github.com/microsoft/vscode-python/blob/3698950c97982f31bb9dbfc19c4cd8308acda284/src/client/providers/docStringFoldingProvider.ts
- https://github.com/microsoft/vscode/blob/76a647c33c04d0b9db566dec0757f953ea838d3c/extensions/python/language-configuration.json#L43

So my best bet is Jupyter.

**Comment by ajrworkprojects** [comment]
Thanks so much!  You were right on the money -- I disabled all of the Jupyter extensions, and that resolved my issue.  

Don't even know why Jupyter was enabled in my instance of VSCodium to begin with.  I didn't purposely enable that, and I don't build/use Jupyter notebooks (never had a need to).

Thanks again!

**Comment by Mechazo11** [comment]
@Crystal-RainSlide thanks, I also got code folding feature following your suggestion. 

Version: 1.72.2 (user setup)

**Comment by Crystal-RainSlide** [comment]
> From https://github.com/microsoft/vscode-jupyter/issues/11703#issuecomment-1287273612 :
> [amunger](https://github.com/amunger): I have added a jupyter.pythonCellFolding that should disable the folding provider from the jupyter extension. That should be available in tomorrow's insiders and hopefully that re-enables the other folding regions for you. Keeping this issue open though to try and figure out why it would be interfereing.
