### ISSUE TITLE
 Kernel selection: Can't find (conda) environments

### ISSUE THREAD

**Issue by thisfro** [VSCodium/vscodium#1298]
**Describe the bug**
Selection of python environments is broken in notebooks.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install Juypter Extension v2022.10.110
2. Create conda environment
3. Create Jupyter notebook 
4. Try to select created environment
<img width="613" alt="Screenshot 2022-10-20 at 12 02 08" src="https://user-images.githubusercontent.com/9142702/196921805-d5c6a7b9-5959-44aa-aab1-79cc7887bde0.png">

**Expected behavior**
Shows all environments (as in older version)
<img width="611" alt="Screenshot 2022-10-20 at 12 03 21" src="https://user-images.githubusercontent.com/9142702/196921698-dfd76ab0-0793-46fd-908e-bbdf044733ca.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Architecture: arm64
 - Version: 1.72.2
 - App Manager: Homebrew

**Additional context**
Also see issue at vscode-jupyter: https://github.com/microsoft/vscode-jupyter/issues/11722

**Comment by mohnishdeshpande** [comment]
I am experiencing this too. Tried purging and reinstalling extensions and the IDE, but no luck.
The behaviour was surprising because everything was working with absolutely no quirks before this.

**Comment by GG-Delta** [comment]
I am facing a similar issue with vscodium (Version: 1.77.3 Release: 23102). Even though having several Jupyter kernels installed vscodium doesn't reveal any in the kernel to select from (installed kernels verified using this command `jupyter kernelspec list`). Is there any workaround for now? Thanks a lot!

**Comment by MelihDarcanxyz** [comment]
Just like the above two comments, jupyter notebooks doesn't work for me anymore. There is no kernel to choose, so notebook refuses to work. I can use the notebook from the browser, but VS Codium doesn't work.

**Comment by GG-Delta** [comment]
After trying several approaches to resolve this issue (including a fresh installation of VSCodium) I tested my current setup in VSCode and there it worked smoothly (no issues regarding Kernel selection). Unfortunately, I was not able to pinpoint the root cause for VSCodium.
