### ISSUE TITLE
How do I download a windows version?

### ISSUE THREAD

**Issue by sere3925sere** [VSCodium/vscodium#1299]
There are a lots of files in [releases](https://github.com/VSCodium/vscodium/releases), but I'm not sure which I should download. What is the difference between those:

VSCodium-ia32-1.72.2.22289.msi
VSCodium-ia32-updates-disabled-1.72.2.22289.msi
VSCodium-win32-arm64-1.72.2.22289.zip
vscodium-reh-win32-x64-1.72.2.22289.tar.gz
vscodium-reh-win32-ia32-1.72.2.22289.tar.gz
VSCodium-win32-x64-1.72.2.22289.zip
VSCodium-x64-1.72.2.22289.ms
VSCodium-x64-updates-disabled-1.72.2.22289.msi
VSCodiumSetup-arm64-1.72.2.22289.exe
VSCodiumSetup-ia32-1.72.2.22289.exe
VSCodiumSetup-x64-1.72.2.22289.exe
VSCodiumUserSetup-arm64-1.72.2.22289.exe
VSCodiumUserSetup-ia32-1.72.2.22289.exe
VSCodiumUserSetup-x64-1.72.2.22289.exe

I guess everything with arm64 is for mobile phones, ia32 is 32bit build, x64 is 64bit build. What is reh and UserSetup though? Msi files are apparently almost like exe files, with extra benefit of possibility of silent remote installation without requiring user input, useful for some.

Main page also mentions installing VSCodium through either Windows Package Manager, Chocolatey or Scoop, what's the difference between those?

**Comment by sere3925sere** [comment]
There is an unanswered questions here, seems very related to this.
https://github.com/VSCodium/vscodium/discussions/1214
What's the difference between VSCodium, VSCodiumSetup and VSCodiumUserSetup installation files?

Since when github has discussions tab in addition to issues? Probably 2020/2021.

**Comment by Crystal-RainSlide** [comment]
- REH is [Remote Extension Host](https://code.visualstudio.com/api/advanced-topics/extension-host), normally not needed;
- For anything else, just reference to: https://code.visualstudio.com/docs/setup/windows .

**Comment by GitMensch** [comment]
Question answered :-) More answer in the linked discussion.

**Comment by GitMensch** [comment]
> Main page also mentions installing VSCodium through either Windows Package Manager, Chocolatey or Scoop, what's the difference between those?

Just seen that extra part: in general - the package managers will nearly always install silently (often with the msi package), often disables updates via application, commonly updating all software it installed itself.
If you use one of these, then you know, otherwise you may want to check those out and think about the question on using those.

**Comment by JenieX** [comment]
There should be links for the major versions on VSCodium website, no need to point to a page that has over a hundred versions.

**Comment by GitMensch** [comment]
@Jenie This issue was about the release page, your request is about the web page, which is tracked at https://github.com/VSCodium/vscodium.github.io/issues/63 - help welcomed.

**Comment by JenieX** [comment]
> @jenie This issue was about the release page, your request is about the web page, which is tracked at [VSCodium/vscodium.github.io#63](https://github.com/VSCodium/vscodium.github.io/issues/63) - help welcomed.

Good point.
