### ISSUE TITLE
New configuration directory?

### ISSUE THREAD

**Issue by gnumoksha** [VSCodium/vscodium#1302]
After updating to [1.72.2.22289](https://github.com/VSCodium/vscodium/releases/tag/1.72.2.22289) the configuration directory changed from `$HOME/.config/VSCodium` to `~/.config/Visual Studio Code`. Is that expected?

```console
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bookworm/sid
Release:        testing
Codename:       bookworm
```

**Comment by daiyam** [comment]
No! How did you install it? Do you have the issue with [1.72.0.22279](https://github.com/VSCodium/vscodium/releases/tag/1.72.0.22279) or a `1.71.x`?

**Comment by gnumoksha** [comment]
I installed it by downloading [codium_1.72.2.22289_amd64.deb](https://github.com/VSCodium/vscodium/releases/download/1.72.2.22289/codium_1.72.2.22289_amd64.deb) and then executed `dpkg -i codium_1.72.2.22289_amd64.deb`.

Testing older versions:
- I've the issue with [1.72.0.22279](https://github.com/VSCodium/vscodium/releases/download/1.72.0.22279/codium_1.72.0.22279_amd64.deb), which is the first release in 1.72 series
- No issue with [1.71.2.22258](https://github.com/VSCodium/vscodium/releases/download/1.71.2.22258/codium_1.71.2.22258_amd64.deb), which is the latest release in 1.71 series

The following works as workaround:
```console
$ rm -Rf "$HOME/.config/Visual Studio Code"
$ ln -s $HOME/.config/VSCodium "$HOME/.config/Visual Studio Code"
```

**Comment by gnumoksha** [comment]
It's worth mentioning that a couple of weeks ago I did a temporary change in product.json in order to install ms-python.vscode-pylance as pointed [here](https://github.com/VSCodium/vscodium/issues/892). But the modified product.json is not active anymore and was not used during the above tests.
