### ISSUE TITLE
PSA: upstream tag "1.72.2" was originally published pointing to an old commit, has now been updated

### ISSUE THREAD

**Issue by DeeDeeG** [VSCodium/vscodium#1303]
See comments here: `https://github.com/microsoft/vscode/issues/163401`

To summarize: The upstream VSCode git tag "1.72.2" was recently updated -- it was originally published pointing to commit https://github.com/microsoft/vscode/commit/129500ee4c8ab7263461ffe327268ba56b9f210d (which was the older commit from the  1.72._1_ release). It is now pointing to commit https://github.com/microsoft/vscode/commit/d045a5eda657f4d7b676dedbfa7aab8207f8a075 (which seems right to me).

I tried to read the build scripts here to see if it would affect VSCodium's build process, but I found it too confusing to understand whether this tagging situation would affect which code got built here. But I figured I would point it out and let you folks know, regardless.

Thanks for all you do. Best Regards.

**Comment by DeeDeeG** [comment]
Also, at the moment the GitHub Release for 1.72.2 isn't visible to me. (Perhaps it got converted to draft when the tag was pushed?)

Again, not sure if GitHub Releases at the upstream repo affects build processes here, just mentioning what I know.

**Comment by daiyam** [comment]
Based on the log https://github.com/VSCodium/vscodium/actions/runs/3261216242/jobs/5355653728, the commit `d045a5eda657f4d7b676dedbfa7aab8207f8a075` was used (`MS_COMMIT="d045a5eda657f4d7b676dedbfa7aab8207f8a075"`, in `Clone VSCode repo`)

`https://update.code.visualstudio.com/api/update/darwin/stable/lol` is used to get the latest VSCode version.

**Comment by DeeDeeG** [comment]
Okay, sounds like VSCodium got the real 1.72.2 content from upstream, then.

They were some pretty small fixes, but still. Good to know. Thanks for the reply.
