### ISSUE TITLE
VS Codium Doesn't Use the Portable Folder on MacOS

### ISSUE THREAD

**Issue by RoyiAvital** [VSCodium/vscodium#1314]
**Describe the bug**

VS Codium doesn't use the portable folder as defined in:

 * https://github.com/VSCodium/vscodium/issues/889.
 * https://github.com/VSCodium/vscodium/issues/333.
 * https://github.com/VSCodium/vscodium/issues/295.

See how it is created:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/7347975/199186653-731966d3-e227-4f43-a7ab-61a7bf8f94f8.png">

The folders remain empty and all data is written to `$HOME/Library/Application Support/VSCodium`.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

<img width="774" alt="image" src="https://user-images.githubusercontent.com/7347975/199186862-416a8487-ed0d-42dc-9285-a0b5fc6a0227.png">

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Download latest version (`1.72.2`).
2. Save to a local folder.
3. Create the portable folder (`codium-portable-data`) next to the app package (The `.app` file).
4. Launch `VSCodium`.
5. See the folder is empty.

**Expected behavior**
Preferences to be written to the portable folder.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: macOS 12.6
 - Architecture: arm64 (M1).
 - Version: 1.72.2.
 - App Manager: None (Download form the releases on GitHub).

**Comment by sommer-gei** [comment]
I experienced the same problem on Windows, `v1.76.2 (user setup)`.

**Comment by RoyiAvital** [comment]
I didn't see it was solved.

**Comment by MrMendelli** [comment]
I am using VSCodium on Windows and I am having the same issue. I have visited all links posted here as well as several others. I have tried what is posted here and suggested externally, this feature does not seem to be working.
