### ISSUE TITLE
Bad install instructions for AUR

### ISSUE THREAD

**Issue by Morganamilo** [VSCodium/vscodium#132]
The install instructions use an AUR helper, which are unsupported by arch and the AUR. What's worse though is the command given will cause partial upgrades.

See also:

https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported
https://github.com/eosrei/twemoji-color-font/issues/59
https://github.com/NASA-SW-VnV/ikos/pull/15

**Comment by stripedpajamas** [comment]
Yikes! I don't know much about Arch Linux. Should those instructions be removed completely or should they be modified in some way?

**Comment by Morganamilo** [comment]
You can just say it's available in the AUR and link to it like so https://github.com/eosrei/twemoji-color-font/pull/63/files. Arch users shouldn't really need instructions on how to install stuff on arch.

**Comment by stripedpajamas** [comment]
Awesome, will do! Thank you @Morganamilo 🙏
