### ISSUE TITLE
Q: how to do clean reinstall?

### ISSUE THREAD

**Issue by ivanjaros** [VSCodium/vscodium#1331]
When I try to reinstall the program I still have crap from the previous installation. How do I do clean uninstall? Windows 10.

**Comment by sandiks** [comment]
remove config folder (in appdata or roaming)

**Comment by ivanjaros** [comment]
didn't work

**Comment by sandiks** [comment]
try to remove  %USERPROFILE%\.vscode\extensions
"vscode" replace with  codium

**Comment by daiyam** [comment]
@ivanjaros remove `%APPDATA%\VSCodium` and `%USERPROFILE%\.vscode-oss`

**Comment by ivanjaros** [comment]
> @ivanjaros remove `%APPDATA%\VSCodium` and `%USERPROFILE%\.vscode-oss`

why uninstall cannot do it itself or provide options for removal?
