### ISSUE TITLE
get start error

### ISSUE THREAD

**Issue by newyorkthink** [VSCodium/vscodium#1332]
![image](https://user-images.githubusercontent.com/87791643/202412270-49a329e3-249b-4058-b528-ad7824899d02.png)

Appimage file 
get start show error

**Comment by nualtunkaya** [comment]
Disabling `Workbench › Welcome Page: Extra Announcements` in _**Preferences**_ fixed this for me.

I'm not sure, was this setting newly added in VSCodium v1.73? There's also a `Workbench › Welcome Page › Experimental: Video Tutorials` setting that I don't remember seeing before. Strangely, these settings do not appear under _**Online Services Settings**_ i.e. they are not tagged with `@tag:usesOnlineServices`.

**Comment by daiyam** [comment]
`Welcome Page: Extra Announcements` are specific to VSCodium, it has been added in `1.72.0.22279`.
It loads the file https://github.com/VSCodium/vscodium/blob/master/announcements-extra.json

**Comment by nualtunkaya** [comment]
Ah, I see, thank you for the clarification!

I hadn't used VSCodium completely offline for a while now; that's probably why I didn't run into this issue before.

**Comment by zaher** [comment]
I confirm that, "Welcome Page" should not fail if there is no internet connection
