### ISSUE TITLE
Clipboard not working after closing program

### ISSUE THREAD

**Issue by Yanoboku** [VSCodium/vscodium#1333]
I can use code that I copied when VSCodium is opened, but if I copy something and close VSCodium, clipboard is clear 

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
- [ ] 
**To Reproduce**
1. Go to 'VSCodium'
2. Copy any text
3. Close VSCodium
4. Try to paste text

OS: Kali linux 2022.4
Architecture: x64
Version: VSCodium 1.73.1

**Comment by daiyam** [comment]
@Yanoboku You need to provide the following informations:

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS, Ubuntu 20.04, etc]
 - Architecture [e.g. x64, ia32, arm64]
 - Version [e.g. 1.33.0]
 - App Manager [e.g. Winget, Homebrew, Snap, AUR, RPM, Nix, ...]
 - Sandboxed [e.g. no, Flatpak, Snap]
