### ISSUE TITLE
Question: installing external extension

### ISSUE THREAD

**Issue by jcalfee** [VSCodium/vscodium#1334]
Just a simple question here.  I guess I need to add a server?

```bash
$ codium --install-extension apollographql.vscode-apollo

Installing extensions...
Extension 'apollographql.vscode-apollo' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
Failed Installing Extensions: apollographql.vscode-apollo
```
From: https://marketplace.visualstudio.com/items?itemName=apollographql.vscode-apollo

It is not clear what their URL is or if this will even work.  Is it not possible to load this from another repo?  At one point someone tried to publish it but it is gone.  That is less than ideal for security.  Of course, I'm curious about privacy.  Maybe this is not worth it.  Thanks for your feedback.

https://github.com/apollographql/apollo-tooling/issues/2003

**Comment by daiyam** [comment]
We can't access the Visual Studio Marketplace: https://github.com/VSCodium/vscodium#extensions-and-the-marketplace
