### ISSUE TITLE
codium-insiders does not launch on Fedora, installed via RPM.

### ISSUE THREAD

**Issue by drwhut** [VSCodium/vscodium#1335]
**Describe the bug**
The application does not launch via the GUI, or via the terminal.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Attempt to launch the application via the start menu, or by running the command `codium-insiders`.
2. See that nothing happens.

**Expected behavior**
The application should launch.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Architecture: x64
 - Version 1.74.0-insider
 - App Manager RPM
 - Sandboxed no

**Additional context**
Running the command by itself does not output anything, but running with `--verbose` gives this output, which may be useful:
```
TypeError: app?.getPreferredSystemLanguages is not a function
    at resolveNlsConfiguration (/usr/share/codium-insiders/resources/app/out/main.js:8:3212)
    at onReady (/usr/share/codium-insiders/resources/app/out/main.js:7:9760)
    at App.<anonymous> (/usr/share/codium-insiders/resources/app/out/main.js:7:9351)
    at Object.onceWrapper (node:events:646:26)
    at App.emit (node:events:526:28)
[6627:1120/124340.932848:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
```

**Comment by jcasale** [comment]
I can confirm this for Windows x64 as well, with the same stack trace.

The last successful build for me was 1.74.0.22319.

**Comment by daiyam** [comment]
Oh! The Insiders! Hum... I will have to test that out...

**Comment by daiyam** [comment]
It's also broken on macOS...

**Comment by xaloc33** [comment]
Same issue with codium-insiders on ubuntu. Codium-insiders installed with apt package version ```1.74.0.22323 amd64```. The processes keep running but nothing appears on screen.

**Comment by daiyam** [comment]
It isn't limited to linux, I have the some error on Windows...

**Comment by PlavorSeol** [comment]
It is fixed in 1.74.0-insider 22328 on Windows. I can confirm it was broken in 22325 for me as well.

**Comment by vraravam** [comment]
Still not working for me - macos, arm (m1), tried with the latest insiders (22325).

**Comment by daiyam** [comment]
@vraravam Try 22328
