### ISSUE TITLE
Can't not navigate to terminal tabs view

### ISSUE THREAD

**Issue by vanvuvuong** [VSCodium/vscodium#1336]
**Describe the bug**
From the version 1.68.1 to the latest one, I can't not use the feature: `Terminal: Focus Terminal Tabs View`. The issue was happened with VSCode (latest version) too.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to 'Terminal: Focus Terminal Tabs View'
2. Nothing Happen.
3. Click one the panel
4. Can navigate

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/76928878/203467623-e111dbfe-199a-4226-82d1-df2431b0ff4f.png)

**Desktop (please complete the following information):**
 - OS: Parrot OS 5.1 (Electro Ara)
 - Architecture: x64
 - Version: ^1.69.0
 - App Manager: APT
 - Sandboxed: No

**Additional context**

**Comment by daiyam** [comment]
Are you sure that it doesn't happen with Visual Studio Code?
Because from a test with both, they have the same behaviour: it focus to the terminal when you are in the terminal tab.

**Comment by vanvuvuong** [comment]
Sorry, I have forgotten to change the whole format. No, it happened to both VSCode & VSCodium.
