### ISSUE TITLE
VSCodium doesn't start anymore Ubuntu 22.04 + flatpak version

### ISSUE THREAD

**Issue by liloumuloup** [VSCodium/vscodium#1338]
**Describe the bug**
The app doesn't start anymore with error related to Electron

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to https://flathub.org/apps/details/com.vscodium.codium
2. Install the app with the command `flatpak install flathub com.vscodium.codium`
3. Try to launch it with `flatpak run com.vscodium.codium`

**Expected behavior**
The app should be launched.

**Screenshots**
Error stack trace : 
```
➜  ~ flatpak run com.vscodium.codium                           
codium-wrapper: Setting up NPM packages
codium-wrapper: Setting up Cargo packages
codium-wrapper: Setting up Python packages
codium-wrapper: Setting up Ruby packages
Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Architecture : x64
 - Version : `1.73.1.22314`
 - App Manager : flatpak
 - Sandboxed : flatpak

**Additional context**
Info from flatpak install : 
```
➜  ~ flatpak info com.vscodium.codium  

VSCodium - Code editing. Redefined. Telemetry less.

          ID: com.vscodium.codium
         Ref: app/com.vscodium.codium/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.73.1.22314
     License: MIT
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 304,6 MB
     Runtime: org.freedesktop.Sdk/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: 1816c0e383a9d497d6840b8fc7eb7791cccc8c270a702e56f5e538615991e07d
      Parent: d8967ddb901f7375b652fa1d071d138236486b398554ee326d375c27b6a348d6
     Subject: :hammer_and_wrench: Remove Debug variables (c9cfa14d)
        Date: 2022-11-17 20:41:02 +0000
```

I also tried to remove and reinstall the package from flatpak, with no chance.

I also installed [visual studio](https://flathub.org/apps/details/com.visualstudio.code) from flatpak and it works.
I don't know if i missed some info. Do not hesitate to ask if needed :blush: 
Thank you !

**Comment by daiyam** [comment]
Hi @liloumuloup, the flatpak is currently managed by https://github.com/flathub/com.vscodium.codium so I don't know anything about it...

**Comment by liloumuloup** [comment]
Hi ! Thank you for your answer. I didn't have time to test until today. I found out this bug : https://github.com/flathub/com.vscodium.codium/issues/149
Today, i updated my vscodium and it work now.
Thank you very much for your time. :bowing_woman:
