### ISSUE TITLE
cann't find c++ tools in extension store

### ISSUE THREAD

**Issue by ixcoding** [VSCodium/vscodium#1340]
Type: <b>Bug</b>

1.73.1. can't search and install microsoft's. c/c++ tools in extension store

VSCodium version: VSCodium 1.73.1 (14f2d26367b7e8f03ff2352516ba27d6302dd7b1, 2022-11-10T18:10:38.644Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sftp|Nat|1.16.1

</details>

**Comment by ixcoding** [comment]
vscodium search c++ and got that:

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/119370197/204404616-292f9897-1129-4986-adfc-a4460094ff9d.png">

**Comment by ixcoding** [comment]
original vscode got that:
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/119370197/204404783-439dfc77-300e-4b4b-9dbf-d260ad0c0136.png">

**Comment by daiyam** [comment]
https://github.com/VSCodium/vscodium#extensions-and-the-marketplace
