### ISSUE TITLE
SSL certificate problem: EE certificate key too weak

### ISSUE THREAD

**Issue by XSpielinbox** [VSCodium/vscodium#1351]
**Describe the bug**
When trying to use the the VSCodium rpm repository (e.g. check for updates) with the [FUTURE crypto-policy](https://fedoraproject.org/wiki/Changes/StrongCryptoSettings3) enabled in Fedora Linux 37 oder RHEL 9 the following error occurs:
```
Errors during downloading metadata for repository 'gitlab.com_paulcarroty_vscodium_repo':
  - Curl error (60): SSL peer certificate or SSH remote key was not OK for https://download.vscodium.com/rpms/repodata/repomd.xml [SSL certificate problem: EE certificate key too weak]
Error: Failed to download metadata for repo 'gitlab.com_paulcarroty_vscodium_repo': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

This error is very likely due to the fact that download.vscodium.com serves a 2048 bit RSA TLS Cert, but modern cryptography standards require 3072 bit or more when using RSA.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. install VSCodium
2. set crypto-policy to FUTURE
3. try to fetch anything from the repo

**Expected behavior**
One can just use the repository with a strong crypto-policy without any errors.

**Desktop:**
 - OS: Fedora Linux 37
 - Architecture x64
 - Version 1.74.0
 - App Manager RPM
 - Sandboxed no

**Additional context**
It is not an issue with the vscodium-deb-rpm-repo of Pavlo Rudy. The Bug was already filed there and concluded that this is an error in the VSCodium infrastructure.

**Comment by rbradley0** [comment]
When browsing to the RPM repodata location at `https://download.vscodium.com/rpms/repodata/repomd.xml`, it throws an `Error code: SSL_ERROR_BAD_CERT_DOMAIN` error on my browser as pictured below.

So basically the SSL cert is misconfigured and only includes `*.b-cdn.net` as a trusted domain for that certificate.

![image](https://user-images.githubusercontent.com/70593983/209419602-337f2ed9-ff13-409a-aaa7-ee51981031bd.png)

**Comment by amitlevy21** [comment]
I'm suffering from the same issue and can't update vscodium, is there a workaround?

**Comment by rbradley0** [comment]
> I'm suffering from the same issue and can't update vscodium, is there a workaround?

@amitlevy21 @XSpielinbox unfortunately no workaround for a suspended/unconfigured/misconfigured CDN endpoint. This is what shows if you don't get a prompt for the SSL certificate error or have previously bypassed the SSL security check.
![SSL Cert Error](https://github.com/VSCodium/vscodium/assets/70593983/e1720964-79cc-4df0-9d6d-5bfe28457886)
