### ISSUE TITLE
VScodium cannot properly transfer settings in zip version new installtion

### ISSUE THREAD

**Issue by dpapis** [VSCodium/vscodium#1353]
Type: <b>Bug</b>

Greetings all
i am using VSCode teaching Python in school.
I am using the vscode zip version as it offers me great portability of code.
in a recent update version,specifically from 17.4.0 to 17.4.1 (17.4.1 is the current version i am using right now) i noticed the following issue:
First ,
i copied the data folder from the old installation folder (17.4.0) to the new installation folder (17.4.1)) than holds  the new extracted version of  newest vs code version
Second,
if i remove to recycle bin the old zip folder than contains the 17.4.0 version,the 17.4.1 version does not transfer the settings and extensions to new installation(notice that the old copied data folder exists in the new installation already).
if i keep the old intallation folder the vscode exe files loads correct all the installed extensions correctly-no new installation and configuration required...
Any suggestions how to resolve this?
as i mentiond before the above procedure that i have desribed is the propper procedure to transfer an old installation of vs code  zip version to a new one, is the official that i use a long time now from the vs code site:
https://code.visualstudio.com/docs/setup/windows

win x64 windows 10 Pro and x64 zip of VS Code all used version utlil now.
Thansk in advaced

VSCodium version: VSCodium 1.74.0 (cb188d662af4ff5d43505b572b49905a1f0153ad, 2022-12-08T20:06:19.200Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
prettier-vscode|esb|9.10.3
code-runner|for|0.11.8
vscode-language-babel|mgm|0.0.35
git-graph|mhu|1.30.0
python|ms-|2022.20.1
jupyter|ms-|2022.10.110
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
sqltools|mtx|0.26.0
vscode-graphql|Pri|0.3.7
vscode-thunder-client|ran|2.2.0
open-in-browser|tec|2.0.0
five-server|yan|0.1.11

</details>

**Comment by Crystal-RainSlide** [comment]
I got this but:

- Same report at VSCode's repo: https://github.com/microsoft/vscode/issues/169462
- Seems to be fixed at https://github.com/microsoft/vscode/issues/169006#issuecomment-1362892184
- Let's wait for VSCode 1.75.0 and see.
