### ISSUE TITLE
Terminal not opening external program

### ISSUE THREAD

**Issue by dimvoly** [VSCodium/vscodium#1354]
**Describe the bug**
I have some code that I run and it is meant to open a pdf file using a rust command.

  open::that("document.pdf").unwrap();

See [Issue](https://github.com/Byron/open-rs/issues/60) in `open` rust crate.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
- [x] did not test in VSCode

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Create a new rust project
2. Add the `open` crate
3. Attempt to open a pdf file -> code completes successfully, but no pdf viewer is opened.
4. Then using a separate terminal (not in VSCodium) run the exact same code -> pdf viewer is opened as expected

**Expected behavior**
Results from steps 3 and 4 should be identical, should open the external program.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Architecture: x64
 - Version: 1.74.1
 - App Manager: Snap
 - Sandboxed: no

**Additional context**
This may have something to do with my settings in VSCodium (security settings?). I used to have similar issues with no links opening up, but that has seemed to fix itself. Maybe there are some settings I could play with?

**Comment by scottfurry** [comment]
I got bit by something similar. It seems upstream added a 'posix_spawn' executable to the binary package. Package managers may have missed setting the correct permissions for this executable for installation. See...
VSCode - [#173600](https://github.com/microsoft/vscode/issues/173600)
Gentoo - [#893208](https://bugs.gentoo.org/893208)
NixOS - [#214617](https://github.com/NixOS/nixpkgs/issues/214617)

Workaround/Fix is to correct the permissions of executable in the VSCodium bundle
```
fperms +x /opt/vscodium/resources/app/node_modules.asar.unpacked/node-pty/build/Release/spawn-helper
```

Terminal should respond/execute normally - assuming you're having the same problem.

**Comment by dimvoly** [comment]
Interesting, while I don't have the `fperms` command on Ubuntu, that file (in another location) seems to already have the execute permissions:

```
/snap/codium/current/usr/share/codium/resources/app/node_modules.asar.unpacked/node-pty/build/Release$ ls -l spawn-helper 
-rwxr-xr-x 1 root root 17792 Mar 11 10:05 spawn-helper
```

So I'm not sure if it is the same issue.

**Comment by dimvoly** [comment]
After various upgrades (VSCodium & rustc), including upgrading the `open` rust crate to "4.0.0", the PDF opens in system viewer if I go to the VSCodium terminal and run `cargo test` from there. If I click on the code lens shortcut to run a specific test, then same problem as before, system viewer doesn't open.

**Comment by scottfurry** [comment]
To start, you're right about `fperms`. That was a *copy-paste* error on my part. Command is apart of Gentoo install infrastructure.

Overall, this feels more like a `snap` install problem rather than a `VSCodium` issue. However, I'm not a VSCodium dev.
