### ISSUE TITLE
Some Extensions Disappeared after Upgrading VSCodium

### ISSUE THREAD

**Issue by onion108** [VSCodium/vscodium#1355]
**Describe the bug**
After upgrading to `1.74.0` by restarting the VSCodium, some of my extensions suddenly disappeared.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Use a VSCodium which has a version number smaller than `1.74.0`
2. Install some extensions, and wait for the notification of "Restart VSCodium to apply the latest update"
3. After upgrading, some of the extensions may disappear.

**Expected behavior**
`null`

**Screenshots**
`null`

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.0.1
 - Architecture arm64
 - Version `1.73.x ~ 1.74.0`
 - App Manager not installed via an app manager
 - Sandboxed no

**Additional context**
I currently found those extensions disappeared (the extensions are directly installed to VSCodium except the first one):
`shalldie.background` (installed when I'm using VSCode and just copied to VSCodium)  
`jaredkent.laserwave`  (installed via `vsix`)
`alexanderte.dainty-vscode`  (installed via `vsix`)
`webfreak.cute-theme` (installed in VSCodium's marketplace)
`usernamehw.errorlens` (installed in VSCodium's marketplace)

**Comment by root-couture** [comment]
Hi. Here the same. For me the plugins also disappear directly after a restart with the portable version 1.74.1 on an Windows 10 machine.

- Architecture: x64
- OS: Windows 10 Pro (Build 19044)
- VSCodium 1.74.1 (Release 22349

**Comment by daiyam** [comment]
@GitMensch I think we have an issue with extensions...

**Comment by daiyam** [comment]
I will try to find out what's going on. I do know I have issue with extensions when connected to a remote server.
But, on my main machine (I haven't tested my VMs), I don't have disappearing extensions.

It would very welcome if somebody else could also look into it.

**Comment by GitMensch** [comment]
Don't have disappearing extensions on .zip and win system installations, also not on Debian via package, also not in remote (but there's the "all deactivated" issue)

**Comment by LockeBirdsey** [comment]
Have disappearing extensions when installed via Scoop, both in the upgrade from 1.73.x to 1.74.x, and with clean 1.74.x installations (install extensions, close, reopen, have to reinstall extensions).
Manual portable and setup process installations work as intended though.

**Comment by daiyam** [comment]
Do you have the issue systematically when updating to 1.74.x?

**Comment by jinfar** [comment]
Same bug after updated to 1.74 using scoop.

**Comment by daiyam** [comment]
OK for `scoop`, they manage the extensions by themself and there was an update yesterday about that issue: https://github.com/ScoopInstaller/Extras/pull/10074
So for those using `scoop`, please update your install. Thx

**Comment by daiyam** [comment]
@onion108 How did you install the editor?

**Comment by onion108** [comment]
> @onion108 How did you install the editor?

just the binary from the official site

**Comment by jinfar** [comment]
> Should be fixed now!
Yes, It's working now. Thank you very much.
