### ISSUE TITLE
In Linux / Gnome the OpenFile and SaveFileAs dialogs open behind the main window

### ISSUE THREAD

**Issue by jbrepogmailcom** [VSCodium/vscodium#1356]
**Describe the bug**

When I want to open file or save text as new file, the Open and SaveAs dialogs pop up BEHIND the main windows, so they are not visible. I have to use Alt-Tab to move them to front

**Please confirm that this problem is VSCodium-specific** - Do not know
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium

**Please confirm that the issue/resolution isn't already documented** It is not
- [ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Try to open file or save as
2. file dialog not visible
3. check all open windows - you will find file dialog behind the main window

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS, Ubuntu 20.04, etc]
 - Architecture [e.g. x64, ia32, arm64]
 - Version [e.g. 1.33.0]
 - App Manager [e.g. Winget, Homebrew, Snap, AUR, RPM, Nix, ...]
 - Sandboxed [e.g. no, Flatpak, Snap]

**Additional context**

**Comment by daiyam** [comment]
@jbrepogmailcom Can you fill the section `Desktop`

**Comment by daiyam** [comment]
duplicate #1120
