### ISSUE TITLE
vscodium in Linux Mint in Parallels Desktop

### ISSUE THREAD

**Issue by digitarenet** [VSCodium/vscodium#1364]
**Describe the bug**
Display artifacts

**Please confirm that the issue/resolution isn't already documented**
- [x ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. macOS host (MacBook Pro 2018 - i9)
2. Install Parallels Desktop
3. Install Linux Mint in Parallels VM (4GB RAM + 3D acceleration enabled)
4. Install VSCodium
6. Using VSCodium, after 10-15 seconds start artifacs like in video 

**Expected behavior**
no artifacts

**Screenshots**
![VSCodium over Linux Mint over Parallels Desktop](https://user-images.githubusercontent.com/11545221/210132889-e68c8177-da95-4e92-851e-ca1fbf09fcc8.gif)

**Desktop (please complete the following information):**
 - OS: Linux Mint in VM Parallels Desktop
 - Version 1.74.2.22355

**Additional context**
Artifacts could depends on Parallels virtualization video card driver?

Thanks

**Comment by PM-Devs** [comment]
# Parallels Desktop
### The Problem you stated is a little bit  trickish.Because the flickering might be thought  as of the memory being slowed or used up. Or, try to set the Video memory to 128 not 64MB.
>So i suggest you increase the memory for the Guest OS .
>>Or here is a relevant information:
- [VM ware Parallel Desktop](https://forums.linuxmint.com/viewtopic.php?t=352623)
