### ISSUE TITLE
FYI - the website for Codium may turn people off

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [VSCodium/vscodium#137]
This is just my opinion but you might want to reconsider your website:

Just heard about your project and went to the website and was **very** surprised to see the large number of marketing type statements on the page that make it seem like it's a product you created and something more than what it really is which is an alternate build of something the VSCode people invented and built.

You might want to reconsider those marketing statements and stick to what is different about vsCodium, it looks bizarre like you're trying to take credit for someone else's work.

(didn't mean to label this as a bug, not sure how to change that sorry, it should be discussion)

**Comment by stripedpajamas** [comment]
@PalinuroSec -- can we just have the website mirror the README's text? I would definitely not want anyone getting the wrong idea.

**Comment by PalinuroSec** [comment]
The intention behind this approach was not to get credits over things we didn't made.

VSCode is an awesome software, and vscodium is its free, community driven, binary distribution.

While the github repo should provide technical information about it, the website should present the entire software as a whole, and if we distribute a free version of vscode, we should tell people what vscode/vscodium is and what features do they have.

If we remove the main vscode features from the vscodium website, how do we expect people to understand what the software can do for them? maybe we should link the visualstudio website instead, but i think a similar change should be discussed by the communty.

Maybe we can find a new idea together to keep the features list and make more explicit that such features come from vscode.

i'm just brainstorming at this point and i would like to listen your ideas as well.
I think that the content of the readme file is perfect for the github repo, but it would not be the most appropriate solution for the website, and my very personal opinion is that the website should have as its priority to be as appealing and developer-friendly as possible.

The current approach may turn people off, it's true, but i also think that a not properly designed UX would keep people away instead.

**Comment by WhatFreshHellIsThis** [comment]
"VSCode is an awesome software, and vscodium is its free, community driven, binary distribution."
Yes, this.  Stop right there, put that single line up with a link to the VSCode features page and call it done.  That's what I would do.  The rest of what you wrote I just don't get at all, I don't think you understand the dynamic here at play; you don't need to educate people about what it does, that just comes across as taking credit when they can already just go to the VSCode site to see that.

**Comment by stripedpajamas** [comment]
I removed a lot of the content that felt iffy to me for now. PRs are welcome in the [website repo](https://github.com/VSCodium/vscodium.github.io) to enumerate features of VSCode in a way that does not make it seem like we are taking credit.

**Comment by WhatFreshHellIsThis** [comment]
While I do like the one lone line at the top that states what it is, the rest beneath is still extremely problematic in my opinion.

I see no changes that would make me reconsider my original case; the rest of that page still has all the same problems as before.
I'm mystified why anyone feels the need to try to "sell" people on it, it's just a rebuild of someone else's work and on top of that someone will continually need to maintain all that unnecessary marketing stuff on that page over the years just making work for something that should not be present in the first place in my opinion.
I'm not sensing any understanding at all of how it looks from the "outside"; I guess time will tell how people react, but it sure looks like the sort of thing that developers despise and get out the "pitchforks" for.  Good luck with your project.

**Comment by stripedpajamas** [comment]
@WhatFreshHellIsThis I have a feeling you are looking at the unupdated version. vscodium.com gets updated on a cron job so it's probably not up to date yet. For my changes, look at vscodium.github.io and let me know if your comments still stand.

**Comment by WhatFreshHellIsThis** [comment]
Ahh...my mistake, didn't realize the main site wasn't updated yet, much better, I take it all back, good job!
