### ISSUE TITLE
1.74.2.23007 linux x64 tar.gz release missing

### ISSUE THREAD

**Issue by idc77** [VSCodium/vscodium#1372]
Trying to install the archlinux package

Failure while downloading https://github.com/VSCodium/vscodium/releases/download/1.74.2.23007/VSCodium-linux-x64-1.74.2.23007.tar.gz

404

Seem like you forgot to add the linux x64 build target

**Comment by daiyam** [comment]
still building...

**Comment by Shayan-Raza** [comment]
the sha256 is also incorrect. Not working with yay and the AUR

**Comment by daiyam** [comment]
still building... https://github.com/VSCodium/vscodium/actions/runs/3862247117/jobs/6584329362

**Comment by daiyam** [comment]
should be ok now

**Comment by Shayan-Raza** [comment]
testing

**Comment by Shayan-Raza** [comment]
I git cloned https://aur.archlinux.org/vscodium-bin.git just now then ran the command
![image](https://user-images.githubusercontent.com/99135614/211158798-0a8f091a-c9d1-42fc-9485-bf0b0b302ec8.png)

**Comment by daiyam** [comment]
Ya, we don't manage the `vscodium-bin`. The error is due to that I had to release a quick fix during the release so I had to scrap the one which was ongoing. So there is a need to update the hashes since the binaries have changed.

**Comment by Shayan-Raza** [comment]
Works now thanks
