### ISSUE TITLE
Unable to upgrade VScodium from 1.74.2.22355

### ISSUE THREAD

**Issue by maxtymchenko** [VSCodium/vscodium#1373]
**Describe the bug**
Unable to update VSCodium from 

Version: 1.74.2 (system setup)
Release: 22355
Commit: d2c422ca15f1fbc976eed3e02e3392bbb39c5824
Date: 2022-12-21T18:33:19.960Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

to the latest one use internal upgrade option (Help -> Check for updates).

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to main VScodium window
2. Click on "Help -> Check for updates"
3. See error

**Expected behavior**
VScodium upgrade successful

**Screenshots**
![image](https://user-images.githubusercontent.com/89496287/211196039-858de24f-7fca-40c0-89e6-a9571d58107e.png)

**Desktop (please complete the following information):**
Version: 1.74.2 (system setup)
Release: 22355
Commit: d2c422ca15f1fbc976eed3e02e3392bbb39c5824
Date: 2022-12-21T18:33:19.960Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

**Additional context**
It looks exactly thew same issue for VSCode described here :
https://github.com/microsoft/vscode/issues/164278

and the root cause described as "There were two Publish builds on the same commit"

**Comment by daiyam** [comment]
@maxtymchenko About "There were two Publish builds on the same commit", I thought you were talking in the case the remote ssh which would have been the case is you had updated to a bad `1.74.2.23007` version. Not the case here.

**Comment by daiyam** [comment]
I confirm the bug!

**Comment by maxtymchenko** [comment]
@daiyam no I have not updated to any 1.74.2.23007 (neither good or bad) due to this bug so it's not about the remote ssh case - I apologize for possible misunderstanding.

As of "There were two Publish builds on the same commit" it is a copy&paste from this comment :

https://github.com/microsoft/vscode/issues/164278#issuecomment-1290198443

and it was related to update the VScode in general (not addons).

**Comment by daiyam** [comment]
The issue was due to my botched update of yesterday. The second release didn't update the hashes for the update service so it was still using those from the first (deleted) release. I've updated them but I can several minutes for the cache to refresh.

**Comment by daiyam** [comment]
It should be good now!

**Comment by maxtymchenko** [comment]
Thank you @daiyam - it works OK now.
