### ISSUE TITLE
Latest Version is not available on winget package manager

### ISSUE THREAD

**Issue by LEFD** [VSCodium/vscodium#1375]
**Describe the bug**
Latest version of vscodium on winget package manager is 1.73.1.22314.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. open terminal
2. run `winget search vscodium`
3. latest verison is 1.73.1.22314

**Desktop (please complete the following information):**
 - OS: Windows 10
 - x64
 - Winget

**Comment by daiyam** [comment]
Oh! There is an error in the winget release without between an error...

**Comment by daiyam** [comment]
The latest version should be available.

**Comment by LEFD** [comment]
Awesome! Tho I insiders release seems broken as well.

**Comment by daiyam** [comment]
Ya, there was the same error but there a new error with the Insiders. `SyntaxError: Unexpected string` at `this.n.label2null"Create on GitHub");` due to some process replacing the i18n string with substitutes. But, it is broken for VSCodium on windows! A pain in the ass...
