### ISSUE TITLE
vscodium basic loop bug

### ISSUE THREAD

**Issue by Nasty76** [VSCodium/vscodium#1378]
i have code: 

```
uinput = 11# int(input("give number:"))
run = 2

while run<=uinput:
    print(run)
    run-=1
    print(run)
    run+=3
    if run>uinput:
        if (uinput %2) == 0:
            pass
        else:
            print(uinput)
 ```
it work like expected , but if i change uinput  =12 its print:
```
1
4
3
6
5
8
7
10
9
12
11
```
but if i put after `run+=3`  `input()` its print again what i expect to print.
if i run this direct windows cmd python test.py code work as expected only i get this error with codium.

**Comment by NovaliX-Dev** [comment]
Did you try on VSCode to see if the issue is there as well ?

_Btw please use the bug template next time, as it helps us to find the problem_

**Comment by daiyam** [comment]
https://unix.stackexchange.com/questions/164987/output-of-a-python-script-running-as-unit-is-out-of-order-while-shells-seems-unn
