### ISSUE TITLE
[Question] portable mode

### ISSUE THREAD

**Issue by tweak-wtf** [VSCodium/vscodium#138]
Hey folks,
just wondering if it is possible to launch this in portable mode?
I'm on macOS and followed the instructions on the official microsoft site here:
https://code.visualstudio.com/docs/editor/portable

Also removed VSCodium from possible quarantine attribute but it won't work.

Any suggestions?

**Comment by stripedpajamas** [comment]
Cool! I'm not sure if anyone has tried this yet, so I'm excited to get it working. When you followed Microsoft's instructions, what did you name the data folder? `code-portable-data`?

**Comment by tweak-wtf** [comment]
Jup simply called it `code-portable-data`
Tried to install the python extension and cobalt2 color theme. I assumed they would land in that folder.
Will se how it works with vanilla VSCode on macOS since I only used portable mode on linux yet

**Comment by stripedpajamas** [comment]
Can you try naming the folder either `vscodium-portable-data` or `code-oss-portable-data`?

**Comment by tweak-wtf** [comment]
haha `vscodium-portable-data` works just fine :)

**Comment by tweak-wtf** [comment]
`code-oss-portable-data` seems not to work on my machine

So stick with `vscodium-portable-data`. Thanks! :)

**Comment by stripedpajamas** [comment]
Awesome! I will leave this open so we can update the DOCS.md file with a tip about this.

**Comment by tweak-wtf** [comment]
perfect... thanks for the wuick help :)
