### ISSUE TITLE
Microsoft Live Preview not present in search results

### ISSUE THREAD

**Issue by quazar-omega** [VSCodium/vscodium#1385]
**Describe the bug**
The [live preview](https://open-vsx.org/extension/ms-vscode/live-server) extension doesn't show in the results when searching.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to the extensions tab
2. Search 'live preview'

**Expected behavior**
The extension should be present since it is on Open VSX

**Screenshots**
![image](https://user-images.githubusercontent.com/56311398/214456307-c9693f7a-1a28-445a-9ef6-8838d9d4d6af.png)

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue 37
 - Architecture: x64
 - Version: 1.74.3
 - App Manager: RPM/Flatpak
 - Sandboxed: Distrobox (Podman)/Flatpak

**Comment by StefanLobbenmeier** [comment]
https://github.com/VSCodium/vscodium/blob/master/DOCS.md#howto-vscode-marketplace

**Comment by quazar-omega** [comment]
@StefanLobbenmeier why should I use the Microsoft marketplace if Live Preview is on Open VSX?

**Comment by StefanLobbenmeier** [comment]
I am sorry, i did not see the open vsx mentioned in your post. Then it is quite strange. In #418 there is a similar issue and they ended up using the Microsoft marketplace. Not sure why it does not work, maybe you need to ask in open vsx too.

**Comment by quazar-omega** [comment]
No worries, thanks for the links, I'll check them out and see what I can do
