### ISSUE TITLE
VSCodium Insiders not building for Windows

### ISSUE THREAD

**Issue by 0x00A1FA** [VSCodium/vscodium#1386]
What's the status on this?

**Comment by daiyam** [comment]
https://github.com/VSCodium/vscodium/pull/1370
https://github.com/jeanp413/open-remote-ssh/issues/44

**Comment by daiyam** [comment]
@GitMensch I've removed the mangle in the latest Insiders version. Could you test it if the remote ssh is still working for you? (it's fine for my tests).
