### ISSUE TITLE
Copilot failing to connect in VS Codium

### ISSUE THREAD

**Issue by DjSapsan** [VSCodium/vscodium#1388]
Hi. I just got Copilot and trying to use it in VS Codium. It is not available in the store so I downloaded and installed .VSIX file. Other extensions installed in this way are working perfectly fine, excep Copilot.
The error I have:

Invalid copilot token: missing token: 404
GitHub Copilot could not connect to server. Extension activation failed: "User not authorized"
And a pop-up
![Screenshot_20230125_232320](https://user-images.githubusercontent.com/12209464/214694997-900045ca-11b9-4983-a158-4a1575bc0251.png)

**Comment by lyrek** [comment]
There is a tutorial here on how to get GitHub Copilot to work in VSCodium. Let me know if you get it working as I'm also interested in using Copilot in VSCodium!
https://prose.bentopais.pt/vscodium-and-copilot

**Comment by zeronyk** [comment]
Worked for me!

Thank you so much for this Link, just sad that it does not show up on the first google entry when you type "vscode github-copilot"

**Comment by StitiFatah** [comment]
I can confirm it works, you have to install vscode first, and I personally didn't find the same snippet, I console.logged `t.token` and `r.token` from similar looking ones to get the needed token.

**Comment by EricBoily** [comment]
I agree with @StitiFatah, It works with his tweak.  The search I used is `{headers:{Authorization:`token ${t.token}` ,  then I found the next `;`  (couple line below) and then added the `console.log(t.token);`

**Comment by rafek1241** [comment]
This approach is no longer valid as the VSCODE in latest version use github authentication instead

**Comment by gdinh** [comment]
Current error I'm getting is 'token not found'. Looking at the files mentioned in the articles above, the lines mentioned in the article have changed from:

```
{headers:{Authorization:`token ${t}`}});
```

to:

```
{headers:{Authorization:`token ${t.token}`,...(0,i.editorVersionHeaders)(e)}}
```

I know very little about js, but it seems like this is related to a change in how tokens are stored in the keychain.

I looked at keychain access on my mac, and the `vscodiumvscode.github-authentication` looks like:

```{"extensionId":"vscode.github-authentication","content":"[{\"id\":\"0123456789abcdef\",\"accessToken\":\"ghp_pastedPATtokenalphanumericstring\",\"account\":{\"label\":\"gdinh\",\"id\":12345678},\"scopes\":[\"user:email\"]}]"}```

whereas `vscodevscode.github-authentication` is a long alphanumeric string (letters, numbers, /, +, and = characters); not sure how it's encoded. Not sure if this is the issue; hopefully someone with a better understanding of the VSCod(ium) auth system can comment.

Has anybody tried to use an older version of the extension to see if the authentication issue related to the extension version or the codium version?

**Comment by jmainhard** [comment]
> to:
>
> ```
> {headers:{Authorization:`token ${t.token}`,...(0,i.editorVersionHeaders)(e)}}
> ```
> 
> I know very little about js, but it seems like this is related to a change in how tokens are stored in the keychain.

I managed to get the token (and connect Copilot) adding the `console.log` a little before, just at the start of the `try`
Search for the corresponding `try` and add this:

```javascript
try{console.log(t); return await e.get(a.Fetcher).fetch(n,{headers:{Authorization:`token ${t.token}`,...(0,i.editorVersionHeaders)(e)}})}catch(t){throw e.get(o.UserErrorNotifier).notifyUser(e,t),t}}(e,t);
```

You also could add it as a new statement just like @EricBoily mentions before

> I agree with @StitiFatah, It works with his tweak. The search I used is `{headers:{Authorization:`token ${t.token}`, then I found the next`;` (couple line below) and then added the`console.log(t.token);`

For example:
```javascript
catch(t){throw e.get(o.UserErrorNotifier).notifyUser(e,t),t}}(e,t); console.log(t); // [...]
```

**Comment by gebeer** [comment]
Is there any chance that vscodium will get out f the box support for copilot? It seems like the hacks mentioned might only work temporarily.

**Comment by stdedos** [comment]
Is there a way to remove the token I have entered before?

Seems that there's no option to "re-authenticate"
![image](https://user-images.githubusercontent.com/133706/231405744-6f3eaa3d-144f-43a0-a8e8-5de6abb54227.png)

The token is not in "plain settings"

and, `Developer: Reinstall Extension` does not work, since GHC is not a Marketplace extension 😖

**Comment by jmainhard** [comment]
> Is there a way to remove the token I have entered before?
> 
> Seems that there's no option to "re-authenticate" ![image](https://user-images.githubusercontent.com/133706/231405744-6f3eaa3d-144f-43a0-a8e8-5de6abb54227.png)
> 
> The token is not in "plain settings"
> 
> and, `Developer: Reinstall Extension` does not work, since GHC is not a Marketplace extension confounded ![image](https://user-images.githubusercontent.com/133706/231406327-c45f6d65-7379-4390-a824-3ec3ae672883.png)

(I don't know about Windows) With Gnome Keyring you could delete the token like this (I'm using Seahorse):

![image](https://user-images.githubusercontent.com/63559099/231458281-5cd628a8-ef93-4711-9bf9-4d1c708a93d5.png)

**Comment by daiyam** [comment]
@stdedos You should be able to see this:
![Screen Shot 2023-04-12 at 4 09 08 PM](https://user-images.githubusercontent.com/587742/231484420-5b4a9add-e0a0-4691-be34-b8a85014586b.jpg)

**Comment by stdedos** [comment]
Yes, that's visible too. "But how could I know, I've never needed that". (Usually _all_ actions are in the Command Palette 😅)

**Comment by wleoncio** [comment]
Finally got it working first by deleting my key (thanks @jmainhard!), then using the token generated by the MS-tainted VSCode installation (see https://github.com/VSCodium/vscodium/issues/1388#issuecomment-1484476693, props to @jmainhard again).

With the ChatGPT extension and GH Copilot in place, I just need to quit my habit of opening a browser and searching for help with my coding. 😅

**Comment by charalamm** [comment]
For those trying to find the `Check vscode's logs (help > developer tools > console);` in VSCode:
* Open the developer tools from `Help > Toggle Developer Tools` 
* Go to the `Console` tab
* Find the `[Extension Host]%> Object` and click it to expand it and the token will be there

**Comment by wleoncio** [comment]
> Is the chatgpt extension (if yes which one ?) doing anything more than providing the same GUI as the official one but in the editor ? Otherwise there are plenty of CLI clients to avoid having to use a browser. I'm currently using https://github.com/sigoden/aichat

A CLI solution is interesting for off-VSC activity, but since most of my coding happens in there, I use the [ChatGPT - Genie AI](https://marketplace.visualstudio.com/items?itemName=genieai.chatgpt-vscode) extension, which is nicely integrated into the editor.

**Comment by StitiFatah** [comment]
> > Is the chatgpt extension (if yes which one ?) doing anything more than providing the same GUI as the official one but in the editor ? Otherwise there are plenty of CLI clients to avoid having to use a browser. I'm currently using https://github.com/sigoden/aichat
> 
> A CLI solution is interesting for off-VSC activity, but since most of my coding happens in there, I use the [ChatGPT - Genie AI](https://marketplace.visualstudio.com/items?itemName=genieai.chatgpt-vscode) extension, which is nicely integrated into the editor.

Does it interact directly with your code (maybe by selecting it then opening a pop up window with the code already in the prompt) ? If yes might be interesting, otherwise Vsc has an integrated terminal too

**Comment by wleoncio** [comment]
> Does it interact directly with your code (maybe by selecting it then opening a pop up window with the code already in the prompt) ?

Yes, it does. Here's a list of commands:

![image](https://user-images.githubusercontent.com/8234768/232684642-47baf14a-80ae-4f85-bdaa-ab3c1000eefb.png)

And some buttons to paste generated code from the chat window into the editor:

![image](https://user-images.githubusercontent.com/8234768/232685176-dd6f17af-fa65-417c-baf2-0c39b146d110.png)

**Comment by StitiFatah** [comment]
> > Does it interact directly with your code (maybe by selecting it then opening a pop up window with the code already in the prompt) ?
> 
> Yes, it does. Here's a list of commands:
> 
> ![image](https://user-images.githubusercontent.com/8234768/232684642-47baf14a-80ae-4f85-bdaa-ab3c1000eefb.png)
> 
> And some buttons to paste generated code from the chat window into the editor:
> 
> ![image](https://user-images.githubusercontent.com/8234768/232685176-dd6f17af-fa65-417c-baf2-0c39b146d110.png)
> 

Thanks, seems cool

**Comment by wleoncio** [comment]
> is it a thing vscodium would need to explicitly support for it to work normally

I think it's technically possible for VSCodium to support Copilot without all this hacking. Copilot worked out-of-the-box on my Arch laptop running [Code - OSS](https://github.com/microsoft/vscode), so perhaps all VSCodium would need to do is to change something on their build script.

Given how relevant Copilot has become, perhaps the VSCodium distributors should make their support plans explicit on the [VSCodium main page](https://vscodium.com/): if there are no plans to change the build scripts to support Copilot (perhaps it would involve allowing some nasty MS telemetry in), potential users should be advised to build VSC from source themselves.

**Comment by gebeer** [comment]
> > is it a thing vscodium would need to explicitly support for it to work normally
> 
> I think it's technically possible for VSCodium to support Copilot without all this hacking. Copilot worked out-of-the-box on my Arch laptop running [Code - OSS](https://github.com/microsoft/vscode), so perhaps all VSCodium would need to do is to change something on their build script.
> 
> Given how relevant Copilot has become, perhaps the VSCodium distributors should make their support plans explicit on the [VSCodium main page](https://vscodium.com/): if there are no plans to change the build scripts to support Copilot (perhaps it would involve allowing some nasty MS telemetry in), potential users should be advised to build VSC from source themselves.

Exactly. Given the popularity of Copilot, the vscodium maintainers should really address this asap.

**Comment by StitiFatah** [comment]
Thanks for letting me know, I'm on Arch too and just installed code, it's working fine but I had to to run it via `code --enable-proposed-api GitHub.copilot` 
Although I've installed code-marketplace package which enable the MS store. 

Unfortunately code isn't the same as vscodium privacy wise.

**Comment by daiyam** [comment]
About `extensionEnabledApiProposals`, VSCodium should be the same as VSCode since we are copying it directly from its archive (https://github.com/VSCodium/vscodium/blob/master/build/update_api.sh)

AUR Code uses the protocol `vscode` which helps to be more compatible with a normal VSCode (and with its name, since some extensions are checking the editor name) but becomes incompatible with VSCode since they are using the same protocol...
VSCodium use the protocal `vscodium` so both editors can run on the same machine.

All is about how to the authentication, by default, VSCode calls a web service on github which reply with an url with `vscode` as the protocol. We tried to pass the return url, does change it. So we decided to scrap the whole process and to go directly to PAT.

**Comment by Aspyryan** [comment]
But PAT tokens seem to always fail for me, it still says user not authenticated even when I am correctly signed in and have access to copilot!

**Comment by StitiFatah** [comment]
> But PAT tokens seem to always fail for me, it still says user not authenticated even when I am correctly signed in and have access to copilot!

Just retried yesterday and it worked fine, it wasn't working at first although I got the toke  but then I updated copilot on both Vscode and Vscodium and it fixed it, maybe make sure you have the same version in both.

**Comment by daiyam** [comment]
@Aspyryan Have you followed https://github.com/VSCodium/vscodium/discussions/1487?

**Comment by Aspyryan** [comment]
> @Aspyryan Have you followed #1487?

Thanks, this worked!

**Comment by jeremiah-k** [comment]
I was able to get my token, thank you for that. But where do I re-enter it?  I can't find anywhere in extension settings, I've uninstalled/reinstalled the extension, etc.

**Comment by StitiFatah** [comment]
> I was able to get my token, thank you for that. But where do I re-enter it?  I can't find anywhere in extension settings, I've uninstalled/reinstalled the extension, etc.

When you have copilot and you aren't logged in you have a pop-up in the bottom right corner asking you to connect, you click on "connect", it'll then redirect you to your browser, you ignore that since you already have your token, you'll then have an input box in the top asking you for your token and just past it here.

**Comment by jeremiah-k** [comment]
> > I was able to get my token, thank you for that. But where do I re-enter it?  I can't find anywhere in extension settings, I've uninstalled/reinstalled the extension, etc.
> 
> (On vscodium) When you have copilot and you aren't logged in you have a pop-up in the bottom right corner asking you to connect, you click on "connect", it'll then redirect you to your browser, you ignore that since you already have your token, you'll then have an input box in the top asking you for your token and just past it here.

Ok, I'm getting a different message in the Output tab.  It's no longer saying that I don't have access, it's saying:
`[INFO] [copilotIgnore] [2023-04-22T06:32:47.367Z] inactive`

Do I still have to activate it somewhere else?

**Comment by StitiFatah** [comment]
> > > I was able to get my token, thank you for that. But where do I re-enter it?  I can't find anywhere in extension settings, I've uninstalled/reinstalled the extension, etc.
> > 
> > (On vscodium) When you have copilot and you aren't logged in you have a pop-up in the bottom right corner asking you to connect, you click on "connect", it'll then redirect you to your browser, you ignore that since you already have your token, you'll then have an input box in the top asking you for your token and just past it here.
> 
> Ok, I'm getting a different message in the Output tab.  It's no longer saying that I don't have access, it's saying:
> `[INFO] [copilotIgnore] [2023-04-22T06:32:47.367Z] inactive`
> 
> Do I still have to activate it somewhere else?

You got that after you pasted the token in the input form of vscodium ?

**Comment by jeremiah-k** [comment]
Yes

> > > > I was able to get my token, thank you for that. But where do I re-enter it?  I can't find anywhere in extension settings, I've uninstalled/reinstalled the extension, etc.
> > > 
> > > 
> > > (On vscodium) When you have copilot and you aren't logged in you have a pop-up in the bottom right corner asking you to connect, you click on "connect", it'll then redirect you to your browser, you ignore that since you already have your token, you'll then have an input box in the top asking you for your token and just past it here.
> > 
> > 
> > Ok, I'm getting a different message in the Output tab.  It's no longer saying that I don't have access, it's saying:
> > `[INFO] [copilotIgnore] [2023-04-22T06:32:47.367Z] inactive`
> > Do I still have to activate it somewhere else?
> 
> You got that after you pasted the token in the input form of vscodium ?

Yes.

**Comment by StitiFatah** [comment]
> Yes
> 
> > > > > I was able to get my token, thank you for that. But where do I re-enter it?  I can't find anywhere in extension settings, I've uninstalled/reinstalled the extension, etc.
> > > > 
> > > > 
> > > > (On vscodium) When you have copilot and you aren't logged in you have a pop-up in the bottom right corner asking you to connect, you click on "connect", it'll then redirect you to your browser, you ignore that since you already have your token, you'll then have an input box in the top asking you for your token and just past it here.
> > > 
> > > 
> > > Ok, I'm getting a different message in the Output tab.  It's no longer saying that I don't have access, it's saying:
> > > `[INFO] [copilotIgnore] [2023-04-22T06:32:47.367Z] inactive`
> > > Do I still have to activate it somewhere else?
> > 
> > You got that after you pasted the token in the input form of vscodium ?
> 
> Yes.

Be sure your vscodium and Vscode version of copilot are both up to date, I had an error 2 days ago because of that

**Comment by jeremiah-k** [comment]
> Be sure your vscodium and Vscode version of copilot are both up to date, I had an error 2 days ago because of that

This is my first time trying Copilot, so I wasn't sure what to expect. I'm using version 1.83.41 downloaded fresh from https://marketplace.visualstudio.com/items?itemName=GitHub.copilot

I followed the instructions in #1487 

`VSCODIUM_FOLDER/resources/app/product.json` is still modified, if that makes a difference.  Other than that everything the way that it was shipped and it's up to date.

**Comment by StitiFatah** [comment]
> > Be sure your vscodium and Vscode version of copilot are both up to date, I had an error 2 days ago because of that
> 
> This is my first time trying Copilot, so I wasn't sure what to expect. I'm using version 1.83.41 downloaded fresh from https://marketplace.visualstudio.com/items?itemName=GitHub.copilot
> 
> I followed the instructions in #1487 
> 
> `VSCODIUM_FOLDER/resources/app/product.json` is still modified, if that makes a difference.  Other than that everything the way that it was shipped and it's up to date.
> 
> Edit:  I'm using Codium Insiders - 1.78.0-insider

I haven't used the #1487 method to get the token, I got it from MS Vscode, don't know if there's any difference. 

And I'm not using vscodium-insiders but the regular version from the AUR. 

My products.json is also modified to get the official marketplace. 

If it can help.

**Comment by psipherious** [comment]
I followed the method at #1487 as well and it worked perfectly for connecting VS Codium without the need to do anything in VS Code.

I did this on Windows myself and initially had an issue in both Command Prompt & Powershell with curl errors.

Ended up resolving that problem by simply using the MING64 based Git Bash as part of the Git Windows package found at:
https://git-scm.com/

**Comment by CedHild** [comment]
> > Is there a way to remove the token I have entered before?
> > Seems that there's no option to "re-authenticate" ![image](https://user-images.githubusercontent.com/133706/231405744-6f3eaa3d-144f-43a0-a8e8-5de6abb54227.png)
> > The token is not in "plain settings"
> > and, `Developer: Reinstall Extension` does not work, since GHC is not a Marketplace extension confounded ![image](https://user-images.githubusercontent.com/133706/231406327-c45f6d65-7379-4390-a824-3ec3ae672883.png)
> 
> (I don't know about Windows) With Gnome Keyring you could delete the token like this, I'm using Seahorse:
> 
> ![image](https://user-images.githubusercontent.com/63559099/231458281-5cd628a8-ef93-4711-9bf9-4d1c708a93d5.png)

On windows, the key can be deleted in the windows "Credential Manager". this logs out the user too.
