### ISSUE TITLE
Distribute versions for macOS as `dmg` files instead of zip

### ISSUE THREAD

**Issue by eirnym** [VSCodium/vscodium#139]
**Describe the bug**
Distribute versions for macOS as `dmg` files instead of zip. They have self-consistency check on mounting and more user-friendly features.

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to Downloads page
2. Check the latest distributions
4. See that version for macOS is distributed as zip archive.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Architecture x64
 - Version 1.33.0

**Additional context**

**Comment by stripedpajamas** [comment]
Hi @eirnym -- I like `dmg` better than `zip` as well. As Microsoft does not currently offer a `dmg` for Visual Studio Code, we would be starting from scratch. PRs are welcome toward this goal.
