### ISSUE TITLE
How to download updates from the specified source instead of GitHub release

### ISSUE THREAD

**Issue by stackinspector** [VSCodium/vscodium#1399]
The `update-api` seems to [hardcode the GitHub release URL](https://github.com/VSCodium/update-api/blob/master/api/update/index.js#L42). So to download updates from the specified source, it seems that another update api needs to be built and the update url in product.json needs to be modified. Is it possible to modify the product.json directly in the installed VSCodium without recompiling?

**Comment by daiyam** [comment]
The update url is defined here: https://github.com/VSCodium/vscodium/blob/9ad93a467b65a407137107025c464a17110cb0a6/prepare_vscode.sh#L105

Not sure what's the issue? Maybe related to https://github.com/VSCodium/vscodium/issues/1227
