### ISSUE TITLE
Needs build instructions

### ISSUE THREAD

**Issue by caioalonso** [VSCodium/vscodium#14]
It would be nice to have some instructions for manually building vscodium on each OS.

**Comment by stripedpajamas** [comment]
Hi @caioalonso -- VSCodium is just a repo of build scripts to automate the build process of [Microsoft's vscode](https://github.com/Microsoft/vscode). To manually build, head over to Microsoft's repo and following their [build instructions](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source). The finished products (the manual build of Microsoft's vscode repo and the [VSCodium binaries](https://github.com/VSCodium/vscodium/releases)) are the same, assuming you add Microsoft's marketplace links in the `product.json` file, as [mentioned in the readme](https://github.com/VSCodium/vscodium#extensions--marketplace).
