### ISSUE TITLE
vscodium apparently not supported by yyx990803/launch-editor

### ISSUE THREAD

**Issue by kirisakow** [VSCodium/vscodium#140]
I can't see vscodium editor among the supported editors in Evan You's launch-editor.
Pair issue created: yyx990803/launch-editor#12
 (Thank you for what you do, no matter what)

**Comment by kirisakow** [comment]
Fork created and proposal submitted: 
https://github.com/yyx990803/launch-editor/commit/b9af8c1c41050dd5f23642149262715fee730e10

**Comment by kirisakow** [comment]
README.md update proposed:
https://github.com/yyx990803/launch-editor/commit/253d3ebef9afb476d702fc2732e37d1535aea942

**Comment by stripedpajamas** [comment]
Hey @kirisakow I don't think there's anything to do on the VSCodium side, and I see you opened the necessary PR to launch-editor (thanks for doing that 👍 ), so I'm gonna go ahead and close this out. If you think anything needs to happen on this end just let me know and I can reopen.
