### ISSUE TITLE
License Update/Switch from MIT to copyleft license.

### ISSUE THREAD

**Issue by gochev** [VSCodium/vscodium#1402]
**Describe the bug**
Why dont we switch to a different non MIT license ? Why VScodium dont use copyleft license that FORBIDS microsoft for doing shits like "having a closed source vs code" ? 

This way microsoft cannot pull any code changes and fixes in vscodium for free.

**Please confirm that this problem is VSCodium-specific**
- Currently Microsoft are splitting the community like they always do, they did it with MFC, they tried with J++, they do it with typescript and so on. VSCodium is great but why we are helping them giving them the ability to pull changes from vscodium codebase into vscode. Lets switch to a GPL for exampel or any copyleft license which will give us the ability to take vscode code but will stop them from taking vscodium code into vs code.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Start vscodium or visit github repo
2. check license
3. it says MIT which only helps Microsoft

**Expected behavior**
1. to use copyleft license which forbids microsoft to use an open source community for propriatary product and do shits like they always do.

**Screenshots**
Do not believe it is relevant

**Desktop (please complete the following information):**
 - OS: Mac OS, Linux, Windows
 - Architecture x64, ia32, arm64
 - Version all
 - App Manager all
 - Sandboxed or native packages, installers , Flatpak, Snap everything

**Additional context**

My main problem is already explained. MIT allows microsoft to have a closed source, patched, telemetry/tracking included version of vscode. VSCodium helps by having a clear version but it also helps them I want an open source community driven version of vscode, so the idea is to have a license where we can take all changes from them but they cannot take any code change from us without beeing fully free and open source.

**Comment by daiyam** [comment]
Microsoft owns Visual Studio Code so they can do whatever they want. If VSCodium moves from MIT to GPL, it won't matter and won't impact the licensing of Visual Studio Code.
While I don't like their play with closed sourced extensions, it's up to them. Can't do nothing about that.

> I want an open source community driven version of vscode, so the idea is to have a license where we can take all changes from them but they cannot take any code change from us without beeing fully free and open source.

You should look at https://github.com/eclipse-theia/theia which is done by the team behind OpenVSX.

**Comment by gochev** [comment]
Hello @daiyam  yes already using theia, the point is that if VSCODIUM is GPL then every pull request or fix that have been done on VSCODIUM will not be able to be pulled back into VSCode.

**Comment by goldingdamien** [comment]
Does this repository have any features, or is it planned for this repository to have any features, that Microsoft may want to put into vscode?

**Comment by daiyam** [comment]
@daiyam no
