### ISSUE TITLE
Can't find "CMake Tools" extension even though it is available in OpenVSX

### ISSUE THREAD

**Issue by GRAPHENE9932** [VSCodium/vscodium#1403]
**Describe the bug**
By typing "CMake Tools" search request on the extensions tab the "CMake Tools" extension doesn't show up.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to the extensions tab.
2. Search for CMake Tools.
3. See that there are no CMake Tools
4. See that it is available in OpenVSX (https://open-vsx.org/extension/ms-vscode/cmake-tools)

**Expected behavior**
The "CMake Tools" extension must show up after search.

**Screenshots**
![image](https://user-images.githubusercontent.com/62153908/217734602-27d469d5-e0ba-4958-b92e-d33b4bed3e08.png)
![image](https://user-images.githubusercontent.com/62153908/217734684-3ad6af32-d6d1-4dd6-b592-60db385ba9e9.png)

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Architecture: x86_64
 - Version: 1.75.0
 - App Manager: dnf
 - Sandboxed: no

**Comment by LumiereDeLOmbre** [comment]
"glad" I am not alone in this case

**Comment by smellymoo** [comment]
what do I do now? I have same problem.

**Comment by daiyam** [comment]
It seems to be an issue with OpenVSX.
You can `Download` the vsix from the page then, in VSCodium, do `Install from VSIX...`

**Comment by smellymoo** [comment]
thanks! it's great that it's so compatible with VSCode, I assumed it wouldn't work.

**Comment by filiptronicek** [comment]
Hey all, Open VSX maintainer here 👋

We will be looking into this issue more closely, but until we do, you can install the extension by searching for `@id:ms-vscode.cmake-tools` in the extension search bar.

**Comment by shanmukhateja** [comment]
@daiyam  This ticket can be marked as closed as the linked issue has been fixed.
