### ISSUE TITLE
VSCodium update available but to prior release

### ISSUE THREAD

**Issue by scottfurry** [VSCodium/vscodium#1405]
**Describe the bug**
Version 1.75.1 Release# 23040 installed on Gentoo X86_64 system without error or observed problems. Extensions were updated without issue.

However, on every restart, VSCodium indicates that an update is available but that update is to prior release (v1.75.0 R# 23033).

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Update Existing VSCodium to latest (v1.75.1 R#23040)
2. Restart VSCodium
3. Observe Settings icon (lower left on primary side bar)
4. A digit will be presented indicating update is available.
5. Downloading update will provide a url to prior release for system in question 

**Expected behavior**
No update should be offered for latest release.

**Desktop (please complete the following information):**
 - OS: Gentoo
 - Architecture x64
 - Version 1.75.1
 - App Manager portage
 - Sandboxed No

**Additional context**
About Dialog
```
Version: 1.75.1
Release: 23040
Commit: c6a9727b801542499d2b59cb7db4224e060fc578
Date: 2023-02-09T22:41:50.017Z
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.88-gentoo-x86_64
Sandboxed: No
```

**Comment by daiyam** [comment]
@scottfurry No just for you, I have also the issue on macos. It seems like the update server hasn't taken the updated version files
@stripedpajamas Could you take a look or restart the service on vercel?

**Comment by scottfurry** [comment]
Problem appears resolved.
