### ISSUE TITLE
the VSCodium-x64-1.75.1.23040.msi seems to be corrupted when testing on the SHA256 file

### ISSUE THREAD

**Issue by dma61** [VSCodium/vscodium#1406]
**Describe the bug**
the VSCodium-x64-1.75.1.23040.msi seems to be corrupted when testing on the SHA256 file

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce** python: 
from Crypto.Hash import SHA256

def verify_file_integrity(file_path, hash_file_path):
    # Read the hash from the .sha256 file
    with open(hash_file_path, 'r') as hash_file:
        expected_hash = hash_file.read().strip()

    # Compute the hash of the .msi file
    with open(file_path, 'rb') as file:
        file_hash = SHA256.new(file.read()).hexdigest()

    # Compare the expected hash with the computed hash
    return file_hash == expected_hash

# Paths to the .msi file and .sha256 file
msi_file_path = r'C:\Users\###\Downloads\VSCodium-x64-1.75.1.23040.msi'
hash_file_path = r'C:\Users\###\Downloads\VSCodium-x64-1.75.1.23040.msi.sha256'

# Check the integrity of the .msi file
if verify_file_integrity(msi_file_path, hash_file_path):
    print("The file is valid and has not been tampered with.")
else:
    print("The file has been modified and its integrity is compromised.")

**Expected behavior**
The file is valid and has not been tampered with

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - Architecture x64, 
 - Version [e.g. 1.33.0]
 - App Manager [e.g. Winget, Homebrew, Snap, AUR, RPM, Nix, ...]
 - Sandboxed [e.g. no, Flatpak, Snap]

**Additional context**

**Comment by daiyam** [comment]
from your code:
- `file_hash` = `10f5c95301f04bf6ba19d4feb69fb540e672c074c90b41da60d17da0e8d48717`
- `expected_hash` = `10f5c95301f04bf6ba19d4feb69fb540e672c074c90b41da60d17da0e8d48717  VSCodium-x64-1.75.1.23040.msi`

The content of `VSCodium-x64-1.75.1.23040.msi.sha256` is `10f5c95301f04bf6ba19d4feb69fb540e672c074c90b41da60d17da0e8d48717  VSCodium-x64-1.75.1.23040.msi`

doc: https://en.wikipedia.org/wiki/Sha1sum

**Comment by antichris** [comment]
Does not reproduce:

```sh
sha256sum -c VSCodium-x64-1.75.1.23040.msi.sha256 
```
```plain
VSCodium-x64-1.75.1.23040.msi: OK
```

PEBKAC. Issue can be closed.
