### ISSUE TITLE
Extensions don't work

### ISSUE THREAD

**Issue by s1nistr4** [VSCodium/vscodium#1413]
**Describe the bug**

On a stock install of VSCodium on Fedora 37, extensions don't work.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install VSCodium
2. Open extensions page
3. It's stuck on an infinite loading screen

**Expected behavior**
For the extensions page to work 

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Architecture: x86_64
 - Version: Latest
 - App Manager: None, installed it from the releases page

**Comment by daiyam** [comment]
It's working
