### ISSUE TITLE
vs codiun menu's bugged

### ISSUE THREAD

**Issue by beastr45** [VSCodium/vscodium#1416]
when running vscodium on linux sometimes the top menu gets bugged and the only way to use the file,edit,selection,view etc. buttons again is to restart vscodium. This issue happens after resizing the window

**Comment by GitMensch** [comment]
Please specify complete version output (Help->Info).
Also: what does "sometimes" mean?
Have you tested if this isn't happening with upstream vscode? It seems to be a more general issue.

**Comment by daiyam** [comment]
Well, it's linux so we will also need the linux version, the DE version
