### ISSUE TITLE
Extension dependency not found

### ISSUE THREAD

**Issue by brunnerh** [VSCodium/vscodium#1417]
Type: <b>Bug</b>

I have [an extension](https://github.com/brunnerh/altervista-thesaurus) which has a dependency on `node-fetch`, this dependency apparently is not installed or not found. Issue reported here:
- https://github.com/brunnerh/altervista-thesaurus/issues/7

Is this just not supported in general or is there an issue with my extension or the dependency?
_Edit_: Just checked [another extension](https://github.com/brunnerh/file-properties-viewer) of mine which has various dependencies, and those work as expected.

VSCodium version: VSCodium 1.75.1 (c6a9727b801542499d2b59cb7db4224e060fc578, 2023-02-09T22:46:15.410Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
altervista-thesaurus|bru|0.2.0
insert-unicode|bru|0.14.0

</details>

**Comment by daiyam** [comment]
@brunnerh The `.vsix` of your extension doesn't include the `node_modules` folder on OpenVSX while it does on the VSCode Marketplace...

**Comment by brunnerh** [comment]
Wow, I just falsely assumed that dependencies would be installed with the extension...
