### ISSUE TITLE
VSCodium uses lower version of python than Code OSS.

### ISSUE THREAD

**Issue by Giger22** [VSCodium/vscodium#1423]
**Describe the bug**
VSCodium uses lower version of python than Code OSS.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Select default interpreter or enter interpreter path. I have the same path for Code OSS and VSCodium. In OSS I have python 3.10.9 (same as installed) and in VSCodium I have 3.10.6.

**Expected behavior**
VScodium should use the same version as VS Code/Code OSS. Note: I have this problem only on Linux not on Windows.

**Desktop (please complete the following information):**
 - OS_: Artix Linux 6.1.12
 - x86_64
 - 1.75.1.23040
 - n/a
 - Flatpak

**Comment by noonsleeper** [comment]
Please open this on https://github.com/flathub/com.vscodium.codium/issues

**Comment by Giger22** [comment]
Ok.
