### ISSUE TITLE
How to change the logo?

### ISSUE THREAD

**Issue by Hate9** [VSCodium/vscodium#1428]
Look, ok, I've looked through the issues, and I get that there's been some controversy over whether or not to use the (objectively hideous) coral logo or the (actually really good) green logo, and I understand that it's not being changed again for the time-being.

That said, I was literally considering switching back to Atom (literally abandoned at this point) just to stop having to look at the coral icon, so in the mean-time, is there anything I can just drop-in to replace the coral icon with the green icon again on my end? Ideally without recompiling from scratch.

I'm on linux, for the record, in case anyone shares file paths or something.

**Comment by TheMemeSniper** [comment]
i'm not sure what DE you're using, but on KDE Plasma this is possible:

right-click VSCodium and click "Edit Application"
![image](https://user-images.githubusercontent.com/67394719/221943524-236d2626-414e-4200-b135-285e78eeae7f.png)

click the icon to open the icon selector
![image](https://user-images.githubusercontent.com/67394719/221943902-7220f4c3-6b0f-4422-9075-2a8f8134e804.png)

choose a replacement icon
![image](https://user-images.githubusercontent.com/67394719/221944018-a56b2f59-e552-4063-8bdd-216b1340a189.png)

**Comment by Hate9** [comment]
I can definitely do that, but it won't change any of the branding *in* the application.

**Comment by Hate9** [comment]
@xfarrow oh, to be clear, I do *not* mean the VSCode logo. I do not like that logo. I mean the green logo that this app apparently briefly had before *some people* complained, and it changed back to the hideous one we currently have.

**Comment by daiyam** [comment]
- https://github.com/VSCodium/vscodium/discussions/1429
- https://github.com/VSCodium/vscodium/discussions/1430

**Comment by GitMensch** [comment]
Maybe you want to use a "fork" of VSCodium for the sake of its icon, like https://github.com/zokugun/MrCode ?

**Comment by Alex313031** [comment]
@Hate9 Just interjecting because I use atom and vscodium and geany. I maintain forks of all three, though my geany and vscodium forks are nothing special. HOWEVER, my atom-ng fork it actually a continuation of atom, and I have updated quite a few things including the packages and node modules and electron version.

Site is here > https://thorium.rocks/atom-ng/ and repo (with releases for linux and windows) is here > https://github.com/Alex313031/atom-ng in case you wanted to try it.

**Comment by Hate9** [comment]
@Alex313031 oooh, I'll have to check that out

**Comment by Alex313031** [comment]
@Hate9 Also, see my vscodium fork that has the name changed to codium, and the logo changed to the vscode-oss logo > https://github.com/Alex313031/codium

**Comment by blizzardengle** [comment]
I would like the green logo back as well. I followed the logic in [this repo](https://github.com/chadlavi/vscodium-icon) but with the green logo/icons and it did not work on Windows. I even followed the comments from [this issue](https://github.com/VSCodium/vscodium/issues/472) and manually replaced all the files and still no luck. I made sure to clear the Windows icon cache as well.

**Does anyone know how to get this working?** Preferably on all operating systems, but in my case Windows 11. This [zip folder](https://github.com/VSCodium/vscodium/files/11183546/resources.zip) all the icon changes that are needed, you should be able to extract this right into your local installation of VSCodium.

For reference I am using Windows 11 and installed VSCodium with `winget` which places the installation in `AppData\Local\Programs` not the traditional `Programs` directory.

This is the logo I am referring to if your new to the logo issue:

![code_70x70](https://user-images.githubusercontent.com/11205240/230728717-1ad784ab-9d22-4fca-966d-d490167b5766.png)

And this is what it would look like when you open VSCodium. This icon would also be used everywhere else the icon currently shows (title bar, icon tray, etc.):

![vscodium-alt-logo](https://user-images.githubusercontent.com/11205240/230728996-9c02864b-7713-44e5-afaa-c117a3724993.png)

**Comment by itkfm** [comment]
back in black now?
![image](https://user-images.githubusercontent.com/53079668/231513089-8c8131bb-03be-4500-830c-1765ba34ce0e.png)

**Comment by BxDev** [comment]
Current logo and icon is scary me.

**Comment by danielbayley** [comment]
@Hate9 Check out https://marketplace.visualstudio.com/items?itemName=danielbayley.custom-app-icons

> I'm on linux

Oh, although it currently doesn’t support Linux… Maybe you could open an issue/PR with details of file paths/how to change on that platform…

**Comment by Hate9** [comment]
That's alright, I like the new-new one fine.

**Comment by GitMensch** [comment]
> Maybe you could open an issue/PR with details of file paths/how to change on that platform…

Not 100% sure but I _guess_ that's mostly (?) the PNG. Also have a look at one of the icon commits in related repos like https://github.com/zokugun/MrCode/commit/75591d69eed78175906a8147e811e9efd66b7ad5#diff-26818155e5ac01f0f6ec812647db3c1a7036b78e60e5d1f70da8ecc3eee4e363

**Comment by Vortigern-The-Grey** [comment]
Also interested in changing the icon. I'm using the .deb stable repo and I want to change to the no background icon. Do I just replace the .png in /usr/share/codium or do I need to do more?

**Comment by Vortigern-The-Grey** [comment]
> Also interested in changing the icon. I'm using the .deb stable repo and I want to change to the no background icon. Do I just replace the .png in /usr/share/codium or do I need to do more?

nvm, replaced the .png and it all worked.
