### ISSUE TITLE
Add Appimage to release assets

### ISSUE THREAD

**Issue by mundusnine** [VSCodium/vscodium#143]
It seems that AppImage support was recently added; Will there be a Asset added to the releases page of Vscodium that replaces .deb( I imagine so I just want to make sure and I realise that the last release is older than the addition of AppImage support). 

I ask because I want to add vscodium to the app/cli installer that I am making( which scrubs the appimage.github.io/feed.json for app images)

**Comment by stripedpajamas** [comment]
There will be an an AppImage asset to the releases page on the next release 👍
