### ISSUE TITLE
VSCodium tries to resolve Google's DNS domain

### ISSUE THREAD

**Issue by xfarrow** [VSCodium/vscodium#1431]
**VSCodium tries to resolve Google's DNS domain**
I am using VSCodium 1.75.0. It tries to resolve 8.8.8.8 and 8.8.4.4 which are Google's proprietary DNS servers. Being a privacy-focused code editor, I'd suggest to implement settings which allow end users to override the system's DNS only if needed (I am currently on a privacy-centric DNS server on my computer). Thank you.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
This is not a bug, but rather a Microsoft's choice that likely will not be changed anytime soon.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open VSCodium
2. Open Wireshark or equivalent software

**Expected behavior**
VSCodium not overriding the system's default DNS

**Desktop (please complete the following information):**
 - OS: Linux
 - Architecture x64
 - Version 1.75.0
 - App Manager [e.g. Winget, Homebrew, Snap, AUR, RPM, Nix, ...]
 - Sandboxed Flatpak

**Comment by daiyam** [comment]
I don't think that the issue is due to VSCodium or VSCode.

It can come from:
- an extension
- flatpak
- ...
