### ISSUE TITLE
fatal: Authentication failed for 'https://github.com/user/repo'

### ISSUE THREAD

**Issue by mannyoii** [VSCodium/vscodium#1441]
I had logged in to GitHub using Personal Access token but it has since expired so i made a new token but i'm not sure where to put it in VSCodium so i can to push to my projects again. Please help me

`remote: Invalid username or password.`
`fatal: Authentication failed for ['https://github.com/user/repo](fatal: Authentication failed for 'https://github.com/mannyoii/css-exercises.git/')`

**Comment by QuickMythril** [comment]
this is the first result when i search this issue, but no answer.  what is the solution?  seems like it should be a simple thing to add your token into codium...  it was no problem to create the token to begin with, and i picked 7 days cause i was not sure i would keep using this.  now i regenerated the token, but it doesn't work?  i need to reapply it somewhere or what??
