### ISSUE TITLE
Doesn't load extensions and crashes with code 502

### ISSUE THREAD

**Issue by neulad** [VSCodium/vscodium#1443]
**Describe the bug**
When I'm trying to find extensions through the extensions tab it's loading for few seconds and then crashes with 

**Please confirm that this problem is VSCodium-specific**
- [ x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to 'Extensions'
2. Click on 'Search tab'
3. See error

**Screenshots**
![Screenshot from 2023-03-14 22-45-57](https://user-images.githubusercontent.com/116178300/225147964-f42f0790-9ebe-4cba-8c56-a0cfeb120617.png)

**Desktop**
 - OS: Manjaro
 - Architecture  x64
 - Version 1.76.1
 - App Manager:  AUR

**Additional context**
Firewall is disabled

**Comment by invpt** [comment]
Same problem here.
- OS: Fedora
- Architecture: x64
- Version: 1.75.1 (c6a9727b801542499d2b59cb7db4224e060fc578)
- App Manager: dnf with paulcarroty repo

**Comment by daiyam** [comment]
502 error on https://open-vsx.org/

**Comment by pluralmonad** [comment]
Same issue but getting 503...

![image](https://user-images.githubusercontent.com/22383011/225184350-6b46847b-b067-41b8-9336-acd74289f136.png)

- OS: Pop!_OS 22.04
- Arch: x64
- Version: 1.76.1

**Comment by ThornedRose** [comment]
Can also confirm, getting the same error as pluralmonad above: "Error while fetching extensions. Server returned 503".

OS: Arch Linux x86_64 
Kernel: 6.2.6-arch1-1 
DE: KDE Plasma 5.27.3
Package: vscodium-bin 1.76.1.23069-2

**Comment by bradleypregon** [comment]
I'm getting the same as above, a 503. My network is nothing overly egregious - no IP proxies, no VPNs, firewall, etc. I've attempted to access Extensions occasionally over the course of ~6 hours with the same result each time.

MacOS Ventura
ARM64
I installed the .dmg first, VSCodium.arm64.1.76.1.23069.dmg, and then tried installing with Brew with no luck.

**Comment by sudadi** [comment]
same issue getting 503
![image](https://user-images.githubusercontent.com/28077788/225245445-d6d05aa2-1a08-4822-8736-8d7526836bf0.png)
- Version: 1.76.1
- Release: 23069
- Electron: 19.1.9
- Chromium: 102.0.5005.167
- Node.js: 16.14.2
- V8: 10.2.154.15-electron.0
- OS: OS : Ubuntu 22.04.2 LTS x64 5.19.0-35-generic

**Comment by mactronmedia** [comment]
Same issue...

https://i.imgur.com/bDjcZh2.png

**Comment by f-x1-1** [comment]
I'm getting both errors, 502 and 503.

**Comment by KastenKlicker** [comment]
I get the same 502 error.

OS: Kubuntu 22.10 x86_64
Kernel: 5.19.0-35-generic
DE: KDE Plasma 5.25.5
Version: 1.76.1.23069, installed via flatpak

**Comment by sudadi** [comment]
> same issue getting 503 ![image](https://user-images.githubusercontent.com/28077788/225245445-d6d05aa2-1a08-4822-8736-8d7526836bf0.png)
> 
>     * Version: 1.76.1
> 
>     * Release: 23069
> 
>     * Electron: 19.1.9
> 
>     * Chromium: 102.0.5005.167
> 
>     * Node.js: 16.14.2
> 
>     * V8: 10.2.154.15-electron.0
> 
>     * OS: Ubuntu 22.04.2 LTS x64 5.19.0-35-generic

error has disappeared

**Comment by levortian** [comment]
Same error. It's like they were forcing us to use VSCode, there is working properly all extensions.

**Comment by neulad** [comment]
The issue resolved itself when the [Open VSX](https://open-vsx.org/) became available.

**Comment by imzoc** [comment]
<img width="243" alt="Screenshot 2023-04-06 at 4 17 17 PM" src="https://user-images.githubusercontent.com/56801478/230510636-2f132d83-5f92-4653-b2ed-d6cd29e3f1b2.png">
`Version: 1.77.1
Release: 23095
Commit: 8311b9c0ddd6ed7738146332e5a0629c76f17be3
Date: 2023-04-05T18:44:04.874Z (1 day ago)
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.4.0
Sandboxed: No`
