### ISSUE TITLE
Update downloads .tar.gz rather than .deb

### ISSUE THREAD

**Issue by edent** [VSCodium/vscodium#1447]
**Describe the bug**

VSCodium Alerted me to an update. Clicking the update button downloaded the .tar.gz version of the latest release. It should have downloaded the .deb

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install an older version using the .deb installer
2. Click on Update
3. The .tar.gz is downloaded
4. User gets confused and is unable to apply the update

**Expected behavior**
If the app has been installed from a .deb, it should download an updated .deb. If the app was installed using an .rpm file, that filetype should be downloaded.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04,
 - Architecture: x64
 - Version: 1.75
 - App Manager: N/A
 - Sandboxed: N/A

**Comment by daiyam** [comment]
It will be fixed with #1449. But there is no way to know which package to download, so it's going to like VSCode, a redirect to the download page.
