### ISSUE TITLE
41661/tcp open  unknown  | Why codium opens an unknown port?

### ISSUE THREAD

**Issue by AnnaSenpaiUwU** [VSCodium/vscodium#1450]
**Describe the bug**
➜ AnnaSenpai@7UwU7  ~  sudo nmap -p- -sS --min-rate 5000 -Pn -n 127.0.0.1
[sudo] password for AnnaSenpai:
Starting Nmap 7.93 ( https://nmap.org ) at 2023-03-20 03:32 -04
Nmap scan report for 127.0.0.1
Host is up (0.0000020s latency).
Not shown: 65533 closed tcp ports (reset)
PORT      STATE SERVICE
1716/tcp  open  xmsg
41661/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.54 seconds
➜ AnnaSenpai@7UwU7  ~  sudo fuser -v 41661/tcp
                     USER        PID ACCESS COMMAND
41661/tcp:           AnnaSenpai  109786 F.... codium
➜ AnnaSenpai@7UwU7  ~  sudo fuser -v 1716/tcp 
                     USER        PID ACCESS COMMAND
1716/tcp:            AnnaSenpai    742 F.... kdeconnectd
➜ AnnaSenpai@7UwU7  ~  

**Please confirm that this problem is VSCodium-specific**

I'm an Arch Linux user, by the way, I installed Codium from Aur,but I don't know if it is specific to arch linux or is it some feature

![Screenshot_20230320_042525](https://user-images.githubusercontent.com/122777930/226285211-3d8a0160-8d40-4ec5-8933-ffc4651cd2ee.png)

**Comment by daiyam** [comment]
https://github.com/microsoft/vscode/issues/73719
