### ISSUE TITLE
Popup in background

### ISSUE THREAD

**Issue by dev-quentin** [VSCodium/vscodium#1451]
Type: <b>Bug</b>

Popup `Open Folder`, `Open File` and `Open Workspace`... alwayse in background
VSCoduim remains in the forefront

VSCodium version: VSCodium 1.76.2 (22a808587994126e19125c6a1a03c00b990223f4, 2023-03-15T18:20:11.806Z)
OS version: Linux x64 5.4.0-144-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2879)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.24GB (9.17GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.1
vscode-eclipse-keybindings|alp|0.16.1
composer-php-vscode|DEV|1.31.12740
phptools-vscode|DEV|1.30.12484
xml|Dot|2.5.1
atom-icons|emr|1.2.0
auto-rename-tag|for|0.1.10
vscode-graphql|Gra|0.3.53
composer|ika|0.8.0
php-cs-fixer|jun|0.3.9
volar|luk|1.0.9
php-namespace-resolver|Meh|1.1.9
vscode-language-pack-fr|MS-|1.76.0
php-docblocker|nei|2.7.0
php-support-utils|ope|1.1.3
material-product-icons|PKi|1.5.0
sonarlint-vscode|Son|3.15.1
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.32.0
php-intellisense|zob|1.1.2

(1 theme extensions excluded)

</details>

**Comment by daiyam** [comment]
duplicate https://github.com/VSCodium/vscodium/issues/1120
