### ISSUE TITLE
`product.json` not read if outside of `~/.config/VSCodium

### ISSUE THREAD

**Issue by damko** [VSCodium/vscodium#1454]
**Describe the bug**
I'm not sure this is a bug. It could be due to my own environment, my codium setup or something I did not understand. 

**Bug:**

I'm trying to use different codium profiles and for some of them I'd like to enable MS marketplace as described [here](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#how-to-use-the-vs-code-marketplace) **but** `product.json` is not read if it's in `--user-data-dir` different than `~/.config/VSCodium`. It seems like `~/.config/VSCodium` is hard-coded somewhere. Maybe?

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

I did not test this as I don't run VSCode

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

I didn't find anything among the issues either.

**To Reproduce**

If I create `product.json` (as described in the doc) inside `~/codium_profile1/settings/` OR `~/codium_profile1/settings/User/` and **then** I start codium this way:

	codium --extensions-dir ~/codium_profile1/extensions --user-data-dir ~/codium_profile1/settings

the file is not read. For example I can not find `joffreykern.markdown-toc` among the available extensions.

If I:

	mv ~/codium_profile1/settings ~/.config/VSCodium

and then I run:

	codium --extensions-dir ~/codium_profile1/extensions --user-data-dir ~/.config/VSCodium

or simply:

	codium --extensions-dir ~/codium_profile1/extensions

`product.json` is read correctly and I can find `joffreykern.markdown-toc`

**Desktop (please complete the following information):**
 - OS: Debian testing
 - Architecture x64
 - Version 1.76.2.23074 (upgraded with DEB downloaded from releases)
 - App Manager DEB
 - Sandboxed no

**Additional context**
I attach the log of:
[debug.txt](https://github.com/VSCodium/vscodium/files/11080466/debug.txt)

	codium --verbose --log debug --extensions-dir ~/codium_profile1/extensions --user-data-dir ~/codium_profile1/settings ~/codium_profile1/content

Note: `~/codium_profile1/extensions` and `~/codium_profile1/settings` were created by codium, I only added `~/codium_profile1/settings/product.json` and created manually `~/codium_profile1/content`

**Comment by daiyam** [comment]
Here the relevant patch: https://github.com/VSCodium/vscodium/blob/master/patches/custom-gallery.patch
https://github.com/VSCodium/vscodium/blob/cd3b6e425a9863d3f99b5e5e8f71823569258b45/patches/custom-gallery.patch#L46-L47
The path isn't hard coded but resolved by the function `getUserDataPath`.

Have you tried you with the environment variables? 

https://github.com/VSCodium/vscodium/blob/cd3b6e425a9863d3f99b5e5e8f71823569258b45/patches/custom-gallery.patch#L20-L27

The 3rd option is the extension of my own: https://open-vsx.org/extension/zokugun/vsix-manager

**Comment by damko** [comment]
> Have you tried you with the environment variables?

no, but I thought of that. It's just that I'm teaching codium (for free) to some students and using ENV variables at this point of the course would be overkilling.
