### ISSUE TITLE
After vscodium was updated to 1.77, the "Select Kernel" function of the Jupyter plugin became invalid

### ISSUE THREAD

**Issue by Mr-Spade** [VSCodium/vscodium#1460]
**Describe the bug**
After vscodium was updated to 1.77, the "Select Kernel" function of the Jupyter plugin became invalid. After clicking "Select Kernel", it has been loading and cannot jump out of several candidate kernel lists.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install 'Jupyter' extension
2. Create a .ipynb file
3. Click on 'Select Kernel'
4. No response

**Expected behavior**
In vscode or earlier versions of vscodium, several candidate kernels should pop up afterwards.

**Screenshots**
![图片](https://user-images.githubusercontent.com/84010735/229491276-1227c73f-9775-4765-9234-eb41f1665389.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture x64
 - Version 1.77.0
 - App Manager deb repo
 - Sandboxed no

**Additional context**
None

**Comment by daviderigamonti** [comment]
Facing the same bug on Arch x86_64 running VSCodium Version 1.77.1

**Comment by waocats** [comment]
Same here. Pop_OS! 22.04 LTS, Codium version 1.77.1. I have a Julia kernel that shows up, but no candidate Python kernels.

**Comment by Mr-Spade** [comment]
Hey guys, I think I've found the source of this problem. After updating to version 1.77, vscode may have changed several APIs, resulting in the original jupyter extension not being able to be used on the new version. In the official marketplace of vscode, jupyter has been updated to adapt to the new version, but this update has not was published to the open-vsx repository, which caused the problem.

So a temporary solution is:

1. Go to the official marketplace of vscode and download the vsix file of the extended version 2023.3.1000892223 of Jupyter
2. Manually install this vsix file in vscodium

**Comment by astrojuanlu** [comment]
Could this issue be kept open? I know there's a workaround, but the default experience is still bad. Or maybe even if it's closed, pin it for visibility.

**Comment by astrojuanlu** [comment]
Also, `2023.3.1000892223` is not shown anymore in https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter, one has to craft the URL manually:

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2023.3.1000892223/vspackage

Otherwise, the latest version at the time of writing fails to install with a message "Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.77.3'.".

**Comment by chicolucio** [comment]
I think this should be kept open too. I have this issue too and, although there is a workaround, it is not intuitive and took some time to find the solution.

**Comment by karbenatek** [comment]
Setting the Jupyter to Pre-Release version fixed the problem in my case.
