### ISSUE TITLE
Unwanted connections

### ISSUE THREAD

**Issue by Flashwalker** [VSCodium/vscodium#1461]
**Describe the bug**
Codium trying to connect `raw.githubusercontent.com` and `openvsxorg.blob.core.windows.net`

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. install codium
2. run it

**Expected behavior**
Option to disable connections to `raw.githubusercontent.com` and `openvsxorg.blob.core.windows.net`

**Screenshots**
![image](https://user-images.githubusercontent.com/2188215/229511333-bf0e23fc-51fe-4e55-ba6c-08c9b549965f.png)
![image](https://user-images.githubusercontent.com/2188215/229511502-6d13c760-387a-428a-90b6-199d957c61ae.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture x64
 - Version 1.77.0.23093
 - App Manager apt
 - Sandboxed no

**Additional context**
Please make options to disable unwanted connections

**Comment by paulcarroty** [comment]
`openvsxorg` is probably the extensions update. `raw.githubusercontent.com` is where VSCodium grabs the [announcements](https://github.com/VSCodium/vscodium/raw/master/announcements-extra.json). You can disable both tho.

**Comment by Flashwalker** [comment]
ok
