### ISSUE TITLE
My imported profile won't load by default

### ISSUE THREAD

**Issue by jrc03c** [VSCodium/vscodium#1462]
**Describe the bug**

Every time I open VSCodium, I have to manually switch to my preferred profile, which I imported from a `*.code-profile` file. This is different than VSCode's behavior, which is always to load an imported profile until I manually switch to a different profile. There doesn't seem to be a way in VSCodium to force my imported profile to be loaded at launch and/or to delete the preexisting default profile.

**Please confirm that this problem is VSCodium-specific**

- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**

- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**

1. Install the VSCodium flatpak from [flathub](https://flathub.org/apps/details/com.vscodium.codium).
2. Launch VSCodium from any folder.
3. Import a profile that was previously exported from VSCode. Confirm that the profile loads correctly.
4. Close VSCodium.
5. Navigate to a different folder and re-launch VSCodium.
6. Notice that the newly-imported profile isn't used, though it is still available as a profile that can be selected.

> Note that launching VSCodium from a folder in which it was previously launched _does_ cause it to load the imported profile automatically, which leads me to believe that it's remembering profiles on a per-folder basis, or something like that.

**Expected behavior**

As in VSCode, I expected my newly-imported profile to be applied at all times, at every launch, until I manually switch to another profile.

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.1 Cinnamon
 - Architecture: x64
 - Version: VSCodium 1.77.0
 - App Manager: Flatpak
 - Sandboxed: Flatpak

**Comment by ololiuhqui** [comment]
The flatpak version kind of suck, i had many issue with it too, install from the official vscodium website following their instructions, everything works fine
