### ISSUE TITLE
VSCodium - 1.77.0.23093 Upgrade issue

### ISSUE THREAD

**Issue by metaad** [VSCodium/vscodium#1464]
Hello team,

While testing **VSCodium-x64-1.77.0.23093.msi** it was found that this release does not upgrade **VSCodium -1.77.0.23090**. They both co-exist. Screenshot of ARP is attached.

![image](https://user-images.githubusercontent.com/106653425/230048080-e2bbecd6-3697-440a-b80f-07e66558b8c7.png)

Can you please confirm if this is intended behaviour? OR there will be fix to upgrade earlier version.

Thanks in advance.

**Comment by Aniruddha120** [comment]
I would also add something to it- after getting this update, each time I open the vscodium the update automatically starts again and asks me to restart the app. I have found the same issue in the vs code GitHub repository where one of the developers recommended reinstalling it. but I have faced this issue 2 times in two different versions.
