### ISSUE TITLE
Feature request: JSON/YAML copy to clipboard the path of selected element

### ISSUE THREAD

**Issue by Trikenstein** [VSCodium/vscodium#1465]
**Describe the bug**

**To Reproduce**
1. Open a JSON or YAML file
2. Navigate to any element
3. Right-click on the element either in the breadcrumbs bar or in the pull down list showing the hierarchy of the nodes.
4. There is no possible action

**Expected behavior**
Would be nice if there is a right-click action which allow to copy the path of the selected element 
Such as `[0].networkProfile.networkInterfaces[0].resourceGroup` for the element shown in the screenshot.

**Screenshots**

![VSCodium_JSON_copy_element_path](https://user-images.githubusercontent.com/72353094/230660345-4ce4dfff-b0c3-4c27-90a4-0148d401ed73.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2
 - Architecture: x64
 - App Manager: installed from `*.deb`

**Other Info**

With IntelliJ IDEA Community Edition (regardless of the version), it is possible to copy the path of the selected element on the breadcrumbs bar. See screenshot below.

![IntelliJ_JSON_copy_element_path](https://user-images.githubusercontent.com/72353094/230660140-b9e6a323-6e28-4294-ad7f-0e1aafc2bb0d.png)

**Comment by daiyam** [comment]
@Trikenstein It's a missing feature from VSCode. It isn't related directly to VSCodium. You should open the issue there. Thx

**Comment by Trikenstein** [comment]
Oups, done: https://github.com/microsoft/vscode/issues/179531
