### ISSUE TITLE
No kernels to select in Jupyter Notebooks. VSCode doesn't have that issue.

### ISSUE THREAD

**Issue by andrei-akopian** [VSCodium/vscodium#1466]
**Describe the bug**
VSCodium doesn't see any kernels, I have Python, Kotlin, and Sage (jupyter) kernels installed and all are visible and useable in both VSCode and jupyter-notebook.

(I am a silly teenager, so please take it into consideration)

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
I don't know how to reproduce this. From my perspective it is just: create a .ipynb (Notebook) and try to select a kernel, no options will show up.

**Expected behavior**
When I try to select kernels, I should have options such as selecting python environments or Jupyter kernels like in VSCode.

**Screenshots**
VS Codium
<img width="1440" alt="Screenshot 2023-04-08 at 14 49 05" src="https://user-images.githubusercontent.com/86117540/230738423-2ab512c7-262d-4e28-a2b7-0d03d00436d9.png">
VS Code
<img width="1440" alt="Screenshot 2023-04-08 at 14 49 24" src="https://user-images.githubusercontent.com/86117540/230738428-16441379-d271-4a35-bf4d-b90e6eefe1c4.png">

**Desktop (please complete the following information):**
 - Mac OS
 - M1 (so Arm)
 - 1.77.1 (both vscodium and vscode)
 - I installed both from .dmg 

**Additional context**
Given I don't know what I am doing, the issue might be mixed into the various conda/homebrew/pip commands I spammed into the command line at some point in the past. But it works in VSCode, so it doesn't seem to be it.

**Comment by Ferrangelo** [comment]
For now you could use the [temporary solution](https://github.com/VSCodium/vscodium/issues/1460#issuecomment-1500906195) from issue #1460

**Comment by andrei-akopian** [comment]
Ok thanks, I guess I will use that for now.
