### ISSUE TITLE
Vscodium leaves processes after closing

### ISSUE THREAD

**Issue by lua-rocks** [VSCodium/vscodium#1476]
I use ZSH as default shell (`"terminal.integrated.defaultProfile.linux": "zsh"`). When I open integrated terminal, it spawns 4 `zsh` processes and one `gitstatusd`. After closing VSCodium, they remain. Each time when I reopen it, I get +5 hanging processes: 5, 10, 15, 20, and so on.

![screenshot](https://user-images.githubusercontent.com/82697845/231569296-cd4e9e7d-5f7d-4a00-9a2a-d711faeb1fbe.png)

**I have never used Microsoft's Visual Studio Code in my life**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Architecture x64
 - Version 1.77.2
 - App Manager AUR

**Additional context**
I've tried temporarily deleting all my settings and extensions, it doesn't make any difference.

**Comment by daiyam** [comment]
It's known upstream issue, please look at #1407 for more details.
