### ISSUE TITLE
Insiders Build?

### ISSUE THREAD

**Issue by Zate** [VSCodium/vscodium#148]
Any chance you'd be willing to do an insiders build also?  Be handy for checking out / using new things without having to wait for it to hit regular vscodium, or having to revert back to vscode insiders to use it.

**Comment by pavanagrawal123** [comment]
@stripedpajamas I think this is pretty reasonable to do, nightly builds could be adopted. Only issue is the release page getting cluttered with extra releases.

**Comment by stripedpajamas** [comment]
I was thinking of making a new repo `vscodium-insiders` with a build script that clones this repo but builds with an env var that drops us into insider conditionals. I think it's very reasonable and we can do it for sure.

**Comment by lsmoura** [comment]
@stripedpajamas Do you know where I can find these "insider conditionals"?

**Comment by stripedpajamas** [comment]
We haven't written the conditionals yet. I think we will need to wrap the current logic of checking out the latest tag.

**Comment by lsmoura** [comment]
@stripedpajamas Can we use the green icon [here](https://github.com/VSCodium/vscodium/issues/4#issuecomment-426642816) for the insiders version?

**Comment by stripedpajamas** [comment]
Sounds good to me @lsmoura

**Comment by DanyC97** [comment]
@stripedpajamas any progress with the insiders build ? asking because i'd love to give https://code.visualstudio.com/blogs/2019/05/02/remote-development a try and see if it improves my productivity

**Comment by pavanagrawal123** [comment]
@DanyC97 Even if insider builds were done, the licensing around all the new remote stuff is very closed off, and not going to be fun getting to work on oss builds.

**Comment by DanyC97** [comment]
oh i see @pavanagrawal123 , wasn't aware of that. Thx for taking the time to respond 👍

**Comment by stripedpajamas** [comment]
Am not sure which approach to take here:

1. configure .travis.yml in `vscodium-insiders` repo that clones `vscodium` and runs through build process with quality=insider set
    - setup build to run on schedule (nightly)
    - requires adding duplicating the env vars from VSCodium build (such as GITHUB_TOKEN) so that build can run through as normal
    - might also require setting up a separate Azure Pipeline config file as well (unclear)
2. add linux/mac/windows builds to the vscodium travis and azure build matrices with quality=insider
    - vscodium already builds daily (could set time to make sure it builds at around the same time MS builds)
    - no duplicating build config (env vars etc)
    - downside is that if insider build fails, the readme badge will show build: failing. perhaps a small price to pay, and should only show for a day.

I am leaning toward option 2.

common work (when quality=insider):
  - checkout master instead of latest tag
  - change destination for release upload to `vscodium-insiders` repo (so as not to muddle vscodium releases page)
  - construct version of binary using package.json instead of tag (since no tag will exist)
  - add insider support to `update-api` and the version json update logic in the build process
  - copy over insider resources before build (this would cover insider-only icon)

**Comment by stripedpajamas** [comment]
Additionally, it doesn't look like Travis's default deploy tool (which we are currently using) supports uploading releases to a different repo than then the one the build is running on. 

So either we do option 1 above or use a different deploy tool with option 2.

**Comment by shreyasminocha** [comment]
> it doesn't look like Travis's default deploy tool (which we are currently using) supports uploading releases to a different repo than then the one the build is running on.

I suppose GitHub Actions changes this.

**Comment by vraravam** [comment]
I would also very much to get such an `insiders` build - since I am on `vscode-insiders` - and the only reason I am unwilling to switch over to codium is the absence of the nightlies.

**Comment by Nezia1** [comment]
> 
> 
> I would also very much to get such an `insiders` build - since I am on `vscode-insiders` - and the only reason I am unwilling to switch over to codium is the absence of the nightlies.

I'm exactly the same. How hard would it be to have it working? I could probably look into it if it's only environment variables to switch.

**Comment by PF4Public** [comment]
They seem to be using a hidden [VSCODE_MIXIN_REPO](https://github.com/microsoft/vscode/search?q=VSCODE_MIXIN_REPO&unscoped_q=VSCODE_MIXIN_REPO) for insiders.

**Comment by officialpiyush** [comment]
Any updates on Vscodium Insider Edition? 👀

**Comment by GitMensch** [comment]
Finally implemented with #1217 - binaries available with https://github.com/VSCodium/vscodium-insiders/releases; the build scripts (and workflows) are directly used from this repo (in case someone wants to use it to build an own insider version from "vscode" sources).

Congrats and thanks go to @daiyam!

**Comment by daiyam** [comment]
> (in case someone wants to use it to build an own insider version from "vscode" sources).

[The section `Insider`](https://github.com/VSCodium/vscodium/blob/master/docs/build.md#insider) will explain you how to do it.

**Comment by GitMensch** [comment]
@paulcarroty Using `apt` with the registered repositories does not bring up any insider version - could you add that, please?

**Comment by paulcarroty** [comment]
Done.

**Comment by GitMensch** [comment]
Thanks for `codium-insiders`!

**Comment by jcasale** [comment]
The insider releases seem to lag behind vscode, yet the workflows appear to run (they just don't find changes).

Are there still issues to work out or is something temporarily awry?

**Comment by daiyam** [comment]
No, it's failing due to the need of updated patch:
https://github.com/VSCodium/vscodium/actions/runs/3417106561/jobs/5687898282
