### ISSUE TITLE
Context menu entries missing when installing it via winget

### ISSUE THREAD

**Issue by imgios** [VSCodium/vscodium#1480]
> DISCLAIMER: I'm not sure if it's a bug, I tried to search also in the issue list but I didn't find anything regarding. I'm sorry in case I'm wrong 😄 

**Describe the bug**
Entries missing in the context menu ("Open with VSCodium") when installing it via `winget`.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Simply install it via `winget` (`winget install vscodium`) and then right click on a folder.

**Expected behavior**
When right-clicking on a folder in the file manager we should see an entry "Open with VSCodium".

**Screenshots**
//

**Desktop (please complete the following information):**
 - OS: `Windows 10`
 - Architecture: `x64`
 - Version: `1.77.3`
 - App Manager: `winget`
 - Sandboxed: `no`

**Additional context**
//

**Comment by imgios** [comment]
Sorry, I thought I had VSCode installed via winget but I was wrong. Same behaviour, this issue can be closed 😄

**Comment by nuno-andre** [comment]
To install VSCodium via winget and setup the context menu you have to run the following command:

```powershell
winget install VSCodium.VSCodium --override '/SILENT /mergetasks="!runcode,addcontextmenufiles,addcontextmenufolders"'
```
