### ISSUE TITLE
Cannot Open Jupyter Notebook and Extension does not seem do be working

### ISSUE THREAD

**Issue by PhilippKorn** [VSCodium/vscodium#1481]
**Describe the bug**
As soon as I open up Vscodium:

```
Cannot open resource with notebook editor type 'jupyter-notebook', please check if you have the right extension installed and enabled
```

and 

```
Extension host terminated unexpectedly 3 times within the last 5 minutes.
```

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

I tried it with a fresh install of VSCode, its working there.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. updated to Vscodium Version: 1.77.3
2. Started the Application
3. opened an .ipynb file

**Expected behavior**
The Extension for viewing Notebooks should start

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Version 12.6
 - App Manager Homebrew

**Additional context**

**Comment by Romeo-CC** [comment]
I met the same problem in 1.78.1

**Comment by daiyam** [comment]
@Romeo-CC Open a new issue
