### ISSUE TITLE
Electron sandboxing prevents basic functionality.

### ISSUE THREAD

**Issue by benjaminrwilson** [VSCodium/vscodium#1482]
**Describe the bug**

Enabling Electron Sandboxing causes VSCodium to become unresponsive on reboot.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Enable `Window > Experimental > Use Sandbox`
2. Restart VSCodium

**Expected behavior**

Electron sandboxing should not affect basic application functionality (e.g., displaying text on the canvas).

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Architecture arm64
 - Version 1.77.3
 - App Manager Homebrew

**Comment by wc7086** [comment]
I noticed that the Electron versions of VSCodium and Visual Studio Code are inconsistent.
