### ISSUE TITLE
"Install Another Version" extension item is inactive for all extensions

### ISSUE THREAD

**Issue by dark-penguin** [VSCodium/vscodium#1483]
Steps to reproduce:
- Open "Extensions" menu
- Click the gear icon on any extension
- "Install Another Version" item is inactive

For some reason, it is not *always* inactive - I was able to use it once, but only once.

There was a similar issue in VS Code long ago: https://github.com/microsoft/vscode/issues/114341 , but apparently it was fixed, seeing that the bug report is closed. Or maybe it was simply closed via "works for me"...
But the problem is, I could not reproduce it on another machine. Both VS Code and Codium work fine on a fresh test system out of the box. However, on my machine, even after upgrading to the latest version, the issue persists. So I can't confirm whether it's a Codium-specific issue.

Still, extensions differ on VS Code and Codium, so it could be. Any idea what could I check about my system to locate the problem?

**Desktop:** Debian Bullseye amd64
**VSCodium:**
Version: 1.77.3
Release: 23102
Commit: 650fc437e02159df39d99355a91b2e3b1f1220c5
Date: 2023-04-12T18:19:15.613Z
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.2.9-4-liquorix-amd64
Sandboxed: No

![Screenshot](https://user-images.githubusercontent.com/16963337/232202817-1657fbbb-c682-4479-ac6e-7dd38f04b268.png)

**Comment by daiyam** [comment]
The `Install Another Version...` will stay disabled if the extension was installed with a `.vsix`.
With extensions for which you can see the links in the `Extension Resources` group (when clicking on them), the menu should be enabled.

**Comment by dark-penguin** [comment]
That would explain something, but for me, this item is disabled for all extensions - and only two of them were installed from a `.vsix`.

I just tried it again on a fresh test machine. No, even extensions installed from a `.vsix` have this option enabled, and it works.

I don't see an "Extension resources" group for any of my extensions. But I do see it on the test machine. Do I maybe need something enabled, like automatic updates? No, disabling automatic updates did not break the test machine, so it's something else...

**Comment by daiyam** [comment]
Weird!

If you have install an extension from a marketplace, you should be able to see the following when clicking on it:
![Screen Shot 2023-04-15 at 11 39 38 AM](https://user-images.githubusercontent.com/587742/232206141-2b7cfc4d-ae12-4b70-ae17-3a874635cecb.png)

Which marketplace are you using? OpenVSX or MS?

**Comment by dark-penguin** [comment]
I see this on a clean machine (even for locally-installed extensions), but not on mine (on any extensions).

I have not changed anything about the marketplace - I thought it's not possible to use the "normal" VS Code marketplace (MS?) in Codium, so there is another one, which does not have some things.

**Comment by dark-penguin** [comment]
I did not even have the time to notice the message and try a new version.

Nope, the issue is still there.
