### ISSUE TITLE
No settings sync option

### ISSUE THREAD

**Issue by ThinkSalat** [VSCodium/vscodium#1486]
**Describe the bug**
There's no settings sync option 
**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Install vs codium v1.77.3 from winget

**Expected behavior**
Show settings sync

**Screenshots**
![image](https://user-images.githubusercontent.com/31082405/232788037-fa33fe15-9d80-4aeb-9e4c-937b553d84ec.png)
**Desktop (please complete the following information):**
 - OS: Win 11 
 - Architecture x64
 - Version: 1.77.3
 - App Manager: Winget
 - Sandboxed: No

**Comment by kohnm** [comment]
Have a look at https://github.com/VSCodium/vscodium/issues/482
It is not available for the OSS build. But there are several extensions which provide this functionality.

**Comment by ZeddZoul** [comment]
It affects me

**Comment by JT-808** [comment]
i want to have it :)
