### ISSUE TITLE
yaourt arch linux checksum does not match

### ISSUE THREAD

**Issue by nalgritz** [VSCodium/vscodium#149]
Hello I am trying to install VSCodium using yaourt but failed.

Here's my command:
```
yaourt -S  vscodium-bin
```

```
==> Building and installing package
==> Making package: vscodium-bin 1.33.1-2 (Sun 05 May 2019 10:49:13 PM HKT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found vscodium-bin.desktop
  -> Found vscodium-bin-1.33.1-2.tar.gz
==> Validating source files with sha256sums...
    vscodium-bin.desktop ... Passed
    vscodium-bin-1.33.1-2.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!
==> ERROR: Makepkg was unable to build vscodium-bin.
```

**Desktop:**
- Arch Linux with deepin desktop env.
- x64
- 1.33.1-2

i saw another thread having the same problem but in brew. guessing it's the same case?

Appreciate of the help!! keep up the great work!

**Comment by stripedpajamas** [comment]
It's the same case, the checksum needs to be updated in AUR. VSCodium doesn't maintain the Arch Linux version so your best bet is to comment on that package so the maintainer can do what needs to be done.

**Comment by nalgritz** [comment]
got it. thanks a lot!
