### ISSUE TITLE
the terminal is not remembering command history

### ISSUE THREAD

**Issue by RabbitRun47** [VSCodium/vscodium#1490]
Type: <b>Bug</b>

simply open the terminal in application, type in a command, restart application and it wont remember any of the previous commands

VSCodium version: VSCodium 1.77.3 (650fc437e02159df39d99355a91b2e3b1f1220c5, 2023-04-12T18:12:53.725Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.0
gitlens|eam|13.5.0
prettier-vscode|esb|9.10.4
svg|joc|1.5.2
color-highlight|nau|2.6.0

</details>

**Comment by anantakrishna** [comment]
> [microsoft/vscode#180474](https://github.com/microsoft/vscode/issues/180474)

It is marked as duplicate of https://github.com/microsoft/vscode/issues/181508, which is resolved in https://github.com/microsoft/vscode/pull/182904. Though in VSCodium v1.79.2, issue is still there.

```
Version: 1.79.2 (user setup)
Release: 23166
Commit: 19c0f5cefaeb2637b45a9c7a356151fcfdcda1e9
Date: 2023-06-15T18:34:39.248Z (2 days ago)
Electron: 22.3.10
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044
```
