### ISSUE TITLE
App & document icons proposal

### ISSUE THREAD

**Issue by Zabriskije** [VSCodium/vscodium#1492]
Hey folks, I've noticed that the app icon has a white shadow instead of a black one (+ some artifacts/leftover pixels in all the [template corners](https://github.com/VSCodium/vscodium/blob/master/icons/template_macos.png)) and thought the logo/background ratio and colors could be enhanced, so I've made a new one (left to right: current one, my proposal for stable and insider):

<img width="128" src="https://user-images.githubusercontent.com/101254295/233840087-098df9cf-b97f-410c-84c1-1713005e9a1a.png"> <img width="128" src="https://user-images.githubusercontent.com/101254295/233840071-9cd3a182-7ab6-45da-806c-5016e0892216.png"> <img width="128" src="https://user-images.githubusercontent.com/101254295/233840082-b6df1062-6fc3-4e27-ac28-3757428ed116.png">

I've also noticed that the document icons are using the old icon format with a _pointy_ corner page bend (Apple is using [this instead](https://developer.apple.com/news/?id=5i6jlf4d) since Big Sur), there are some graphic imperfections here and there (for example, the low left corner of the "C" in the icon below is cut), and the small logo in the right corner is not used anymore. I made an icon pack ~1 year ago, already optimized to be the lightest possible without sacrificing quality (left current, right my proposal):

<img width="128" src="https://user-images.githubusercontent.com/101254295/233840948-64a0cd75-fd55-4ff8-adc5-4d063aa2db5b.png"> <img width="128" src="https://user-images.githubusercontent.com/101254295/233840962-bbf9eb9d-aa58-4173-a7d3-c96d32a1bb21.png">

You can find both app and document icons in [this ZIP file](https://github.com/VSCodium/vscodium/files/11303790/VSCodium-icons.zip).
If you need some other files, hit me up.

**Comment by daiyam** [comment]
About the app icon, the macos icon will stay with the white background. But the repository https://github.com/VSCodium/icons any PR to custom icons :wink:

About the document icons, they are generated by using the VSCode ones. I just applying our logo to them.
Do you have them for all the languages? Although, the logo will need to be on the icon, so that we are be able to differentiate which editor is associated with the file.

**Comment by Zabriskije** [comment]
> About the app icon, the macos icon will stay with the white background. But the repository https://github.com/VSCodium/icons any PR to custom icons 😉

Will do!

> About the document icons, they are generated by using the VSCode ones. I just applying our logo to them. Do you have them for all the languages? Although, the logo will need to be on the icon, so that we are be able to differentiate which editor is associated with the file.

Yup, they're all based on the VSCode ones, naming scheme included.

Isn't the new look enough to differentiate them? I know having a logo it's more effective, but I didn't see branding done like that in a long time, it's not used anymore (at least on macOS).
Can we try with a custom background instead?
