### ISSUE TITLE
Recent files/projects not showing on welcome page

### ISSUE THREAD

**Issue by jost-s** [VSCodium/vscodium#1494]
**Describe the bug**
When I open VSCodium, the welcome page shows but there's no "Recent" section below the "Start" section.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/28270981/234055108-09a0a4cc-5d29-4827-bbe2-845aeb784815.png">

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install VSCodium
2. Open VSCodium
3. Confirm there's no "Recent" section

**Expected behavior**
I always see the "Recent" section

**Screenshots**
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/28270981/234045055-27014854-88ae-4071-99f0-6a6ee4fd69f1.png">

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1
 - Architecture: arm64
 - Version: 1.77.3
 - App Manager: Nix
 - Sandboxed: no

**Comment by jost-s** [comment]
There's something up with the profile. I've backed up my existing profile and created an empty one and "Recent" is showing up as expected.

**Comment by paulcarroty** [comment]
Now it works, probably fixed long time ago.

**Comment by jost-s** [comment]
It started working again a couple of days ago.
