### ISSUE TITLE
Upgrade to 1.78 to keep pace with vscode

### ISSUE THREAD

**Issue by Romeo-CC** [VSCodium/vscodium#1499]

**Comment by youcefv** [comment]
Code-OSS

- v1.78.0 released May 3, 2023 23:03 GMT+1
- v1.78.1 released May 9, 2023, 18:56 GMT+1

**Comment by daiyam** [comment]
Help is always welcome :wink:

**Comment by septsea** [comment]
Hello. VSCodium v1.78 has been released.

**Comment by daiyam** [comment]
> Hello. VSCodium v1.78 has been released.

Still building... experiencing network errors...

**Comment by youcefv** [comment]
1.78.1 should follow shortly.

**Comment by daiyam** [comment]
`v1.78.1` was released
