### ISSUE TITLE
Sync Settings extension download error

### ISSUE THREAD

**Issue by robertopc** [VSCodium/vscodium#150]
When I download settings from sync settings extension.
I had a error in installation of them. Example:

"bin/code" --install-extension ms-vscode.atom-keybindings
Error: Command failed: "bin/code" --install-extension ms-vscode.atom-keybindings
/bin/sh: 1: bin/code: not found

How workaround for this error?

**Comment by stripedpajamas** [comment]
Can you see if the documented workaround for that extension works for you? Link here: https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace

**Comment by lsmoura** [comment]
No workaround needed for me.

It works out of the box on the latest release, and when building vscodium myself from vscode's master branch. (I'm on the latest MacOS)

**Comment by stripedpajamas** [comment]
The workaround is only needed on Linux I believe

**Comment by robertopc** [comment]
This workaround worked for me.
I use Linux.
Thanks
