### ISSUE TITLE
Missing Release notes on 1.78.1

### ISSUE THREAD

**Issue by netizen-ais** [VSCodium/vscodium#1502]
Trying to see the relase notes results in a blank editor tab.

**Comment by daiyam** [comment]
Got the error `Refused to execute inline script because it violates the following Content Security Policy directive:` in the Developer console.

Same error as #1503 and #1504.

**Comment by peter-fb** [comment]
I updated VSCodium to version [1.78.1.23131](https://github.com/VSCodium/vscodium/releases/tag/1.78.1.23131) but this doesn't seem to fix this issue.

This is the Console error message:

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'sha256-N4YFn5ze5crjPqMK/opogKs7bSGWtf3lmjV/3LfbSOs=' 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-gL9sMIYaOSpgU2r/kGAnB4ETLEykloodzKO0BgrHHPQ='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by netizen-ais** [comment]
Works for me:
![image](https://github.com/VSCodium/vscodium/assets/3426685/500dbe6c-6fe9-4a05-ab4d-e0e9f85fb16b)

**Comment by peter-fb** [comment]
I'm using Windows, maybe that's why it's not working:

Version: 1.78.1 (user setup)
Release: 23131
Commit: abdfa343d7fcd6ee2fd896e746a586e990db1e33
Date: 2023-05-11T15:09:14.581Z
Electron: 22.3.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

**Comment by daiyam** [comment]
Ya, still an issue on windows! :rage:

**Comment by daiyam** [comment]
Closing in favor of #1515. Please follow the updates there.
