### ISSUE TITLE
Cannot display image on 1.78.1

### ISSUE THREAD

**Issue by vuthanho** [VSCodium/vscodium#1504]
**Describe the bug**
Through the file explorer, double click to open a png file, a blank page is opened. In addition, I also have the same issue as https://github.com/VSCodium/vscodium/issues/1502 and https://github.com/VSCodium/vscodium/issues/1503.

Version: 1.78.1
Release: 23130
Commit: 748cf23d39091308b3b0d65ac43f0d784709fdcc
Date: 2023-05-10T01:49:13.634Z
Electron: 22.3.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.2.6-76060206-generic
Sandboxed: No

**Comment by daiyam** [comment]
It should be fixed in `1.78.1.23131`
