### ISSUE TITLE
Need help building or installing extension from source

### ISSUE THREAD

**Issue by jcalfee** [VSCodium/vscodium#1509]
**Describe the bug**

Need to build, debug, and fix various extension that don't fully work in VSCodium as documented.  I'm finding it difficult to find clues (docs, web) on how to do this in VSCodium though.  The cli Extensions Management installs from a VSIX, but has no option to install from a folder or build a VSIX.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
(any vscode extension example will do, this one looks very simple though)
1. Go to https://github.com/barklan/inline_sql_syntax
2. git clone
3. pnpm i

The package.json is all about code only and does nothing to really package the extension (vscode:prepublish for example updates the ./out folder).  Some time ago, they removed the VSIX file:
https://github.com/barklan/inline_sql_syntax/commit/1dd1e66aeb278555b65c9df74eece165e1479c1b

I assume it was bindery bulk stuff that did not belong in Git.  I'm guessing it is build here: 

https://github.com/barklan/inline_sql_syntax/blob/main/.tasks#L13

`command=vsce package`

**Expected behavior**
How can I install an extension from source? Or, how to build an extension installer?

**Desktop (please complete the following information):**
 - OS: [Pop-Os 20.04, etc]
 - Architecture [x64]

**Comment by jcalfee** [comment]
Maybe it is not the same.  I don't have a `code` executable, only `codium` and `codium` does not have the [--extensionDevelopmentPath](https://code.visualstudio.com/api/working-with-extensions/testing-extension#the-test-script) option.

**Comment by daiyam** [comment]
Here my debug task: https://github.com/zokugun/vscode-sync-settings/blob/master/.vscode/launch.json
