### ISSUE TITLE
stopped displaying

### ISSUE THREAD

**Issue by greghonox** [VSCodium/vscodium#1510]
Type: <b>Bug</b>

stopped displaying details in window.

VSCodium version: VSCodium 1.78.1 (748cf23d39091308b3b0d65ac43f0d784709fdcc, 2023-05-10T01:49:13.634Z)
OS version: Linux x64 6.2.6-76060206-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 3353)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|15.36GB (7.62GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.1
vscode-sqlite|ale|0.14.1
arepl|alm|2.0.5
vscode-django|bat|1.8.0
githistory|don|0.6.20
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
gitlens|eam|13.5.0
vscode-python-config|fra|1.17.0
vscode-pull-request-github|Git|0.64.0
test-adapter-converter|hbe|0.1.6
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.25.0
vsc-python-indent|Kev|1.18.0
jupyter|lum|2022.3.108
MagicPython|mag|1.1.1
rainbow-csv|mec|3.3.0
python-path|mge|0.0.14
git-graph|mhu|1.30.0
vscode-docker|ms-|1.25.0
vscode-language-pack-pt-BR|MS-|1.78.0
vscode-dotnet-runtime|ms-|1.6.0
python|ms-|2023.6.0
jupyter|ms-|2023.3.100
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
autodocstring|njp|0.6.1
oracledevtools|Ora|21.5.0
code-spell-checker|str|2.20.4
vscode-remotework-extension-pack|sug|1.1.4
python|tht|0.2.2
jinja|who|0.0.8
markdown-editor|zaa|0.1.9

(2 theme extensions excluded)

</details>

**Comment by greghonox** [comment]
Image
![image](https://github.com/VSCodium/vscodium/assets/35502196/a783221c-fe4d-4df0-ac88-5d78c958e6cc)

**Comment by tc2290** [comment]
@greghonox what type of file are you working with? 

I'm experiencing this with .ipynb files, but the issue seems like it may be related to the renderer because others are having issues with images displaying as well as markdown display.

**Comment by greghonox** [comment]
@tc2290 python jupyter is also not working anymore

**Comment by rwperrott** [comment]
Since v1.7.8.1, at least Markdown not displaying for *.md file and extensions!
On Linux Mint 21.1 MATE 64-bit
Unusable for what I need, so will be downgrading and try to block updates to this version.

**Comment by Moini** [comment]
Extension details tabs are also empty, looks like basically everything that displays a website is broken?

**Comment by greghonox** [comment]
yes @Moini . 
had to start using vs code

**Comment by andthum** [comment]
Probably related to #1502, #1503 and #1504.

Opening the Commit Graph with GitLens also does not work and just shows an empty window.

**Comment by Pecneb** [comment]
Same issue with me in Pop_OS!, stopped showing PDF and markdown files.

**Comment by Carbocode** [comment]
Same issue with the Thunderclient Tab

**Comment by greghonox** [comment]
hi, here is updated and now it works
