### ISSUE TITLE
bug(windows): broken webview in 1.81.1

### ISSUE THREAD

**Issue by daiyam** [VSCodium/vscodium#1515]
The bug is affecting Windows since `1.81.1.23130` and still present in `1.81.1.23131`.

I found out that the GH Action didn't used the latest commit (with the fix) of `master`. Maybe due to the ongoing issues of GitHub. (It had never happened before)
I will re-release a new `23132` after midnight GMT and will follow if it uses the correct commit.

For those who can't wait, there is a fix:
- edit the files `C:\Program Files\VSCodium\resources\app\out\vs\workbench\contrib\webview\browser\pre\index.html` and `C:\Program Files\VSCodium\resources\app\out\vs\workbench\contrib\webview\browser\pre\index-no-csp.html` (The location depends on how it was installed, they might be in the user's home)
- replace `VSCodium` with `VS Code`
- save
- restart VSCodium

#1508 #1503 #1502

**Comment by WMarks-Enertech** [comment]
Just a quick note, I had to edit `index.html` and not `index-no-csp.html`

**Comment by matthiasbock** [comment]
Here is the above fix for Linux users (vscodium installed from the Debian package):

* go to /usr/share/codium/resources/app/out/vs/workbench/contrib/webview/browser/pre
* replace "VSCodium" with "VS Code" in index.html and index-no-csp.html
* restart codium

The text replacement can also be accomplished with the following sed command:
~~~sh
$ sudo sed -e "s/VSCodium/VS Code/g" \
    -i /usr/share/codium/resources/app/out/vs/workbench/contrib/webview/browser/pre/index*.html
~~~

Confirmed working for:
Version: 1.78.1
Release: 23130
Commit: 748cf23d39091308b3b0d65ac43f0d784709fdcc
