### ISSUE TITLE
how do you add "code" command?

### ISSUE THREAD

**Issue by Pshemas** [VSCodium/vscodium#1517]
Is it possible to add code command?  If yes is it doable via powershell (as a system user)? I'd like to deploy it at local fablab and it would help greatly.

edit: I've tried command pallete and writing "shell..." as in docs but I get "no matching commands".

**Comment by charleech** [comment]
From my machine, after installing with `.msi`,  the `C:\path\to\codium\bin` has been added to the `%PATH%`.

Then in *Powershell* I'm able to executed the `codium .` to open the current directory with *VSCodium*, without any further configuration.

I'm not sure if adding the `path\to\codium\bin` to the `%PATH%` (Windiws) or `$PATH` (*nix) may help or not.

**Comment by daiyam** [comment]
VSCodium can provide only `codium` command.
