### ISSUE TITLE
MP4 support in VSCodium webview?

### ISSUE THREAD

**Issue by xpol** [VSCodium/vscodium#152]
Is it possible to configure VSCodium with full audio/video playback support in its webview?

I'm utilize VSCodium as a multimedia content authoring tool using markdown files.
As I know, The official vscode can't playback any video/audio in its webview.

I found VSCodium can playback my mp3 files.

But for the video, It can playback mp4 format.

Insert follow code into a markdown file. It the built-in markdown preview has a gray play button.
```markdown
<video controls>
  <source src="http://techslides.com/demos/sample-videos/small.mp4" type="video/mp4">
</video>
```

BTW: Atom can have fully audio/video playback support, is it use different version of ffmpeg?

**Comment by stripedpajamas** [comment]
> The official vscode can't playback any video/audio in its webview.

@xpol -- VSCodium is a build of `vscode`. As such, we do not implement any features or fix any bugs in `vscode` itself, we only run the already written build scripts. MS has [no plans to make this work](https://github.com/microsoft/vscode/issues/54097), but if they ever do, it will then work in VSCodium.

**Comment by xpol** [comment]
Thanks for replay.

In case anyone wants MP4 and other video audio support for VSCode/VScodium:

I have solved this by replace VSCode/VScodium packed libffmpeg with libffmpeg form https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases .

**Comment by stripedpajamas** [comment]
Awesome!! I would recommend you also put this workaround in the vscode issue to help out others! 🙏

**Comment by xpol** [comment]
Those vscode issues are closed can't add any comments.

**Comment by ejabu** [comment]
> Thanks for replay.
> 
> In case anyone wants MP4 and other video audio support for VSCode/VScodium:
> 
> I have solved this by replace VSCode/VScodium packed libffmpeg with libffmpeg form https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases .

Is there any step by step guides to use implement it ?
