### ISSUE TITLE
System error

### ISSUE THREAD

**Issue by vardidze-rostom** [VSCodium/vscodium#1520]
**Describe the bug**
Sometimes when I work in VSCodium my system freezed and logout. 

**Please confirm that this problem is VSCodium-specific**
- Now I don't use VSCode.

**Please confirm that the issue/resolution isn't already documented**
- [ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Only work on VSCodium

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 38 Gnome 44
 - Architecture  x64
 - Version 1.78.2
 - App Manager RPM
 

**Additional context**
Sometimes system doesn't logout and continue work after freeze

**Comment by GabsEdits** [comment]
+1, I also get system errors even when not using it.

![image](https://github.com/VSCodium/vscodium/assets/110247388/39f661f0-f7f5-4c49-960e-16a9a3623581)
