### ISSUE TITLE
File './vscodium-1.78.1.23130-x86_64.rpm' not found on medium 'https://download.vscodium.com/rpms/' Opensuse Tumbleweed

### ISSUE THREAD

**Issue by DrK01** [VSCodium/vscodium#1521]
Describe the bug
I can't update my Codium installation

Please confirm that this problem is VSCodium-specific
Yes, it is. Code updates work as expected

Please confirm that the issue/resolution isn't already documented
- [x] Yes, I checked all the issues & couldn't find something related

- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

To Reproduce
Run `sudo zypper up`

Expected behavior

Screenshots
![screenshot](https://github.com/VSCodium/vscodium/assets/45756472/385b31b7-36ba-4612-a976-bbbc6c34dbbd)

Desktop (please complete the following information):

OS: Opensuse Tumbleweed KDE
Architecture: x86_64
App Manager: Zypper

**Comment by paulcarroty** [comment]
1.78.2 is now available on https://download.vscodium.com.

**Comment by DrK01** [comment]
Thank you for letting me know there is a new version available for downloading but this does not solve the issue because when i try to install the rpm package from github repo (using Discover, KDE's Store) openSUSE says it can't be verified and omits it. It only installs when i do it using sudo in the terminal & later on a new update patch it suggest to downgrade (gives the same error as in the image)/remove it because the entire update patch won't be applied because openSUSE assumes it will break the system.

I think the problem might be in the rpm repos.

Thank you

**Comment by paulcarroty** [comment]
OK, let me check.

**Comment by paulcarroty** [comment]
Tested on Leap/Tumbleweed, all is fine. Did you accepted the GPG key?

Without the full debug zypper log it's hard to guess what happened.

**Comment by paulcarroty** [comment]
Tested for second time with success, closing for now.

**Comment by DrK01** [comment]
I apologize for being so late, i had to switch distro because of this & now i'm back at OpenSUSE & can confim that the issue has been solved. Thank you
