### ISSUE TITLE
No more x86 installer on Windows

### ISSUE THREAD

**Issue by Thilas** [VSCodium/vscodium#1523]
@daiyam, I just noticed you don't build x86 installers for Windows anymore (since #1500). Can you tell me why?

Right now, because of that, no more Chocolatey package are automatically published when a new version is released. I need to know if it's on purpose or not before adjusting my part (if needed).

**Comment by daiyam** [comment]
The 32bits builds are failing due to an error: https://github.com/VSCodium/vscodium/actions/runs/4931065606/jobs/8812711461

I haven't took the time to look into it.

**Comment by theofficialgman** [comment]
also missing 32bit arm <https://github.com/VSCodium/vscodium/pull/1500/commits/d99d1a5ff8d3c77229d429c6dffc3cd671e2a7f7>
