### ISSUE TITLE
Latest update broke nearly all syntax highlighting

### ISSUE THREAD

**Issue by zachHixson** [VSCodium/vscodium#1525]
**Describe the bug**
Everything is default grey, across all languages and projects. Only tokens that aren't grey are the curly braces and parenthasis

**Please confirm that this problem is VSCodium-specific**
- [X ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**

**Expected behavior**
Normal, functioning syntax highlighting like VSCodium always has

**Screenshots**
![image](https://github.com/VSCodium/vscodium/assets/30204733/fc4646c4-fa4b-4426-917b-2c403681f708)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Architecture x64
 - Version 1.78.2

**Comment by Ranguna** [comment]
Syntax highlight is working for me:

![image](https://github.com/VSCodium/vscodium/assets/5003755/34a4bf5b-7555-4b79-b654-27d13050ef95)

Version: 1.78.2
Release: 23132
Commit: e06ea6147733c975d26c3d3552462681e05cb147
Date: 2023-05-12T00:42:22.773Z
Electron: 22.3.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.3.4-arch1-1
Sandboxed: No
