### ISSUE TITLE
Large files can not be displayed (1.1M)

### ISSUE THREAD

**Issue by cws999** [VSCodium/vscodium#1529]
os:devuan 4
app:1.78.2.23132

I thought the program had been running for too long, but after restarting the program, it still couldn't display large files.
But scite, mousepad, they all work
[https://picdl.sunbangyan.cn/2023/05/24/ulj1gs.png](url)

**Comment by daiyam** [comment]
This is a VSCode issue and I don't think it will be ever be resolved since it's related about the used technologies (electron, html)
You should use another editor for big files.
