### ISSUE TITLE
No shortcuts reference

### ISSUE THREAD

**Issue by Scartiloffista** [VSCodium/vscodium#153]
**Describe the bug**
command 'workbench.action.keybindingsReference' not found - or, no keyboard shortcut pdf/documentation.

- [+] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

- [+] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to 'Help'
2. Click on Keyboard shortcut reference
3. VSCodium gives command 'workbench.action.keybindingsReference' not found

**Expected behavior**
A pdf with the shortcuts

**Desktop (please complete the following information):**
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-05-04T00:22:12.210Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-18-generic (Ubuntu 18.04)

**Comment by stripedpajamas** [comment]
Hi @Scartiloffista 👋 Good find!! 

Looks to me like we were missing some fields in the product.json that link to those keymaps. I've opened #155 to resolve this.

Thanks for helping us find stuff like this!
