### ISSUE TITLE
Settings file is not saved

### ISSUE THREAD

**Issue by andy9a9** [VSCodium/vscodium#1533]
**Describe the bug**
IDE could not change the `settings.json` file.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. VSCodium -> Settings -> Profiles -> Show Contents... 
2. Double click on `settings.json`
3. Modify content
4. Save file
5. Open terminal
6. cat ~/Library/Application\ Support/VSCodium/User/settings.json
7. Content without change...

**Expected behavior**
Even if the `777` mask has been used for `settings.json`, IDE is not applying any change. After IDE restart it used the previous content. If I change the file manually in console, the IDE use the actual content.

**Screenshots**
<img width="1030" alt="Screenshot 2023-05-29 at 13 08 32" src="https://github.com/VSCodium/vscodium/assets/20794139/63296578-aae0-4dfa-b934-b8a13d2d9f66">

**Desktop (please complete the following information):**
 - OS: `Mac OS`
 - Architecture: `arm64`
 - Version: `1.78.2.23132`
 - App Manager: `Homebrew`
 - Sandboxed: `no`

**Comment by snobb** [comment]
I have similar issue. When I try modifying the settings via UI - it shows the following popup:
![image](https://github.com/VSCodium/vscodium/assets/578528/ae86fca4-7404-494d-a304-ba96f5ee052d)

If however I edit the setting.json in the editor - then I can write it without any issues.

**Comment by snobb** [comment]
I noticed that the issue happens when the JSON is invalid (beyond comments that are allowed in VSCodium). Eg. missing comma or a comma after the last element of an object or an array. Fixing issues with the JSON in the settings.json normally solves it.
