### ISSUE TITLE
EL7 vscode-policy-watcher: Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found

### ISSUE THREAD

**Issue by cdorbell2** [VSCodium/vscodium#1537]
Hello

i try the version 1.78.2 on my centos 7.9 , but the codium crash with a problem a glibc .
it is normal ? the equivalent vscode 1.78.2 don't have the problem.

/usr/share/codium/resources/app/node_modules.asar.unpacked/@vscode/policy-watcher/build/Release/vscode-policy-watcher.node: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found 

/usr/share/codium/resources/app/node_modules.asar.unpacked/@vscode/policy-watcher/build/Release/vscode-policy-watcher.node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found

**Comment by paulcarroty** [comment]
#1262

**Comment by GitMensch** [comment]
duplicate

**Comment by GitMensch** [comment]
Actually - the original post in the referenced issue was wrong (that is about vscodium-reh, which works [tested 1.79.2; the issue here is about vscodium; which I have not tested yet but the issue opener has done this).

@cdorbell2: does the issue affect you with the current 1.79.2?
