### ISSUE TITLE
VSCodium stuck forever trying to update extension

### ISSUE THREAD

**Issue by huang-jy** [VSCodium/vscodium#1541]
**Describe the bug**
VSCodium continuously tries to update some extensions

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
(I cannot verify this, I do not use VS Code)

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Start VSCodium
2. Note extensions to update
3. Extensions will show "Installing" then "Reload Required"
4. Click to reload
5. Extensions will show "Installing" then "Reload Required"
6. Go to Step 4

**Expected behavior**
Successful Extensions Update

**Screenshots**

![Screenshot from 2023-06-10 08-07-03](https://github.com/VSCodium/vscodium/assets/2756283/4edab5fd-f330-478f-8412-db59540ec92e)

**Desktop (please complete the following information):**
 - OS: Manjaro (previously Fedora 36 -- see note below)
 - Architecture: x64
 - Version: As in AUR repo
 - App Manager: AUR (paulcarroty COPR under F36)
 - Sandboxed: No, AUR

**Additional context**
I previously had VSCodium running under Fedora 36. I copied my home directory to external USB then back over to Manjaro. This migrated the state and config of my applications, but VSCodium doesn't seem to like that somehow. Even though it's kept all my extensions, it doesn't seem to want to update them.

I did try removing `~/.config/VSCodium` and `~/.vscode` but neither helped

**Comment by daiyam** [comment]
Which AUR repository? The update should be deactivated since the app is manager by AUR.

**Comment by huang-jy** [comment]
Standard one. Installed using 

`yay -S vscodium-bin`

I also installed `vscodium-bin-marketplace` and `vscodium-bin-features`

**Comment by nopeless** [comment]
having same issue

**Comment by huang-jy** [comment]
I eventually totally reset the vscodium state by removing these folders (if they exist)

* `~/.config/Code`
* `~/.config/VSCodium`
* `~/.vscode`
* `~/.vscode-oss`
* `~/.vscode-R`

Then opening VSCodium and reinstalling all my extensions, or using the command line and doing 

```
codium --install-extension {{ extension }} --force
```

This may have messed up other settings, but so far so good.

**Comment by renestalder** [comment]
Issue also happening on macOS, installed via Homebrew.

**Comment by daiyam** [comment]
@renestalder are you using MS marketplace for the extensions?

**Comment by renestalder** [comment]
@daiyam Yes, that's right. And I just checked whether the changes in `product.json` are still there to make sure it doesn't try to update extensions from another marketplace where they might not exist. And so far, it seems correctly set up.
