### ISSUE TITLE
How to download "Workloads" (ex Desktop Development with C++) and "Individual Components" (ex. .NET 7.0) ?

### ISSUE THREAD

**Issue by Rexadev** [VSCodium/vscodium#1542]
**Describe the bug**

Tried the official Microsoft installed for  Microsoft C++ Build Tools but is installs Visual Studio

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Architecture x64
 - App Manager

**Comment by theol-git** [comment]
It doesn't actually install visual studio, launch the executable it will give you options on what to install.

**Comment by daiyam** [comment]
I just wonder why it's related to VSCodium?
