### ISSUE TITLE
Python/Jupyter extension keeps crashing after version 1.77

### ISSUE THREAD

**Issue by nrthIxne** [VSCodium/vscodium#1545]
**Describe the bug**
After upgrading from version 1.77.3 to 1.78 or 1.79 the Python (ms-python) and/or Jupyter (ms-toolsai) extensions keep crashing. Therefore, Jupyter Notebooks are unusable. VSCodium tries to connect to a selected kernel but keeps crashing, after 5 crashes is aborts the connection try. I am unable to execute any cells in my notebook. Going back to version 1.77 and downgrading the extensions fixes the issue.

**Please confirm that this problem is VSCodium-specific**
I downloaded the latest version of VSCode and didn't encounter these issues.

**Please confirm that the issue/resolution isn't already documented**
Similar issued have been reported, but they didn't fix my issue

**To Reproduce**
1. Open VSCodium
2. Open Jupyter Notebook
3. Try to connect to Kernel
4. Try executing a cell

**Expected behavior**
On start-up VSCodium should connect to kernel and let me execute cells in my Jupyter Notebook.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Architecture:  x64
 - App Manager: AUR
 
**Additional context**
What log files should I share for better insight.

**Comment by saeedark** [comment]
I have the same problem. Switching to a pre-release version of ms-toolsai.jupyter seems to solve this problem.

**Comment by jake-is-ESD-protected** [comment]
Same issue here. @saeedark 's solution does not work, at least for me. 

>Details:
VSCodium 1.79.2.23166 via snap
Zorin OS 16
