### ISSUE TITLE
Jupyter doesn't work after 1.77, causes extension host to crash

### ISSUE THREAD

**Issue by wjandrea** [VSCodium/vscodium#1549]
**Describe the bug**
When I try to start an [interactive window](https://code.visualstudio.com/docs/python/jupyter-support-py#_using-the-python-interactive-window) with [Jupyter](https://code.visualstudio.com/docs/datascience/jupyter-notebooks), it hangs and I see in the status bar it says "Extension host terminated unexpectedly. Restarting..." for a moment. Then nothing happens in the interactive window. Also, if I try it again and watch the processes, a new ipykernel gets started while the old one keeps running, which shouldn't happen.

I noticed the issue in version 1.78.2 but rolled back to 1.77.3 and it worked again. Issue is still present in 1.79.2.

Probably related to #1545

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
    - Tested using a Codespace, if that's relevant. I don't have VSCode installed.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.
    - Could [Proprietary Extensions](/VSCodium/vscodium/blob/master/DOCS.md#proprietary-extensions) be relevant?

**To Reproduce**
1. If needed, install the Jupyter extension and possibly the Python extension too. You may also need to perform the [setup](https://code.visualstudio.com/docs/datascience/jupyter-notebooks#_setting-up-your-environment).
1. Run **Jupyter: Create Interactive Window** (`jupyter.createnewinteractive`)
3. You may need to try running a line of Python code in the box at the bottom, for example, run `1+1` and you should get `2`.
4. Watch status bar for message
5. Interactive window hangs

**Expected behavior**
Interactive window shows the Python and IPython versions, indicating it's ready for input.

**Screenshots**
Hung:
![Screenshot showing "_Connecting to py3_10 (Python 3.10.11)..._" in the interactive window](https://github.com/VSCodium/vscodium/assets/22385371/4644e201-7de5-4d89-b60e-36bbceeab722)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Architecture: x64
 - Version: 1.79.2
 - App Manager: APT
 - Sandboxed: no

**Additional context**
\-

**Comment by DaiDuncan** [comment]
@wjandrea 
Great! 
I've come across the same issue, by rolling back to `1.76.2` from 1.79.2 (the latest), it works well now.

P.S. I noticed that the version of the extension is also adapted to the downgraded version (e.g. the version of Python extension is now `v2023.4.1`, before the downgraded was v2023.10.x)

**Comment by wjandrea** [comment]
I tried testing this on a 22.04 virtual machine but wasn't able to reproduce the issue. On a 20.04 VM, I got an error popup that I never saw before, but I couldn't make sense of it -- I think it said a system library crashed with a segfault.

I'll report back with more info, though I might just upgrade to 22.04 and call it quits.

**Comment by wjandrea** [comment]
Resolved as of 1.82.2. I don't know what caused the problem or when exactly it got fixed.
