### ISSUE TITLE
command 'codeium.openProfile' not found

### ISSUE THREAD

**Issue by xshua06** [VSCodium/vscodium#1554]
**Describe the bug**
command 'codeium.openProfile' not found

This bug happens when I use Microsoft's Visual Studio Code.

**Comment by Ting-xin** [comment]
I have the same question, have you resolved it yet?

**Comment by Mukul1127** [comment]
> **Describe the bug** command 'codeium.openProfile' not found
> 
> This bug happens when I use Microsoft's Visual Studio Code.

This looks like the extension Codeium based on how it's spelled, is it Codeium or Codium, if the first, then the extension issue probably

**Comment by daiyam** [comment]
Not a VSCodium issue
