### ISSUE TITLE
The x86 build does not work on Windows 10

### ISSUE THREAD

**Issue by walpox** [VSCodium/vscodium#1557]
**Describe the bug**
After installing the IA-32 (32-bit) version of VSCodium on a Windows 10 Pro VM, the app does not show up after opening its shortcut in the Start menu. The VSCodium.exe processes show up in Task Manager, but no GUI.

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Create a Windows 10 Pro (32-bit) VM with Hyper-V.
2. Download [https://github.com/VSCodium/vscodium/releases/download/1.79.2.23166/VSCodium-ia32-1.79.2.23166.msi](https://github.com/VSCodium/vscodium/releases/download/1.79.2.23166/VSCodium-ia32-1.79.2.23166.msi) on the VM.
3. Install VSCodium with the defaults.
4. Open the VSCodium shortcut in the Start menu or with the last checkbox in the installer.
5. The app's GUI will not show up on screen.
6. The app's processes will show up in Task Manager.

**Expected behavior**
VSCodium is supposed to show up on screen by running its executable. The equivalent build of Visual Studio Code (VSCodeSetup-ia32-1.79.2.exe) works fine.

**Screenshots**

![2023-06-30-7KDa8D](https://github.com/VSCodium/vscodium/assets/68171111/63076f06-c242-412c-9b0b-853eff8173e7)

**Desktop (please complete the following information):**
 - OS: Windows 10.
 - Architecture: IA-32.
 - Version: 22H2 Build 19045.3086.
 - App Manager: No.
 - Sandboxed: No.

**Additional context**
I checked installing the 32-bit version of VSCodium on a Windows 10 Pro x64 host (no VM) and the problem also occurs.

**Comment by LiarleyCodie** [comment]
Same thing is happening to me. I am using VSCodium in my main system (windows 10 x86). This problem only occurs when i use the latest version of VSCodium, because of that i use the april 4 release.

**Comment by walpox** [comment]
This bug still occurs on VSCodium 1.80.1.23194.

**Comment by tavora-lucas** [comment]
I was having the same problem, but the VSCodium-x64 worked fine. I installed the IA-32 version for mistake

**Comment by walpox** [comment]
This bug is now fixed on VSCodium version 1.83.0.23283.
