### ISSUE TITLE
Windows Defender flagging vscodium.exe as Trojan:Win32/Randet.A!plock

### ISSUE THREAD

**Issue by curather** [VSCodium/vscodium#1564]
The latest version downloaded from here was VSCodium-x64-1.80.1.23194.msi
I installed it and then windows defender popped up flagging it as Trojan:Win32/Randet.A!plock

![image](https://github.com/VSCodium/vscodium/assets/16297956/99323893-5dc6-464f-93a4-a0672d8ea97d)

**Comment by cj360** [comment]
Same here after downloading todays update it gets re-flagged upon opening the new version. 
![vscodium-flagged](https://github.com/VSCodium/vscodium/assets/2075051/cd3d17a1-720c-42d4-9593-05e60af3a41e)

**Comment by refrainsclub** [comment]
Same here

![Screenshot 2023-07-14 132641](https://github.com/VSCodium/vscodium/assets/36752154/4b62a152-5c4b-4411-95cb-0850272934f0)

**Comment by ImperialsGit** [comment]
Same here ![same here](https://github.com/VSCodium/vscodium/assets/68413525/d4af7e12-46d6-4797-ad76-47ca5245cfe3)

**Comment by orbitusii** [comment]
![image](https://github.com/VSCodium/vscodium/assets/64510652/1a08c685-7cc6-4d26-93ac-a56e4d9c8198)

Likewise, another log for the fire here.

**Comment by evvv-vvve** [comment]
Same here
![image](https://github.com/VSCodium/vscodium/assets/76193592/c6943552-74c8-42b7-9402-28e5912cfd88)

**Comment by Yawan-1** [comment]
Same and Defender warned multiple times even after deleting that Trojan File.

**Comment by Tyf0x** [comment]
Last windows update seems to have fixed the issue - so I'm assuming it's a false-positive.

**Comment by daiyam** [comment]
Yes, It's a false positive. (That version has being merged in winget...)
After a quick search, other applications are having the same issue (Roblox studio, stable-diffusion-webui, Dying Light 2 or TickTick)

**Comment by SamHobbsOrg** [comment]
When I try to save a file, that I have been able to save previously, VSCodium says I have insufficient privileges. I edit the same file using VS Code and I am able to save the file. I am not aware of any other applications having a similar problem.

Norton does complain about something but I forget what the messages say and I do not know where to look. I can make more of an effort if important. The messages do not occur at save time.

**Screenshots**
![VSCodiumInsufficientPrivileges](https://github.com/VSCodium/vscodium/assets/46226711/1955c18a-7570-4b4f-bf36-49a5b7b3242f)

- OS: Windows 11 Home 23H2 build 22631.2048
- Architecture: Intel
- VSCodium Version: 1.80.1

**Comment by Crystal-RainSlide** [comment]
@SamHobbsOrg You may have a look at Norton's action history and whitelist that action.
