### ISSUE TITLE
keepassxc no ok

### ISSUE THREAD

**Issue by htqx** [VSCodium/vscodium#1567]
Type: <b>Bug</b>

install vscodium
install keepassxc & on freedesktop secure
no ok

VSCodium version: VSCodium 1.80.1 (77ff082dba0bc91978df4a7acd7f42007abde4cc, 2023-07-13T18:24:25.229Z)
OS version: Linux x64 6.4.3-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (12 x 3980)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.27GB (24.86GB free)|
|Process Argv|--ms-enable-electron-run-as-node --no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
codegeex|AMi|2.0.2
language-gas-x86|bas|0.0.2
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
vsc-material-theme-icons|equ|2.8.0
vscode-hugo-snippets|fiv|0.4.1
code-runner|for|0.12.0
vscode-pull-request-github|Git|0.68.0
vscode-language-pack-zh-hans|MS-|1.80.0
hexeditor|ms-|1.9.9
debugger-for-edge|msj|1.0.16
syncing|non|3.3.4
rust-analyzer|rus|0.3.1583
vscode-markdown-paste-image|tel|1.0.0
pdf|tom|1.2.2
vscode-lldb|vad|1.9.2
volar|Vue|1.8.4
debug|web|0.26.1
var-fast|ydz|0.0.4
markdown-all-in-one|yzh|3.5.1
vscode-zig|zig|0.4.2

</details>

**Comment by htqx** [comment]
An OS keyring couldn't be identified for storing the encryption related data in your current desktop environment.

**Comment by BachoSeven** [comment]
Any news on this?
