### ISSUE TITLE
Enable build-in update system on Linux

### ISSUE THREAD

**Issue by misog** [VSCodium/vscodium#1568]
**Describe the bug**
Build-in update system was disabled on Linux, see https://github.com/VSCodium/vscodium/pull/1548#issuecomment-1641808996

I use `.appimage` version. Before this "fix" I occasionally got Update alert in VSCodium that new version is available. I could click a button which opened this page https://github.com/VSCodium/vscodium/releases/ and I manually updated the `.appimage` file. Also I could do `Help > Check for updates` and then `Help > Download available update` which also opened https://github.com/VSCodium/vscodium/releases/

I was happy. Also users who use `.deb` and other package formats without a package manager were probably happy. 

But now, after this "fix" I can not find `Help > Check for updates` and probably I will not get notified about new updates.

I am sad. Maybe if I did not investigate this I would be happy because I would live happily with outdated VSCodium version forever. _What the eye doesn't see, the heart doesn't grieve over._ Especially in the area of security updates, right?

So this "fix" is misleading because it does not "disable update on linux" but it does "disable update system on linux".

In fact, it is a bug:

> A functional bug means that the program does not work as intended. For example, a user clicks the Save button, but the data is not saved.
Source: https://www.techtarget.com/searchsoftwarequality/definition/bug

A feature which disables such important functionality should be minor, not patch version change (or equivalent). Then it would be not a bug. But it it would be still crippled software in my opinion.

The main reason for disabling it (creating a bug) is that some Linux users which use package managers were confused with update alerts or update menu item.

Yes, **some** of the most users (which use package a manager) were getting confused (user set A). Were those **some** users getting confused for months or years? I would have recommend them to learn Linux basics about package managers or a note in VSCodium documentation about updates and update alerts.

Certainly I would not disable update notifications (alerts) for **all** of the remaining users (users not using a package manager) if they expect it (user set B). So this "fix" is a functional bug by definition for users in set B.

Questions which should be asked.
1) Is it sure that the number of confused and would-be-confused-in-future users in set A is more than the number of all remaining users in set B?
2) Is it worth it to lower confusion for user in set A for the price of risking outdated software and possible unfixed vulnerabilities for users in set B? 
3) How long it would take to prepare the PR to directly fix the confusion problem compared to the time of previous confusion period?
4) Is it sure that VSCodium is a type of software project where UI/UX is preferred over functionality and security?

Also it is a wrong design decision in general, because Linux is different from Windows and MACOS in a way that one should not assume anything about conventions and usualities. Because a standard machine or a popular distro is NOT whole Linux world:

**A)** There are four things which are concern of VSCodium:
- Menu button "Check for updates"
- Auto alert if new update is available
- Automatically updating the VSCodium by VSCodium
- Semi-manual process of updating VSCodium (open releases section in browser)

**B)** And two things which are concern of user
- Automatically updating VSCodium by custom program (dnf, apt, zap, MACOS paid updater, Windows paid updater, ...)
- Manual process of updating VSCodium

The "fix" caused that all in **A)** is disabled for every Linux user in general, hoping that Linux users use some other update program (dnf, apt, zap) or hoping that users will remember to manually update VSCodium.

**I propose to enable build-in system ASAP to save many user-hours of investigating "why update alerts are not working when they worked before" and also to make it right from design perspective.
And then create more granular improvements of VSCodium (like disabling alerts for users using dnf, apt, zap, ...).
The revert should be ASAP because following days many Linux users will get into this trap as last release was only 6 days (4 working days) ago and it is summer time, so many users will update in the future. So there is still time to revert this.**

**Comment by darealshinji** [comment]
I would like the feature of a manual update + notification be enabled too.
