### ISSUE TITLE
Unclear functions related to Shellcheck errors

### ISSUE THREAD

**Issue by zpiatt** [VSCodium/vscodium#1570]
I found two errors where the original intent is unclear to me.
1. In `stores/snapcraft/check_version.sh` the following line (30) produces this error: [https://www.shellcheck.net/wiki/SC2216](https://www.shellcheck.net/wiki/SC2216).
```bash
snap info "${SNAP_NAME}" | true
````
 My guess is this to ignore errors in which case the correct code should be:
```bash
snap info "${SNAP_NAME}" || true
````
2. In `build/linux/appimage/build.sh` the following line (22) produces this error: [https://www.shellcheck.net/wiki/SC2211](https://www.shellcheck.net/wiki/SC2211).
```bash
./pkg2appimage-*.AppImage --appimage-extract && mv ./squashfs-root ./pkg2appimage.AppDir
```
I am unsure of the intent/fix for this issue.

**Comment by daiyam** [comment]
1. Yes, it should be `snap info "${SNAP_NAME}" || true`

2. We are failing in the case mentioned in the **Exceptions**

Let's force the name of binary:
```
wget -c "${APPIMAGE_URL}" -o pkg2appimage.AppImage

chmod +x ./pkg2appimage.AppImage

./pkg2appimage.AppImage --appimage-extract && mv ./squashfs-root ./pkg2appimage.AppDir
```

**Comment by zpiatt** [comment]
Ok, this make sense now. I am making those changes now. I will have a PR ready shortly with the completion of Shellcheck for the entire repo.

**Comment by zpiatt** [comment]
Closed with [https://github.com/VSCodium/vscodium/pull/1572](https://github.com/VSCodium/vscodium/pull/1572)
