### ISSUE TITLE
The Dreaded Electron icon bug is back!!

### ISSUE THREAD

**Issue by Alex313031** [VSCodium/vscodium#1571]
Same bug as this > https://github.com/VSCodium/vscodium/issues/1448

It has come back. I have tried in a VM and with real hardware.
Tried with:

Windows 10 and 11
Nodejs 16.17, nodejs 16.20
Python 3.9 and 3.11
Visual studio 2019 and 2022, with 19041, 22000, and 22621 winSDK toolchains
Using 7zip 2201 and latest jq.exe
Tried with wix 3 and 4

Doesn't matter what the f*** I do, the Icon STILL ends up being the default electron one instead of the proper one.

This happens with 1.78.2, 1.80.1, and insiders 1.81.0.
IDK what to do and how other people are not coming across this. I wish I knew EXACTLY the environment you guys are using to build on github actions so I can replicate it, because apparently your builders are not encountering this.

Plz help...

**Comment by daiyam** [comment]
Hi @Alex313031,

You can find the `windows-2019` specs at https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md

Can you make sure that after a build, you have in the correct icon at `vscode/resources/win32/code.ico`?

**Comment by Alex313031** [comment]
@daiyam Yes, I have checked that. All patches were applied correctly, and icons were copied correctly. Im using vanilla vscodium. Also happens with my fork, codium. Doesn't happen with upstream vscode.

**Comment by Alex313031** [comment]
@daiyam Second update:

It also happens with upstream VSCode. I used windows server 2019.

What do you use on your own local win10 setup? To compare it to mine and see if I am missing anything or different versions.

Windows 10 22H2
Visual Studio 2019 with 17763 Windows SDK installed + Visual C++ tools
7-Zip 23.01 with jq.exe in the same folder and added to my path so that git bash can find jq.exe and 7z.exe.
Python 3.9 installed system wide and in my path.
Git + Git Bash for Windows 2.41.0
Nodejs 16.20.1
WiX toolset version 3.11 installed system wide.
Latest net framework and Visual C++ Redistributables installed.

I clone Vscodium, and run .\build\build.ps1 in powershell. Everything builds correctly, but the damn icon is wrong.

**Comment by daiyam** [comment]
- Windows 10 21H2
- no Visual Studio
- 7-Zip 22.01
- Python 3.9.6
- Git + Git Bash for Windows 2.37.3
- nodejs 16.19.1
- WiX 3.11.2.4516

Maybe you could reapply the icon (you can look at https://github.com/microsoft/vscode/blob/501a0190687e5bd799ff6844d9563b45c0e3ed53/build/gulpfile.vscode.win32.js#L156 on how to do it)?

**Comment by Alex313031** [comment]
@daiyam That sets the icon on the installer, not the actual .exe.

Happens with vscodium and vscode. I might file a bug upstream

**Comment by Alex313031** [comment]
@daiyam https://github.com/microsoft/vscode/issues/191077

**Comment by Alex313031** [comment]
@daiyam Upon more investigation, it seems that either the @vscode/gulp-electron or the rcedit npm package is screwing up. Because not only is the icon not set, all the other .rc metadata that is supposed to be set on the electron executable is NOT being set. The version, company name, and copyright are still the same as electron upstream, whereas my previous sucessful codium build, and vscodium downloaded from this repo has Copyright VSCodium and proper version set.

Even with yarn install --frozen-lockfile, it doesn't work properly.

I am trying to manually set rcedit and gulp-electron to the last known working version, and I will get back to you.

**Comment by Alex313031** [comment]
@daiyam FINALLY FOUND the culprit.

It IS because gulp-electron is using a very outdated rcedit. Forking it, updating rcedit, and building VSCode and VSCodium fixes the issue. I have filed a bug and PR upstream!

See > https://github.com/microsoft/vscode-gulp-electron/issues/16

**Comment by 15904550933** [comment]
How can I solve this problem? Can I update the rcedit version？

**Comment by 15904550933** [comment]
https://github.com/microsoft/vscode-gulp-electron/pull/17
