### ISSUE TITLE
insiders unavailable in deb-rpm repo 

### ISSUE THREAD

**Issue by kimcosmos** [VSCodium/vscodium#1578]
https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ 
404 error for all deb-rpm repos
Unable to locate package codium-insiders
thus all debian and rpm install instructions are incorrect [except flatpak]
https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo#how-to-install-for-debianubuntulinux-mint

**Comment by Codedevlo** [comment]
@kimcosmos Try checking `apt-get list codium*`; it should show something like this:
```
codium/unknown 1.80.1.23208 amd64
```

It doesn't show `codium-insider` for me and is missing from https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/index.
Maybe the Gitlab repo/mirror doesn't include `codium-insider`? not sure. :man_shrugging: 
@paulcarroty

**Comment by paulcarroty** [comment]
The `insider-linux` job failed several times: https://github.com/VSCodium/vscodium/actions?query=workflow%3Ainsider-linux
