### ISSUE TITLE
VSCodium 1.80.1.23194 checksums do not match

### ISSUE THREAD

**Issue by Thilas** [VSCodium/vscodium#1579]
**Describe the bug**
Same as #192, I am maintaining the Chocolatey package for VSCodium and last release (1.80.1.23194) has been updated with new installers (i.e. new checksums).

In the context of a Chocolatey package, this is an issue because the checksum is done once and is not expected to change overtime (see https://github.com/Thilas/chocolatey-packages/issues/62).

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install chocolatey (https://chocolatey.org/install)
2. Install VSCodium using chocolatey: `choco install vscodium`

**Expected behavior**
Install should be alright, i.e. checksums should be immutable.

**Desktop (please complete the following information):**
 - OS: Windows
 - Architecture: x64, ia32
 - Version: 1.80.1.23194

**Comment by daiyam** [comment]
Ya, it was a mistake due to some optimisations of the bash scripts.

I will create backup of release files so if it happens again, I will able to put the original files back.
