### ISSUE TITLE
Module compatiblily : tomsaunders.vscode-workspace-explorer

### ISSUE THREAD

**Issue by camlafit** [VSCodium/vscodium#159]
**Describe the bug**
This module can't reload vscodium when a workspace is selected.

Display information is ok, all workspsace are displayed in sidebard. But when a workspace is selected, should reload/update workspace context.
Works withs code but not with vscodium

**Please confirm that this problem is VSCodium-specific**
- [ x ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ x ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install https://marketplace.visualstudio.com/items?itemName=tomsaunders.vscode-workspace-explorer
2. Configure a workspace directory
3. Try to load a workspace from side bar

**Expected behavior**
Vscodium should be update with new workspace context

**Comment by lsmoura** [comment]
The problem with this extension is the way it tries to open `vscode`. According to [its own source code](https://gitlab.com/jfwy2bhilv/9vsgwopwel/vscode-workspace-explorer/blob/master/extension.js#L34)

```javascript
  // Identify which application to use.
  let applicationName;
  if (vscode.env.appName == 'Visual Studio Code - Insiders') {
    applicationName = 'code-insiders';
  } else {
    applicationName = 'code';
  }
```

I'm pretty sure it's trying to invoke `vscode` instead of `vscodium`, which is triggering the error. Even tough it "does work with vscode and not with vscodium", I'm thinking it will be tricky to solve this problem without changing the extension's source code.

**Comment by stripedpajamas** [comment]
We've seen this kind of hard coding of the app in extensions before -- usually a small PR to the extension repo with another conditional is well received 😊

(Thanks for digging in @lsmoura)

**Comment by stripedpajamas** [comment]
The change is very small, and I've made it in a fork of the project (https://gitlab.com/stripedpajamas/vscode-workspace-explorer/commit/88b14503ee1b8c2516a7341e95d682db77af0cfd), but I can't figure out how to open a merge request to the parent repository the way they have it set up. 

If you go [here](https://gitlab.com/groups/jfwy2bhilv/9vsgwopwel/-/merge_requests), you can choose to open a merge request for `vscode-workspace-explorer`, but when you actually hit the button, it 404s - https://gitlab.com/jfwy2bhilv/9vsgwopwel/vscode-workspace-explorer/merge_requests/new

**Comment by camlafit** [comment]
Hello

Thank a lot PR doesn't look enable in this repository.
I've followed old way and open an issue 
https://gitlab.com/jfwy2bhilv/9vsgwopwel/vscode-workspace-explorer/issues/3

Thanks a lot

**Comment by stripedpajamas** [comment]
Awesome 👍 I will close out this issue as the responsibility is on the extension maintainer at this point.

**Comment by camlafit** [comment]
Hello

It's closed \o/ Thank a lot 

https://gitlab.com/jfwy2bhilv/9vsgwopwel/vscode-workspace-explorer/merge_requests/1
