### ISSUE TITLE
trouble connecting to remote server

### ISSUE THREAD

**Issue by JunkyardCat** [VSCodium/vscodium#1591]
**Describe the bug**
I cant ssh into my remote debian server. Im win10 and using the extension open remote ssh 0.0.39 and my vscodium 1.81.0.23216. I was able to connect just fine but after i did an update through the self auto update it now fails to connect. Take note i didnt restart or anything

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to remote explorer 
2. Choose the host and directory to ssh into
3. Enter the password (fail) could not establish connection to hostname1

**Expected behavior**
Able to ssh in

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win 10 connecting to debian bullseye
 - Architecture x64
 - Version 19045.2364
 - App Manager [e.g. Winget, Homebrew, Snap, AUR, RPM, Nix, ...]n/a
 - Sandboxed [e.g. no, Flatpak, Snap]n/a

**Additional context**

**Comment by daiyam** [comment]
The REH(server) binaries are only available since 15 minutes ago. So now, it should work.
