### ISSUE TITLE
Asking for keyring

### ISSUE THREAD

**Issue by ttsoares** [VSCodium/vscodium#1594]
Type: <b>Bug</b>

Every time Codium starts there is a dialog window asking my keyring password. But my keyring password is not accepted ! What works is my user password, that is totally different. The key ring is to access, for instance, my Github account, but my user pass can do '**sudo'** ! I do not like to give sudo permissions to any process that do not need it...

_$ ps auxw | grep ring
myuser    1280  0.0  0.0 535860  8316 ?        SLl  08:44   0:00 gnome-keyring-daemon --start
myuser    2303  0.0  0.0   8092  5956 ?        S    08:44   0:00 /usr/bin/ssh-agent -D -a /run/user/1000/keyring/.ssh_

<br>

VSCodium version: VSCodium 1.81.0 (ee0ba35e0f5ffb18669618446b41de0e99569167, 2023-08-04T18:13:08.077Z)
OS version: Linux x64 5.15.0-78-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 2, 1|
|Memory (System)|11.54GB (7.28GB free)|
|Process Argv|--ms-enable-electron-run-as-node .|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
html-snippets|abu|0.2.1
tailwind-docs|aus|2.1.0
htmltagwrap|bra|1.0.0
vscode-tailwindcss|bra|0.9.11
simple-react-snippets|bur|1.2.7
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
ccs-flutter-color|cir|1.0.2
dakara-foldplus|dak|1.5.2
vscode-eslint|dba|2.4.2
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.14
live-sass|gle|6.0.6
smartmulticursor|ida|0.0.4
functional-js-snippets|kol|1.0.2
vscode-language-babel|mgm|0.0.39
dotenv|mik|1.0.1
vscode-duplicate|mrm|1.2.1
vscode-typescript-next|ms-|5.2.20230805
indent-rainbow|ode|8.3.1
convert-css-in-js|pau|1.1.3
material-icon-theme|PKi|4.29.0
vscode-css-peek|pra|4.4.1
prisma|Pri|5.1.0
create-react-tsx-component|ric|1.11.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.9
format-code-action|roh|0.1.0
vscode-paste-and-indent|Rub|0.0.8
markdown-preview-enhanced|shd|0.6.8
svg-preview|Sim|2.8.3
indenticator|Sir|0.7.0
js-jsx-snippets|sky|11.0.1
vscode-standard|sta|2.1.3
vscode-status-bar-format-toggle|tom|3.1.1
errorlens|use|3.12.0
console-ninja|Wal|0.0.192
nextjs|Wil|0.0.8
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details>

**Comment by ProDeSquare** [comment]
Try launching **Codium** with `codium --password-store="gnome-keyring"` flag. If this solution helps, then while in **Codium** hit `Ctrl+Shift+P` and run `Preferences: Configure Runtime Arguments` command. This would open `argv.json` and add `"password-store": "gnome-keyring"` so you don't have to specify the flag each time you launch **Codium**.

**Comment by ttsoares** [comment]
By launching with those props did fix the appearance of the dialog window asking the password...
But when I tried to insert the new line in argv.json there is an error message telling:
 - Property "password-store" is not allowed.

**Comment by ProDeSquare** [comment]
Just add the `password-store` property anyway and set it to your default keyring. Possible keyrings could be:
1. `gnome`
2. `gnome-keyring`

If this still doesn't fix the issue try installing the `seahorse` package and check if the default keyring is unlocked

**Comment by ttsoares** [comment]
That line in argv.json fixed the appearance of the dialog windows. Thank you.
As I rather deal with git in a xterm, my hope is that the IDE do not start messing around with my repos.

**Comment by ttsoares** [comment]
As I rather deal with git in a xterm, my hope is that the IDE do not start messing around with my repos.

**Comment by boussou** [comment]
thanks.
it worked for me with ```	"password-store": "gnome", ``` but not "gnome-keyring"

**Comment by boussou** [comment]
> 1. gnome

thanks.
it worked for me with ```	"password-store": "gnome", ``` but not "gnome-keyring"

**Comment by boussou** [comment]
Solution: 
```
vscodium --password-store=basic 
```

or
 
```
"password-store": "basic"
```

Configure Runtime Arguments command. This would open argv.json and add "password-store": "basic" 

source : https://stackoverflow.com/questions/63107939/visual-studio-code-asking-to-authenticate-default-keyring-everytime-i-start

**Comment by ProDeSquare** [comment]
> installing seahorse had no effect

The `seahorse` package is to manage PGP keys, which was only recommended to check if the default keyring was unlocked.

**Comment by boussou** [comment]
I think your recommendation were good. Except it is better to write "basic" to avoid keyring ;-)
