### ISSUE TITLE
Changelog support

### ISSUE THREAD

**Issue by joseluisq** [VSCodium/vscodium#160]
Please log your changes somewhere in order to follow the project progress for every release.
For example, a [changelog](https://keepachangelog.com/en/1.0.0/) would be a good option or Github releases too.

**Comment by stripedpajamas** [comment]
Sounds like a good idea 👍  I will add a description to the Github release with VSCodium-specific changes that occurred since the last release.

**Comment by joseluisq** [comment]
:+1:
