### ISSUE TITLE
extension list

### ISSUE THREAD

**Issue by lufke** [VSCodium/vscodium#1603]
Type: <b>Bug</b>

cant't fetch extensions list. error 500 from server

VSCodium version: VSCodium 1.81.1 (aef377c42cea6e9aea642829953104f07097abfa, 2023-08-10T18:29:45.715Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12650H (16 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.63GB (9.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by lapawa** [comment]
The same here on macOS Ventura 13.5 with VSCodium 1.81.1.23222 installed by brew.

**Comment by albertguedes-estuda** [comment]
Same problem with me. 

Version: 1.80.0
Release: 23188
Commit: 9d3b0fa210fb4535589e8296483a5b43fe5e660a
Date: 2023-07-07T18:21:29.357Z
Electron: 22.3.14
ElectronBuildId: undefined
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.1.41-gentoo-x86_64

![image](https://github.com/VSCodium/vscodium/assets/130697946/2a042e3b-cc41-4990-b9ab-1777890c9639)

**Comment by popsUlfr** [comment]
Search API seems down

https://status.open-vsx.org/

**Comment by e-g1gor** [comment]
Have same issue, installing extensions via `Ctrl+P` quick open still works.
![image](https://github.com/VSCodium/vscodium/assets/29484330/7e4e4912-0b4c-4f9d-b654-5e8ba0e11d23)
