### ISSUE TITLE
Connection to market place

### ISSUE THREAD

**Issue by london-coder** [VSCodium/vscodium#1604]
**Describe the bug**
When searching the EXTENSION: MARKETPLACE, using the search key(s) C++ or c++, all I see is:
Error while fetching extensions. Server returned 500 

**Please confirm that this problem is VSCodium-specific**
- This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to 'EXTENSIONS'
2. Click on 'text box'
3. Enter C++ or c++

**Expected behavior**
To see extension by the filter 

**Screenshots**

**Desktop (please complete the following information):**
Version: 1.81.1
Release: 23222
Commit: aef377c42cea6e9aea642829953104f07097abfa
Date: 2023-08-10T18:39:03.748Z
Electron: 22.3.18
ElectronBuildId: undefined
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.6.0
 - OS: [Mac OS  Ventura 13.5]
 - Architecture [ x64,]
 - Version [e.g. 13.5]
 - App Manager [e.g. Winget, Homebrew, Snap, AUR, RPM, Nix, ...]
 - Sandboxed [e.g. no, Flatpak, Snap]

**Additional context**

**Comment by slc66** [comment]
Hello, 

I have the same issue.

Version: 1.81.1
Commit: aef377c42cea6e9aea642829953104f07097abfa
Architecture :x64 
OS: BunsenLabs GNU/Linux 11 (Beryllium)

**Comment by NickDCA** [comment]
Hi,

I'm having the same problem when searching for any extension in Marketplace.

**Comment by DARKBOW923** [comment]
I'm having the same problem, i can see an error 500 when i try to use the marketplace for vscodium, i tried to go to open-vsx and its down too, could be that related to the vscodium marketplace? If i remember, vscodium doesn't use the official visual studio code marketplace, but uses the FOSS store one, if the codium marketplace is not working i guess that maybe could be related to open-vsx being down at the moment.

**Comment by daiyam** [comment]
Yes, VSCodium is using OpenVSX

**Comment by DARKBOW923** [comment]
> Yes, VSCodium is using OpenVSX

Then we can confirm, the search API for open-vsx is down, so that's why vscode marketplace is down.

**Comment by mbnoimi** [comment]
> Then we can confirm, the search API for open-vsx is down, so that's why vscode marketplace is down.

Really strange! OpenVSX itself works fine but their API is downs!!!

**Comment by 0tii** [comment]
I too have encountered this issue

**Comment by T00rk** [comment]
Same problem here.
Error 500 when connecting to marketplace

**Comment by Danielduel** [comment]
I suggest retrying @london-coder

**Comment by mbnoimi** [comment]
> I suggest retrying @london-coder

Voila, It's working now.

**Comment by AlexNottaBen** [comment]
Hello,

I have the same issue.
Version: 1.81.1
"Error while fetching extensions. Server returned 500."

**Comment by ProDeSquare** [comment]
I tried the same and it works without any problem

VS Codium Version: 1.81.1

![screenshot_full-230821_223044](https://github.com/VSCodium/vscodium/assets/41067282/31ea249d-05d2-4525-93b5-26fef9be2fe8)

Additionally, on **Arch GNU/Linux** `vscodium-bin-marketplace` is available on the AUR which enables **vscode** marketplace in **VS Codium**. You may also search a similar package for your distribution.

**Comment by mbnoimi** [comment]
> Additionally, on **Arch GNU/Linux** `vscodium-bin-marketplace` is available on the AUR which enables **vscode** marketplace in **VS Codium**. You may also search a similar package for your distribution.

I'm a little curious. I couldn't find such a thing in the official repository dedicated for Ubuntu bases distro!
I believe `vscodium-bin-marketplace` is not an official package.

**Comment by ProDeSquare** [comment]
> > Additionally, on **Arch GNU/Linux** `vscodium-bin-marketplace` is available on the AUR which enables **vscode** marketplace in **VS Codium**. You may also search a similar package for your distribution.
> 
> I'm a little curious. I couldn't find such a thing in the official repository dedicated for Ubuntu bases distro! I believe `vscodium-bin-marketplace` is not an official package.

You can use **VS Code** marketplace with **VS Codium**, guide is present [here](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#how-to-use-the-vs-code-marketplace) in the official **VS Codium** docs. Even without enabling **VS Code** marketplace, **VS Codium** didn't throw any error. I just enabled that a while ago just because the theme I use (Marine Dark) wasn't available on the **Codium** marketplace.

**Comment by daiyam** [comment]
Or use my extension [VSIX Manager](https://open-vsx.org/extension/zokugun/vsix-manager) to be able to use multiple marketplaces

@mbnoimi [`vscodium-bin-marketplace`](https://aur.archlinux.org/packages/vscodium-bin-marketplace) is a hook in the AUR (Arch User Repository) so it's only available on Arch.

**Comment by ProDeSquare** [comment]
> Or use my extension [VSIX Manager](https://open-vsx.org/extension/zokugun/vsix-manager) to be able to use multiple marketplaces
> 
> @mbnoimi [`vscodium-bin-marketplace`](https://aur.archlinux.org/packages/vscodium-bin-marketplace) is a hook in the AUR (Arch User Repository) so it's only available on Arch.

That may be the solution to install extensions from the VSIX files or to access multiple marketplaces, but for them, the marketplace is returning server error.

**Comment by Danielduel** [comment]
I suggest marking this issue as Completed @london-coder
