### ISSUE TITLE
Error while fetching extensions.

### ISSUE THREAD

**Issue by kaelynbu** [VSCodium/vscodium#1605]
Type: <b>Bug</b>

Open VSCodium, click on extensions, search any extension.

![image](https://github.com/VSCodium/vscodium/assets/116585000/b0c04d05-93f0-4726-9b12-5e5319e40cbc)

VSCodium version: VSCodium 1.81.1 (aef377c42cea6e9aea642829953104f07097abfa, 2023-08-10T18:29:45.715Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by pleish** [comment]
Same error for me.

**Comment by jmsalvat** [comment]
#1604

**Comment by HI101AI** [comment]
This is an error in extensions gallery pulled from _open-vsx.org_.

Try to change it towards _makerplace.visualstudio.com_ in **product.json** file. 

in
`/usr/share/codium/resources/app/product.json`

search for
```javascript
"extensionsGallery": {
    "serviceUrl": "https://open-vsx.org/vscode/gallery",
    "itemUrl": "https://open-vsx.org/vscode/item"
```
replace with
```javascript
"extensionsGallery": {
    "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
    "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
    "itemUrl": "https://marketplace.visualstudio.com/items"
```

**Comment by nlin24** [comment]
Thanks! This seems to fix the issue for me. I'm running VScodium from Flatpak.
```
#$ flatpak list
Name                Application ID                                Version         Branch        Installation
VSCodium            com.vscodium.codium                           1.81.1.23222    stable        system
```

> This is an error in extensions gallery pulled from _open-vsx.org_.
> 
> Try to change it towards _makerplace.visualstudio.com_ in **product.json** file.
> 
> in `/usr/share/codium/resources/app/product.json`
> 
> search for
> 
> ```js
> "extensionsGallery": {
>     "serviceUrl": "https://open-vsx.org/vscode/gallery",
>     "itemUrl": "https://open-vsx.org/vscode/item"
> ```
> 
> replace with
> 
> ```js
> "extensionsGallery": {
>     "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
>     "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
>     "itemUrl": "https://marketplace.visualstudio.com/items"
> ```

**Comment by GioU57** [comment]
What if I do not want to use the Visual Studio Gallery? Do I just wait until the search api is fixed on the VSX registry?

**Comment by Danielduel** [comment]
Looks like it is fixed for me, could you retry @kaelynbu

**Comment by karstengit** [comment]
Today installed codium_1.82.2.23257_amd64.deb from
https://github.com/VSCodium/vscodium/releases/download/1.82.2.23257/codium_1.82.2.23257_amd64.deb

It's still the same issue and has not been fixed.
