### ISSUE TITLE
Server returned 500

### ISSUE THREAD

**Issue by LeFaucheur0769** [VSCodium/vscodium#1607]
**Describe the bug**
When i tried to install an extension, it said that the server returned 500 and i cannot see any extensions  

**Please confirm that this problem is VSCodium-specific**
- This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to extension,s
2. Click on 'search.'
3. Write 'python'

**Screenshots**
[screenshot](https://github.com/VSCodium/vscodium/assets/90474269/02c3ea4f-9298-4ad6-a0ea-c7c50384f558)

**Desktop (please complete the following information):**
 - OS: linux mint 21.2
 - Architecture x64
 - Version 1.81.1.23222
 - App Manager apt (nala)
 - Sandboxed no

Thank you for the help

**Comment by blackandcold** [comment]
same here, maybe it has to do with the store itself - let us see

**Comment by Danielduel** [comment]
@blackandcold @LeFaucheur0769 Looks like it is fixed for me.

**Comment by blackandcold** [comment]
yes, server working again

**Comment by LeFaucheur0769** [comment]
> @blackandcold @LeFaucheur0769 Looks like it is fixed for me.
for me too
