### ISSUE TITLE
JS/TS language teatures

### ISSUE THREAD

**Issue by zeenmc** [VSCodium/vscodium#1612]
Type: <b>Bug</b>

Just started VSCodium, no steps :)

VSCodium version: VSCodium 1.81.1 (aef377c42cea6e9aea642829953104f07097abfa, 2023-08-10T18:39:03.748Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|10, 6, 4|
|Memory (System)|16.00GB (2.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
commit-message-editor|ada|0.25.0
gitignore|cod|0.9.0
git-history-plus|cwe|1.1.1
githistory|don|0.6.20
gitlens|eam|14.2.1
git-graph|mhu|1.30.0
vscode-azureappservice|ms-|0.24.9
vscode-azurefunctions|ms-|1.12.4
vscode-azureresourcegroups|ms-|0.7.5
python|ms-|2023.12.0
jupyter|ms-|2023.3.100
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
azure-account|ms-|0.11.5
azurecli|ms-|0.5.0
git-commit-plugin|red|1.2.0
vscode-git-extension-pack|sug|1.1.1
xasnippets|Tom|2.13.1
vscode-conventional-commits|viv|1.25.0
gitblame|wad|10.4.0

(1 theme extensions excluded)

</details>

**Comment by GitMensch** [comment]
It is completely unclear what this issue is about (you installed vscodium and it opens). Please elaborate.
