### ISSUE TITLE
Windows arm64 system-setup installer - version check not working `Server returned 404`

### ISSUE THREAD

**Issue by docgalaxyblock** [VSCodium/vscodium#1616]
The Update checker does not work on system-setup arm64 windows builds. x86 is working fine.
user-setup and portable

- This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
- I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
- Install a system-setup version (`VSCodiumSetup-arm64- ... .exe`)
 - Click `Check for Updates...`

**Laptop:**
 - Arm64 - Win 11 22H2 22621.2134
 ```
Version: 1.81.1 (system setup)
Release: 23222
Commit: aef377c42cea6e9aea642829953104f07097abfa
Date: 2023-08-10T18:37:00.983Z
Electron: 22.3.18
ElectronBuildId: undefined
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT arm64 10.0.22621
 ```
 
 Logs with `codium.cmd --verbose`
 ```
[main 2023-08-25T09:22:52.257Z] update#checkForUpdates, state =  idle
[main 2023-08-25T09:22:52.258Z] update#setState checking for updates
[main 2023-08-25T09:22:52.258Z] resolveShellEnv(): skipped (Windows)
[main 2023-08-25T09:22:52.564Z] Error: Server returned 404
    at o (C:\Program Files\VSCodium\resources\app\out\vs\code\electron-main\main.js:43:35119)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[main 2023-08-25T09:22:52.568Z] update#setState idle
[16968:0825/112252.575:INFO:CONSOLE(762)] "Server returned 404", source: vscode-file://vscode-app/c:/Program%20Files/VSCodium/resources/app/out/vs/workbench/workbench.desktop.main.js (762)
 ```

**Comment by docgalaxyblock** [comment]
Update:

The extractable zip version `VSCodium-win32-arm64-1.81.1.23222.zip` is not affected.

`.\VSCodium.exe --verbose --wait`
```
[main 2023-08-25T09:48:52.331Z] update#checkForUpdates, state =  idle
[main 2023-08-25T09:48:52.332Z] update#setState checking for updates
[main 2023-08-25T09:48:52.332Z] resolveShellEnv(): skipped (Windows)
[main 2023-08-25T09:48:52.560Z] update#setState idle
```

**Comment by daiyam** [comment]
@docgalaxyblock With which installer was the initial report?

**Comment by docgalaxyblock** [comment]
@daiyam The current System Setup installer (`VSCodiumSetup-arm64-1.81.1.23222.exe`)

**Comment by docgalaxyblock** [comment]
@daiyam Update: UserSetup is also not affected.
I have tried `VSCodiumUserSetup-arm64-1.82.2.23257.exe` and it updates to 1.83.1

So only system-setup installs are affected. Any idea why only this variant?

**Comment by daiyam** [comment]
OK I've finally found the issue...

On Windows, when it's a system install or x86 install, those info aren't send to the update server.
The update server does correctly default to system install for x64 and x86 systems.
But for arm64 system install, no default is done and return a 404.

First fix is to update the update server to add the default.
Second fix will be to update VSCodium to send all the useful data to avoid to default to possibly wrong data...

**Comment by daiyam** [comment]
Damn! The deployment on Vercel is failing and I can't see the error...

**Comment by docgalaxyblock** [comment]
Not sure when you did a fix but at the moment it works.
I had updated it to 1.85.0 and just confirmed the update checker now while updating to 1.85.1
