### ISSUE TITLE
Pylance stopped working

### ISSUE THREAD

**Issue by alecov** [VSCodium/vscodium#1622]
**Describe the bug**
Pylance is not working again, even with product.json specific hacks (setting `nameLong` and `nameShort` to `"Visual Studio Code"`).
Reporting here as to help us track the next workaround for this.

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Install Pylance, set the above necessary product.json flags and check that Pylance does not work anymore.

**Additional context**
Stopped working recently in my setup (last couple weeks), a new update to the extension must have broken things again.

**Comment by paulcarroty** [comment]
Closing in favor of https://github.com/VSCodium/vscodium/issues/1556#issuecomment-1624331493.
