### ISSUE TITLE
ritwickdey Live Server Extension doesn't work on VSCodium Version 1.8.1.1 User but it works on VSCode in the same machine

### ISSUE THREAD

**Issue by NAXSIS94** [VSCodium/vscodium#1623]
VSCodium Version 1.8.1.1
Live Server;
-Version  : 5.7.9
- Owner : ritwickdey

Does not work ( try reinstall ( vscodium, Live server Extension, XAMPP (workin on php btw) )

Latest Vs Code and latest ritwickdey Live server extension the live server works.

is there any body to help ( btw i not that's not a support etc, i try tôsolve and struggle with two days, Thx)

Wheñthe problem solve i can delete the bug report immediately

**Comment by daiyam** [comment]
Go the extension (https://github.com/ritwickdey/vscode-live-server) to report the issue.
