### ISSUE TITLE
Install  link installs VS Code, not VSCodium

### ISSUE THREAD

**Issue by SamHobbsOrg** [VSCodium/vscodium#1633]
See [Releases · VSCodium/vscodium](https://github.com/VSCodium/vscodium/releases). When I click on _update vscode to 1.82.0_, the link is for `visualstudio.com`, correct? It installs VS Code, not VSCodium, correct?

**Comment by daiyam** [comment]
Yes, that's correct so that you can see what are the changes.

**Comment by SamHobbsOrg** [comment]
It is supposed to install VS Code? I cannot install VSCodium? I get to that page when I try to install VSCodium. I do not see how I am supposed to install VSCodium.

**Comment by daiyam** [comment]
In "Assets"

**Comment by SamHobbsOrg** [comment]
In [VSCodium/vscodium: binary releases of VS Code without MS branding/telemetry/licensing](https://github.com/VSCodium/vscodium) I click on _Download latest release here_. In that page it does say update **vscode**. I apologize for not thinking. I think however it could be more clear about saying the link is **for** VS Code updates. It is not clear we need to scroll down to download VSCodium.  At least this (issue or post or whatever) will help others in the future.
