### ISSUE TITLE
What are these call?

### ISSUE THREAD

**Issue by frederikhors** [VSCodium/vscodium#1636]
**Describe the bug**
First time I'm using it today.

The first time I opened it my firewall blocked a call to this IP address: 142.251.209.46.

Second time at this: 185.199.108.133.

What is it about?

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Just open it

**Desktop (please complete the following information):**
 - App Manager: scoop

```
Version: 1.82.0
Release: 23250
Commit: 13ae69686c4390a9aee7b71b44337eb488319f26
Date: 2023-09-07T19:06:27.091Z
Electron: 25.8.0
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by python-and-fiction** [comment]
visit https://site.ip138.com/185.199.108.133/
you will get some sites which belong to github,i guess that is vscodium's checking.

**Comment by frederikhors** [comment]
Hence my question: what is it?

**Comment by daiyam** [comment]
update check
