### ISSUE TITLE
Repository for deb and rpm packages doesn't work anymore. - Github 404 

### ISSUE THREAD

**Issue by nercolaszerg** [VSCodium/vscodium#1638]
**Describe the bug**
Try to upgrade vscodium - "https://download.vscodium.com/debs" was ignored - 404.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if any other package I installed. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to 'Terminal'.
2. Type or insert `sudo apt upgrade`.
3. See the ignored state.
4. Try to open `https://download.vscodium.com/debs` in the browser. 
5. See error - get 404 from github.

**Expected behavior**
Upgrade the package if newer version is present.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture x86_64
 - Version 1.82.0
 - App Manager apt and nala as wrapper

**Comment by chebedewel** [comment]
Have a look here : https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/blob/master/README.md

**Comment by nercolaszerg** [comment]
Now `https://download.vscodium.com/debs` works again. Issue can be closed. Thanks.

**Comment by QuickMythril** [comment]
this appears to be offline again at the moment.

**Comment by FovenX3** [comment]
offline again at the moment.
