### ISSUE TITLE
Release 1.82.1.23255 missing vscodium-reh-linux-x64-1.82.1.23255.tar.gz

### ISSUE THREAD

**Issue by ltcptgeneral** [VSCodium/vscodium#1639]
**Describe the bug**
The newest release seems to be missing vscodium-reh-linux-x64-1.82.1.23255.tar.gz.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Using remote explorer, try to connect to a linux remote target running on x64. 

Should return this error: 
```
Server install command stderr:
https://github.com/VSCodium/vscodium/releases/download/1.82.1.23255/vscodium-reh-linux-x64-1.82.1.23255.tar.gz:
2023-09-12 20:36:39 ERROR 404: Not Found.
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows (Ubuntu Server remote target)
 - Architecture: x64
 - Version: 1.82.1
 - App Manager: winget
 - Sandboxed: no

**Comment by daiyam** [comment]
appimage build has been disabled
