### ISSUE TITLE
Text blank in Linux Fedora

### ISSUE THREAD

**Issue by asharifauzan** [VSCodium/vscodium#1642]
**Describe the bug**
I just updated my Vscodium to 1.82.2 and after reopening the app I wondered why all the texts of the contents are blank, I decided to downgrade to 1.82.1 and the problem still occurs. So I decided to downgrade again to 1.80.1 which is the latest version I had downloaded.

**Please confirm that this problem is VSCodium-specific**
I also facing this issue in Vscode-insiders (1.83), but in Vscode (1.82.2) & Vscodium-insiders (1.83) the problem is not occur

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open Vscodium
2. See all texts are disappeared

**Expected behavior**
Just works normally

**Screenshots**
![image](https://github.com/VSCodium/vscodium/assets/52328248/f1e481a6-8978-4871-b97e-b45aef4226c0)
![image](https://github.com/VSCodium/vscodium/assets/52328248/a30d5f84-6f87-4dce-9836-802319626e37)

**Desktop (please complete the following information):**
 - OS: Fedora 38 XFCE, GTK 3.24.38
 - Architecture x64
 - Version 1.82.2
 - App Manager dnf dragora
 - Sandboxed no

**Additional context**
I don't think the texts really disappear or maybe the texts are set to colored transparent since I tried to copy a random file and paste it to another text editor (pluma) and it copied all the selected code

**Comment by python-and-fiction** [comment]
@asharifauzan Could you try 1.82.2 which is tar.gz format? I think that maybe something was broken during upgrading vscodium.
I create a Fedora 38 with XFCE in VM,and install vscodium via rpm of release 1.82.2, but the issue doesn't appear.
![Fedora_xfce-2023-09-17-16-45-04](https://github.com/VSCodium/vscodium/assets/16256910/40400ea4-114a-4d91-b9fd-b4a4bd345d7b)

**Comment by asharifauzan** [comment]
> @asharifauzan Could you try 1.82.2 which is tar.gz format? I think that maybe something was broken during upgrading vscodium.
> I create a Fedora 38 with XFCE in VM,and install vscodium via rpm of release 1.82.2, but the issue doesn't appear.
> Please try to disable all extensions and restart.
> ![Fedora_xfce-2023-09-17-16-45-04](https://github.com/VSCodium/vscodium/assets/16256910/40400ea4-114a-4d91-b9fd-b4a4bd345d7b)
>  Open developer tools,Could you see any errors?
> ![Fedora_xfce-2023-09-17-16-56-52](https://github.com/VSCodium/vscodium/assets/16256910/eefe5fe7-576a-47cc-8f85-d4ce9ace792c)

I'm using .rpm to install since it's more simple and never using tar.gz installation. I'll try reinstall with no any extension installed and soon report the result here

**Comment by chenxiaolong** [comment]
This might be the same as https://github.com/microsoft/vscode/issues/190437 (which is an upstream Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1442633). Does deleting the `GPUCache` directory in vscodium's config directory fix things?

**Comment by asharifauzan** [comment]
@chenxiaolong after clearing GPUCache it works 🙏

`rm -rf .config/VSCodium/GPUCache `
