### ISSUE TITLE
baseUrl not working

### ISSUE THREAD

**Issue by 6Q9zYC6** [VSCodium/vscodium#1643]
### baseUrl not working :: https://download.vscodium.com/rpms/

fix it

![Screenshot from 2023-09-17 13-44-42](https://github.com/VSCodium/vscodium/assets/80390283/08011a4f-3f6c-43c7-92aa-b0d00e4dbf4d)

**Comment by QuickMythril** [comment]
same on debian-based os:
`Failed to fetch tor+https://download.vscodium.com/debs/dists/vscodium/InRelease  Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification.`

**Comment by python-and-fiction** [comment]
CDN of https://download.vscodium.com isn't ready,or hasn't configured.

**Comment by Hekkaryk** [comment]
+1  
https://download.vscodium.com/ returns following in browser:
> Domain suspended or not configured
>
>If you are the administrator and believe this is an error on our side, please check your BunnyCDN account configuration or contact customer support. 

Error on `apt update`:
> W: Failed to fetch https://download.vscodium.com/debs/dists/vscodium/InRelease  Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification.

**Comment by daiyam** [comment]
@PalinuroSec Can you look into it? Thx

**Comment by alkorang** [comment]
On Debian when I run `apt update`:
```
Err:9 https://download.vscodium.com/debs vscodium Release
  Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 169.150.249.168 443]
...
E: The repository 'https://download.vscodium.com/debs vscodium Release' no longer has a Release file.
```

https://download.vscodium.com/debs/ links to error message from BunnyCDN:
```
Domain suspended or not configured
If you are the administrator and believe this is an error on our side, please check your BunnyCDN account configuration or contact customer support. 
```
![image](https://github.com/VSCodium/vscodium/assets/11420879/1798b99d-26c3-419b-ad93-c9befafce9e9)

**Comment by stephanlachnit** [comment]
It's working again

**Comment by liar666** [comment]
Same problem again today...

**Comment by daiyam** [comment]
Ya, follow at https://github.com/VSCodium/vscodium/issues/1910
