### ISSUE TITLE
Graphic artifacts after the last update

### ISSUE THREAD

**Issue by alex27riva** [VSCodium/vscodium#1648]
**Describe the bug**
I'm experiencing graphical artifacts in VSCodium

**To Reproduce**
Just open VSCodium from terminal or GUI

**Screenshots**
![Schermata del 2023-09-18 18-48-08](https://github.com/VSCodium/vscodium/assets/5512235/48765169-d6f6-4d77-89bd-ade37a5cb306)

**Desktop (please complete the following information):**
 - OS: Fedora Workstation 38
 - Architecture: x64
 - Version: codium-1.82.0.23250-el7.x86_64
 - App Manager: RPM
 - Sandboxed: no

**Comment by daiyam** [comment]
Can you try `rm -rf .config/VSCodium/GPUCache`? (from https://github.com/VSCodium/vscodium/issues/1642#issuecomment-1722536016)

**Comment by alex27riva** [comment]
> Can you try `rm -rf .config/VSCodium/GPUCache`? (from [#1642 (comment)](https://github.com/VSCodium/vscodium/issues/1642#issuecomment-1722536016))

Thanks, now it's working.
