### ISSUE TITLE
MacPorts

### ISSUE THREAD

**Issue by fuzunspm** [VSCodium/vscodium#165]
This awesome implementation needs MacPorts Port.

**Comment by stripedpajamas** [comment]
Hi @fuzunspm -- if I understand MacPorts correctly, a port consists of the necessary logic/commands to fetch, extract, patch, configure, build, and output a binary for some open source software. This sounds exactly like what VSCodium currently does -- it fetches `vscode`, patches some default telemetry settings, runs the build tasks outlined by Microsoft, and uploads the binary to GitHub. As such, if there were a MacPorts port, I think it would/should be of `vscode`, not VSCodium. I think any port that tries to replicate what we're doing with VSCodium would end up almost being a copy of our `.travis.yml` file (and have to be maintained separately).

Anyone can give it a shot -- I recommend making a MacPort of `vscode` (although be warned that Microsoft's build process takes 20+ minutes). But making the port is not in the scope of the VSCodium project.
