### ISSUE TITLE
Can't run in wayland

### ISSUE THREAD

**Issue by Master811129** [VSCodium/vscodium#1650]
**Describe the bug**
Can't run in wayland with this flags
`codium --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland `
ms-vscode on the other hand does work normally

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. install as snap
2. try to open as wayland

`codium --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland `

**Expected behavior**
vscode wayland window

**Screenshot**
![image](https://github.com/VSCodium/vscodium/assets/37829730/5fb3b11b-f2f6-418f-952f-81970982ddc5)

**Desktop (please complete the following information):**
 - OS:  Ubuntu 23.04
 - Architecture: x86_64
 - Version: 1.82.2
 - App Manager: Snap
 - Sandboxed: Snap (classic mode)

**Additional context**
Both vscode and vscodium print two warning messages but vscodium refuses to pop up.

**Comment by ls1w** [comment]
A similar issue here with flatpak version, but vscodium on arch repo work great

**Comment by mcendu** [comment]
Cannot reliably reproduce the issue after attempting to run with gdb.

**Comment by rxmmah** [comment]
i have the samr issue  the app quite after 2 seconds

**Comment by negativeExponent** [comment]
similar issue here when vscodium is run in native wayland, it just immediately closes

**Comment by RalfJung** [comment]
Yeah, same problem here -- some recent update completely broke vscodium, it doesn't start any more in my Gnome Wayland session. On the terminal all I am getting is
```
$ flatpak run com.vscodium.codium 
Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.
```
I have previously configured things to force the use of the X11 fallback since the native Wayland mode of Electron still has some severe issues. Possibly that is causing issues now? I have this in my overrides:
```
[Context]
sockets=!fallback-x11
```

Downgrading to this version works but the window icon is missing in the Gnome taskbar:
```
sudo flatpak update --commit 20aad2933e1ae45bc1cfd8292da8e7f1f1b72e2b0070cef81fc12cfd62e07f66 com.vscodium.codium
```

I have to downgrade to `be96c3ecc66eb95ae045f7bd988f93f273d0fbc5e966ba38e166cb61f7aecf76` to fix the window icon. The next version changelog says "Fix ozone-platform-hint auto config (17e2fcc2)", looks like something went wrong there.

**Comment by DrymarchonShaun** [comment]
Been having this issue for a while now, first on Arch, then on NixOS

**Comment by daiyam** [comment]
Have you tried with the setting (VSCodium's `settings.json`) `"window.titleBarStyle": "custom"`? (from https://github.com/microsoft/vscode/issues/184124)

**Comment by DrymarchonShaun** [comment]
> Have you tried with the setting (VSCodium's `settings.json`) `"window.titleBarStyle": "custom"`? (from https://github.com/microsoft/vscode/issues/184124)

Yeah, I'm not sure if it helped. The issue is inconsistent regardless, so it's hard to tell if it did anything.

**Comment by Master811129** [comment]
@daiyam  Yes I tried it in both `native` and `custom`. It didn't change anything. same issue

**Comment by MidGe48** [comment]
Same issue here. Suddenly vscodium not working any longer. 

Tried re-installing after a purge with apt, tried previous version, all to no avail.

Running debian KDE under wayland on x64.

Any way around this?  Or do I need install another IDE?

**Comment by ls1w** [comment]
> Same issue here. Suddenly vscodium not working any longer.
> 
> Tried re-installing after a purge with apt, tried previous version, all to no avail.
> 
> Running debian KDE under wayland on x64.
> 
> Any way around this? Or do I need install another IDE?
> 
> I found the answer: running from the console with the follwing as suggested by Master811129] above works for me. "codium --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland"
> 
> I also changed the menu accordingly and that works as well!
> 
> Thanks @Master811129

You can run as xwayland instead wayland, this work for me at list, you can run on x11 session too

**Comment by DrymarchonShaun** [comment]
> You can run as xwayland instead wayland
So far this is the only thing that has solved this for me.

**Comment by loulou310** [comment]
Using custom title bar style solved the problem for me. I also use the `--enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland` start options.

**Comment by madhums** [comment]
Any update on this? Is there one setting somewhere to make this work regardless of whether you open the app from terminal or GUI? Anyone willing to share a solution and perhaps update the documentation?

**Comment by dR3b** [comment]
Arch linux and Sway, Xwayland is working but with:
```
--enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland
```
The Codium window closes immediately and the process is ended.

**Comment by TenEXP** [comment]
> Arch linux and Sway, Xwayland is working but with:
> 
> ```
> --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland
> ```
> 
> The Codium window closes immediately and the process is ended.

For me, it doesn't close immediately, but as soon as I move a mouse cursor over any part of its window.

**Comment by oyvindln** [comment]
Not sure if it's helpful but running with ```codium --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland``` under gnome wayland, ubuntu 23.10 with vscodium installed as a deb seems to start fine for me - though it still causes Xwayland to start if it's not already running and while it does not show up if running ```xlsclients``` when launched with these options killing the Xwayland server instantly kills codium as well so it seems to depend on X in some manner still.

**Comment by omnigenous** [comment]
@loulou310 Thank you, it worked for me! However I had a little issue, could you explain for dummies how to make those flags persist? It's not ideal to type them every time I want to lunch vscodium.

**Comment by loulou310** [comment]
> @loulou310 Thank you, it worked for me! However I had a little issue, could you explain for dummies how to make those flags persist? It's not ideal to type them every time I want to lunch vscodium.

You can edit the .desktop file. They are located in `/usr/share/applications`. Then in the file, in front of Exec, you can see the command that is executed to launch the app. You can add the flags before the %F. Also, lower in the file there's another Exec that is for new windows, I believe you need to change it here too.

**Comment by regulator-g** [comment]
upstream VSCode doesn't have this issue so what is it doing differently?

**Comment by Hellscaped** [comment]
I actually had this issue earlier and fixed it, but another one arose: the window was tiny inside my window, when i moved my mouse to the bottom left of the full window it showed that it was registering mouse events at the real pos but rendering as a tiny window

**Comment by JFincher42** [comment]
Same issue here on EndeavourOS (Arch)

VSCodium installed from AUR, no combination of CLI options works to force Wayland

Version: 1.85.2
Release: 24019
Commit: c8a36a69377856369f139f39ee56dd3838130fbf
Date: 2024-02-03T22:34:16.729Z
Electron: 25.9.7
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.7.4-arch1-1

**Comment by negativeExponent** [comment]
its appears that wayland mode is indeed working. built from Arch-AUR
