### ISSUE TITLE
RPM: Downloading successful, but checksum doesn't match

### ISSUE THREAD

**Issue by ngxson** [VSCodium/vscodium#1652]
**Describe the bug**
Cannot upgrade vscodium on Fedora Silverblue due to `Downloading successful, but checksum doesn't match`

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
On Fedora Silverblue, do:

```
rpm-ostree upgrade
```

Result:

```
...
Resolving dependencies... done
Will download: 1 package (124,4 MB)
Downloading from 'gitlab.com_paulcarroty_vscodium_repo'... done
error: Cannot download vscodium-1.82.2.23257-x86_64.rpm: All mirrors were tried; Last error: Downloading successful, but checksum doesn't match. Calculated: dd3593cc0275f0bfe072bbddfd4cfa3f1a239e9fe0c1c247cd6e4da7d8f1bb76(sha256)  Expected: 84002c511de94d0e9a7c1e1ca3fe19c7ab56ed47963b5eadc2281d2d7a6875ea(sha256)
```

**Expected behavior**
Vscodium download & installed via rpm-ostree install

**Screenshots**
(N/A)

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue 38
 - Architecture: x64
 - Version: 1.82.2
 - App Manager: RPM-OSTree
 - Sandboxed: no

**Comment by daiyam** [comment]
@ngxson Not sure what's going on there since the [primary.xml](https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/repodata/9cc553888b27f014165a6b3d6d95e17b39e7b722349a6e9d52539f9963bf0d69-primary.xml.gz) expect the `x86_64` package to have a checksum equals to `dd3593cc0275f0bfe072bbddfd4cfa3f1a239e9fe0c1c247cd6e4da7d8f1bb76`. I don't know where your `84002c511de94d0e9a7c1e1ca3fe19c7ab56ed47963b5eadc2281d2d7a6875ea` is coming from...

@paulcarroty Can you take a look at your repo?

```
# from GitHub
❯ shasum -a 256 codium-1.82.2.23257-el7.x86_64.rpm
ae312acacc923822f3f072f63f5c672ea4d2f659071c0a2430ea495e7022840f  codium-1.82.2.23257-el7.x86_64.rpm

# from the your repo
❯ shasum -a 256 vscodium-1.82.2.23257-x86_64.rpm
dd3593cc0275f0bfe072bbddfd4cfa3f1a239e9fe0c1c247cd6e4da7d8f1bb76  vscodium-1.82.2.23257-x86_64.rpm
```

Why the checksums are different?
Could you are add a checksum verification on your download since `codium-1.82.2.23257-el7.x86_64.rpm.sha256` is available?

**Comment by matiros96** [comment]
I get a similar error on OpenSUSE

```
Warning: Digest verification failed for file 'vscodium-1.82.2.23257-x86_64.rpm'
[/var/tmp/AP_0xcdtLtU/vscodium-1.82.2.23257-x86_64.rpm]

  expected dd3593cc0275f0bfe072bbddfd4cfa3f1a239e9fe0c1c247cd6e4da7d8f1bb76
  but got  bc74a982c9ff119e3d01cdcc01bcbf2041eefc2804e1c759fce13bbc91818d21
```

**Comment by paulcarroty** [comment]
@daiyam 'cause my repo & all packages are GPG signed.
Tested on Fedora 38, no issues.

**Comment by daiyam** [comment]
@paulcarroty Yep, I didn't see the `rpm --addsign` at L107. Sorry

@matiros96 The expected checksum is correct. Maybe an issue in your download.

**Comment by paulcarroty** [comment]
Closing for now, please reopen if this issue will appear.

**Comment by pereslava** [comment]
Now on _openSUSE Leap 15.5 x86_64_:

```
Warning: Digest verification failed for file 'vscodium-1.84.0.23306-x86_64.rpm'
[/var/tmp/AP_0xt2Sz6x/vscodium-1.84.0.23306-x86_64.rpm]

  expected 186cedf1b93d8475d1cda632593811a93ce7a79738f04f02c7b02e8d2dd6305c
  but got  8baebbf51bd98c54f1c4d777ebaa4a014c6d8c537d28465b1c4bc50b21f62814

```
