### ISSUE TITLE
debugging gives "undefined" is not valid JSON

### ISSUE THREAD

**Issue by trangius** [VSCodium/vscodium#1655]
**Describe the bug**
When I try to debug code on my macOS system i get an error; "undefined" is not valid JSON. The error apperas in a small box in the bottom right corner.

I am trying to debug C#/.NET code and have not tried other languages. There is nothing wrong with the projects I am trying to compile, and I've created new projects from scratch. The debugger simply wont start in neither of my old or new projects. I can't seem to figure out what JSON file is referred here (I haven't created anyone, only updated  launch.json to  `"console": "integratedTerminal"`.

I've tried Visual Studio Code and the debugger works fine there.
I've uninstalled VSCodium and installed it again.
I've remoed all of the VSCodium files in home/Library/Application\ Support

**Please confirm that this problem is VSCodium-specific**
- [ x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. start a new project with executable code
2. choose Run->Debug

**Expected behavior**
The debugger to start

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.5.2
 - Architecture x64 - intel chip
 - Version  1.82
 - App Manager homebrew
 - Sandboxed no

**Comment by legendaryredfox** [comment]
- Same thing happens in Windows 11
- Architecture x64 - intel chip
- Sandboxed no
- App Manager none

**Comment by Pete-404** [comment]
Same thing on Linux.

**Comment by Dreamoochy** [comment]
I've faced the [similar issue](https://github.com/muhammadsammy/free-omnisharp-vscode/issues/60) with free-omnisharp-vscode v2.0. So it might be extension-related issue.

**Comment by D3ENNY** [comment]
same issue on arch linux. 

code OSS

**Comment by Kolka2** [comment]
Same issue on Debian 12.

**About**

> Version: 1.83.1
> Release: 23285
> Commit: 36d13de33ac0d6c684f10f99cff352e2f58228b3
> Date: 2023-10-12T18:26:29.496Z
> Electron: 25.8.4
> ElectronBuildId: undefined
> Chromium: 114.0.5735.289
> Node.js: 18.15.0
> V8: 11.4.183.29-electron.0
> OS: Linux x64 6.1.0-13-amd64

**Installed extensions**: 

> Name: .NET Runtime Install Tool
> Id: ms-dotnettools.vscode-dotnet-runtime
> Description: This extension installs and manages different versions of the .NET Runtime.
> Version: 1.8.1
> Publisher: ms-dotnettools
> VS Marketplace Link: https://open-vsx.org/vscode/item?itemName=ms-dotnettools.vscode-dotnet-runtime

> Name: C#
> Id: muhammad-sammy.csharp
> Description: C# support for vscode-compatible editors (powered by OmniSharp and NetCoreDbg).
> Version: 2.0.436
> Publisher: muhammad-sammy
> VS Marketplace Link: https://open-vsx.org/vscode/item?itemName=muhammad-sammy.csharp

> Name: C# Extensions
> Id: jsw.csharpextensions
> Description: C# IDE Extensions for VSCode
> Version: 1.7.3
> Publisher: jsw
> VS Marketplace Link: https://open-vsx.org/vscode/item?itemName=jsw.csharpextensions

> Name: Python
> Id: ms-python.python
> Description: IntelliSense (Pylance), Linting, Debugging (multi-threaded, remote), code formatting, refactoring, unit tests, and more.
> Version: 2023.18.0
> Publisher: ms-python
> VS Marketplace Link: https://open-vsx.org/vscode/item?itemName=ms-python.python

**Comment by yelvert** [comment]
A workaround for this seems to be adding `"csharp.debug": {},` to your settings
