### ISSUE TITLE
Boxes instead of correct font when trying to delete file

### ISSUE THREAD

**Issue by popovidis** [VSCodium/vscodium#1663]
**Describe the bug**
When trying to delete a file from the explorer the text is just boxes

**Please confirm that this problem is VSCodium-specific**
- [ x ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ x ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Try to delete a file from the explorer.

**Expected behavior**
You should be able to read what the message is when trying to delete a file. This does not happen on Flatpak but it does happen on Snap.

**Screenshots**
[VSCodium Snap](https://i.imgur.com/Oy48A1S.png)
[VSCodium Flatpak](https://i.imgur.com/3AdBZb1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - Architecture x64
 - Version 1.18.0
 - App Manager Snap
 - Sandboxed Snap

**Additional context**
Snap version of VSC works
Flatpak version of VSCodium works
Snap version of VSCodium has the issue

Running Gnome x11

**Comment by daiyam** [comment]
Please look at https://github.com/VSCodium/vscodium/wiki/Troubleshooting#fonts-showing-up-as-rectangles

**Comment by popovidis** [comment]
> Please look at https://github.com/VSCodium/vscodium/wiki/Troubleshooting#fonts-showing-up-as-rectangles

thanks 🙏🏻
