### ISSUE TITLE
Can't edit settings.json

### ISSUE THREAD

**Issue by lsmoura** [VSCodium/vscodium#167]
**Describe the bug**
When on settings page, some settings expose a button that reads "Edit in settings.json". This button is not working on VSCodium

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to Settings (Command + ',')
2. Type "Launch" (also work with other options. this is just an example)
3. Click on "Edit in settings.json"
4. Nothing happens

**Expected behavior**
The user's `settings.json` file should appear for editing.

**Screenshots**
<img width="1091" alt="Screen Shot 2019-05-21 at 4 17 22 PM" src="https://user-images.githubusercontent.com/453756/58127840-51676000-7be4-11e9-925d-49a7f6582d30.png">

**Desktop (please complete the following information):**
 - Mac OS
 - 1.33.1

**Additional context**
I realize that the docs have the proper file path for the settings and I still can open it manually and edit it properly, but the button on the settings page should work.

**Comment by stripedpajamas** [comment]
Hmmm... I'm not able to reproduce this behavior. When I click "Edit in settings.json" it properly opens the file for editing. I also tried deleting my current settings.json file and it properly created a fresh one when I clicked the edit link. 

Does the `{}` button work when on the Settings page?
![image](https://user-images.githubusercontent.com/2707340/58129468-a8fad100-7bce-11e9-939f-c8a6637ae207.png)

Would you mind updating to the latest version (1.34.0) to confirm it isn't something wrong with 1.33.1?

**Comment by lsmoura** [comment]
Hey, @stripedpajamas !

When clicking on the `{}`, I get an error notification:

<img width="463" alt="Screen Shot 2019-05-21 at 4 48 12 PM" src="https://user-images.githubusercontent.com/453756/58129684-4a425100-7be8-11e9-9a6c-425e4514c8fe.png">

**Comment by lsmoura** [comment]
It works on 1.34.0.

**Comment by lsmoura** [comment]
Thanks for looking into it, @stripedpajamas
