### ISSUE TITLE
Semantic highlighting (coloring) not work

### ISSUE THREAD

**Issue by milen-prg** [VSCodium/vscodium#1671]
**Describe the bug**
Semantic highlighting (coloring) not work. Different themes and additional Extensions like "Color Identifiers" did not help.
All variables has one color.

**Please confirm that this problem is VSCodium-specific**
- [ YES] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [YES ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
The problem is checked in C and Python files.

**Expected behavior**
The variables must have different colors.

**Screenshots**
This is in VSCodium:
![image](https://github.com/VSCodium/vscodium/assets/59639866/a5aa9bc6-cf24-445d-b19f-fc6b7f90b4be)

Must be (VSCode):
![image](https://github.com/VSCodium/vscodium/assets/59639866/11a050ed-3f1b-480d-b61e-9f3c206d4990)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Architecture [x64]
 - Version [1.82.2]
 - App Manager [Chocolatey]
 - Sandboxed [no]

**Additional context**
Many Extensions, which  exists for VSCode, did not appears in VSCodium installation list. But this is another problem.

**Comment by dev-1415** [comment]
YES!!! This bug has been driving me insane!! I thought there was something wrong with the extensions that I have installed

**Comment by daiyam** [comment]
https://github.com/VSCodium/vscodium/issues/1674

**Comment by dev-1415** [comment]
> #1674

confirmed: workaround does not work. Jedi infact, crashes

**Comment by GitMensch** [comment]
This is an issue with the extensions that partially are explicit not usable with non Microsoft binaries.
See https://github.com/VSCodium/vscodium/blob/master/docs/index.md#extensions-marketplace to get some more information.

Note: for C files I can definitely recommend the clangd extension. If you don't use clang for compile the [Bear](https://github.com/rizsotto/Bear) is one of the options to generate the necessary compile_commands.json.

Closed as not planned / upstream / extension issue.
