### ISSUE TITLE
VSCodium needs access to microphone? (macOS)

### ISSUE THREAD

**Issue by JustAGabriel** [VSCodium/vscodium#1673]
**Describe the bug**
Not sure it's one, but strange behaviour for sure:
updated VSCodium today an was prompted to grant access to my microphone.

**Please confirm that this problem is VSCodium-specific**
- [ x ] I have VSCode installed on another maschine too (yes, also macOS) - updated it and wasn't prompted to allow microphone access

**Please confirm that the issue/resolution isn't already documented**
- [ x ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. install latest VSCodium version via _brew_

**Expected behavior**
no access to microphone requested

**Screenshots**
i didn't caught a screenshot for the actual system prompt, but here are the applications that requested mic access (mac os system permissions view)
![image](https://github.com/VSCodium/vscodium/assets/45315755/fa4c5af6-2f86-4279-9e4f-9997ba3ed639)

**Desktop (please complete the following information):**
 - OS:  Mac OS (Sonoma 14.0)
 - Architecture  arm64 (M1)
 - Version: 1.83.0 (Release: 23277, Commit: 57dae766d7d9084be351c47b43b26bf64acc9312)
 - App Manager: Homebrew
 - Sandboxed: no

**Additional context**
the full _About VSCodium_ specs dump:
```
Version: 1.83.0
Release: 23277
Commit: 57dae766d7d9084be351c47b43b26bf64acc9312
Date: 2023-10-04T19:03:27.708Z
Electron: 25.8.4
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0
```

**Comment by JustAGabriel** [comment]
thanks for all your work, lad's and gent's!

**Comment by daiyam** [comment]
Do you have any extensions? Have you tested without it?

**Comment by JustAGabriel** [comment]
uh, good catch!

after re-installing `vscodium` without any plugins no such prompt came up!
stupid of me not thinking about this in advance...sorry for wasting your time @daiyam and thank you for your quick response!!!

**Comment by daiyam** [comment]
You're welcome.

Do you know which extension is asking for the microphone? Is it normal?

**Comment by JustAGabriel** [comment]
no, can't really tell which one it was. had a bunch installed and simply installed `vscodium` again without any.
strange thing is that i saw that `Andoid Studio` was also listed as a program that wants access the the microphone...
could be coincidence or actually related to some legit IDE requirements (e.g. in JB IDE's there is [code with me](https://www.jetbrains.com/code-with-me/), even though i am not aware of any such functionality in `vscode` currently nor was any of my plugins obviously providing such)...

can not really tell.

guess time will show if other people also stumble upon this.

thanks again!

br
gabriel
