### ISSUE TITLE
VSCodium PyLint not work properly

### ISSUE THREAD

**Issue by milen-prg** [VSCodium/vscodium#1674]
**Describe the bug**
PyLint gives errors that are not real.

**Please confirm that this problem is VSCodium-specific**
- [YES ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ YES] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**

1. Install Python and Pylint extensions
2. Input this example in .py file:

```
import requests as rq

print(rq.codes.ok)

```

**Expected behavior**
There must not be any error (as in VSCode).

**Screenshots**
![image](https://github.com/VSCodium/vscodium/assets/59639866/54c2668c-c064-45a1-ba4c-a5094017d1f0)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Architecture [x64]
 - Version [1.82.2]
 - App Manager [Chocolatey]
 - Sandboxed [no]

**Additional context**

**Comment by python-and-fiction** [comment]
> **Describe the bug** PyLint gives errors that are not real.
> 
> **Please confirm that this problem is VSCodium-specific**
> 
> * [YES ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
> 
> **Please confirm that the issue/resolution isn't already documented**
> 
> * [ YES] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Install Python and Pylint extensions
> 2. Input this example in .py file:
> 
> ```
> import requests as rq
> 
> print(rq.codes.ok)
> ```
> 
> **Expected behavior** There must not be any error (as in VSCode).
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/59639866/273136173-54c2668c-c064-45a1-ba4c-a5094017d1f0.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: [Windows 10 Pro]
> * Architecture [x64]
> * Version [1.82.2]
> * App Manager [Chocolatey]
> * Sandboxed [no]
> 
> **Additional context**

which version of python do you use？

**Comment by milen-prg** [comment]
Python 3.11.6 64bit
pylint                            3.0.1

But, I apologize, in VSCode is not error, because there the Pylint was disabled entirely. If I enable PyLint in VSCode - the error is far more complex:

Traceback (most recent call last):
  File "c:\Users\mlap\.vscode\extensions\ms-python.pylint-2023.8.0\bundled\tool\lsp_server.py", line 725, in _run_tool_on_document
    result = utils.run_module(
             ^^^^^^^^^^^^^^^^^
  File "c:\Users\mlap\.vscode\extensions\ms-python.pylint-2023.8.0\bundled\tool\lsp_utils.py", line 200, in run_module
    return _run_module(module, argv, use_stdin, source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\mlap\.vscode\extensions\ms-python.pylint-2023.8.0\bundled\tool\lsp_utils.py", line 185, in _run_module
    runpy.run_module(module, run_name="__main__")
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Lib\site-packages\pylint\__main__.py", line 10, in <module>
    pylint.run_pylint()
  File "C:\Python311\Lib\site-packages\pylint\__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "C:\Python311\Lib\site-packages\pylint\lint\run.py", line 136, in __init__
    args = _preprocess_options(self, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pylint\config\utils.py", line 256, in _preprocess_options
    cb(run, value)
  File "C:\Python311\Lib\site-packages\pylint\config\utils.py", line 152, in _init_hook
    exec(value)  # pylint: disable=exec-used
    ^^^^^^^^^^^
  File "<string>", line 1
    import sys; sys.path.extend([""c:\\Users\\mlap\\.vscode\\extensions\\ms-python.devicesimulatorexpress-2020.0.36321\\out"",""c:\\Users\\mlap\\.vscode\\extensions\\ms-python.devicesimulatorexpress-2020.0.36321\\out\\micropython"",""c:\\Users\\mlap\\.vscode\\extensions\\ms-python.devicesimulatorexpress-2020.0.36321\\out\\clue"",""c:\\Users\\mlap\\.vscode\\extensions\\ms-python.devicesimulatorexpress-2020.0.36321\\out\\base_circuitpython""])
                                 ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?

This is in VSCode, seems that the Pylint extension not work in general and this is not VSCodium problem.

**Comment by milen-prg** [comment]
Now I experiment and when in VSCode I set
"python.languageServer": "Jedi"

The Pylint works exactly as in VSCodium. So the problems was for Pylint extension, not VSCodium. I'm closing this. Thanks.

**Comment by milen-prg** [comment]
Now I experiment and when in VSCode I set
"python.languageServer": "Jedi"

The Pylint works exactly as in VSCodium. So the problems was for Pylint extension, not VSCodium. I'm closing this. Thanks.
