### ISSUE TITLE
Reproducible build instructions

### ISSUE THREAD

**Issue by JayAndCatchFire** [VSCodium/vscodium#168]
As mentioned in the comments from #14, this repository is mostly just build scripts to build vscodium from the vscode repository.  However, that issue's comment goes on to recommend reading the official vscode build instructions.

I'd like to know the build steps that are taken that result in the builds that are posted in the project's [releases page](https://github.com/VSCodium/vscodium/releases).

Ideally, we should be able to create packages at home that are bit-identical to the ones posted here.

**Comment by stripedpajamas** [comment]
Is something more than reading the .travis.yml required?

**Comment by JayAndCatchFire** [comment]
I wouldn't even have thought of looking at that file.  Perhaps this should be added to the docs.

**Comment by stripedpajamas** [comment]
That makes sense -- I've opened a PR to add some more info around the build process #170
