### ISSUE TITLE
CUPS dependency that is not present in VSCode

### ISSUE THREAD

**Issue by Frostbyte4664** [VSCodium/vscodium#1680]
**Describe the bug**
VSCode does not require CUPS to run, but VSCodium does.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. ~~Build VSCodium~~ Apparently the ebuild just unpacks a release...?
2. Attempt to run VSCodium without CUPS installed
3. `/opt/vscodium/bin/../codium: error while loading shared libraries: libcups.so.2: cannot open shared object file: No such file or directory`

**Expected behavior**
VSCodium running with the same dependencies as VSCode.

**Desktop (please complete the following information):**
 - OS: Gentoo
 - Architecture: amd64
 - Version: [1.83.0.23277](https://github.com/VSCodium/vscodium/releases/tag/1.83.0.23277)
 - App Manager: Portage
 - Sandboxed: No

**Comment by arthurzam** [comment]
This is still relevant, and just closing it won't fix the issue.

Stale bots never help fix issues, they just increase the rug. https://nostalebots.xyz/

**Comment by daiyam** [comment]
stale != closed

**Comment by daiyam** [comment]
The issue is most likely due to gentoo packaging. Feel free to make any PR if needed 😉

**Comment by daiyam** [comment]
> This is still relevant, and just closing it won't fix the issue.
> 
> Stale bots never help fix issues, they just increase the rug. https://nostalebots.xyz/

I most agree to the argument and I hate those that close and lock an issue after a month of inactivity.

So I've implemented loose rules:
- stale after 180 days (6 months) of inactivity
- then closed after 30 days of inactivity
- then locked after 90 days of inactivity

I found myself re-evaluating an issue after the stale notification.

**Comment by daiyam** [comment]
@arthurzam Have you opened an issue on Gentoo/Portage? It might be an issue due to the repackaging?
