### ISSUE TITLE
Very slow to open each file  VSCodium: 1.83.0   takes 6+ seconds to just open up

### ISSUE THREAD

**Issue by kantheerava** [VSCodium/vscodium#1681]
I started using VSCodium since yesterday Oct 7, 2023.

It is too slow, takes 6+ seconds to just open up.

I have disabled all extensions

I used snap version to install on Ubuntu 20.04 i.e.,  (sudo snap install codium)

Machine has adequate resources (8 GB RAM & i5) & not any background services to hog -- confirmed using top

Can this be investigated?

Using "Startup Performance" in command palette

* VSCodium: 1.83.0 (57dae766d7d9084be351c47b43b26bf64acc9312)
* OS: linux(5.15.0-84-generic)

* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: true

VSCodium Info... 

Version: 1.83.0
Release: 23277
Commit: 57dae766d7d9084be351c47b43b26bf64acc9312
Date: 2023-10-04T19:32:23.556Z
Electron: 25.8.4
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-84-generic snap

## Performance Marks

| What                                                            | Duration | Process                   | Info                                                        |
| --------------------------------------------------------------- | -------- | ------------------------- | ----------------------------------------------------------- |
| start => app.isReady                                            | 102      | [main]                    | initial startup: true                                       |
| nls:start => nls:end                                            | 5        | [main]                    | initial startup: true                                       |
| require(main.bundle.js)                                         | 72       | [main]                    | initial startup: true                                       |
| start crash reporter                                            | 0        | [main]                    | initial startup: true                                       |
| serve main IPC handle                                           | 1        | [main]                    | initial startup: true                                       |
| create window                                                   | 70       | [main]                    | initial startup: true, state: 0ms, widget: 51ms, show: 18ms |
| app.isReady => window.loadUrl()                                 | 173      | [main]                    | initial startup: true                                       |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 4798     | [main->renderer]          | NewWindow                                                   |
| require(workbench.desktop.main.js)                              | 723      | [renderer]                | cached data: YES, node_modules took 0ms                     |
| wait for window config                                          | 2        | [renderer]                | -                                                           |
| init storage (global & workspace)                               | 24       | [renderer]                | -                                                           |
| init workspace service                                          | 28       | [renderer]                | -                                                           |
| register extensions & spawn extension host                      | 260      | [renderer]                | -                                                           |
| restore viewlet                                                 | 0        | [renderer]                | -                                                           |
| restore panel                                                   | 0        | [renderer]                | -                                                           |
| restore & resolve visible editors                               | 159      | [renderer]                | 1: workbench.editors.files.fileEditorInput                  |
| overall workbench load                                          | 318      | [renderer]                | -                                                           |
| workbench ready                                                 | 6155     | [main->renderer]          | -                                                           |
| renderer ready                                                  | 1086     | [renderer]                | -                                                           |
| shared process connection ready                                 | 280      | [renderer->sharedprocess] | -                                                           |
| extensions registered                                           | 6356     | [renderer]                | -                                                           |

**Comment by Crystal-RainSlide** [comment]
No good, all those three are too slow:
- window.loadUrl() => begin to require(workbench.desktop.main.js)
- workbench ready
- extensions registered

Can you try a non-snap version?

**Comment by kantheerava** [comment]
Thanks @Crystal-RainSlide for the patient listening.

https://github.com/VSCodium/vscodium/releases/download/1.83.0.23283/codium_1.83.0.23283_amd64.deb

I will try with this and report back the stats.

**Comment by kantheerava** [comment]
Thank you, 
I'm done now..
the Debian package version is relatively better.

Though, Codium still lags compared to Sublime Text....  DPKG version is much much better.

I moved to Codium, to debug perl scripts in Codium and I'll get working on it.. Thank you @Crystal-RainSlide 

## Performance Marks

| What                                                            | Duration | Process                   | Info                                                        |
| --------------------------------------------------------------- | -------- | ------------------------- | ----------------------------------------------------------- |
| start => app.isReady                                            | 95       | [main]                    | initial startup: true                                       |
| nls:start => nls:end                                            | 4        | [main]                    | initial startup: true                                       |
| require(main.bundle.js)                                         | 120      | [main]                    | initial startup: true                                       |
| start crash reporter                                            | 0        | [main]                    | initial startup: true                                       |
| serve main IPC handle                                           | 1        | [main]                    | initial startup: true                                       |
| create window                                                   | 81       | [main]                    | initial startup: true, state: 0ms, widget: 53ms, show: 26ms |
| app.isReady => window.loadUrl()                                 | 246      | [main]                    | initial startup: true                                       |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 3879     | [main->renderer]          | NewWindow                                                   |
| require(workbench.desktop.main.js)                              | 864      | [renderer]                | cached data: NO, node_modules took 0ms                      |
| wait for window config                                          | 1        | [renderer]                | -                                                           |
| init storage (global & workspace)                               | 48       | [renderer]                | -                                                           |
| init workspace service                                          | 27       | [renderer]                | -                                                           |
| register extensions & spawn extension host                      | 580      | [renderer]                | -                                                           |
| restore viewlet                                                 | 0        | [renderer]                | -                                                           |
| restore panel                                                   | 0        | [renderer]                | -                                                           |
| restore & resolve visible editors                               | 5        | [renderer]                | 0:                                                          |
| overall workbench load                                          | 194      | [renderer]                | -                                                           |
| workbench ready                                                 | 5338     | [main->renderer]          | -                                                           |
| renderer ready                                                  | 1121     | [renderer]                | -                                                           |
| shared process connection ready                                 | 530      | [renderer->sharedprocess] | -                                                           |
| extensions registered                                           | 6007     | [renderer]                | -                                                           |

**Comment by BrettFraley** [comment]
I'm glad I found this @kantheerava because I thought I was going crazy that my machine was bogged down and realized it is vscodium! I am running ubuntu and the snap package too.
