### ISSUE TITLE
virustotal warning for VSCodium-linux-x64-1.83.0.23277.tar.gz

### ISSUE THREAD

**Issue by uli-heller** [VSCodium/vscodium#1682]
**Describe the bug**
Due to the AppImage version currently missing, I decided to give a try to the tar.gz packaged version of vscodium.
I downloaded the file and checked it via https://virustotal.com. Unfortunately, a virus got detected.

**Screenshots**

![image](https://github.com/VSCodium/vscodium/assets/1677414/d1be9895-fbe6-4130-ac21-6525cd728335)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Architecture [e.g. x64, ia32, arm64] x64
 - Version [e.g. 1.33.0] 1.83.0
 - App Manager [e.g. Winget, Homebrew, Snap, AUR, RPM, Nix, ...] None
 - Sandboxed [e.g. no, Flatpak, Snap] No

**Comment by uli-heller** [comment]
I do get the same virustotal warning for other downloads, for example firefox-118.0.2.tar.bz2.
I double checked the older firefox version 118.0.1. It shows OK within virustotal at first. Clicking on "Reanalyze"
leads to the same virus total warning. So: One check on virustotal seems to have changed and became much
more sensitive. It may be a false positive...

**Comment by daiyam** [comment]
> It may be a false positive...

It is a false positive. 1 on 59! Specially when the vendor is a ML.
