### ISSUE TITLE
VSCodium making connection to Microsoft servers. 

### ISSUE THREAD

**Issue by M-Smits** [VSCodium/vscodium#1684]
**Describe the bug**
Documentation:

> VSCodium's build script [sets the updateUrl field](https://github.com/VSCodium/vscodium/blob/master/prepare_vscode.sh#L36) in product.json to that of VSCodium's own small [update server](https://github.com/VSCodium/update-api), so enabling that setting won't actually result in any calls to Microsoft servers.

> As noted above, the [Open VSX Registry](https://open-vsx.org/) is the pre-set extension gallery in VSCodium. Using the extension view in VSCodium will therefore by **default** use it.

Yet when using extensions:marketplace in VSCodium a TCP connection is made to 20.60.40.4:443.
Checking with WHOIS

```
NetRange:      20.33.0.0 - 20.128.255.255
CIDR:          20.48.0.0/12, 20.33.0.0/16, 20.34.0.0/15, 20.128.0.0/16, 20.40.0.0/13, 20.64.0.0/10, 20.36.0.0/14
OrgName:       Microsoft Corporation
```

- I used '@tag:usesOnlineServices' in the settings to disabled everything I possibly could. But behavior persists.
- I made sure I don't have any extensions making a connection to Microsoft.

**Please confirm that this problem is VSCodium-specific**
- [x] Yes, this is specific to VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x]  As you can see in the bug description, I have done my best to read the documentation and understand it.

**To Reproduce**
1. Open VScodium and extension:manager
2.  use Get-NetTCPConnection, look-up PID in loop and put a sleep around it in script.

**Expected behavior**
No connection is made to Microsoft servers. Or documentation clears this up to avoid confusion.

**Screenshots**

![image](https://github.com/VSCodium/vscodium/assets/9571065/cb136788-1614-4b63-b6e9-39c2b2a48c9b)
![image](https://github.com/VSCodium/vscodium/assets/9571065/a7926762-70ca-4ee9-82ad-0636805a79de)

Version: 1.82.2
Release: 23257
Commit: a5004432af6600c99fa4f918a3f2f8d44df71e6

**Comment by daiyam** [comment]
it can be for the update check (Vercel then GitHub) or extensions check (OpenVSX run on Azure).

**Comment by M-Smits** [comment]
> it can be for the update check (Vercel then GitHub) or extensions check (OpenVSX run on Azure).

Even with these settings?

![image](https://github.com/VSCodium/vscodium/assets/9571065/972974ac-50f9-4cbc-a9b0-a8a4720acd9c)
![image](https://github.com/VSCodium/vscodium/assets/9571065/e3c8cb8a-c05b-4e68-84bc-a8a0a2fd2e25)

So that leaves that OpenVSX runs on Azure. Must be it. I just double checked with Wireshark and I see same behavior.
