### ISSUE TITLE
No more windows binaries on latest releases

### ISSUE THREAD

**Issue by BazirClem** [VSCodium/vscodium#1685]
On the 2 latest relases ( https://github.com/VSCodium/vscodium/releases/tag/1.83.0.23277 and https://github.com/VSCodium/vscodium/releases/tag/1.82.3.23277 ), there aren't any windows binaries. It seem to be caused by the Github Action jobs that fails.

I wanted to report this in case nobody saw it and to know if it was normal to have releases with Github Action failed jobs

**Comment by daiyam** [comment]
duplicate #1669
