### ISSUE TITLE
Missing sha256 files for AppImage releases

### ISSUE THREAD

**Issue by cwfoo** [VSCodium/vscodium#169]
On the [releases](https://github.com/VSCodium/vscodium/releases) page, sha256 files for AppImage files are missing. For example, `VSCodium-1.34.0-1558029460.glibc2.17-x86_64.AppImage` doesn't have a corresponding `*.sha256` file.

**Comment by stripedpajamas** [comment]
Good catch! Thanks @cwfoo 🙏 It looks like the AppImage file needs to be referenced in [the sum script](https://github.com/VSCodium/vscodium/blob/master/sum.sh)
