### ISSUE TITLE
VSCodium start with blank screen after update to macOS Sonoma (Intel Mac)

### ISSUE THREAD

**Issue by freebrowser1** [VSCodium/vscodium#1692]
**Describe the bug**

**Please confirm that this problem is VSCodium-specific**
- [ ] In Visual Studio (same version) this issue occurs as well.

**Please confirm that the issue/resolution isn't already documented**
No, it is not documented.
<img width="1047" alt="Screenshot 2023-10-11 at 08 31 31" src="https://github.com/VSCodium/vscodium/assets/26625141/ecebf980-a27e-4d93-a946-306b3b4f12a1">

- [ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Use macOS 14.0 Sonoma on an Intel Mac
2. Start VSCodium
3. A blank screen will be shown

**Expected behavior**
Normal behavior.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:macOS 14.0 Sonoma on Intel Macbook Pro 2018
 - Architecture  x64
 - Version  1.83.0.23283
 - App Manager : Downloaded from Github (the x64 variant)

**Additional context**
I completely uninstalled VSCodium and removed all my preferences. Then I reinstalled it cleanly. But the issue persisted.
On my other Macbook Pro (a 2021 M1 version) no issue at all happened, it kept working normally after the upgrade.

**Comment by freebrowser1** [comment]
I tried the update : VSCodium.x64.1.83.1.23285.dmg which has the same issue.

**Comment by nullptrdevs** [comment]
Hi,

Just ran into a **similar** issue on a linux machine after a system update, although the view wasn't completely blank - the outline of the 'Welcome` tab was visible.

Try `codium --disable-gpu` and  if that resolve the issue delete/rename `~/.config/VSCodium/GPUCache` (it will be regenerated).

Otherwise look for errors: `codium --verbose`, in my case:
```
Errors:
link failed but did not provide an info log
[6646:1014/173624.467881:WARNING:angle_platform_impl.cc(48)] ProgramGL.cpp:989 (checkLinkStatus): Program link or binary loading failed with no info log.
[6646:1014/173624.467976:ERROR:shared_context_state.cc(81)] Skia shader compilation error
```

**Comment by freebrowser1** [comment]
No, it didn't help.
`rm -rf  ~/Library/Application\ Support/VSCodium/GPUCache`
and then
`codium --verbose  --disable-gpu | tee err`
results in
I repeated it several times, but always same result.
```
[90m[main 2023-10-15T08:03:08.185Z][0m [File Watcher (node.js)] Request to start watching: /Users/myuser/Library/Application Support/VSCodium/User (excludes: <none>, includes: <all>),/Users/myuser/Library/Application Support/VSCodium/User/settings.json (excludes: <none>, includes: <all>)
[90m[main 2023-10-15T08:03:08.205Z][0m Starting VSCodium
[90m[main 2023-10-15T08:03:08.205Z][0m from: /Applications/VSCodium.app/Contents/Resources/app
[90m[main 2023-10-15T08:03:08.205Z][0m args: {
  _: [],
  diff: false,
  merge: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  'pre-release': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': true,
  'disable-chromium-sandbox': false,
  'ms-enable-electron-run-as-node': true,
  telemetry: false,
  debugRenderer: false,
  'enable-smoke-test-driver': false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'use-inmemory-secretstorage': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  'disable-gpu-sandbox': false,
  '__enable-file-policy': false,
  'enable-coi': false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  'disable-dev-shm-usage': false,
  'profile-temp': false,
  logsPath: '/Users/myuser/Library/Application Support/VSCodium/logs/20231015T100308'
}
[90m[main 2023-10-15T08:03:08.207Z][0m Resolving machine identifier...
[90m[main 2023-10-15T08:03:08.207Z][0m Resolved machine identifier: b7d50d44820711c8eaab7652922290e00ec01b04eddc9fd97071e1dfc81a213f
[90m[main 2023-10-15T08:03:08.207Z][0m Main->SharedProcess#connect
[90m[main 2023-10-15T08:03:08.234Z][0m StorageMainService: creating application storage
[90m[main 2023-10-15T08:03:08.237Z][0m ElectronURLListener: waiting for window to be ready to handle URLs...
[90m[main 2023-10-15T08:03:08.237Z][0m lifecycle (main): phase changed (value: 2)
[90m[main 2023-10-15T08:03:08.237Z][0m windowsManager#open
[90m[main 2023-10-15T08:03:08.238Z][0m windowsManager#open pathsToOpen [
  {
    backupPath: '/Users/myuser/Library/Application Support/VSCodium/Backups/1697356522687',
    remoteAuthority: undefined
  }
]
[90m[main 2023-10-15T08:03:08.238Z][0m windowsManager#doOpenEmpty {
  restore: true,
  remoteAuthority: undefined,
  filesToOpen: undefined,
  forceNewWindow: true
}
[90m[main 2023-10-15T08:03:08.239Z][0m IPC Object URL: Registered new channel vscode:4e21a0ad-062b-487c-84bd-a7d6ba750abd.
[90m[main 2023-10-15T08:03:08.239Z][0m window#validateWindowState: validating window state on 1 display(s) { mode: 1, x: 208, y: 66, width: 1024, height: 768 }
[90m[main 2023-10-15T08:03:08.239Z][0m window#validateWindowState: 1 monitor working area { x: 0, y: 0, width: 1440, height: 900 }
[90m[main 2023-10-15T08:03:08.239Z][0m window#ctor: using window state { mode: 1, x: 208, y: 66, width: 1024, height: 768 }
[90m[main 2023-10-15T08:03:08.291Z][0m window#load: attempt to load window (id: 1)
[90m[main 2023-10-15T08:03:08.303Z][0m windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 1, emptyToOpen: 0)
[90m[main 2023-10-15T08:03:08.303Z][0m lifecycle (main): phase changed (value: 3)
[90m[main 2023-10-15T08:03:08.303Z][0m resolveShellEnv(): skipped (VSCODE_CLI is set)
[90m[main 2023-10-15T08:03:08.309Z][0m update#setState idle
[90m[main 2023-10-15T08:03:08.663Z][0m [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/Users/myuser/Library/Application Support/VSCodium/User/settings.json'
[90m[main 2023-10-15T08:03:08.677Z][0m [File Watcher (node.js)] Started watching: '/Users/myuser/Library/Application Support/VSCodium/User'
[90m[main 2023-10-15T08:03:10.805Z][0m lifecycle (main): phase changed (value: 4)
```

The only way to stop it was `ps -ef | grep -i codi` and then `kill -9 <the returned pid>`.

**Comment by Sierra1011** [comment]
> Try `codium --disable-gpu` and if that resolve the issue delete/rename `~/.config/VSCodium/GPUCache` (it will be regenerated).

I've just been hit by this issue out of nowhere and nothing made it work - finally stumbled across this and it worked immediately!

Running VSCodium 1.83.1.23285, OpenSUSE Tumbleweed and all the same hallmarks - I could see frames and menus but no content.

**Comment by freebrowser1** [comment]
Sierra1011: Is it Arm or Intel ?

**Comment by Sierra1011** [comment]
> Sierra1011: Is it Arm or Intel ?

Intel

**Comment by nilsnh** [comment]
I was also hit by this issue just now.  

Could not see any content upon startup. What fixed it was running `flatpak run com.vscodium.codium --disable-gpu`. Afterwards I tried deleting VSCodium's cache found in `~/.var/app/com.vscodium.codium/config/VSCodium/GPUCache` (Flatpak organizes files a certain way). When I then re-ran VSCodium the issue was solved!

This is on Linux Mint 21.2 using Intel CPU.

More info about my VSCodium setup:

```
Version: 1.83.1
Release: 23285
Commit: 36d13de33ac0d6c684f10f99cff352e2f58228b3
Date: 2023-10-12T18:26:29.496Z
Electron: 25.8.4
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-87-generic
```

**Comment by rukshn** [comment]
I had the same issue, and this solved the issue. Thank you @nilsnh 

https://github.com/VSCodium/vscodium/issues/1692#issuecomment-1785078676

**Comment by daiyam** [comment]
The current issue is about macOS sonoma.
Dear linux users, please see #1701 :wink:

**Comment by rukshn** [comment]
> The current issue is about macOS sonoma. Dear linux users, please see #1701 😉

It's not just about MacOS, it also effected my Intel running OpenSuse and @nilsnh solution solved my issue on OpenSuse

**Comment by APPLESOFT98** [comment]
I use OpenSUSE Tumbleweed and after updating to the latest version I'm having the same problem (again, #1701 ). I've tried doing `rm -rf .config/VSCodium/GPUCache` but it's only a temporary fix. If this problem is present on both MacOS and Linux, I think it's present for all Unix-like systems. 
I should try to check if it is present on Windows as well.

**Comment by daiyam** [comment]
I can't reproduce the issue on either macOS 11 or 12 (not VM). And, I can't find any similar issues for VSCode.

**Comment by shawnbrown** [comment]
I encountered this on Fedora with a Flatpak installation. The fix that @nilsnh used (now added to the [wiki](https://github.com/VSCodium/vscodium/wiki/Troubleshooting)) also worked for me.

**Comment by 0x1a8510f2** [comment]
FWIW I've also had this issue show up on an Intel-based Dell Precision 7530 with AMD GPU, and Framework 13 AMD CPU&GPU. Both running openSUSE Tumbleweed with Codium installed via the official Codium repos.

**Comment by daiyam** [comment]
@0x1a8510f2 see #1701
