### ISSUE TITLE
package error in Windows10

### ISSUE THREAD

**Issue by gitmessage** [VSCodium/vscodium#1697]
"C:\Program Files\Git\bin\bash.exe" ./build/windows/msi/build.sh
error:

++ pwd
+ CALLER_DIR=/c/dev/vscodium
++ dirname ./build/windows/msi/build.sh
+ cd ./build/windows/msi
+ WIN_SDK_MAJOR_VERSION=10
+ WIN_SDK_FULL_VERSION=10.0.17763.0
+ [[ '' == \i\n\s\i\d\e\r ]]
+ PRODUCT_NAME=VSCodium
+ PRODUCT_CODE=VSCodium
+ PRODUCT_UPGRADE_CODE=965370CD-253C-4720-82FC-2E6B02A53808
+ ICON_DIR='..\..\..\src\stable\resources\win32'
+ SETUP_RESOURCES_DIR='.\resources\stable'
++ powershell.exe -command '[guid]::NewGuid().ToString().ToUpper()'
+ PRODUCT_ID=77FCA848-ACA3-4EEA-B7E5-F48D9FA1C554
+ PRODUCT_ID=77FCA848-ACA3-4EEA-B7E5-F48D9FA1C554
+ CULTURE=en-us
+ LANGIDS=1033
+ SETUP_RELEASE_DIR='.\releasedir'
+ BINARY_DIR='..\..\..\VSCode-win32-'
+ LICENSE_DIR='..\..\..\vscode'
++ env
++ sed -n 's/^ProgramFiles(x86)=//p'
+ PROGRAM_FILES_86='C:\Program Files (x86)'
+ [[ -z '' ]]
+ OUTPUT_BASE_FILENAME=VSCodium--
+ [[ '' == \i\a\3\2 ]]
+ export PLATFORM=
+ PLATFORM=
+ sed -i 's|@@PRODUCT_UPGRADE_CODE@@|965370CD-253C-4720-82FC-2E6B02A53808|g' '.\includes\vscodium-variables.wxi'
+ sed -i 's|@@PRODUCT_NAME@@|VSCodium|g' '.\vscodium.xsl'
+ find i18n -name '*.wxl' -print0
+ xargs -0 sed -i 's|@@PRODUCT_NAME@@|VSCodium|g'
+ 'C:\Program Files (x86)\WiX Toolset v3.11\bin\heat.exe' dir '..\..\..\VSCode-win32-' -out Files-VSCodium--.wxs -t vscodium.xsl -gg -sfrag -scom -sreg -srd -ke -cg AppFiles -var var.ManufacturerName -var var.AppName -var var.AppCodeName -var var.ProductVersion -var var.IconDir -var var.LicenseDir -var var.BinaryDir -dr APPLICATIONFOLDER -platform ''
heat.exe : error HEAT0001 : startIndex 不能大于字符串长度。
参数名: startIndex

Exception Type: System.ArgumentOutOfRangeException

Stack Trace:
   在 System.String.Substring(Int32 startIndex, Int32 length)
   在 Microsoft.Tools.WindowsInstallerXml.Tools.Heat.ParseCommandLine(String[] args)
   在 Microsoft.Tools.WindowsInstallerXml.Tools.Heat.Run(String[] args)

**Comment by GitMensch** [comment]
What did you do, what did you expect?

**Comment by daiyam** [comment]
Nothing, since `./build/windows/msi/build.sh` is normally called by other scripts with a bunch of env variables...
