### ISSUE TITLE
Older windows not supported

### ISSUE THREAD

**Issue by s0mt0chukwu** [VSCodium/vscodium#1698]
Older windows os not up-to-date with latest windows os like 10 or 11
Last version vscodium for older windows was 1.69.2
OS was Windows_NT x64 6.1

**Comment by python-and-fiction** [comment]
see #1264

**Comment by daiyam** [comment]
`[1.81.1.23222](https://github.com/VSCodium/vscodium/releases/tag/1.81.1.23222)` is the latest version supported by Windows 7.

**Comment by popey** [comment]
Snapcrafters no longer publishes vscodium since December 2021. 
Issues should be filed at https://github.com/VSCodium/vscodium/issues

**Comment by GitMensch** [comment]
Closed as not planned, if you need newer versions that don't use upstream electron, you may try https://github.com/Alex313031/codium/releases
