### ISSUE TITLE
extension code-settings-sync fails

### ISSUE THREAD

**Issue by PhE** [VSCodium/vscodium#17]
The extension [code-settings-sync](https://github.com/shanalikhan/code-settings-sync) fails on vscodium.

The extension loads fine but fails to download settings (cf [issue](https://github.com/shanalikhan/code-settings-sync/issues/650))

here is the error notification :
![image](https://user-images.githubusercontent.com/1107924/45739409-3d053a80-bbf3-11e8-9e87-68768af44d48.png)

and the developer tools console :
![image](https://user-images.githubusercontent.com/1107924/45739499-78076e00-bbf3-11e8-88ce-200ea6f54c3b.png)

**Comment by stripedpajamas** [comment]
@PhE support was merged upstream, should I'm thinking it will work in the next version of the extension 🎉
