### ISSUE TITLE
Blank screen on start (Fedora 39)

### ISSUE THREAD

**Issue by Flywall** [VSCodium/vscodium#1704]
**OS**
*Fedora 39*
**Problem**
_Blank screen on start_
![image](https://github.com/VSCodium/vscodium/assets/24573430/b6aae529-e88b-4079-9e38-769132b8f8cb)
_Logs attached_
[codium-bug.log](https://github.com/VSCodium/vscodium/files/13206788/codium-bug.log)

**Comment by daiyam** [comment]
https://github.com/VSCodium/vscodium/wiki/Troubleshooting#how-do-i-fix-rendering-glitches-such-as-text-andor-the-entire-interface-not-appearing

**Comment by Flywall** [comment]
@daiyam, Thanks for this trick.
