### ISSUE TITLE
Donating Funds to VSCodium

### ISSUE THREAD

**Issue by Lfada** [VSCodium/vscodium#1711]
**Describe the bug**
No bug, just a big Thank You from a team that depends on you :)

Hi VSCodium community and maintainers.  I'm Lucas, a core contributor to the Radworks project. https://radworks.org/

We've been using https://github.com/VSCodium/vscodium as part of [[Drips](http://drips.network/)]. It's in fact one of our most critical dependencies!

We really appreciate the work you all do and want to ensure you are all well-funded to keep doing it. For that reason, we have decided to donate some funds to your project through [[Drips](https://www.drips.network/)](an initiative that is coming out of our organization for funding FOSS).

Who can I talk to about it?

**Screenshots**
<img width="1144" alt="Screenshot 2023-11-02 at 5 58 11 PM" src="https://github.com/VSCodium/vscodium/assets/105462273/b4cfe1eb-93d7-40f0-b57b-bbf1a8fa87ae">

cc: @daiyam @stripedpajamas

**Comment by daiyam** [comment]
Hi Lucas, you're welcome.

You can contact me at daiyam@zokugun.org

**Comment by Lfada** [comment]
Hi @daiyam, wanted to follow up on this.

Happy to bring some of our more technical people into a conversation to answer any questions you might have.

We also have resources that can help you pick the right wallet for your needs.

But most importantly, what's blocking or stopping you from starting the claim process?
