### ISSUE TITLE
Cannot autoclose quotes in shell script file

### ISSUE THREAD

**Issue by L1so** [VSCodium/vscodium#1716]
**Describe the bug**
I found that I'm unable to auto close the quotes. I have set autoclosing settings to always. It happens when I writing shell script.

**Please confirm that this problem is VSCodium-specific**
- [] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [v] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Open any shell script
2. Type `echo "`
3. Watch that it doesn't auto close.

**Expected behavior**
Autoclose quote like `echo ""`

**Screenshots**
![1](https://i.stack.imgur.com/852c1.gif)
The settings:
![2](https://i.stack.imgur.com/jXTgg.png)

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Architecture: x64
 - Version 1.84.1
 - App Manager: apt
 - Sandboxed: No

**Additional context**
However, just typing quote `"` it will auto close, but if I put word before quote like `echo`, `read`, `printf`. No auto close

**Comment by L1so** [comment]
Can anyone please confirm if there experience same problem as me ?

**Comment by daiyam** [comment]
Visual Studio Code has the same behaviour.
