### ISSUE TITLE
Windows (System install): Updates don't work since a while

### ISSUE THREAD

**Issue by GitMensch** [VSCodium/vscodium#1717]
**Describe the bug**
Updates are recognized, but clicking on "Install Update" just leads to a note "Installing Update..." which never changes

**Please confirm that this problem is VSCodium-specific**
- [x] I'm quite sure that auto-update isn't broken on Microsoft's Visual Studio Code, but I did not checked that.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.
c:\Users\me\.vscode-oss\extensions\extensions.json.vsctmp

**To Reproduce**
1. Install https://github.com/VSCodium/vscodium/releases/download/1.84.1.23311/VSCodium-x64-1.84.1.23311.msi
2. Start
3. Get an update notice, click on Update

**Expected behavior**
Update installation working

**Desktop (please complete the following information):**
 - Win 11

**Additional context**
Uninstalling via "software" and re-installing manually with msi did not work (tried the previous uninstall several times, last time with 1.84.1)

This _may_ be related to "update not working" mentioned in #1694.
@daiyam Any idea?

**Comment by lorypelli** [comment]
it gives an error that not every istance of the program is closed

**Comment by lorypelli** [comment]
actually, if you are lucky, it could work

**Comment by daiyam** [comment]
Uninstalling et re-installing should still work. At least, it does for me.

Yeah, the update seems broken...

**Comment by GitMensch** [comment]
Yes, re-install works, but doesn't fix the update.

**Comment by daiyam** [comment]
here the patch for MSI: https://github.com/VSCodium/vscodium/blob/master/patches/update-windows.patch

**Comment by daiyam** [comment]
The correct file is downloaded, it sound like the `spawn` is been blocked.

**Comment by daiyam** [comment]
OK, I get the error `The program or feature "\??\C:\Users\User\AppData\Local\Temp\codium-stable-undefined-x64\CodeSetup-stable-5a21cd9bd26def06f1b56c50933f812884617855.exe" cannot start or run due to incompatibity with 64-bit versions of Windows. Please contact the software vendor to ask if a 64-bit Windows compatible version is available.` in the Windows Logs.

It's a path issue!

I will get the same error with `msiexec.exe /i .\VSCodium-x64-1.84.2.23314.msi`, while `msiexec.exe /i VSCodium-x64-1.84.2.23314.msi` will work.

**Comment by lakshits11** [comment]
Can anyone please suggest a step by step method if they know to get this thing working again

**Comment by lorypelli** [comment]
> Can anyone please suggest a step by step method if they know to get this thing working again

Go to
```
C:\Users\<username>\AppData\Local\Temp\codium-stable-system-x64
```
and run the executable file

**Comment by lorypelli** [comment]
it worked for me

**Comment by daiyam** [comment]
Downloading and executing the MSI directly will work fine.

**Comment by lorypelli** [comment]
> Downloading and executing the MSI directly will work fine.

no data loss, right?

**Comment by alibutt30** [comment]
Hello, 
Maybe i am outdated here. 
I have the user only version of vscodium installed. 
The updates were working fine (If you click update -- it updated the vscodium) but with some latest release now it downloads the vscodium from the browser instead of updating it. 
Has something changed here ? 

(Just a question, just want to understand)

**Comment by daiyam** [comment]
@alibutt30 Please open a new issue with more description of your system and binary used. Thx

**Comment by alibutt30** [comment]
@daiyam  - sure, i will do it. Thank you so much

**Comment by daiyam** [comment]
A patch is coming for the MSI update issue.

You will have manually update to the next version or apply the following fix:
- Disable `update.enableWindowsBackgroundUpdates`
  ![Screen Shot 2023-11-13 at 12 26 43](https://github.com/VSCodium/vscodium/assets/587742/5edeed8c-c889-4040-8c99-99570b330bc1)

Then you should have the menu `Restart to Update`
![Screen Shot 2023-11-13 at 12 28 32](https://github.com/VSCodium/vscodium/assets/587742/a0a2d638-686b-4579-88e3-f790a4ef4ec4)

**Comment by lorypelli** [comment]
> A patch is coming for the MSI update issue.
> 
> You will have manually update to the next version or apply the following fix:
> 
> * Disable `update.enableWindowsBackgroundUpdates`
>   ![Screen Shot 2023-11-13 at 12 26 43](https://user-images.githubusercontent.com/587742/282449145-5edeed8c-c889-4040-8c99-99570b330bc1.png)
> 
> Then you should have the menu `Restart to Update` ![Screen Shot 2023-11-13 at 12 28 32](https://user-images.githubusercontent.com/587742/282449255-a0a2d638-686b-4579-88e3-f790a4ef4ec4.png)

I had the menu also without doing this, and even in the update I did today, I had to do it manually with exe file in AppData temp folder

**Comment by lorypelli** [comment]
it was the one released 3 hours ago as of now

**Comment by lakshits11** [comment]
> > A patch is coming for the MSI update issue.
> > You will have manually update to the next version or apply the following fix:
> > 
> > * Disable `update.enableWindowsBackgroundUpdates`
> >   ![Screen Shot 2023-11-13 at 12 26 43](https://user-images.githubusercontent.com/587742/282449145-5edeed8c-c889-4040-8c99-99570b330bc1.png)
> > 
> > Then you should have the menu `Restart to Update` ![Screen Shot 2023-11-13 at 12 28 32](https://user-images.githubusercontent.com/587742/282449255-a0a2d638-686b-4579-88e3-f790a4ef4ec4.png)
> 
> I had the menu also without doing this, and even in the update I did today, I had to do it manually with exe file in AppData temp folder


Not working. Mine is always stuck on downloading update

**Comment by GitMensch** [comment]
Last updates all worked fine for me, so closing that.

**Comment by 0x416c69** [comment]
<img width="164" alt="VSCodium_3XHCNkxDXV" src="https://github.com/user-attachments/assets/5ec0dd82-920c-4433-bcb5-27d63318f526">

I have a CodeSetup-stable-21b1e2955ddda36eeba3a94e643128e465285b93.exe under **AppData\Local\Temp\codium-stable-undefined-x64**

@GitMensch

**Comment by GitMensch** [comment]
the MSI is a system wide install, so admin privileges are definitely expected; for a user setup take VSCodiumUserSetup-x64 (.exe only, no .msi) - that _may_ get you an UAC prompt on update but should work as a normal user.
If you don't want any  of that then the .zip is the right one, but I think that has updates disabled.

In any case this leaves the question if `update.enableWindowsBackgroundUpdates` should work with a system-install (I guess it is stuck because you don't have an UI to pass UAC).
What is the default setting for that?

**Comment by indexds** [comment]
Still happening on my side;
Version: 1.93.1
Release: 24256
Commit: dbab3f8e8c5da7ca1bde636806e0a973e497aa01
Date: 2024-09-12T18:37:29.599Z
Electron: 30.4.0
ElectronBuildId: undefined
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045
Running the executable situated here: C:\Users\_index\AppData\Local\Temp\codium-stable-undefined-x64
gives an error that the program cannot execute on this computer.

**Comment by daiyam** [comment]
@olirumiffol On which version were you?
