### ISSUE TITLE
Wrong memory page alignment on Linux arm64 Apple Silicon

### ISSUE THREAD

**Issue by janvhs** [VSCodium/vscodium#1720]
**Describe the bug**
The snap uses the wrong memory page alignment.
I think it has to use 16k, but I'm not sure.

```
/snap/codium/360/usr/lib/aarch64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders: error while loading shared libraries: libgmodule-2.0.so.0: ELF load command alignment not page-aligned
/snap/codium/360/usr/share/codium/bin/../codium: error while loading shared libraries: libffmpeg.so: ELF load command alignment not page-aligned
```

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Install Linux on Apple Silicon (Fedora Asahi Remix)
2. Install Snap
3. Install Codium via Snap
4. Start Codium

**Expected behavior**
Start Codium

**Desktop (please complete the following information):**
 - OS: Fedora Asahi Remix
 - Architecture: Arm64 Apple M2
 - Version: 1.84.2.23314
 - App Manager: Snap
 - Sandboxed: Snap

**Additional context**
The Flatpak version has no issues starting.

**Comment by segabor** [comment]
The very same issue hits my Raspberry Pi 5 as well.

```sh
segabor@bigfive:~ $ codium
/snap/codium/366/usr/lib/aarch64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders: error while loading shared libraries: libgmodule-2.0.so.0: ELF load command alignment not page-aligned
/snap/codium/366/usr/share/codium/bin/../codium: error while loading shared libraries: libffmpeg.so: ELF load command alignment not page-aligned
```
OS: Raspberry OS 64 bit (Debian 12 based).
Install Command: `sudo snap install codium --classic`

**Comment by janvhs** [comment]
I think one has to update the snap runtime to core20 or even better core22.

I tried that, but building the Snap fails with an error that certain packages are not found.
