### ISSUE TITLE
Updating downloads the zip file instead of updating vscodium

### ISSUE THREAD

**Issue by alibutt30** [VSCodium/vscodium#1721]
**Describe the bug**
Updating the vscodium downloads the zip file instead of updating the vscodium.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. The currently installed version is https://github.com/VSCodium/vscodium/releases/tag/1.84.1.23311 -- [VSCodiumUserSetup-x64-1.84.1.23311.exe](https://github.com/VSCodium/vscodium/releases/download/1.84.1.23311/VSCodiumUserSetup-x64-1.84.1.23311.exe))
2. Click on check for updates.
4. There is an update. The Download update (1) is shown.  
![image](https://github.com/VSCodium/vscodium/assets/18707261/90caf205-e087-4c31-8d90-ba5126fced53)
5. Click on Download update (1).
6. Instead of updating the vscodium, it downloads this zip file:  
https://github.com/VSCodium/vscodium/releases/download/1.84.2.23314/VSCodium-win32-x64-1.84.2.23314.zip 

**Expected behavior**
The update of vscodium was expected to happen instead of downloading the zip file.

**Screenshots**
![image](https://github.com/VSCodium/vscodium/assets/18707261/657928d4-c581-49a0-930b-929f44be54b7)
![image](https://github.com/VSCodium/vscodium/assets/18707261/dab64a75-2c54-4103-9683-a03fc0645852)

**Desktop (please complete the following information):**
 - OS: [Windows_NT x64 10.0.19045] Windows 10
 - Architecture [x64]
 - Version [1.84.1 Release 23311]
 - App Manager [Manual download of .exe file and install]
 - Sandboxed [No]

**Additional context**
It used to work before, but since some new updates (i cannot say which one) it started behaving this way.

**Comment by daiyam** [comment]
Can you check that you have the file `unins000.exe` in `C:\Users\<User>\AppData\Local\Programs\VSCodium` (the path where you have installed VSCodium)?

**Comment by alibutt30** [comment]
@daiyam 
You are right, I have no `unins000.exe` in `C:\Users\XXX\AppData\Roaming\Apps\VSCodium` 

![image](https://github.com/VSCodium/vscodium/assets/18707261/962e8bf9-8f79-45a1-8570-0e0f84808e82)

**Comment by daiyam** [comment]
The `unins000.exe` is used to detect the `.exe` install and to get correct update (it's a VSCode code)
I wonder why you it's installed in `Roaming`?

**Comment by daiyam** [comment]
Are you able to uninstall VSCodium?

**Comment by alibutt30** [comment]
@daiyam I can see the uninstall option in control panel on windows. Shall i uninstall and reinstall again ?

**Comment by daiyam** [comment]
Yes, please. Before reinstalling, could you check if `C:\Users\XXX\AppData\Roaming\Apps\VSCodium` is empty?
And can you make sure that you are using the `UserSetup` version, thx.

Are you using a company machine? Because `Roaming` means that your windows profile can be moved to another machine (synced to a server).

**Comment by alibutt30** [comment]
@daiyam Yes i am using a company machine. In this case is User Setup not the correct one ? 
Should i install the full system wide version ?

**Comment by daiyam** [comment]
User Setup should be fine. I just wonder why the `unins000.exe` is missing...
If it's still missing, yes, try the system version.

**Comment by alibutt30** [comment]
So the reinstall fixed it. 
Now the location of the install is also correct. `C:\Users\XXX\AppData\Local\Programs\VSCodium` 
Can also see the `unins000.exe`
![image](https://github.com/VSCodium/vscodium/assets/18707261/c07f5f19-df5c-43db-922a-c7bf6a9b88ad)


Thank you so much for your support (Y) 

This issue can be closed.
