### ISSUE TITLE
Diff ignoring indent change

### ISSUE THREAD

**Issue by moritz-t-w** [VSCodium/vscodium#1723]
Type: <b>Bug</b>

1. checkout https://github.com/moritz-t-w/Godot-Form-AL/commit/e027000a73c5dbca043a207ceaa1db0aab1e63af
2. apply changes from https://github.com/moritz-t-w/Godot-Form-AL/commit/268e5a46d17c9b3d1d744844a84c8040606b2146
3. Look at the diff

I don't know the exact issue and I don't have time for it. If someone wants to look at this, here it is.

VSCodium version: VSCodium 1.84.2 (5a21cd9bd26def06f1b56c50933f812884617855, 2023-11-10T18:20:39.461Z)
OS version: Linux x64 6.1.62-1-lts
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz (8 x 3602)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|31.29GB (24.03GB free)|
|Process Argv|--ms-enable-electron-run-as-node --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by moritz-t-w** [comment]
![image](https://github.com/VSCodium/vscodium/assets/90388353/7a31be4f-9adb-41d2-890c-eaa5d2d7969b)

**Comment by moritz-t-w** [comment]
Relevant block:
```gdscript
## Input control to label
@export var input: Control:
	set(new_val):
		if FormContainer.is_input(new_val):
			if input != null:
				input.gui_input.disconnect(indicate_validity)
			input = new_val
			mode = mode # run setter
			indicate_required()
			if validate_on_input && input != null:
				input.gui_input.connect(indicate_validity.unbind(1))
		else:
			printerr(get_class(),": input must be a input button or input field")
```

**Comment by moritz-t-w** [comment]
I reported this here without even realising cause I used the built in reporting tool but it's probably a vscode issue so I will post it there aswell.

**Comment by daiyam** [comment]
@moritz-t-w If you look at https://github.com/moritz-t-w/Godot-Form-AL/commit/268e5a46d17c9b3d1d744844a84c8040606b2146, you can see that the space before the `input = new_val` has been removed (on the left side of the diff)

**Comment by moritz-t-w** [comment]
I know. That's what's not showing up in vscodium as you can see in the screenshot

**Comment by daiyam** [comment]
Ah! You need to activate the whitespace differences on the top right 
![Screen Shot 2023-11-13 at 14 41 42](https://github.com/VSCodium/vscodium/assets/587742/91ff97f0-709c-4883-bf5d-55c9fefe9280)

**Comment by moritz-t-w** [comment]
Aha! Thanks I didn't know that was a thing
