### ISSUE TITLE
Alternative to Pylance?

### ISSUE THREAD

**Issue by farahats9** [VSCodium/vscodium#1724]
As the whole purpose of using VSCodium is to stay away from closed source and telemetry, is there any comparable extension to the Python extension that includes closed source language server (Pylance)? 
I remember there was Jedi before it which was MIT licensed but I cannot find an extension for it anymore.

**Comment by daiyam** [comment]
Maybe https://github.com/pappasam/jedi-language-server

**Comment by farahats9** [comment]
Ok I didn't know there is a setting to switch from Pylance to Jedi in the Python extension
