### ISSUE TITLE
Any document or text is left blank and cannot be displayed

### ISSUE THREAD

**Issue by TogoFire** [VSCodium/vscodium#1739]
**Describe the bug**
Any document or text is left blank and cannot be displayed

**Please confirm that this problem is VSCodium-specific**
This problem happens in VsCode and VsCodium

**To Reproduce**
1. Open VsCode
2. New text document or Open any text document.
3. Typing anything will be blank or invisible.

**Expected behavior**
The normal behavior was to view the text, but the text does not appear.

**Screenshots**
![Screenshot_20231126_120305](https://github.com/VSCodium/vscodium/assets/45384937/5451552f-fcef-41c4-b815-239dc2a7252a)

**Desktop (please complete the following information):**
OS: openSUSE Tumbleweed x86_64 
Kernel: 6.6.2-1-default 
Uptime: 23 mins 
Packages: 2842 (rpm) 
Shell: bash 5.2.21 
Resolution: 1366x768 
DE: Plasma 5.27.9 
WM: KWin 
Theme: [Plasma], Adwaita [GTK2], Breeze [GTK3] 
Icons: [Plasma], breeze-dark [GTK2/3] 
Terminal: konsole 
CPU: Intel i5-5200U (4) @ 2.700GHz 
GPU: Intel HD Graphics 5500 
Memory: 2382MiB / 7841MiB 
 - App Manager: RPM (YaST).
 - Sandboxed: no.

**Additional context**
This problem has been happening for over 3 months. I tested on other computers and the same problem happens. I was hoping that an update would fix it, but that never happened.

**Comment by daiyam** [comment]
https://github.com/VSCodium/vscodium/wiki/Troubleshooting#how-do-i-fix-rendering-glitches-such-as-text-andor-the-entire-interface-not-appearing

**Comment by TogoFire** [comment]
> https://github.com/VSCodium/vscodium/wiki/Troubleshooting#how-do-i-fix-rendering-glitches-such-as-text-andor-the-entire-interface-not-appearing

rm -rf ~/.config/VSCodium/GPUCache

Thanks. This worked!

**Comment by starball5** [comment]
Also [Why am I getting rendering issues with VS Code 1.82-1.84?](https://stackoverflow.com/q/77100725/11107541)
