### ISSUE TITLE
Sign Windows Binaries (False positive Malware)

### ISSUE THREAD

**Issue by Makazzz** [VSCodium/vscodium#174]
Each time I open VSCodium ia32 in portable mode on a Windows 10 x64 with Bitdefender; It's saying Atc4.detection or Malware detected and block it.

-[✓] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

-[✓] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

To Reproduce
1. Go to the root folder of the app
2. Open VSCodium.exe ia32 version
3. Wait to see the warning with Bitdefender stop the app and block it

![falsepositive](https://user-images.githubusercontent.com/49844464/58375431-6cb6d000-7f42-11e9-8791-7e59a8b15ff1.PNG)

 - OS: Windows 10
 - Architecture: x64
 - Version: 1.34.0

**Comment by JL2210** [comment]
Probably because this tries to upload telemetry to `0.0.0.0` and the Microsoft URLs are allowed in the anti-malware software.

**Comment by Makazzz** [comment]
> 
> 
> Probably because this tries to upload telemetry to `0.0.0.0` and the Microsoft URLs are allowed in the anti-malware software.

But why it is doing that only in the ia32 version? I have no problem with the x64.

**Comment by JL2210** [comment]
Microsoft force enables telemetry anyway. I'd blame it on Windows.

**Comment by stripedpajamas** [comment]
Pretty weird situation @Makazzz -- I will try to reproduce it on my Windows machine and figure out what exactly it is reacting to. Thanks for reporting!!

**Comment by knopp** [comment]
Is the windows binary codesigned? Distribution windows binaries without (preferably EV certificate) is world of hurt, as everything flaggs it as malware. And even with certificate there are still often heaps of false positives.

**Comment by stripedpajamas** [comment]
The Windows binary is not being codesigned at this time. I should prioritize that if it would help with malware false positives.

**Comment by Makazzz** [comment]
Information: I can't test this problem anymore because I uninstalled Bitdefender.

**Comment by GitMensch** [comment]
@stripedpajamas wrote:

> The Windows binary is not being codesigned at this time. I should prioritize that if it would help with malware false positives.

It definitely would. Ideally both the executable and the installer exe+msi would use the same code sign

**Comment by GitMensch** [comment]
Just adding the reference: #527 (already closed, but found first in my search).

**Comment by GitMensch** [comment]
@daiyam Closed, so the installer and executables are now signed?

**Comment by daiyam** [comment]
no, I've closed it because of "False positive Malware"

**Comment by GitMensch** [comment]
Then the "old issue of signing the codium executable and the installer (however this may work) is still open, I'd suggest to keep track of code signing certificate issues here.

**Comment by GitMensch** [comment]
reopening it to keep track of code-signing here.
