### ISSUE TITLE
How to generate exe on windows

### ISSUE THREAD

**Issue by yinhunfeixue** [VSCodium/vscodium#1742]
run ./build/build.sh on window 11 ,  but no exe file

thanks

**Comment by yellowman1273** [comment]
.sh files are for linux users only
go to https://github.com/VSCodium/vscodium/releases, click "Show all 92 assets," and find the setup .exe

**Comment by daiyam** [comment]
> .sh files are for linux users only

On Windows, `build.sh` is correct (`"C:\Program Files\Git\bin\bash.exe" ./build/build.sh`)
The `.ps1` is just a shortcut to that file.

The VSCodium `.exe` will be found under the directory `./VSCode-win32-x64`

If you want the install files, you will need to run the command `./build/build.sh -p`.

**Comment by yellowman1273** [comment]
> > .sh files are for linux users only
> 
> On Windows, `build.sh` is correct (`"C:\Program Files\Git\bin\bash.exe" ./build/build.sh`) The `.ps1` is just a shortcut to that file.

oh ok i havent used windows in a while so i didnr know
