### ISSUE TITLE
Install with winget

### ISSUE THREAD

**Issue by JasonCraneAdkins** [VSCodium/vscodium#1745]
**Describe the bug**
There is no option to install VSCodium machine wide and no option to install x64 version

**Please confirm that this problem is VSCodium-specific**
- Installation ignores Winget setting to install to Machine wide and architecture.
Also there is way to select machine wide and x64

Winget Settings:

    "installBehavior": {
        "preferences": {
            "scope": "machine"
        }
    },
    "installBehavior": {
        "defaultInstallRoot": "%PROGRAMFILES%"
  },
    "installBehavior": {
        "preferences": {
            "architectures": ["x64", "arm64"]
        }     

**Please confirm that the issue/resolution isn't already documented**
No open Issues related to this Problem is open

**To Reproduce**
Termibal/CMD/Powershell command
winget install VSCodium

**Expected behavior**
Check Winget settings where to install or ask where to install

**Desktop (please complete the following information):**
 - OS:Win11 23H2 Enterprise 
 - Architecture x64
 - Version 10.0.22631
 - App Manager Winget

**Comment by anhkhoakz** [comment]
You should try this https://github.com/VSCodium/vscodium#install-with-winget
