### ISSUE TITLE
Npm scripts error sh: 1: melos: not found

### ISSUE THREAD

**Issue by guyluz11** [VSCodium/vscodium#1750]
**Describe the bug**
I am using `NPM SCRIPTS`, some commands work and for [melos](https://pub.dev/packages/melos) script I am getting an error.

 
**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Create a [dart](https://dart.dev/) project with the following `pubspec.yamel`
```dart
name: tools

environment:
  sdk: '>=3.0.0 <4.0.0'
dev_dependencies:
  melos: ^3.1.1
```
2. Create `pacakge.json` file with melos script
```
{
    "name": "test",
    "version": "0.0.1",
    "scripts": {
        "bootstrap": "melos bootstrap"
    }
}
  
```
3. Run `dart pub global activate melos`
4. Run `dart pub get`
5. In the `EXPLORER` bottom part there will be `NPM SCRIPTS` part (if it missing try right click in the area and adding it.
6. Run the bootstrap script.

**Expected behavior**
Script will work

**Screenshots**
![image](https://github.com/VSCodium/vscodium/assets/9304740/8cdfa019-bbf4-44a4-8ab1-661bb4b1aeb6)

**Desktop (please complete the following information):**
 - OS: Kubuntu 23.10
 - Architecture x64
 - Version 1.84.2
 - App Manager snap
 - Sandboxed snap

**Additional context**
Running other commands from NPM SCRIPTS seem to work!.
This is my first time using vscodium so I am probably missing something very basic.
Wokrs on NPM SCRIPTS from vscode snap as well as directly from terminal.
I have only 3 EXTENSIONS installed: Dart, Flutter, YAMEL.

Terminal output:
```
> cbj_smart_home@0.0.1 bootstrap
> melos bootstrap

sh: 1: melos: not found

 *  The terminal process "/usr/bin/bash '-c', 'npm run bootstrap'" terminated with exit code: 127. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by daiyam** [comment]
It seems like a snap issue which use an incorrect PATH

**Comment by guyluz11** [comment]
Currently I have stoped using Melos, will close the issue.
