### ISSUE TITLE
snap 1.85.0.23343 installed this morning is unusable

### ISSUE THREAD

**Issue by mvvvv** [VSCodium/vscodium#1756]
**Describe the bug**
The program lost memory at each restart. No more recent files, asking for trusty directories again and again. CodeLLDB asking for reload again and again.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Launch vs codium.
2. restart reload for codeLLDB again and again.
3. No more rust tooling

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - ubuntu 23.10 x86 gnome
 - snap

**Additional context**

**Comment by PinkaminaDianePie** [comment]
have exactly the same issue, but can update that nothing works at all - search, terminal etc, like most of the functionality not just recent files

**Comment by katian** [comment]
cpu burn :
![image](https://github.com/VSCodium/vscodium/assets/1428843/d06e2ac6-f591-407e-a26c-0a1152cc9fe3)

**Comment by Amereyeu** [comment]
same here...after update extensions not working, git keeps searching for files, trust domain keeps asking over and over again, cpu at 100%
tried on VM clean install - v 1.84 works fine ...after snap auto update to 1.85 nothing works

**Comment by daiyam** [comment]
OK, I've revert the snap to `1.84.2.23319`

It must be related to https://github.com/VSCodium/vscodium/pull/1754 and maybe that the snap still use `core18`

**Comment by katian** [comment]
Thanks @daiyam and the connection to the Godot framework works now

**Comment by daiyam** [comment]
I had to move the build images to focal since:
- the VSCode build process is now using the builtin method `fetch` (since Node-v18)
- Ubuntu Bionic (Ubuntu 18.04) doesn't support Node-v18

Additionally,
- VSCode' snap is using `core20` (https://github.com/VSCodium/vscodium/pull/1658)
- VSCode is migrating from containers to sysroots (https://github.com/microsoft/vscode-linux-build-agent/commit/ac73445eb6185e5602c640fe7e1397f1e7700899) (merge done on the day of the new release, not sure if it was used)

**Comment by mvvvv** [comment]
If such a problem occurs again it would be really useful to have the previous snap version as a backup.

**Comment by r0gi** [comment]
Version 1.85.1.23348 is broken for me in the exact same way that the others have described. I am running Ubuntu 20.04.6 LTS. This was updated automatically and I don't see any option to install a previous version. Echoing what @mvvvv said it would be useful to have previous versions up.
```
channels:
  latest/stable:    1.85.1.23348 2023-12-14 (369) 182MB classic
  latest/candidate: ↑                                   
  latest/beta:      ↑                                   
  latest/edge:      ↑                                   
installed:          1.85.1.23348            (369) 182MB classic
```

**Comment by daiyam** [comment]
Damn! I forgot to disable the snap! I've reverted the version. Sorry!

**Comment by judemvm** [comment]
The version `1.86.2.24054` has been released, but there's no new version for snap.
Any updates?

**Comment by daiyam** [comment]
Still in my todo list...

**Comment by mvvvv** [comment]
Version 1.86.2 installed today. Well done !
