### ISSUE TITLE
1.85 can not update in WSL

### ISSUE THREAD

**Issue by jmaasing** [VSCodium/vscodium#1757]
After updating to 1.85 on my windows machine I am now unable to connect to WSL. I guess because it is trying to update to 1.85 on the virtual linux and fails for unknown reasons.

[Trace  - 05:20:09.757] Server install command stdout:
Error while extracting server contents
462bd5ead84ec927d8d7d21d: start
exitCode==1==
listeningOn====
connectionToken====
logFile==/home/xxx/.vscodium-server/.00c993f9b9a2a07730235274df02f05bd76575f7.log==
osReleaseId==ubuntu==
arch==x86_64==
platform==Linux==
tmpDir==/run/user/1000/==
462bd5ead84ec927d8d7d21d: end

**Comment by daiyam** [comment]
Do you know which version of Ubuntu is used in WSL?

I'm thinking it might be related to this: https://github.com/VSCodium/vscodium/issues/1756#issuecomment-1848943684

**Comment by jmaasing** [comment]
My WSL-instance has

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

I don't know if the codium update triggered this but it was about that time I tried to upgrade codium

12:18 ~ $ snap changes
ID   Status  Spawn               Ready               Summary
49   Done    today at 05:58 CET  today at 05:58 CET  Auto-refresh snap "core22"

I upgrade VSCode to 1.85 and that works in WSL.

**Comment by jmaasing** [comment]
Fixed in later versions
