### ISSUE TITLE
Crashes when trying to maximize the window

### ISSUE THREAD

**Issue by planetoryd** [VSCodium/vscodium#1764]
`codium --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime --enable-features=WaylandWindowDecorations .`

 6.6.6-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC

`"window.titleBarStyle": "native"`

It crashes when I click the maximize button in the title bar, or from the pop up menu in the bottom bar of KDE, or when I double tap the title bar.

**Comment by planetoryd** [comment]
Vscode also crashes

**Comment by aspizu** [comment]
Weird issues with wayland, if you first open vscodium in xwayland, then open vscodium with wayland support. this wayland window will behave normally, won't immediately crash (or crash on maximizing/snapping). but if you start vscodium wayland without first starting xwayland then it will crash.

**Comment by planetoryd** [comment]
I just tried it again and it told me 

```
➜  ~ codium --ozone-platform=wayland --enable-wayland-ime -n                                                                           
Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'enable-wayland-ime' is not in the list of known options, but still passed to Electron/Chromium.
```

**Comment by aspizu** [comment]
those warnings are normal, they always appear for electron apps.
