### ISSUE TITLE
codium won't open only if root on hardened linux kernel  

### ISSUE THREAD

**Issue by me0mar** [VSCodium/vscodium#1769]
**Describe the bug**
I am encountering an issue where Codium cannot be opened either from the terminal or dmenu. The only way I can run Codium is by root privileges using the following command:
`sudo codium --no-sandbox --user-data-dir`

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**Things I Have Tried**
1. Reinstall.
2. Updated the kernel to the latest version.

**Desktop (please complete the following information):**
 - OS: Arch Linux 
 - Architecture: x64
 - Kernel Version: 6.6.8-hardened
 - App Manager: Paru
 - Sandboxed: No

**Additional context**
The issue occurs on a fresh install, and Codium has not been configured with AppArmor, SELinux, or any other Mandatory Access Control mechanisms.

**Comment by daiyam** [comment]
Which aur did you used?

**Comment by me0mar** [comment]
https://aur.archlinux.org/packages/vscodium-bin
`paru -S vscodium-bin`

**Comment by me0mar** [comment]
**Not Specific to Codium:** 
This issue is not exclusive to Codium; rather, it arises due to the hardened kernel's restriction on non-privileged user namespaces.

if you want To enable unprivileged user namespaces for the current session, execute the following command:

`sudo sysctl kernel.unprivileged_userns_clone=1`

Subsequently, Codium will launch as expected.

**Considerations for Enabling Unprivileged User Namespaces:**
Determining whether to enable unprivileged user namespaces is a decision that requires careful consideration. I do not possess the qualifications to provide a definitive answer. I recommend conducting thorough research and making an informed decision based on your specific requirements.

but if you decide to enable unprivileged user namespaces permanently, use the following commands:

`echo 'kernel.unprivileged_userns_clone=1' | sudo tee -a /etc/sysctl.d/99-unprivileged-userns.conf` 
`sudo sysctl --system`

**Comment by me0mar** [comment]
Not Specific to Codium:
This issue is not exclusive to Codium; rather, it arises due to the hardened kernel's restriction on non-privileged user namespaces.

if you want To enable unprivileged user namespaces for the current session, execute the following command:

sudo sysctl kernel.unprivileged_userns_clone=1

Subsequently, Codium will launch as expected.

Considerations for Enabling Unprivileged User Namespaces:
Determining whether to enable unprivileged user namespaces is a decision that requires careful consideration. I do not possess the qualifications to provide a definitive answer. I recommend conducting thorough research and making an informed decision based on your specific requirements.

but if you decide to enable unprivileged user namespaces permanently, use the following commands:

echo 'kernel.unprivileged_userns_clone=1' | sudo tee -a /etc/sysctl.d/99-unprivileged-userns.conf
sudo sysctl --system

**Comment by swnf** [comment]
In case anyone else has issues with this:

Even if `unprivileged_userns_clone` is set to `1`, the creation of user namespaces can be denied by very recent changes to apparmor (see [here](https://discourse.ubuntu.com/t/spec-unprivileged-user-namespace-restrictions-via-apparmor-in-ubuntu-23-10/37626), [here](https://gitlab.com/apparmor/apparmor/-/wikis/unprivileged_userns_restriction)). In this case, your `dmesg` will contain `apparmor="DENIED"` messages for codium.

There are two ways to deal with this:
 - Disable the new security feature (probably not a good idea). This is controlled by `kernel.apparmor_restrict_unprivileged_userns`. The file `/usr/lib/sysctl.d/10-apparmor.conf` might contain some documentation about this parameter.
 - Create a minimal AppArmor profile for codium. On Ubuntu you can create a file `/etc/apparmor.d/Codium` with the following contents:
    ```
    abi <abi/4.0>,

    include <tunables/global>

    /usr/share/codium/codium flags=(unconfined) {
      userns,
    }
    ```
    It will take effect after a reboot or `sudo systemctl reload apparmor`.
