### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by wsalmeida** [VSCodium/vscodium#177]
How likely is it to extend this beautiful design to other forms of packaging like appimage, snap, and flatpak?

**Comment by stripedpajamas** [comment]
AppImage and Flatpak are mentioned in the README. Snap is in development, tracked in another issue 👍

**Comment by stripedpajamas** [comment]
#102 - Snap issue
AppImage provided in https://github.com/VSCodium/vscodium/releases
Flatpak option: https://github.com/VSCodium/vscodium#flatpak
