### ISSUE TITLE
format not working on ssh

### ISSUE THREAD

**Issue by end3r-man** [VSCodium/vscodium#1776]
**Describe the bug**
in my local project im able to use the code format like laravel blade format, html, css but in my ssh its not working im 100% sure that my ssh installed all the extensions right click menu doesn't have the format option and in the ctrl+shift+p also doesn't have take a look at screentshots

**Please confirm that this problem is VSCodium-specific**
- [ yes ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: arch linux
 - Architecture x64
 - Version 2024.01.01
 - App Manager pacman
 - Sandboxed  Flatpak,

**Comment by noonsleeper** [comment]
@end3r-man Can you add some screenshots and command to make more clear what's going on?

**Comment by di-rect** [comment]
@noonsleeper I do see the same. No format option anywhere to find and that with shfmt installed for Bash.

On Visual Studio Code where I come from it indeed worked. 

There is not much of screenshots possible as there isn't much to show!

**Comment by leagris** [comment]
Also affected, tried to configure path of shfmt command, nothing happens. The top thin running thing indicator blue line goes from left to right a couple times then it stop and file is not formatted.

**Comment by daiyam** [comment]
@end3r-man Can you give me your server infos?
@di-rect @leagris Can you give your desktop and server infos?

Can you also check `Developer: Show Running Extensions` do see if HTML/CSS extensions are correctly running?

Just to know, I don't have the issue...

**Comment by end3r-man** [comment]
desktop: plasma arch linux, server: rockylinux

**Comment by end3r-man** [comment]
ill check it and update " Developer: Show Running Extensions "
