### ISSUE TITLE
Remote SSH is not working

### ISSUE THREAD

**Issue by coderj001** [VSCodium/vscodium#1777]
**Describe the bug**
I have a instances running on gcp I was trying to connect with vscodium, 
```
❯ vscodium --version
1.85.1
08e6c15293922dd53a864bb041be381322fee401
x64
```
 during the process of initialization its unable to connect and return 404 error
 
![image](https://github.com/VSCodium/vscodium/assets/39460245/75f07af0-0fb2-4437-9138-9b5ff973b24f)

I found the url where it trying to download vscode on gcp server
  
![image](https://github.com/VSCodium/vscodium/assets/39460245/0f1c7524-2e07-44df-81e1-4681f073d992)

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. I'm using Arch linux and yay package manager and install vscodium using `yay -S vscodium-bin vscodium-bin-features vscodium-bin-marketplace`
2. Installed [Remote SSH Plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh)
3. Configure ssh using `gcloud compute config-ssh`
4. Next try to ssh to hostname
https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ArchLinux, WD: Gnome
 - Architecture x64
 - Version 1.85.1
 - App Manager Yay

**Additional context**

**Comment by daiyam** [comment]
The `Remote - SSH ` plugin from MS is imcompatbale with VSCodium (https://github.com/VSCodium/vscodium/blob/master/docs/extensions-compatibility.md).
Use [Open Remote - SSH](https://open-vsx.org/extension/jeanp413/open-remote-ssh) instead.
