### ISSUE TITLE
Open ssh does not work on Centos 7

### ISSUE THREAD

**Issue by trungklam** [VSCodium/vscodium#1778]
I'm using VSCodium latest version with `open-remote-ssh` extension and tried to connect to Centos 7 (7.9) and get the below error from server side

`
/root/.vscodium-server/bin/08e6c15293922dd53a864bb041be381322fee401/node: /lib64/libm.so.6: version GLIBC_2.27' not found (required by /root/.vscodium-server/bin/08e6c15293922dd53a864bb041be381322fee401/node)
/root/.vscodium-server/bin/08e6c15293922dd53a864bb041be381322fee401/node: /lib64/libc.so.6: version GLIBC_2.25' not found (required by /root/.vscodium-server/bin/08e6c15293922dd53a864bb041be381322fee401/node)
/root/.vscodium-server/bin/08e6c15293922dd53a864bb041be381322fee401/node: /lib64/libc.so.6: version GLIBC_2.28' not found (required by /root/.vscodium-server/bin/08e6c15293922dd53a864bb041be381322fee401/node)
/root/.vscodium-server/bin/08e6c15293922dd53a864bb041be381322fee401/node: /lib64/libstdc++.so.6: version CXXABI_1.3.9' not found (required by /root/.vscodium-server/bin/08e6c15293922dd53a864bb041be381322fee401/node)
/root/.vscodium-server/bin/08e6c15293922dd53a864bb041be381322fee401/node: /lib64/libstdc++.so.6: version GLIBCXX_3.4.20' not found (required by /root/.vscodium-server/bin/08e6c15293922dd53a864bb041be381322fee401/node)
/root/.vscodium-server/bin/08e6c15293922dd53a864bb041be381322fee401/node: /lib64/libstdc++.so.6: version GLIBCXX_3.4.21' not found (required by /root/.vscodium-server/bin/08e6c15293922dd53a864bb041be381322fee401/node)
`

I guess it can come from the node version we build the vscodium server from. I'm really appreciate if there are any workaround for this
Thanks a lot !

**Comment by trungklam** [comment]
After a search around I found it might related to https://github.com/VSCodium/vscodium/issues/1629

**Comment by GitMensch** [comment]
It is, so closing as duplicate.
