### ISSUE TITLE
unreadable characters appear when opening external windows.

### ISSUE THREAD

**Issue by extremeuser** [VSCodium/vscodium#1780]
Type: <b>Bug</b>

When opening an externa window (open file, save as, about, license, etc.), all the characters appears as squared shapes. I noticed that after I changed the Ubuntu Themes. All other programs at my computer are not affected after changing the themes. I am using VSCodium snap.

Could you please help me with this issue?

Thank you!

![Open File characters bug](https://github.com/VSCodium/vscodium/assets/2085783/719c4df0-4b35-43ba-a19c-2dfdcabcf18a)

VSCodium version: VSCodium 1.84.2 (1fc52b725b3f76b97eadfd988cea42a739ae923f, 2023-11-15T21:57:44.436Z)
OS version: Linux x64 6.5.0-14-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8120 Eight-Core Processor (8 x 1408)|
|GPU Status|2d_canvas: disabled_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: disabled_off<br>webgl2: disabled_off<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.59GB (10.34GB free)|
|Process Argv|--ms-enable-electron-run-as-node --no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|9.17.0
latex-snippets-jeff|Jef|1.2.3
language-julia|jul|1.65.2
python|ms-|2023.20.0
cody-ai|sou|1.0.5
latex-support|tor|3.10.0
grammarly|znc|0.24.0

</details>

**Comment by daiyam** [comment]
See https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md#fonts-showing-up-as-rectangles

**Comment by extremeuser** [comment]
> See https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md#fonts-showing-up-as-rectangles

Hi daiyam,

I have tried your  instructions by closing VSCodium, running the three commands, reopen VSCodium and the fonts are still showing up as rectangles. Have the three commnands to be opened as root?  Do I have to restart the computer?

I am using Ubuntu Mate. 

Thank you!

**Comment by extremeuser** [comment]
> See https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md#fonts-showing-up-as-rectangles

Hi daiyam,

I repeat your instructions as root and restarting the computer and the fonts are still showing up as rectangles.

What do you recommend?


Thank you!
