### ISSUE TITLE
unreadable characters appear when opening external windows Part 2

### ISSUE THREAD

**Issue by extremeuser** [VSCodium/vscodium#1781]
When opening an external window (open file, save as, about, license, etc.), all the characters appears as squared shapes. I noticed that after I changed the Ubuntu Mate Themes. All other programs at my computer are not affected after changing the themes. I am using VSCodium snap.

I followed @daiyam instructions:

 See https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md#fonts-showing-up-as-rectangles

_Originally posted by @daiyam in https://github.com/VSCodium/vscodium/issues/1780#issuecomment-1880087494_

I tried the instructions as an user and as a root and restarting the computer and the fonts are still showing up as rectangles.

I closed the past issue by mistake. I am sorry. 

Could you please help me with this issue?

What do you recommend?

Thank you!

![Open File characters bug](https://github.com/VSCodium/vscodium/assets/2085783/b8b41a48-7f3c-428b-98e1-554e02664f82)

![Instructions_1](https://github.com/VSCodium/vscodium/assets/2085783/32abc5fa-fcf6-412c-906e-b1a4e96d1bf2)

**Comment by colleen05** [comment]
This keeps happening to me too, seemingly at random.
