### ISSUE TITLE
```codium-insiders``` not opening a WSL remote window such as ``code``

### ISSUE THREAD

**Issue by sklbz** [VSCodium/vscodium#1791]
When using this command in the WSL terminal, it launches automatically connected to WSL.
```bash 
code
```

But when launching VS Codium Insiders in the WSL terminal it does not connect automatically to WSL.
```bash 
codium-insiders
```

**Comment by tadghh** [comment]
you need to patch the MS WSL extension or use Open Remote - WSL from openvsix

**Comment by sklbz** [comment]
It is already installed

**Comment by tadghh** [comment]
> It is already installed

Which extension
