### ISSUE TITLE
Mac installation: adding code-oss in the path

### ISSUE THREAD

**Issue by yanns** [VSCodium/vscodium#18]
VScode installs `code` in the path, so that it's very convenient to open it from any directory:
```
~/in-my-project $ code .
```
opens VSCode for `in-my-project`

```
ls -la /usr/local/bin/code
lrwxr-xr-x 1 <user> <group> 68 May 17  2017 /usr/local/bin/code -> '/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code'
```

It'd be awesome if the brew installation would do the same.

**Comment by stripedpajamas** [comment]
@yanns AFAIK, Visual Studio Code doesn't add `code` to the path by default. You have to go to the command palette and choose `Shell command: Install 'code' command in PATH`. In VSCodium you have the same option

![image](https://user-images.githubusercontent.com/2707340/45751224-bd21a500-bbdf-11e8-8fb7-b645b97aae49.png)

This allows `~/in-my-project $ vscodium .`

If you want `code`, you can make an alias `code=vscodium` in your shell profile.

**Comment by yanns** [comment]
Thx a lot for the precision!

**Comment by identifysun** [comment]
```
$ alias code="codium"
```
