### ISSUE TITLE
code-settings-sync extension cannot sync and install extensions on linux build

### ISSUE THREAD

**Issue by mijkami** [VSCodium/vscodium#180]
**Describe the bug**
 `code-settings-sync` extension cannot install extensions when using linux build. 

**Please confirm that the issue/resolution isn't already documented**
The workaround listed [in the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) doesn't work. Also the specific elements that should be changed in the workaround are commented now in the current version of the extension.js file and the folder seems to be detected from a different line of code nowadays.

I managed to migrate manually some settings in the meantime.

**To Reproduce**
Roughly the same problem than the previous [similar issue about code-settings-sync](https://github.com/VSCodium/vscodium/issues/72).

1. Update a gist with code-settings-sync within Visual Studio Code
2. Install latest VSCodium version, install code-settings-sync to attempt to sync your settings
3. Error message pops indicating that "Sync : error logged in console"
4. When toggling developper tools, it shows an error "onDidNotificationChange | @ | workbench.main.js:2361"

**Expected behavior**
code-settings-sync extension working and updating list of VSCodium extensions with the linked gist token.

**Desktop:**
- VSCodium Version : [ Version 1.34.0 ]
- Code Settings Sync Version : [ 3.2.9 ]
- Operating System : [ Ubuntu 19.04 ]
- Architecture : [ x64 ]

**Comment by stripedpajamas** [comment]
Can you paste the Extensions output when this problem happens?
![image](https://user-images.githubusercontent.com/2707340/58719198-e6f0b580-8383-11e9-88a0-eb15f95bdc25.png)

**Comment by stripedpajamas** [comment]
Also keep an eye on https://github.com/shanalikhan/code-settings-sync/pull/859 as work is actively being done to make the extension compatible with `Code - OSS` and `VSCodium`.

**Comment by mijkami** [comment]
I'm not sure to do it well, but when i show the Extensions output and then try to make `code-settings-sync` connect to the remote gist, the Extensions output seems to stay empty.

On the picture here, the "sync : Invalid / Expired Github token" happened at first attempt for some reason. After deleting credentials, generating a new token and saving it, it showed the "Sync  error logged in console" error i spoke about previously.
![image](https://user-images.githubusercontent.com/38231801/58728865-2355fd00-83e8-11e9-92b2-4d958aabaa43.png)

Thanks for the link on the current work (seems to validate the differences i saw from the current Docs page linked fix), i'll keep an eye on that !

**Comment by tbergeron** [comment]
It seems to be only a github token issue. It still works for me on Linux.

Try this https://github.com/shanalikhan/code-settings-sync/issues/408#issuecomment-335014416

**Comment by mijkami** [comment]
It seems unrelated as when i go into syncLocalSettings.json through "editing local settings" command, it shows the exact same settings than in VSCode, except it works in VSCode and not VSCodium.

Apparently some fixes are implemented in 3.3.0 of code-settings-sync (previous link updated https://github.com/shanalikhan/code-settings-sync/pull/859), i'll wait for an official release to see if it works.

**Comment by stripedpajamas** [comment]
Closing out this issue for now, as the extension's interaction with VSCodium is not under our control. If the extension developers have questions about integrating, they can raise a new issue.
