### ISSUE TITLE
Python automatic debugging configuration missing in VSCodium even though Python Extension installed?

### ISSUE THREAD

**Issue by paneerlovr** [VSCodium/vscodium#1801]
I'm using vscodium (version 1.85.1), I installed the official python extension (ms-python).

I'm looking to debug a python file using breakpoints that can I can do some simple type inspection.

When I click "run and debug", and then I click "show all automatic debug configurations", I expect to see python as a debug configuration, however it does not appear.

Would anyone know why?

I've tried setting the interpreter for my virtual environment using the command palette and it is set to the correct one.

**Comment by daiyam** [comment]
[`ms-python`](https://github.com/VSCodium/vscodium/blob/master/docs/extensions-compatibility.md)

**Comment by paneerlovr** [comment]
> https://github.com/VSCodium/vscodium/blob/master/docs/extensions-compatibility.md

I realize it says partial compatibility due to pylance being closed source but I’m wondering if I am doing something wrong to not even be able to see a debugger registered with the Ms-Python extension….

I’m just trying to figure out if that’s how it is, or if I’m doing something wrong.

thanks for responding

**Comment by paneerlovr** [comment]
I’m sorry to say, I downloaded vscode and the python extension worked as expected.  Maybe one day it will work in the future.  Python really benefits heavily from debugging extensions due to its loose typing in my opinion.

**Comment by daiyam** [comment]
> Maybe one day it will work in the future.

I will never since MS is restricting its popular extensions to Visual Studio Code.

**Comment by paneerlovr** [comment]
Maybe with all the telemetry data Microsoft collects from vscode, ChatGPT can help someone create a new extension that works as an alternative for vscodium.

**Comment by jangboolee** [comment]
Came here when I ran into the same issue with the following configurations:

* System OS: EndeavourOS
* VS Codium version: 1.85.2.24019-1
* Install method: `yay -S vscodium-bin`
* Python extension version: v2024.0.0

I thought it was strange that I couldn't debug a Python code on my personal Linux machine, while I was using the debugger with no issues on my work Windows machine also running VS Codium.

I tried replicating the working Python configuration from my Windows VS Codium machine on my Linux VS Codium by creating the following `launch.json` file, and it seems to work:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true,
        }
    ]
}
```

However, I do get a warning saying that the `python` configuration will be deprecated soon, and to replace it with `debugpy`. Unfortunately, when I try replacing it with `debugpy`, I get taken to the extensions marketplace with no search results, so I assume `debugpy` is not available on VS Codium. 

The above workaround should work for the time being, but it is unfortunately not a long-term solution, as it runs the risk of not working once the `python` configuration is deprecated.

**Comment by TechPro424** [comment]
Same issue for me, resolved using same workaround
OS: Windows 11
VSCodium version: 1.85.2.24019
Install method: 
```
scoop bucket add extras
scoop install extras/vscodium
```
Python extension version: v2024.0.1

**Comment by showgood163** [comment]
Now there are two solutions. 

First, adding the debugger configuration manually as @jangboolee said.
Second, use [python debugger extension](https://open-vsx.org/extension/ms-python/debugpy) to add configurations automatically.

**Comment by jangboolee** [comment]
> Second, use [python debugger extension](https://open-vsx.org/extension/ms-python/debugpy) to add configurations automatically.

This is great, thank you! The extension was not available on the VS Codium store last week, but it seems it was made available on 2024-02-14. This method is recommended, as it is more future-proof than relying on the `python` configuration that will soon be deprecated.

**Comment by Stampede** [comment]
> Now there are two solutions.
> 
> First, adding the debugger configuration manually as @jangboolee said. Second, use [python debugger extension](https://open-vsx.org/extension/ms-python/debugpy) to add configurations automatically.

I'm running VSCodium 1.87.2 via a Snap package on Linux. I disabled the old debugger  and installed this new one from the extension marketplace. I had it automatically create me a launch.json and left all the default values in the json; the name is "Python Debugger: Current File with Arguments."

Now I cannot create breakpoints in my code by clicking next to the line number. The breakpoints I had from the old debugger are still visible, and if I click them, they disappear but I cannot recreate them, or create any breakpoints for that matter.

Can anyone explain how to make new breakpoints?
