### ISSUE TITLE
Flathub verification

### ISSUE THREAD

**Issue by qoijjj** [VSCodium/vscodium#1803]
I'm reaching out on behalf of the maintainers of the [flatpak for vscodium](https://github.com/flathub/com.vscodium.codium/issues/273) to ask if the maintainers here would be interested in a simple step to add verification to the flathub build. This step enables additional user trust by giving a cryptographic "blessing" to the flatpak build. All it requires is to host a verification token in a file behind the vscodium.com TLD, as described here: https://docs.flathub.org/docs/for-app-authors/verification/#website

**Comment by daiyam** [comment]
I will look into it. Can you add me to that repo?

**Comment by qoijjj** [comment]
Thank you. I can't but [@noonsleeper](https://github.com/noonsleeper) can

**Comment by noonsleeper** [comment]
Hi @qoijjj & @daiyam, I also don't have those permissions to add people to the repo, but I create a petition to the flathub team [here](https://github.com/flathub/flathub/issues/4925) with this is only matter of time that you gain access to the repo =). From them, @daiyam you will be able to verify the package following the instructions after login on flathub.org

Btw, It's good to see that interest to make official the flatpak version, thanks @daiyam & @qoijjj

**Comment by noonsleeper** [comment]
Also, as a note @daiyam this is the same process to verify flatpak's codium-insiders, then you can start the verification process whenever you like =)

**Comment by daiyam** [comment]
I'm finishing the `1.86.0` release (I'm a bit late and testing for older linux) then I will do the alpine version and finally, I will look into flathub ;)

**Comment by noonsleeper** [comment]
Take your time, you have plenty of things on your plate =)

**Comment by rowbawts** [comment]
I'm happy to see this, could this be indicative of a move towards the Flatpak being an official distribution of this software?

**Comment by sr66139p** [comment]
Does this mean that the Flatpak is being taken on by the official project to some extent, or is it still an entirely separate project but with an endorsement from the official project? The vscodium website still just lists the Flatpak as unofficial

**Comment by daiyam** [comment]
I'm in the process to verify the flatpak. I've updated the site. But, the main maintainer of the flatpak will still be @noonsleeper 😉

**Comment by daiyam** [comment]
They have the blue checkmark. (https://flathub.org/apps/search?q=codium)
