### ISSUE TITLE
Error: EMFILE: too many open files, open '/tmp/yaourt-tmp-fabio/aur-vscodium/src/vscode/out-build/vs/base/browser/ui/selectBox/selectBoxCustom.js.map'

### ISSUE THREAD

**Issue by FabioNevesRezende** [VSCodium/vscodium#1808]
**Describe the bug**
Can't build Vscodium from AUR (arch user repository)

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
- haven't tried on VSCode

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
- Build this specific version from AUR

**Expected behavior**
Successful build of the application

**Desktop (please complete the following information):**
 - OS: Artix linux
 - x64
 - Version vscodium 1.85.2.24019-2  
 - AUR
 - no

**Additional context**
Error stack:
```

[14:02:42] Starting optimize-vscode ...
[14:02:48] 'minify-vscode' errored after 5.87 s
[14:02:48] Error: EMFILE: too many open files, open '/tmp/yaourt-tmp-fabio/aur-vscodium/src/vscode/out-build/vs/base/browser/ui/selectBox/selectBoxCustom.js.map'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
+++ error_function build
+++ ((  ! BASH_SUBSHELL  ))
++++ gettext 'A failure occurred in %s().'
+++ error 'A failure occurred in %s().' build
+++ local 'mesg=A failure occurred in %s().'
+++ shift
++++ gettext ERROR:
+++ printf '==> ERROR: A failure occurred in %s().\n' build
==> ERROR: A failure occurred in build().
++++ gettext Aborting...
+++ plainerr Aborting...
+++ plain Aborting...
+++ ((  QUIET  ))
+++ local mesg=Aborting...
+++ shift
+++ printf '    Aborting...\n'
    Aborting...
+++ exit 4
+ clean_up
+ local EXIT_CODE=4
+ ((  INFAKEROOT  ))
+ [[ -p '' ]]
+ ((  (EXIT_CODE == E_OK || EXIT_CODE == E_INSTALL_FAILED) && BUILDPKG && CLEANUP  ))
+ remove_deps
+ ((  ! RMDEPS  ))
+ return 0
+ exit 4
==> ERROR: Makepkg was unable to build vscodium.

```

**Comment by Andyloris** [comment]
I have the same problem, on the same platform. Has anybody found a solution ?
