### ISSUE TITLE
'VSCodium's tsserver was deleted by another application such as a misbehaving virus detection tool. Please reinstall VSCodium.'

### ISSUE THREAD

**Issue by secondl1ght** [VSCodium/vscodium#1809]
**Describe the bug**
After just updating VSCodium I opened the application and got the following error:
```
VSCodium's tsserver was deleted by another application such as a misbehaving virus detection tool. Please reinstall VSCodium.
```

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Update version
2. See error on startup

**Expected behavior**
No error.

**Screenshots**
![image](https://github.com/VSCodium/vscodium/assets/85003930/63689b19-7639-4641-a71d-ee14100286b6)

**Desktop (please complete the following information):**
- Ubuntu
- VSCodium v1.86.2

**Additional context**
Thanks

**Comment by ToMattBan** [comment]
Yup. Happens here too, and just in the last version "1.86.2"
In the previous version "1.85.2" it don't happen.

Going a little deeper into this, I discovered that the error is about the TS extension not founding this file here: "/usr/share/codium/resources/app/extensions/node_modules/typescript/lib/typescript.js". In fact, the 1.86.2 don't even have the "node_modules" folder, so it can't find the typescript stuff.

Hope it helps you guys to solve this problem!

**Comment by daiyam** [comment]
oh!

**Comment by daiyam** [comment]
I will have to check it...

**Comment by daiyam** [comment]
I'm pretty sure it's due to that line: https://github.com/VSCodium/vscodium/blob/f309a13e49054b50e3b7270cbd10987c51584cd0/.github/workflows/stable-linux.yml#L110

(done so we can support `glibc2.17`)

**Comment by daiyam** [comment]
@ToMattBan will do

**Comment by alsongard** [comment]
Same issue 
O.S  :  Kali Rolling
Version: 2024.1
@daiyam Great  Software

**Comment by yttiiz** [comment]
Hello @daiyam, i've got the same error after updating VSCodium 1.85.2 to 1.86.2
OS: Ubuntu 22.04.4 LTS
Thanks for work frérot.

**Comment by f-fusco** [comment]
I'm having the same issue on v1.86.2.

**Comment by daiyam** [comment]
@ToMattBan and others, a test version is available at https://github.com/VSCodium/vscodium/actions/runs/8012468841 (in the artifact [bin-x64](https://github.com/VSCodium/vscodium/actions/runs/8012468841/artifacts/1268270225))
First of all, do you have access? Can you test it? Thx

And, for me, the typescript service is now correctly working.

**Comment by 0xca551e** [comment]
@daiyam I was able to access the test version. I tested the AppImage from the bin-x64 artifact and it works fine :+1:

**Comment by daiyam** [comment]
[1.86.2.24054](https://github.com/VSCodium/vscodium/releases/tag/1.86.2.24054) is out and fix the issue.

**Comment by yttiiz** [comment]
Works fine now. Thanks so much for your reactivity @daiyam, you the best !

**Comment by bitstein** [comment]
Thank you @daiyam. How long does this usually take to enter the debs repository?

**Comment by daiyam** [comment]
> to enter the debs repository

What do you mean?

**Comment by bitstein** [comment]
> > to enter the debs repository
> 
> What do you mean?

This: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo

I currently cannot downgrade using it, so I will have to wait until it is updated. It’s not an issue, per se, so I thought it might be okay to ask here in this thread.

**Comment by ToMattBan** [comment]
@bitstein I just installed using the deb in the release section for now. It should update itself when launching new versions. No need to wait to install from the deb repos

**Comment by daiyam** [comment]
@ToMattBan No, on Linux, the automatic updates are disable due to some users clicking on the update (which resulted to other issues) when they should use the app manager. I've also assumed that those who are using the .deb, known how to update it themself.

**Comment by ToMattBan** [comment]
@daiyam Sorry, I build my sentence wrong. Didn't mean automatic update, but automatic search for updates. At least here, when I downgraded I got a update request in my update manager.

**Comment by martinbarilik** [comment]
> > > to enter the debs repository
> > 
> > 
> > What do you mean?
> 
> This: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo
> 
> I currently cannot downgrade using it, so I will have to wait until it is updated. It’s not an issue, per se, so I thought it might be okay to ask here in this thread.

i guess we'll have to wait ....

**Comment by daiyam** [comment]
Sorry, I didn't understand the issue.
There is the error when building the repo: `ERROR: Uploading artifacts as "archive" to coordinator... 413 Payload Too Large  id=6239193797 responseStatus=413 Payload Too Large status=413 token=glcbt-65`
@paulcarroty, maybe the Insiders version isn't needed in the repo? What do you think?

**Comment by daiyam** [comment]
It has been fixed.

For reference: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/issues/98
