### ISSUE TITLE
macOS Mojave blocks app

### ISSUE THREAD

**Issue by jrappen** [VSCodium/vscodium#181]
<img width="422" alt="image" src="https://user-images.githubusercontent.com/8577450/58715017-4a033c00-83c6-11e9-83f0-b7fcf62b9b62.png">

Running `brew cask install vscodium` results in macOS Mojave blocking the user from opening the app **by clicking the app icon**. Opening the app via the terminal works, however.

 - OS: macOS 10.14.5 (18F203)
 - Architecture: x64
 - Version: 1.34.0

**Comment by stripedpajamas** [comment]
See #161 for some details. I've updated the README to include instructions for first time opening on Mojave.

**Comment by jrappen** [comment]
@stripedpajamas maybe you could add the instructions as a post-install message for brew cask users?
