### ISSUE TITLE
Better Darwin binaries (App verification fails)

### ISSUE THREAD

**Issue by kunaltyagi** [VSCodium/vscodium#182]
**Describe the bug**
Installing 1.34 binary brings the prompt which says:
"""
“VSCodium” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.

Homebrew Cask downloaded this file <time> from github.com.
"""

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

This is different from unknown author error mentioned (on website with install via Homebrew instructions)

**To Reproduce**
1. brew cask install vscodium (Or download the darwin zip file from Github releases)
2. Start VSCodium
3. Let MacOS try to verify app

**Expected behavior**
No error

**Screenshots**
<img width="422" alt="Screen Shot 2019-06-01 at 12 09 20" src="https://user-images.githubusercontent.com/2657068/58743088-1ed02980-8466-11e9-85f3-0c0563e6eb74.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.5
 - Version 1.34

**Comment by stripedpajamas** [comment]
Hi @kunaltyagi -- this is a known issue (see #181 and #161) with Mojave. Please read the comments in #161 specifically for why we aren't fixing this right now.

The README in this repo has the updated Mojave instructions that need to happen for first run. I'll get the website updated as well.
