### ISSUE TITLE
Extension Tab doesn't load

### ISSUE THREAD

**Issue by mayronH** [VSCodium/vscodium#1825]
**Describe the bug**
I followed the [Extensions - Marketplace guide](https://github.com/VSCodium/vscodium/blob/master/docs/index.md#extensions-marketplace) to use vscode gallery and on version 1.87.0 the Extensions Tab loads endlessly even without searching, the Insider version works correctly. I also tried to reload disabling extensions.

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**Expected behavior**
The extension tab at least showing the installed extensions.

**Screenshots**
![image](https://github.com/VSCodium/vscodium/assets/38799771/105ed57b-3bc6-4cdf-ae48-1b6c487423d3)

**Desktop (please complete the following information):**
 - OS: Fedora 39
 - Architecture x86_64
 - Version Kernel 6.7.7-200.fc39.x86_64
 - App Manager DNF
 - Sandboxed no

**Comment by Sfinx** [comment]
Same here with v1.87.1, Ubuntu 22.04. Moreover - it lost (or does not show) the already installed extensions

**Comment by mayronH** [comment]
I think is related to the APC extension, funny that even with the > Developer: Reload With Extensions Disabled the bug still occurred.

After updating the bug was gone.

 https://github.com/drcika/apc-extension/issues/160

**Comment by Sfinx** [comment]
I do not use APC extension. The freshly installed v1.87.1 codium works too. The bug have been appeared during upgrade

**Comment by Sfinx** [comment]
My bad, monkey patch was accidentally enabled. Disabling it fixes the "bug" ;)

**Comment by daiyam** [comment]
Have you reported the issue to the APC extension?
Any PR is welcome to help to fix the issue, if needed.

**Comment by mayronH** [comment]
Looking at the issues seems to be a known and already fixed problem.
I didn't try to look at to the APC Extension before because of the Reload With Extensions Disabled.

Sorry for wasting your time.
