### ISSUE TITLE
1.87.1.24068 failed to apply binary-name.patch

### ISSUE THREAD

**Issue by Brli** [VSCodium/vscodium#1826]
**Describe the bug**
During building for Linux x86_64, using aur/vscodium's recipe

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**

1. git clone https://aur.archlinux.org/vscodium.git
2. cd vscodium
3. mkarchpkg (setup and build under clean chroot with dependencies)
4. error:

```
yarn config v1.22.21
success Set "cache-folder" to "/build/vscodium/src/yarn-cache".
Done in 0.02s.
patching file product.json
291s/'default': true/'default': false/
217s/'default': TelemetryConfiguration.ON/'default': TelemetryConfiguration.OFF/
150s/'default': true/'default': false/
applying patch: ../patches/binary-name.patch
applying patch: ../patches/brand.patch
applying patch: ../patches/build-version.patch
applying patch: ../patches/crash-reporter.patch
applying patch: ../patches/disable-cloud.patch
applying patch: ../patches/ext-from-gh.patch
applying patch: ../patches/feat-announcements.patch
applying patch: ../patches/fix-build-linux.patch
applying patch: ../patches/fix-eol-banner.patch
applying patch: ../patches/merge-user-product.patch
applying patch: ../patches/ppc64le-support.patch
applying patch: ../patches/remove-mangle.patch
applying patch: ../patches/report-issue.patch
applying patch: ../patches/update-cache-path.patch
applying patch: ../patches/update-msi.patch
applying patch: ../patches/update-windows.patch
applying patch: ../patches/use-github-pat.patch
applying patch: ../patches/win7.patch
applying patch: ../patches//binary-name.patch
error: patch failed: build/gulpfile.vscode.js:289
error: build/gulpfile.vscode.js: patch does not apply
error: patch failed: src/vs/platform/native/electron-main/nativeHostMainService.ts:351
error: src/vs/platform/native/electron-main/nativeHostMainService.ts: patch does not apply
failed to apply patch ../patches//binary-name.patch
```

**Expected behavior**

Pass, and build continues.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Architecture x64
 - Version 1.87.1.24068 and 1.87.0.24060

**Additional context**

**Comment by daiyam** [comment]
Have you tried with `makepkg -sr` as indicated in the `BUILDING` file?

**Comment by Brli** [comment]
> Have you tried with `makepkg -sr` as indicated in the `BUILDING` file?

It's irrelevant anyway

1. If it's not clean build, the patch would failed even earlier

2. Patch things require no dependencies, it's just a base-devel package that do inline replacement to source code, aka. text file.

**Comment by daiyam** [comment]
Can you give us the log of the build, at least with the output of `MS_COMMIT`?

Here the log of the test build before the push to the AUR (https://github.com/VSCodium/vscodium/actions/runs/8207306570/job/22449034203#step:3:691)

**Comment by Brli** [comment]
okay, I see what's happening here:

check out the first few lines:

```
applying patch: ../patches/binary-name.patch
```

and check the failure lines:
```
applying patch: ../patches//binary-name.patch
error: patch failed: build/gulpfile.vscode.js:289
```

it just re-applying the patch again.

**Comment by Brli** [comment]
ok, so it seems to be that some capitalized environment variables are presumed to be exported by the docker mechanism?

where if not a docker, they don't exist?

**Comment by daiyam** [comment]
Please post your log.
