### ISSUE TITLE
Windows - Uninstaller leaves behind files and registry keys

### ISSUE THREAD

**Issue by o-l-a-v** [VSCodium/vscodium#1828]
**Describe the bug**

On Windows, the VSCodium EXE and MSI uninstaller leaves behind the `%APPDATA%\VSCodium` directory.

The EXE uninstaller also leaves behind a registry key in `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\AppListBackup`.

This is unexpected, especially as the EXE uninstaller asks:

```
---------------------------
VSCodium Uninstall
---------------------------
Are you sure you want to completely remove VSCodium and all of its components?
---------------------------
Yes   No   
---------------------------
```

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

*^ I don't see how the behavior of VSCodium vs. VSCode matters here. Fork or not: Uninstaller should remove everything,  unless user is promted about keeping preferences and configuration.*

**Please confirm that the issue/resolution isn't already documented**
- [*] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**

1. Download latest VSCodium for Windows from [releases](https://github.com/VSCodium/vscodium/releases).
   * EXE or MSI doesn't really matter.
2. Install VSCodium.
3. Uninstall VSCodium using [Geek Uninstaller](https://geekuninstaller.com/download).
4. After VSCodium uninstaller is done, Geek Uninstaller will find mentioned leftovers.

**Expected behavior**

Uninstaller should remove everything, especially when it explicitly asks "remove VSCodium and all of its' components"?

**Screenshots**

After uninstall of EXE that I've had installed for a while:

<img width="1268" alt="VSCodium - 240310 - Uninstaller leaves a lot behind" src="https://github.com/VSCodium/vscodium/assets/6450056/451cd63c-a637-4b93-b8c8-5951fa6e8f90">

After clean install and uninstall of the EXE:

<img width="1247" alt="VSCodium - 240310 - Uninstaller leaves a lot behind - EXE" src="https://github.com/VSCodium/vscodium/assets/6450056/e3713422-4dde-49bd-850a-62883e0950a9">

After clean install and uninstall of the MSI:

<img width="581" alt="VSCodium - 240310 - Uninstaller leaves a lot behind - MSI" src="https://github.com/VSCodium/vscodium/assets/6450056/04939c92-2cfd-4539-9a18-b356a206f13b">

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 (22631.3155)
 - Architecture: x64
 - Version: v1.87.1.24068
 - App Manager: Manual installation, uninstall triggered by Geek Uninstaller.
 - Sandboxed: No

**Additional context**

**Comment by o-l-a-v** [comment]
**any comment**

**Comment by daiyam** [comment]
I see that as the expected behaviour.
