### ISSUE TITLE
VSCodium unable to find header files in C

### ISSUE THREAD

**Issue by soumyaDghosh** [VSCodium/vscodium#1834]
**Describe the bug**

I have added the necessary folders in includepaths, but still, vscodium is not able to find the header. Even though, vscode is showing it properly.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Write this code in a file and save it. 
https://github.com/snapcore/snapd-glib/blob/master/examples/snap-glib.c
2. VSCodium will show errors

**Expected behavior**
VSCodium should be able to look into the header files.

**Screenshots**

![Screenshot from 2024-03-24 23-56-01](https://github.com/VSCodium/vscodium/assets/72045785/8443caf9-b8b3-47ec-9a30-bd37a7adea7c)
![Screenshot from 2024-03-24 23-55-23](https://github.com/VSCodium/vscodium/assets/72045785/40adc3c2-7baa-461a-b6bf-c409518b27eb)

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - Architecture: x64
 - Version: 1.86.2
 - App Manager: Snap
 - Sandboxed: Snap

**Additional context**
I found that there is an extension for C/C++ that I can't install in vscodium. The id of that extension is `ms-vscode.cpptools`. Probably this extension can fix everything.

**Comment by anuragvohraec** [comment]
Facing same issue

**Comment by anuragvohraec** [comment]
Ok After installing `CMake Tools` from `ms-vscode` solved issue for me. I had to relaunch `codium` a couple of times after installation as per popups I received. But it worked.
