### ISSUE TITLE
Release 1.35.0 is missing AppImage

### ISSUE THREAD

**Issue by JayAndCatchFire** [VSCodium/vscodium#184]
[The latest release](https://github.com/VSCodium/vscodium/releases/tag/1.35.0), while tagged, is missing binaries.

**Comment by stripedpajamas** [comment]
Looks like a transient problem during build. I've restarted the builds.

**Comment by stripedpajamas** [comment]
MS has moved from Node 8 to Node 10. Updating our build scripts b6b51ba5105b046348c2bb50ab2b3256b0fd3712

**Comment by antoniofagardo** [comment]
It seems like the darwin binaries has still not been generated, is it also part of the pipeline ?

**Comment by stripedpajamas** [comment]
The Mac install is having a different issue. I'm troubleshooting it -- you can have a look at the build logs here to see: https://travis-ci.com/VSCodium/vscodium/jobs/206168238

**Comment by tyu1996** [comment]
The AppImage binary is also missing in v1.35. Is there any issue found during the AppImage building process?

**Comment by eladcandroid** [comment]
brew cask upgrade vscodium
didn't upgrade to v1.35..

**Comment by stripedpajamas** [comment]
Brew cask downloads the Mac binary which does not exist yet. We are working on it.

**Comment by stripedpajamas** [comment]
Mac build has since succeeded, I will update the cask. 

AppImage failed for an unknown reason, I will investigate.

**Comment by antoniofagardo** [comment]
brew cask upgrade vscodium worked !

Thank you for your help

**Comment by JayAndCatchFire** [comment]
It looks like the AppImage version is still missing from the binaries for 1.35.0.  This doesn't affect me personally as I needed a deb file for arm64.  Should I close this issue or leave it open for the AppImage version?

**Comment by ntilotta** [comment]
I'm on Kubuntu 19.04, sudo dpkg -i codium_1.35.0-1560135863_amd64.deb

(Reading database ... 223914 files and directories currently installed.)
Preparing to unpack codium_1.35.0-1560135863_amd64.deb ...
Unpacking codium (1.35.0-1560135863) ...
dpkg: error processing archive codium_1.35.0-1560135863_amd64.deb (--install):
 trying to overwrite '/usr/share/pixmaps/com.visualstudio.code.oss.png', which is also in package vscodium 1.34.0-1558029460
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 codium_1.35.0-1560135863_amd64.deb

**Comment by JayAndCatchFire** [comment]
@ntilotta that happened to me as well. This is because the package name changed from `vscodium` to `codium` in this release (#176, #187). The solution is to uninstall the old version before installing the new version.

**Comment by stripedpajamas** [comment]
@JayAndCatchFire let's leave this open to track the missing AppImage.

**Comment by tyu1996** [comment]
Is it related to recent changing name from vscodium to codium? What if rename all the 'vscodium' to 'codium' in VSCodium-AppImage-Recipe.yml?

**Comment by stripedpajamas** [comment]
It is related to the name change, but I'm not sure which places should be changed to `codium`.

@probonopd can you help?

**Comment by probonopd** [comment]
This line needs to be changed for sure:

https://github.com/VSCodium/vscodium/blob/81ef7c6d8f1e835f8fd3e97447c611555d07b590/VSCodium-AppImage-Recipe.yml#L20

I don't know about these lines, they need to be changed in case the filenames have changed from `vscodium` to `codium`:

https://github.com/VSCodium/vscodium/blob/81ef7c6d8f1e835f8fd3e97447c611555d07b590/VSCodium-AppImage-Recipe.yml#L23-L35

**Comment by tyu1996** [comment]
I did an edit on the recipe file and pull a request. If it works on Travis build, this issue can be marked as solved and closed.

**Comment by stripedpajamas** [comment]
Fixed by @tyu1996 in #203 -- AppImage should return on next release.
