### ISSUE TITLE
The website seems to be down

### ISSUE THREAD

**Issue by aapeliv** [VSCodium/vscodium#1840]
And is displaying a domain parking page.

**Comment by firednerve** [comment]
The last instance of the website displaying as normal on the Wayback machine is 27 March, https://web.archive.org/web/20240201000000*/vscodium.com

**Comment by daiyam** [comment]
@PalinuroSec I've just sent you an email about the issue 😉

**Comment by snowkluster** [comment]
The repo also seems to have been taken down

```
E: Failed to fetch https://download.vscodium.com/debs/dists/vscodium/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://download.vscodium.com/debs vscodium InRelease' is no longer signed.
```

I am at my home network, and all my other Ubuntu boxes seem to working perfectly, can anyone confirm ?

**Comment by daiyam** [comment]
Ya, the domain name is down. I've sent an email to @PalinuroSec which manage it... But, we are saturday evening, so the issue can take fews days to resolve. Sorry about that!

**Comment by theLockesmith** [comment]
@snowkluster this is what brought me here as well. I imagine the website and repo issues are related.

**Comment by githubuser6000** [comment]
@theLockesmith  The repo is under the domain (as a subdomain) so expected, I guess. 
I would like to politely suggest that the repo be added to fedora copr for the rpm format. Would be sweet for such a widely used community package.

**Comment by Xmetalfanx** [comment]
glad i am not losing it ... last night I reinstalled (due to the xz thing) my Tumbleweed install and in my scripts to reinstall stuff my way, vscodium was the only part that wasn't working (i do see on the gitlab page the instructions did change a TAD versus what I had.

**Comment by Xmetalfanx** [comment]
> Ya, the domain name is down. I've sent an email to @PalinuroSec which manage it... But, it's saturday evening, so the issue can take fews days to resolve. Sorry about that!

no problem  while i know not everyone "celebrates it" I also know its a Holiday this Sunday.   IT will be taken care, i am sure .. I think i may have an old rpm file of it here somewhere i can install .. so no big deal
