### ISSUE TITLE
windows.net connection

### ISSUE THREAD

**Issue by daslicht** [VSCodium/vscodium#1843]
Why is vscodium trying to connect to windows.net ?

**Comment by daiyam** [comment]
Can your provide logs with all your extensions disabled?

**Comment by daslicht** [comment]
ahh good hint! I havent cionsidered that it coudl be a extension. Will do

**Comment by daslicht** [comment]
these sconnection attempts do I get without plugins:
https://imgur.com/a/Kkf44jy

**Comment by daslicht** [comment]
these sem to be normal ? no?

**Comment by daiyam** [comment]
Yes, vercel/now are the urls for the update process. It also connects to github to get the latest VSCodium announcements.
