### ISSUE TITLE
Codium-server does not initialize the webui

### ISSUE THREAD

**Issue by sodomon2** [VSCodium/vscodium#1844]
**Describe the bug**

Hi, I was trying to mount codium to use it in the browser with its reh version, but when I run the initialization script I get only a forbidden
it never generates neither the `webui` nor the token, I tried both the glibc version and the alpine version (my main system), this problem is something that only happened to me with `codium-server`, when trying [code-server](https://github.com/coder/code-server) or [openvscode-server](https://github.com/gitpod-io/openvscode-server/) both work as they should.

i was checking and apparently codium-server has some files and directories that are not generated
for example the directories `out/code`, `out/editor` and other files, I don't know if it is an error in the compilation or it is an internal problem because in the same `code-oss-server` I also get the same error.

**Please confirm that this problem is VSCodium-specific**
No, the problem also happens in vscode

**Please confirm that the issue/resolution isn't already documented**
It is not

**To Reproduce**
download any version of vscodium-reh and run it
**Expected behavior**

**Screenshots**
![imagen](https://github.com/VSCodium/vscodium/assets/49420637/d172896d-de4a-450b-b2bc-39a521a361cb)

**Desktop (please complete the following information):**
 - OS: Alpine Linux Edge
 - Architecture: x65
 - Version 1.88.0.24096
 - App Manager: APK
 - Sandboxed: no

**Comment by daiyam** [comment]
What you want is `remote/web` in the source of VSCode while REH is only `remote`
VSCodium doesn't provide the feature, yet. Fell free to make a PR.

**Comment by sodomon2** [comment]
Is there no way to support it?
From what I saw vscodium does generate the missing files and directories but does not organize them.

**Comment by daiyam** [comment]
The REH-web archives are availables.

**Comment by chatranjan7865** [comment]
![image](https://github.com/user-attachments/assets/f28c8fdf-34a2-4bed-b698-573607db2ad5)

 i have download vscodium vscodium-reh-linux-x64-1.91.0.24190 if you guys can see my screen you will able to know i am facing forbidden error, Can anyone guide me how i can open this in browser

**Comment by daiyam** [comment]
Don't provide a token and follow the new url given in the output (with a new token).

**Comment by chatranjan7865** [comment]
![image](https://github.com/user-attachments/assets/6561fa66-b89c-4401-bc5a-e4ca0b24ca37)

 I am really sorry, but i couldn't get any URL please see my screenshot, if you don't mine do you have process to setup and vscodium. if you have please share to me it will be great help

**Comment by chatranjan7865** [comment]
I couldn't get any Url printed in console like above you mention but i tried to pass token from url  as you can see in screenshot then i got **Not Found**
![image](https://github.com/user-attachments/assets/4eb1d3b7-a240-4494-8286-bc0a4694feb2)
i have downloaded this from below url :
https://github.com/VSCodium/vscodium/releases?expanded=true&page=2&q=1.89.1.24130
vscodium-reh-linux-x64-1.91.0.24190

Can you guide me how i can resolve this **Not Found**

**Comment by chatranjan7865** [comment]
if anyone know how to to fix my above issues

**Comment by chatranjan7865** [comment]
i have resolved above issues. But i need one more clarification
if i want to open vs in sandbox environment how i can do that
