### ISSUE TITLE
Cant move window

### ISSUE THREAD

**Issue by Musta1song** [VSCodium/vscodium#1850]
Type: <b>Bug</b>

I cant move the VScodium window. I can only change its size 

VSCodium version: VSCodium 1.88.1 (f81c3ddb8c04073b36844c4102c939c634b770f5, 2024-04-11T18:30:34.468Z)
OS version: Linux x64 6.8.0-76060800daily20240311-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics (12 x 3106)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|7.09GB (2.57GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-rxjs-ngrx|ang|1.1.2
ng-template|Ang|17.3.0
vscode-intelephense-client|bme|1.10.4
vscode-tailwindcss|bra|0.10.2
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.0
angular-schematics|cyr|6.9.0
vscode-eslint|dba|2.4.4
php-intellisense|fel|2.3.14
vscode-firefox-debug|fir|2.9.1
angular-essentials|Gyd|0.2.0
javascript-essentials|Gyd|0.1.1
typescript-essentials|Gyd|1.1.2
headwind|hey|2.0.0
Angular2|joh|16.0.1
php-namespace-resolver|Meh|1.1.9
csdevkit|ms-|1.4.2
csharp|ms-|2.18.15
vscode-dotnet-runtime|ms-|2.0.3
debugpy|ms-|2024.4.0
python|ms-|2024.2.1
cpptools|ms-|1.19.3
symfony-code-snippets|nad|2.1.1
symfony-extension-pack|nad|1.2.0
twig-code-snippets|nad|2.0.0
php-docblocker|nei|2.7.0
angular-component-extractor|PKi|0.1.0
vscode-yaml|red|1.14.0
vscode-status-bar-format-toggle|tom|3.2.0
volar|Vue|2.0.7
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details>

**Comment by daiyam** [comment]
Can you provide the following infos?
 - OS: [e.g. Mac OS, Ubuntu 20.04, etc]
 - Architecture [e.g. x64, ia32, arm64]
 - Dispay server [e.g. X11, Wayland]
 - App Manager [e.g. Winget, Homebrew, Snap, AUR, RPM, Nix, ...]
 - Sandboxed [e.g. no, Flatpak, Snap]

**Comment by daiyam** [comment]
Same issue as #1842
