### ISSUE TITLE
GitHub authentication needs to be done all the time

### ISSUE THREAD

**Issue by lucasmz-dev** [VSCodium/vscodium#1855]
This is probably a duplicate, I feel like people would've complained; but for some reason I could not find anything.

When using the GitHub extension, I am asked to authenticate / open the browser multiple times, this was also an issue before I knew this project and was using VS Code built for Flatpak, but not when I tried official binaries. This is quite annoying as it happens every time I need to sync, and such. (It also might happen with GitLab, but haven't tested)

Is this normal? Is there a workaround?

**Comment by daiyam** [comment]
> but not when I tried official binaries

Also flatpak?

**Comment by daiyam** [comment]
> Is this like a Flatpak issue?

Maybe. Here, I think, a related issue #1846

It would great if you can test the `.rpm` or `.AppImage` or other packages...

**Comment by lucasmz-dev** [comment]
Yeah... it seems to work with the officially built packages... weird. The nice thing I had with the Flatpak build is that it didn't have Wayland issues for some reason, meanwhile .rpm does, so I'm going to just use X11 for now. Nvidia's fault probably DW. I have had issues with Signal as well so.
