### ISSUE TITLE
SHA1 and SHA256 Hashes for 1.88 Debian .deb AMD64 Not Matching

### ISSUE THREAD

**Issue by ganakee** [VSCodium/vscodium#1859]
**Describe the bug**
I downloaded (twice) the debian binary.  codium_1.88.1.24104_amd64.deb  and corresponding SHA1 and SHA256.
Neither hash matches for me. (2024-04-26 12:10PM)

**To Reproduce**
1. Go to the 1.88 releases page https://github.com/VSCodium/vscodium/releases/tag/1.88.1.24104
2. Select  codium_1.88.1.24104_amd64.deb  https://github.com/VSCodium/vscodium/releases/download/1.88.1.24104/codium_1.88.1.24104_amd64.deb
3. Download.
4. Use favorite hash to hash file and check against the posted SHA1 and SHA256. 
I get 
SHA1 = `e4bf4a3d906d3acdbb4f5d6e3c1f14aa3aa3b23b`    and
SHA256 = `a3b561c976cfead9bd5b844d80fc38e1da21527ca61d0d438e3685305f521c27`    

The posted SHA1 = `a8c6f3e8828688e5713bd614ef93f7970ff906a1`  codium_1.88.1.24104_amd64.deb
The posted SHA256 =` fb0c9c8d883b00e94a9f94d0ea1631d9ab5a841e2e8b280a2395787de9deab0d`  codium_1.88.1.24104_amd64.deb

NOTE: the file size also appears incorrect. I get 92.5MB (92,527,760 bytes) but the site lists 88.2MB.

**Expected behavior**
The hashes should match for a correct download.

**Comment by daiyam** [comment]
Here what I get from a freshly downloaded `codium_1.88.1.24104_amd64.deb`

```
❯ shasum -a 256 codium_1.88.1.24104_amd64.deb
fb0c9c8d883b00e94a9f94d0ea1631d9ab5a841e2e8b280a2395787de9deab0d  codium_1.88.1.24104_amd64.deb
❯ shasum -a 1 codium_1.88.1.24104_amd64.deb
a8c6f3e8828688e5713bd614ef93f7970ff906a1  codium_1.88.1.24104_amd64.deb

```

**Comment by ganakee** [comment]
Thank you for checking.  Closed.

I am puzzled but this must be my error somehow. I reran the CLI `shasum` and correctly get:
```
$ shasum -a 256 codium_1.88.1.24104_amd64.deb
fb0c9c8d883b00e94a9f94d0ea1631d9ab5a841e2e8b280a2395787de9deab0d  codium_1.88.1.24104_amd64.deb
$ shasum -a 1 codium_1.88.1.24104_amd64.deb
a8c6f3e8828688e5713bd614ef93f7970ff906a1  codium_1.88.1.24104_amd64.deb
```
I use GtkHash normally (a GUI hash). Odd. That also now works.
( I went back and again tried the file. I have no idea how the hashes above occurred. Puzzling. I verified multiple times that I used the correct file. Odd.)
