### ISSUE TITLE
Crash open folder with Wayland and xdg-desktop-portal-wlr

### ISSUE THREAD

**Issue by AgostinoA** [VSCodium/vscodium#1861]
**Describe the bug**
Open folder, Open file and crash

Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to 'Open Folder/Open File'

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Architecture: arm64
 - Version [e.g. 1.33.0]
 - App Manager Appimage
 - Sandboxed Appimage

**Comment by NeoKaios** [comment]
@AgostinoA did you manage to fix the issue ? If so, how ?
I have the same issue when launching from AppImage, the problem disappear with a .deb install tho
