### ISSUE TITLE
"--unity-launch" flag in Linux desktop file breaks file opening from the outside

### ISSUE THREAD

**Issue by xalt7x** [VSCodium/vscodium#1865]
**Describe the bug**
Since v1.89.0.24126, when Linux user tries to open a file from external program (e.g., file manager), VSCodium doesn't open a file but instead it simply launches a new VSCodium window.  
VSCodium's Linux desktop file still has a recently [removed](https://github.com/microsoft/vscode/commit/0da22a226000adc62cf7b8a83b045668fb8a9296) "[--unity-launch](https://github.com/microsoft/vscode/issues/202545)" flag.  
When I launch VSCodium with that flag, I receive such message in a terminal:

> Warning: 'unity-launch' is not in the list of known options, but still passed to Electron/Chromium.

And like any other non-existing flag, it breaks opening files from the outside (e.g., `codium --unity-launch launch ~/.bash_history`).

**Please confirm that this problem is VSCodium-specific**
- [*] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [*] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. On Linux desktop open any file manager (e.g., KDE Dolphin)
2. Right click on any text file
3. Choose "Open With VSCodium"
4. New VSCodium window without requested file is launched

**Expected behavior**
Requested file is opened in VSCodium

**Desktop (please complete the following information):**
 - OS: Fedora 40
 - Architecture: x64
 - Version: v1.89.0.24126
 - App Manager: RPM
 - Sandboxed: no

**Additional context**
The problem is reproducible with different desktops (GNOME 46, KDE Plasma 6.0) so I presume it affects all Linux users. If possible, please make a new release with the fix to avoid duplicated reports for downstream packagers (Flathub, AUR etc.)

**Comment by daiyam** [comment]
Not yet complete. It has to be released.

**Comment by ipkpjersi** [comment]
It works for me again with https://github.com/VSCodium/vscodium/releases/tag/1.89.0.24127 so I'm pretty sure this can be closed now.

**Comment by resu-xuniL** [comment]
> It works for me again with https://github.com/VSCodium/vscodium/releases/tag/1.89.0.24127 so I'm pretty sure this can be closed now.

No , don't close please !
It doesn't work neither with that version on my machine nor other (see here : https://bbs.archlinux.org/viewtopic.php?id=295570).
Had to downgrade for version 1.88.1.24104-1

**Comment by daiyam** [comment]
I forgot about Arch!

**Comment by resu-xuniL** [comment]
How dare you ?! ;) ;) ;)

**Comment by ChocoTaco1** [comment]
Please fix

**Comment by daiyam** [comment]
`vscodium` and `vscodium-git` have been fixed.
Since I'm not co-maintainer for `vscodium-bin`, I'm not able to do it. I've asked the maintainer but no answer.
