### ISSUE TITLE
Releases 1.89.0.24127 doesn't contains Mac OS binary

### ISSUE THREAD

**Issue by sendaoYan** [VSCodium/vscodium#1868]
**Describe the bug**
Releases 1.89.0.24127 doesn't contains macos binary

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to [Releases 1.89.0.24127 web](https://github.com/VSCodium/vscodium/releases/tag/1.89.0.24127)
2. search dmg

**Expected behavior**
[1.88.1.24104](https://github.com/VSCodium/vscodium/releases/tag/1.88.1.24104) has contains dmg binary:

![image](https://github.com/VSCodium/vscodium/assets/24123821/a5f112da-f9d2-40f6-818b-39b098b51ae6)

**Screenshots**
![image](https://github.com/VSCodium/vscodium/assets/24123821/211a3944-0604-4147-8176-7b71e70ad589)

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS, Ubuntu 20.04, etc] MacOS
 - Architecture [e.g. x64, ia32, arm64] aarch64
 - Version [e.g. 1.33.0] Releases 1.89.0.24127
 - App Manager [e.g. Winget, Homebrew, Snap, AUR, RPM, Nix, ...] dmg
 - Sandboxed [e.g. no, Flatpak, Snap] no

**Comment by wanderingmeow** [comment]
During the build process, an error occurred due to an expired codesign certificate (CSSMERR_TP_CERT_EXPIRED). The build logs can be found here: https://github.com/VSCodium/vscodium/actions/runs/8962504270/job/24611461953#step:9:38.

It appears that the developer certificate from @stripedpajamas to sign the software has expired, or there is something wrong with the CI configuration, but I've checked and it doesn't seem to have changed recently. 

Reference: https://forums.developer.apple.com/forums/thread/712043

**Comment by daiyam** [comment]
Yep, I've been pondering what to do since Sunday... (logs added in the Insiders version).
But I thinking I've already seen the `CSSMERR_TP_CERT_EXPIRED` error but I can't be sure.

Renew the certificate / Get an official from Apple.
What happens when the certificate change? Broken update?

**Comment by daiyam** [comment]
Hi, the latest Insiders version is notarized.
Can you test it? https://github.com/VSCodium/vscodium-insiders/releases/tag/1.90.0.24153-insider

By the way, you will need to manually update since the certificate has been changed (the update process fails the verification of the downloaded app).

**Comment by sendaoYan** [comment]
> Hi, the latest Insiders version is notarized. Can you test it? https://github.com/VSCodium/vscodium-insiders/releases/tag/1.90.0.24153-insider
> 
> By the way, you will need to manually update since the certificate has been changed (the update process fails the verification of the downloaded app).

The new version report a faillure when install the chinese language: `End of central directory record signature not found. Either not a zip file, or file is truncated.`

![image](https://github.com/VSCodium/vscodium/assets/24123821/4b4fe0b2-6929-4dfc-856c-4f4fd85f5eb6)

**Comment by daiyam** [comment]
> `End of central directory record signature not found. Either not a zip file, or file is truncated.`

Same error for any extension...

I need to check on another os since the error seems like to be about a bad zip file.

**Comment by jeanp413** [comment]
> End of central directory record signature not found. Either not a zip file, or file is truncated.

I was about to create an issue about this, it's an open-vsx bug already reported https://github.com/eclipse/openvsx/issues/922 and merged https://github.com/eclipse/openvsx/pull/928 but not deployed

@daiyam you could skip the signature verification for this release here https://github.com/gitpod-io/openvscode-server/commit/3c72b12e4414a4691f7a19cdfae262b429270ee9

**Comment by daiyam** [comment]
> @daiyam you could skip the signature verification for this release here [gitpod-io/openvscode-server@3c72b12](https://github.com/gitpod-io/openvscode-server/commit/3c72b12e4414a4691f7a19cdfae262b429270ee9)

Ok, so it's a new thing for `1.90`. Thanks for the update.

**Comment by daiyam** [comment]
@jeanp413 I've done the patch in https://github.com/VSCodium/vscodium/pull/1915

**Comment by waja** [comment]
Hmm ... I can't find any arm dmg at https://github.com/VSCodium/vscodium/releases/tag/1.90.0.24158

**Comment by daiyam** [comment]
> Hmm ... I can't find any arm dmg at https://github.com/VSCodium/vscodium/releases/tag/1.90.0.24158

Yep. The job is failing, I'm working on it (https://github.com/VSCodium/vscodium/actions/runs/9405828286)

**Comment by daiyam** [comment]
> > Hmm ... I can't find any arm dmg at https://github.com/VSCodium/vscodium/releases/tag/1.90.0.24158
> 
> Yep. The job is failing, I'm working on it (https://github.com/VSCodium/vscodium/actions/runs/9405828286)

The macOS versions are available for x86 and arm
