### ISSUE TITLE
Failed to open file/folder in KDE Plasma Dolphin

### ISSUE THREAD

**Issue by playgithub** [VSCodium/vscodium#1872]
**Describe the bug**
Failed to open file/folder in KDE Plasma Dolphin by "Open with VSCodium"/"Open Folder With" in the context menu of Dolphin

**Please confirm that this problem is VSCodium-specific**
not tested for vscode

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Open Dolphin
2. "Open with VSCodium"/"Open Folder With" in the context menu of Dolphin
3. VSCodium launches sucessfully, but no file or folder opens

**Expected behavior**
The file/folder to be opened should be opened.

**Desktop (please complete the following information):**
 - OS: KDE Plasma 6.0.4
 - Architecture x64
 - Version 1.89.1
 - App Manager AUR
 - Sandboxed no

**Comment by daiyam** [comment]
I've just asked to be co-maintainer of the AUR `vscodium-bin` so that I can push the patch.

**Comment by xalt7x** [comment]
I believe it's a duplicate of #1865 , and also Arch AUR specific. [vscodium](https://aur.archlinux.org/packages/vscodium) and [vscodium-bin](https://aur.archlinux.org/packages/vscodium-bin) maintainers should sync their desktop files with #1866 .

---

Meanwhile, in KDE Plasma it's really easy to fix.   
Just  launch KDE Menu Editor (`kmenuedit`), find VSCodium launcher and remove "`--unity-launch`" flag.

**Comment by playgithub** [comment]
It must be duplicated.
