### ISSUE TITLE
Release 1.35.0: Problem connecting to marketplace

### ISSUE THREAD

**Issue by muideenlawal** [VSCodium/vscodium#188]
After upgrading vscodium from v1.33.1 to v1.35.0, I can't connect to the marketplace any longer.

Also, the list of installed extensions has disappeared from the *Extension* tab.
Here is the message I have (see below) on the *Extension* tab;

`We cannot connect to the Extensions Marketplace at this time, please try again later.`

**Note: I am not behind any proxy.**

**Comment by stripedpajamas** [comment]
What OS are you running VSCodium on?

**Comment by muideenlawal** [comment]
> What OS are you running VSCodium on?

Running on MacOS.

**Comment by stripedpajamas** [comment]
I'm also on MacOS 1.35.0 and do not have trouble accessing the marketplace or seeing installed extensions. Can you paste your `product.json` here? It should be located here: `/Applications/VSCodium.app/Contents/Resources/app/product.json`

**Comment by muideenlawal** [comment]
> I'm also on MacOS 1.35.0 and do not have trouble accessing the marketplace or seeing installed extensions. Can you paste your `product.json` here? It should be located here: `/Applications/VSCodium.app/Contents/Resources/app/product.json`

Here is the content of my `product.json` file:

`{
  "nameShort": "VSCodium",
  "nameLong": "VSCodium",
  "applicationName": "codium",
  "dataFolderName": ".vscode-oss",
  "win32MutexName": "vscodium",
  "licenseName": "MIT",
  "licenseUrl": "https://github.com/Microsoft/vscode/blob/master/LICENSE.txt",
  "win32DirName": "VSCodium",
  "win32NameVersion": "VSCodium",
  "win32RegValueName": "VSCodium",
  "win32AppId": "{{E34003BB-9E10-4501-8C11-BE3FAA83F23F}",
  "win32x64AppId": "{{D77B7E06-80BA-4137-BCF4-654B95CCEBC5}",
  "win32UserAppId": "{{C6065F05-9603-4FC4-8101-B9781A25D88E}",
  "win32x64UserAppId": "{{2E1F05D1-C245-4562-81EE-28188DB6FD17}",
  "win32AppUserModelId": "Microsoft.VSCodium",
  "win32ShellNameShort": "V&SCodium",
  "darwinBundleIdentifier": "com.visualstudio.code.oss",
  "linuxIconName": "com.visualstudio.code.oss",
  "licenseFileName": "LICENSE.txt",
  "reportIssueUrl": "https://github.com/Microsoft/vscode/issues/new",
  "urlProtocol": "vscodium",
  "extensionAllowedProposedApi": ["ms-vscode.references-view", "ms-vsliveshare.vsliveshare"],
  "extensionAllowedBadgeProviders": ["api.bintray.com", "api.travis-ci.com", "api.travis-ci.org", "app.fossa.io", "badge.fury.io", "badge.waffle.io", "badgen.net", "badges.frapsoft.com", "badges.gitter.im", "badges.greenkeeper.io", "cdn.travis-ci.com", "cdn.travis-ci.org", "ci.appveyor.com", "circleci.com", "cla.opensource.microsoft.com", "codacy.com", "codeclimate.com", "codecov.io", "coveralls.io", "david-dm.org", "deepscan.io", "dev.azure.com", "flat.badgen.net", "gemnasium.com", "githost.io", "gitlab.com", "godoc.org", "goreportcard.com", "img.shields.io", "isitmaintained.com", "marketplace.visualstudio.com", "nodesecurity.io", "opencollective.com", "snyk.io", "travis-ci.com", "travis-ci.org", "visualstudio.com", "vsmarketplacebadge.apphb.com", "www.bithound.io", "www.versioneye.com"],
  "updateUrl": "https://vscodium.now.sh",
  "releaseNotesUrl": "https://go.microsoft.com/fwlink/?LinkID=533483#vscode",
  "keyboardShortcutsUrlMac": "https://go.microsoft.com/fwlink/?linkid=832143",
  "keyboardShortcutsUrlLinux": "https://go.microsoft.com/fwlink/?linkid=832144",
  "keyboardShortcutsUrlWin": "https://go.microsoft.com/fwlink/?linkid=832145",
  "quality": "stable",
  "extensionsGallery": {
    "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
    "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
    "itemUrl": "https://marketplace.visualstudio.com/items"
  },
  "commit": "553cfb2c2205db5f15f3ee8395bbd5cf066d357d",
  "date": "2019-06-07T00:53:09.590Z",
  "checksums": {
    "vs/workbench/workbench.main.js": "YqInhQ+qdgAawAsvhiz56g",
    "vs/workbench/workbench.main.css": "QmZWwYc3U1LAARGNaLaVLw",
    "vs/code/electron-browser/workbench/workbench.html": "SJ2O65ioCx9YnHuee80AWQ",
    "vs/code/electron-browser/workbench/workbench.js": "5O9mbNGakN+ux44X4TqDjw"
  }
}`

**Comment by muideenlawal** [comment]
Thank you @stripedpajamas.
I managed to solve this problem. Seems I needed to restart my computer after updating and re-open the app.
`Extension` now showing after restarting.

**Comment by stripedpajamas** [comment]
Awesome!!

**Comment by sevkin** [comment]
same issue after upgrade vscodium 1.45.1 -> 1.46.0 (on unbuntu 18.04)
only downgrade solve this for me
but vscode 1.46.0 on same pc work fine
