### ISSUE TITLE
已经安装vscode了 再安装vscodium会冲突吗？

### ISSUE THREAD

**Issue by git10135405** [VSCodium/vscodium#189]

**Comment by stripedpajamas** [comment]
Hi @git10135405 👋 VSCodium does not conflict with VSCode, they can be run side-by-side without issue.

**Comment by git10135405** [comment]
> 嗨@ git10135405  VSCodium与VSCode不冲突，它们可以并行运行而不会出现问题。

再请教下 check for updates报 server returned 404
![image](https://user-images.githubusercontent.com/35558611/59241260-8b52e180-8c39-11e9-903f-385342fcdc45.png)

如果我用exe进行安装的 怎么更新呢？

**Comment by tyu1996** [comment]
似乎目前VSCodium尚未支持自动更新，毕竟它只是简单的把VSCode里非开源的部分去除掉重新汇编过，与VSCode官方binary无关。
Linux 有其[解决方案](https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo)，Windows就不清楚。

**Comment by git10135405** [comment]
@stripedpajamas
support update？
https://github.com/VSCodium/vscodium/issues/189#issuecomment-500670402

**Comment by stripedpajamas** [comment]
Updates are somewhat supported. Currently Mac and Windows User installs have updating working.
