### ISSUE TITLE
how to change the icon

### ISSUE THREAD

**Issue by wobushitankun** [VSCodium/vscodium#1899]
The icon of the application I compiled from the source code is for Electron. How do I set the icon when packaging? The icon I downloaded from the official website is correct. This makes me very confused.

![image](https://github.com/VSCodium/vscodium/assets/24643632/b9442329-d610-41ae-9ff7-3540374be104)

![image](https://github.com/VSCodium/vscodium/assets/24643632/7a066eb0-17fc-4205-9949-65ce46a203b1)

there are some shotcut for offcical app:
![image](https://github.com/VSCodium/vscodium/assets/24643632/eca1548b-a233-4b9e-a672-077a35e11a68)

![image](https://github.com/VSCodium/vscodium/assets/24643632/d88ca7e2-a9ac-4307-bf5d-259987545a9b)

**Comment by daiyam** [comment]
Use https://github.com/electron/rcedit to update the icon.
