### ISSUE TITLE
Command not found: codium

### ISSUE THREAD

**Issue by starun96** [VSCodium/vscodium#190]
**Describe the bug**
After the update to 1.35 and the new `vscodium-bin` package, I can no longer launch vscodium. Typing `vscodium` or `codium` into my terminal gives me the error `fish: Unknown command vscodium` or `fish: Unknown command codium`. 

**Please confirm that this problem is VSCodium-specific**
- [ Yes ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ Yes ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there. 

It is a fairly recent issue. I noticed that the latest comment from the `vscodium-bin` AUR page includes "Version 1.35.0 of VSCodium has introduced some breaking changes that are not accommodated in this release. The binary has been renamed to "codium", so "vscodium-bin.desktop" and the symlinks created in the PKGBUILD must be updated to use the new binary." However, I was not able to use `codium` anyway

**To Reproduce**
1. Install VSCodium with `yay -S vscodium-bin`
2. Enter `codium` or `vscodium` into the terminal (doesn't matter if using fish or zsh).

**Expected behavior**
I expect that an instance of VSCodium would start.

**Screenshots**
Unnecessary.

**Desktop (please complete the following information):**
 - OS: Arch Linux 4.19 LTS
 - Architecture: x86-64
 - Version: 1.35.0-1

**Additional context**
Previously, I had the version of VSCodium where I could launch it with `vscodium`. When I installed the new version, I reinstalled my computer. I then could not launch it with `vscodium` or `codium`. 

** Solution **
I was able to launch VSCodium only by going into the `/usr/share/vscodium-bin` folder and then manually executing `codium`, e.g. `./codium`.

**Comment by joseluisq** [comment]
Did you try this one?

<img width="625" alt="Screenshot 2019-06-11 at 08 29 22" src="https://user-images.githubusercontent.com/1700322/59248635-4b80ff80-8c23-11e9-96bc-e7929ee3bd14.png">

> Shell command 'codium' successfully installed in PATH.

```sh
~> which codium
/usr/local/bin/codium
```
Verify your binary path after that. It was tested in Mac but It should be similar in Linux.

**Comment by stripedpajamas** [comment]
As @joseluisq has said -- I believe you need to run the "Install 'codium' command in PATH" command inside VSCodium to get it working.

**Comment by joseluisq** [comment]
I have tested in __Arch Linux__ and it works after the update.

```sh
~> vscodium -v
1.34.0
a622c65b2c713c890fcf4fbf07cf34049d5fe758
x64

~> yay -Sy vscodium-bin
# [Aur: 1]  vscodium-bin-1.35.0-2 ....

~> vscodium -v
1.35.0
553cfb2c2205db5f15f3ee8395bbd5cf066d357d
x64

~> codium -v
1.35.0
553cfb2c2205db5f15f3ee8395bbd5cf066d357d
x64

~> which codium
/usr/bin/codium
```

**Comment by starun96** [comment]
After updating to 1.35.0-2, the `codium` executable is now on my PATH. I can now call it normally. Thank you.

**Comment by brodock** [comment]
command option to enable CLI doesn't exist anymore in current version.

**Comment by kitattyor** [comment]
@brodock are you using the flatpak version? I couldn't find the command in the flatpak but then updated to the "native" version and now I can use `codium` to open up a project folder

**Comment by brodock** [comment]
Yes, that was flatpak. I've learned that there are a lot of quirks when running in flatpak, so I assume the lack is due to that.

**Comment by graciano** [comment]
Using the AppImage version here and the command is unavailable as well

**Comment by gsal** [comment]
Well, right about a year later, and I am having an installation issue on Linux CentOS7.

When I simply download the program and type the command codium, it just does not do anything, I just get the prompt back. 

Then, I actually became root and installed codium-1.60.2-1632356608.el7.x86_64.rpm  and managed to get the gui, but ended up frozen.

Having a hard time getting to work.   Being an open source project, I wish one was able to install it in one's home directory without having to become root.

Can somebody point me to a Linux download that I can simply put in my home directory?   Thx.

**Comment by gsal** [comment]
Oh, I also tried VSCodium-linux-x64-1.60.2.tar.gz and extracting the files in my home directory..._no cigar_.
