### ISSUE TITLE
Wayland icon is shown instead of VSCodium icon on KDE

### ISSUE THREAD

**Issue by zartre** [VSCodium/vscodium#1901]
**Describe the bug**

The default Wayland icon is displayed on the taskbar and in the app switcher on KDE Plasma 6.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Open VSCodium
2. Observe the taskbar and the app switcher (`Alt` + `Tab`)

**Expected behavior**

VSCodium icon is used instead of Wayland icon.

**Screenshots**

![Screenshot_20240521_203426](https://github.com/VSCodium/vscodium/assets/3814520/4a8ed374-b1d3-4885-b399-4f09a657ff58)

![Screenshot_20240521_203901](https://github.com/VSCodium/vscodium/assets/3814520/8c269b55-0f2b-4233-ba6f-b2eb3fc9d867)

**Desktop (please complete the following information):**
 - OS: Fedora 40 with KDE Plasma 6.0.4
 - Architecture: x64
 - Version: 1.89.0
 - App Manager: RPM
 - Sandboxed: Flatpak

**Comment by wobushitankun** [comment]
same as me. I meet this issue on windows when i build vscodium form the source. In the task bar vscodium show the default electron icon, but i download the vscodium on their website version the icon is the corrct one. Maybe there are some config not record into the doc.

**Comment by daiyam** [comment]
@wobushitankun Your issue is different of the current one! Are you on Linux with Wayland and Flatpak???

**Comment by zartre** [comment]
I tried installing VSCodium through [dnf](https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo) and this version doesn't have this problem.

**Comment by daiyam** [comment]
> I tried installing VSCodium through [dnf](https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo) and this version doesn't have this problem.

Yep! I was pretty sure that it's a Flatpak issue

**Comment by noonsleeper** [comment]
> > I tried installing VSCodium through [dnf](https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo) and this version doesn't have this problem.
> 
> Yep! I was pretty sure that it's a Flatpak issue

Indeed, is a [well known problem in flatpak](https://github.com/flathub/com.vscodium.codium/issues/149)

I'll look to fix this, when I have some time to install a vm with KDE.

Some people mention that the problem maybe is how KDE ignores the `icon=` reference in the desktop file, and instead try to search for an icon that match with the name of the binary.

As reference, the icon installed by flatpak is named `com.vscodium.codium` and the binary `codium`

**Comment by noonsleeper** [comment]
Well, in the end the problem has a relative easy fix/workaround =).

@zartre, @wobushitankun, can confirm the fix in codium-insider using this?
```bash
flatpak install https://dl.flathub.org/build-repo/111269/com.vscodium.codium-insiders.flatpakref
```

The build will be only available for 24hs

**Comment by zartre** [comment]
Hi @noonsleeper 

Thanks for the fix. I can confirm that the icon is now showing!

**Comment by noonsleeper** [comment]
@zartre this patch was applied on [flatpak's codium](https://github.com/flathub/com.vscodium.codium/pull/346) and [flatpak's codium-insiders](https://github.com/flathub/com.vscodium.codium-insiders/pull/29), in ~4 hours will be available.

**Comment by fldu** [comment]
Having the same issue on Gentoo/KDE/Wayland with version 1.91.0.24190 - removing `--ozone-platform-hint=auto` from `/usr/share/applications/vscodium.desktop` fixes it.

**Comment by noonsleeper** [comment]
@zartre if this is already fixed, can you close the issue?

**Comment by nathan-opn** [comment]
@noonsleeper Seems like I don't have the permission to close the issue. If you do, please feel free to close it 🙂

![image](https://github.com/user-attachments/assets/5d259955-5cce-44eb-9f16-06ac754b6edf)

**Comment by daiyam** [comment]
@nathan-opn The issue was created by the user `zartre`. That's why you can't close it. You will have to switch to the correct account.
