### ISSUE TITLE
VSCodium not maximized when opening

### ISSUE THREAD

**Issue by markovic-nikola** [VSCodium/vscodium#1902]
Type: <b>Bug</b>

VSCodium does not remember the state of the window.
Whenever I open the app I have to click on maximize manually.
Using Ubuntu 24.04 LTS

VSCodium version: VSCodium 1.89.1 (a045dcfceda27f896936bfd8cbf524f6a93a2f46, 2024-05-09T18:30:40.866Z)
OS version: Linux x64 6.8.0-31-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7800X3D 8-Core Processor (16 x 4390)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|30.50GB (23.85GB free)|
|Process Argv|--no-sandbox --force-user-env|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
alpine-js-intellisense|adr|1.2.0
project-manager|ale|12.8.0
laravel-extra-intellisense|ami|0.6.5
astro-vscode|ast|2.10.2
laravel-blade-spacer|aus|2.3.0
laravel-docs|aus|1.11.0
markdown-preview-github-styles|bie|2.0.4
vscode-intelephense-client|bme|1.10.4
htmltagwrap|bra|1.0.0
vscode-tailwindcss|bra|0.10.5
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.8.5
laravel-goto-view|cod|1.3.11
laravel-goto-controller|ctf|0.6.8
githistory|don|0.6.20
prettier-vscode|esb|10.4.0
font-switcher|eva|4.1.0
vue-inline-template|fai|1.0.1
vscode-svelte-snippets|fiv|0.5.0
auto-rename-tag|for|0.1.10
shell-format|fox|7.2.5
github-linker|gim|0.2.5
go|gol|0.41.4
todo-tree|Gru|0.0.226
copy-filename|jac|2.3.2
minifyall|jos|2.10.0
vscode-view-in-browser|kop|1.0.5
localtunnel-for-vscode|mau|1.0.0
rainbow-csv|mec|3.11.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
file-downloader|min|1.0.13
laravel-goto-config|MrC|1.0.3
vscode-duplicate|mrm|1.2.1
vscode-scss|mrm|0.10.0
live-server|ms-|0.4.13
makefile-tools|ms-|0.9.10
color-highlight|nau|2.8.0
php-docblocker|nei|2.7.0
language-liquid|nei|0.1.1
vetur|oct|0.37.3
indent-rainbow|ode|8.3.1
laravel-blade|one|1.36.1
htmx-tags|oto|0.0.8
laravel-jump-controller|pgl|0.0.33
material-icon-theme|PKi|5.3.0
gitlink|qez|1.2.4
LiveServer|rit|5.7.9
theme-check-vscode|Sho|2.3.0
vscode-blade-formatter|shu|0.24.2
svg-preview|Sim|2.8.3
vscode-autohide|sir|1.0.10
alpinejs-syntax-highlight|spe|1.0.1
svelte-vscode|sve|108.4.1
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.17.2

(5 theme extensions excluded)

</details>

**Comment by daiyam** [comment]
It isn't a VSCodium thing but more a Gnome one.

https://askubuntu.com/questions/1464737/some-applications-do-not-remember-window-state
https://askubuntu.com/questions/1315204/where-does-gnome-keep-track-of-window-size-to-use-when-starting-applications
https://askubuntu.com/questions/1410229/is-there-anyway-to-make-ubuntu-22-04-remember-the-size-and-location-of-windows

**Comment by markovic-nikola** [comment]
@daiyam 

Second link that you shared, I've read it before too.

![image](https://github.com/VSCodium/vscodium/assets/16388545/34581c63-1509-410b-ab91-7e9edacf2a5a)

I was under the impression that it's up to the program to store the settings of the window.
> The window size and state upon program start is controlled by the application itself.

On the other hand the bug is reported on [their end](https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/2013542).

**Comment by daiyam** [comment]
I think it's a swiss cheese issue: it's a cumulative result of small bugs in the driver, gnome, snap, app.
You should try the `.deb`. Maybe with luck, it will work...
I've seen many issues resolved by removing the container (snap, flatpak, appimage, ...).
