### ISSUE TITLE
Unable to load vscodium in arch linux

### ISSUE THREAD

**Issue by tarunkumarreddytirupathi** [VSCodium/vscodium#1907]
**Describe the bug**
**https://github.com/VSCodium/vscodium/blob/master/docs/index.md) this link is not working**
after installing vscodium first time in arch linux . when I try to launch  vscodium from terminal it gives this error mentioned in below image

Yes, I confirm that this problem is VSCodium-specific 
- [1] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

yes, I confirm that the issue/resolution isn't already documented
- [1] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. yay -S vscodium (to install vscodium i narch linux)
2. type vscodium in terminal
3. press enter
4. you will see the error message

**Expected behavior**
There was a problem in /usr/share/vscodium/resources/app/product.json
I edited this line

"https://open-vsx.org"

as this

"linkProtectionTrustedDomains": [
        "https://open-vsx.org"
    ],

It solved problem and loaded vscodium and now it's works fine

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Arch linux]
 - Architecture [ x64,
 - Version [1.89.1.24130]
 - App Manager [YAY ( AUR Helper ) ]
 - Node.js Version [18.18.2]

![Screenshot_2024-05-30_22-10-26](https://github.com/VSCodium/vscodium/assets/150784964/6ff3998c-e197-48a5-a91b-e55cabc8eed7)

**Comment by daiyam** [comment]
Which AUR did you used?

**Comment by tarunkumarreddytirupathi** [comment]
This one I used

**YAY**
[https://aur.archlinux.org/packages/yay)]
