### ISSUE TITLE
Markdown Preview search broken

### ISSUE THREAD

**Issue by shuyuxie** [VSCodium/vscodium#1908]
**Describe the bug**
Default markdown Preview search broke. Search works in source markdown file.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to any Markdown source file
2. Click on 'Open Preview' on right click tab menu
3. Hit Command+F and search for keywords
5. See error

**Expected behavior**
See searched keywords highlighted and focused

**Screenshots**
<img width="1076" alt="image" src="https://github.com/VSCodium/vscodium/assets/123744197/9fc1574e-2ebb-4896-8634-4fd2dc2fb68b">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Architecture: x64
 - Version: 1.88.1 24104
 - App Manager: Downloaded from Github Release
 - Sandboxed: no
 
**Additional context**
None

**Comment by daiyam** [comment]
Same issue as #1860
