### ISSUE TITLE
What is the domain string for VSCodium default settings on Mac OS?

### ISSUE THREAD

**Issue by xtimmu** [VSCodium/vscodium#191]
I'm inherently trying to use VIM plugin with VSCodium on OS X. It has a repeat key feature that has to be enabled using mac system default settings (man defaults).

https://github.com/VSCodeVim/Vim outlines the procedure as:

`$ defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false         # For VS Code`
`$ defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false # For VS Code Insider`

Unsuprisingly neither of those has any effect on VSCodium. Can someone point out what the correct domain string is?

**Comment by stripedpajamas** [comment]
Please check out the DOCS page as this is mentioned there: https://github.com/VSCodium/vscodium/blob/master/DOCS.md
