### ISSUE TITLE
[Solved] Domain suspended or not configured

### ISSUE THREAD

**Issue by rjc3rd** [VSCodium/vscodium#1910]
It seems that this may have happened before, but...

https://download.vscodium.com/debs/dists/vscodium/InRelease

Domain suspended or not configured

If you are the administrator and believe this is an error on our side, please check your BunnyCDN account configuration or contact customer support.

**Comment by daiyam** [comment]
@PalinuroSec Can you check the BunnyCDN. Thx

@PrimaIVoid The CDN is sponsored by @PalinuroSec. The most likely issue is that the bill hasn't be paid.

**Comment by KeyboardInterrupt** [comment]
Is this just mildly annoying, or is there a real risk that the domain could be grabbed by someone with malicious intend whenever this happens?

**Comment by daiyam** [comment]
@KeyboardInterrupt No, it's just that the CDN has suspended the account. There is no risk.

**Comment by seungjin** [comment]
@KeyboardInterrupt 
You can always download it form github: https://github.com/VSCodium/vscodium/releases
It's opensource and free. I can understand the situation. 
I switched direct download from github release than package manager to save some unnecessary cost. 

https://github.com/seungjin/mytoolbox/blob/47b9299f2d0ad58502dd6a8b1a16ccacf23781c8/Fedora/rawhide/Containerfile#L13

**Comment by daiyam** [comment]
@KeyboardInterrupt VSCodium is still usable, just the update (for rpm/deb) might be impacted.

**Comment by KeyboardInterrupt** [comment]
I know, It's just that my Setup scripts (for a new box) failed, I can be productive in other ways, so I will wait this one out and rerun the bootstrap scripts.
If this takes unexpectedly long, I will consider a different temporary solution.
Thanks for letting me know though!

**Comment by KeyboardInterrupt** [comment]
Oh! great I didn't have to wait to long :D Thank you for fixing this!

**Comment by rjc3rd** [comment]
The problem is solved now. I had not seen this problem before but when I searched here, I saw it had happened before. It didn't enter my mind at the time that it might be related to money. I first figured that someone made a change on the server that broke the downloads. Anyway, it's working now and if it happens again I won't be asking about it. Thanks.
