### ISSUE TITLE
[riscv64]vscodium-insiders doesn't support linux-riscv64

### ISSUE THREAD

**Issue by sendaoYan** [VSCodium/vscodium#1911]
**Describe the bug**
vscodium-insiders doesn't support linux-riscv64

```log
[Trace  - 02:47:17.466] Server install command stderr:
https://github.com/VSCodium/vscodium-insiders/releases/download/1.90.0.24153-insider/vscodium-reh-linux-riscv64-1.90.0.24153-insider.tar.gz:
2024-06-05 10:47:17 ERROR 404: Not Found.
```

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. install `open-remote-ssh-0.0.45.vsix` manual
2. open riscv64 ssh remote machine

**Expected behavior**

**Screenshots**

![image](https://github.com/VSCodium/vscodium/assets/24123821/a082716a-1958-4153-89ab-1b4f13419134)

[remote-ssh-riscv64.log](https://github.com/user-attachments/files/15572514/remote-ssh-riscv64.log)

[open-remote-ssh-0.0.45.vsix.zip](https://github.com/user-attachments/files/15572518/open-remote-ssh-0.0.45.vsix.zip)

**Desktop (please complete the following information):**
```
uname -a ; cat /etc/os-release ; free -h ; lscpu | head -n 25
Linux fedora-riscv 6.1.31 #1 SMP Thu Jun 15 01:30:00 CST 2023 riscv64 GNU/Linux
NAME="Fedora Linux"
VERSION="38 (Workstation Edition)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation
               total        used        free      shared  buff/cache   available
Mem:           125Gi       1.2Gi       114Gi        15Mi        10Gi       123Gi
Swap:          8.0Gi          0B       8.0Gi
Architecture:        riscv64
Byte Order:          Little Endian
CPU(s):              64
On-line CPU(s) list: 0-63
NUMA node(s):        4
NUMA node0 CPU(s):   0-7,16-23
NUMA node1 CPU(s):   8-15,24-31
NUMA node2 CPU(s):   32-39,48-55
NUMA node3 CPU(s):   40-47,56-63
```
**Additional context**

**Comment by daiyam** [comment]
Linux versions have not been finalized for `1.90.0.24153`

**Comment by sendaoYan** [comment]
> Linux versions have not been finalized for `1.90.0.24153`

Does the previous versions support linux-riscv64.

**Comment by daiyam** [comment]
> Does the previous versions support linux-riscv64.

Look for `vscodium-reh-linux-riscv64-*.tar.gz`

I would recommend to use the non-insiders version (`1.89.1.24130`)
