### ISSUE TITLE
Error: net::ERR_NETWORK_ACCESS_DENIED

### ISSUE THREAD

**Issue by youngunix** [VSCodium/vscodium#1924]
**Describe the bug**
VSCodium generates network access errors upon launch and unable to update or install new extensions.

**Please confirm that this problem is VSCodium-specific**
- [*] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [*] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to 'extensions'
2. Click on 'update' or 'install'
3. Scroll down to 'console output'
------------------------
[error] net::ERR_NETWORK_ACCESS_DENIED: Error: net::ERR_NETWORK_ACCESS_DENIED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:109791)
    at SimpleURLLoaderWrapper.emit (node:events:514:28
------------------------

**Expected behavior**
Update or install extensions as normal.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Architecture [x64 (AMD64)]
 - Version [1.90]
 - App Manager [Winget]
 - Sandboxed [none]

**Additional context**
The output below is from the 'About' window:

Version: 1.90.0 (user setup)
Release: 24158
Commit: cc102f3a62bd35f39ed059b99c5cce90e50a16e2
Date: 2024-06-06T18:39:48.552Z
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by youngunix** [comment]
It's using the default marketplace it came with "https://open-vsx.org".

![image](https://github.com/VSCodium/vscodium/assets/6511377/60ca72b4-277c-4277-8424-69d7fa163370)

**Comment by youngunix** [comment]
This is what I see when I switch to "https://marketplace.visualstudio.com/VSCode". It seems to be working as it should and I believe that open-vsx has issues because on the browser it doesn't load icons. 

![image](https://github.com/VSCodium/vscodium/assets/6511377/b66cc61b-a8ac-48ff-89e2-697f3c68ae33)

**Comment by daiyam** [comment]
> I believe that open-vsx has issues because on the browser it doesn't load icons.

That's weird. It was/is working fine. Where are you?

**Comment by youngunix** [comment]
I'm right here beside you friend (US/Central).

Actually, what I did only solved the error but now I cannot search for extensions. If I type 'Go' for example, nothing comes up.
Do you have an example of 'product.json' from a working VSCodium or VSCode?

**Comment by youngunix** [comment]
The latest update reverted back the changes I made to the 'serviceurl' entry. 

![image](https://github.com/VSCodium/vscodium/assets/6511377/8c02d5e8-385f-4bfd-b22b-83079aa5a27c)

**Comment by youngunix** [comment]
![image](https://github.com/VSCodium/vscodium/assets/6511377/49b401ac-99fb-467f-9b94-e9606a4c89c1)

![image](https://github.com/VSCodium/vscodium/assets/6511377/21a7eac8-077d-48a7-97b5-f03e1f684977)

**Comment by daiyam** [comment]
I don't know what's going on. But, on my machine, the icons are showing up on open-vsx.org.

Can you look at the console in your browser to see if there is any errors... 

Are you using a VPN or something filtering your connection?

**Comment by youngunix** [comment]
I did some investigating and it seems that open-vsx.org is acting suspicious indeed. I understand if it was the browser's hardened settings and extensions but it seems to be acting the same way on a barebone secondary browser. 

I am safely assuming that one of the firewalls this machine is behind does not like what that website is doing. 

Also, this is out of scope but this website is very good at bypassing the privacy & safety invasion/abuse counter measures which is more suspicious than I would hope.

**Comment by daiyam** [comment]
> Also, this is out of scope but this website is very good at bypassing the privacy & safety invasion/abuse counter measures which is more suspicious than I would hope.

Not sure what you mean. I'm using Brave + uBlock origin and it's working fine.

If there is a privacy/safety issue, you report to their repo: https://github.com/eclipse/openvsx (the site is under EPL and under the umbrella of the Eclipse Foundation)

> it seems to be acting the same way on a barebone secondary browser.

Ya, that's why I think it's network issue. But where? on their side? yours? or in middle???
The logs in the browser (in the console) might help. In particular, any error on the network tab.

**Comment by youngunix** [comment]
How can I get "https://marketplace.visualstudio.com/VSCode" to work with VSCodium?

**Comment by daiyam** [comment]
> I will open an issue with their team.

Could you post here the link to the issue so I can follow it? Thx

**Comment by daiyam** [comment]
@JavadCodes Since OpenVSX is US-operated, they might have to follow some rules that restrict the access to your country (Iran).

**Comment by JavadCodes** [comment]
Yes, you are right. However, this issue has only occurred recently. Before this, I was using it without any problems.
Additionally, I am using it on other devices without any issues.
