### ISSUE TITLE
SELinux is preventing codium from using the execheap access on a process.

### ISSUE THREAD

**Issue by JohnPadewick** [VSCodium/vscodium#1931]
Type: <b>Performance Issue</b>

Hello, 

this happens like 3-4 consecutive times after i start VSCodium, then it stops and after some time (now while using VSCodium) it repeats.
Not sure what is causing this. It als doesn't really break anything (i'm aware of), i just thought i'd report it here :)
Greetings!

Text from SETroubleshoot Details Window: 
Plugin: allow_execheap 
The codium application attempted to change the access protection of memory on the heap (e.g., allocated using malloc).  This is a potential security problem.

VSCodium version: VSCodium 1.88.1 (0d01a72525276e5e3771fe5851b9c83de0de1e2b, 2024-04-13T01:53:59.491Z)
OS version: Linux x64 6.9.4-100.fc39.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-14700K (28 x 5639)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 0|
|Memory (System)|31.11GB (26.73GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   159	  4275	codium main
    0	    32	  4279	   zygote
    0	   127	  4310	     gpu-process
    0	    32	  4280	   zygote
    0	     0	  4282	     zygote
    0	   255	  4335	window [1] (Extension: Live Server - elfmeter-turnier - JavaScript - VSCodium)
    0	    96	  4644	       window
    0	    96	  4900	window [2] (Issue Reporter)
    0	    64	  4315	   utility-network-service
    0	    64	  4384	ptyHost
    0	     0	  4491	     /usr/bin/bash --init-file /usr/share/codium/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	    96	  4395	shared-process
    0	     0	  4912	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    64	  4397	fileWatcher [1]
    0	   191	  4763	extensionHost [1]
    0	   127	  4779	     electron-nodejs (tsserver.js )
    0	   255	  4780	     electron-nodejs (tsserver.js )
    0	    64	  4815	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	    64	  4793	     /usr/share/codium/codium /usr/share/codium/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=4763
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Extension: Live Server - elfmeter-turnier - JavaScript - VSCodium)
|    Folder (elfmeter-turnier): 36 files
|      File types: tsx(7) png(5) json(4) html(2) css(2) ts(2) cjs(1)
|                  gitignore(1) md(1) js(1)
|      Conf files: package.json(1) tsconfig.json(1);
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
catppuccin-vsc|Cat|3.14.0
catppuccin-vsc-icons|Cat|1.13.0
es7-react-js-snippets|dsz|4.4.3
vscode-great-icons|emm|2.1.105
prettier-vscode|esb|10.4.0

</details>

**Comment by JohnPadewick** [comment]
yeah, that's the same issue. 
Sorry for duplication... & 
Thanks!

**Comment by wi24rd** [comment]
I'm using vscodium from copr [1], but in same situation.
I'll try `setsebool -P selinuxuser_execheap 1`.

[1] https://copr.fedorainfracloud.org/coprs/qoijjj/vscodium/package/codium/

**Comment by wi24rd** [comment]
I'm using vscodium from copr [1], but in same situation.
I'll try `setsebool -P selinuxuser_execheap 1`.

[1] https://copr.fedorainfracloud.org/coprs/qoijjj/vscodium/package/codium/

**Comment by wi24rd** [comment]
I'm using vscodium from copr [1], but in same situation.
I'll try `setsebool -P selinuxuser_execheap 1`.

[1] https://copr.fedorainfracloud.org/coprs/qoijjj/vscodium/package/codium/
