### ISSUE TITLE
Doubts regarding the source code

### ISSUE THREAD

**Issue by andersontz** [VSCodium/vscodium#1933]
I don't know if this is the correct place for this, but my intention is to obtain the source code and create a system derived from it, with another name (the license allows it). My question is, how to do it, because I got the files from here, and the main source code is missing. How to obtain the complete source, without telemetry and without violating the license, including from Microsoft. Do you have any description that explains how to do it?

**Comment by daiyam** [comment]
https://github.com/VSCodium/vscodium/blob/master/docs/howto-build.md

**Comment by andersontz** [comment]
Right, thanks, but still, every way I try to download, we don't have access to the full source code. It doesn't have package.json either. How do I download the complete source code, with the possibility of editing it?

**Comment by andersontz** [comment]
Thanks
