### ISSUE TITLE
An error occurred when an open-remote-ssh extension was used to connect to a riscv linux device

### ISSUE THREAD

**Issue by wang-zhichuang** [VSCodium/vscodium#1934]
**Describe the bug**
An error occurred when an open-remote-ssh extension was used to connect to a riscv linux device, Connecting to x86 linux is normal

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. install [open-remote-ssh-0.0.45.vsix](https://github.com/kxxt/open-remote-ssh/tree/master) manual
2. open riscv64 ssh remote machine

**Expected behavior**

**Screenshots**
windows11
![image](https://github.com/VSCodium/vscodium/assets/37931535/d2cbff8d-a29c-4c7a-bd52-7ba038687c6e)

riscv

![image](https://github.com/VSCodium/vscodium/assets/37931535/d0dfd288-9888-44ac-8452-f34234cb5849)

**Desktop (please complete the following information):**
 - OS: [ Windows11 ]
 - Architecture [e.g. x64]
 - Version [e.g. 1.90.2 ]
 - App Manager [...]
 - Sandboxed [e.g. no]

**Additional context**
[remote-ssh.log](https://github.com/user-attachments/files/15923686/remote-ssh.log)

**Comment by wang-zhichuang** [comment]
I see another issue but it doesn't help my question,   https://github.com/VSCodium/vscodium/issues/1911

I would like some help on how to debug reh

**Comment by kxxt** [comment]
Please upload the full contents of the output from the plugin. The screenshot only contains an ssh identity  issue.

**Comment by wang-zhichuang** [comment]
> Please upload the full contents of the output from the plugin. The screenshot only contains an ssh identity issue.

this Plug-in output [remote-ssh.log](https://github.com/user-attachments/files/15923243/remote-ssh.log)

**Comment by kxxt** [comment]
> @kxxt It would be good if you can create a PR to add RiscV to the plugin (https://github.com/jeanp413/open-remote-ssh/blob/8191939de706952fa035f80a6fce0e85f85495f6/src/serverSetup.ts#L280)

Actually I already opened a PR two months ago, but it appears that the maintainer of that plugin isn't active. https://github.com/jeanp413/open-remote-ssh/pull/147

**Comment by wang-zhichuang** [comment]
> @wang-zhichuang From the logs, I can see that it's connecting successfully but then it tries to reconnect.从日志中，我可以看到它连接成功，但随后它尝试重新连接。 Can you send us the logs on the server? `/home/test/.vscodium-server/.7d98c6de73fb939f1eb4b8a500c569b858b2d297.log`你能把服务器上的日志发给我们吗？ `/home/test/.vscodium-server/.7d98c6de73fb939f1eb4b8a500c569b858b2d297.log`
> 
> @kxxt It would be good if you can create a PR to add RiscV to the plugin (https://github.com/jeanp413/open-remote-ssh/blob/8191939de706952fa035f80a6fce0e85f85495f6/src/serverSetup.ts#L280)如果您可以创建一个 PR 将 RiscV 添加到插件中，那就太好了 （ https://github.com/jeanp413/open-remote-ssh/blob/8191939de706952fa035f80a6fce0e85f85495f6/src/serverSetup.ts#L280）

![image](https://github.com/VSCodium/vscodium/assets/37931535/4a556313-bfb8-4b7c-a916-12fab92217ce)

It's just a simple log, is there a way to open more logs?

**Comment by kxxt** [comment]
> It's just a simple log, is there a way to open more logs?

Could you also check if it works after killing all the vscodium-sever processes removing `~/.vscodium-server` on your server. And if it still fails, could you check `coredumpctl`(and `journalctl`) to see if the server process crashed?

**Comment by kxxt** [comment]
> > Please upload the full contents of the output from the plugin. The screenshot only contains an ssh identity issue.
> 
> this Plug-in output [remote-ssh.log](https://github.com/user-attachments/files/15923243/remote-ssh.log)

I don't see any errors that we can help with. But it just looks like you have a bad openssh  setup and it failed to resolve remote authority for 5 attempts.

```
[Info  - 05:42:27.2] Resolving ssh remote authority 'ssh-remote+192.168.109.184' (attemp #5)
```

**Comment by wang-zhichuang** [comment]
> `journalctl`

Thank you for your help. I found the problem using the following method

- View newly added log entries in real time：[[journalctl]] -f
	-
	  ```shell
	  6月 21 18:06:08 openEuler sshd[32613]: refused local port forward: originator ::ffff:127.0.0.1 port 63747, target 127.0.0.1 port 46749
	  6月 21 18:06:08 openEuler sshd[32613]: Close session: user test from 192.168.109.129 port 63742 id 1
	  6月 21 18:06:08 openEuler sshd[32613]: refused local port forward: originator ::ffff:127.0.0.1 port 63750, target 127.0.0.1 port 46749
	  6月 21 18:06:08 openEuler sshd[32809]: Connection from 192.168.109.129 port 63748 on 192.168.109.184 port 22 rdomain ""
	  ```
- The log indicates that port 63747 on '127.0.0.1' was forwarded to port 46749 on target '127.0.0.1', but was rejected.
- Solution:
- Check SSH configuration: '/etc/ssh/sshd_config' Modify configuration AllowTcpForwarding yes'
- Retry the connection successfully


Thanks again
