### ISSUE TITLE
merge user product.json feature has failed when using --user-data-dir commandline.

### ISSUE THREAD

**Issue by kendling** [VSCodium/vscodium#1941]
**Describe the bug**
1. Download and extract the zip package.
2. Create the shortcut for VSCodium.exe.
3. Modify the shortcut and add `--user-data-dir` for it.
4. Produce user product.json from `https://github.com/VSCodium/vscodium/blob/master/docs/index.md#extensions--marketplace`.
5. Start it via the shortcut.
6. The instance using open-vix.org still.
7. It can merge `product.json` when place in `%AppDATA%\VSCodium\product.json`

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I using data dir as protable user data in same folder as VSCodium.exe.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**Expected behavior**
VSCodium can merge it when product.json place in dir prass by `--user-data-dir` param.

**Desktop (please complete the following information):**
 - OS: Windows
 - Architecture: x64
 - Version: 10.0.22631.3807

**Additional context**
I reviewed the merge-user-product.patch file in repo.
The resolveUserProduct function call getUserDataPath using `{}` as `cliArgs` param, it that the problem?

**Comment by daiyam** [comment]
It has been fixed in #2055 and #2066
