### ISSUE TITLE
Fcitx5 not working in vscodium Wayland windows.

### ISSUE THREAD

**Issue by kyv001** [VSCodium/vscodium#1966]
Type: <b>Bug</b>

Fcitx5 is not working in vscodium Wayland windows but it's working fine in X11 windows.
Using Fcitx5 5.1.10 on latest Arch Linux with:
XMODIFIERS=@im=fcitx
GTK_IM_MODULE=fcitx
SDL_IM_MODULE=fcitx
INPUT_METHOD=fcitx
GLFW_IM_MODULE=ibus
QT_IM_MODULES="wayland;fcitx;ibus"
VSCodium is installed from AUR packages "vscodium-bin"

VSCodium version: VSCodium 1.91.1 (8512cb3341b26a5dba985a9a17eed8d7c3362886, 2024-07-11T18:37:10.462Z)
OS version: Linux x64 6.9.9-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics (16 x 4076)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 1|
|Memory (System)|27.26GB (22.55GB free)|
|Process Argv|--enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland --enable-proposed-api jeanp413.open-remote-ssh|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|10.1.0
open-remote-ssh|jea|0.0.46
vscode-language-pack-zh-hans|MS-|1.91.0
debugpy|ms-|2024.8.0
python|ms-|2024.10.0

</details>

**Comment by noonsleeper** [comment]
@kyv001 this is a problem in upstream, it is already reported and tracking here https://github.com/microsoft/vscode/issues/167757#issuecomment-2198398853

**Comment by Bryan2333** [comment]
It is strange. I put two argument `--ozone-platform-hint=auto --enable-wayland-ime` into `codium-flags.conf`, this makes Fcitx5 unsable in wayland.

But when I pass these two arguments in terminal like `codium --ozone-platform-hint=auto --enable-wayland-ime`, I'm able to use input method.

**Comment by daiyam** [comment]
> It's my fault. I use the AUR package vscodium, which does not read the codium-flags.conf.

Oh, ya. I have to add that support...

**Comment by kyv001** [comment]
Passing "--enable-wayland-ime" fixes this problem.
