### ISSUE TITLE
Ubuntu: The repository 'https://download.vscodium.com/debs noble Release' does not have a Release file.

### ISSUE THREAD

**Issue by RiaanBurger** [VSCodium/vscodium#1968]
**Describe the bug**
When running `apt update` it presents this error:

```pre
E: The repository 'https://download.vscodium.com/debs noble Release' does not have a Release file.
```

**Please confirm that this problem is VSCodium-specific**
- [x ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

A previous issue on the matter is now closed: https://github.com/VSCodium/vscodium/issues/1059

```sh
cat /etc/apt/sources.list.d/vscodium.sources     
```

```pre
Architectures: amd64
Components: main
Enabled: yes
X-Repolib-Name: vscodium
Signed-By: /etc/apt/keyrings/vscodium.asc
Suites: noble
Types: deb deb-src
URIs: https://download.vscodium.com/debs
```

**Comment by RiaanBurger** [comment]
The new Mint 22 that was released just now and which I've been testing that led to the error does not have snaps as a fallback,

**Comment by RiaanBurger** [comment]
Also discussed here, where currently the only option left is to move back to Microsoft vscode:

https://forums.linuxmint.com/viewtopic.php?p=2498549

**Comment by daiyam** [comment]
I just made a comment on the linux mint forum (it need to validated since I'm a new user...)

But it seems to be a linux mint issue, I will see with the folks there.

**Comment by RiaanBurger** [comment]
Thank you very much for the attention. It may be worth mentioning that for this Linux Mint is using Ubuntu 24.04 LTS (Noble Numbat), hence the Suites: `noble part`. Mint though, disables snaps, which may be why Ubuntu users haven't yet reported this (bar in that thread of a previous issue here that I linked.

**Comment by RiaanBurger** [comment]
I posted on the forum too and copy here:

Apologies if my troubleshooting is naive, I'm not familiar with apt and deb sources.

When I run:

`sudo apt -oDebug::pkgAcquire::Worker=1 update 2>&1 | sed 's/%20/ /g' | grep codium | sed 's/%0a/\n/g'`

It would seem the file it is looking for is:

`https://download.vscodium.com/debs/dists/noble/InRelease`

**Comment by RiaanBurger** [comment]
Reading:

https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/blob/master/updaterepos.sh?ref_type=heads

It looks like one may have to run reprepro multiple times per suite/codename.

I read that [Aptly](https://www.aptly.info/) may be better suited.

**Comment by RiaanBurger** [comment]
I know little enough about these things that I'm not sure if I'm being helpful or just adding noise, but I found this `.gitlab-ci.yml` as an example of using aptly:

https://github.com/nodiscc/toolbox/blob/master/.gitlab-ci.yml

**Comment by RiaanBurger** [comment]
Thank you for the attention. I'm reverting back to VSCode for now. I'll check back some time to see if Codium repos are up.

**Comment by paulcarroty** [comment]
It works, tested in docker on Latest mint.
