### ISSUE TITLE
VSCode version 1.35.1 was released

### ISSUE THREAD

**Issue by JayAndCatchFire** [VSCodium/vscodium#197]
I feel like garbage opening a ticket like this as I'm sure you're already aware of this, @stripedpajamas.  But just on the off chance that you haven't been alerted, [VSCode 1.35.1](https://github.com/microsoft/vscode/releases/tag/1.35.1) has been released.

I don't know if you, @stripedpajamas, think this would be worth it, but maybe some level of automation could be set up that automatically attempts a build/release when VSCode cuts a release?  Or maybe something that just automatically opens an issue or a PR or something?  I guess it all depends on how often builds require manual intervention.  Or if there could be some way to test that a VSCodium release succeeded besides just that the build script didn't crash and the build artifacts exist.  Or at least, that's what I'd be thinking about before making it completely automated.  I'm just thinking out loud.

My point is just that I completely recognize and understand that issues like this can come across as annoying and whiny.  I appreciate this project and the work you do, @stripedpajamas.  I don't wish to annoy.

**Comment by stripedpajamas** [comment]
The builds run daily and if MS has cut a new release, the builds cut one too. None of it is manual besides the dependent distributors -- brew, chocolatey, aur, etc. 

Should see 1.35.1 tomorrow.

**Comment by stripedpajamas** [comment]
Automated validation of build artifacts would be great, PRs welcome 🤠

**Comment by JayAndCatchFire** [comment]
Awesome.  I didn't realize is was a daily thing.  Good to know.  From now on, I'll wait up to 48 hours before pestering. ;-)

**Comment by JayAndCatchFire** [comment]
I wonder how/if MS does that kind of validation.  I mean, I know they have unit tests, but I don't know if there are any tests that actually run against their binaries.

**Comment by stripedpajamas** [comment]
A good start may even be to just run the binaries with --version to confirm they aren't completely broken. It wouldn't be a big job to implement that.

**Comment by JayAndCatchFire** [comment]
I did some spelunking in the VSCode issues and resurfaced with this gem.  Maybe this could be adapted?  https://github.com/Microsoft/vscode/blob/master/test/smoke/README.md
