### ISSUE TITLE
Extension update returns 502

### ISSUE THREAD

**Issue by henrypp** [VSCodium/vscodium#1979]
**Describe the bug**
![sshot-001](https://github.com/user-attachments/assets/c2986b25-8e79-4f3a-89ae-c9748b91b3d6)

**Desktop (please complete the following information):**
 - OS: win11
 - Architecture x64
 - Version 1.91.1

**Comment by daiyam** [comment]
duplicate #1978

**Comment by henrypp** [comment]
@daiyam ok, understand, and now it was fixed, but where VSCodium 1.92?
