### ISSUE TITLE
holding 'ctrl'+ left-click did not add multi cursor

### ISSUE THREAD

**Issue by darkPeace** [VSCodium/vscodium#198]
hi,
i had tried to use multiple cursor features like in vscode but failed to do so using ctrl key and mouse click. is there any setting i should change before i can use that feature or that feature is not available yet in vscodium?

tq

os: parrot 4.7
kernel: 5.1.0 x64
vscodium 1.35.0

**Comment by stripedpajamas** [comment]
That feature is available in VSCodium, I use it daily. Perhaps the default key binding is different? Can you check what the key binding is set to?

**Comment by stripedpajamas** [comment]
Actually it doesn't look like it's listed as a "keyboard shortcut" because it involves the mouse. Isn't the default Alt-Click?

**Comment by darkPeace** [comment]
omg...i'm sorry. you are right. my default setting is alt key. then i just change it to ctrl key in the settings. its working now. thanks!

![Screenshot_20190613_093959](https://user-images.githubusercontent.com/23012721/59397688-1bbb2e80-8dc0-11e9-9325-8f7613a526d9.png)

**Comment by darkPeace** [comment]
i will close this issue now... thanks @stripedpajamas
