### ISSUE TITLE
Where 1.92?

### ISSUE THREAD

**Issue by henrypp** [VSCodium/vscodium#1985]
Above week from release VS Code 1.92, when you release update?

**Comment by youcefv** [comment]
It's actually 10 days as of now,
I think this repo should focus on releasing the most resent releases form "Code - OSS" as soon as possible,
rather than adding extra functionality and fixing issues related to those additions.

**Comment by 0rzech** [comment]
The update has just been [released](https://github.com/VSCodium/vscodium/releases/tag/1.92.1.24225).

Thank you very much for your hard work, @daiyam and @stripedpajamas !

**Comment by henrypp** [comment]
thx @daiyam
