### ISSUE TITLE
Loop for upgrade

### ISSUE THREAD

**Issue by bonvi83** [VSCodium/vscodium#1987]
Type: <b>Bug</b>

Ho questa versione del software:
Versione: 1.91.1
Release: 24193
Commit: 8512cb3341b26a5dba985a9a17eed8d7c3362886
Data: 2024-07-11T18:26:16.171Z
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
Sistema operativo: Darwin arm64 23.6.0

Quando scarico ed installo la 1.92.1.24225, mi dice che c'è un altro aggiornamento e mi riporta alla 1.91.1.
Risulta essere un loop infinito.

VSCodium version: VSCodium 1.92.1 (1ff04139c0ffdd7ef85760b15566fe2de88da2ec, 2024-08-12T12:56:48.158Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 3, 3|
|Memory (System)|16.00GB (1.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
vscode-intelephense-client|bme|1.12.2
githistory|don|0.6.20
gitlens|eam|15.2.3
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|10.4.0
php-debug|fel|1.22.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
rainbow-csv|mec|3.3.0
git-graph|mhu|1.30.0
vscode-language-pack-it|MS-|1.91.0
color-highlight|nau|2.8.0
indent-rainbow|ode|8.3.1
laravel-blade|one|1.36.1
material-icon-theme|PKi|5.9.0
vscode-css-peek|pra|4.4.1
LiveServer|rit|5.7.9
vscode-blade-formatter|shu|0.24.2
open-in-browser|tec|2.0.0
pdf|tom|1.2.2
volar|Vue|2.0.28
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.6.2

</details>

**Comment by daiyam** [comment]
Are you using homebrew? If yes, you should disable the internal updates (`"update.mode": "none",`)

**Comment by bonvi83** [comment]
no I don't use homebrew.

**Comment by bonvi83** [comment]
no fixed

**Comment by bonvi83** [comment]
no fixed

**Comment by bonvi83** [comment]
.

**Comment by daiyam** [comment]
I've tried on x86 and arm64 and I can't replicate the problem...

Can you look into `/Users/<User>/Library/Application Support/VSCodium/logs/<date>/main.log` for errors?
Have you tried to install the new version directly from the DMG?

**Comment by bonvi83** [comment]
Last file main.log

2024-08-12 22:42:03.571 [info] update#setState idle
2024-08-12 22:42:28.192 [info] update#setState checking for updates
2024-08-12 22:42:28.547 [info] update#setState downloading
2024-08-12 22:42:33.592 [info] update#setState downloaded
2024-08-12 22:42:33.592 [info] update#setState ready
2024-08-12 22:44:08.948 [info] Extension host with pid 26158 exited with code: 0, signal: unknown.


And yes I have tried to install a new version from web site, but problem is the same.

**Comment by daiyam** [comment]
> And yes I have tried to install a new version from web site, but problem is the same.

That's weird... So with `1.92.1.24225` installed, when checking for an update, it's download a new update? You don't get any message saying that there is no update available?

What do you get with:
- `wget https://vscodium.now.sh/api/update/darwin-arm64/stable/1ff04139c0ffdd7ef85760b15566fe2de88da2ec` => `204 No Content` (no update for 1.92.1.24225)
- `wget https://vscodium.now.sh/api/update/darwin-arm64/stable/8512cb3341b26a5dba985a9a17eed8d7c3362886` => a JSON file

**Comment by bonvi83** [comment]
if I try to check upgrade, the VSCodium install version 1.91

**Comment by bonvi83** [comment]
ok guys. I restart app and Mac. Now it works!

**Comment by bonvi83** [comment]
ok guys. I restart app and Mac. Now it works!
