### ISSUE TITLE
Have the Flatpak “Code - OSS” Flatpak package reuse the “VSCodium” branding?

### ISSUE THREAD

**Issue by alexander255** [VSCodium/vscodium#199]
I'm not sure if you already considered this, but what is your take on this having the “Code – OSS” flatpak package sharing the branding with this project?

I'm asking because I just opened an issue at their issue tracking regarding this idea and I think a unified branding could help both projects: https://github.com/flathub/com.visualstudio.code.oss/issues/42

Let me know what you think or comment on the other issue, thank you!

**Comment by stripedpajamas** [comment]
If the flatpak project wants to adopt the name or icons of VSCodium, that is fine with me, provided that project is also aligned with the community driven default configuration present in VSCodium. 

Currently the assets produced by the flatpak project are not related at all to VSCodium and they are produced in a very different way. As such, I think the branding ought to be very different to avoid confusion.
