### ISSUE TITLE
AutoUpdate not working

### ISSUE THREAD

**Issue by Novack** [VSCodium/vscodium#1994]
Is auto-update supossed to be working? I could not find much info, there is an old [discussion ](https://github.com/VSCodium/vscodium/issues/41)from back in 2018 where guys describe the autoupdate implementation.

However even though it shows me available updates, it wont auto-update: will send me to the package download url on the browser instead.

I am not sure this is expected or a wrong configuration/issue on my part.

These are my settings:
![image](https://github.com/user-attachments/assets/346cc338-4553-4f11-af9c-610f6252ba5b)

This is my current VSCodium info (though its been like this for a long time, is not a new behaviour):
> Version: 1.92.1
> Release: 24225
> Commit: 1ff04139c0ffdd7ef85760b15566fe2de88da2ec
> Date: 2024-08-12T13:12:03.718Z
> Electron: 30.1.2
> ElectronBuildId: undefined
> Chromium: 124.0.6367.243
> Node.js: 20.14.0
> V8: 12.4.254.20-electron.0
> OS: Windows_NT x64 10.0.19045

**Comment by daiyam** [comment]
> will send me to the package download url on the browser instead

It send you to the url because it can't detect how it was installed and so which installer to download and execute.

The update process doesn't support the Portable Mode, same as Visual Studio Code (cf note in https://code.visualstudio.com/docs/editor/portable).

**Comment by Novack** [comment]
@daiyam thank you so much for the clarification, I've been bumping my head on the wall for sometime now, but didn't noted the obvious. 

Im closing this one.
