### ISSUE TITLE
New Window does not respect Zoom In

### ISSUE THREAD

**Issue by brettwilcox** [VSCodium/vscodium#1995]
**Describe the bug**

When opening a `New Window` it does not respect the existing zoom.

**To Reproduce**

1. Open VSCodium
2. View -> Appearance -> Zoom In
3. File -> New Window

**Expected behavior**

When opening a new window, the screen size should be the same.

**Screenshots**

Zoom In
<img width="502" alt="image" src="https://github.com/user-attachments/assets/6d5cf64d-e9f3-4d6c-a592-393f11e1adac">

Open New Window
<img width="413" alt="image" src="https://github.com/user-attachments/assets/f66e770c-ad2e-40fd-8523-689cbaa851f6">

Here is a screenshot showing the issue
<img width="984" alt="image" src="https://github.com/user-attachments/assets/ad5913dd-0e36-4182-bbef-6bf277b798a7">

**Desktop (please complete the following information):**
 - OS: Debian 12 + Mac OS
 - Architecture: x64, arm64
 - Version: 1.92.2
 - App Manager: apt + brew
 - Sandboxed: No

**Additional context**

I tried this using a fresh install with no extensions. It's happening across both Debian 12 KDE and Mac OS. The behavior is not happening with VSCode. 

If you try closing all windows and opening, it comes back up with one screen zoomed in and the other not.

<img width="136" alt="image" src="https://github.com/user-attachments/assets/e339d390-e89d-4170-bd2d-feb580e89859">

If you close the zoomed in window while the zoomed out window is open then close the app, it will open a new session with the window zoomed out.

**Comment by daiyam** [comment]
I have the same issue with Visual Studio Code.

**Comment by brettwilcox** [comment]
After some searching, I found the `window.zoomPerWindow` setting and unchecked the box. This sets the behavior to what I was expecting, but still differs from Visual Studio Code behavior. I verified that this setting is checked in Visual Studio Code.

<img width="568" alt="image" src="https://github.com/user-attachments/assets/24203f54-1039-4be8-8db2-194c142e3cb9">

**Comment by daiyam** [comment]
Yep, I was going to reference (https://github.com/microsoft/vscode/issues/214926)

Using `"window.zoomPerWindow": false,` gives your expecting behaviour on VSCodium.

**Comment by brettwilcox** [comment]
Thank you @daiyam!
