### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by mr-ubik** [VSCodium/vscodium#2]
Releasing this as an AUR package should not be too complicated. If I manage to find the time I will do a PR, in the meantime here's the issue.

**Comment by WebReflection** [comment]
I was just looking for that ... `visual-studio-codium-bin` would nail it 😂

**Comment by WebReflection** [comment]
Just FYI, I've done the following and it went up right away without issues.

Worth mentioning I already had VS Code installed so its dependencies might be necessary too.

```sh
yaourt -S --needed --noconfirm \
  fontconfig libxtst gtk3 python \
  cairo alsa-lib nss gcc-libs libnotify \
  libxss gconf glibc debtap

sudo debtap -u

curl -LO https://github.com/VSCodium/vscodium/releases/download/1.26.1/code-oss_1.26.1-1535381775_amd64.deb

debtap -Q code-oss_1.26.1-1535381775_amd64.deb

yaourt -U code-oss-1.26.1-1-x86_64.pkg.tar.xz
```

The **Code - OSS** app at that point will be available through the Desktop (GNOME in my case, just window/special key and type code).

It works !!! Awesome stuff

**Comment by markuman** [comment]
works fine ...but why the hell it installed also opera?

```
...
Pakete (2) opera-55.0.2994.44-1  code-oss-1.26.1-1
...
```

**Comment by markuman** [comment]
No, I have not before.

**Comment by WebReflection** [comment]
Then no, I have not the clue (and doesn't happen in here)

**Comment by MazeChaZer** [comment]
FYI, there is already a free software build of VS Code in the official repositories of Arch Linux, so this probably isn't needed (https://www.archlinux.org/packages/community/x86_64/code/)

**Comment by Calinou** [comment]
@MazeChaZer Does it ship with the extensions gallery enabled?

**Comment by stripedpajamas** [comment]
@WebReflection this is great news. Can you answer @Calinou's question: after installing, are you able to install extensions from the marketplace?

**Comment by WebReflection** [comment]
@stripedpajamas @Calinou my extension worked just fine

![screenshot from 2018-09-19 15-30-22](https://user-images.githubusercontent.com/85749/45757467-bf0d5780-bc23-11e8-987b-e523e7790850.png)

As you can see, template literals with HTML are highlighted now 🎉

![screenshot from 2018-09-19 15-31-25](https://user-images.githubusercontent.com/85749/45757476-c3397500-bc23-11e8-8738-a2e9e74dec62.png)

**Comment by stripedpajamas** [comment]
@WebReflection awesome 🎉
