### ISSUE TITLE
Make a notice in README that build process involves downloading binary packages and binary blobs

### ISSUE THREAD

**Issue by huksley** [VSCodium/vscodium#20]
The build process involves downloading binary blobs and binary packages so it is not a complete build from source

**Comment by stripedpajamas** [comment]
@huksley to confirm, are you talking about the build step where it downloads node debug and node debug 2? as mentioned in https://github.com/Microsoft/vscode/issues/49159

I think it would be good to note this in the README.

**Comment by huksley** [comment]
Yes, 
ffmpeg,
libnode
is binary components it downloads.
