### ISSUE TITLE
No appimage builds since 1.92

### ISSUE THREAD

**Issue by ppp7032** [VSCodium/vscodium#2003]
**Describe the bug**
No appimage builds provided in github releases.

**Please confirm that this problem is VSCodium-specific**
- [*] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [*] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Attempt to download appimage from releases.
2. See there is no appimage build.

**Expected behavior**
There is an appimage build available in github releases.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
appimages may not be important to most, but in some situations it is the only way to get an app working on a platform.

**Comment by Zamony** [comment]
Appimage build is probably disabled  in commit https://github.com/VSCodium/vscodium/commit/41b1e88740d1558be5a5ce9ef1f9d4144a5103ba

**Comment by ppp7032** [comment]
> Appimage build was probably disabled in commit [41b1e88](https://github.com/VSCodium/vscodium/commit/41b1e88740d1558be5a5ce9ef1f9d4144a5103ba)

So a conscious decision was made to remove support for appimage?

**Comment by daiyam** [comment]
> So a conscious decision was made by the project to remove support for appimage?

No, since it's available in the Insiders version (https://github.com/VSCodium/vscodium-insiders/releases/tag/1.93.0.24242-insider)
While there is an error when building `1.92` (https://github.com/VSCodium/vscodium/actions/runs/10674103243/job/29584298631#step:9:1342, runned yesterday)

**Comment by ppp7032** [comment]
I noticed AppImages are back in 1.93.1.24256 so I'm closing this issue.

**Comment by lemonzest79** [comment]
No AppImage build again, last two releases not included, last build with an AppImage was https://github.com/VSCodium/vscodium/releases/tag/1.93.1.24256 could this be fixed please??

**Comment by KnowZero** [comment]
@daiyam That should be solvable by just setting the ENV, no?



```
export ARCH=x86_64
```

in

```
build/linux/appimage/build.sh
```

I tried it and was able to build an appimage:

[https://github.com/KnowZero/vscodium/releases](url)

**Comment by daiyam** [comment]
> That should be solvable by just setting the ENV, no?

Ya, surely. But I don't like this workaround. 
Outside the fact that detecting a Javascript to be an `armhf` binary file is bogus, I really would like to be able to specify a version for `pkg2appimage`.
