### ISSUE TITLE
使用插件SVN问题

### ISSUE THREAD

**Issue by git10135405** [VSCodium/vscodium#201]
vscodium版本1.35.1
win7旗舰版64位

在使用插件：
名称:SVN
id: johnstoncode.svn-scm
说明: Integrated Subversion source control
版本: 1.54.0
发布者: Chris Johnston
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=johnstoncode.svn-scm
在使用该插件时经常遇到如下图所示情况，vecode暂无此情况发生。就是放着一段时间或锁屏一端时间后看到如下图，update一直加载不出来
![image](https://user-images.githubusercontent.com/35558611/59592229-32e08000-9122-11e9-8dbb-e917eaa15922.png)

**Comment by stripedpajamas** [comment]
Can you log an issue with in the extension repo to see if they can troubleshoot? https://github.com/JohnstonCode/svn-scm/issues

The extension might not support VSCodium and might need to be updated as such.
