### ISSUE TITLE
Alpine ARM64 builds failing

### ISSUE THREAD

**Issue by andrewhertog** [VSCodium/vscodium#2012]
**Describe the bug**
It appears that the alpine-arm64 build is failing. [This](https://github.com/VSCodium/vscodium/actions/runs/10350055015/job/28651185813#step:7:600) appears to have been the first appearance of it. Seems like the image being used by VSCode to pull the node version for the alpine packaging doesn't support the archtype using the image.

[This](https://github.com/VSCodium/vscodium/actions/runs/9841823648/job/27170098283) previous build succeeded, and it looks like the only difference that impacted this was the node version it was trying to pull.

**Please confirm that this problem is VSCodium-specific**
- [ x ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ x ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
See the build links 
This one failed: https://github.com/VSCodium/vscodium/actions/runs/10350055015/job/28651185813#step:7:600
This one succeeded: https://github.com/VSCodium/vscodium/actions/runs/9841823648/job/27170098283

**Expected behavior**
Expect the build to succeed

**Comment by daiyam** [comment]
Thanks for reminding me of the issue. I've fixed it in #2013
