### ISSUE TITLE
deb and rpm metadata is incomplete

### ISSUE THREAD

**Issue by pshem** [VSCodium/vscodium#202]
**Describe the bug**
`codium`'s apt and rpm packages, as built by the [recommended repository](https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo), are missing some metadata that differentiates `codium` from VS Code, such as the license and the project url.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

This is not an issue in VS Code, because it affects things that differentiate `codium` from `code`.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
View the package metadata in a graphical package manager, such as Discover and from the commandline(`apt show` and the `dnf` equivalent).

**Actual behaviour**
For the `deb` package, as seen from Discover(screenshot in screenshots):
- the license is unknown,
- the homepage is that of `code`,
- there is no logo,
- the description talks about VS Code.

For the rpm package:
- the license is correctly set to MIT,
- the url points to VS Code
- the description talks about VS Code,
- no idea on the status of the logo.

**Expected behavior**
The license for both packages should be shown as MIT, the URL should be changed to this repository, the description should explain the difference between the two distributions, and the logo should be displayed in graphical package managers.

**Screenshots**
![apt metadata in Discover](https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/uploads/0fb965d2c7792db0c776654bb160bcab/codium_discover.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 19.04
 - Architecture amd64
 - Version 1.35.1-1560422401

**Additional context**
I have first reported the problem to the deb repository maintainer(@paulcarroty) at https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/issues/15 and been told this is an upstream issue that can only be solved in the `vscodium` repository.

**Comment by stripedpajamas** [comment]
Thanks for reporting this @pshem ! Would definitely like to clean this up. From what I can tell, the source of the information in the packages comes from these files:

- [resources/linux/code.appdata.xml](https://github.com/microsoft/vscode/blob/master/resources/linux/code.appdata.xml)
- [resources/linux/debian/control.template](https://github.com/microsoft/vscode/blob/master/resources/linux/debian/control.template)
- [resources/linux/rpm/code.spec.template](https://github.com/microsoft/vscode/blob/master/resources/linux/rpm/code.spec.template)
- [resources/linux/snap/snapcraft.yaml](https://github.com/microsoft/vscode/blob/master/resources/linux/snap/snapcraft.yaml) (although we haven't gotten Snapcraft for VSCodium working yet)

It should be that we can slightly adjust these files pre-build.

**Comment by stripedpajamas** [comment]
As per #236, we need to make sure the MIT license is reflected properly in deb/rpm.

**Comment by paulcarroty** [comment]
@stripedpajamas can we add `code.appdata.xml`, `debian/control.template`, `code.spec.template` to vscodium repository? Writing tons of regexps to fix this issue seems unproductive.
