### ISSUE TITLE
VSCodium doesn't support architecture 'i386'

### ISSUE THREAD

**Issue by snowkluster** [VSCodium/vscodium#2031]
**i386 not supported**
When trying to update my machine, I see a warning generated by the vscodium repository that says the following 
`N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://download.vscodium.com/debs vscodium InRelease' doesn't support architecture 'i386'`

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Open terminal on Debian / Ubuntu derivative
2. Run `sudo apt update && sudo apt upgrade`
3. Scroll down to see the log
4. See warning `N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://download.vscodium.com/debs vscodium InRelease' doesn't support architecture 'i386'`

**Expected behavior**
The update goes through normally without no warnings or errors in the terminal.

**Screenshots**
![image](https://github.com/user-attachments/assets/2342e48b-5237-4968-b87e-d0c7ce3ab25d)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3 Cinnamon (based on Ubuntu 22.04)
 - Architecture x86_64
 - Version 1.93.1
 - App Manager apt
 - Sandboxed no

**Additional context**
No Additional context

**Comment by daiyam** [comment]
We don't support 32 bits on any OS.

**Comment by m4lvin** [comment]
If you are on `amd64` anyway, then you can avoid the warning by changing the file `/etc/apt/sources.list.d/vscodium.list` to be something like this, with a constraint of the architecture: 
```
deb [arch=amd64 signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg] https://download.vscodium.com/debs vscodium main
```

**Comment by snowkluster** [comment]
> We don't support 32 bits on any OS.

Hi, thanks for the info. I had not previous had this issue with VSCodium Ubuntu repo, and the warning just showed up a few hours ago. 

As commented by @m4lvin, I have updated my source list to avoid the warning
