### ISSUE TITLE
Help > Documentation doesn't open documentation link

### ISSUE THREAD

**Issue by trivikr** [VSCodium/vscodium#204]
**Describe the bug**
The link to documentation is missing

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open VSCodium
2. Click on Help > Documentation
3. Notice that documentation doesn't open, and message `command 'workbench.action.openDocumentationUrl' not found` is displayed

**Expected behavior**
It should open the following documentation link in browser? https://code.visualstudio.com/docs#vscode

**Screenshots**
![image](https://user-images.githubusercontent.com/16024985/59788031-a8ae2e00-927f-11e9-8f2a-aac495dd63cd.png)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Architecture: x86
 - Version: 1.35.1

**Comment by stripedpajamas** [comment]
Thanks for catching this! We are missing the `documentationUrl` field in our `product.json`. This can be added pre-build in the build.sh file. It looks like MS has theirs set to:

```
"documentationUrl": "https://go.microsoft.com/fwlink/?LinkID=533484#vscode"
```
