### ISSUE TITLE
Feature request: zoom on minimap

### ISSUE THREAD

**Issue by nemo701** [VSCodium/vscodium#2044]
[Cudatext](https://cudatext.github.io/) has a very nice feature whereby if you mouse-over the minimap, a pop-up appears with a zoomed-in preview of the text in that part of the document (video attached). Is that something that could perhaps be added to VSCodium, please?

https://github.com/user-attachments/assets/4e5903c9-7e72-4402-a193-ac91137a0929

**Comment by GitMensch** [comment]
that sounds like a good idea; as the minimap is a feature of vscode itself, this feature request should be done there (but check for existing ones first) https://github.com/microsoft/vscode/issues

**Comment by nemo701** [comment]
Thank you :)

I've checked the vscode repository, and as you suggested, it looks like someone else asked for this a couple of years ago (https://github.com/microsoft/vscode/issues/163121). It didn't get enough votes to make the cut, though. Ah well. I guess the authors of cudatext decided to add it anyway.
