### ISSUE TITLE
vscodium-server?

### ISSUE THREAD

**Issue by Axelen123** [VSCodium/vscodium#205]
I really liked the coder server (https://coder.com). It is open-source and licensed under MIT at https://github.com/cdr/code-server. Maybe create a fork that uses vscodium instead of regular vscode?

**Comment by aral** [comment]
Would also love to see this :)

(And I’m not the only one, apparently: https://freeradical.zone/@prplecake/107747362652042043)

Also see: https://github.com/gitpod-io/openvscode-server
