### ISSUE TITLE
Font Aliasing

### ISSUE THREAD

**Issue by creativetags** [VSCodium/vscodium#2053]
I noticed a difference in the appearance of Font Aliasing between VSCode and VSCodium. When "workbench.fontAliasing": "antialiased" the appearance is noticeably different. I can live with default instead but it was a surprising difference coming from VSCode.

**Comment by daiyam** [comment]
**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS, Ubuntu 20.04, etc]
 - Architecture [e.g. x64, ia32, arm64]
 - Version [e.g. 1.33.0]
 - App Manager [e.g. Winget, Homebrew, Snap, AUR, RPM, Nix, ...]
 - Sandboxed [e.g. no, Flatpak, Snap]

**Comment by creativetags** [comment]
![image](https://github.com/user-attachments/assets/fffe5cf6-f3d1-413a-b61b-97c2ff93e712)

Screenshot shows VSCode in foreground and VSCodium in background. Both have font aliasing set to antialiased.

MacOS 15.0.1 M2 arm64
Version: 1.94.1
Release: 24283
Commit: fe691b6a87017dca963a33a20771a8407349bffb
Date: 2024-10-09T19:34:58.406Z
Electron: 30.5.1
ElectronBuildId: undefined
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

Didn't use App Manager

**Comment by daiyam** [comment]
The VSCode's one seems be in bold.

Can you check the tokens? `Shift+Cmd+P`/`Developer: Inspect editor tokens and scopes`

I don't have the issue on my macOS x86.
From your screenshot, it seems like VSCodium is using `antialiased` and VSCode is using `default` or `auto`.

**Comment by creativetags** [comment]
I'd guess you're not seeing it because your screen is hi-dpi. I'm using a 4k 32" monitor which I run at native resolution. Mac's can render the display at a higher resolution and then scale down to native to give sharper appearance which also makes antialiasing unnecessary. 

Inspect editor tokens and scopes does nothing because there are no tokens in that plain text file (No grammar or semantic tokens available.)

Again showing settings in both. VSCode in foreground:
![image](https://github.com/user-attachments/assets/f4880c56-bb16-4533-8281-9d43de6ee843)

**Comment by daiyam** [comment]
> 'd guess you're not seeing it because your screen is hi-dpi. 

Sadly no. Just a plain 27' at 1440p on macOS 11.
Since it's macos setting, I may not see the difference.

But from what I searched on the net, antialiased text shouldn't appear to be bold.
https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth
https://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/

**Comment by creativetags** [comment]
It's ok, I can live with it. Thanks anyway
