### ISSUE TITLE
Question: Why do you get to modify the original MIT license of VSCode?

### ISSUE THREAD

**Issue by mjbeyeler** [VSCodium/vscodium#206]
This is a question rather than an issue. I just read about MIT licensing and how the only condition to redistribute a modified version of the original code is to keep the MIT license file intact.

So, if that's the case, why are you allowed to modify year and copyright owner of the license?
(the original VSCode has a copyright year of 2015 and is copyrighted to Microsoft)

I'm asking purely out of curiosity.

Best

**Comment by stripedpajamas** [comment]
We are not modifying the original license. The license for the code in this repo is MIT licensed ([this one](https://github.com/VSCodium/vscodium/blob/master/LICENSE)). When we build the binaries, we are pulling the `vscode` repo and running their scripts. If you install VSCodium and go to Help | View License, it opens up the MIT license in the `vscode` repo ([this one](https://github.com/Microsoft/vscode/blob/master/LICENSE.txt?lang=en)). That being said, if we're missing something or should be doing something differently (IANAL), I welcome feedback.

**Comment by mjbeyeler** [comment]
I see. Thanks, everything makes perfectly sense now!
