### ISSUE TITLE
Push the #2056 (product.json) fix to the insiders branch as well

### ISSUE THREAD

**Issue by masterberg** [VSCodium/vscodium#2062]
**Describe the bug**
Product.json issue was fixed on stable, but not yet pushed to insider's build.

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

(Well, technically it is documented, just not merged on insider's branch)

**To Reproduce**
(Same as #2056)

**Expected behavior**
(Same as #2056)

**Comment by daiyam** [comment]
confirmed!

**Comment by daiyam** [comment]
fixed in `1.95.0.24293-insider`
