### ISSUE TITLE
Update Node.js version in build_docker.sh to newer version

### ISSUE THREAD

**Issue by Scriptiee** [VSCodium/vscodium#2065]
Description

The line responsible for downloading Node.js in the build/build_docker.sh script should probably be updated to more recent version Node.js.  Latest one currently is version 23. 

Running plugin remotely can fail as some require version 18 at least (copilot in this case)

Current URL of the line: https://github.com/VSCodium/vscodium/blob/5db0194218b8f140f1f5444b8dfcbacc641e0689/build/build_docker.sh#L31

this probably comes with other modules being updated, so not sure how much of a task this is.

**Comment by kylrth** [comment]
This would fix #2021 I think

**Comment by daiyam** [comment]
`build_docker.sh` isn't used for CI but for cross-platform testing. I haven't used it in age.

**Comment by Scriptiee** [comment]
@daiyam the only reference I could find of the specific node version being installed in the vscodium-reh-linux-x64 package. it's been a while back so can't exactly remember how I ended up on that file any more. Since this was raised the reh package seem to have had it's node updated to 18 so this can be considered fixed.
