### ISSUE TITLE
Help > Introductory Videos don't link to intro videos

### ISSUE THREAD

**Issue by trivikr** [VSCodium/vscodium#207]
**Describe the bug**
The link to "Introductory Videos" is missing

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
- In VSCode, it directs to https://code.visualstudio.com/docs/getstarted/introvideos#VSCode

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open VSCodium
2. Click on Help > Introductory Videos
3. Notice that documentation doesn't open, and message `command 'workbench.action.openIntroductoryVideosUrl' not found` is displayed

**Expected behavior**
It should open the following documentation link in browser? https://code.visualstudio.com/docs/getstarted/introvideos#VSCode

**Screenshots**
![image](https://user-images.githubusercontent.com/16024985/59939010-70d3f180-940b-11e9-840a-b89cc14bce5a.png)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Architecture: x86
 - Version: 1.35.1

**Comment by stripedpajamas** [comment]
Good catch -- very similar situation as #204 -- we need to add the link to the `product.json` file pre-build. MS has this:

```
"introductoryVideosUrl": "https://go.microsoft.com/fwlink/?linkid=832146"
```
