### ISSUE TITLE
Broken template literal type highlight without TypeScript Nightly extension

### ISSUE THREAD

**Issue by greentore** [VSCodium/vscodium#2074]
**Describe the bug**
`infer T extends ...` syntax within template literal types is highlighted incorrectly. It works fine in vanilla VSCode and VSCodium with TypeScript Nightly extension installed from open-vsx. 

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
```ts
type T0 = "100" extends `${infer T extends number}` ? T : never; // 100
type T1 = "100" extends `${infer T extends bigint}` ? T : never; // 100n
type T2 = "true" extends `${infer T extends boolean}` ? T : never; // true
```
Taken from https://github.com/microsoft/TypeScript/pull/48094

**Expected behavior**
Template literal highlight shouldn't leak beyond the closing tick.

**Screenshots**
Broken
![broken](https://github.com/user-attachments/assets/59e14cb4-67a9-4b44-bace-ee9a827f6aa3)
Working
![working](https://github.com/user-attachments/assets/23070576-2687-436c-943e-799fe2e4b1d9)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Architecture: x64
 - Version: 1.94.2.24286
 - App Manager: scoop
 - Sandboxed: no

**Comment by daiyam** [comment]
I can't reproduce the issue on Win10 or macOS.

Have you looked into the logs: `View`/`Output`/`TypeScript`?

**Comment by greentore** [comment]
It looks like my scoop installation is borked. I can reproduce it on 2 computers with fresh profiles, but not if I run a build downloaded from github directly. Sorry for the noise.

**Comment by daiyam** [comment]
So the issue come from scoop?

**Comment by daiyam** [comment]
Hum, I've just tried scoop, no issue...

**Comment by greentore** [comment]
It was caused by `vscode.typescript-1.62.3` in my extensions directory. I guess I copied the whole thing from vanilla vscode years ago. Bisect wouldn't find it as codium was treating it as native extension. Sorry again.

**Comment by daiyam** [comment]
That make sense. No problem.
