### ISSUE TITLE
typo in DOCS.md to open vscodium with terminal

### ISSUE THREAD

**Issue by simooooone** [VSCodium/vscodium#208]
**Describe the bug**
in  vscodium/DOCS.md at the paragraph "How do I open VSCodium from the terminal?" there is a typo. Just tested that to open vscodium on my Fedora 30, I got to give "codium" command instead of "vscodium"

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to terminal
2. Click on type vscodium
4. See bash error

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Architecture x86_64
 - Version 1.35.1

**Comment by stripedpajamas** [comment]
Good catch-- changing the binary name from `vscodium` to `codium` was recent. Will need to update the docs to reflect the change.

**Comment by pshem** [comment]
Looking at github search, there are still 16 files where `vscodium` is present in the repository: https://github.com/VSCodium/vscodium/search?q=vscodium&unscoped_q=vscodium

- [ ] In the `README.md`. Changing it there should include a mention of the previous name for returning users
- [ ] In the AppImage recipe (it appears the .desktop file might not have been renamed)
- [x] In the icons - I don't think there is a point renaming those
- [ ] In DOCS.md
- [x] `check_tags.sh`, `check_tags.ps1` and `update_version.sh` only use it to refer to the repository - shouldn't be changed.
- [ ] `build.sh` - some paces where it's the repository URL, and some places where it's in `product.json`
- [ ] `sum.sh`, `create_zip.sh`, `win32-build.yml`, `sign_dmg.sh`, `sign_mac_app.sh` - should be updated to match the change to the executable name
- [x] `create_appimage.sh` shouldn't be changed
- [x] `CODE_OF_CONDUCT.md` only has a vscodium email address

All in all, 9 places where the new name should be shown to users.

**Comment by stripedpajamas** [comment]
Most of those should not be changed. The project remains VSCodium, the binary is `codium`. The DOCS file should be updated in the section regarding the binary itself (as the OP has mentioned). The `build.sh` file will need to be updated in certain places as per #193.

**Comment by simooooone** [comment]
Can I fix it?

**Comment by stripedpajamas** [comment]
For sure 👍 update screenshot as well if possible

**Comment by simooooone** [comment]
Since I've not a Mac, I can't fix other issues apart those about DOCS.md
