### ISSUE TITLE
Bug when clicking on the File menu. Closing unexpectedly.

### ISSUE THREAD

**Issue by viniciusmelocodes** [VSCodium/vscodium#2088]
Type: <b>Bug</b>

Bug when clicking on the File menu. Closing unexpectedly.

Details:
Version: 1.95.1
Release: 24307
Commit: 8798508b6fcf62248291cdf7a7e870bd84f7257d
Date: 2024-11-02T15:11:51.261Z
Electron: 32.2.1
ElectronBuildId: undefined
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.1.0-26-amd64

VSCodium version: VSCodium 1.95.1 (8798508b6fcf62248291cdf7a7e870bd84f7257d, 2024-11-02T15:11:51.261Z)
OS version: Linux x64 6.1.0-26-amd64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz (4 x 3637)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|4, 5, 5|
|Memory (System)|15.51GB (8.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
vscode-database|baj|2.2.3
captain-stack|cap|0.0.3
vscode-eslint|dba|3.0.10
composer-php-vscode|DEV|1.52.16271
phptools-vscode|DEV|1.52.16271
profiler-php-vscode|DEV|1.52.16271
vscode-html-css|ecm|2.0.10
bootstrap-4-cdn-snippet|eve|1.13.0
bootstrap5-snippets|Han|1.2.5
debugpy|ms-|2024.12.0
python|ms-|2024.18.0
vscode-typescript-next|ms-|5.3.20230808
git-reminder|nhe|0.1.0
material-icon-theme|PKi|5.12.0
postman-for-vscode|Pos|1.4.1
nextjs-snippets|Pul|1.0.2
git-blame|sol|0.2.58
sonarlint-vscode|Son|4.6.0
cody-ai|sou|1.40.1
vscode-sqlfluff|sql|2.3.1
vscode-conventional-commits|viv|1.26.0
gitblame|wad|11.1.1
better-align|wwm|1.1.7

</details>

**Comment by daiyam** [comment]
duplicate #2082
