### ISSUE TITLE
Is it legal to access the Visual Studio Marketplace from VSCodium?

### ISSUE THREAD

**Issue by ltennstedt** [VSCodium/vscodium#209]
Taken from the "Microsoft  Visual  Studio  Marketplace  Terms  of  Use" from January 2019:

1. Use Rights > b. Visual Studio Products and Services

"Marketplace Offerings  are  intended  for  use  only  with  Visual  Studio  Products  and  Services  and  you  may  only  install and  use  Marketplace  Offerings  with  Visual  Studio  Products  and  Services."

**Comment by stripedpajamas** [comment]
Until we get a cease and desist, we will continue offering as many options available in the standard build of `vscode` as possible.
