### ISSUE TITLE
Dark theme issue with extension information page

### ISSUE THREAD

**Issue by mas-co** [VSCodium/vscodium#2091]
**Describe the bug**
Extension information pages (details, features, changelog, &c) do not render properly with dark themes.  If I want to read the text, I must highlight it.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
- [x] Happens with every extension I have tried
- [x] No problem with light themes

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.
I did my best to find anything related to dark themes

**To Reproduce**
1. Use a dark theme.
2. Go to the extension manager.
3. Search for an extension.
4. Attempt to read about the extension in the pane.

**Expected behavior**
I expect the text to be white with a dark background.  Instead, there is black text on a dark background.

**Screenshots**
Please see attached screenshot, below.  Some text is highlighted in order to read it.

**Desktop (please complete the following information):**
 - OS:  Windows 10 Pro (22H2)
 - Architecture:  AMD Ryzen Threadripper
 - Version:  VSCodium 1.95.1 Release 24307
 - App Manager downloaded binary from website
 - Sandboxed:  nope

**Additional context**

That's all folks.  Have a great day!

![Screenshot 2024-11-04 155705](https://github.com/user-attachments/assets/8ff05183-bd4d-4ac4-b9e8-1a8587a060e2)

**Comment by daiyam** [comment]
All colors are controlled by the theme, so bad color = bad theme

![Screen Shot 2024-11-04 at 23 11 06](https://github.com/user-attachments/assets/f3661132-b43c-42b5-bf9d-6e96e2578869)

**Comment by mas-co** [comment]
> All colors are controlled by the theme, so bad color = bad theme
> 

So either all of the pre-installed dark themes have been changed on my system and have very poor colors or there is a problem with VS Codium.   And why does, say, the "Dark Modern" theme have white text in VS Code and not in VS Codium.

No worries.  I will go back to VS Code.

**Comment by mas-co** [comment]
Please note, this was a fresh install, and no settings were altered from the defaults.
I was able to fix this by deleting the settings.json file in the app data folder.  Now it works as expected.
I have no idea why this happened.
