### ISSUE TITLE
atualização

### ISSUE THREAD

**Issue by MiguelDevDeMods** [VSCodium/vscodium#2096]
Type: <b>Bug</b>

Instalei a atualização mas veio em um arquivo .zip extrai ele, procurei e encontrei a pasta do visual studio code arrastei os arquivos para lá e abri e fechei o visual studio code e continuou aparecendo para que eu baixase a atualização, mas não tinha nenhum botão para que atualizace
apenas para baixar o arquivo de atualização e não sei oque fazer para atualizar.

VSCodium version: VSCodium 1.75.1 (c6a9727b801542499d2b59cb7db4224e060fc578, 2023-02-09T22:41:50.017Z)
OS version: Linux x64 6.1.11-200.fc37.x86_64
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|15.52GB (10.90GB free)|
|Process Argv|--ms-enable-electron-run-as-node --extensions-dir /home/lucas/.var/app/com.vscodium.codium/data/codium/extensions --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-pt-BR|MS-|1.75.0
LiveServer|rit|5.7.9

</details>

**Comment by daiyam** [comment]
English mate!

Not sure what's going on since updates are disabled on linux (since you should use your package manager).
Also, you already have the latest version.

Have you modified the `product.json`? Does it have the `updateUrl` property?

**Comment by xgrind** [comment]
Your version is quite old, as we are already on version 1.95.1 and yours is 1.75.1
Is your distro .deb or .rpm based? The best way to install vscodium is through a repository or flatpak.

**Comment by daiyam** [comment]
> Your version is quite old, as we are already on version 1.95.1 and yours is 1.75.1

Good catch! The updates are disabled only since `1.87.0`.

> Also, you already have the latest version.
Oops, I've misread! Doh!

Please update to a newer version or disable the updates in your `settings.json`.
