### ISSUE TITLE
Missing build assets  of  v.1.95.2.24313  for Windows OS

### ISSUE THREAD

**Issue by kotlinFan** [VSCodium/vscodium#2101]
**Describe the bug**
In the list of assets there are no .zips and .exe builds for Windows. All 112 others are there.

**Expected behavior**
Windows is still most popular OS :)

**Comment by leefordjudes** [comment]
Kindly update for windows build also.

**Comment by daiyam** [comment]
Yep, I forgot the validate the signing (done manually) then I had to sleep...

**Comment by daiyam** [comment]
done
