### ISSUE TITLE
VSCodium crashes when accessing the File menu

### ISSUE THREAD

**Issue by sid-the-sloth** [VSCodium/vscodium#2102]
Type: <b>Bug</b>

Installed VSCodium as downloaded from github release: 
`VSCodium-linux-x64-1.95.2.24313.tar.gz `

Cleaned-up all user settings and extensions (removed the `~/.vscode-oss` and `~/.config/VSCodium` folders).

Start VSCodium. Try to access the `File` menu using either the keyboard or the mouse.

Result: VSCodium crashes and exits.

Same bug was experienced with the previous released version.

VSCodium version: VSCodium 1.95.2 (7656a0bea17ba6cf301721572e10c9035bb378e6, 2024-11-08T18:21:12.757Z)
OS version: Debian 12.7 (bookworm)
Kernel: Linux x64 6.1.0-26-amd64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2643 v3 @ 3.40GHz (24 x 3591)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|62.67GB (55.32GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|lightdm-xsession|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by daiyam** [comment]
Duplicate #2082
