### ISSUE TITLE
Curl error (60): SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by Burhanverse** [VSCodium/vscodium#2114]
**Describe the bug**
So I have been using codium for almost a year now and as usual I was updating my machine and got this error;
```
download.vscodium.com                                                                                                                                                                              ???% |   0.0   B/s |   0.0   B |  00m01s
>>> Curl error (60): SSL peer certificate or SSH remote key was not OK for https://download.vscodium.com/rpms/repodata/repomd.xml [SSL: no alternative certificate subject name matches target hostname 'download.vscodium.com'] - https://d
>>> Curl error (60): SSL peer certificate or SSH remote key was not OK for https://download.vscodium.com/rpms/repodata/repomd.xml [SSL: no alternative certificate subject name matches target hostname 'download.vscodium.com'] - https://d
>>> Curl error (60): SSL peer certificate or SSH remote key was not OK for https://download.vscodium.com/rpms/repodata/repomd.xml [SSL: no alternative certificate subject name matches target hostname 'download.vscodium.com'] - https://d
>>> Curl error (60): SSL peer certificate or SSH remote key was not OK for https://download.vscodium.com/rpms/repodata/repomd.xml [SSL: no alternative certificate subject name matches target hostname 'download.vscodium.com'] - https://d
>>> Librepo error: Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```
**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Open terminal and check for update 
2. The error will be shown on Repo updates/checks
3. See error

**Expected behavior**
Well generally the repo check should be success

**Screenshots**
![Screenshot From 2024-11-15 03-11-35](https://github.com/user-attachments/assets/09b60101-a097-4bce-8d6f-5c5537793064)

**Desktop:**
 - OS: Fedora 41 Workstation
 - Architecture x86_64
 - Version 1.95.1.24307
 - App Manager DNF/RPM
 - Sandboxed No

**Comment by ashuping** [comment]
Getting a similar error using Apt on Linux Mint. It looks like the website itself is down - visiting download.vscodium.com on a browser shows this:
![image](https://github.com/user-attachments/assets/fc11c5d5-ea54-427c-9137-7c7544de9498)

**Comment by daiyam** [comment]
@PalinuroSec
