### ISSUE TITLE
VScodium IDE exits with Mouse Over File Menu 

### ISSUE THREAD

**Issue by ENate** [VSCodium/vscodium#2116]
**Describe the bug**

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to 'File Menu'
2. Click on 'File'
3. The Window exits

**Expected behavior**
Will expect the File Menu Dropdown Menu to show up
**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Ubuntu 22.04 LTS
 - Architecture x64
 - Version: 1.95.2
 - App Manager apt, apt-get
 - Sandboxed N/A

**Additional context**

More details:

Version: 1.95.2
Release: 24313
Commit: 7656a0bea17ba6cf301721572e10c9035bb378e6
Date: 2024-11-08T18:21:12.757Z
Electron: 32.2.1
ElectronBuildId: undefined
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.8.0-48-generic

**Comment by daiyam** [comment]
duplicate #2082
