### ISSUE TITLE
Clicking on "File" in the top left closes the code editor.

### ISSUE THREAD

**Issue by Staffed** [VSCodium/vscodium#2123]
**Describe the bug**
Whenever I click on "File" in the top left of the toolbar, it closes the code editor.

This bug doesn't happen if I use **Microsoft's Visual Studio Code**. It only happens in **VSCodium**.

I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Open VsCodium
2. Click on File
3. See error

**Expected behavior**

**Desktop**
 - OS: Pop!_OS 22.04 LTS
 - Architecture: x64
 - Version [e.g. 1.33.0]
 - App Manager: Software Manager
 - Sandboxed: Flatpak

**Comment by daiyam** [comment]
Update to `1.95.3.24321`, it's known bug in `1.95.x` (#2082)
