### ISSUE TITLE
Can we bump the node compile version to 19?

### ISSUE THREAD

**Issue by tadghh** [VSCodium/vscodium#2125]
Some plugins are crashing due to... see the following https://github.com/tamasfe/taplo/issues/703

**Comment by daiyam** [comment]
Hi, here some of previous comments on the current situation with REH:

> For compatibility, reh is still using node-v16.
> You can upgrade to node-v20 by updating the node executable

> Newer Node uses newer LibC not available on all distros.
> 
> > I installed node 20 via nvm, and it is seen in the terminal, but the extension host presumably sticks with the included node version.
> 
> In the `~/.vscodium-server/bin/<uuid>/`, there the binary file `node`. You will to update that file.

_Originally posted by @daiyam in https://github.com/VSCodium/vscodium/issues/2021#issuecomment-2480161942_

**Comment by tadghh** [comment]
> Hi, here some of previous comments on the current situation with REH:
> 
> > For compatibility, reh is still using node-v16.
> > You can upgrade to node-v20 by updating the node executable
> 
> > Newer Node uses newer LibC not available on all distros.
> > > I installed node 20 via nvm, and it is seen in the terminal, but the extension host presumably sticks with the included node version.
> > 
> > 
> > In the `~/.vscodium-server/bin/<uuid>/`, there the binary file `node`. You will to update that file.
> 
> _Originally posted by @daiyam in [#2021 (comment)](https://github.com/VSCodium/vscodium/issues/2021#issuecomment-2480161942)_

conditional compile check? I assumed vscodium was === vscode, if they drop support we drop support no?

**Comment by daiyam** [comment]
> conditional compile check?

No, it's at the bundle step.

> I assumed vscodium was === vscode, if they drop support we drop support no?

I try to keep compatibility when I can. If it's too complex, I drop the support.

I've opened a discussion #2126 about a possible solution.


For the time being, you can drop-in a newer `node` binary, it should work fine.
