### ISSUE TITLE
when i hover or click over file on menubar vscodium crash

### ISSUE THREAD

**Issue by mhakm** [VSCodium/vscodium#2135]
Type: <b>Bug</b>

i use archlinux with sway wayland when i hover over menubar and move between them i can but as soon as i hover over File or simply click it vscodium crash

VSCodium version: VSCodium 1.95.1 (8798508b6fcf62248291cdf7a7e870bd84f7257d, 2024-11-02T15:11:51.261Z)
OS version: Linux x64 6.11.2-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 3499)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|7.51GB (4.85GB free)|
|Process Argv|--enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|sway|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|2.0.11
LiveServer|rit|5.7.9

</details>

**Comment by daiyam** [comment]
Please update to `1.95.3`, it's a known bug in Electron #2082
