### ISSUE TITLE
file encoding options missing

### ISSUE THREAD

**Issue by vw-anna** [VSCodium/vscodium#2140]
**Describe the bug**
In vscode the file encoding of a file is visible in the bottom toolbar:
 ![Screenshot From 2024-12-09 16-51-04](https://github.com/user-attachments/assets/b47e3aec-849c-4418-94e4-99674eace9fe)

When clicking on the file encoding, a menu appears:
![image](https://github.com/user-attachments/assets/99b0d34f-c946-42d2-b8ab-d5a51e8ea96f)

The file encoding options are missing entirely from Vscodium/

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. open a file
2. notice that file encoding options are missing

**Expected behavior**
File encoding options should be displayed as in vscode.

**Desktop (please complete the following information):**
 - OS: [Fedora 42]
 - Architecture [ arm64]
 - Version [1.95.3]
 - App Manager [dnf]

**Comment by daiyam** [comment]
Right-click on the status bar and check `Editor Encoding`

**Comment by vw-anna** [comment]
ah of course i was missing something obvious. 
thanks
