### ISSUE TITLE
Help > Report Issue creates an issue with vscode repository

### ISSUE THREAD

**Issue by trivikr** [VSCodium/vscodium#215]
**Describe the bug**
Help > Report Issue creates an issue with vscode repository

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
- Should codium create issues with codium repository? It can be moved to vscode repository if they're in vscode

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open Codium
2. Click on Help -> Report Issue
3. Populate some test text and click on "Preview on GitHub"
4. Notice that the link opens preview on vscode repo https://github.com/Microsoft/vscode/issues/new

**Expected behavior**
The link opens preview on codium repo https://github.com/VSCodium/vscodium/new

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Architecture: x86
 - Version: 1.35.1

**Comment by shreyasminocha** [comment]
I think that the your expected behaviour is incorrect since this repository is only for VSCodium-specific issues, while most issues are likely to be with VSCode itself.

**Comment by trivikr** [comment]
I also believe that most issues are likely to be with VSCode itself, but since they're logged from Codium should they be created with Codium repo? Codium collaborators can then move the ones related to VSCode to vscode repo.

We can introduce this change to see how many issues are logged from the editor itself. If all the issues are related to VSCode over certain period in time, then this change can be reverted.

**Comment by stripedpajamas** [comment]
Since the program being opened is actually built from the `vscode` repo, I would rather we leave the issue link pointing to the `vscode` repo. This aligns with the feature request link as well. I keep an eye on VSCodium mentioned in the `vscode` repo (https://github.com/microsoft/vscode/search?q=vscodium&type=Issues) and have not seen the need yet to direct more issues here.
