### ISSUE TITLE
download.vscodium.com is down (#1049 again)

### ISSUE THREAD

**Issue by KaKi87** [VSCodium/vscodium#2178]
Cf. #1049

**Comment by Cyrille37** [comment]
Hi

Is not down for me but the https certificate is invalid

```
Err:7 https://download.vscodium.com/debs vscodium InRelease                                                                                    
  Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 138.199.36.10 443]
```

The certificate is for `*.b-cdn.net, b-cdn.net`

Regards.

**Comment by KaKi87** [comment]
The certificate being invalid is a consequence of the site being down, cf. the linked issue.

**Comment by daiyam** [comment]
It just that the CDN hasn't been paid, yet.
It's provided by @PalinuroSec so I don't have any control over it.

**Comment by Cyrille37** [comment]
Incident is resolved. I can update vscodium.

Thanks ! :smile: 

Issue could be closed.
