### ISSUE TITLE
VSCodium crashes

### ISSUE THREAD

**Issue by KAMI911** [VSCodium/vscodium#218]
**Describe the bug**
[error] [VS Code]: render process crashed! in the log. The error message in the IUI:

![kép](https://user-images.githubusercontent.com/5292264/60380506-19570680-9a47-11e9-9bc8-ab9a9dfe76d3.png)

**Please confirm that this problem is VSCodium-specific**
I didn't try that.

**Please confirm that the issue/resolution isn't already documented**
Not documented.

**To Reproduce**
This happens time by time. When I use VSCodium maybe it is more frequent, but today it happened when the app was in the beckground.

**Expected behavior**
No crash.

**Screenshots**
![kép](https://user-images.githubusercontent.com/5292264/60380506-19570680-9a47-11e9-9bc8-ab9a9dfe76d3.png)

**Desktop (please complete the following information):**
 - Linux Mint 19.1
 - Linux mint 5.0.0-15-generic #16~18.04.1-Ubuntu SMP Tue May 7 14:17:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by stripedpajamas** [comment]
This does not sound like a VSCodium-specific issue. Others have experienced it in Visual Studio Code (https://github.com/microsoft/vscode/search?q=render+process+crashed&type=Issues). I recommend you open an issue in the `vscode` repo. They can help you dig deeper into what may be causing it. To get help from them, you may need to install Visual Studio Code,.
