### ISSUE TITLE
Tab moves focus even whtn crtl_m is off

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [VSCodium/vscodium#220]
**Describe the bug**
pressing tab does NOT add a tab character. .

**Please confirm that this problem is VSCodium-specific**
- [ yes] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [yes ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. open editor (I use golang files)
2. press tab
3. observe it not insert a tab but instead select the `problems` tab above the terminal

**Expected behavior**
It should insert a tab character on my cursor

**Screenshots**

**Desktop (please complete the following information):**
 - OS: debian 9.9
 - Architecture x64
 - Version 1.33.1

**Additional context**

**Comment by stripedpajamas** [comment]
Hi @gidoBOSSftw5731 👋 

To confirm, in the task tray of VSCodium "Tab Moves Focus" is not showing? (as it is in [this comment](https://github.com/microsoft/vscode/issues/71345#issuecomment-478506070))

**Comment by gidoBOSSftw5731** [comment]
yes, I even tested it with TMF on

**Comment by stripedpajamas** [comment]
Can you install the latest version and test?

**Comment by gidoBOSSftw5731** [comment]
Sorry for the delay. Issue is present on 1.36.1

```
Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-09T19:18:18.513Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.9.0-9-amd64
```

**Comment by gidoBOSSftw5731** [comment]
Ok I dont know what I did but I went into my keybinds.json and deleted everything, now it works. sorry for the trouble!

Cheers
