### ISSUE TITLE
Remove 32-bit Linux build from .travis.yml

### ISSUE THREAD

**Issue by stripedpajamas** [VSCodium/vscodium#221]
Need to investigate Travis logs.

**Comment by BO41** [comment]
Are you talking about the new version 1.36?
Because of the new Electron version and therefore the new Chrome version, 32bit is no longer supported.
https://code.visualstudio.com/updates/v1_36#_linux-32bit-support-ends
https://electronjs.org/blog/linux-32bit-support

**Comment by stripedpajamas** [comment]
Ah, good catch. We should remove the 32-bit linux build going forward.
