### ISSUE TITLE
VSCodium update check returns 404

### ISSUE THREAD

**Issue by Real-XFaCE** [VSCodium/vscodium#224]
**Describe the bug**
VSCodium always returns a 404 when running a Check for Updates.

**Please confirm that this problem is VSCodium-specific**
- This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click 'Help' -> 'Check for Updates...'
2. See 404 popup.

**Expected behavior**
A message either indicating no new updates or new updates.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Architecture: amd64
 - Version: 1.36.0 (but since update functionality has been introduced)

**Comment by stripedpajamas** [comment]
Are you running the user install or the system install?

**Comment by Real-XFaCE** [comment]
System install.

**Comment by stripedpajamas** [comment]
System install not yet supported.

**Comment by Real-XFaCE** [comment]
Ah I missed that. Here is my workaround script in the meantime (requires some sort of Bash implementation on Windows):

```
#!/bin/bash

releasesURL=https://github.com/VSCodium/vscodium/releases
latestURL=$(curl -fsSLI -o /dev/null -w %{url_effective} $releasesURL/latest)
latestVer=${latestURL##*/}
codeVersion=$(vscodium -v)

trap "exit" INT
if [ "$(printf "$codeVersion" | head -n 1)" != "$latestVer" ]
then
    tempDir=$(mktemp -d)
    pushd $tempDir
        releaseName=VSCodiumSetup-$(printf "$codeVersion" | sed "3q;d")-$latestVer.exe
        awk -v releasesURL="$releasesURL" -v latestVer="$latestVer" -v releaseName="$releaseName" '
            BEGIN {
                a[0] = ""
                a[1] = ".sha256"
                for (i in a) {
                    print releasesURL "/download/" latestVer "/" releaseName a[i] | "xargs wget"
                }
            }
        '
        sha256sum -c $releaseName.sha256 && start $releaseName
    popd
fi
```
