### ISSUE TITLE
The Folding code feature is missing

### ISSUE THREAD

**Issue by hzb** [VSCodium/vscodium#225]
Issue Type: **Bug**

I wrote nodejs in VSCodium, and here are some codes

```
.get("/a", async(ctx)=>{
    //lots of codes
})
.get("/b", async(ctx)=>{
    //lots of codes
})
.get("/c", async(ctx)=>{
    //lots of codes
})
```

And some code blocks have the folding code feature, but some don't have.  

![Screen Shot 2019-07-04 at 12 04 21](https://user-images.githubusercontent.com/535675/60639154-f5832e80-9e53-11e9-9ace-3a5de9dd0d55.png)

![Screen Shot 2019-07-04 at 12 04 32](https://user-images.githubusercontent.com/535675/60639156-f61bc500-9e53-11e9-9069-c5ef91407975.png)

VS Code version: VSCodium 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T18:19:13.191Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 7, 3|
|Memory (System)|8.00GB (1.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|3.0.4
markdown-preview-github-styles|bie|0.1.6

(1 theme extensions excluded)

</details>

**Comment by hzb** [comment]
BTW, I use the latest version

**Comment by stripedpajamas** [comment]
I am not able to reproduce this issue:

![image](https://user-images.githubusercontent.com/2707340/60918297-d7e50900-a247-11e9-9581-f22e459886b7.png)

Have you confirmed that the code folding works on all of your blocks if you use VSCode instead of VSCodium?

**Comment by hzb** [comment]
@stripedpajamas I took a screen recording, you can see here: https://www.dropbox.com/s/7my4iiywm72wxpn/Screen%20Recording%20.mov?dl=0

**Comment by stripedpajamas** [comment]
I see. And do all the blocks have folding options if you open the file up in VSCode instead of VSCodium?

**Comment by hzb** [comment]
The latest VSCode has the same issue, I submitted this bug to them, but
they told me the version of the VSCode that  I use is too old, I don’t
agree with it.

**Comment by hzb** [comment]
BTW. you can see this issue that I submitted to VSCode.

https://github.com/microsoft/vscode/issues/76559

**Comment by stripedpajamas** [comment]
Ok. There isn't any support we can provide if VSCode has the same issue. Any bugs in VSCode will be in VSCodium. If you want the bug fixed, I recommend you post your issue again on the vscode repo but make it clear you are using the latest version of VSCode so that they can troubleshoot and fix it.

**Comment by hzb** [comment]
Got it, I close this issue now and I will append if this is solved.
