### ISSUE TITLE
macOS won't open dmg nor app and claims it is unable to search them for malware

### ISSUE THREAD

**Issue by dschuessler** [VSCodium/vscodium#226]
When downloading dmg from Github and trying to open it:

![Bildschirmfoto 2019-07-10 um 00 30 30](https://user-images.githubusercontent.com/5774545/60927384-085d8f00-a2aa-11e9-9d7f-7f16ba0115fe.png)

Translates to: ""VSCodium.1.36.0.dmg" can not be opened, because Apple can not search for malware in it. This software must be updated. Contact the developer for more information."

A similar error appears when installing with `brew cask install vscodium`:

![Bildschirmfoto 2019-07-10 um 00 33 42](https://user-images.githubusercontent.com/5774545/60927476-64281800-a2aa-11e9-9667-d0594806dbef.png)

I tried with 1.36.0 and 1.36.1.

**Comment by stripedpajamas** [comment]
Hi @dschuessler -- did you follow the instructions in the readme regarding this message? https://github.com/VSCodium/vscodium#install-with-brew-mac

You should be able to open it by right-clicking and choosing Open (first run only).

**Comment by dschuessler** [comment]
It doesn't make a difference. I can not open it either way.

**Comment by optikfluffel** [comment]
@stripedpajamas @dschuessler I think it's right-clicking, and then holding the alt/option key while clicking open 🤔

**Comment by dschuessler** [comment]
Thank you. That does it indeed.

I would have not expected this to be the official workflow for getting the app to run. Is this considered a bug or shall I close this?

**Comment by stripedpajamas** [comment]
You can read the original discussion on the issue in #161, but for now it's not something we can fix (as MS is not notarizing their app).
