### ISSUE TITLE
“VSCodium.app” can’t be opened on OSX

### ISSUE THREAD

**Issue by mudlee** [VSCodium/vscodium#228]
I get this message when installed from brew:

`“VSCodium.app” can’t be opened because Apple cannot check it for malicious software.`.

There is no usual "OK I'm fine with that" button in the preferences/security&privacy :(

<img width="414" alt="osx" src="https://user-images.githubusercontent.com/1439334/61106784-75c21900-a47e-11e9-971a-0f037f452193.png">

**Comment by mudlee** [comment]
An additional comment: after using the standard `code .` command, I realised that it's now VSCodium, so using command line, it starts properly.

**Comment by optikfluffel** [comment]
@mudlee for now you'd have to "right click" the App and then hold the alt/option key, while clicking "Open" (only on first launch I think)

**Comment by meission** [comment]
command$ code

**Comment by christophwolff** [comment]
still an issue.

**Comment by VPetukhov** [comment]
Running `xattr -d com.apple.quarantine /Applications/VSCodium.app` solved the issue for me

**Comment by umitozturk** [comment]
> Running the following solved the issue for me:
> 
> ```
> codesign --sign - --force --deep /Applications/VSCodium.app
> xattr -d com.apple.quarantine /Applications/VSCodium.app
> ```
deleting quarantine only solved my problem. 
`xattr -d com.apple.quarantine /Applications/VSCodium.app`

**Comment by itsabhisek** [comment]
I found that if you go to Applications-> RightClick-> Open it works. And its only required to be done the first time.

**Comment by nicholascloud** [comment]
> @mudlee for now you'd have to "right click" the App and then hold the alt/option key, while clicking "Open" (only on first launch I think)

Worked for me as well. Thanks for the workaround!

**Comment by soriyath** [comment]
> @mudlee for now you'd have to "right click" the App and then hold the alt/option key, while clicking "Open" (only on first launch I think)

This should be in the README.md file.
