### ISSUE TITLE
Update available, no idea how to do it

### ISSUE THREAD

**Issue by BrunoSDomingues** [VSCodium/vscodium#229]
It says the update is available, but when I go to download it, it asks me which program I want to use to open the download and I honestly have no clue which one I should pick. How do I update?

**Comment by snow8gaia** [comment]
Which OS?

**Comment by BrunoSDomingues** [comment]
Arch Linux, KDE plasna

**Comment by stripedpajamas** [comment]
Were you prompted to install an update from inside VSCodium or did it come through Arch Linux? 

Can you also provide how you originally installed VSCodium?

**Comment by BrunoSDomingues** [comment]
I was prompted to download the update from inside VSCodium. I tried to remember how I installed it, but I just can't remember how (yeah I know it seems implausible but I really don't remember, I think I might have used the AUR but I'm not sure).

**Comment by BrunoSDomingues** [comment]
yay just provided me with an option to update VSCodium, all good.
