### ISSUE TITLE
Question - which Win32 release to install? VSCodiumSetup or UserVSCodiumSetup?

### ISSUE THREAD

**Issue by snow8gaia** [VSCodium/vscodium#230]
**Thanks.** 🙂

**Comment by stripedpajamas** [comment]
Up to you! Here is Microsoft's explanation: https://code.visualstudio.com/docs/setup/windows#_user-versus-system-setup

**Comment by snow8gaia** [comment]
Thanks a lot. 🙂

<details>

<summary>titanic wall of text-> click to read</summary>

<p>
Time to download it.
</p>
</details>
