### ISSUE TITLE
Appimage update

### ISSUE THREAD

**Issue by linsui** [VSCodium/vscodium#231]
**Describe the bug**
When I try to download appimage update, it lead me to https://github.com/VSCodium/vscodium/releases/download/1.36.1/VSCodium-linux-x64-1.36.1.tar.gz

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to 'Help'
2. Click on 'Download avalible update'
3. See error

**Expected behavior**
Download appimage

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Architecture x64
 - Version 1.36.0

**Comment by stripedpajamas** [comment]
Hi @linsui 😃 

Currently VSCodium (and I think Visual Studio Code) just provide "archive" updates to the Linux builds. So when VSCodium says an update is ready, it just directs you to that archive. Linux updates would ideally come through different channels, like a package repository (deb, rpm) or by using snap / AppImage. The VSCodium AppImage, which you have installed, does not have update capabilities currently. So updating would require downloading the latest AppImage from the releases page and installing.

**Comment by linsui** [comment]
Thanks for your reply. I'm not sure if I understand you correctly.
Now the updateUrl link to the newest tar.gz package. Could you change the url to the newest appimage package? It seems that all linux package use the same updateUrl?

**Comment by stripedpajamas** [comment]
updateUrl points to an update server (that's consistent across all archs and OS). The code that checks for updates asks the update server if there are any updates based on OS, Arch, and install type (and ultimately commit hash). That is baked into the vscode code, and is not editable by us during build. 

So for Mac builds, the code asks the update server for "Darwin" updates. For Windows there are multiple permutations: win32-x64-system, win32-x64-user, win32-x64-archive, win32-ia32-system, win32-ia32-user, win32-ia32-archive. For Linux builds there are just two: linux-x64-archive and linux-ia32-archive. 

Creating the AppImage is something we do after build (and only applies to x64 Linux build). So the code that checks for updates has no visibility as to whether or not the user used and AppImage, Deb, rpm, or archive to install the software and in any case only knows to ask for one particular kind of update: the archive (tar.gz). 

The shortest path to better updates for AppImage users is to get AppImage update functionality working - this is a feature of AppImages and separate from the code that runs automatically in the VSCodium Linux binaries.

**Comment by linsui** [comment]
Thanks, I got. :smile:

**Comment by darealshinji** [comment]
Hmm. I'm not satisfied with this. If it's hard-coded, can't you just change the URL inside the binary with grep to `https://github.com/VSCodium/vscodium/releases/tag/<version>`? That should work as long as the new URL is the same length or shorter and ends with a null byte.

**Comment by darealshinji** [comment]
> For Linux builds there are just two: linux-x64-archive and linux-ia32-archive.

Can't you just point to the Github download page instead of the tarball? That would be much better for RPM, deb and AppImage users.

**Comment by stripedpajamas** [comment]
You're absolutely right @darealshinji 

Looking at the update logic [here](https://github.com/microsoft/vscode/blob/29c36ae95d5cecc2ae748934199ccb63913e3f76/src/vs/platform/update/electron-main/updateService.linux.ts#L64), it looks like we ought to be pointing to the releases page instead of going straight to the tarball. 

Will move this issue to the update-api so we can track completion. Thanks for calling this out 🙏
