### ISSUE TITLE
deb package adds Microsoft apt repository

### ISSUE THREAD

**Issue by argv-minus-one** [VSCodium/vscodium#234]
**Describe the bug**
The Debian package's postinst script creates a file `/etc/apt/sources.list.d/vscode.list`, which points to a repository containing Microsoft's proprietary VS Code builds, rather than VSCodium.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. `dpkg-deb -e codium_*.deb codium`
2. `less codium/postinst`
3. Scroll to the bottom.
4. See that the URL in the generated `vscode.list` starts with `http://packages.microsoft.com`.

**Expected behavior**
The postinst script should probably not add any file to `/etc/apt/sources.list` at all.

**Desktop (please complete the following information):**
 - OS: Debian
 - Architecture amd64
 - Version 1.36.1, 1.37.0

**Notes:**
This issue was previously reported as #23. The unexpected behavior has apparently reappeared, and I can't reopen it now that it's closed, so I'm opening a new issue about it.

**Comment by stripedpajamas** [comment]
Good catch @argv-minus-one -- it looks like all the logic in the postinstall template is inside a conditional, so we'll have to investigate why we're falling into that block at all.

https://github.com/microsoft/vscode/blob/master/resources/linux/debian/postinst.template#L21
https://github.com/VSCodium/vscodium/blob/master/build.sh#L53

**Comment by annoying258** [comment]
To confirm, is it the deb package from this repo's releases page?

I use the same package on Kubuntu 19.04. Can't remember whether I used dpkg or apt to install it.
I don't have the file in that folder. 

----

Will Post Update here ->

**Comment by argv-minus-one** [comment]
I just downloaded [the deb from the GitHub releases page](https://github.com/VSCodium/vscodium/releases/download/1.37.0/codium_1.37.0-1565373212_amd64.deb), and examined its contents as described above (under “to reproduce”). I did not attempt to install it.

**Comment by annoying258** [comment]
> I did not attempt to install it.

┻━┻ ︵﻿ ╰(゜Д゜)╯︵ ┻━┻

**Comment by stripedpajamas** [comment]
@argv-minus-one I understand that "http://packages.microsoft.com" is mentioned in the post install script... can you confirm that a fresh install using the deb is actually adding that url to /etc/apt/sources.list.d/vscode.list ?
