### ISSUE TITLE
Version 1.37 does not have valid build artifacts 

### ISSUE THREAD

**Issue by in-in** [VSCodium/vscodium#235]
**Describe the bug**
I cannot properly install version 1.37 on Linux Mint
After installation, I cannot run the editor `codium: command not found`

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. on Linux Mint 19.1
2. download package: `https://github.com/VSCodium/vscodium/releases/download/1.37.0/codium_1.37.0-1565290804_amd64.deb`
3. install it: `sudo dpkg -i codium_1.37.0-1565290804_amd64.deb`
4. check version: `codium --version`

**Expected behavior**
Successful installation

**Actual behavior**
`update-alternatives: error: alternative path /usr/bin/codium doesn't exist`
and
`codium: command not found`

**Screenshots**
![192211565309821](https://user-images.githubusercontent.com/8797432/62746061-9a49ea80-ba56-11e9-8f81-a7bdcfe06e5a.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.1 Cinnamon
 - Architecture x86_64
 - Version [1.37.0]

**Additional context**
I installed the previous version (1.36.1) and it works properly
![192211565312006](https://user-images.githubusercontent.com/8797432/62746614-4c82b180-ba59-11e9-9e0a-2ad381f7466a.png)

**Comment by VentGrey** [comment]
Builds seem to be deployed in a wrong way, packages are way too "thin".

**Comment by stripedpajamas** [comment]
Agreed, the latest build has produced bad binaries. I will investigate.

**Comment by aniketbarik** [comment]
Facing the same issue on Ubuntu 19.04. Everything was working fine but on updating via the repo https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs, I can no longer find the icon in menu, can't run it from the terminal either. 

It shows up on running `apt list --installed | grep codium`

On removing and reinstalling Codium I see the following error
`update-alternatives: error: alternative path /usr/bin/codium doesn't exist`

On further investigation, I found that the exec location codium.desktop points to is broken `Exec=/usr/share/codium/codium`

The location `usr/share/codium` doesn't exist on my system.

**Comment by wolviecb** [comment]
Also the missing .tar.gz artefacts is intentional?

**Comment by ekorudiawan** [comment]
I have the same issue after updating codium. I can't find codium in the application menu and can't open via terminal. I use Linux Mint 19.1

**Comment by SuShY28** [comment]
Hello, i have the same problem with this version 1.37.
`WARNING: apt does not have a stable CLI interface. Use with caution in scripts.`
The location usr/share/codium doesn't exist on my system.

**Comment by wennaspeedy** [comment]
Same issue, DEB has 250kb only.

**Comment by crisconru** [comment]
I have the same problem. When I've upgraded from 1.36.1 to 1.37 the program dissapear from my laptop:

Elementary OS 5.0 Juno (Ubuntu 18.04.2 LTS)
Linux 4.15.0-55-generic
GTK+ 3.22.30

**Comment by Guergeiro** [comment]
Yes. Until the bug is fixed, I recommend using 1.36.1.

**Comment by stripedpajamas** [comment]
I am deleting the 1.37 release until I can figure out what happened to hopefully minimize the blast radius.

**Comment by stripedpajamas** [comment]
It looks like MS has done significant work on updating their build process since the last release. I'm working to update the gulp targets we call to conform to the changes.

**Comment by stripedpajamas** [comment]
Have opened PR #237 with changes. I was able to produce the Linux and Darwin builds on this branch using the new gulp targets (and adding a keep alive wrapper for a long running task): https://github.com/stripedpajamas/vscodium/releases/tag/1.37.0

After initial checks run, I will merge and hopefully we will be back to normal.

**Comment by stripedpajamas** [comment]
Builds completed successfully 😅 

It may be another 24 hours before the deb/rpm repository is updated, since that's on a cronjob from @paulcarroty

**Comment by paulcarroty** [comment]
The repository has been updated.

**Comment by ArbanNichols** [comment]
I just ran the apt install and everything works. Nice turnaround time!

**Comment by wolviecb** [comment]
Just updated the gentoo overlay and everything looks good, thanks! Good job :)

**Comment by aniketbarik** [comment]
Just updated from the deb repository. Works perfectly now.
Thanks for fixing it so fast.

**Comment by dirk-olmes** [comment]
> Just updated the gentoo overlay and everything looks good, thanks! Good job :)

Which gentoo overlay is that? I'm currently maintaining my own ebuild but if there's an official overlay I'd like to switch.

**Comment by SuShY28** [comment]
Hello update and it's OK. Thanks for fix this bug !

**Comment by wolviecb** [comment]
> > Just updated the gentoo overlay and everything looks good, thanks! Good job :)
> 
> Which gentoo overlay is that? I'm currently maintaining my own ebuild but if there's an official overlay I'd like to switch.

nopes, not official overlay, just my personal one also :)
