### ISSUE TITLE
DEB package is licenced "proprietary"?

### ISSUE THREAD

**Issue by thebarbershop** [VSCodium/vscodium#236]
**Describe the bug**
The DEB package says it is licensed "proprietary", when it should be MIT.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Download a DEB package from the [releases](https://github.com/VSCodium/vscodium/releases/tag/1.37.0) page. (Tested with both DEBs of 1.37.0 and the DEB of 1.36.1)
2. Open it with a package manager.
3. See License under Details.

**Expected behavior**
I thought the license should be MIT. Does it being provided as a DEB package make any difference? (Or is this a thing with the Ubuntu package manager?)

**Screenshots**
![Screenshot from 2019-08-09 14-54-47](https://user-images.githubusercontent.com/25029365/62757266-b9c43000-bab5-11e9-8781-443f2ca27083.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Architecture: x64
 - Version: 1.36.1, 1.37.0

**Comment by thebarbershop** [comment]
Maybe related to #202 ?
That issue says the license is "unknown", but now it is printing "proprietary." If the root cause is the same, this issue should be closed in favour of that one.

**Comment by LodanZark** [comment]
now the deb files cannot be found in the latest release section

**Comment by stripedpajamas** [comment]
This issue can be taken care of as a part of #202, I will make a note in that issue.

@LodanZark see #235 for more info about latest release. I've removed the Linux build files from the release until we can get it working properly.
