### ISSUE TITLE
Updating Vscodium

### ISSUE THREAD

**Issue by annoying258** [VSCodium/vscodium#238]
**Describe the bug**

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
`Don't use VSCode. will not. Is necessary?`

**Please confirm that the issue/resolution isn't already documented**
:heavy_check_mark:  I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**

open vscodium.
1. Go to the gearbox at the bottom.
2. Click on `CHeck for update`.
3. Scroll down to  Click on download update.
4. A menu appears; select the web browser.
6. Click on  save file.
7. This file is downloaded-> VSCodium-linux-x64-1.37.0.tar.gz

**Expected behavior**
I thought it would download this file->  codium_1.37.0-1565373212_amd64.deb
as I used  amd64.deb to install it first time; from the github releases page.

The gear icon is at the bottom right.
![Screenshot_201908](https://user-images.githubusercontent.com/53851969/62817039-d2802480-bb4d-11e9-87ee-499e4df93399.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 19.04]
 - Architecture [e.g. x64]
 - Version [e.g. 1.36.1]

**Additional context**

In app settings, Update Mode **is manual**.
```
sha256sum VSCodium-linux-x64-1.37.0.tar.gz 
1f4d9f58f05d5b49e8164b0d31087f9704bf1cd8029b4e9064766d540821d02b  VSCodium-linux-x64-1.37.0.tar.gz
```

**Comment by stripedpajamas** [comment]
Hi @annoying258 :wave:

Check out the comments on this issue: https://github.com/VSCodium/vscodium/issues/231

**Comment by annoying258** [comment]
Thanks.
