### ISSUE TITLE
Linux install clarification and repo issues

### ISSUE THREAD

**Issue by evitalis** [VSCodium/vscodium#239]
Didn't feel like the template fit this issue. In the README for Linux packages it says to check the releases. When I do so I see 2 DEBs and two RPMs with slightly different version strings so it is not clear which should be used.

That being said I also attempted to add the repo from GitLab for Fedora but noticed I was still stuck on 1.34 with no updates available. Should an issue be opened on that repo for it being out of date or is it also maintained by this project's team?

**Comment by stripedpajamas** [comment]
The Linux repository repo on Gitlab is not maintained by this team, so you can file an issue there if it's getting out of date.

In regard to having the 2 debs and 2 rpms -- I believe that was a fluke of release 1.37.0 and hasn't happened in the past couple of releases.
