### ISSUE TITLE
Remote Development Extensions don't work on VSCoidum

### ISSUE THREAD

**Issue by watkinsmatthewp** [VSCodium/vscodium#240]
**Describe the bug**

The [Remote Development](https://code.visualstudio.com/docs/remote/remote-overview) extensions do not work on VSCodium. You get errors like "command 'opensshremotes.openEmptyWindow' not found"

**Please confirm that this problem is VSCodium-specific**

- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**

- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**

1. Install the  extension pack.
1. Try to use it to connect to an SSH host
1. You get the error mentioned above

**Expected behavior**

I would expect that extensions that work on VS Code would also work on VSCodium

**Desktop (please complete the following information):**

 - OS: Windows 10 64-bit

**Additional context**

Doing a little digging, my _suspicion_ is that because these extensions are developed by Microsoft, they likely suffer from the same restrictions as the C# extension as documented in #82.  However, a little more Googling suggests that I can modify the product.json to enable it ([source](https://bugs.archlinux.org/task/62822))?

**Comment by magic-k** [comment]
The remote extensions are closed source. The license states that you can only use it with official microsoft products. And the remote server actively prevents OSS versions from connecting. Even if you enable the proposed apis needed, you will get an "Unauthorized client" error message.

**Comment by watkinsmatthewp** [comment]
Yeah I saw that right afterwards :( Sorry

**Comment by markmaas** [comment]
I can whole heartily recommend the use of sshfs (https://www.digitalocean.com/community/tutorials/how-to-use-sshfs-to-mount-remote-file-systems-over-ssh)

**Comment by sixtyfive** [comment]
Unfortunately when you open a folder that's mounted via sshfs, there seems to be no Git integration.

**Comment by sixtyfive** [comment]
Unfortunately it doesn't "see" SSHFS folder mounted via Nemo/Nautilus in the "Open Folder" dialog on Linux, except for in the "Recent" section.

**Comment by pferreir** [comment]
> And the remote server actively prevents OSS versions from connecting. Even if you enable the proposed apis needed, you will get an "Unauthorized client" error message.

Maybe someone should open an issue on the Microsoft repo describing the actual problem? After all, Microsoft is supposed to be Open-Source-friendly these days, right?

**Comment by knopp** [comment]
IICR, one of the issues is the VSDA module shipped with vscode that is used to generate signature for handhake when connecting to remote instance. This module has a binary blob that generates the signature. So other than modifying product.json this extension also needs to be present. I think it was possible to circumvent this for debug builds, but I'm not sure it is anymore.

**Comment by atrauzzi** [comment]
Did a quick tweet: https://twitter.com/alextrauzzi/status/1311452153467170816

Feel free to like and share.

**Comment by ljmf00** [comment]
Seems like they really want to keep Remote SSH only for their closed source release, see https://github.com/microsoft/vscode/pull/107875#issuecomment-702408258 .

**Comment by atrauzzi** [comment]
Really, it's not acceptable. It's time for people to put pressure on Microsoft to allow the remote functionality to be available across the board.

I want to be able to use code from a Chromebook and have the remote coding functionality.

**Comment by Vilasamuni** [comment]
For a long time I've been using SSHFS to mount remote filesystems as recommended by @markmaas above, but recently the source control section of VScodium stopped working with those filesystems. It now says 'no repository detected' when I open the folder on the server.
