### ISSUE TITLE
Not displayed "Status bar"

### ISSUE THREAD

**Issue by doox911** [VSCodium/vscodium#246]
When I set hotkeys to the on / off status bar (ctrl + alt + j) and open any file for editing, the combination does not work and even the parameters do not work. Only after deleting the ./VScode directory and re-setting the settings, it starts working. 

OS Ubuntu 18.04 LTS

**Comment by stripedpajamas** [comment]
Hi @doox911 

Can you provide some more information? What version of VSCodium are you running? Is this a recurring problem or is it fixed now that you've deleted some configuration directory?

Have you tried the same thing in VSCode instead of VSCodium? What was the result?
