### ISSUE TITLE
How to update ?

### ISSUE THREAD

**Issue by sundowndev** [VSCodium/vscodium#248]
I already have 1.34 installed and would like to update, so I tried redownload Codium and install the 1.37 .deb package, it succeed, but it didn't updated the app.

Am I missing something ?

**Comment by CatKasha** [comment]
`vscodium` now have `codium` executable name (https://github.com/VSCodium/vscodium/issues/36)
After installation `codium` you have both `vscodium` and  `codium` apps in your OS

You need delete `vscodium` and `codium` to prevent errors (https://github.com/VSCodium/vscodium/pull/176#issuecomment-501396622), and install `codium` from the package again (also do not forget to save the VSCodium settings)

**Comment by stripedpajamas** [comment]
Hi @sundowndev :wave:

I believe @CatKasha is correct as we switched from `vscodium` to `codium` somewhat recently. Let us know if this issue should still be open.

**Comment by sundowndev** [comment]
Thanks @CatKasha
