### ISSUE TITLE
Windows Explorer right-click menu shows "Open with VSCodium", pressing underlined S creates shortcut instead

### ISSUE THREAD

**Issue by jimbo1qaz** [VSCodium/vscodium#250]
**Describe the bug**
When I install VSCodium and right-click a file or folder, the "Open With VSCodium" has the S underlined, but when I press S, it creates a shortcut instead of opening with vscodium.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install VSCodium (maybe you need to enable adding Windows Explorer right-click menu options)
2. Open Windows Explorer, focus (click) a file, and press the keyboard right-click menu key
3. See the vscodium entry, notice S is underlined, and try to press S
4. It creates a shortcut instead of opening vscodium

**Expected behavior**
The underlined key opens vscodium.

https://github.com/VSCodium/vscodium/blob/f787c21b3cfa021f1541362d26ee597445de063a/build.sh#L49 shows that "V&SCodium" and the S is meant to be underlined.

Opening ShellMenuView and searching `codium`, vscodium creates 4 registry entries and uses "Open W&ith V&SCodium" for all 4, indicating both "ith" and "SCodium" are "meant" to be underlined, but the second underline overrides the first.

I think the second ampersand should be removed, since there shouldn't be two ampersands, and the current setup makes it difficult to open a file in vscodium via the keyboard alone. (With the second ampersand removed, I can open files in vscodium in two keystrokes, by pressing "menu" key and "i".)

Honestly this issue may be language-specific, and "pressing S creates shortcut" is the case in English but possibly not other languages. But having 2 underlined keys seems like a bad design in of itself. Was it done to avoid clashing with `Open W&ith Code` or similar?

**Screenshots**

![vscodium](https://user-images.githubusercontent.com/913957/64082013-9f98fe80-ccbd-11e9-948e-d4a1b242e208.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Architecture x64
 - Version 1.37.1

**Additional context**

**Comment by stripedpajamas** [comment]
Thanks for calling this out @jimbo1qaz ! When I first wrote the build script and included the changes to product.json, I really had no idea what the ampersand affected. Your explanation makes a lot of sense.

To clarify -- is the recommendation to change  `win32ShellNameShort='setpath(["win32ShellNameShort"]; "V&SCodium")' ` to  `win32ShellNameShort='setpath(["win32ShellNameShort"]; "VSCodium")' ` ?

**Comment by jimbo1qaz** [comment]
That seems like a reasonable change to make, and replicates what I did manually to the registry. I hope it doesn't have any unexpected side effects though.
