### ISSUE TITLE
Possibilty to install the vscodium via ppa

### ISSUE THREAD

**Issue by nazarepiedady** [VSCodium/vscodium#252]
HI everyone, I hope you are well.
Well my question is, when will we have possibility to install vscodium via ppa?
Or would be better consider the possibility to have the text editor package added by default on linux repositories like Ubuntu or Debian?

**Comment by stripedpajamas** [comment]
Most likely we would only support PPA if Microsoft started supporting it upstream. 

Installing on Linux through a repository can be done by following the instructions here: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo

Any extra energy we have to make Linux installs less painful will go toward getting a Snap package setup for VSCodium (#102) as that is currently supported by Microsoft for Visual Studio Code.
