### ISSUE TITLE
Make Update Download Folder Unique

### ISSUE THREAD

**Issue by jeffrson** [VSCodium/vscodium#254]
The automatic update mechanism in VSCodium appears to be broken.

Sometimes an update is reported and installed again when it had been installed previously. This happens even when this new version will be cleanly installed. This happened to me with 1.37. After some days it seems to be fixed magically.

Now, with 1.38, VSCodium again and again tries to "update" with VS Code...

I'm not sure how I can help with system information. It's Windows 10, and I'm currently using Codium and VS Code in parallel.

**Comment by matrixraven** [comment]
I installed 1.38.1 manually tonight (W10 Pro), and the check for updates item in the help menu triggers a "server returned 404" error. Update definitely seems broken.

**Comment by drasbeck** [comment]
I am getting the same result, trying to update from 1.38.0 on W10 Pro.

**Comment by stripedpajamas** [comment]
Hi @jeffrson (and others who commented). This is a known issue and has happened in the past couple of versions released. It doesn't get fixed magically -- someone reports it and we troubleshoot it and then push a fix.

Some more info needed to properly troubleshoot it this time:
- what installer are you using for vscodium? system or user?
- what architecture are you on? 32-bit or 64-bit?

**Comment by matrixraven** [comment]
User. 64-bit. Happy to give any other info you need.

**Comment by drasbeck** [comment]
Of course. 64-bit system installer.

**Comment by stripedpajamas** [comment]
@TroySchmidt @linsui @mdavis199 have any of you had update problems with the latest release? I'm unable to reproduce the issue here, but it sounds very similar to what was happening in 1.36 for you all.

**Comment by mdavis199** [comment]
I'm running version 1.38.1.  (Windows 10 x64 Ent, 1809). I had no problems with this release. Thanks.

**Comment by TroySchmidt** [comment]
I am not having issues either.

**Comment by linsui** [comment]
VSCodium-win32-x64-1.38.1.zip, no problem here.

**Comment by jeffrson** [comment]
Well, as it seems (on Windows at least), as long as "%temp%\vscode-update-user-x64" contains the VSCode update, the correct update to VSCodium will *not* be downloaded and VSCode instead will be installed again and again.
You probably should change the name of the download folder.

**Comment by TroySchmidt** [comment]
@jeffrson are you running both VS Code and VS Codium in tandem?  I am only running Codium and have no issues still.

**Comment by jeffrson** [comment]
Yes, did not uninstall it when I started to try VSCodium.

And, you know, bug reports require to test with VSCode as well.

**Comment by stripedpajamas** [comment]
Good call out @jeffrson ! This makes a clear action item for this issue.

**Comment by stripedpajamas** [comment]
Unfortunately the 'vscode' part of the path is fixed: https://github.com/microsoft/vscode/blob/master/src/vs/platform/update/electron-main/updateService.win32.ts#L58

I think our only option is to patch this file pre-build to set the path to `vscodium-update-...`
