### ISSUE TITLE
VSCodium still accessing MS data gathering URLs

### ISSUE THREAD

**Issue by Unlearn** [VSCodium/vscodium#26]
Running the latest build of VScodium on maxOS High Sierra.

As reported by the Little Snitch firewall. The binary is trying to access telemetry domains:

`dc.services.visualstudio.com` 
`dc.trafficmanager.net`
`vortex.data.microsoft.com`

These are MS data gathering URLs. If one of the intentions of this project is to disable Telemetry it would be good to remove the communication to these.

There has been quite a bit of discussion around this on the VScode github page:

https://github.com/Microsoft/vscode/issues/16131

And on Reddit:

https://www.reddit.com/r/privacy/comments/80d8wu/just_realised_that_visual_studio_code_sends/

Telemetry in VSCode can be turned off, but not fully. Instead of disabling it altogether, they just register that you have it turned off, the server communication still happens. 

The URL `https://vortex.data.microsoft.com/collect/v1` is referenced in the VSCode source, so it could be replaced with something innocuous via Sed, that doesn't stop the other domains or any future ones they add. The others are likely added via the code's npm/build dependencies. 

So it may be best to just simply add information on the "issue" and instructions to this projects README.MD to work around the problem by utilising your local hosts file to block the domains.

eg. Adding the line to your `/etc/hosts` file:

`0.0.0.0 dc.services.visualstudio.com dc.trafficmanager.net vortex.data.microsoft.com`

I'm interested in hearing what others think about this.

**Comment by stripedpajamas** [comment]
This is so sad. Thank you @Unlearn for bringing this up. I will begin immediately investigating what we can do about this. Best case scenario we make some small edits to the vscode codebase before build and stop everything. If that ends up not being possible, we'll go forward with what you said about updating the README.

**Comment by stripedpajamas** [comment]
I am also using Little Snitch and have seen the same things reported by @Unlearn with the exception of `dc.trafficmanager.net` -- I see no traffic to this URL (and I do not find any mention of it in my findings below). @Unlearn can you confirm that the traffic is coming from VSCodium and if so dig in a little? I'm wondering if maybe it's a particular extension you have installed? Or is there something you have to do after opening VSCodium to trigger this traffic?

I've found that after installing dependencies it's easier to track down where the traffic is originating from.

Found so far:
- the npm module [`applicationsinsights`](https://www.npmjs.com/package/applicationinsights) is responsible for all calls to `dc.services.visualstudio.com`
- the npm module [`vscode-extension-telemetry`](https://www.npmjs.com/package/vscode-extension-telemetry) is responsible for calls to `vortex.data.microsoft.com` as well as:
  - [`build/lib/stats`](https://github.com/Microsoft/vscode/blob/master/build/lib/stats.ts)
  - [`src/vs/platform/telemetry/node/appInsightsAppender`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/telemetry/node/appInsightsAppender.ts)

**Comment by paulcarroty** [comment]
`vscodium  14647   paul  119u  IPv4 556476      0t0  TCP localhost.localdomain:33380->13.107.6.175:https (ESTABLISHED)`

Just after the app start.

**Comment by stripedpajamas** [comment]
@paulcarroty I believe that is the Marketplace and is expected behavior. Since VSCodium uses Microsoft's Marketplace for extensions, it will call out checking for updates and such. 

```bash
$ host marketplace.visualstudio.com
marketplace.visualstudio.com has address 13.107.6.175
```

**Comment by Unlearn** [comment]
Hi @stripedpajamas, thanks for the prompt response. 

Looking at the origin of dc.trafficmanager.net, it perhaps came from an extension. Testing further, on my clean install it was not referenced. It was referenced in discussions about the topic, so may be worth keeping an eye out for. 

The fixes in place look good. I will be a continuing user of VSCodium so will monitor for any further telemetry that MS adds.

**Comment by paulcarroty** [comment]
I recommend to create regex and patch all files with these domains.
