### ISSUE TITLE
RPM package out of date

### ISSUE THREAD

**Issue by nsolerqwork** [VSCodium/vscodium#261]
**Describe the bug**
#257 changes aren't reflected on the RPM build. I'm having the same issues reported on #256 on CentOS 7 as of October 8th 2019.

**Please confirm that this problem is VSCodium-specific**
This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
I checked the issues page from #257 to this day and there isn't an issue mentioning this.

**To Reproduce**
1. Go to https://vscodium.com/
2. Follow the RPM install steps
3. Run codium --verbose
4. Same error happens as #256

**Expected behavior**
#257 changes should be present in the RPM, and they are not.

**Screenshots**
![Captura de pantalla de 2019-10-08 14-38-55](https://user-images.githubusercontent.com/49989497/66418882-6dc03980-e9d9-11e9-99e2-624a49b1d98a.png)

**Desktop (please complete the following information):**
 - OS: CentOS 7.7
 - Architecture: x86_64

**Comment by stripedpajamas** [comment]
PRs being merged are reflected in the next release. There hasn't been a release since the PR was merged. When MS releases their October version, VSCodium will build again with these changes. If the issue persists after the next release we will reopen the issue.
