### ISSUE TITLE
Icon in release notes tab need to be replaced

### ISSUE THREAD

**Issue by linsui** [VSCodium/vscodium#263]
**Describe the bug**
Icon in release notes tab need to be replaced.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to 'help -> Release Notes'

**Screenshots**

![2019-10-10 22_36_46-Release Notes_ 1 39 0 - 工作区 (工作区) - VSCodium](https://user-images.githubusercontent.com/36977733/66578905-75afe300-eb6b-11e9-846c-087f3c82abfa.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Architecture x64
 - Version 1.39.0

**Comment by stripedpajamas** [comment]
Looks like they moved the source of the file we were overwriting (https://github.com/microsoft/vscode/commit/f6df256c60892c0b31f70a5a872c5d9a1559d126#diff-c680307e5b549ac6eedabec2b4bc6b5a)

Will open a PR to adjust the path on our side as well.
