### ISSUE TITLE
Setup a WebHook to automatically detect and trigger new VSCodium builds

### ISSUE THREAD

**Issue by cyfrost** [VSCodium/vscodium#264]
Hi, thanks for working on VSCodium.

I noticed what might become an issue for many users of VSCodium: A few hours ago, MS [released](https://github.com/microsoft/vscode/releases/tag/1.39.1) the recovery build (v1.39.1) for the September release of VSCode. I was trying to find the VSCodium builds for it but couldn't find it. After searching through the issues, I [found](https://github.com/VSCodium/vscodium/issues/197#issuecomment-501513328) a relevant answer from @stripedpajamas where you said that the "probe and cut new self-builds" process occurs once every 24 hours automatically. But wouldn't it be nice to have a [GitHub Integration WebHook](https://developer.github.com/v3/activity/events/types/#releaseevent) setup with VSCode's repo to automatically trigger and cut new builds without any delay? That'll help us get the newer builds almost at the same pace as upstream releases.

For instance, v1.39.1, which was out today, contained an [important fix](https://github.com/microsoft/vscode/commit/7f87a64621b010ed8a7e171d07583921e8c1e8ac) for a potential security [vulnerability](https://github.com/microsoft/vscode/issues/82296), so getting the update faster becomes all the more important.

**Comment by stripedpajamas** [comment]
👏 👏 👏 

Completely agree; I will look into setting this up.

**Comment by stripedpajamas** [comment]
@cyfrost actually I feel like I looked into this a while ago, but maybe I misunderstood the documentation. Isn't it true that only the repository owner can setup a webhook for the events that happen in that repository? In our case, we want notifications from the vscode repo to call a webhook that would trigger our VSCodium build on Travis.

**Comment by cyfrost** [comment]
@stripedpajamas Thanks for the reply, you're correct, only the owner of the repository can setup webhooks. We can try raising an issue at upstream asking them to setup a webhook for us but I don't think it'll end well, so instead, I've setup an opensource mirror of upstream [here at this gitlab repository](https://gitlab.com/cyfrost/vscode-mirror/), and Thanks to the "Tag Push Events" webhook offered in GitLab's repository integrations, we are now able to reliably tell when there's a new release and trigger Travis builds of VSCodium.

For demo purposes, I have created two sample webhooks of my mirror:

1. This hook gets triggered on each new commit pushed to `master` of upstream: [Test the webhook here](https://webhook.site/#!/95df740d-2a33-4d7c-b274-d123220fdb16)

2. This hook gets triggered whenever there's a new release of upstream: [Test the webhook here](https://webhook.site/#!/603ba788-fe5b-4da1-9273-ff95909e734e/a4529c04-31c4-468d-902f-c28fef57bbe3/1)

Unfortunately, unlike the first hook, testing the 2nd hook will require a new release from upstream. Alternatively to test new Release events, there's a Test button in the Integrations page of the repository.

**Comment by cyfrost** [comment]
@stripedpajamas Thanks for the reply. You're correct, only the owner of the repository can setup webhooks. We can try raising an issue at upstream asking them to setup a webhook for us but it may or may not happen.

Although for our testing purposes, I've setup an opensource mirror of VSCode on GitLab [here](https://gitlab.com/cyfrost/vscode-mirror/). Since it's a mirror, all changes are updated automatically, and thanks to the "Tag Push Events" webhook offered in this mirror repository, its possible to reliably tell when there's a new release and have Travis run.

For demo purposes, I've setup two simple webhooks of my mirror:

1. This hook gets triggered on each commit pushed to `master` of upstream: [Test the webhook here](https://webhook.site/#!/95df740d-2a33-4d7c-b274-d123220fdb16)

2. This hook gets triggered whenever there's a new release upstream: [Test the webhook here](https://webhook.site/#!/603ba788-fe5b-4da1-9273-ff95909e734e/a4529c04-31c4-468d-902f-c28fef57bbe3/1)

~~Unfortunately, testing the 2nd hook will require a new release from upstream.~~ To test new Release events, there's a Test button in the Integrations page of the repository.

I've added you (on GitLab) as a repository maintainer of my mirror so you can test out the integrations, please let me know how it goes.

**Comment by cyfrost** [comment]
Update: today's release of v1.40 upstream has triggered our dummy webhook [here](https://webhook.site/#!/603ba788-fe5b-4da1-9273-ff95909e734e/a4529c04-31c4-468d-902f-c28fef57bbe3/1), it is working as expected.

**Comment by stripedpajamas** [comment]
Thank you for setting this up, @cyfrost; I think this will work perfectly. Action item to close out this issue would be to implement a handler (probably keeping the code in the github.com/vscodium org) that can be called from the Gitlab webhook that triggers Travis and Azure for builds.
