### ISSUE TITLE
Checksum failure in DNF

### ISSUE THREAD

**Issue by stefanfluit** [VSCodium/vscodium#265]
[MIRROR] vscodium-1.39.1-x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 7e2e471736cb4539de316788618e3f7c804a7d4d6c2821b8e3f21d50a71276e4(sha256)  Expected: ff5d730b8fc826ce2380a804840af235daf22c9142429efef97cc4be8dd5f84e(sha256) 
[MIRROR] vscodium-1.39.1-x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 7e2e471736cb4539de316788618e3f7c804a7d4d6c2821b8e3f21d50a71276e4(sha256)  Expected: ff5d730b8fc826ce2380a804840af235daf22c9142429efef97cc4be8dd5f84e(sha256) 
[MIRROR] vscodium-1.39.1-x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 7e2e471736cb4539de316788618e3f7c804a7d4d6c2821b8e3f21d50a71276e4(sha256)  Expected: ff5d730b8fc826ce2380a804840af235daf22c9142429efef97cc4be8dd5f84e(sha256) 
[MIRROR] vscodium-1.39.1-x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 7e2e471736cb4539de316788618e3f7c804a7d4d6c2821b8e3f21d50a71276e4(sha256)  Expected: ff5d730b8fc826ce2380a804840af235daf22c9142429efef97cc4be8dd5f84e(sha256) 
[FAILED] vscodium-1.39.1-x86_64.rpm: No more mirrors to try - All mirrors were already tried without success

**Comment by stripedpajamas** [comment]
Please provide more detail -- steps to reproduce? OS/arch?

**Comment by AntonOellerer** [comment]
I have a similar error 
```
[MIRROR] vscodium-1.40.2-x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 230cec74aa518a39e55093e4375ff8f798e47a4decb3215d2a2063da64c193c5(sha256)  Expected: 030ca1c7499bf07904679b643ddc9fd1bb05b954ca6e8c6a172ddc3bb35325c7(sha256) 
[MIRROR] vscodium-1.40.2-x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 230cec74aa518a39e55093e4375ff8f798e47a4decb3215d2a2063da64c193c5(sha256)  Expected: 030ca1c7499bf07904679b643ddc9fd1bb05b954ca6e8c6a172ddc3bb35325c7(sha256) 
[MIRROR] vscodium-1.40.2-x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 230cec74aa518a39e55093e4375ff8f798e47a4decb3215d2a2063da64c193c5(sha256)  Expected: 030ca1c7499bf07904679b643ddc9fd1bb05b954ca6e8c6a172ddc3bb35325c7(sha256) 
[MIRROR] vscodium-1.40.2-x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 230cec74aa518a39e55093e4375ff8f798e47a4decb3215d2a2063da64c193c5(sha256)  Expected: 030ca1c7499bf07904679b643ddc9fd1bb05b954ca6e8c6a172ddc3bb35325c7(sha256) 
[FAILED] vscodium-1.40.2-x86_64.rpm: No more mirrors to try - All mirrors were already tried without success                                                                                                                                 
```
on Fedora 31 
```
$ uname -a Linux xxx 5.3.12-300.fc31.x86_64 #1 SMP Thu Nov 21 22:52:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

| Package | Architecture | Version               | Repository                           | Size |
|---------|--------------|-----------------------|--------------------------------------|------|
| codium  | x86_64       | 1.40.2-1574798730.el7 | gitlab.com_paulcarroty_vscodium_repo | 80 M |

**Comment by AntonOellerer** [comment]
Link to the error on gitlab:
https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/issues/22

**Comment by paulcarroty** [comment]
Please close this issue here, no sense to discuss it everywhere. I'll take a look.
@stripedpajamas @stefanfluit
