### ISSUE TITLE
[Discussion] Codium Remote

### ISSUE THREAD

**Issue by notpushkin** [VSCodium/vscodium#266]
As discussed in #196 and #240, Microsoft's proprietary Remote extensions aren't usable in OSS builds (insiders versions might be, though – see https://github.com/microsoft/vscode-remote-release/issues/574). Perhaps we could look into making an open source replacement of our own, based on the stubs that _are_ provided in the source code?

**Comment by watkinsmatthewp** [comment]
I would love to see this as my current company does not approve the pre-built binaries from MS so we all use VSCodium and would love to use Remote extension functionality.

**Comment by stripedpajamas** [comment]
Yeah that would be super cool. I don't have the capacity to contribute to that currently, but would help out where possible.

If insiders currently supports unlicensed builds, it may mean that the standard version will support them in the near future; also a hope is to get VSCodium automated builds of the insider's version in the near future (#148). That would potentially unblock using the remote extensions without a big effort building from piecemeal.

**Comment by alexandrudsc** [comment]
hello, any news on this? I love vscodium as is, but I would like to use this as well

**Comment by kmantel** [comment]
In the meantime, [ponyssh](https://marketplace.visualstudio.com/items?itemName=thingalon.pony-ssh) has done what I needed

**Comment by sarpik** [comment]
@kmantel 
> In the meantime, [ponyssh](https://marketplace.visualstudio.com/items?itemName=thingalon.pony-ssh) has done what I needed

Yeah that might be cool, but we'd still prefer the actual remote development extensions.

Any news here?

**Comment by notpushkin** [comment]
@sarpik Pony SSH could be a good start though? :thinking:

**Comment by dalisoft** [comment]
Pony SSH asks my remote server SSH password even i loaded it to agent, so, looks like insecure( I really want use SSH remote development

**Comment by LaurianoElmiroDuarte** [comment]
any news of remote access to the remote-ssh ?

**Comment by gyzerok** [comment]
I am interested in contributing my time to create an ssh extension. If anybody has any pointers as to where should I start, they are very welcome.

My initial understanding is that I will need to figure out how to start vscode headless to use it for the "server" and develop an extension which will register different providers remotely.

**Comment by Lcchy** [comment]
I was looking for a solution to this and found something on the way but I'm not certain about it.
Can anyone tell me if it's a good idea to use [sshfs](https://github.com/libfuse/sshfs) in order to mount the remote server into the local working directory and then use VSCodium to browse/edit the files ? 
It seems like it's too good to be true, why would one need any extension then ?

**Comment by notpushkin** [comment]
@Lcchy Mainly for the debugger I think. Other things (version control and code jump to dependencies) most of the time work fine with just files, but debugging requires running a special process on the server (for some languages it's a separate script, e. g. [debugpy](https://github.com/microsoft/debugpy) for Python, for others it's just an option) and port forwarding (so that nobody else can “debug” your code :) to work.

**Comment by notpushkin** [comment]
Another good starting point might be to try to hook up a vscode-ish server ([GitPod](https://github.com/gitpod-io/gitpod), [code-server](https://github.com/cdr/code-server)) to the Codium UI.

Also related: https://github.com/cdr/code-server/issues/1315

**Comment by bpmct** [comment]
> Another good starting point might be to try to hook up a vscode-ish server ([GitPod](https://github.com/gitpod-io/gitpod), [code-server](https://github.com/cdr/code-server)) to the Codium UI.

Would this mean that Codium would install code-server on a remote resource and then proxy that connection through the Codium window? Interesting!
