### ISSUE TITLE
Updating VSCodium

### ISSUE THREAD

**Issue by AdonisN** [VSCodium/vscodium#268]
VSCodium came pre-installed with Parrot OS (Linux). In the settings gear on the lower left side, there is a "1" and I see an option to download the update. I download it but it just goes to the downloads folder. How do I actually run the update?

**Comment by PalinuroSec** [comment]
hello, that button is deactivated because codium is included in the official parrot repository

codium is updated with the rest of the system. just run sudo parrot-upgrade and see what happens

**Comment by stripedpajamas** [comment]
As @PalinuroSec said -- updating through Linux should probably be done through a package manager. In the case of Parrot OS, VSCodium is in the official repository, so you should be able to update through that. Closing for now, let me know if this should be re-opened.

**Comment by zareshahi** [comment]
Hello
it's automatically downgrade to 1.47 version in parrot(parrot package manager) while the 1.50 version released !

**Comment by joshzinny** [comment]
has this been resolved because i am having similar issues

**Comment by PalinuroSec** [comment]
updated. give it few hours to land on rolling branch

**Comment by joshzinny** [comment]
Thank you @PalinuroSec 
I suppose in few hours, sudo parrot-upgrade will upgrade it right?

**Comment by joshzinny** [comment]
> updated. give it few hours to land on rolling branch

No luck yet with this @PalinuroSec

**Comment by smarkor-5** [comment]
how to update vs codium in parrot os. i dont know about the installation of tar.gz files.

**Comment by PalinuroSec** [comment]
you update it with the rest of the system using sudo apt update && sudo apt full-upgrade

if there is a new version available, you will get it, otherwise the new version is not yet ready and needs more testing in the rolling-testing branch. wait few days and try again

**Comment by ochecodes7** [comment]
it doesn't work

**Comment by ochecodes7** [comment]
even when you update the whole system the codium still comes up with an update
and when you try downloading it gives you a tar.gz file without a proper documentation on how to use

**Comment by bang-zoel** [comment]
extract tar.gz, go to bin folder, run codium file

**Comment by habtij** [comment]
after running the codium file in bin, vscodium started but my system hang after 5 secs, why?

**Comment by ochecodes7** [comment]
i did that nothing came up so i deleted it and downloaded the real vs code 

> extract tar.gz, go to bin folder, run codium file

**Comment by daiyam** [comment]
@habtij Can you open an new issue since yours isn't related to the current issue. Could you also give me details?
@ochecodes7 Codium users are not lambda users. And our small teams don't have infinite time. You are welcome to contribute to the project.
