### ISSUE TITLE
[Discution] Does plugin telemetry also removed ?

### ISSUE THREAD

**Issue by sucrecacao** [VSCodium/vscodium#269]
Hi 

From what I understand vscodium disable vscode telemetry.
But what about plugin telemetry ? 
For example microsoft python plugin claim to use telemetry ( https://github.com/Microsoft/vscode-python). Will this be disable by default too ?

**Comment by stripedpajamas** [comment]
Unfortunately no, plugin telemetry is per-plugin (some plugins have it some don't). It's up to each person if they want to install and use those plugins.

It would be great to see a) an open source vscode extension marketplace and b) open source plugins for popular languages that have no telemetry. As things currently stand, MS has somewhat locked everyone into using their marketplace and MS themselves have written most of the popular plugins and they have telemetry.

**Comment by sucrecacao** [comment]
alright i'm back to vim then
