### ISSUE TITLE
To much phoning home by default.

### ISSUE THREAD

**Issue by nextgenthemes** [VSCodium/vscodium#270]
**Describe the bug**
After reading the docs and seeing how you just disable one or two flags I have to say I am disappointed. And then the complicated and annoying guide to disable phoning home stuff. I though the goal of the project was to make it private?

The crash reporting is still on by default. Fetching MS Experiments ... whatever that is. Why not at least disable more settings by default instead of sending people to guides? I mean these are just options right?

Ideally "going out of the way" completely removing code used to send data to MS would be awesome but I think at least there should be no "you have to do these steps to disable what you are actually here for" pointing to the official VS Code site is disappointing. 

For extensions I get it, but maybe they use a common API or something that can be disabled? But the core stuff should be just completely off after install.

**Please confirm that this problem is VSCodium-specific**
Well the thing is I think the goal should be to make this private by default and not "just" exclude the bullshit MS puts on top of the open source code. I think it should not phone home in any way by default. I won't even try to make MS disable it by default so ...

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**

1. Install.
2. Look at settings.
3. Look at docs.

**Expected behavior**
No phoning home features, at least not enabled by default.

**Desktop (please complete the following information):**
```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-16T10:47:27.951Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.3.5-1-default
```

**Comment by nextgenthemes** [comment]
Actually I just read https://github.com/VSCodium/vscodium/issues/145 and it seems you purposefully let all this things on? I do not get it. Why start something that you not even try to finish? Because people may lose functionality? What functionality do I use when I do not enable experiments from MS?? How about making it the other way arround. Make it private by default and if people "lose" (I never used VSCode) functionality they want they can enable things and feed MS their data.

**Comment by stripedpajamas** [comment]
The goal of the project is definitely not privacy. The top of the readme says "This is a repository of scripts to automatically build Microsoft's vscode repository into freely-licensed binaries with a community-driven default configuration."

It might be important to call out that besides default-false'ing the telemetry settings, we do [change the (known) telemetry host addresses to 0.0.0.0](https://github.com/VSCodium/vscodium/blob/master/undo_telemetry.sh) to prevent telemetry that isn't governed by the options. If you have discovered VSCodium making a call to Microsoft, can you share that so we can determine the source? (You mentioned Experiments, but that setting doesn't cause a call to MS, as #145 makes clear).

It seems like you are approaching the project as "A privacy-centric build of Visual Studio Code". Discussion is welcome on this topic. Consider using https://gitter.im/VSCodium/Lobby as this is not a bug.

**Comment by nextgenthemes** [comment]
"Community driven config" ? Where is this community who wants this features? I do be believe it exists.

Oh OK fuck off then you guys seem to be idiots if you not even want to disable malicious default options what the fucking point of spending time to build it yourself. If I want MS bullshit I can as well go to their website and download the official version.

And things like this could be discussed here by "the community" as well. I would be not surprised if most people who actually seek out this build are here for that exact reasons. I mean what other reason is there? What is your goal? To disable one option but leave all the others on? I really **really** do not get it at all. But I won't waste any time "discussing" this with the likes of you who just close this withing minutes.

The last chat where you want me to go way in august. Seems not really a active community at all behind this to justify a chatroom. Privacy would be a goal to attract people and build opon, just getting PRs in to just merge without any work probably ... but I guess someone else needs to do that. It won't be me at this point.

**Comment by wrapper** [comment]
I too just installed VSCodium to avoid phoning home to MS only to find that the telementary options were both present and enabled by default. At best this is confusing, at worst it is misleading to people who are installing the software for this very reason.

**Comment by stripedpajamas** [comment]
@wrapper what telemetry options did you find enabled? Can you send a screenshot and/or open an issue? Our goal is to disable telemetry by default.

**Comment by nextgenthemes** [comment]
@wrapper Thanks, at last one for now you confirms my thoughts. These 3 down-votes I got 

@stripedpajamas ROFL are you stupid or something? You know that you enable I think exactly **one** config switch for `temetry` and refuse to do more. And then you send people to **annoying official tutorial** that tells you do go though your `@tag:online-services` config or something like that and pick what is there.

And now you ask him for a screenshot? For what? You know exactly what the other guy b4 me that you shut down was talking about and you still know it. Did you change your mind now or for what you want a screenshot? I did some basic very quick overvie of the online setting and this is what I have disabled. There seem to be at least two other core telemetry settings that I am guessing you disable on the default config so they do not show up in the user config? So you no not even disable all telemetry options.

You still have not answered me what those `experiments` are and why "the community" would feed their data to M$ to get them. Crash reporting is something I do not want for M$ because I do not trust them and they probably send all kinds of personal data with it. Same for this Natural Language search whatever that is. Probably sends contents of entire files to M$ for analysis or something shady. But yeah you need that screenshot now ...

This is the relevant parts of my settings.json and I probably missed something.
```
{
    "telemetry.enableCrashReporter": false,
    "workbench.enableExperiments": false,
    "workbench.settings.enableNaturalLanguageSearch": false
}
```

I fucking hate how M$ creep-ed its way back onto my life. I am 8 years+ on Linux now and boot the Windows 10 spyware only for gaming that I rarely do these days, not for months.

First they buy Github, something they had nothing to do with, just to suck off all that data all these hard working open source devs put into it. Nothing special for M$. They initially bought the first Windows version and not came up with it on their own.

I have to admit VScode is better then Atom and Typescript is also pretty cool so here I am M$ is back in my digital world on Linux. What a disgusting practice to  develop a program that is 100% open source to then but some closed source bullshit on top of it and release it. They copied that from Google. This is exactly what they do with Chrome. And 9.5 out of 10 idiot Linux users are eager to install Chrome as their first app on Linux. Fucking idiots. I have seen countless Blogs and Stackexchange answers that showed this. They should use Firefox or just install Chromium that is in every default Distro repo but these idiots are all to eager to infest their almost complete open source OS with some close source app from a data collection giant. Even Chromium has that Google account connect and stuff everything build in, same as VSCode with telemetry is seems. Are they just do branding? What code do they actually build into it? They purposefully even make their telemetry code open source so even the open source builds have it. It would be the responsibility or projects like this to at the very least disable it of not cutting out the code completely.

I was a bit to extreme earlier. I do think there is a point on having a open source build because there is no insight on what they actually build on top of it. Still there should be more. That fact that is just some some config switches and you refuse to to so make me question your entire operation.

GH issues can be perfectly fine to have a discussion on the public record (On a M$ owned platform lol) I do not see the need for a chat. Why not keep it open and let the community actually say their opinions? I do not believe you are up for a open discussion, you want to **shut it down withing minutes** early and move it away to some external chat site. How is that making "the community drive the config file?" I think you are being dishonest and want you just shove your opinions down people throats.

Those 3 downvotes I got above are probably people involved, their friends or the fact that I used cursewords and name-calling. I know its not helping me but things like this just completely piss me off.

OK I end my rant. Love you all.

**Comment by stripedpajamas** [comment]
@nextgenthemes you are in clear violation of [our code of conduct](https://github.com/VSCodium/vscodium/blob/master/CODE_OF_CONDUCT.md).

@wrapper our readme says we disable telemetry by default. Please open an issue if you have found telemetry to be enabled by default in VSCodium. On my own I have found that Crash Reporting was enabled on a recent fresh install, which is a telemetry setting. I've opened #273 to track resolution.

all: "Enable Experiments" is not telemetry for VSCodium; nothing is sent to Microsoft as there is no experiments url in VSCodium's product.json file ([code](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/experiments/common/experimentService.ts#L171)).

I would love to discuss pros/cons of enabling/disabling the Natural Language Search feature in the Lobby (https://gitter.im/VSCodium/Lobby).

**Comment by nextgenthemes** [comment]
> all: "Enable Experiments" is not telemetry for VSCodium; nothing is sent to Microsoft as there is no experiments url in VSCodium's product.json file

Well that should be mentioned in the "How to get the telemetry out" section then. You instead make it seem that you just flip two switches in the default config file. So you do that and you remove the url? What else? From another file. Is there a overview of something maybe a git diff of those files you change. Would be helpful if you lead people easy to a overview of what you actually change. 

> On my own I have found that Crash Reporting was enabled on a recent fresh install, which is a telemetry setting. I've opened #273 to track resolution.

Funny you found out "on your own" 6 hours ago that crash reporting was enabled after I made my comment 7 hours ago about my need to disable it? Strange coincidence. So you actually agree it should be disabled and actaully failed at doing what you claim you do? I understood that as a you purposefully not doing it after you said you are not about privacy. How can you miss that if the setting actually starts with `telemetry.` ???

> I would love to discuss pros/cons of enabling/disabling the Natural Language Search feature in the Lobby (https://gitter.im/VSCodium/Lobby).

I searched that gitter chat for `lang`, `natural` and `search` and nothing came up ... so you want to disable telemetry and happily let settings searches go to go to Microsoft just because they do not call it telemetry. This is so funny. I just looked at https://code.visualstudio.com/blogs/2018/04/25/bing-settings-search and they go out of their way with some uber complicated search thing just to search for settings inside a app. ROFL what they do to get a few more Bing searches in. So desperate for some data to sell and abuse. I did some basics tests. I fail to see how I would type actual questions in there as settings come up based on keywords and its perfectly fine without online search. Probably even better because those results would probably distract me. If I want a setting a keyword is more then enough and there is a menu and its not that many settings. I fail to see how you justify forcing this on people who come for this. It should be opt-in for people who want it. Not forced on people.

Seeking out open source apps comes hand on hand with seeking for privacy, people in fact like open source because they can verify is not doing shady things they do not want. Its not that some in app Bing searches are going to kill anyone, its just so not very useful, seems forced and unneeded and a perfect candidate to disable by default.
