### ISSUE TITLE
Missing VSCodium 1.40 windows version?

### ISSUE THREAD

**Issue by xuchengpeng** [VSCodium/vscodium#280]
Missing VSCodium 1.40 windows version?

**Comment by erlangp** [comment]
https://github.com/VSCodium/vscodium/issues/262

**Comment by xuchengpeng** [comment]
> [#262 (comment)](https://github.com/VSCodium/vscodium/issues/262#issuecomment-540394820)

oh thanks, i will check later

**Comment by erlangp** [comment]
lets download it now :) https://github.com/VSCodium/vscodium/releases
