### ISSUE TITLE
open url with scheme "vscode:" "vscodium:" "codium:"

### ISSUE THREAD

**Issue by erlangp** [VSCodium/vscodium#281]

**Comment by stripedpajamas** [comment]
Can you clarify what is needed here?

**Comment by erlangp** [comment]
show popup Launch Application when url like vscode:// vscodium:// codium:// :)

**Comment by ImportTaste** [comment]
@stripedpajamas For Windows:
```
Set-Item -Path Registry::HKCR\vscode\shell\open\command -Value '"C:\Program Files\VSCodium\VSCodium.exe" --open-url -- "%1"'
Set-Item -Path Registry::HKCR\vscodium\shell\open\command -Value '"C:\Program Files\VSCodium\VSCodium.exe" --open-url -- "%1"'
Set-Item -Path Registry::HKCR\codium\shell\open\command -Value '"C:\Program Files\VSCodium\VSCodium.exe" --open-url -- "%1"'
```

**Comment by stripedpajamas** [comment]
I'm confused; does VSCode currently register itself for vscode:// and/or code:// ?

**Comment by ImportTaste** [comment]
@stripedpajamas Yes. Check out the Install button on this link: https://marketplace.visualstudio.com/items?itemName=CodeStream.codestream

I believe they were initially using `code:` but they decided it was too generic and started primarily using `vscode:`, but there are still projects still using the old one.

**Comment by stripedpajamas** [comment]
I see. This feature is baked into the product itself using the `urlProtocol` flag in `product.json`. Ours is currently set to `vscodium` and it doesn't look to me like it's possible (without patching VSCode in some way) to have it handle more than one protocol. 

So the option now would be: `vscodium:` or `codium:` ?

( if you have VSCodium installed, the example above should work: vscodium:extension/CodeStream.codestream )

**Comment by ImportTaste** [comment]
Hm, well, there's not really much point unless you can use the vscode: protocol... oh, a GreaseMonkey script to transform vscode: to vscodium: on the VS 'marketplace' might work.

**Comment by stripedpajamas** [comment]
Ok; for now I will leave url scheme as it is (vscodium:) and let people figure out clever ways to get VS marketplace links to work in-browser.
