### ISSUE TITLE
[question] diferences between vscodiumsetup and vscodiumusersetup (exe) ?

### ISSUE THREAD

**Issue by erlangp** [VSCodium/vscodium#282]

**Comment by Makazzz** [comment]
The **_VSCodiumSetup-x64-1.40.0.exe_** will be install in your `C:\Program Files` like other program (so every user in the computer can use VSCodium)

And **_VSCodiumUserSetup-x64-1.40.0.exe_** will be install in your `C:\Users\YourName\AppData\Roaming` and only your profile will have access to it (and Admin)

**Comment by erlangp** [comment]
ow thanks sir
