### ISSUE TITLE
VSCodium installer for Windows uses default code-icon

### ISSUE THREAD

**Issue by ealap** [VSCodium/vscodium#285]
**Describe the bug**
VSCodium installer still has the default code-icon

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open VSCodium installer
2. See icon on the installer's header

**Expected behavior**
Should use VSCodium icon

**Screenshots**
![image](https://user-images.githubusercontent.com/15620712/68951408-ee543000-07f8-11ea-8f3c-28a2f2848b8a.png)

![image](https://user-images.githubusercontent.com/15620712/68951964-00829e00-07fa-11ea-96a5-dd71c4d691ec.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Architecture: x64
 - Version: 1.40.1

**Comment by stripedpajamas** [comment]
It appears MS has added many different sizes for the setup icon in https://github.com/microsoft/vscode/tree/master/resources/win32, used [here](https://github.com/microsoft/vscode/blob/master/build/win32/code.iss#L22-L23) whereas we only have small and big in https://github.com/VSCodium/vscodium/tree/master/src/resources/win32.

To resolve, we will need to replicate the additional sizes.

**Comment by stripedpajamas** [comment]
Should be fixed by #413 (will build into next MS release)
