### ISSUE TITLE
VSCodium freeze on replace text on multipled files after finish

### ISSUE THREAD

**Issue by jabiertxof** [VSCodium/vscodium#286]
Not sure is a upstream bug by I need to kill my machine each time I use.
Latest VSCodium, Debian Bullseye.

**Comment by stripedpajamas** [comment]
Have you tried Visual Studio Code and had the same issue?

**Comment by jabiertxof** [comment]
No. sorry no time to test now I close the issue, reader feel free to reopen if you have this problem
