### ISSUE TITLE
Where is the linux ia32 version of VSCodium?

### ISSUE THREAD

**Issue by MouriNaruto** [VSCodium/vscodium#287]
I have a development devices which CPU is using Intel Yonah micro architecture. (We know it supports 32-bit only.) I am using Debian 10.2 on it. And I wonder to use Visual Studio Code because it's good for me to write implementations using Rust and my diary using Markdown.

But as we all know, Visual Studio Code dropped the Linux 32-bit support because of https://electronjs.org/blog/linux-32bit-support. (But I found Electron still publish linux 32-bit binaries in the newest stable version 7.1.1.)

I have read the readme in the VSCodium repository and found it says support Linux 32-bit. But when I want to download the newest version, I can't found the prebuilt binaries.

Kenji Mouri

**Comment by stripedpajamas** [comment]
We dropped ia32 at the same time vscode dropped it since this repo is just building vscode from source. So the latest version of VSCodium you can get for Linux ia32 is https://github.com/VSCodium/vscodium/releases/tag/1.35.1

Is it confusing to list it in the readme? Maybe I can clarify by putting `(up to v1.35.1)` there as well.

**Comment by MouriNaruto** [comment]
@stripedpajamas 

I hope you can clarify it because I am confused about that. (I tried using methods in https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo for installing VSCodium and the apt-get said can't find the codium package.)

Kenji Mouri

**Comment by EchedeyLR** [comment]
Zettlr, an electron app using last electron versions is providing support for IA32. Can't be this recovered??

**Comment by EchedeyLR** [comment]
https://github.com/electron/electron/releases

Latest 9.x and 8.x releases are supporting IA32 (x86_32) GNU/Linux
