### ISSUE TITLE
portable mode not working again

### ISSUE THREAD

**Issue by AndyNaimoli** [VSCodium/vscodium#295]
As in issue #138 portable mode is not working (again?).

On Mac - Not yet tried with Win and Lnx (but need for all platforms :) - named data folder as "vscodium-portable-data" along the ".app" file and also tried "vscode-..." and "code-oss...". It's ignored. v.1.40.02 pre-built binaries on Mac 10.14.5

**Comment by stripedpajamas** [comment]
Due to the application name switching from VSCodium to Codium somewhat recently. The logic in the code is ```${product.applicationName}-portable-data```, so make your folder `codium-portable-data` and it should work. Will use this issue to update our DOCS file.
