### ISSUE TITLE
Mac OS / brew installation not working

### ISSUE THREAD

**Issue by stchris** [VSCodium/vscodium#297]
**Describe the bug**
I followed the installation steps for homebrew on Mac OS (`brew cask install vscodium`), but starting the application results in this error message:

> “VSCodium” can’t be opened because Apple cannot check it for malicious software.

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. `brew cask install vscodium`
2. Start VSCodium

**Expected behavior**
VSCodium starts up.

**Screenshots**

<img width="532" alt="Screenshot 2019-12-04 at 16 19 03" src="https://user-images.githubusercontent.com/217554/70155160-06112c80-16b2-11ea-8eb6-cdc3cfd5b290.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Architecture: x64
 - Version: 10.14.6 (Mojave)

**Additional context**
The version installed here is `1.40.2`.

**Comment by metadave** [comment]
There's a note [here](https://github.com/VSCodium/vscodium#install-with-brew-mac) that will resolve the issue (under `brew cask install vscodium`)

**Comment by stchris** [comment]
I'm really sorry about not having read that. The workaround works. The issue was the dialog looks different when you open the app from spotlight, but the right-click and open worked. Apologies for the unnecessary bug ticket!
