### ISSUE TITLE
No AppImage in 1.40.2 release ?

### ISSUE THREAD

**Issue by mundusnine** [VSCodium/vscodium#299]
![image](https://user-images.githubusercontent.com/29337013/70246533-e9becf80-1745-11ea-8eaa-67862252cccf.png)

![image](https://user-images.githubusercontent.com/29337013/70246615-022eea00-1746-11ea-9c06-d35ab2927437.png)

**Comment by sambuccid** [comment]
Hi, you can follow what happened in this other issue #253 , but probably is better to leave this issue open as it is now more pertinent with the actual problem
