### ISSUE TITLE
Latest Release Missing OSX

### ISSUE THREAD

**Issue by ryanolsonx** [VSCodium/vscodium#3]
The 1.26.1 release is missing a binary for Mac OS X.

**Comment by stripedpajamas** [comment]
Good catch. I will kick that build off again and investigate what went wrong.

**Comment by stripedpajamas** [comment]
It's a race condition that I haven't really figured out a way around. Will noodle on it. The latest release is done now with linux+darwin. Thanks @ryanolsonx

**Comment by ryanolsonx** [comment]
Thanks!
