### ISSUE TITLE
VSCodium checks for updates on startup even when update.mode is set to manual

### ISSUE THREAD

**Issue by layday** [VSCodium/vscodium#304]
With `update.mode` set to 'manual' I have observed that VSCodium connects to a 'bc.googleusercontent.com' URL on startup which is the same URL it uses to check for updates from the menu bar.  The tooltip for the 'manual' mode in settings states that it should 'disable automatic background update checks.'

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Launch VSCodium
2. Monitor open sockets using your socket-monitoring tool of choice

**Desktop (please complete the following information):**
 - OS: macOS
 - Architecture: x64
 - Version: 1.40.2

**Comment by stripedpajamas** [comment]
Thank for bringing this to my attention. I will try to reproduce it on my Mac and get to the bottom of it.

**Comment by stripedpajamas** [comment]
Using Little Snitch I was able to somewhat reproduce the issue; but I never see connections to `bc.googleusercontent.com` as the OP says. @layday can you confirm that this host is called by VSCodium and maybe tell me what program you are using to see ? 

Little Snitch detects an outbound connection to `vscodium.now.sh` when Codium first opens (which update mode = auto). This is the lambda we use to provide update information (code here: https://github.com/VSCodium/update-api). 

The issue: even when I change update mode to manual, VSCodium still calls `vscodium.now.sh` on startup. My suspicion is that the code has it check the version on startup, regardless of the update mode, but won't automatically update to the latest version when set to manual. More digging into the `vscode` codebase is necessary for clarity.

Open questions:
- exactly what call is made to the update api on startup when the update mode is manual? (I should be able to monkey-patch Codium to hit a local API and log out the request)
- what's bc.googleusercontent.com ? Codium on my machine (macOS) never contacts this host and I don't think the update api `vscodium.now.sh` is in any way tied to Google... the API is hosted with Zeit, which uses AWS as its backend. hoping to get clarity from @layday on what he saw

**Comment by layday** [comment]
That's simply the hostname that `vscodium.now.sh` (ultimately) resolves to for me and it's what `nettop` is showing me.  Maybe they've registered their domains with Google, I don't really know - it's been a long time since I dabbled in this stuff 🤷🏽‍♂️ If you perform a reverse DNS lookup or whatchamacallit, you'll probably see something similar.... unless of course this is all dependent on their CDN:

```sh 
$ host vscodium.now.sh
vscodium.now.sh has address 35.195.188.93
$ host 35.195.188.93
93.188.195.35.in-addr.arpa domain name pointer 93.188.195.35.bc.googleusercontent.com.
```

**Comment by stripedpajamas** [comment]
Makes sense @layday ; I got confused because I get different host results (maybe regional?)

```
$ host vscodium.now.sh
vscodium.now.sh has address 54.201.139.97
vscodium.now.sh has address 54.186.164.90
$ host 54.201.139.97
97.139.201.54.in-addr.arpa domain name pointer ec2-54-201-139-97.us-west-2.compute.amazonaws.com.
$ host 54.186.164.90
90.164.186.54.in-addr.arpa domain name pointer ec2-54-186-164-90.us-west-2.compute.amazonaws.com.
```
