### ISSUE TITLE
Happy Holidays!

### ISSUE THREAD

**Issue by PlavorSeol** [VSCodium/vscodium#308]
Can VSCodium also give the _Manage_ icon a santa hat like Visual Studio Code does?
![2019-12-17](https://user-images.githubusercontent.com/43488966/70978283-d96a0580-20f2-11ea-8836-e0a468730883.png)

**Comment by GammaGames** [comment]
I think it'd be great, but if you go look at the closed issues in the vscode repo it's... interesting. Issues 87403, 87286, and 87437 are probably my favorites.

**Comment by stripedpajamas** [comment]
It's a fun addition (in my own opinion) but I think based on the issues in vscode we've dodged a bullet by not including it. In any case it will most likely be removed within a week or two by vscode, so I opt to skip it.

**Comment by GammaGames** [comment]
What about adding the `holiday.gearIconStyle` setting that the insiders build now has?

**Comment by PlavorSeol** [comment]
I agree to that. I just found Visual Studio Code - Insiders now has `holiday.gearIconStyle` which allows configuring the appearance of gear icon and I think it is great.
