### ISSUE TITLE
Windows artifacts are missing from Release 1.41.1

### ISSUE THREAD

**Issue by martonnagy** [VSCodium/vscodium#309]
Hi Guys,

the Windows binaries/setup is missing from Release 1.41.1
Can you check it, please?

Cheers!

**Comment by PlavorSeol** [comment]
It seems that macOS binaries are also missing.

**Comment by stripedpajamas** [comment]
Sorry for the delay! We had a bug in the build func that I've corrected. All assets available on the releases page now.

**Comment by martonnagy** [comment]
That's fine, thank you very much
