### ISSUE TITLE
[question] why does log talk about telemetry ?

### ISSUE THREAD

**Issue by neyb** [VSCodium/vscodium#314]
running the command `vscodium --verbose` log this :

```
[main 2020-01-07T15:03:31.253Z] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('telemetry.lastSessionDate','Tue, 07 Jan 2020 14:11:06 GMT'),('telemetry.currentSessionDate','Tue, 07 Jan 2020 15:03:31 GMT')
```

Can we be sure it's not a sign that some telemetry stuff is still not disabled ?

**Comment by stripedpajamas** [comment]
The code saves data into local storage, but this does not indicate that it is sent off to MS (this is the part we have disabled). 

Ref:
- https://github.com/microsoft/vscode/blob/af9dddd0fcd65f310cc795e0c7c5370b4ca17086/src/vs/platform/storage/node/storageMainService.ts
- https://github.com/microsoft/vscode/blob/af9dddd0fcd65f310cc795e0c7c5370b4ca17086/src/vs/platform/storage/node/storageIpc.ts
- https://github.com/microsoft/vscode/blob/dedf0de944fae56f0bf748913cbc1b2cc24987d2/src/vs/platform/telemetry/common/telemetry.ts
