### ISSUE TITLE
Improvement, add more resolution to taskbar icon in Windows

### ISSUE THREAD

**Issue by fausthor97** [VSCodium/vscodium#317]
Not a bug, just an improvement. The taskbar icon in windows is pixelated, doesn't look good.
![imagen](https://user-images.githubusercontent.com/29243458/73095309-2205a300-3e97-11ea-9bb6-06199b748ec5.png)

**Comment by stripedpajamas** [comment]
Should be covered by #413 (will build into next MS release)
