### ISSUE TITLE
Apt update with gitlab repo : too many requests

### ISSUE THREAD

**Issue by eoli3n** [VSCodium/vscodium#318]
**Describe the bug**
I manage 800 nodes with ansible, when i play my playbook, i get on some nodes
```
W: Impossible de récupérer https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs/dists/vscodium/InRelease  429  Too Many Requests [IP : XXX.XXX.XXX.XXX 3142]
W: Le téléchargement de quelques fichiers d'index a échoué, ils ont été ignorés, ou les anciens ont été utilisés à la place.
```

**To Reproduce**
A dirty way
```
for i in $(seq 1 800); do curl -s https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs/dists/vscodium/InRelease & > /dev/null ; done
```

**Expected behavior**
No limitation about number of queries.

**Additional context**
We use apt-cacher to cache debs files, but it can't cache indexes.

**Comment by stripedpajamas** [comment]
This might belong on @paulcarroty's repo; not sure if there will be a way around this with our current setup.

**Comment by paulcarroty** [comment]
Guess it's Gitlab anti-DoS defense, talk with their support.

**Comment by eoli3n** [comment]
I sent support a msg, lets wait for its answer

**Comment by stripedpajamas** [comment]
Closing; further issues with the repo can be logged on the Gitlab side. See also #469
