### ISSUE TITLE
Windows 10 - Select Open with VSCodium not working when open

### ISSUE THREAD

**Issue by GHMusicalCoder** [VSCodium/vscodium#319]
When you have VSCodium open with some files tabbed, and then open Windows Explorer, find a file, right click it, and select Open with VSCodium, all I get is an error ding, and nothing else happens.  If VSCodium is closed, this works fine.  But if you've had it opened an worked with files, adding a new file this way does not work.

I do not have VS Code installed, so I cannot confirm this is not a straight VS Code issue.

- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

In Windows 10 -
1. Have VS Codium open with some files that you have edited and saved.
2. Go to Windows Explorer
2. Select any file you would open in VS Codium
3. Right click the file and select "Open with VS Codium"
4. Hear the error ding, and note that nothing else happens.

**Expected behavior**
A new tab opens in VS Code with the said file.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Architecture x64
 - Version 1.41.1

**Comment by Deshanm123** [comment]
Try to run as Administrator

**Comment by GHMusicalCoder** [comment]
Well - don't I feel stupid now!
