### ISSUE TITLE
Start menu icon is off center

### ISSUE THREAD

**Issue by ghost** [VSCodium/vscodium#329]
The start menu icon on Windows 10 is off center when the tile size is set to medium. 

For reference, Visual Studio Code and Visual Studio have similar off-center issues while most other applications do not, including other Microsoft applications such as Skype, OneNote and the other built-in Windows 10 applications.

![image](https://user-images.githubusercontent.com/50193859/74522271-8e6a4400-4f23-11ea-90b9-f09faa25df55.png)

![image](https://user-images.githubusercontent.com/50193859/74522568-1a7c6b80-4f24-11ea-8ea6-99ad097f20da.png)

Thanks.

**Comment by daiyam** [comment]
Visual Studio Code icon has the same issue.
