### ISSUE TITLE
Cannot install in Mac

### ISSUE THREAD

**Issue by ClimberBear** [VSCodium/vscodium#33]
I'm trying to install with brew, but I get a SHA signature validation error. It's a new / clean Macbook (no previous vscodium installed)

This is the output (I have also tried 'brew update' with no change)

brew cask install vscodium
==> Satisfying dependencies
==> Downloading https://github.com/VSCodium/vscodium/releases/download/1.27.2/VS
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'vscodium'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'vscodium' does not match.

Expected: 53dee2011c3447756ceb4abe7c8b24b0d75bd55575ff4c1f56d853ff92004e7a
Actual:   12eab5a0387aa3042ee1e2f1dd6dd8b5ed68ef7f20f1b08eefee172ab209aa4c
File:     /Users/myuser/Library/Caches/Homebrew/downloads/23252e6726991c70244c11a9f6116e142517dc6a683e96d25eacd2b64d49b9fc--VSCode-darwin-1.27.2.zip

**Comment by stripedpajamas** [comment]
Good catch @ClimberBear -- the binaries were recently updated after merging in some un-telemetry measures. I will update the cask upstream.

**Comment by stripedpajamas** [comment]
https://github.com/Homebrew/homebrew-cask/pull/53067

**Comment by ClimberBear** [comment]
Really quick! I was editing/reinstalling cask formula, but I will wait for your update

**Comment by stripedpajamas** [comment]
@ClimberBear homebrew-cask merged upstream. Can you try again?

**Comment by ClimberBear** [comment]
Perfect now!!!
Thanks!

**Comment by matheusbn** [comment]
Same problem happening here. New / clean Macbook as well.
