### ISSUE TITLE
Portable mode: expecting a folder named data (not codium-portable-data)

### ISSUE THREAD

**Issue by NebojsaKrtolica** [VSCodium/vscodium#333]
**Describe the bug**
After reading #138 and #295 I tried to get portable mode working in version [1.42.1](https://github.com/VSCodium/vscodium/releases/tag/1.42.1) zip version VSCodium-win32-x64-1.42.1.zip

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
VSCode works as expected (with a `data` folder)

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.
I've followed https://github.com/VSCodium/vscodium/blob/master/DOCS.md#how-do-i-run-vscodium-in-portable-mode

**To Reproduce**
1. Download VSCodium-win32-x64-1.42.1.zip from https://github.com/VSCodium/vscodium/releases/tag/1.42.1
2. extract
3. create a folder named `codium-portable-data` (next to the extracted files)
4. start VSCodium.exe
5. check `Users/user/` and `AppData/roaming`

**Expected behavior**
All on start generated VSCodium data is stored inside the `codium-portable-data`

**Desktop:**
 - OS: [Windows 10]
 - Architecture [x64]

**Additional context**
### After trying codium-portable-data and vscodium-portable-data. I've managed to get it working by creating a `data` folder. 

**NOTE:** Inside all of the folders above  I've manually added an extensions, user-data and tmp folder respectively

**Comment by stripedpajamas** [comment]
Hi @NebojsaKrtolica -- for Windows the folder is just named `data`; for Mac it is `codium-portable-data`. Can you confirm portable mode works properly when you make a `data` folder?

**Comment by NebojsaKrtolica** [comment]
Hi @stripedpajamas -- 
I've managed to get it working by creating a `data` folder (I've described this allready but I've updated my comment to make that part more visible.)

After rereading the doc part about portable mode and with the experience that I now have, I can understand what it says, but the first time I've read it it wasnt so obvious.

I've created a pull-request #347  addressing this issue :shipit:
