### ISSUE TITLE
PR to spread the word about VSCodium

### ISSUE THREAD

**Issue by wolfiton** [VSCodium/vscodium#339]
Hi everyone,

I wrote an article here https://dev.to/wolfiton/vscodium-the-open-source-version-of-vscode-without-telemetry-4dn0
, about the awesome VSCodium you built and was wondering if you have any suggestions to improve the article or if I missed something

Thanks, VSCodium Team, for creating project

**Comment by stripedpajamas** [comment]
Thanks so much for the PR @wolfiton 💙 

I don't see any improvements to make at this point. Thanks again
