### ISSUE TITLE
The Linux Deb/RPM repository

### ISSUE THREAD

**Issue by paulcarroty** [VSCodium/vscodium#34]
Hosted on [Gitlab](https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo) only. Scheduler and GPG sign works. Please test it and notify me about any issue.

I did it 'cause nobody are interested in #5 .

**Comment by stripedpajamas** [comment]
@paulcarroty thank you for taking the initiative here. It looks great to me.

After some Linux users try it out we can update the README to point to this resource. 

@sam0x17 @mathiasblc @G-Ray @Lomanic @JL2210 I am in favor of closing #1 and #5 if this works.

**Comment by mathiasblc** [comment]
This is great! 👍🏻

**Comment by JL2210** [comment]
You might want to store the packages themselves on [bintray](https://bintray.com). They have a 10GB storage limit for OSS applications and a 1TB download limit. They natively support debs and rpms. Along with that, they also have a CDN. Chromebrew uses it, and I can say I haven't had a problem with it yet.

**Comment by paulcarroty** [comment]
1TB limit = ~16.7k downloads. This is literally nothing for such project.

Anyway, we can configure bintray as independent mirror. But better move this idea to another issue.

**Comment by stripedpajamas** [comment]
@paulcarroty can you look over the README change I just proposed in #38 ? If it looks alright I think we can wrap this up.

**Comment by paulcarroty** [comment]
@stripedpajamas looks fine.

**Comment by sam0x17** [comment]
@paulcarroty I am getting the same issue with GPG keys that they guy who posted the issue on your repo is complaining about. It is saying the repo is unsigned even after installing your gpg key and refreshing keys etc.

```
Reading package lists... Done                      
E: The repository 'https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs vscodium Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
``

**Comment by VGerris** [comment]
I have this issue recurring today, combined with 'too many requests'.

**Comment by paulcarroty** [comment]
https://github.com/VSCodium/vscodium/issues/355

**Comment by davidrhoderick** [comment]
Also had this issue and #355 plus like @VGerris said, I am getting the "too many requests" error.
