### ISSUE TITLE
vscodium not working with xmonad?

### ISSUE THREAD

**Issue by zeta-00** [VSCodium/vscodium#341]
Hello there,
I just installed vscodium using these nix instructions: https://nixos.wiki/wiki/VSCodium , and it built without any errors. After rebooting nixos I ran codium and it did not work. I am using xmonad without a desktop environment so I figured that vscodium is missing some functionality? here is the error that vscodium is throwing? https://gist.github.com/zeta-00/5f9497a6e6702709a9af6c654c06f06b

**Comment by stripedpajamas** [comment]
Hi @zeta-00 -- I'm not sure what's going on here as the Nix version isn't officially supported. I am not sure who ported VSCodium to Nix (maybe one of the contributors to [this file](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vscode/vscodium.nix)) but they would be able to help troubleshoot further.

**Comment by zeta-00** [comment]
hello @stripedpajamas ,
I am running xmonad without a desktop environment, so it there some functionality that vscodium is missing which is causing it not to work? I already asked the xmonad people and they said they don't know and to go ask the maintainers of vcodium. So at this point I have idea?

**Comment by stripedpajamas** [comment]
VSCodium is a GUI app; if you don't have a desktop environment, I don't think you can use this app.

**Comment by zeta-00** [comment]
hello again @stripedpajamas ,
Apparently it works with other window/tiling managers, but for some reason it is not working with xmonad? https://github.com/NixOS/nixpkgs/issues/80749
hmm, any ideas?
