### ISSUE TITLE
VSCodium + xmonad desktop environment

### ISSUE THREAD

**Issue by zeta-00** [VSCodium/vscodium#342]
Hello there,
I installed vscodium, but it does not open, and is throwing this error? https://hastebin.com/roqigetida.rb
So, what is causing the error and how do I fix it? At this point I have no idea?
Thanks in advance.

**Comment by zeta-00** [comment]
After talking to other people, it turns out vscodium does work with xmonad, but I am not sure how they got it working, and why i'm getting that issue?

**Comment by zeta-00** [comment]
also, i am using xmonad by itself without any desktop environment, so maybe xmonad needs some extra functionality for vscodium to work?

**Comment by sbalmer** [comment]
@zeta-00 I'm using Codium in pure Xmonad on Debian 10. Didn't have to configure anything special.

Note: Your Hastebin link is empty.
