### ISSUE TITLE
cppvsdbg not work in vscodium, but work in vscode

### ISSUE THREAD

**Issue by playgithub** [VSCodium/vscodium#344]
Can it be solved?
Thanks

**Comment by stripedpajamas** [comment]
This is an issue because the extension is "proprietary". https://github.com/VSCodium/vscodium/blob/master/DOCS.md#proprietary-debugging-tools

There's unfortunately nothing we can do about this.

**Comment by GitMensch** [comment]
@playgithub There's something you could do - ask MS to release the debugging extensions under MIT-License as "vscode" is, you'll get a bunch of upvotes for the related issue when leaving a reference here...

**Comment by playgithub** [comment]
That's hard, M$ intended to do this.
I'm considering to use Linux. It should be much easier.

**Comment by GitMensch** [comment]
> That's hard, M$ intended to do this.

What now, intended to "open-source + lock-in" or to intended to release the debugging extensions as open-source?
Using a GNU/Linux machine is quite reasonable, especially but not limited to people that do coding.

**Comment by playgithub** [comment]
> What now, intended to "open-source + lock-in" or to intended to release the debugging extensions as open-source?

Maybe, M$ intended to do telemetry, both vscode & vs can debug using M$ cpp debugger, both do telemetry.

> Using a GNU/Linux machine is quite reasonable, especially but not limited to people that do coding.

Yes, open source is much more mature nowadays.
