### ISSUE TITLE
VSCodiumSetup-x64-1.42.1.exe   gives  virus infection alert on bitdefender total security 2020 on spdlog.node

### ISSUE THREAD

**Issue by Delli** [VSCodium/vscodium#345]
hi 
the file that is infected 
 C:\Program Files\VSCodium\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node is geïnfecteerd met Gen:Variant.Ursu.760913 

this is a node package 
Simply push a new tag and the CI will automatically publish to NPM
https://www.npmjs.com/package/spdlog  is a mircosoft package

what is the deployement security policy ?

**Comment by Delli** [comment]
just curious if there is a use of Malicious Software Removal Tool  as post production step?

I reported the file to bitdefender for inspection

**Comment by Mazwak** [comment]
McAfee reported the same file here. With a very vague "RDN/Generic.dx".

**Comment by Mazwak** [comment]
Didn't see #331 before commenting.

**Comment by stripedpajamas** [comment]
I will close this in favor of #331
