### ISSUE TITLE
Not able to integrate Git Bash with VSCodium, please help.

### ISSUE THREAD

**Issue by Anonymouscaste** [VSCodium/vscodium#348]
When I add this in terminal settings : terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe
The color of this code becomes red and doesn't work.

**Comment by WhiteR4bbitt** [comment]
I believe in your `config.json` it should read:
`terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe`
Otherwise did you ever configure anything with your terminal before trying to integrate it?

**Comment by Anonymouscaste** [comment]
I forgot to put inverted commas on whole, sorry.
This is what is looks like and works great :- "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"

**Comment by Anonymouscaste** [comment]
I forgot to put inverted commas on whole, sorry.
This is what is looks like and works great :- "terminal.integrated.shell.windows": "C:\Program Files\Git\bin\bash.exe"
