### ISSUE TITLE
Python files opening in VS Studio Code...

### ISSUE THREAD

**Issue by Anonymouscaste** [VSCodium/vscodium#350]
When I open some file through VS Codium like "code hello.py" , the file opens in VS Studio Code. Please solve my problem, I have integrated Git Bash with VS codium

**Comment by Anonymouscaste** [comment]
It worked just by changing my command from "code hello.py" to "codium hello.py"(In Windows) and "vscodium hello.py"(In Linux)

**Comment by stripedpajamas** [comment]
https://github.com/VSCodium/vscodium/blob/master/DOCS.md#terminal-support for future reference
