### ISSUE TITLE
Wrong version?

### ISSUE THREAD

**Issue by eladcandroid** [VSCodium/vscodium#352]
Got 1.44 instead of 1.43 ...

![Screen Shot 2020-03-11 at 14 14 33](https://user-images.githubusercontent.com/13297000/76416020-f2f1b500-63a2-11ea-9040-5b00f65bad6d.png)

**Comment by blocknonip** [comment]
Same. Also got a new tab popping up talking about "insiders version/edition", which I definitely did not request.

**Comment by appelgriebsch** [comment]
Check this issue reported yesterday: https://github.com/VSCodium/vscodium/issues/351

**Comment by kamiyubidan** [comment]
Installation via Scoop (complete reinstall, but keeps settings) breaks the install completely. VSCodium will not start.

Seems like the auto-update mechanism might be less problematic in that regard. 

For my particular use case, I rolled back to the previous version without issues.

**Comment by stripedpajamas** [comment]
Something got confused upstream (https://github.com/microsoft/vscode/issues/92403). I've gone ahead and deleted the 1.44.0 assets from the releases page now that 1.43.0 has been properly published upstream.
