### ISSUE TITLE
brew package version mismatch

### ISSUE THREAD

**Issue by TravellerSam** [VSCodium/vscodium#356]
Installing VSCodium on MacOS 10.14 with `brew cask install vscodium` gives an error:
`Download failed on Cask 'vscodium' with message: Download failed: https://github.com/VSCodium/vscodium/releases/download/1.43.0/VSCodium.1.44.0.dmg`

As of now, the newest release listed is 1.43.0, so 1.44.0 is not found.

**Please confirm that this problem is VSCodium-specific**
- [x ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**Desktop (please complete the following information):**
 - MacOS 10.14

**Comment by dandanio** [comment]
I am trying to fix it for homebrew, but there is an issue that they are 2 bad commits ahead. :( 1.44.0 (not relased) -> 1.43.0 (not available for MacOS X) -> 1.42.1 (last available).

**Comment by stripedpajamas** [comment]
Rebuild of Mac version is in progress; PR to fix the cask is here: https://github.com/Homebrew/homebrew-cask/pull/78539

I suspect after the build is finished we may need an additional PR to the cask to get the right sha sum. Will be tracking resolution in #357
