### ISSUE TITLE
No 1.43 binary version build (*.dmg) for MacOS X

### ISSUE THREAD

**Issue by dandanio** [VSCodium/vscodium#357]
**Describe the bug**
No 1.43 binary version build (*.dmg) for MacOS X.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

Checked https://github.com/VSCodium/vscodium/releases/tag/1.43.0, not there, homebrew is broken too.

**Comment by felipesabino** [comment]
>Error: Download failed on Cask 'vscodium' with message: Download failed: https://github.com/VSCodium/vscodium/releases/download/1.43.0/VSCodium.1.44.0.dmg

My homebrew install seems to also be looking for the wrong file  (version `1.43.0` vs `VSCodium.1.44.0.dmg`)

**Comment by felipesabino** [comment]
It is actually missing all the `deb` assets, the build is [generating deb files with `1.44` version](https://travis-ci.com/github/VSCodium/vscodium/jobs/296437934#L2699)  and all zip creation [hard matches the version number](https://github.com/VSCodium/vscodium/blob/master/create_zip.sh)

**Comment by stripedpajamas** [comment]
There was an issue upstream with the versions; I've deleted the 1.44 artifacts and I'm rebuilding now. We should have 1.43.x assets in the release presently.

**Comment by stripedpajamas** [comment]
Brew should be fixed: https://github.com/Homebrew/homebrew-cask/pull/78558
