### ISSUE TITLE
Wrong checksum in RPM repository

### ISSUE THREAD

**Issue by ajvn** [VSCodium/vscodium#359]
**Describe the bug**
Wrong checksum when updating on Fedora 31 using package manager.
```
[MIRROR] vscodium-1.43.0-x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 848fc5f19007c9dff11269c68fefe34bdc2255428544e0323eeb2b973b467526(sha256)  Expected: 0f725cb7834790af5af0abd62d72287b0bfaa20818ce63f840418490e33aef78(sha256) 
```

**Please confirm that the issue/resolution isn't already documented**
- [:heavy_check_mark:  ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Run `sudo dnf update -y`
2. Get an error that checksum is not same as expected in multiple mirrors.

**Expected behavior**
Update to a new version.

**Desktop (please complete the following information):**
 - OS: Fedora 31
 - Architecture x86-64
 - Package manager: dnf
 - Kernet version: 5.5.7-200.fc31.x86_64

**Comment by Micronetic** [comment]
The same in the AUR: https://aur.archlinux.org/packages/vscodium-bin/

**Comment by abitrolly** [comment]
Problems with RPM packages are tracker here - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo

**Comment by steffendietz** [comment]
@ajvn you could try cleaning the `dnf` caches with `dnf clean all`. At least that has worked for me.

**Comment by Hr46ph** [comment]
> @ajvn you could try cleaning the `dnf` caches with `dnf clean all`. At least that has worked for me.

While this works, at least this time, its more of a work around than a solution. This issue shouldn't happen at all under normal circumstances.

**Comment by stripedpajamas** [comment]
This repo doesn't manage/control the RPM repository. As @abitrolly said, issues can be tracked in https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo

I'm not sure who/where the AUR repository is managed, so I don't have an issue tracking link to provide for problems experienced there.
