### ISSUE TITLE
codium as app executable name instead of vscodium?

### ISSUE THREAD

**Issue by 435vic** [VSCodium/vscodium#36]
The titles, names, and executables in the official and OSS versions all are variations of `code` and `code-oss` respectively. Maybe we should keep the pattern by making the executable `codium`? Also I think the  Visual Studio name is copyrighted by Microsoft, not sure, but we might as well be careful. Something else I like about the original `code` executable is that it's very quick to type, enabling commands like `code ~/very/big/path` feel more fluent and quick.

**Comment by JL2210** [comment]
See number #28.

**Comment by 435vic** [comment]
I see... Well, that does make sense. Thank you!

**Comment by drasbeck** [comment]
@435vic you could always just create a symlink to `vscodium`, called `codium`.

**Comment by dzmitry-lahoda** [comment]
https://github.com/VSCodium/vscodium/issues/28

**Comment by dzmitry-lahoda** [comment]
Renaming to `codium` would make me happy. 

When I type `code` and get into editor - cool. 
When I type `vscodium` - I am unhappy.

**Comment by JL2210** [comment]
Just make a symlink or an alias.

**Comment by dzmitry-lahoda** [comment]
```
New-Alias code vscodium
```

**Comment by JL2210** [comment]
No, put alias code=vscodium in your bashrc.

**Comment by stripedpajamas** [comment]
I think @dzmitry-lahoda is on Windows @JL2210

**Comment by bittner** [comment]
Can we reopen this issue? I'd like to fix this problem for everyone.

**Comment by bittner** [comment]
Personally, I'd like to stick to the pattern that the non-free distribution follows:

* VSCode --> `code`
* VSCodium --> `codium`

That will make it also easier for developers transitioning from VSCode to VSCodium.
Muscle memory is a thing that is hard to overcome.

**Comment by stripedpajamas** [comment]
All yours @bittner 💙 

This is a breaking change, so proceed with caution. Making the change should be simple (change product.json pre-build). I suppose we will need a big notice in the changelog of the next release that lets people know that `vscodium` will no longer work (and therefore anyone who has `alias code=vscodium` will break as well). I'm not sure if any extensions are affected. Some extensions try to call the binary itself... I remember this coming up in an issue a couple of weeks ago but I don't recall where it ended up.

**Comment by bittner** [comment]
Cool, thank you!

I'm not totally sure, but shouldn't it possible to simply change the value for `applicationName` in [build.sh](https://github.com/VSCodium/vscodium/blob/master/build.sh#L24)? I'll try that in a PR. I hope the build will tell me when things break.

Do we have functional tests? I don't see any. We may want to add a simple one (à la "run `codium --version`") to the `before_deploy:` block or after calling `./build.sh` in [.travis.yml](https://github.com/VSCodium/vscodium/blob/master/.travis.yml#L29-L33).

**Comment by stripedpajamas** [comment]
Yes that's where the change should be made -- that's the part that updates the product.json file right before building.

**Comment by bittner** [comment]
Everyone looking into upgrading your `vscodium` package, please [read my hints](https://github.com/VSCodium/vscodium/pull/176#issuecomment-501396622) in the PR. :eyes: 

Thanks @stripedpajamas and @paulcarroty! :1st_place_medal:  :clinking_glasses: :champagne:

**Comment by drasbeck** [comment]
Thanks @bittner. 💪

Now I'm happily waiting for this change to silently appear via homebrew.
