### ISSUE TITLE
Missing ffmpeg.dll with UserSetup v1.43

### ISSUE THREAD

**Issue by brikabrak** [VSCodium/vscodium#361]
**Describe the bug**
Reference to #360 which corrected builds for v1.43.

After install of VSCodiumUserSetup-x64-1.43.0.exe, I cannot launch VSCodium and am told ffmpeg.dll cannot be found; advised to reinstall program. Reinstall does not fix the issue and ffmpeg.dll is not included in the v1.43 install folder.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium. (Tested with VSCodeUserSetup-x64-1.43.0.exe)

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install a fresh copy of VSCodiumUserSetup-x64-1.43.0.exe.
2. Attempt to open exe.
3. See error.

**Expected behavior**
Program opens as expected. ffmpeg.dll is included in install directory.

**Desktop (please complete the following information):**
 - OS: Windows
 - Architecture x64

**Comment by TheFreeman193** [comment]
I can confirm this is happening for the 64-bit build for windows, version 1.43.0.

Looking at both the installers (Setup and UserSetup) as well as the ZIP archive, the ffmpeg library isn't even included in the 64-bit release, but is as expected in the 32-bit one.

Copying an appropriate x64 ffmpeg.dll from elsewhere (such as the 1.42.1 64-bit release) fixes the issue, but looks like it was missed out of the latest build.

**Comment by zume2020** [comment]
yes, getting the same error!

**Comment by safeerbhatti** [comment]
Same

**Comment by vonwiktor** [comment]
same here...

**Comment by brikabrak** [comment]
Closing this as I've waited enough time that 1.44.2 UserSetup is now working correctly on install.

**Comment by TrixniteTech** [comment]
same
