### ISSUE TITLE
Can not start application on macOS

### ISSUE THREAD

**Issue by Weltraumschaf** [VSCodium/vscodium#370]
The current version 1.43.2 can not launch on macOS. Error message in popup window: 

> “VSCodium.app” can’t be opened because Apple cannot check it for malicious software.

- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

1. `brew cask install vscodium` or download & unzip
2. doubble click VSCodium.app in `/Application`
3. See error

I expect the program to launch.

 - OS: macOS 
 - Architecture: x64
 - Version: 10.14.6

**Comment by entepe85** [comment]
Possible solution:

1. Open Finder
1. Navigate to Applications folder
1. Right-click VSCodium and select open
1. Confirm opening the application in the appearing popup window

You should then be able to launch VSCodium subsequently.

**Comment by Weltraumschaf** [comment]
I can't reproduce it anymore. Was there an update? Or maybe reboot fixed it...
