### ISSUE TITLE
Integrate with Open VSX Registry

### ISSUE THREAD

**Issue by rrmckinley** [VSCodium/vscodium#372]
Please integrate with Open VSX Registry, open-vsx.org. It provides extensions for VS Code compatible editors in a community driven way.

Example from Theia:
https://github.com/eclipse-theia/theia/commit/73bd544d99a1f93159cc83cedd9769e627033811

**Comment by svenefftinge** [comment]
We definitely plan to support VS Code and with that VS Codium. We need to reverse engineer the proprietary marketplace API and hook up an adapter to translate between openvsx protocol and that. Any help is highly appreciated.
https://github.com/eclipse/openvsx/issues/55
