### ISSUE TITLE
[WSL1] Cannot open file/folder with command "codium ."

### ISSUE THREAD

**Issue by ianyepan** [VSCodium/vscodium#373]
Thank you for this project! I'm trying to get VSCodium working on my Windows Subsystem for Linux (WSL1). However, when I try to open a project folder with `codium .` from the terminal (Ubuntu 18.04 LTS), it gives me the following error message:
```
/mnt/c/Users/bquine/.vscode-oss/extensions/ms-vscode-remote.remote-wsl-0.42.4/scripts/wslCode.sh: 49: /mnt/c/Users/bquine/.vscode-oss/extensions/ms-vscode-remote.remote-wsl-0.42.4/scripts/wslCode.sh: /home/ianpan/.vscode-server-oss/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/bin/codium: not found
```
I have tried using `code .` from VSCode stable and `code-insiders .` from VSCode Insiders and both work fine.

**Comment by Miaourt** [comment]
Same error, it seems that the binary isn't named `codium` but `code`
![image](https://user-images.githubusercontent.com/1571367/78513075-5e178700-77a9-11ea-948f-6fac40f4fc30.png)

Renaming it `codium` seems to work but then the connection couldn't be established from VSCodium

**Comment by stripedpajamas** [comment]
Hi @ianpan870102 and @Miaourt -- can you provide some more context on the setup here? I'm seeing reference to an extension (`ms-vscode-remote.remote-wsl-0.42.4`?)... perhaps the extension is expecting `code` and `code-insiders`? 

How was VSCodium installed on your computers?

**Comment by Rohaq** [comment]
> Same error, it seems that the binary isn't named `codium` but `code`
> ![image](https://user-images.githubusercontent.com/1571367/78513075-5e178700-77a9-11ea-948f-6fac40f4fc30.png)
> 
> Renaming it `codium` seems to work but then the connection couldn't be established from VSCodium

As a workaround, you could try creating an alias for `vscodium` in your chosen shell user profile pointing to the `code` binary?

**Comment by Miaourt** [comment]
Sadly I don't have access to the environment anymore, and back then I ended up using the proprietary vscode ^^'

**Comment by hematogender** [comment]
Still doesn't work, same problem as Miaourt had. Any ideas how to fix it?

**Comment by hematogender** [comment]
Bad news, this extension is closed-source 😭 

#266 #196 #240 
https://github.com/microsoft/vscode-remote-release/issues/1925

**Comment by vdurante** [comment]
@Rohaq creating an alias doesn't work.

**Comment by Rohaq** [comment]
> @Rohaq creating an alias doesn't work.

Would this not work in your Powershell profile, for example?
```ps1
function Invoke-VsCodium {
    code $args
}
Set-Alias codium Invoke-VSCodium
```

**Comment by vdurante** [comment]
@Rohaq 

Thanks for the response, but I just gave up on WSL. It feels that the extension requires VSCode to be running and since VSCodium has different naming internally it simply doesn't work.

I would guess the solution would require VSCodium to stop renaming a few things internally. But I feel this won't happen, either due to VSCodium or Microsoft restrictions.

**Comment by joaoreis13** [comment]
This error persists, a year later. Posting here hoping someone can take a look at this, or...get back to VS Code...

- VSCode Version: "1.58.2" (fresh install)
- Local OS Version: WSL
- Remote OS Version: n/a
- Remote Extension/Connection Type: n/a
- Logs:
`XXXXXX@yyyy:/mnt/c/Users/XXXXXX$ codium
/mnt/c/Users/XXXXXX/.vscode-oss/extensions/ms-vscode-remote.remote-wsl-0.58.2/scripts/wslCode.sh: 69: /mnt/c/Users/XXXXXX/.vscode-oss/extensions/ms-vscode-remote.remote-wsl-0.58.2/scripts/wslCode.sh: /home/XXXXXX/.vscode-server-oss/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/bin/codium: not found`

```
$ ls -ls /home/XXXXXX/.vscode-server-oss/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/
total 72220
      16 -rw-r--r--  1 XXXXXX XXXXXX    13380 Jul  8 03:53 LICENSE
        4 drwxr-xr-x  3 XXXXXX XXXXXX     4096 Jul  8 03:54 bin
        4 drwxr-xr-x 34 XXXXXX XXXXXX     4096 Jul  8 03:54 extensions
72144 -rwxr-xr-x  1 XXXXXX XXXXXX 73873984 Jul  8 03:54 node
        4 drwxr-xr-x 74 XXXXXX XXXXXX     4096 Jul  8 03:54 node_modules
        4 drwxr-xr-x  3 XXXXXX XXXXXX     4096 Jul  8 03:54 out
        4 -rw-r--r--  1 XXXXXX XXXXXX     1059 Jul  8 03:53 package.json
      36 -rw-r--r--  1 XXXXXX XXXXXX    34748 Jul  8 03:53 product.json
        4 -rwxr-xr-x  1 XXXXXX XXXXXX      222 Jul  8 03:53 server.sh
```
```
ls -ls /home/XXXXXX/.vscode-server-oss/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/bin/
total 8
4 -rwxr-xr-x 1 tidereis13 tidereis13  335 Jul  8 03:53 code
4 drwxr-xr-x 2 tidereis13 tidereis13 4096 Jul  8 03:54 helpers
```

Steps to Reproduce:

1. Install VSCodium in WSL Ubuntu using APT package manager
2. Run "codium ." in any directory

**Comment by daiyam** [comment]
@joaoreis13 All Remote extensions from Microsoft are proprietary and aren't open source. Their licenses exclude any use outside Visual Studio Code. There is nothing we can do.
We need to find or develop our own alternative to this interesting feature.

**Comment by joaoreis13** [comment]
Thanks for the information. Looking forward when VSCodium has this features too.

**Comment by daiyam** [comment]
I've added the wiki page: https://github.com/VSCodium/vscodium/wiki/Extensions-Compatibility
