### ISSUE TITLE
dmg.sha256 contains file name with space instead of "." separating name and version

### ISSUE THREAD

**Issue by gavinbeatty** [VSCodium/vscodium#375]
e.g., contents of VSCodium.1.43.2.dmg.sha256:
```
3a81ed31c30cd758b16601a764d289561ad57b4da02bfaa01ebdbff9a577215e  VSCodium 1.43.2.dmg
```
However, the dmg file listed for 1.43.2 is named "VSCodium.1.43.2.dmg". Note the "m.1" not "m 1".

This prevents `sha256sum -c VSCodium.1.43.2.dmg.sha256` from finding the dmg. Editing the sha256 file works of course.

**Comment by stripedpajamas** [comment]
Thanks for the heads up @gavinbeatty -- I think Travis was taking the space out during upload to GH Releases, but the shasum happens before then. I've opened #385 to correct; will merge when I've confirmed it works.

**Comment by stripedpajamas** [comment]
Looks like #385 works! https://github.com/stripedpajamas/vscodium/releases/download/1.44.2/VSCodium.1.44.2.dmg.sha256

Will take affect on next release.
