### ISSUE TITLE
Win Arm64 (WoA) Build

### ISSUE THREAD

**Issue by davide-rota** [VSCodium/vscodium#379]
Hi, it should be now possible to build vscode for Win ARM64 and it would be great if vscodium offered such a version (as a Surface Pro X user I would be very happy!) https://github.com/microsoft/vscode/pull/85326#issuecomment-613386485

Do you plan to offer Win ARM builds?
Thanks

**Comment by stripedpajamas** [comment]
for sure! just need to figure out what deps are required and then update our build scripts. PRs welcome :smile:
