### ISSUE TITLE
Which 1.44.1 should I choose?

### ISSUE THREAD

**Issue by JL2210** [VSCodium/vscodium#381]
There are several 1.44.1 versions on the releases page. It's unclear which one I should use.

Since this is about VSCodium releases, I would say so. I don't see anything of the like in Microsoft's releases page.

The DOCS page says nothing of the sort.

1. Go to https://github.com/VSCodium/vscodium/releases
2. Scroll down to 1.44.1
3. See 1.44.1 twice

**Expected behavior**
See 1.44.1 only once

**Screenshots**
![Screenshot 2020-04-15 at 7 48 03 PM](https://user-images.githubusercontent.com/38843657/79399731-213e5380-7f52-11ea-9746-8e0302e8133d.png)

 - OS: Debian 10 Buster
 - Architecture: AMD64
 - Version: 1.44.1

**Comment by JL2210** [comment]
Now the 1.43.2 release has 1.43.2, 1.44.0, 1.44.1, and 1.44.2. What gives?

**Comment by scottfurry** [comment]
A guess on my part is that the right tag isn't being employed. Something wrong with how assets are being added to release. There was a mess created upstream with wrong version was used about a month ago. Ever since, new assets get added old tag (v1.43.2).

**Comment by stripedpajamas** [comment]
Like @scottfurry said, I think something went awry upstream with the tagging. When the VSCodium builds run, they use the latest tag in the MS repo to label the release. MS (at least up until last month) has pushed a new tag for every version. I think things have straightened out now; the last build of VSCodium is released as 1.44.2 and is tagged to 1.44.2, and this is the version that should be used. Anyone who wants to install 1.44.1 can use the 1.44.1 release that is tagged to 1.44.1. Most likely I will delete the releases that have mismatching tags.
