### ISSUE TITLE
Update download failed 1.44.0

### ISSUE THREAD

**Issue by john-arvid** [VSCodium/vscodium#382]
**Describe the bug**
Update download failed. The server sent an invalid response. Try again later. Source: Update Service

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium. 

I don't have MS Visual Studio Code

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Click on VSCodium or Settings cog
2. Click on Check for updates...

**Expected behavior**
Not produce an error

**Desktop (please complete the following information):**
Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-09T11:03:46.219Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0

**Comment by john-arvid** [comment]
Suddenly saw that it had updated automatically. My theory is that the update server was not available, but I can not say since the error message was so vague.

Since it might not been a bug I will close this. Don't have any feature labels that I can add.

**Comment by nbara** [comment]
I'm having the same message pop up every time I fire up VSCodium on macOS

### System information


CPUs | Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | 3, 3, 2
Memory (System) | 32.00GB (4.97GB free)
Process Argv |  
Screen Reader | no
VM | 0%
