### ISSUE TITLE
Last 4 releases are the same

### ISSUE THREAD

**Issue by nikitrkmn** [VSCodium/vscodium#384]
hey,
what's going on. Last 4 releases are the same.

**Comment by stripedpajamas** [comment]
Hi @nikitrkmn -- what do you mean by "the last 4 releases are the same"?

**Comment by nikitrkmn** [comment]
hi @stripedpajamas 
Last included commit in latest release.
![Screen Shot 2020-04-20 at 01 13 43](https://user-images.githubusercontent.com/3787035/79701255-4b6e7900-82a4-11ea-996c-1c5128dca486.png)

Latest release 1.44.2
![Screen Shot 2020-04-20 at 01 13 56](https://user-images.githubusercontent.com/3787035/79701266-5f19df80-82a4-11ea-853d-bc2baf96d38d.png)

Same releases
![Screen Shot 2020-04-20 at 01 14 11](https://user-images.githubusercontent.com/3787035/79701276-69d47480-82a4-11ea-90a6-6cb09b6b900e.png)

@stripedpajamas you released 4 version in 1 month, but all of this releases are same, no difference

**Comment by stripedpajamas** [comment]
Oh yes. The commits/notes may be confusing. VSCodium is a project that builds Microsoft's vscode repo automatically. So there is a new release every time Microsoft cuts a new release. As such, there may be no new commits on the VSCodium side (hence same commit mentioned). And there may be many releases in a single month (up to Microsoft to decide). If you have questions about how it all works, feel free to chat with us on gitter.im (link in README).
