### ISSUE TITLE
Unable to Open Folder through GUI

### ISSUE THREAD

**Issue by allen505** [VSCodium/vscodium#386]
**Describe the bug**
Unable to open folder from _File>Open Folder_ 

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.
It is similar to Issue #373 , but in my case `codium .` worked from terminal, but the GUI option didn't

**To Reproduce**
1. Go to 'File' on the top Menu bar
2. Click on 'Open Folder'
3. Try opening a folder with files and sub-folders

**Expected behavior**
The selected folder is supposed to open. To go deeper (i.e. to the subfolders) the folder needs to be double clicked in the folder explorer.

**Actual behavior**
It opens the directory within the file explorer till a file is selected, when it works the same as _Open File_ by opening the selected file

**Desktop (please complete the following information):**
 - OS: Manjaro Lysia 20.0
 - Architecture 64-bit
 - Version VSCodium 1.44.2

**Additional context**
I installed Codium from AUR.

**Comment by smac89** [comment]
What file manager do you use?

**Comment by allen505** [comment]
I use Dolphin which comes pre-installed on Manjaro KDE
