### ISSUE TITLE
Confusing release page (VSCodium, VSCodiumSetup, VSCodiumUserSetup)

### ISSUE THREAD

**Issue by ilindaniel** [VSCodium/vscodium#391]
The release page is offering following files for Win x64:
VSCodium-win32-x64-1.44.2.zip
VSCodiumSetup-x64-1.44.2.exe
VSCodiumUserSetup-x64-1.44.2.exe

What's the difference between those files? I could not find any explanation in the readme.md or on the wiki page.

**Comment by stripedpajamas** [comment]
Please refer to Microsoft's guide regarding this: https://code.visualstudio.com/docs/setup/windows
