### ISSUE TITLE
New Icon Look

### ISSUE THREAD

**Issue by rejedai** [VSCodium/vscodium#392]
I really like this project, but the icon looks a little... ugly.
Well, I redrawn the icon, deleted the circle and made it bold.

![image](https://user-images.githubusercontent.com/60342258/80908497-fc572800-8d28-11ea-9140-d305e6b0a0eb.png)

And look for 4 different backgrounds:
![image](https://user-images.githubusercontent.com/60342258/80908502-09741700-8d29-11ea-8d69-9d90738c2e09.png)

Comparison of the old and the new look of the icon.
![image](https://user-images.githubusercontent.com/60342258/80908514-23adf500-8d29-11ea-8c16-66133697b930.png)

And comparison with VS Code icon.
![image](https://user-images.githubusercontent.com/60342258/80908563-7daeba80-8d29-11ea-9977-3117785e5fbf.png)

If you are interesting i can made vector version.

**Comment by rejedai** [comment]
I have new an idea 

![image](https://user-images.githubusercontent.com/60342258/80918011-58db3700-8d6b-11ea-8ac1-3066a7f3ed7d.png)

What do you think?

**Comment by stripedpajamas** [comment]
Please move discussion to #313 where we are voting on new logo and color.
