### ISSUE TITLE
The icon in the upper-left corner is changed?

### ISSUE THREAD

**Issue by xuchengpeng** [VSCodium/vscodium#394]
The icon is strange......
Version: VSCodium-win32-x64-1.45.0.zip

**Comment by ellietheoracle** [comment]
what icon are you talking about ? could you provide a screenshot ? is this issue vscodium specific ?

**Comment by xuchengpeng** [comment]
> what icon are you talking about ? could you provide a screenshot ? is this issue vscodium specific ?

Checkout #406

**Comment by ellietheoracle** [comment]
oh, ok, so then you should probably delete this issue, since the other one is much more descriptive .

**Comment by xuchengpeng** [comment]
Duplicated with #406 ,close this issue
