### ISSUE TITLE
VSCodium icon renders badly in Gnome

### ISSUE THREAD

**Issue by ixxie** [VSCodium/vscodium#396]
VSCodium icon does not render well in Gnome:

![Screenshot from 2020-05-09 23-32-59](https://user-images.githubusercontent.com/20320695/81484399-c5fc3a00-924d-11ea-85fe-02208aca2bac.png)

Suspected cause is that the resolution of the icon is not correct. Following a guide such as [this one](https://icons8.com/articles/choosing-the-right-size-and-format-for-icons/) should allow choosing the right icon resolutions and filetypes to support a variety of distributions, but I am not sure what other code-base or upstream packaging changes would be needed otherwise.

Adding an SVG version may be an easy improvement for most cases, and would at least fix the Gnome case.

**Comment by gafarma89** [comment]
That's true. but more simple (KISS based) icon would be great. This project should not lost time with an icon.

**Comment by ixxie** [comment]
If I had the original SVG I would happily contribute a PR for icon sizes; I could also design a new and simplified icon potentially.

**Comment by rivetchip** [comment]
Seems like you are using Numix Circle icons ? If yes the "codium.desktop" file refer the icon as "Icon=vscodium", which is located in "/Numix-Circle/48/apps/vscodium.svg".

Maybe you should update your icon pack, or submit an issue to Numix ? 

For me it render like this :  
![Capture d’écran du 2020-06-22 00-46-04](https://user-images.githubusercontent.com/7000625/85236850-341d4a80-b411-11ea-8e51-d688b156be10.png)

I'm on X11, now with "default" Adwaita : maybe it render differently on Wayland ?
![Capture d’écran du 2020-06-22 00-49-39](https://user-images.githubusercontent.com/7000625/85236899-a42bd080-b411-11ea-8fcd-5ca66a3cce86.png)

**Comment by ixxie** [comment]
@rivetchip I didn't think of that! Very good point.
