### ISSUE TITLE
Install extension command not work with appimage

### ISSUE THREAD

**Issue by gafarma89** [VSCodium/vscodium#397]
This command does not work ( but it works on microsoft vscode )

> vscodium.AppImage --install-extension "darkriszty.markdown-table-prettify"

Above command opens vscodium GUI. no warnings, no errors.

I try this on the latest version of vscodium also with Ubuntu 20.04 and 18.04 also on 2 different machines. One of them is:

```
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-14T03:45:36.707Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.4.0-29-generic
```

Thank you

**Comment by GitMensch** [comment]
Just to recheck:

* It works on the AppImage of Visual Studio Code, but not on the AppImage of VSCodium, correct?
* Where do you get both AppImages from?

**Comment by Lonniebiz** [comment]
@gafarma89 I'll like to try VSCodium, but will only do so if there is an AppImage for it. I can't find one, but you mention one. Where is that?

**Comment by GitMensch** [comment]
> @gafarma89 I'll like to try VSCodium, but will only do so if there is an AppImage for it. I can't find one, but you mention one. Where is that?

https://github.com/VSCodium/vscodium/releases/ has those, the current one is https://github.com/VSCodium/vscodium/releases/download/1.69.2/VSCodium-1.69.2-1658192312.glibc2.17-x86_64.AppImage (and other than Ubuntu's "snaps" this should have no permission regressions).

@paulcarroty Do you think we can leave a link to the newest AppImage on vscodium.com? If not: what do you think of at least mentioning it there (a paragraph before the snap one)? I may be able to PR some text if that helps.

**Comment by paulcarroty** [comment]
Sure, we can forward to `https://github.com/VSCodium/vscodium/releases/latest` or even to the direct link, a bit JS required.
