### ISSUE TITLE
How to install vs codium on linux 32 ?

### ISSUE THREAD

**Issue by OrnithOrtion** [VSCodium/vscodium#399]
Hello,
I tried to build vscodium from source but it didn't worked.
Is there already a way to do so, using a previous release that supports 32 bit linux ?

**Comment by OrnithOrtion** [comment]
Does this way work for linux 32 Ubuntu mate distribution (18.04)
[](https://github.com/VSCodium/vscodium/issues)

**Comment by Rowisi** [comment]
Electron no longer supports linux 32bit

https://www.electronjs.org/blog/linux-32bit-support

**Comment by OrnithOrtion** [comment]
Ok, too bad.
I'll use atom, until I have a 64 bit machine.

**Comment by stripedpajamas** [comment]
Right-- Microsoft stopped releasing Visual Studio Code for Linux 32-bit at version 1.35.1 for this reason. If you'd like to try it, you can download that release from your releases page, which has the Linux 32-bit assets.

**Comment by OrnithOrtion** [comment]
Thanks a lot, I didn't found the deb package in the previous releases, I am going to install this version..
