### ISSUE TITLE
Better Icon

### ISSUE THREAD

**Issue by ryanolsonx** [VSCodium/vscodium#4]
We should come up with a better icon for the FOSS version. The FOSS icon is really ugly.  That would be sugar on top of the cake. 👍

**Comment by Breakthrough** [comment]
Here's my go at a logo which looks fairly decent as an icon (see attached).  Feel free to use it (or not) in any way you would like.  ([Source](https://openclipart.org/detail/173827/leaves-and-branches-2))
![vscodium-logo-32x32](https://user-images.githubusercontent.com/125316/44695772-cbe2c500-aa42-11e8-8875-045658b0772d.png)
![vscodium-logo-64x64](https://user-images.githubusercontent.com/125316/44695773-cbe2c500-aa42-11e8-82e3-7cf767eea45f.png)
![vscodum-logo](https://user-images.githubusercontent.com/125316/44695774-cbe2c500-aa42-11e8-92a3-6560b22fe94d.png)

**Comment by stripedpajamas** [comment]
Thank you so much for this contribution, @Breakthrough 

@ryanolsonx I also agree the current icon sucks. I'm a little wary of changing too much of original source repo during build because I want to keep trust levels high. But I think updating the icon shouldn't be too crazy, if it can be done in a very straightforward way. PRs are welcome. I'll do it if I can get some free time in the coming days.

**Comment by jaredreich** [comment]
Not sure if this is too close to the original, but here's one I've used before to replace the original MS ones, which I think are ugly.
[vscodium.icns.zip](https://github.com/VSCodium/vscodium/files/2397358/vscodium.icns.zip)
![vscodium](https://user-images.githubusercontent.com/8563847/45758294-80a37880-bbe2-11e8-8a5b-a760c5a1ef7d.png)

**Comment by solie** [comment]
something like code ninja :D
![codium_logo](https://user-images.githubusercontent.com/1745596/46149168-469a3c80-c29c-11e8-8964-3d94a3161ce5.png)
sample:
![screenshot from 2018-09-27 21-26-44](https://user-images.githubusercontent.com/1745596/46149249-78130800-c29c-11e8-9815-e99a9c10a1b1.png)

**Comment by clarsonneur** [comment]
Proposed this code change...

**Comment by stripedpajamas** [comment]
Thank you for the PR @clarsonneur 

To anyone involved in this discussion, here are my thoughts:
- The current MS icon sucks
- Three icons have been proposed, so I think it comes down to how many 👍 each gets to decide
- The gorgeous icon proposed by @jaredreich I believe would be considered a copyright violation for us to use as it is nearly identical to the Visual Studio icon ([reference](https://visualstudio.microsoft.com/downloads/)). I don't want any possibility of copyright problems so I'm not considering that icon (unless anyone can show that it would be safe).
- The most 👍 s would then fall to the tree icon submitted by @Breakthrough, which @clarsonneur has kindly put a PR in for (#25)

I am inclined to merge this PR but I wanted to make sure everyone has a chance to speak up if they have any hesitations about this.

**Comment by jaredreich** [comment]
@stripedpajamas I agree about the potential copyright issues. I think the tree icon is aiming to look like "codium" which is a type of algae, but yeah it looks more a standard tree. I'll post another set of icons shortly.

**Comment by vforge** [comment]
@jaredreich You can hardly recognize the tree in the very small icon (not to mention the leaves and branches are not visible at all). I suggest using a simpler, more geometric icon (or tree/algae representation).

**Comment by jaredreich** [comment]
What do y'all think? (.icns files are in the .zip file below)

<img src="https://user-images.githubusercontent.com/8563847/46382826-356d7900-c66a-11e8-9dba-93439497f3e3.png" width="150" height="150">
<img src="https://user-images.githubusercontent.com/8563847/46382827-37373c80-c66a-11e8-8d91-81706f6e7a3c.png" width="150" height="150">

[codium.zip](https://github.com/VSCodium/vscodium/files/2440096/codium.zip)

**Comment by sam0x17** [comment]
is it bad that I love the ms icon?

**Comment by clarsonneur** [comment]
Great. To be honest, I prefer when we have few colors. It is quite monochrome icon. But I'm ok. 
I can update the PR with those icons.

**Comment by Jorgeelalto** [comment]
Well, to be honest being a monochrome icon you can change the gray to any other dark shaded colour and it will work nice. Maybe we can try with green or blue?

**Comment by clarsonneur** [comment]
Sure. Let's make a try.

**Comment by Jorgeelalto** [comment]
![export](https://user-images.githubusercontent.com/32217459/46409680-b5511d00-c716-11e8-8657-e3ff12ab7778.png)

Hey, this is a quick test with some colors. Personally I like the light and dark blue, and the light green, because the dark green is too similar to Atom. The orange ones were just a test and I don't really think they fit too well. Note that I call "dark" to the colour filled ones with the white tree, and "light" the ones which are white with the colored tree.

[colored.zip](https://github.com/VSCodium/vscodium/files/2441947/colored.zip)

**Comment by clarsonneur** [comment]
I vote for green one! :-)

**Comment by jaredreich** [comment]
Let's not use green only because of one person's opinion. For me, I liked grey because it doesn't associate with any brand and implies plain and clean.

A vote would make sense here.

![image](https://user-images.githubusercontent.com/8563847/46414356-c9c1f500-c6d7-11e8-8985-0d0958e80916.png)

👍 - grey
😄 - green
🎉 - blue
❤️ - other

**Comment by stripedpajamas** [comment]
@jaredreich it looks like blue has beat grey by a small margin. Maybe we give it one more day and then move forward?

I am curious, regardless of which one is voted in, are we using the colored-background-white-logo or the white-background-colored-logo? Another vote?

**Comment by jaredreich** [comment]
New vote:

![image](https://user-images.githubusercontent.com/8563847/46486187-1417a480-c7b2-11e8-84aa-693346cb99e1.png)

Whatever the result, here are all the assets (including sketch files):
[codium_icons.zip](https://github.com/VSCodium/vscodium/files/2447066/codium_icons.zip)

👍 - light blue
🎉 - dark blue

**Comment by stripedpajamas** [comment]
@clarsonneur can you update your PR with the voted for icon?

**Comment by Jorgeelalto** [comment]
The custom icon set for every file type is a bit more of work but it's certainly feasible. I would not mind working on that to be honest, but maybe we can focus on the linux icon set, the win32 icons for the installer (and the 150x & 70x versions). I think we can easily generate those from the original files by @jaredreich :)

**Comment by jaredreich** [comment]
You should be able to generate everything you need from the sketch file I uploaded. I think a nice icon is pretty important if you want anyone to use this app.

@stripedpajamas are you not able to do this, being the original contributor?

**Comment by stripedpajamas** [comment]
I would do it but I don't know how. Anyone with more expertise with icons can help out here. Thank you @jaredreich for all the work so far 🙏

**Comment by clarsonneur** [comment]
@stripedpajamas Yes, I will update the PR.

**Comment by clarsonneur** [comment]
@jaredreich @stripedpajamas, I reworked on the PR, but I'm in trouble to generate icns files...

The only thing I can do, is to convert png to icns (from linux)
But, doing that way, I got an icns file with a single icon, while vscode has multiple icons for each icns file.

I tried https://iconverticons.com/online/ to convert ico files to icns, or from png.
But, doing that way, I got a HQX file format, where I can't extract the icns.
I tried the macutils to extract the resource file, but then... I don't know how to extract the icns from that resource file (*.RSRC).

I'm currently blocked here.
Any help or hint would be appreciate to move further...

**Comment by jaredreich** [comment]
Maybe try http://www.img2icnsapp.com/ (mac only) or https://cloudconvert.com/png-to-icns

**Comment by clarsonneur** [comment]
I'm under Linux. So, the first one won't work.

I tried the second one, but I did not used properly. I retried and it looks good! So, thanks, I will use that one!

**Comment by paulcarroty** [comment]
This issue was created 43 days ago. Maybe it's time to speed up slowly? :smile: 

@clarsonneur Photoshop 2018 works great under wine.

**Comment by clarsonneur** [comment]
@paulcarroty Thanks for the suggestion. I have wine for a while, but I avoid it... usually it is not well working for different unknown reason. So, I prefer to avoid. 

Anyway, the last website is the right one to fix the latest issue for mac. And then it will be done. normally today.

**Comment by clarsonneur** [comment]
The PR is ready

I have a doubt about the icns file.
I was able to create each for same image format (256/512) in single files from several png files, but it looks like transparency has been lost.

I used the `png2icns` which finally do a better job than https://cloudconvert.com/png-to-icns
I reworked all vscode icons.

I thought to expose the code to generate them from a script. But I don't know if that make sense for you guys.
Anyway, I think we have all to go forward now.

**Comment by stripedpajamas** [comment]
Thanks for everyone's help and discussion to get this wrapped up! 🙏

I will rebuild release 1.28.0 and update homebrew so new downloads get the new icon.

**Comment by rm--** [comment]
Looks very cool! Thanks to all of you.

**Comment by harvest316** [comment]
Sorry, still pretty garish compared to other icons.  Way to complex.  Need something simpler like @jaredreich 's original suggestion, just reimagined so it doesn't break copyright.  https://github.com/VSCodium/vscodium/issues/4#issuecomment-422816484

**Comment by harvest316** [comment]
Here's a Windows PowerShell script to set your VSCodium icon to anything you like.  Just stick the icon in the same folder, and call it VSCodium.ico

```powershell
Write-Host "`n========= Setting VSCodium Icon ========="
#Here's a Windows PowerShell script to set your VSCodium icon to anything you like.
#Just stick the icon in the same folder, and call it VSCodium.ico
#It presumes your install path for VSCodium is the default.  If not, change the 3rd last line.

#region Header
$debugMode = $false
if ($debugMode) { 
    Set-PSDebug -Step -Trace 2
} else {
    $ErrorActionPreference = 'SilentlyContinue'
}
$here = Split-Path -parent $MyInvocation.MyCommand.Definition
$script = $MyInvocation.MyCommand.Name
#endregion

Write-Host "`n========= Ensure Elevated Privileges ========="
#region
$identity = [System.Security.Principal.WindowsIdentity]::GetCurrent()
$principal = New-Object System.Security.Principal.WindowsPrincipal($identity)
if (-not $principal.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Warning "Not running with administrative rights. Attempting to elevate..."
    $command = "-NoProfile -ExecutionPolicy ByPass -Command `"$here\$script`""
    # Write-Host $command
    Start-Process powershell -verb runas -argumentlist $command
    Exit
}
#endregion

#And now for the guts of this script:
$Shell = New-Object -ComObject ("WScript.Shell")
$Shortcut = $Shell.CreateShortcut("$env:ProgramData\Microsoft\Windows\Start Menu\Programs\VSCodium\VSCodium.lnk")
$Shortcut.IconLocation = "$here\VSCodium.ico, 0"
$Shortcut.Save()
```

**Comment by bittner** [comment]
Just wanted to say a big, massive :bowing_man: **THANK YOU** :100: for the beautiful icon and VSCodium in general. This lightens up my day constantly. You girls and guys are all awesome! :medal_sports:

**Comment by altaway** [comment]
Poor @Breakthrough.

**Comment by Avaray** [comment]
I agree that default icon of VSCodium is terrible.
Is there any reason for Not using official VSCode icon?

BTW. All icon proposals above are also terrible. Please, don't use any of them.

**Comment by sam0x17** [comment]
I think the `codium_blue_dark` one looks great. The white version is too bright though.

**Comment by bittner** [comment]
This is all a matter of the past. The [new logo](413) rocks. Face it! And seriously, really, it's not all that bad, is it?

Be. Good. Citizens!


![](http://fc05.deviantart.net/fs30/f/2008/058/2/8/Be_A_Good_Citizen_by_lahandi.jpg)

**Comment by harvest316** [comment]
Much agreed.
