### ISSUE TITLE
ARM64 packages don't work

### ISSUE THREAD

**Issue by 435vic** [VSCodium/vscodium#40]
I just installed the deb package, but the window is empty. I'm pretty sure that it's an issue with cross compiling upstream, since I ran another repository without the VSCodium changes and the issue persisted. For now, I think we should say that ARM64 packages cannot be built correctly yet.
I hope that the issue is fixed soon, but for now I guess we still won't be able to support ARM.
I tried to file an issue to Microsoft, but since I used the VSCodium build the issue was immediately closed, telling me that "please start by filing this issue to VSCodium." The issue is [here](https://github.com/Microsoft/vscode/issues/60564) if you're curious.
![image](https://user-images.githubusercontent.com/13788817/46825767-033ed400-cd5a-11e8-8979-41c8ae1d3e31.png)
![image](https://user-images.githubusercontent.com/13788817/46826015-8d873800-cd5a-11e8-845b-8779d6ad88cf.png)

**Comment by stripedpajamas** [comment]
Sad :( I've removed the binaries and commented out the arm64 part of the build matrix until we can figure it out. I'll close this issue and we'll continue to work on ARM as a part of #6

**Comment by JL2210** [comment]
I've heard that ARM64 has some issues with regular VS C0de, too. I'm fairly sure that it's not an issue with VSCodium. Also, this isn't cross compiling.
