### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by shaeinst** [VSCodium/vscodium#400]
why anyone should trust your binary?
i read online forms, reddit answers, etc.. people were saying there in no point on using vscodium since vscode allows user to block telemetry through setting.

is there anything special about vscodium?

**Comment by stripedpajamas** [comment]
VSCodium's main difference is the license -- MIT licensed, whereas Visual Studio Code is not.

Regarding telemetry, yes it is just a setting. There is a small difference (important for some people) that VSCodium has telemetry off by default, whereas in Visual Studio Code telemetry will always be sent at least during the first run. Additionally, telemetry is sent in Visual Studio Code even for disabling telemetry.

Regarding trust-- the people who are interested in VSCodium are typically frustrated that the build process that Microsoft uses to build Visual Studio Code is a secret. For this reason VSCodium builds in public (on Travis and Azure) where anyone can inspect the build files and build logs. We try to make it easy to trust :)

But overall, VSCodium is a convenience for people who would have liked to build Visual Studio Code from source. Microsoft offers instructions but they are arduous to follow and the compilation step needs to happen again on each release. So we automate that build process. 

If you have further questions I'd love to answer more over on our gitter -- https://gitter.im/VSCodium
