### ISSUE TITLE
VSCodium crashes after launch

### ISSUE THREAD

**Issue by barmaley997** [VSCodium/vscodium#403]
Hello, i am using VSCodium a couple of months and still not updated it, and some days ago VSCodium is requested to update, i click button "Update" and update begins but was failed, it shows that executed file VSCodium.exe was blocked and options - Retry, Abort, Ignore, i choosed Retry many times and this message always shows again, so i killed process VSCodium.exe in task manager and tried to run VSCodium again but it not started - in task manager procees VSCodium.exe starts and immediately disappears, i open command shell CMD goes into folder where VSCodium was installed and type VSCodium.exe and press Enter after that i seen:

`
C:\VSCodium>VScodium.exe

C:\VSCodium>

#
# Fatal error in , line 0
# Version mismatch between V8 binary and snapshot.
#   V8 binary version: 7.6.303.31-electron.0
#    Snapshot version: 7.8.279.23-electron.0
# The snapshot consists of 701096 bytes and contains 3 context(s).
#
#
#
#FailureMessage Object: 000000B99F6FE8D0
`
My system - Windows 10 x64 Version 1909

**Comment by dalisoft** [comment]
Same issue, on macOS.

```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-15T11:07:54.108Z (2 wks ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

**Comment by ctarx** [comment]
Might be the same bug, VSCodium crashes randomly.

```
Process:               Electron [26942]
Path:                  /Applications/VSCodium.app/Contents/MacOS/Electron
Identifier:            com.visualstudio.code.oss
Version:               1.45.1 (1.45.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Electron [26942]


Date/Time:             2020-05-31 21:37:34.374 +0100
OS Version:            Mac OS X 10.15.5 (19F96)
Report Version:        12
```

**Comment by dalisoft** [comment]
Please fix this @VSCodium, i really love this tool, but random crashes forces me use of VSCode which i don't want really, please fix

**Comment by NotHM** [comment]
I've been getting a lot of crashes lately too but for different reasons mentioned above.
