### ISSUE TITLE
Icon of welcome tab fall back to code-oss

### ISSUE THREAD

**Issue by linsui** [VSCodium/vscodium#406]
**Describe the bug**
Icon of welcome tab fall back to code-oss

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**Expected behavior**
It should be vscodium's icon

**Screenshots**
![2020-05-20 23-10-15 的屏幕截图](https://user-images.githubusercontent.com/36977733/82463233-15433580-9aac-11ea-947e-511a45facb70.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Architecture [x64]
 - Version [1.45.0, 1.45.1]

**Comment by Turysaz** [comment]
I encountered the same issue for 1.45.0 on Windows 10.
The application icon looks like this, no matter what type of file I'm editing.
![grafik](https://user-images.githubusercontent.com/16538627/83000891-44f1c080-a00b-11ea-9bb5-6a07afb2dabd.png)

**Comment by stripedpajamas** [comment]
Should be fixed by #413 (builds into next MS release).
