### ISSUE TITLE
Anyway to automatically upgrade VSCodium with system setup on Windows?

### ISSUE THREAD

**Issue by playgithub** [VSCodium/vscodium#411]
Now I have to check github periodically to see if there is a new version.

**Comment by Lonniebiz** [comment]
Well, you can automate that too.

**Comment by stripedpajamas** [comment]
Auto updates should work out of the box. We run a small server (https://GitHub.com/VSCodium/update-api) that VSCodium calls to check for the latest release on GitHub. 

Have you noticed that updates are not working? If so can you provide some more context about what version, OS, etc you're running?

**Comment by playgithub** [comment]
It's greate.
I'll take care for the next update.
Thanks

**Comment by Lierrmm** [comment]
Just to add on to this;

When requesting an update from Windows 10 1909 the update-api returns a 404 status with no further information.
I have provided an image below of the notification if it helps at all.

![image](https://user-images.githubusercontent.com/13552261/84005622-4f924b00-a965-11ea-81b9-3d83c0bf46c6.png)

**Comment by playgithub** [comment]
VSCdoium 1.45.1
Windows 10
Check for Updates, shows:
![image](https://user-images.githubusercontent.com/3665590/84014243-97889080-a9ac-11ea-9d0d-ae63e684c9a6.png)

**Comment by stripedpajamas** [comment]
@Lierrmm can you provide OS + arch + type of installation (archive, system, user)? 

I just poked the API with the various combinations and look good. I suspect MS may have changed the way in which they call the Update API for some specific combination.

https://vscodium.now.sh/api/update/win32-x64-system/stable/asdf
https://vscodium.now.sh/api/update/win32-x64-user/stable/asdf
https://vscodium.now.sh/api/update/win32-x64-archive/stable/asdf
https://vscodium.now.sh/api/update/win32-ia32-system/stable/asdf
https://vscodium.now.sh/api/update/win32-ia32-user/stable/asdf
https://vscodium.now.sh/api/update/win32-ia32-archive/stable/asdf

**Comment by Lierrmm** [comment]
win32-x64-system was the version of VSCodium I installed.

System Details from winver:  Windows 10 Pro 1909 Build: 18363.836

**Comment by AlexQuiniou** [comment]
I have the same issue

> Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-15T10:23:54.161Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/34091990/84157458-0fb58b80-aa6b-11ea-8463-511dc6aaea97.PNG">

I use the install x64 version

**Comment by stripedpajamas** [comment]
Based on [this code snippet](https://github.com/microsoft/vscode/blob/master/src/vs/platform/update/electron-main/updateService.win32.ts#L93-L107), I think the issue is that MS is no longer sending "-system" up for x64 system install.

As far as I can tell (pls check my work!), the platform combinations should hit the following urls (asdf is the "commit" portion of the url):
| arch  | installer | url |
| ----- | -------- | --- |
| x64 | system | `/api/update/win32-x64/stable/asdf` |
| x64 | user | `/api/update/win32-x64-user/stable/asdf` |
| x64 | archive | `/api/update/win32-x64-archive/stable/asdf` |
| ia32 | system | `/api/update/win32/stable/asdf` |
| ia32 | user | `/api/update/win32-user/stable/asdf` |
| ia32 | archive | `/api/update/win32-archive/stable/asdf` |

The fix should be fairly trivial change in https://github.com/VSCodium/update-api (PRs welcome; I'll work on it if I have a free hour to focus).

**Comment by GitMensch** [comment]
Just a related note- auto-updates via package managers (of this and a multitude of other software) is a general option, too (works fine for me on Trisquel GNU/Linux, should work fine on other systems, too as long as you use the available package managers - see https://vscodium.com/#install).
I'd still like to see the win32-x64 updates working, too.

**Comment by playgithub** [comment]
From 1.45.1 to 1.46.0, it seems working, it shows downloading in the menu.
Because of my network environment the download speed is at 0.1MB/s.
However it works.

**Comment by GitMensch** [comment]
Didn't work for me with:

~~~
Version: 1.46.0 (system setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-12T10:32:02.515Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
~~~

Still getting a 404 error.
Reopen?

@playgithub Does it work for you? Do you also use a x64 version?

**Comment by playgithub** [comment]
It shows downloading as Menu/Help/Dowloading Update...
It's very slow, it'll take hours to download.
Tested for about 5 minutes, not error message.
Also checked the log, no error.
```
Version: 1.46.0 (user setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-12T10:32:02.515Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by GitMensch** [comment]
Rechecked, that is what my log says:

> [2020-06-19 15:21:11.109] [main] [info] update#setState idle
[2020-06-19 15:21:23.528] [main] [info] update#setState checking for updates
[2020-06-19 15:21:23.757] [main] [error] Error: Server returned 404
    at t.asJson (C:\Program Files\VSCodium\resources\app\out\vs\code\electron-main\main.js:374:953)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-06-19 15:21:23.757] [main] [info] update#setState idle
[2020-06-19 15:21:41.121] [main] [info] update#setState checking for updates
[2020-06-19 15:21:41.308] [main] [error] Error: Server returned 404
    at t.asJson (C:\Program Files\VSCodium\resources\app\out\vs\code\electron-main\main.js:374:953)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-06-19 15:21:41.308] [main] [info] update#setState idle

Is there a way to log more details?

**Comment by playgithub** [comment]
> [2020-06-19 20:46:23.787] [main] [info] update#setState idle
> [2020-06-19 20:46:28.025] [main] [info] update#setState checking for updates
> [2020-06-19 20:46:29.578] [main] [info] update#setState downloading

**Comment by GitMensch** [comment]
@playgithub Do you have a 32bit or 64bit version of VSCodium? [if not100% sure: open it, open it, then open taskmanager->details, right click on the columns, choose "platform" and have a look]
In my case it is a 64bit version of VSCodium and the previous discussion here hinted that only those are broken.

**Comment by playgithub** [comment]
I've pasted it, see it above above.

**Comment by playgithub** [comment]
With a proxy, successfully updated from 1.46.0 to 1.46.1
vscodium 1.46.0 x64 on Windows 10 pro x64

**Comment by GitMensch** [comment]
So do the people that get a 404 need to configure a proxy? If yes how?
Note: all extensions can be installed and updated via VSCodium fine, the only thing that never worked so far was the integrated update...

**Comment by playgithub** [comment]
shadowsocks client will set the proxy in system level automatically, vscodium use that automatically.

**Comment by Heptazhou** [comment]
I believe the problem is still with `*-system` cases.

@playgithub Update does work in a `user setup` but not in a `system setup`.
> It shows downloading as Menu/Help/Dowloading Update...
> It's very slow, it'll take hours to download.
> Tested for about 5 minutes, not error message.
> Also checked the log, no error.
> 
> ```
> Version: 1.46.0 (user setup)
> Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
> Date: 2020-06-12T10:32:02.515Z
> Electron: 7.3.1
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.18363
> ```

**Comment by Heptazhou** [comment]
@stripedpajamas I wonder if you have time to take a look at https://github.com/VSCodium/update-api/pull/5, see whether it meets https://github.com/VSCodium/vscodium/issues/411#issuecomment-641641163.

**Comment by boistordu** [comment]
So I've searched for hours now if it was my pihole or nextdns filter but it seems not. I still have 404 error.
X64 system windows 10 
general setup not user setup.
Did you succeed to make some changes about the update process or not at all?

**Comment by GitMensch** [comment]
@boistordu The current state is "works with user setup, doesn't with system setup".
That's the reason this issue is kept open. But I do suggest to rename it to make that clear - @playgithub can you please do this?

**Comment by playgithub** [comment]
of cause, edited

**Comment by stripedpajamas** [comment]
Thanks to @Heptazhou for the PR; https://vscodium.now.sh/api/update/win32-x64/stable/asdf now returns an update blob. Can the people who have Windows x64 system setup see if the auto update is working?

**Comment by GitMensch** [comment]
Update worked like a charm (the only issue is that the temporary installer has no code-certificate at all, but that looks like already been handled by #174). I think this can be closed now.
Note: I _guess_ the new issue tracked at #447 just come in "naturally", not by the update procedure.
