### ISSUE TITLE
Fails to open on mac after brew install

### ISSUE THREAD

**Issue by roadie-james** [VSCodium/vscodium#412]
**Describe the bug**
Installed on Mac using "brew cask install vscodium"

App fails to open.  See attached screenshot.
![image](https://user-images.githubusercontent.com/42683258/83987980-e3392c80-a90f-11ea-8982-739167147dcb.png)

**Comment by ivarlovlie** [comment]
As stated [here](https://github.com/VSCodium/vscodium#install-with-brew-mac) you need to right click the app in Finder > Applications and click on open.

**Comment by rickwierenga** [comment]
See [this](https://support.apple.com/en-gb/guide/mac-help/mh40616/mac) for more information.

**Comment by roadie-james** [comment]
Thank you both.  Has anyone looked into removing this requirement?  I would lend more credibility to the alternate build of VS Code.  I'm personally super excited to see someone has gone through the effort to create this.  Thank you!

**Comment by rickwierenga** [comment]
I'm not a developer on this project but I do believe this is an OS level safety precaution. If this is indeed the case, the developers can do nothing about it. You may be able to [do some stuff with GateKeeper](https://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/) on your machine, but I would recommend against it and verify on a per-application basis.

**Comment by stripedpajamas** [comment]
(Thank you @ivarlovlie and @rickwierenga for directing to the answer here.)

Hi @roadie-james 👋 actually we should be able to remove this requirement if #324 is completed. MS recently notarized VSCode, so it shouldn't be _too_ hard to do the same; I haven't had the time to do so yet. PRs/recommendations/help appreciated!

On another note, we do get a fair amount of issues created around exactly what you experienced. I suspect we need better documentation or more visible documentation around this until the notarization work is complete. If you have any suggestions as to what we could do to make it more clear what needs to happen after the first install on a Mac let us know!

I'll close this issue for now. Further comments regarding the popup from Apple and/or notarization can go into #324.
