### ISSUE TITLE
May update breaks extension search, doesn't return results for most extensions

### ISSUE THREAD

**Issue by nowak-boltzman** [VSCodium/vscodium#415]
mac osx catalina 

Like the title says, after updating I can no longer search for extensions, I get a very limited amount of results back. I was looking for the Haskell GHCi plugin and it did not return any Haskell extensions. Downgrading by reinstalling from Homebrew fixed the issue. I also tried searching for some extensions I already had installed, i.e Julia and Scheme, and those searches did not return any results either.

**Comment by GitMensch** [comment]
That's a feature, not a bug, see https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace what to do about it (ask the extension authors to publish on a non-restricted place, at least additional to the ms-one; or, if with the likeliness of a possible license breach setup vscodum to use a restricted one instead).

**Comment by stripedpajamas** [comment]
Yep -- this is now expected; VSCodium has migrated off of Microsoft's closed-source extension marketplace. Extensions are vsix files; the extension marketplace is simply an index of those vsix files. So any extension you _want_, you can install. See the link that @GitMensch posted for more information on Open VSX.

**Comment by nowak-boltzman** [comment]
I see, that makes sense. I just wasn't paying attention to the changes. Thanks for the doc links, and the work towards making it truly opens source.
