### ISSUE TITLE
AppImage.zsync file is missing

### ISSUE THREAD

**Issue by linsui** [VSCodium/vscodium#417]
**Describe the bug**
AppImage.zsync file is missing which is needed for update.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**Comment by srevinsaju** [comment]
Please provide a *.AppImage.zsync file needed to update the appimage in the releases. Looking at https://github.com/VSCodium/vscodium/blob/master/src/resources/linux/appimage/pkg2appimage#L470, it looks like its created, but only not uploaded as release assets
