### ISSUE TITLE
Forgetting to set npm_config_arch on arm64

### ISSUE THREAD

**Issue by JL2210** [VSCodium/vscodium#42]
I might have an idea to why arm64 doesn't build properly. When you build on arm64, try setting `npm_config_arch` to `arm64`.

**Comment by JL2210** [comment]
The `Failed to load shared library ... : No such file or directory` errors suggest that we are using binaries for different platforms, rather than ARM64 ones. See #40.

**Comment by stripedpajamas** [comment]
@JL2210 can you keep arm comments/ideas/suggestions in #6 ?

**Comment by JL2210** [comment]
Not really. This is more of a solution for #40.

**Comment by stripedpajamas** [comment]
#40 was closed yesterday to keep arm comments/ideas/suggestions in #6 (see my comment in that issue).
