### ISSUE TITLE
appimage desktop integration

### ISSUE THREAD

**Issue by PietroMB** [VSCodium/vscodium#429]
After first launch of appimage it  does not generate the shortcut to be launched in gnome or for open a file by right-click, can this feature be implemented?

Someone know a workaround for the moment to show the appimage in the gnome launcher?

I use Ubuntu 20.04 but the bug is the same also in my CentOS VM
Thanks

**Comment by linsui** [comment]
Try appimagelauncher?

**Comment by stripedpajamas** [comment]
As far as I know, menu integration isn't a feature of the AppImage itself, but can happen by running something else like AppImageLauncher (https://docs.appimage.org/user-guide/run-appimages.html#integrating-appimages-into-the-desktop). If I'm wrong and there's something about our AppImage generation that needs to change let me know.
