### ISSUE TITLE
A lot of popular extensions are not present in the extension store

### ISSUE THREAD

**Issue by methylprednisolone** [VSCodium/vscodium#430]
On macOS Catalina (10.15.4), VScodium downloaded via homebrew, when I try to go to the extension store and search for popular extensions that have always been there previously, there are not there anymore.

For example, a search for my favorite Moonlight colorscheme returns [nothing](https://gofile.io/d/shMD8S). Or a search for python returns some [obscure extensions](https://gofile.io/d/q7TwBP) with ~100 downloads (no official ones from MS).

Anyone else have this issue or know how to fix it?

**Comment by stripedpajamas** [comment]
See #418 for some discussion on this. It is intended behavior as of 1.46.0.

**Comment by stripedpajamas** [comment]
As well as https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace

**Comment by methylprednisolone** [comment]
> As well as https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace

Ok, thanks. Could I get access to MS extension store by downgrading to a previous version of VSCodium?

**Comment by stripedpajamas** [comment]
Yes, downgrading to previous version would do it. Also, you can edit the product.json file at `/Applications/VSCodium.app/Contents/Resources/app/product.json` and change the extension url as described in the docs link:

```
"extensionsGallery": {
    "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
    "itemUrl": "https://marketplace.visualstudio.com/items"
}
```

**Comment by methylprednisolone** [comment]
> Yes, downgrading to previous version would do it. Also, you can edit the product.json file at `/Applications/VSCodium.app/Contents/Resources/app/product.json` and change the extension url as described in the docs link:
> 
> ```
> "extensionsGallery": {
>     "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
>     "itemUrl": "https://marketplace.visualstudio.com/items"
> }
> ```

I tried it, but it results in the [following](https://gofile.io/d/2OXxwD) error. Are you sure this is valid for packages installed via homebrew? Anyway, do you happen know by any chance how to install a particular previous versions of the VSCodium cask?

**Comment by Crazor** [comment]
There should probably be a preference to change this easily. It appears changing the product.json in the app bundle does not survive updates, or does it?

**Comment by dalisoft** [comment]
@stripedpajamas Thanks for fix, it worked, but it's possible to modify it within user config?

**Comment by MPLew-is** [comment]
For anyone else looking for a quick fix for this on macOS, I've pushed [a fork of the VSCodium cask formula](https://github.com/MPLew-is/homebrew-vscodium) that resets the Extensions Gallery settings automatically during installation. All you have to do is run the following command to have this work out of the box:

`brew cask uninstall vscodium && brew cask install mplew-is/vscodium/vscodium`
