### ISSUE TITLE
Can't install Themes and Extesnions + Settings Sync missing

### ISSUE THREAD

**Issue by zettlrobert** [VSCodium/vscodium#433]
**Describe the bug**
I cant install extensions anymore.
So i decided to clean my extensions, purged codium, removed .config/VSCodium, removed ~/.vscode-oss
and installed it again (repo on ubuntu)

cant install any extensions anymore (Tested only Theme so far, thats where i am starting)

Unable to load file:///home/zettlrobert/.vscode-oss/extensions/equinusocio.vsc-community-material-theme-1.4.1/themes/Community-Material-Theme-Ocean-High-Contrast.json: Problems parsing JSON theme file: Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, End of file expected

and i can't find Settings Sync Extension anymore...
i have used vscodium for onver a year and never run into any problem no clue whats happening
![Screenshot from 2020-06-21 00-49-59](https://user-images.githubusercontent.com/19976985/85213016-2c01d400-b359-11ea-8828-1106edf42fb8.png)
 

The JSON is valid

**Please confirm that this problem is VSCodium-specific**
- [ x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS, Ubuntu 16.04, etc]
 - Architecture [e.g. x64, ia32, arm64]
 - Version [e.g. 1.33.0]

**Additional context**

**Comment by zettlrobert** [comment]
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-19T10:53:55.306Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-7634-generic

**Comment by zettlrobert** [comment]
VSX Problems, sync settings not availalbe and additionale vscode insider build has amicrosoft based sync settings now. might create a PR to autoimport it.

**Comment by adamsiwiec** [comment]
@zettlrobert Can you describe how you solved this problem? I am having the same issues with missing extensions in the marketplace.

**Comment by zapateo** [comment]
@adamsiwiec, @bushblade, maybe [this](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace) can help you.

**Comment by bushblade** [comment]
@zapateo That's great, thanks!

**Comment by zettlrobert** [comment]
> @zettlrobert Can you describe how you solved this problem? I am having the same issues with missing extensions in the marketplace.

I have not, i switched back to vim. The Debian/Ubuntu repo a user setup stops working every few weeks. I will try to find a fix when i have time, if i come to it i will let you know.

For now I suggest asking the creator to port his extension to the vscodium marketplace.
