### ISSUE TITLE
Better icons request for Windows 10.

### ISSUE THREAD

**Issue by younyokel** [VSCodium/vscodium#437]
**Describe the problem:**
Files icon that opens with VSCodium by default looks really unremarkable.

**Please confirm that this problem is VSCodium-specific:**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Screenshots:**
[![untitled.png](https://i.postimg.cc/XNDH8f4Y/untitled.png)](https://postimg.cc/8sMmkr72)

**To Reproduce:**

1. Right-click on any file in your PC.
2. Press "Open with".
3. In "How do you want to open this file?" window choose VSCodium and turn the "Always use this app to open ... files" checkbox.
4. In Explorer set the view size to minimum.

**Desktop (please complete the following information):**
- OS: Windows 10
- Architecture: x64
- Version: 1.46.1

**Comment by stripedpajamas** [comment]
Icons were just redone in #413 which will be present in next MS release. We will most likely not change icons for a while afterwards, but if you don't like the new Windows icons after next release feel free to open PR with suggested changes.
