### ISSUE TITLE
Menu bar items flash on Linux Mint 19.3

### ISSUE THREAD

**Issue by georgedavid004** [VSCodium/vscodium#438]
**Describe the bug**
When clicked on any menu item, it flashes.

**Please confirm that this problem is VSCodium-specific**
- [* ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ *] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Click on any menu item.It flashes white before showing submenu.

**Expected behavior**
flashes white before showing submenu.

**Screenshots**
![1](https://user-images.githubusercontent.com/43302127/86312719-f3a7a300-bc40-11ea-91e6-c1800210a646.png)
![4](https://user-images.githubusercontent.com/43302127/86312782-16d25280-bc41-11ea-8407-a22bee0ae022.png)
![3](https://user-images.githubusercontent.com/43302127/86312763-0d48ea80-bc41-11ea-9929-efee8d98ce6f.png)
![2](https://user-images.githubusercontent.com/43302127/86312755-091ccd00-bc41-11ea-95f7-82c6e0bca9b9.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3

 - Architecture amd64
 - Version 1.46.1

**Additional context**

**Comment by pkoch** [comment]
I'm seeing the same thing.

```
pkoch@fadista $ uname -a
Linux fadista 5.4.0-39-generic #43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

pkoch@fadista $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

pkoch@fadista $ codium --version
1.46.1
cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
x64
```

**Comment by nihillum** [comment]
Is there anyone that looked into this? I'm having this problem too...

![screen](https://user-images.githubusercontent.com/55314691/89296388-8da8a400-d662-11ea-9ece-144065031f3d.gif)

* **OS**: Ubuntu 20.04
* **Architecture**: x86_64
* **Version**: 1.47.3

**Comment by clementblaudeau** [comment]
Same issue on 
* **OS:** GNU/Linux, Fedora 32
* **Architecture:** x86_64
* **Version:** 1.47.3

**Comment by Luukvdm** [comment]
Same thing.

- **OS:** Arch Linux
- **Architecture:** x86_64
- **DE:** GNOME 3.36.5
- **Version:** 1.48.2

**Comment by Luukvdm** [comment]
This seems to be fixed in the latest version.

**Comment by nihillum** [comment]
I don't have this problem anymore after the latest release. I think this issue can be closed.
