### ISSUE TITLE
automatic telemetry removal

### ISSUE THREAD

**Issue by sam0x17** [VSCodium/vscodium#44]
> Even though we do not pass the telemetry build flags (and go out of our way to cripple the baked-in telemetry), Microsoft will still track usage by default. After installing VSCodium, you must manually disable telemetry in your settings file to stop it from sending tracking data to Microsoft.

Couldn't we just add a post-install script on every platform that automatically fixes the settings file? imo the whole purpose of this repo is telemetry is disabled. Even better, couldn't we just remove the code responsible for _all_ aspects of telemetry? (I am sure there is some compelling reason for us not being able to do the latter, though)

**Comment by stripedpajamas** [comment]
Good idea @sam0x17. I'm not inclined to update anyone's settings.json file, as that is outside the scope of the project, but your comment made me realize that it would be very easy to update the defaults that the settings.json file is built around pre-build. I found the two main telemetry settings here:

- crash reporter: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/crashReporter/electron-browser/crashReporterService.ts#L38
- the main telemetry service: https://github.com/Microsoft/vscode/blob/master/src/vs/platform/telemetry/common/telemetryService.ts#L168

It should be as easy as setting the defaults to false in both of those cases. Maybe we could get some discussion around whether or not to also disable by default auto extension update checks and natural language processing on search terms.

(p.s. the telemetry code is so spider-webbed throughout the project, it would not be feasible to remove it)

**Comment by sam0x17** [comment]
I definitely like the idea of defaulting to false

**Comment by stripedpajamas** [comment]
@sam0x17 any thoughts on whether or not we should also disable by default auto extension update checks and natural language processing on search terms? For now I think @joelwass is focusing on just disabling basic telemetry and crash reporting telemetry in #46.

**Comment by sam0x17** [comment]
@stripedpajamas I think just the basic telemetry and crash reporting telemetry makes sense
