### ISSUE TITLE
Why open-vsx.org?

### ISSUE THREAD

**Issue by playgithub** [VSCodium/vscodium#442]

**Comment by playgithub** [comment]
It's not convenient so far, and I switched to the ms' extentsion gallery by editing `path/to/vscodium/root/resources/app/product.json`, but after installing a new version of vscodium,
`product.json` is resetted to use open-vsx's gallery
"extensionsGallery": {
		"serviceUrl": "https://open-vsx.org/vscode/gallery",
		"itemUrl": "https://open-vsx.org/vscode/item"
}
```

Because open-vs.org is not convenient, so what is the reason to use it?

**Comment by pfeerick** [comment]
Because the VSCodium devs would prefer not be be sued by Micro$haft

https://github.com/VSCodium/vscodium#extensions-and-the-marketplace

**Comment by playgithub** [comment]
OK, M$'s code editor and IDE are really better， I mean convenient.
But M$ would not do it without any benifit, I mean telemetry is the tradeoff.
Really hard to find a completely free IDE or code editor that easy to use.
