### ISSUE TITLE
HexEditor not available

### ISSUE THREAD

**Issue by andradei** [VSCodium/vscodium#446]
**Describe the bug**
The new HexEditor, available since 1.46 on VSCode, doesn't seem to be available on VSCodium.
Is it because it is a microsoft extension?

https://github.com/microsoft/vscode-hexeditor

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Try to open HexEditor as documented on: https://github.com/microsoft/vscode-hexeditor#how-to-use

**Expected behavior**
To have this feature, or extension, available

**Screenshots**
No screenshots, unfortunately.

**Desktop (please complete the following information):**
 - OS: Pop!_OS (Ubuntu)
 - Architecture x64
 - Version 20.04 LTS

**Comment by Scannow** [comment]
Same here.

**Desktop**:
- Windows x64
- Architecture x64
- 1903
- VSCodium 1.47.0

**Comment by WSSDude** [comment]
It seems to be incompatible, at least when you try to use it from their git repo... It gets registered, but ultimately is not working.

Also, you need to install it as an extension from marketplace, it is not built-in (sounded like you expected it to be). Another thing is that it is not on VSCodium's one, as it uses https://open-vsx.org/ as it's repository instead of Microsoft one.

**Comment by GammaGames** [comment]
Duplicate of #418

**Comment by andradei** [comment]
@WSSDude Yeah, the Release Notes for 1.47.0 didn't make it clear it was an Extension that needed to be installed from the marketplace. Still... I hope the marketplace issue gets a good solution quick. I understand that for now it involves manually changing a file to point to the Microsoft marketplace. Kind of unfortunate but I understand the current limitations.

**Comment by andradei** [comment]
@GammaGames What is this? StackOverflow? :smile:
I'd say this issue is related, but in no way it is a duplicate. It will probably be solved when #418 is closed though.

**Comment by GammaGames** [comment]
@andradei Read 418 again. It started as a bug with open-vsx, but has transformed into a discussion about using an alternative marketplace that is missing most extensions and how it effects users.

**Comment by andradei** [comment]
@GammaGames I spent some time reading the issue yesterday. But failed to find the actual fix in the comments because the conversation is all over the place... One guy suggested reverting codium to use Microsoft's marketplace, another made a fork that seems to have done that, other people suggested manually changing a config file to point to Microsoft's marketplace, etc.

Could you point me to the comment that explains the solution? I that case I'll gladly close this issue.

**Comment by andradei** [comment]
Oh, I think that's [the solution](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace) you are referring to which resolves #418.

That actually solves this issue too. Thanks!
