### ISSUE TITLE
Cannot find or install many (if not the majority) of extensions available on the marketplace

### ISSUE THREAD

**Issue by devlexanderxyz** [VSCodium/vscodium#448]
**Describe the bug**
I cannot find extensions to install. An example of an extension I cannot install/find is https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple, even if I use the `ext` command.

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install vscodium
2. Attempt to install any extension such as Pawn Tools, or Shades of Purple.

**Expected behavior**
I expected to find the extension and install it.

**Screenshots**
Did Not Answer.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Architecture: x64
 - Version: 1.46.1

**Additional context**
Did Not Answer.

**Comment by WSSDude** [comment]
VSCodium uses https://open-vsx.org/ as it's repositary for packages, not microsoft ones.

**Comment by GammaGames** [comment]
Duplicate of #418

**Comment by riteshjn** [comment]
I also have similar issue!

**Comment by Rowisi** [comment]
More extensions are getting added everytime and almost all extensions I needed were added. You can check [here](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace) the tips to request for adding missing extensions.

**Comment by devlexanderxyz** [comment]
Thank you!

**Comment by tubbadu** [comment]
Otherwise until your request is approved you may head to marketplace.visualstudio.com, search for your extension, download it as .vsix, and then go in vscodium, extensions tab, click on the three dots and select "install from VSIX"
This way the extension is not automatically update, but if you really need it this is a way to get it fast
