### ISSUE TITLE
GPG sign for Linux packages

### ISSUE THREAD

**Issue by paulcarroty** [VSCodium/vscodium#45]
The latest (minimum) Linux packages aren't signed - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/issues/1

I can sign them with my repository key, but then verifications by checksums will be broken. So, I'd suggest sign them after build like MS [did](https://code.visualstudio.com/docs/setup/linux).

**Comment by stripedpajamas** [comment]
Is the recommendation that we sign the packages with a vscodium gpg key and then you include the same key in your repo?

**Comment by paulcarroty** [comment]
Yeah. Repository metadata also should be sign with the same key.

**Comment by paulcarroty** [comment]
@stripedpajamas you should generate the default key pair. Most tricky moment here - how to sign Gitlab repos with your key.

Alternative way - sign all packages with my repo keys. It breaks checksums verifications but packages can be compares via something like [pkgdiff](https://github.com/lvc/pkgdiff).

**Comment by paulcarroty** [comment]
Fixed by https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/commit/f53761c927b3e38f52a0b625748c18ebc89d223e
