### ISSUE TITLE
VSCodium installed an extension it was NOT instructed to

### ISSUE THREAD

**Issue by colemickens** [VSCodium/vscodium#450]
**Describe the bug**
I originally filed this as  https://github.com/microsoft/vscode/issues/102540 but it does NOT occur in VS Code and I was wrong to have assumed and filed it there.

To restate it:
The wrong extension was installed when I specifically used an `ext install ...` command to install a specific extension.

Here's a video of the entire exchange: https://youtu.be/-ipK_A9Q4No

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

I installed VS Code. This does not happen. If I `ext install ...` an extension that doesn't exist, the UI immediately switches to "search for... " extension, whereas Codium just acts like it can always install any extension name.

Thoughts:
* maybe OpenVSX return a false specific result for that and Codium blindly installs the result without checking the name?

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
See this video: https://youtu.be/-ipK_A9Q4No
Or:

1. Ctrl+p
2. Paste `ext install asciidoctor.asciidoctor-vscode`, <enter>
3. It installs Red Hat Java support instead....

**Expected behavior**
The wrong extension to not be installed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS, Ubuntu 16.04, etc] Linux
 - Architecture [e.g. x64, ia32, arm64] x64
 - Version [e.g. 1.33.0] **VSCodium 1.46.1**

**Additional context**

**Comment by spoenemann** [comment]
Probably the same root problem as in #434. It should work now, please verify.

**Comment by colemickens** [comment]
It no longer repros. Thanks!
