### ISSUE TITLE
Running a program using F5 or CTRL + F5 does nothing

### ISSUE THREAD

**Issue by shadyabh** [VSCodium/vscodium#451]
**Describe the bug**
I am working with version 1.47.0. When I open a folder to run my file with launch.json configured to current file (default), I press F5 or CTRL + F5 no terminal is opened, and if I open one manually it doesn't affect it and my code is not executed.

**Please confirm that this problem is VSCodium-specific**
- [v] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [v ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to some python file
2. Click on F5 or CTRL+F5
3. Nothing happens other than debugger toolbar that is shown for couple of seconds.

**Expected behavior**
It is expected to run some commands in the integrated terminal that run the debugger and execute the code.

**Desktop (please complete the following information):**
 - OS: [Linux Parrot OS]
 - Architecture [x64]
 - Version [5.6.0]

**Comment by iinuwa** [comment]
I also have a similar issue with debugging a .NET Core project with the C# extension. All the doumentation shows that the dfeault tasks.json and launch.json files generated for .NET Core projects should "just work," but when I try to launch or attach a debugger, all I see is that the debugger toolbar appears at the top, and the debug console stays open, but the program never executes.

I wonder if it's some sort of DRM issue, given the banner in the debug console output:

> \-------------------------------------------------------------------
> You may only use the Microsoft .NET Core Debugger (vsdbg) with
> Visual Studio Code, Visual Studio or Visual Studio for Mac software
> to help you develop and test your applications.
> \------------------------------------------------------------------

**Comment by iinuwa** [comment]
Hmm. My issue specifically is documented in [DOCS.md](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#proprietary-debugging-tools). (Didn't see it called out on the README, so I didn't notice it at first.)

FWIW, I have been able to debug Python files just in VSCodium in the past (haven't tried on a recent release though).

**Comment by shadyabh** [comment]
@stripedpajamas Yes it is the same issue.
