### ISSUE TITLE
Add package to official Debian repository

### ISSUE THREAD

**Issue by pktiuk** [VSCodium/vscodium#456]
It would be nice and pretty convenient for users if VsCodium would be added as a package to the official Debian repository, it would make vscodium accessible for users of debian- and ubuntu-based systems without the need of adding PPA.

Instructions for adding packages can be found [here](https://www.debian.org/doc/manuals/developers-reference/pkgs.html#newpackage) and [in this FAQ](https://wiki.debian.org/DebianMentorsFaq)

I have found out that somebody has already proposed adding `codium` to Debian repository, it is on the list of [Prospective packages](https://www.debian.org/devel/wnpp/index.en.html) ([its thread](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=959941)).
Currently, this package is just waiting for somebody, who would like to be its maintainer.
Maybe it could be somehow integrated with this project's PPA (mentioned here https://github.com/VSCodium/vscodium/issues/34)

**Comment by pktiuk** [comment]
This package doesn't pass `lintian` check:


E: brave-browser: [appstream-metadata-invalid](https://lintian.debian.org/tags/appstream-metadata-invalid.html) brave-browser.appdata.xml
E: brave-browser: [dir-or-file-in-opt](https://lintian.debian.org/tags/dir-or-file-in-opt.html) opt/brave.com/
E: brave-browser: [dir-or-file-in-opt](https://lintian.debian.org/tags/dir-or-file-in-opt.html) opt/brave.com/brave/
E: brave-browser: [dir-or-file-in-opt](https://lintian.debian.org/tags/dir-or-file-in-opt.html) opt/brave.com/brave/MEIPreload/
E: brave-browser: [dir-or-file-in-opt](https://lintian.debian.org/tags/dir-or-file-in-opt.html) ... use --no-tag-display-limit to see all (or pipe to a file/program)
E: brave-browser: [embedded-library](https://lintian.debian.org/tags/embedded-library.html) opt/brave.com/brave/brave: freetype
E: brave-browser: [embedded-library](https://lintian.debian.org/tags/embedded-library.html) opt/brave.com/brave/brave: lcms2
E: brave-browser: [embedded-library](https://lintian.debian.org/tags/embedded-library.html) opt/brave.com/brave/brave: libjpeg
E: brave-browser: [embedded-library](https://lintian.debian.org/tags/embedded-library.html) ... use --no-tag-display-limit to see all (or pipe to a file/program)
E: brave-browser: [no-copyright-file](https://lintian.debian.org/tags/no-copyright-file.html)
E: brave-browser: [prerm-calls-updatemenus](https://lintian.debian.org/tags/prerm-calls-updatemenus.html)
W: brave-browser: appstream-metadata-in-legacy-location usr/share/appdata/brave-browser.appdata.xml
W: brave-browser: description-synopsis-starts-with-article
W: brave-browser: extended-description-line-too-long
W: brave-browser: package-contains-timestamped-gzip usr/share/doc/brave-browser/changelog.gz 2020-07-15T09:21:44
W: brave-browser: pkg-not-in-package-test brave-browser-stable usr/share/menu/brave-browser.menu
W: brave-browser: setuid-binary opt/brave.com/brave/chrome-sandbox 4755 root/root


These errors should be fixed before publishing package.

**Comment by EchedeyLR** [comment]
Maybe working to be compilable to more supported archs by Electron as showed in https://github.com/VSCodium/vscodium/issues/465, should be taken into account.

**Comment by pktiuk** [comment]
Currently `.deb` package for vscodium doesn't pass `lintian`'s check:
```
E: codium: arch-dependent-file-in-usr-share usr/share/codium/chrome-sandbox
E: codium: arch-dependent-file-in-usr-share usr/share/codium/codium
E: codium: arch-dependent-file-in-usr-share usr/share/codium/libEGL.so
E: codium: arch-dependent-file-in-usr-share ... use --no-tag-display-limit to see all (or pipe to a file/program)
E: codium: debian-changelog-file-missing
E: codium: embedded-library usr/share/codium/codium: freetype
E: codium: embedded-library usr/share/codium/codium: libjpeg
E: codium: embedded-library usr/share/codium/codium: libjsoncpp
E: codium: embedded-library ... use --no-tag-display-limit to see all (or pipe to a file/program)
E: codium: executable-desktop-file usr/share/applications/codium.desktop 0775
E: codium: missing-dep-for-interpreter node => nodejs (usr/share/codium/resources/app/extensions/ms-vscode.node-debug2/node_modules/mkdirp/bin/cmd.js) #!node
E: codium: missing-dep-for-interpreter node => nodejs (usr/share/codium/resources/app/extensions/node_modules/rimraf/bin.js) #!node
E: codium: missing-dependency-on-libc needed by usr/share/codium/chrome-sandbox and 16 others
E: codium: no-copyright-file
E: codium: shlib-with-executable-bit usr/share/codium/libEGL.so 0755
E: codium: shlib-with-executable-bit usr/share/codium/libGLESv2.so 0755
E: codium: shlib-with-executable-bit usr/share/codium/libffmpeg.so 0755
E: codium: shlib-with-executable-bit ... use --no-tag-display-limit to see all (or pipe to a file/program)
E: codium: statically-linked-binary usr/share/codium/resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg
E: codium: unknown-control-interpreter control/postinst #!/usr/bin/env
E: codium: unknown-control-interpreter control/prerm #!/usr/bin/env
E: codium: unstripped-binary-or-object usr/share/codium/chrome-sandbox
E: codium: unstripped-binary-or-object usr/share/codium/libffmpeg.so
E: codium: unstripped-binary-or-object usr/share/codium/resources/app/node_modules.asar.unpacked/keytar/build/Release/keytar.node
E: codium: unstripped-binary-or-object ... use --no-tag-display-limit to see all (or pipe to a file/program)
W: codium: appstream-metadata-in-legacy-location usr/share/appdata/codium.appdata.xml
W: codium: executable-not-elf-or-script usr/share/applications/codium.desktop
W: codium: extended-description-line-too-long
W: codium: maintainer-script-ignores-errors postrm
W: codium: non-standard-dir-perm usr/ 0775 != 0755
W: codium: non-standard-dir-perm usr/share/ 0775 != 0755
W: codium: non-standard-dir-perm usr/share/appdata/ 0775 != 0755
W: codium: non-standard-dir-perm ... use --no-tag-display-limit to see all (or pipe to a file/program)
W: codium: non-standard-executable-perm usr/share/applications/codium.desktop 0775 != 0755
W: codium: non-standard-executable-perm usr/share/codium/bin/codium 0775 != 0755
W: codium: non-standard-executable-perm usr/share/codium/resources/app/node_modules.asar.unpacked/keytar/build/Release/keytar.node 0775 != 0755
W: codium: non-standard-executable-perm ... use --no-tag-display-limit to see all (or pipe to a file/program)
W: codium: non-standard-file-perm usr/share/appdata/codium.appdata.xml 0664 != 0644
W: codium: non-standard-file-perm usr/share/applications/codium-url-handler.desktop 0664 != 0644
W: codium: non-standard-file-perm usr/share/bash-completion/completions/codium 0664 != 0644
W: codium: non-standard-file-perm ... use --no-tag-display-limit to see all (or pipe to a file/program)
W: codium: setuid-binary usr/share/codium/chrome-sandbox 4755 root/root
```
This should be firstly taken into account (in terms of improving packaging)

**Comment by GitMensch** [comment]
@pktiuk Can you have a look at improving the deb?

**Comment by pktiuk** [comment]
@GitMensch   
Unluckily no, because I don't know anything about packaging Typescript apps.  
The only think I can do in this matter is running `lintian` to check deb package.

I think it would be good to find maintainer experience with packaging this type of apps.   
I think there is a need for such a package (check [request for adding vscode to debian repos](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898259)) and you could get some help form team creating Pop_os, because they have also packaged vscode for their distribution (https://github.com/pop-os/vscode it is available via [their repositories](https://apt.pop-os.org/))

**Comment by soredake** [comment]
Before vscode we need to get electron https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=842420

**Comment by DuckDuckWhale** [comment]
keep alive

**Comment by DuckDuckWhale** [comment]
keep alive

**Comment by GitMensch** [comment]
I'm not sure  if there's anything we can reasonably do on our side - this is a Debian package issue (found in the Debian issue tracker) which is officially "blocked" by several issues (most important: electron package).

Until Debian has that the vscodium website does provide notes how to install it with adding an external repository.

While it would be nice to have vscodium in Debian directly, I tend to close this as unplanned-not-our-issue. Is there a reason to not do this?

**Comment by daiyam** [comment]
I don't think we can expect that Debian will integrate VSCodium any time soon since they like extra stable softwares (with 5 years support with LTS).

**Comment by GitMensch** [comment]
Agreed, so please go on with the Debian issue tracker (items linked above) and in the meanwhile use the option with the private repository added.
