### ISSUE TITLE
Some extensions do not appear on the marketplace

### ISSUE THREAD

**Issue by ZurMaD** [VSCodium/vscodium#461]
For example, I have install janisdd.vscode-edit-csv extension in VSCode. However, when I search on VSCodium extensions I can't find it.

Extension:

![image](https://user-images.githubusercontent.com/28235457/87989525-c9127280-caa7-11ea-9293-8b995cab3851.png)

In VSCode:

![image](https://user-images.githubusercontent.com/28235457/87989202-35d93d00-caa7-11ea-979f-cdefc1a55490.png)

VSCodium 

![image](https://user-images.githubusercontent.com/28235457/87989226-4093d200-caa7-11ea-8e16-eae2572982bc.png)

**Comment by husy8** [comment]
see #430

**Comment by stripedpajamas** [comment]
Yep -- expected behavior given VSCodium does not use Microsoft's extension marketplace.
