### ISSUE TITLE
Unable to debug with xdebug (MacOS)

### ISSUE THREAD

**Issue by alechko** [VSCodium/vscodium#464]
Hi there,

I'm using MacOS Catalina 10.15.5 and [ddev](https://www.ddev.com/) which is a Docker based tool and I'm unable to get xdebug going with VSCodium, while the same launch config file and the same dev tools works perfectly fine from vscode.

When trying to launch the debug configuration from the debug panel, it's trying to connect but fails every time with no errors, just stops connecting. I've tried multiple variations of the launch configuration but none connected.

After many failed attempts of configuring the docker containers etc., I've downloaded vscode and launched from the same folder with the same files and connected from the first time.

vscode: 1.47.2
code: 1.47.2

my launch.json:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "hostname": "127.0.0.1",
            "port": 9000,
            "pathMappings": {
                "/var/www/html": "${workspaceRoot}"
            }
        }
    ]
}
```

**Comment by iinuwa** [comment]
This may be related to #451.

**Comment by brunob** [comment]
same as #466

**Comment by TomaszGasior** [comment]
Please take a look on my comment here: https://github.com/VSCodium/vscodium/issues/466#issuecomment-687331078. Maybe it works on macOS too.
