### ISSUE TITLE
sudo apt update "Too Many Requests"

### ISSUE THREAD

**Issue by therealrobster** [VSCodium/vscodium#469]
**Describe the bug**
As per the title, I'm trying to install via the repository.  When I do the sudo apt update command after installing the repo I get `Too Many Requests` error

**Please confirm that the issue/resolution isn't already documented**
I've checked and can't find this issue in the tracker.

**To Reproduce**
Add the GPG key of the repository:
`wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | sudo apt-key add -`

Add the repository:
`echo 'deb https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs/ vscodium main' | sudo tee --append /etc/apt/sources.list.d/vscodium.list`

Update then install vscodium:
`sudo apt update && sudo apt install codium `

**Expected behavior**
It should install... It gives the error as described.

**Desktop (please complete the following information):**
 - OS: POP!_OS 20.04
 - Architecture x64

**Comment by cyberorg** [comment]
Same issue here: https://github.com/VSCodium/vscodium/issues/318

**Comment by CedMaire** [comment]
I have the same issue when running `sudo apt update`.

Output:
```
~ sudo apt update
[...]
Err:6 https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs vscodium InRelease
  429  Too Many Requests [IP: 172.65.251.78 443]
[...]
W: Failed to fetch https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs/dists/vscodium/InRelease  429  Too Many Requests [IP: 172.65.251.78 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by jim4067** [comment]
Same issue here. 
Feels really good to not be one opening issues

**Comment by arxo** [comment]
I have the same issue since at least yesterday.

**Comment by paulcarroty** [comment]
[Workaround](https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/issues/36#note_395793123)

**Comment by arxo** [comment]
thanks a lot :)

**Comment by stripedpajamas** [comment]
Closing; workaround is above ^ and not really anything we can do on the VSCodium side.
