### ISSUE TITLE
Too big icon on start menu

### ISSUE THREAD

**Issue by linsui** [VSCodium/vscodium#471]
**Describe the bug**
Too big icon on start menu.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**Screenshots**
![sshot-009](https://user-images.githubusercontent.com/36977733/90304210-cdfaf400-dea4-11ea-8d2b-021caa639412.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Architecture x64
 - Version 1.48.0

**Comment by Bufkin** [comment]
Same issue on Windows 10 Pro

**Comment by linsui** [comment]
https://github.com/VSCodium/vscodium/blob/master/src/resources/win32/code_150x150.png
https://github.com/VSCodium/vscodium/blob/master/src/resources/win32/code_70x70.png
These icons should be fixed.

**Comment by layday** [comment]
The new icon is oversized on Mac as well.

**Comment by estatra** [comment]
Thanks for the reports. [Here's the fix for Windows](https://github.com/VSCodium/vscodium/pull/474).

For the 70x70 one I couldn't do a perfect 66% padding because the image editor doesn't scale to floating points, so I got it to as close as possible at 65.719% padding.

---
@layday Could specify what icon(s) please? Dock? Tab? Other?

@linsui @stripedpajamas Can you guys help me locate the problematic icons for Mac? I use Linux only. I recommend we solve this before merging, so I can append the Mac fix to the PR.

**Comment by layday** [comment]
It appears to be the case that it is slightly oversized in the dock as well as in the Finder and the tab switcher in comparison to other icons.

<img width="418" alt="Screenshot 2020-08-16 at 00 15 49" src="https://user-images.githubusercontent.com/31134424/90321792-bdef1d00-df55-11ea-8147-d07942676725.png">

**Comment by estatra** [comment]
Thanks for the quick reply layday. Seems to be a padding issue also. I'll wait for linsui and stripedpajamas help.

**Comment by linsui** [comment]
I don't use mac. The icons looks perfectly on Windows. Thanks! @estatra

**Comment by estatra** [comment]
> I don't use mac. The icons looks perfectly on Windows. Thanks! @estatra

No problem!

I'll wait for stripedpajamas when he have the time to help and I'll fix the Mac ones. I'll do some padding for the Linux ones also to make it even across the board : )

**Comment by yusf** [comment]
VS Code is having the [same issue](https://github.com/microsoft/vscode/issues/101014) and have also had that in [past rebrandings](https://code.visualstudio.com/blogs/2017/10/24/theicon).

**Comment by estatra** [comment]
> VS Code is having the [same issue](https://github.com/microsoft/vscode/issues/101014) and have also had that in [past rebrandings](https://code.visualstudio.com/blogs/2017/10/24/theicon).

Oh thanks for that info @yusf. Good know, I was unaware of that. I blindly followed VS Code's hierarchy and icon sizes.

For VSCodium, one PR is up and done. The Windows one is fixed. Currently working on a second PR to fix the macOS one, and improve the Linux one a little bit.
