### ISSUE TITLE
Repo not working

### ISSUE THREAD

**Issue by starrynightspy** [VSCodium/vscodium#476]
Adding APT repo results in this.

`W: Failed to fetch https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs/dists/vscodium/InRelease  429  Too Many Requests [IP: [myipv6]] 

I should also add I'm on a residential connection, so I doubt I've been rate limited. 

I don't think Gitlab intended their service to be used like this. I'd suggest [Open Build Service](https://openbuildservice.org/) from OpenSUSE as an alternative. Should be about as easy.

`

**Comment by CasualRascal** [comment]
This was addressed on gitlab, the repository is getting spanked by gitlab because of an excessive amount of requests.
They moved the repo to https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/
You can change the baseurl in your vscodium.repo file to get updates

**Comment by stripedpajamas** [comment]
See #318 and #469
