### ISSUE TITLE
vscodium crashes/closes when opening a folder

### ISSUE THREAD

**Issue by nexxtnit** [VSCodium/vscodium#479]
**Describe the bug**
When I open a folder in vscodium, in my case the documents folder, the program crashes. When I open a second instance of vscodium it suddenly works. I really don't know why this happens. This all started with the update 1.48 I think. 

I started vscodium in verbose mode to check the errors:
```
[26995:0820/123455.952047:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
[26995:0820/123455.952255:ERROR:command_buffer_proxy_impl.cc(93)] ContextResult::kFatalFailure: AllocateAndMapSharedMemory failed
[26840:0820/123455.952712:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
```
unfortunately I have no idea what to do with them

**To Reproduce**
1. Go to File -> Open Folder
2. Click on any folder
3. Open folder

**Expected behavior**
vscodium closes while trying to open the folder

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Architecture: x64

**Comment by bkis** [comment]
Can confirm. I am running VSCodium as a snap packagage, the behavior is as described in this issue.  
Syslog says...

```
Aug 27 22:31:57 computername kernel: [28727.162843] codium[95182]: segfault at ffffd858f0c8cf38 ip 000055ea9a10797e sp 00007fff96734240 error 5 in codium[55ea9a03e000+53b2000]
Aug 27 22:31:57 computername kernel: [28727.162859] Code: 48 89 77 38 5d c3 cc cc cc cc cc cc 55 48 89 e5 41 57 41 56 41 55 41 54 53 48 83 ec 38 f2 0f 11 45 a8 49 89 fc e8 c2 b8 04 00 <48> 8b 08 48 89 c7 ff 91 88 00 00 00 48 8b 08 48 89 c7 ff 51 58 84
```

So... a segfault? Do you maybe use a snap, too?

**Comment by bkis** [comment]
Also - the same version of the original VSCode (also used as a snap package) does not produce this error.

**Comment by nexxtnit** [comment]
No I am not using a snap, I installed from AUR. I am somehow glad though I am not the only one with this issue. On the other hand I guess there is no real solution for this?

**Comment by bkis** [comment]
> No I am not using a snap
Well, that's good to know, so it's not about the snap package. But then I wonder why we seem to be the only ones looking for a solution here...

**Comment by Dajvid** [comment]
I have the same problem on version 1.48.2 installed with snap.

**Comment by bkis** [comment]
I don't know about you, @nexxtnit, but using the current version, ...

```
Version: 1.49.3
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-03T00:36:30.859Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-7642-generic snap
```
..., the problem seems to be fixed.

**Comment by nexxtnit** [comment]
Hey @bkis  I totally forgot to add it here but yes it seems for me as well that it got fixed :D 
thanks a lot for reminding me about it :)
