### ISSUE TITLE
Vote : Alternate blue version of the new logo?

### ISSUE THREAD

**Issue by cd4d** [VSCodium/vscodium#481]
As per #472 regarding the new logo, I think some criticisms come from the green color clashing with the blue themed UI of codium. A blue version would be more in line with the UI. 

I think the author of the logo is open about making a blue version, provided there is a demand for it from the users. 

**Would you want an alternate blue version of the new logo available to download?** 

_Vote on this post to make your voice heard._

👍 = Yes
👎 = No

Please try not to chime in on a replacement for the logo as it would be much more work for the author. A color change is simpler to do and that's just what this discussion is about.

Also, if there is a better way to conduct such poll, let me know.

EDIT: added vote instructions per post 2.

**Comment by ChiAlpha** [comment]
A smaller version of the logo would be nice as well as a blue one. If possible, a white (or chalky yellow) outline around the edges too.

**Comment by estatra** [comment]
[VSCodium Logo - Blue Version.zip](https://github.com/VSCodium/vscodium/files/5121067/VSCodium.Logo.-.Blue.Version.zip)

**Comment by cd4d** [comment]
Thank you!
