### ISSUE TITLE
Settings sync is not available

### ISSUE THREAD

**Issue by Shatur95** [VSCodium/vscodium#482]
**Describe the bug**
[VSCode 1.48](https://code.visualstudio.com/updates/v1_48) introduced built-in [Settings Sync](https://code.visualstudio.com/docs/editor/settings-sync) in stable version. [User guide](https://code.visualstudio.com/docs/editor/settings-sync) says that I need to enable it in the **Manage** gear menu at the bottom of the **Activity Bar** but there is not such option in this menu.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium. Official version have **Turn on settings sync** on my machine.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Architecture: x64
 - Version: 1.48.1

**Comment by sheiun** [comment]
@Shatur95 I thought it's available now and it just appear when I searched `Settings Sync` in extension tab, but I have same problem as you before today.

**Comment by cd4d** [comment]
@sheiun no this is an extension you're talking about. It's now possible to sync settings without any extension directly from vscode, but that feature is not available in codium.

**Comment by Shatur95** [comment]
Looks like this feature not available for OSS builds at all: https://github.com/microsoft/vscode/issues/105310#issuecomment-693262654

**Comment by stripedpajamas** [comment]
Closing per the that information @Shatur95 

They must be mixing it in during their private build

**Comment by Nick-Shadow** [comment]
Any good way to sync/ good extension for it (I saw that mentioned)? (even if it is the one Microsoft uses, I am okay syncing with a Microsoft account. I want to use the open source version, but I kind of need settings sync.

**Comment by daiyam** [comment]
There is the extension that I made: [Sync Settings](https://open-vsx.org/extension/zokugun/sync-settings) (also available on VS Marketplace).
