### ISSUE TITLE
"All extensions are up to date." but they are not

### ISSUE THREAD

**Issue by gerroon** [VSCodium/vscodium#483]
**Describe the bug**
I have not been able to find an update to any of the extensions I have installed here for quite a long time

**Please confirm that this problem is VSCodium-specific**
I do not use Vscode

**Please confirm that the issue/resolution isn't already documented**
The workaround mentioned  for some extensions but none of those steps worked for me.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Architecture x64
 - Version 1.48.1

**Additional context**
According to the MS Python extension page it is  `Version	2020.8.103604` and my installed version is `2020.5.86806 (10 June 2020)` as you see I am way behind and I get no update for it along with 10s of other extensions.  Even so, I have alot of non MS extensions.

I applied the `extensionsGallery` and that did not work either. This isssue has started a month or more ago but I did not think there was an update issue, now I feel like this is broken at least for me. 

```
	"extensionsGallery": {
	    "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
        "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
        "itemUrl": "https://marketplace.visualstudio.com/items"

    },


```

One thing is that I am behind proxy so I use these lines. This always worked since I started using Vscodium. I see no reason why this would cause it.

(forwarded privoxy)
```
 "http.proxy": "http://127.0.0.1:8118",
    "https.proxy": "http://127.0.0.1:8118",
```

I can actually search the market and install extensions, so not sure why updates do not work.

**Comment by Androphin** [comment]
Is there a way to switch marketplace from open-vsx to Microsoft?
Problem is: Some extensions have bugs and are in the open-vsx store with older buggy versions, whereas in Microsoft's are already updated.
That's blocking some productive dev workflows and is really annoying.

**Comment by gerroon** [comment]
I do not even get the updates when I change to the MS store (search here there are tips for it). I was able to get the Python extension updated or shown as an update when I search for it, then I see "update" next to it. However regularly it is not showing updates, unless you search for them one by one.

**Comment by debo** [comment]
I have the very same issue, but I'm on OSX and I'm on open-vsx and I verified that the extension is up to date on the latter as well. So yeah, VSCodium for some reason lags behind.

**Comment by stripedpajamas** [comment]
See #494 which has now been merged/deployed.

> Auto-update of extensions that were previously installed from Open VSX stops working in VSCodium after the change is deployed. You need to reinstall these extensions to update them once, afterwards everything is fine again. Extensions installed before switching to Open VSX or after this change can be auto-updated without problems.

**Comment by GitMensch** [comment]
> You need to reinstall these extensions to update them once, afterwards everything is fine again.

That's exactly what I've figured out some weeks ago. I think a low-level announcement mailing list (or if you really prefer: a closed announcement issue one can subscribe to and only the author can post to) would be really useful.
Useful would also be to replace the Visual Studio Code whatsnew page, partially copying the parts from the MS ones, removing the MS-only parts (like "hey use own nice new service and binary packages") and adding a VSCode specific part. It may be possible to add a file that contains the notes for the next VSCodium version and let the CI merge both the MS one and the VSCodium one to a new file and referencing this one?

Given that the one-time reinstall _is_ necessary (which I know sucks a bit, especially when you aren't aware of this) I suggest to close this issue.

**Comment by linsui** [comment]
A little off topic: The MS Python extension is outdated on open-vsx, and what's worse, not work on 1.51.0.

**Comment by GitMensch** [comment]
@linsui that's nothing vscodium can do about, please send open vsx notes to https://github.com/eclipse/openvsx

**Comment by stripedpajamas** [comment]
Closing this issue as per @GitMensch's comment. Interested in hijacking the MS changelog screen that appears after updating; will open a new issue to track that.
