### ISSUE TITLE
Latex Workshop Extension not working

### ISSUE THREAD

**Issue by jpaczia** [VSCodium/vscodium#486]
**Describe the bug**
The [LaTeX Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop) extension is currently not working in VS Codium. The extension symbol is not showing, other extensions are working as expected.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install the extension: Press Ctrl + P and enter `ext install James-Yu.latex-workshop`
2. Open a .tex file, an example file can be found [here](https://gist.github.com/Michael0x2a/e46e12a66b7dc604db5e)
3. Try to build the document, using the shortcut Ctrl + Alt + b
(to check if you have all latex packages this can also be done via the terminal, e.g. with `pdflatex [NAME].tex`)
4. See error "command 'latex-workshop.build' not found" in the right bottom corner

**Expected behavior**
The  latex document is compiled into an output format, e.g. a PDF file.

**Desktop (please complete the following information):**
 - OS: Ubuntu and Kubuntu 20.04
 - Architecture x86_64
 - Version 1.48.1

**Additional context**
[This](https://github.com/James-Yu/LaTeX-Workshop/issues/2160) issue might be relevant.

**Comment by GeQi** [comment]
I've being using the extension with VS Codium without issue. Seems there are related issues in the extension's repo (e.g. https://github.com/James-Yu/LaTeX-Workshop/issues/469).

**Comment by jpaczia** [comment]
Yes, there are related issues. 
However this seems to be VSCodium specific, since the extension is working with VS Code.
I was also able to use this extension with and older version of VSCodium, but with version 1.48.1 the extension does not work.
According to [this issue](https://github.com/James-Yu/LaTeX-Workshop/issues/2160) the extension does not work because of VSCodium.

Which versions of VSCodium and the extension are you using @GeQi ?

**Comment by GeQi** [comment]
@jpaczia I'm using the latest version indeed. However my extension was installed way before any changes was made to the marketplace, so likely that is the source of the issue.

**Comment by indierodo** [comment]
Hello!

Error message in developer tools.

```
abstractExtensionService.ts:411 Activating extension 'James-Yu.latex-workshop' failed: Cannot find module '/home/rodo/.vscode-oss/extensions/james-yu.latex-workshop-8.11.1/out/src/main.js'
Require stack:
- /usr/share/codium/resources/app/out/vs/loader.js
- /usr/share/codium/resources/app/out/bootstrap-amd.js
- /usr/share/codium/resources/app/out/bootstrap-fork.js.
```

The out folder does not exist in `~/.vscode-oss/extensions/james-yu.latex-workshop-8.11.1`

WORKAROUND
After installing the extension from marketplace, close codium. Open a terminal and run this:
```
cd ~/.vscode-oss/extensions
rm -r james-yu.latex-workshop-8.11.1
wget https://github.com/James-Yu/LaTeX-Workshop/archive/v8.11.1.tar.gz
tar -xvf v8.11.1.tar.gz
rm v8.11.1.tar.gz
mv LaTeX-Workshop-8.11.1 james-yu.latex-workshop-8.11.1
cd james-yu.latex-workshop-8.11.1
npm install && npm run compile
```

Don't forget to install latexmk package.

**Comment by stripedpajamas** [comment]
Per [this comment](https://github.com/James-Yu/LaTeX-Workshop/issues/2160#issuecomment-652137338) the issue is that the extension itself on OpenVSX is missing files / corrupt. Nothing we can do (thanks for the workaround @indierodo). Either publisher needs to update OpenVSX version of the extension, or OpenVSX themselves can possibly do it.

**Comment by jpaczia** [comment]
The issue has been reported and fixed [here](https://github.com/open-vsx/publish-extensions/issues/163).

**Comment by drepram** [comment]
Hi, I basically ran `LaTeX Workshop: Build LaTeX Project`, and then it updates itself. Now the features are working well.

**Comment by DavideRossi** [comment]
The issue is still open for me (codium 1.60.0 and latex workshop 8.20.2). I had to follow the workaround by @indierodo to get it working.
I also tried the workaround by @drepram but it did not work for me.

**Comment by daiyam** [comment]
@DavideRossi This is an issue of OpenVSX which has publish a broken version. (I've checked files are missing). I would encourage you to encourage the author of the extension to publish directly the extension.
In the meantimes, you can download the vsix from https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop and install it manually.

**Comment by daiyam** [comment]
I've opened the issue: https://github.com/James-Yu/LaTeX-Workshop/issues/2865

**Comment by daiyam** [comment]
Sorry guys, that extension is officially not supported on VSCodium. I wanted to ask why but I can't... no very open to discussion.
The alternative is that somebody makes a fork and maintains it for OpenVSX.

**Comment by DavideRossi** [comment]
I'm sorry to turn this issue into a chat, but can't we just report the issue to maintainer at OpenVSX? Since this is a recurring issue maybe they are willing to look into it.

**Comment by daiyam** [comment]
@DavideRossi You can, they have done so before. But, since it seems to be recurring issue, I wanted the devs of the extension to maintain it themself since it's easy to do so. 
I find it funny that a LaTeX extension doesn't want to be maintained on alternative editors since I'm associating it to Linux.
