### ISSUE TITLE
"Update download failed" on startup after latest version

### ISSUE THREAD

**Issue by matronator** [VSCodium/vscodium#489]
**Describe the bug**
When I launch VSCodium, a notification appears after a while saying:

```
Update download failed. The server sent an invalid response. Try again later.

Source: Update Service
```

The notification also appears from time to time while the app is open.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

Sorry, don't have VSCode.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Start VSCodium
2. Wait
3. ???
4. ~~Profit~~ Notification appears

**Expected behavior**
Silently and successfully download the update.

**Screenshots**
<img width="461" alt="Snímek obrazovky 2020-08-26 v 9 30 17" src="https://user-images.githubusercontent.com/5470780/91274775-7cdde080-e77f-11ea-9515-d2a0e98554c1.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6 (19G73)
 - Architecture: x64
 - Version: 1.48.1
     - Commit: 3dd905126b34dcd4de81fa624eb3a8cbe7485f13
     - Date: 2020-08-21T18:50:36.401Z (4 days ago)
     - Electron: 7.3.2
     - Chrome: 78.0.3904.130
     - Node.js: 12.8.1
     - V8: 7.8.279.23-electron.0
     - OS: Darwin x64 19.6.0

**Additional context**
I changed the extension provider from open-vsx to the VSCode marketplace.

**Comment by SimonBrazell** [comment]
Seeing today this also.

**Comment by blistok** [comment]
I was seeing the same thing since yesterday, but eventually it got to update to 1.48.2 and now it doesn't show up anymore. Perhaps related to #488 ? Or server was temporarily down?

**Comment by matronator** [comment]
Yup, false alarm, got updated today.

**Comment by harshithjv** [comment]
@blistok  This is same issue as the one raised. Fixed now.
