### ISSUE TITLE
Error using PPA

### ISSUE THREAD

**Issue by ramiel** [VSCodium/vscodium#492]
**Describe the bug**
Using the ppa stop working. I get this error:

```
Error:50 https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs vscodium InRelease                   
  429  Too Many Requests [IP: 172.65.251.78 443]
```

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Just add the Ubuntu ppa and run `sudo apt update`

**Expected behavior**
Update should happen but it doesn't

**Desktop (please complete the following information):**
 - OS: KDE neon User Edition 5.19 (Ubuntu 18:04)
 - Architecture x64
 - Version any

**Comment by brunob** [comment]
You're not using the right PPA url see https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/#alternative-option-2-using-apt-key & https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/issues/36#note_395793123

**Comment by ramiel** [comment]
So is the documentation in the website outdated?

**Comment by paulcarroty** [comment]
Yeah, [PR](https://github.com/VSCodium/vscodium.github.io/pull/29) was merged but website provides the old URL. Ping @PalinuroSec @stripedpajamas

**Comment by PalinuroSec** [comment]
the website is hosted on github pages, so it should automatically update when new stuff is merged. let me check what went wrong

**Comment by stripedpajamas** [comment]
Website is up to date.
