### ISSUE TITLE
C/C++ Extension can't be installed

### ISSUE THREAD

**Issue by JonathanCabezas** [VSCodium/vscodium#493]
I just went back from VSCode to VSCodium, and I can't find the `ms-vscode.cpptools` extension (C/C++ from Microsoft).
It seems to have disappeared from VSCodium.

It makes the type `cppdbg` unusable in `launch.json` and I don't know how to automatically attach gdb from VSCodium without it. If anyone can either fix the aforementioned problem, or atleast give a quick fix to attach gdb another way, I'd be grateful.

**Comment by spoenemann** [comment]
VSCodium now uses https://open-vsx.org as extension registry (see [DOCS.md](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace)). The Microsoft C++ extension cannot be offered there because of its restrictive [license](https://github.com/microsoft/vscode-cpptools/blob/master/Extension/LICENSE.txt):

> You may only use the C/C++ Extension for Visual Studio Code with Visual Studio Code, Visual Studio or Xamarin Studio software

**Comment by kevinfiol** [comment]
@JonathanCabezas Is this the extension you are trying to install? https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

As a workaround, you can always download the `.vsix` file and drag it into your Extensions sidebar on VSCodium. Look under "Resources" on the above link, and click "Download Extension".

**Comment by spoenemann** [comment]
Note that the license of this extension does not allow you to use it with VSCodium.

This is an MIT licensed alternative: https://open-vsx.org/extension/llvm-vs-code-extensions/vscode-clangd

**Comment by rednaz1337** [comment]
> VSCodium now uses https://open-vsx.org as extension registry (see [DOCS.md](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace)). The Microsoft C++ extension cannot be offered there because of its restrictive [license](https://github.com/microsoft/vscode-cpptools/blob/master/Extension/LICENSE.txt):
> 
> > You may only use the C/C++ Extension for Visual Studio Code with Visual Studio Code, Visual Studio or Xamarin Studio software

This is true about the compiled version, but the addon's github repo says it's licensed under MIT.

**Comment by JosueCom** [comment]
The goal of open source projects is to allow the user to have the choice to do whatever they want. Why doesn't VScodium allow one to add an extension that uses restrictive license if we wish to do so?

**Comment by stripedpajamas** [comment]
The extension itself throws when it's not run in the proprietary version. I recommend urging MS to remove the limitations from the extension.

**Comment by j0k4rX** [comment]
> @JonathanCabezas Is this the extension you are trying to install? https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
> 
> As a workaround, you can always download the `.vsix` file and drag it into your Extensions sidebar on VSCodium. Look under "Resources" on the above link, and click "Download Extension".

@kevinfiol i did exactly what u said, but there's a problem. The extension itself claims (wriiten in extension details ) to use data & telemetry of users to improve user experiences. Even the official vscode says that it can be disabled using this following line of code in settings ``"telemetry.enableTelemetry": false`` , but i don't know how far it will work.

**Comment by danger89** [comment]
For the people reading this, you can just [download the extension `.vsix` file](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) and install via command line, example:

```sh
codium --install-extension ms-vscode.cpptools-1.7.1.vsix 
```
