### ISSUE TITLE
No instructions to install from code in any GNU/Linux.

### ISSUE THREAD

**Issue by cpcbegin** [VSCodium/vscodium#496]
There is no instructions to install from code in any GNU/Linux without ppa, snap, etc...

**Comment by jim4067** [comment]
There is an option to use your systems default package manager.

**Comment by stripedpajamas** [comment]
@cpcbegin not sure what you mean; if you are looking for instructions to build from source, you can follow Microsoft's directions (https://github.com/microsoft/vscode/wiki/How-to-Contribute#prerequisites) -- that is actually what VSCodium is doing + some small changes to the product.json file.

If you are looking to download VSCodium, we have tar files on the releases page... but I don't know how they are to be used :smile: MS doesn't mention them in their docs (https://code.visualstudio.com/docs/setup/linux).

Closing this issue, but if there is something I missed let me know and I will reopen.
