### ISSUE TITLE
Setup RPM/Deb packages repositories

### ISSUE THREAD

**Issue by G-Ray** [VSCodium/vscodium#5]
Maybe consider using a service like https://packagecloud.io which is free for open source projects ?

**Comment by stripedpajamas** [comment]
@G-Ray sounds great. Can you outline what steps would need to happen for this to be set up? PRs are welcome if this requires build scripts to change.

**Comment by G-Ray** [comment]
I created an account on packagecloud and they enabled it as an OSS account. I will try to set up automatic upload of rpm/deb in the CI and will open a PR ;)

**Comment by Lomanic** [comment]
I'm personally not a huge fan of adding another third-party dependency (packagecloud), wouldn't it be sensible to host repositories directly on github (using github pages) like [this](https://pmateusz.github.io/linux/2017/06/30/linux-secure-apt-repository.html)?

**Comment by G-Ray** [comment]
@Lomanic I was not aware this was possible. Sure it would be better to not rely on another third-party dependency

**Comment by Lomanic** [comment]
Didn't know about that indeed

https://help.github.com/articles/what-is-github-pages/#usage-limits

100 GB / month, max site size 1 GB… that makes it suboptimal for a repository (vscode/ium packages are huge). I might hack something on [glitch.me](https://glitch.me).

**Comment by paulcarroty** [comment]
https://sourceforge.net/ hasn't the traffic limits.

**Comment by JL2210** [comment]
https://bintray.com/ has a 10G storage limit for OSS apps.

**Comment by KaKi87** [comment]
+1
