### ISSUE TITLE
Documentation concerning macOS defaults

### ISSUE THREAD

**Issue by lavaman** [VSCodium/vscodium#50]
I just had to search through all the defaults on my mac to find the proper name for defaults for this app. I was trying to turn of press & hold so the vim plugin was actually useable. 

Not really sure where this info should live, but it would be nice to let folks know the right name for that, since all the answers online assume you're using the MS version. In any case, here's what I had to do make it work:

defaults write com.visualstudio.code.oss ApplePressAndHoldEnabled -bool false

The MS version uses com.microsoft.VSCode.

Thanks

**Comment by stripedpajamas** [comment]
I think that would be very helpful. I think moving some of the technical details from the README into a separate doc and including how to change the defaults for vscodium in there would be great. If I get some spare time in the next couple of days I'll put in a PR, but anyone is welcome to.

**Comment by stripedpajamas** [comment]
Had a couple of minutes, how does #52 look @lavaman ?

**Comment by lavaman** [comment]
Looks good to me. Wasn't sure if there was some other docs somewhere i wasn't aware of, otherwise I would've submitted a pr myself :)

Thanks
