### ISSUE TITLE
Please release darwin package for 1.49.0

### ISSUE THREAD

**Issue by turion** [VSCodium/vscodium#500]
I'm trying to package vscodium for nixpkgs, but the 1.49.0 release seems to be missing a darwin package:

https://github.com/VSCodium/vscodium/releases/

For the older releases, there is always a file like https://github.com/VSCodium/vscodium/releases/download/1.48.2/VSCodium-darwin-1.48.2.zip, but this is missing for 1.49.0.

**Comment by edwardloveall** [comment]
I believe it was pulled because it won't launch on macOS: https://github.com/VSCodium/vscodium/issues/498#issuecomment-691128388

**Comment by stripedpajamas** [comment]
Yeah it's busted. Tracking in #498
