### ISSUE TITLE
No VSCodium-darwin-1.49.0.zip in the 1.49.0 artifacts

### ISSUE THREAD

**Issue by samuela** [VSCodium/vscodium#501]
It looks like the macOS builds of VSCodium were not included in the 1.49.0 release for some reason: https://github.com/VSCodium/vscodium/releases/tag/1.49.0. This breaks downstream users/scripts that rely on the build outputs, including https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vscode/update.sh.

Is there any way we could get those macOS build artifacts uploaded as well?

**Comment by eshimischi** [comment]
There is an issue with Mac build (because VSCode moved from Electron 7.0 to 9.0 version and it broke VSCodium build), better sit and wait for the issue to solve.

**Comment by samuela** [comment]
Gotcha, is there a github issue tracking that?

**Comment by eshimischi** [comment]
> Gotcha, is there a github issue tracking that?

sure thing, #498

**Comment by turion** [comment]
Duplicate of https://github.com/VSCodium/vscodium/issues/500
