### ISSUE TITLE
New codium on macOS will not launch

### ISSUE THREAD

**Issue by aaronsdevera** [VSCodium/vscodium#502]
**Describe the bug**
It appears that after upgrading to the latest VSCodium on macOS, the app will not launch.

**To Reproduce**
1. Update the latest VSCodium build.
2. Click on the VSCodium icon

**Expected behavior**
Expected VSCodium to launch upon click of icon or `.app` executable in the system `Applications` directory.

**Desktop (please complete the following information):**
 - macOS 10.15.6
 - Architecture [e.g. x64, ia32, arm64]
 - Version [e.g. 1.33.0]

**Potential fix:**
- uninstall VSCodium
- install VSCodium with Homebrew: `brew cask install vscodium`
- ensure that macOS app firewall is not blocking launch of the app by going to the "Security" pane in the System Preferences

**Comment by mmoran0032** [comment]
Had to do this as well. The `brew` version is:

```
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-26T11:14:30.690Z (2 wks ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
```

Is this related to https://github.com/VSCodium/vscodium/commit/27d8a663860d717102a9763724a7565f30a52749?

**Comment by bnied** [comment]
https://github.com/VSCodium/vscodium/issues/498
