### ISSUE TITLE
enable-crash-reporter is true in 1.49.0

### ISSUE THREAD

**Issue by Rondom** [VSCodium/vscodium#504]
**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ X ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Update to 1.49.0 (via RPM on Fedora 32 in my case)
2. Open argv.json to check the `enable-crash-reporter` setting. => It is `true`

**Expected behavior**
Crash reporting is still disabled.

**Desktop (please complete the following information):**
 - OS: Fedora 32
 - Architecture x64
 - Version: 1.49.0

**Additional context**

See the [release notes about the change from `telemetry.enableCrashReporter` to `enable-crash-reporter` in `argv.json`](https://code.visualstudio.com/updates/v1_49#_disabling-crash-reporter)

**Comment by SteveJobs91** [comment]
I think that this bug has been fixed in the newer version of VSCodium.
I think that this bug is only occuring to you. I have not seen any similiar bugs.
I think that this problem is only in VSCodium, but I think that this bug is only occuring to you.
