### ISSUE TITLE
Why was a darwin download dropped in favor of Homebrew?

### ISSUE THREAD

**Issue by MSoegtropIMC** [VSCodium/vscodium#505]
As far as I can see the latest Version for Darwin / macOS available for download is 1.47.2. After that the recommendation seems to be to use homebrew.

I am not a big fan of homebrew because it makes system binary folders writable to the current user, so that stuff can be installed without sudo - at least that was so when I last tried it begin of this year. Essentially it kills all system security measures. I don't think that this is a good idea so I am not using homebrew.

I would really appreciate if there would be a downloadable installer for macOS again.

Users hit by the 1.49.0 update issue #498 and not using homebrew have to go back to 1.47.2 now.

**Comment by MSoegtropIMC** [comment]
Hmm, I found a 1.48.2 darwin image after some searching, but most releases don't have one. Can you please clarify what the policy is?

**Comment by stripedpajamas** [comment]
We release Darwin binaries with every release. 1.49.0 hasn't worked yet so that one is still pending. We don't recommend homebrew over any other installation method. If a Darwin binary is missing it's most likely due to some issue.
