### ISSUE TITLE
Unable to install platformio after update

### ISSUE THREAD

**Issue by sdaitzman** [VSCodium/vscodium#508]
**Describe the bug**
Does not show up in the marketplace and cannot be installed by unique identifier at CLI.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to marketplace tab
2. Search for platformio (no results
3. Open terminal, run `$ code --install-extension platformio.platformio-ide`
4.

```
Installing extensions...
Extension 'platformio.platformio-ide' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
Failed Installing Extensions: platformio.platformio-ide
```
5. 😢 

**Expected behavior**
PlatformIO should appear in search results and install successfully.

**Desktop (please complete the following information):**
![Screen Shot 2020-09-19 at 8 42 11 AM](https://user-images.githubusercontent.com/1499476/93667455-0bc6db80-fa54-11ea-8d71-4c10035b1d38.jpg)
```
About VSCodium:
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-26T11:14:30.690Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
```

**Comment by sdaitzman** [comment]
I've also tried fully uninstalling the remaining artifacts of the package, restarting VSCodium, and installing again. No luck.

**Comment by vsivsi** [comment]
I'm also seeing inconsistencies in the marketplace packages listed as available.  Here are two examples:

---

Search: `awk`

VSCode:

<img width="424" alt="image" src="https://user-images.githubusercontent.com/428642/93825278-c94efb80-fc19-11ea-85a5-d8cdcee7e7f1.png">

VSCodium:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/428642/93825351-eb487e00-fc19-11ea-8a07-a5f6c412aba3.png">

---

Search: `golang`

VSCode:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/428642/93825424-192dc280-fc1a-11ea-9b84-1c4704aa2b76.png">

VSCodium:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/428642/93825453-2d71bf80-fc1a-11ea-90e5-ad2e32adfc13.png">

---

Note: In the case of the standard Go package, the two editors aren't even offering the same version of the package (v0.17.0 vs v0.16.2)

Both of VSCod(e|ium) are v1.49.1 and both were installed using `brew` on:

<img width="238" alt="image" src="https://user-images.githubusercontent.com/428642/93825718-ad982500-fc1a-11ea-9ebf-8ff6f893753b.png">

**Comment by vsivsi** [comment]
@sdaitzman  See my update above. Are you sure you aren't seeing the same effects of the switch to open-vsx, whenever that happened?

**Comment by stripedpajamas** [comment]
Closing per https://github.com/platformio/platformio-vscode-ide/issues/1802

Additional considerations for VSCodium+extensions: https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace

**Comment by chintan-mishra** [comment]
[MS is considering publishing](https://github.com/microsoft/vscode-cpptools/issues/6518) VSCode-CppTools to Open VSX. This will help get PlatformIO in Open VSX repo.

Press thumbs up on the MS issue if you want to make this process faster.

**Comment by G2G2G2G** [comment]
@chintan-mishra doesn't look like it. 

Anyone have a link on how to manually install platformIO (for those of us who know that microsofts terms etc are irrelevant), I guess I'll probably figure it out before anyone replies.

**Comment by chintan-mishra** [comment]
Install MS' CppTools from the *.vsix provided on GitHub. Then download the PlatformIO *.vsix file. Install the two manually and you are good to go.

**Comment by G2G2G2G** [comment]
Yea I got it, I just did `pip3 install platformio` and it works fine
