### ISSUE TITLE
Error: Cask 'vscodium' conflicts with 'visual-studio-code'.

### ISSUE THREAD

**Issue by alexventuraio** [VSCodium/vscodium#509]
**Describe the bug**
I'm on Mac and I'm trying to install both **VSCode** and **VSCodium** using [Homebrew](https://brew.sh) and I get the following error:

```sh
➜  ~ brew cask install visual-studio-code
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
odrive

==> Downloading https://update.code.visualstudio.com/1.49.1/darwin/stable
Already downloaded: /Users/alex/Library/Caches/Homebrew/downloads/eeb0142ac77bb0a08e95a4bdbd0afbaf9b826f77d5bbb9889800ead4ae0260f7--VSCode-darwin-stable.zip
==> Verifying SHA-256 checksum for Cask 'visual-studio-code'.
==> Installing Cask visual-studio-code
==> Moving App 'Visual Studio Code.app' to '/Applications/Visual Studio Code.app'.
==> Linking Binary 'code' to '/usr/local/bin/code'.
🍺  visual-studio-code was successfully installed!
➜  ~ brew cask install vscodium
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
tinymediamanager

Error: Cask 'vscodium' conflicts with 'visual-studio-code'.
➜  ~
```

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I install either one or the other using `brew` command and the other one by downloading directly from the corresponding browser link.
- The only problem is when trying to install both using `brew` commands.
- [x] They can remain both in the same computer and they work pretty well after installing using different ways for both.

**To Reproduce**
1. Go to 'terminal' app.
3. Install [Homebrew](https://brew.sh/)
2. Run either `brew cask install visual-studio-code` or `brew cask install vscodium`
3. Run the other command from above (no matter the order).

**Screenshots**
<img width="1363" alt="Screen Shot 2020-09-19 at 12 37 38" src="https://user-images.githubusercontent.com/13169164/93684364-ee563980-fa74-11ea-8967-bde490ac4381.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - Architecture: x64
 - Version: 10.15.6 (19G73)

**Comment by h4p** [comment]
I experience the same on macOS Catalina

**Comment by stripedpajamas** [comment]
I don't think they should conflict since they use different data folders.

It's reporting a conflict due to this line in the cask formula: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/vscodium.rb#L12

Feel free to open an issue/PR in that repo (nothing in this repo affects the cask formula).

**Comment by Strajk** [comment]
I've downloaded the installer directly from https://github.com/VSCodium/vscodium/releases and it works fine side by side with VSCode, no conflicts so far.

Btw here's the discussion about adding the conflict check... I'm not very smart from it ¯\_(ツ)_/¯ 

https://github.com/Homebrew/homebrew-cask/pull/62036#pullrequestreview-227808506

![image](https://user-images.githubusercontent.com/697301/110171493-14da1800-7dfc-11eb-8631-29b97a887ab5.png)

**Comment by alexventuraio** [comment]
> I've downloaded the installer directly from https://github.com/VSCodium/vscodium/releases and it works fine side by side with VSCode, no conflicts so far.
> 
> Btw here's the discussion about adding the conflict check... I'm not very smart from it ¯_(ツ)_/¯
> 
> [Homebrew/homebrew-cask#62036 (review)](https://github.com/Homebrew/homebrew-cask/pull/62036#pullrequestreview-227808506)
> 

The problem was not to run them side by side on the same computer at the same time but the problem was to download them using Homebrew because of a conflict on the folder this tool downloads the package from both formulas.

**Comment by daiyam** [comment]
The main issue is that the binary is named `code` which is the same name for VS Code's binary.
It's is only for macOS, on Linux and Windows, the binary is named `codium`. It've done the PR #655 to fix that.
