### ISSUE TITLE
Release notes for latest version are "null"

### ISSUE THREAD

**Issue by davidskeck** [VSCodium/vscodium#513]
**Describe the bug**
The release notes for the latest version are "null"

**Please confirm that this problem is VSCodium-specific**
This is in the repository for vscodium.

**Please confirm that the issue/resolution isn't already documented**
Checked open issues.

**To Reproduce**
Go to the latest release.

**Expected behavior**
Normal release notes.

**Comment by stripedpajamas** [comment]
This is due to some recent deploy logic. We rarely have release notes though; VSCode's release notes contain the actual changes.

**Comment by davidskeck** [comment]
Got it. Thanks! Just seemed out of place.
