### ISSUE TITLE
 A specific extension cannot be found

### ISSUE THREAD

**Issue by vojtechkral** [VSCodium/vscodium#514]
Issue moved over from microsoft/vscode#107034

---

Issue Type: <b>Bug</b>

I can't seem to be able to install the extension [File Browser](https://marketplace.visualstudio.com/items?itemName=bodil.file-browser) from VSCode.

When I enter the extension name or ID into the search field in VSCode, it will never be included in the list of results. Using `ext install bodil.file-browser` as instructed on the marketplace leads to the same result.

I had to download the VSIX and install from that - that does work, there seems to be no issue with using the extension. It does show up in my *installed extensions* list, but still won't show up in the online search.

All other extensions can be found just as normal as far as I can tell - I wasn't able to find any other extension where this would occur as well so far.

I have tried both in regular session as well as with extensions disabled, there's no difference.

VS Code version: VSCodium 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T19:42:46.044Z)
OS version: Linux x64 5.8.8-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 2292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|31.05GB (3.66GB free)|
|Process Argv|--unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by sunng87** [comment]
VSCodium is using [openvsx](https://open-vsx.org/) as its default marketplace. It seem your extension is not available there.

**Comment by isaiasneto** [comment]
> VSCodium is using [openvsx](https://open-vsx.org/) as its default marketplace. It seem your extension is not available there.

There is how to set the same marketplace that vscode uses?

**Comment by stripedpajamas** [comment]
https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace

**Comment by vojtechkral** [comment]
Ah, interesting, thanks.

**Comment by debo** [comment]
Sorry for comment on this one, but one thing is not fully clear to me, where do I find the _product.json_ file?

**Comment by pdfrod** [comment]
I had the same issue as @debo; the documentation talks about a `product.json` but gives no hints about where to find it. It took me a while to locate it.

**Comment by debo** [comment]
@pdfrod would you be able to share that information with me too please? I still didn't manage to find it. Thanks.

**Comment by pdfrod** [comment]
@debo if you're using Ubuntu like me, it's in `/usr/share/codium/resources/app/product.json`. For other operating systems I have no idea, sorry.

**Comment by GitGangGuy** [comment]
@pdfrod Thank you so much, the location you found should work for all GNU/Linux distributions (though the package might be named differently, i.e. on Arch Linux it's `/usr/share/vscodium-bin` instead of `/usr/share/codium`).
