### ISSUE TITLE
Missing AUR package

### ISSUE THREAD

**Issue by smac89** [VSCodium/vscodium#515]
The aur package [vscodium-bin](https://aur.archlinux.org/packages/vscodium-bin/) does not exist. Did it move?

**Comment by stripedpajamas** [comment]
I'm not the maintainer of the AUR package. @plague-doctor ?

**Comment by Zetabite** [comment]
Weird thing is, there is nothing about a deletion.

**Comment by CRKatri** [comment]
It's git repo is still available however it seems to have been removed from the AUR by him, as @Zetabite said there is nothing about it getting removed in the mailing lists. I can take over as maintainer if you all would like.

**Comment by stripedpajamas** [comment]
I have no opinion here :smile: I'm not sure how maintainership works in AUR.

**Comment by CRKatri** [comment]
It is now available again. I have taken over as maintainer, so this issue can be closed.

**Comment by jee-r** [comment]
Yes [git repo still available](https://aur.archlinux.org/cgit/aur.git/?h=vscodium-bin)  really strange that the pkg is missing from the AUR index. 

it can be a good thing if someone active and reachable from the VSCodium community take the ownership.

**Comment by CRKatri** [comment]
If someone else wants to take it be my guest, but until then I'll do it.

**Comment by jee-r** [comment]
it's ok if you feel you can keep it up to date quickly

**Comment by smac89** [comment]
Sweet! Thanks everyone and thank you @CRKatri for taking this on

**Comment by jee-r** [comment]
@CRKatri can you update it pkg is flagged out-of-date since the 09-25 

If you want you can add me as co-maintainer so i can help you to keep the pkg updated

**Comment by CRKatri** [comment]
#520

**Comment by jee-r** [comment]
hmm ok my bad, sorry !

**Comment by CRKatri** [comment]
No problem, it doesn't seem to be a major release, just a change to the README, so I'm in no rush.
