### ISSUE TITLE
Python Interactive cells missing "Run Cell", "Run Below", "Debug Cell" prompts

### ISSUE THREAD

**Issue by imtherainman** [VSCodium/vscodium#516]
**Describe the bug**
When creating a cell to run in python interactive mode (using `# %%`), in VSCode, there are prompts for "Run Cell", "Run Below", "Debug Cell", but they do not show up in Codium. The keyboard shortcuts `ctrl+enter` and `shift+enter` for Run and Run and Advance still work, but there doesn't seem to be a way to replicate the "Debug Cell" functionality.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Create and save a new file with the `.py` extension
2. Comment `# %%` followed by some python code
3. No prompts show up for "Run Cell", "Run Below", "Debug Cell"

**Expected behavior**
Prompts for "Run Cell", "Run Below", "Debug Cell" should show up as they do in VSCode

**Screenshots**
VSCode working as expected:
![image](https://user-images.githubusercontent.com/15202629/94051380-4ef2b880-fd8c-11ea-818e-487c8a900cce.png)

Codium missing the expected prompts
![image](https://user-images.githubusercontent.com/15202629/94051456-692c9680-fd8c-11ea-881b-56d74d7e09e4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (and reproduced on Mac OS Catalina)
 - Architecture: x64
 - Version:
```
Version: 1.49.1 (user setup)
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-18T10:28:29.357Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17134
```

**Additional context**

**Comment by ejuarezg** [comment]
I'm also seeing this issue.

**Comment by ZeusDeus** [comment]
same

**Comment by daiyam** [comment]
... that feature is provided by the extension Jupyter (ms-toolsai.jupyter) which isn't available on [Open VSX](https://open-vsx.org/)

You will need to switch to the VS Code Marketplace ([howto](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace)) or directly install the `.vsix` from https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
