### ISSUE TITLE
Incorrect app_id

### ISSUE THREAD

**Issue by wb9688** [VSCodium/vscodium#518]
**Describe the bug**
`app_id` is not the same as the name of the .desktop file.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open VSCodium

**Expected behavior**
`app_id` is the same as the name of the .desktop file. i.e. `codium`

**Desktop (please complete the following information):**
 - OS: Debian unstable
 - Architecture: amd64
 - Version: 1.49.1-1600426486

**Additional context**
This causes the icon to not properly show up on e.g. standards compliant Wayland compositors. `app_id` gets automatically set from X's `WM_CLASS`, which is set to `vscodium` for the class and `VSCodium` for the instance.

**Comment by wb9688** [comment]
Closing, because .desktop files apparently also have some optional field for the `WM_CLASS`, namely `StartupWMClass`, which is correct.

**Comment by alejandro097** [comment]
having the problem, wm_class is missing under wayland.

![image](https://user-images.githubusercontent.com/47724370/178131062-b3a4319a-51b1-4af4-b807-bbb70ebe1db7.png)
