### ISSUE TITLE
GitHub Actions ARM Builds Fail

### ISSUE THREAD

**Issue by CRKatri** [VSCodium/vscodium#520]
**Describe the bug**
Under releases there is none for arm with the expected name of `VSCodium-linux-arm-1.49.2.tar.gz`

**Comment by stripedpajamas** [comment]
Yeah, it looks like the ARM build is trying to download something Electron-related that is not found: https://github.com/VSCodium/vscodium/runs/1163373204?check_suite_focus=true#step:7:79

More investigation needed, as I think Electron supports this architecture without issue.

**Comment by CRKatri** [comment]
On the latest github actions run it seems both arm builds have failed.

**Comment by CRKatri** [comment]
https://github.com/VSCodium/vscodium/actions/runs/285170050

**Comment by stripedpajamas** [comment]
Have merged my PR; we should get ARM release in the next 20-30 mins.
