### ISSUE TITLE
Ctrl click does not jump to function implementation

### ISSUE THREAD

**Issue by gerroon** [VSCodium/vscodium#524]
**Describe the bug**
The ctrl-lef click combo on a functiion name normally jumpts to the function's implementation. However this seems broken in Vscodium. I have tested this with Vscode 1.49.3 and it works with that so I am not sure why it is broken in Vscodium.

**Please confirm that this problem is VSCodium-specific**
- [X ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open a python file with some function calls and their implementation functions
2. find a place where  a function is used
3. click on the function's name with ctrl-left click
4. it does not jump to the implementation

**Expected behavior**
When click it should open/jump to the function's implemetation body.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Architecture x64
 - Version 1.49.3

**Comment by GitMensch** [comment]
What type of function is this? If it is a C function then you'd need an extension (most times using a language server) to handle that; for the non-free Visual Studio Code this would be the cpp extension, but the language server it uses is not even "open source" and its license explicit only allows it to be used from the "Microsoft Product".
There free extensions, most are around clangd.

It _may_ be the case that newer versions of "MS Visual Studio Code" now ship with more default extensions, including c++/C# or others that are non-free - or it may be possible that this isn't about "C/C++/C#` but another language which may have a free extension bundled that is responsible for this and already possible to use with a manual installation of it after installing vscode.

... after reading the additional post I see that it contains "open python file". So you likely want to install `ms-python` which is available in the open vsx registry and therefore in the default extension provider (and may had that extension installed on the MS side).

I'm looking forward to read your update and possible close of this issue - In any case: please add "python function" in your issue title.

**Comment by gerroon** [comment]
I could not figure out the casue of this unfortunately, after debuggin it for some hours. I deleted all my settings and extensions and started from scratch :( Now it work. I am thinking  that this was more of a  setting of some kind rather than caused by an extension

**Comment by Jagrutiti** [comment]
Hey,

I was facing the same issue for Python. It was resolved after I installed `ms-python` as suggested in the comments above. Shouldn't this feature be activated by default or something? Because I use Visual Studio Code for Node or Python and never needed to install an extension for this feature :)
