### ISSUE TITLE
non sign exe for user install

### ISSUE THREAD

**Issue by x0rld** [VSCodium/vscodium#527]
I would like to install vscodium on my professional computer to use it but the exe is not sign so windows smartscreen don't let me install it 
when I click on more info i don't have the "run anyway" button
![image](https://user-images.githubusercontent.com/45242856/95307120-8aab7900-0888-11eb-9a8f-9fd3933b16ff.png)

**Comment by stripedpajamas** [comment]
Yeah we haven't gotten Windows signing implemented yet. It should let you click More Info and then Run Anyway, or something similar to bypass the prompt.

**Comment by x0rld** [comment]
on my laptop i don't have "Run Anyway" thats the issue
