### ISSUE TITLE
remote: No anonymous write access. fatal: Authentication failed for 'https://github.com/Trend20/RestaurantWebApplication.git/

### ISSUE THREAD

**Issue by Trend20** [VSCodium/vscodium#528]
**Describe the bug**

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS, Ubuntu 16.04, etc]
 - Architecture [e.g. x64, ia32, arm64]
 - Version [e.g. 1.33.0]

**Additional context**

**Comment by stripedpajamas** [comment]
Please fill out the template.

**Comment by abhiroopghatak** [comment]
same issue with my laptop . No matter it is VS code or plain win command line . Even using correct password git isnt allowing to push into own repo . Something fishy with https communication

**Comment by chauanphu** [comment]
In my case, even though I had set up the ssh key, email, password, it didn't work.
However, I managed to solve it by re-cloning the project but this time I used the ssh url.
Now it works beautifully.

**Comment by erythrocyte** [comment]
had same issue. nothing works except reclone

**Comment by jonasht** [comment]
I have the same essue
