### ISSUE TITLE
ccptools built-in not enabled properly?

### ISSUE THREAD

**Issue by michaelopdenacker** [VSCodium/vscodium#530]
When I use VS Code on the Linux kernel code and enable cpptools, I can immediately see the prototype of functions when I move the mouse over a function call, and I have the full "Go to declaration, Go to definition..." menu:

![vscode1](https://user-images.githubusercontent.com/5461949/95562925-10602d80-0a1d-11eb-9bd2-03888ca942b1.png)
![vscode2](https://user-images.githubusercontent.com/5461949/95562957-19e99580-0a1d-11eb-8825-a38fefa5fe4f.png)

However, I don't have this behavior with cpptools that is built in VSCodium. When I move the mouse over a function, there is no prototype automatically displayed, and there is just a plain menu, which seems to indicate that symbols for the project hasn't been indexed:

![vscodium1](https://user-images.githubusercontent.com/5461949/95563010-2a017500-0a1d-11eb-8206-0b87c61fb47a.png)

Is there anything to do to get the project indexed?

- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
- [x ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

 - OS: Ubuntu 20.04
 - Architecture: x86_64
 - Version: 1.49.3

**Comment by michaelopdenacker** [comment]
Note that I managed to get some of the functionality by adding the Exuberant Ctags add-on (https://github.com/chriswheeldon/vscode-ctags), and running the "regenerate tags file" command.

Please excuse the probably naive questions. I'm new to "vscode" and "vscodium".

**Comment by moether** [comment]
From your VSCodium screenshot above I see that the Microsoft C/C++ extension is not active / installed at all. The typical entries in the status bar are missing.

**Comment by michaelopdenacker** [comment]
I understood that the Microsoft C/C++ extension (cpptools) was compiled as a built-in in VSCodium. Isn' t this so?

**Comment by moether** [comment]
I highly doubt that.

But since VSCodium is now using open-vsx.org as extensions store, you won't find the C/C++ extension anymore in the extensions tab from within VSCodium. I believe it won't ever appear in that store for licensing reasons.
But there are multiple other tickets about the new store and how to switch back to the official Microsoft extension store. Then you will be able to install C/C++ and see the same result as with official MS Code builds.

**Comment by michaelopdenacker** [comment]
![codium-cpp-builtin](https://user-images.githubusercontent.com/5461949/97314561-2157ce00-1868-11eb-8701-195e98e50c52.png)

Thanks for your insights. At least in the built I have (see below), cpp support seems to be built-in.
I'll check the freely licensed options !
Thanks again,
Michael.

Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-15T11:13:06.921Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-52-generic

**Comment by GitMensch** [comment]
That's the builtin cpp basics (grey one) which provides exactly what it says (no intellisense). MS specified they don't want to extend its function and leave that to the (proprietary) cpptools extension (the purple one).

From your screenshot the builtin extension works fine, I therefore suggest to close this issue.
For more information about the extensions, including the cpptools one see https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace. your ctags option is likely the way to go.

**Comment by stripedpajamas** [comment]
Closing per @GitMensch's comment. The more functional extension is proprietary and licensed to only work with Visual Studio Code (ref: https://github.com/VSCodium/vscodium/blob/master/DOCS.md#proprietary-debugging-tools).
