### ISSUE TITLE
AppImage fails to create in Docker environment

### ISSUE THREAD

**Issue by stripedpajamas** [VSCodium/vscodium#532]
Recently switched to building in containers, the same as Microsoft is doing. Now the AppImage [fails to build](https://github.com/stripedpajamas/vscodium/runs/1229304191?check_suite_focus=true) with this message:

```
fuse: device not found, try 'modprobe fuse' first

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
Error: Process completed with exit code 127.
```

This seems to be a known issue (https://github.com/AppImage/AppImageKit/issues/405, https://github.com/AppImage/AppImageKit/wiki/FUSE#docker), but I'm not sure exactly how to fix it. Looking for help from perhaps @linsui who got the AppImage scripts in our build.

**Comment by linsui** [comment]
I'd like to help but I don't have enough skill... Forward ping to @tyu1996 :joy:

**Comment by stripedpajamas** [comment]
Should be fixed in next release, thanks @ferion11
