### ISSUE TITLE
Set update.mode = none on install

### ISSUE THREAD

**Issue by ggreif** [VSCodium/vscodium#533]
**Describe the bug**

`codium` sometimes starts to download an update from a Microsoft server.
The corresponding setting ID is `update.mode` the value it is set originally is
``` js
"update.mode": "default"
```

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

NACK. We probably want to deviate from VSC here.

**Please confirm that the issue/resolution isn't already documented**
- [ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

https://github.com/VSCodium/vscodium/blob/master/DOCS.md#getting-all-the-telemetry-out mentioned that these settings can be disabled. I'm just asking whether they could come out of the box disabled, like this:
``` js
"update.mode": "none"
```

**To Reproduce**
1. Start `codium` the first time
2. Observe the bottom-left cogwheel, notifying you
3. Hover over it
4. See "Manage - New VSCodium update available" notice:
<img width="171" alt="Screen Shot 2020-10-11 at 12 40 21" src="https://user-images.githubusercontent.com/1312006/95676621-b3e94380-0bbf-11eb-887b-3855422bf949.png">
5. When clicking on it I get a menu offering update:
<img width="210" alt="Screen Shot 2020-10-11 at 12 41 40" src="https://user-images.githubusercontent.com/1312006/95676617-ad5acc00-0bbf-11eb-85c4-2fc8c79337d3.png">

**Expected behavior**

Come to life like this:

<img width="473" alt="Screen Shot 2020-10-11 at 12 47 09" src="https://user-images.githubusercontent.com/1312006/95676663-f9a60c00-0bbf-11eb-9959-869c8eda07e9.png">

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Mac OS (High Sierra), Ubuntu 20.04
 - Architecture x64
 - Version 1.49.3

**Additional context**

For the record, `v1.50.0` just came out, so maybe that's the one it wants to download...

In both OSs I used `nixpkgs` to get the app.

**Comment by ggreif** [comment]
For the record, `v1.50.0` just came out, so maybe that's the one it wants to download...

**Comment by stripedpajamas** [comment]
Hi @ggreif 

First off just for clarification -- VSCodium does not contact Microsoft's servers to check for updates. VSCodium has it's own update server (https://github.com/VSCodium/update-api).

There has been a few comments lately about disabling auto-updates by default. Would you still want auto-updates disabled now knowing that it isn't calling MS?

**Comment by ggreif** [comment]
@stripedpajamas Thanks. It is relieving to learn that it contacts its own server! But then it shouldn't say that "The updates are fetched from a Microsoft online service"!
Personally I think the default should be `none`, still. But I am probably biased, because I am using `nixpkgs` to get the recent versions. Maybe that's the reason that the update couldn't be applied, as `/nix/store/...` is read-only.
