### ISSUE TITLE
Missing extensions to use sftp

### ISSUE THREAD

**Issue by step135** [VSCodium/vscodium#541]
Comparing to Visual Studio Code, there are not found any extensions to connect through ftp.

**Comment by stripedpajamas** [comment]
Hi @step135 -- as mentioned in the docs, VSCodium uses a different extension marketplace which does not currently include all the extensions in Microsoft's marketplace.

https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace

**Comment by step135** [comment]
"VSCodium uses a different extension marketplace" - This is obvious and unhelpful statement you are providing. It does not solve the issue how to connect through ftp. It could be directly integrated without any need of extension. 

You closed the issue, that means you are not interested that any solution would appear!

**Comment by stripedpajamas** [comment]
@step135 I linked to the documentation that explains how to install any extension you want. 

"Directly integrating" some kind of FTP support is out of the scope of this project.
