### ISSUE TITLE
gitlab link/repo is not good

### ISSUE THREAD

**Issue by JOduMonT** [VSCodium/vscodium#542]
https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/

![image](https://user-images.githubusercontent.com/5204724/97078213-aba7f400-1614-11eb-8efc-da3e244c6231.png)

**Comment by paulcarroty** [comment]
It's not a bug, the behavior documented [here](https://docs.gitlab.com/ee/user/project/pages/introduction.html#gitlab-pages-access-control). Short version - Gitlab Pages returns 404 if there's no `index.html` in `dir/`.
