### ISSUE TITLE
nrwl angular console (nx console) & jest runner not found in the market place

### ISSUE THREAD

**Issue by vladimirdrayling** [VSCodium/vscodium#544]
**Describe the bug**

The 2 extension(s) below, in workspace recommendations have issues: nrwl.angular-console (not found in marketplace) firsttris.vscode-jest-runner (not found in marketplace)

![image](https://user-images.githubusercontent.com/16114644/97082142-cf187200-1607-11eb-8dcd-2335046a4dd5.png)

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
* [Install microsoft's VS Code (system installer)](https://code.visualstudio.com/download)
* `ctrl+shift+x`.
* Type `nx console` in search field & install
* Remove VS Code
* Install VS Codium
* Open Codium
* See the notification in the right bottom corner (see image in the bug description)

**Expected behavior**
Extension should be show in in left sidebar.

**Desktop (please complete the following information):**
 - OS: win 10
 - Architecture: x64
 - Version: 1.50.1

**Comment by stripedpajamas** [comment]
This is expected; VSCodium uses a different extension marketplace than Visual Studio Code. See the entry about this in the docs https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace
