### ISSUE TITLE
Appimage not available for 1.50.0 and 1.50.1

### ISSUE THREAD

**Issue by Tauheed-Elahee** [VSCodium/vscodium#545]
**Describe the bug**
An AppImage is not available for the 1.50.0 and 1.50.1 releases. It is available for previous releases.

**Please confirm that this problem is VSCodium-specific**
- [✓] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [✓] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to [Releases](https://github.com/VSCodium/vscodium/releases)
2. Scroll down to either release [1.50.0](https://github.com/VSCodium/vscodium/releases/tag/1.50.0) or [1.50.1](https://github.com/VSCodium/vscodium/releases/tag/1.50.1)
3. Try to find AppImage

**Expected behavior**
An AppImage on GitHub releases to make the program accessible and easy to download on Linux.

**Screenshots**
![Screenshot_20201025_200806](https://user-images.githubusercontent.com/36247967/97122793-dd958500-16fe-11eb-894d-87f03b8b969c.png)

**Desktop (please complete the following information):**
 - OS: GNU/Linux (All)
 - Architecture x64
 - Version 1.50.0 and 1.50.1

**Additional context**
AppImages are a great way to distribute programs on Linux in a disto agnostic way. [See AppImage website.](https://appimage.org/)

**Comment by stripedpajamas** [comment]
This was due to #532 but has since been fixed. AppImages are in the latest release.
