### ISSUE TITLE
VSCodium creates debug.log automatically

### ISSUE THREAD

**Issue by jmoupah** [VSCodium/vscodium#550]
Hello,

issue is here for VSCode : https://github.com/microsoft/vscode/issues/108886 and had been fixed in 1.49.2
Is there a problem to fix it to in VSCodium ?

To repro :
1. clone https://git.spip.net/spip-contrib-extensions/cvt_rechercher.git somewhere on your Windows 10 machine
2. open this repo in VSCodium
3. clone https://git.spip.net/spip-contrib-extensions/responsivenav.git somewhere else on your Windows 10 machine
4. open this 2nd repo in another VSCodium
5. open the file prive\squelettes\contenu\configurer_responsivenav.html
6. TADAM !

Thanks

**Comment by chrispinkney** [comment]
Having this too @ 1.50.1

**Comment by CxRes** [comment]
Please refer to https://github.com/microsoft/vscode/issues/108886#issuecomment-717398981 where it is suggested that vscodium needs a runtime fix in line with the fix for vscode...

**Comment by CxRes** [comment]
The error still occurs in 1.51.0!!!

**Comment by stripedpajamas** [comment]
Well I've got no idea what was done in https://github.com/microsoft/vscode/pull/107366 :raised_eyebrow: no files were changed. If anyone has any ideas I'm all ears.

**Comment by jmoupah** [comment]
Hello,

for some reason I ignore, the bug is no longer present but I can't let if it's with a VSCodium update or some Windows update.

VSCodium 1.53.2
Windows 10 20H2 / 19042.804
