### ISSUE TITLE
blank codium window on ubuntu 18

### ISSUE THREAD

**Issue by greenpdx** [VSCodium/vscodium#551]
I have installed vscodium 1.50.1 using both the repo and dpkg -i deb on a fresh ubuntu 18.04 lxc containers. 

I also have to install libgbm, libx11-xcb libxcb-dri2-0 libasound2 to get it to start.

After it starts the only thing displayed is the window that is blank. But the mouse cursor chnages as I move it over the window.  I can click on where the "file" menu should be and the I see a blank menu show and if I click at the bottom where quit should be, it exits.  So the menu is working, but I can see only a white window.

   

![codium--nowidgets](https://user-images.githubusercontent.com/4604678/97459411-fd909880-18f8-11eb-9e19-a25ecba5c027.png)

**Comment by greenpdx** [comment]
[codiumVerbose.txt](https://github.com/VSCodium/vscodium/files/5455112/codiumVerbose.txt)

Here is the --verbose output

**Comment by GitMensch** [comment]
I don't know how you connect to the containers, maybe via x11-forwad? I had to patch libxcb.so, disabling big messages to get it working in that context.

**Comment by greenpdx** [comment]
codium --no-xshm
