### ISSUE TITLE
Are vscodium extensions telemetry free?

### ISSUE THREAD

**Issue by playgithub** [VSCodium/vscodium#552]
To be more clear
1. Are integerated extenstions of vscdoium telemetry free?
2. Are extensions in vscodium's office extenstion market telemetry free by default?

**Comment by stripedpajamas** [comment]
The integrated extensions are bundled at build time, and therefore should not have telemetry (we sweep the code for known MS telemetry hosts and replace them). 

There are no guarantees that extensions in the extension marketplace are telemetry-free. 

All extensions "should" honor the global telemetry setting in VSCode/VSCodium, which VSCodium sets to Off at build time.

**Comment by playgithub** [comment]
Thanks
