### ISSUE TITLE
Deleting a file from the source tree makes the program hang for seconds at time

### ISSUE THREAD

**Issue by bryanpedini** [VSCodium/vscodium#555]
**Describe the bug**
Almost identical to [microsoft/vscode#43508](https://github.com/microsoft/vscode/issues/43508), when deleting a file from the left tree the program hangs for seconds every time, as seen in the video, by not having the mouseover shadow appear (is there any other way to show a hanged program?).
Only issue, as per video proof, is that this time only `codium` has this bug.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. open `codium` on a project folder
2. delete a file to trash (I have "don't ask me again" enabled, dunno if it changes anything)
3. wait

**Expected behavior**
not wait, file deleted immediately

**Screenshots**
https://youtu.be/_2H9S5912KY

**Desktop (please complete the following information):**
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-15T11:13:06.921Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.19.0-12-amd64

**Additional context**
N/A

**Comment by The-CodeNinja** [comment]
Hello there! I am facing a similar issue. Accept in my case, the codium requires to be restarted. happens only when I delete a file from the left tree. Also, it asks if I want to send the file to trash after restarting

**Comment by bryanpedini** [comment]
> Also, it asks if I want to send the file to trash after restarting

Maybe your installation doesn't keep the "do not ask me again" setting persistent (if the "do you want to send it to trash instead?" question was not displayed before and after a restart it is, and I understood correctly).
Which OS do you `codium` on?

**Comment by finzzz** [comment]
Same problem, I have disabled `Explorer: Confirm Delete` in the setting.

**Comment by The-CodeNinja** [comment]
> Which OS do you `codium` on?
I'm on a debian machine

**Comment by The-CodeNinja** [comment]
@finzzz will try that! Thx

**Comment by bryanpedini** [comment]
strangely enough I had this issue on Debian w/ KDE, but (after bricking GRUB 'cause I accidentally overwritten my Linux disk instead of flashing a Raspberry SD card) now that I am on Linux Mint (tho I don't have all the plugins and settings I had before) but I don't see this issue popping up, so... dunno 🤷🏻

**Comment by bryanpedini** [comment]
@finzzz:
> FYI, I'm using KDE Plasma.

May at this point be a Plasma integration issue, rather than *just* a `codium` issue?

**Comment by finzzz** [comment]
@bryanpedini probably. I haven't tried that with other distributions. But regardless, it would be great to have it fixed.

**Comment by bryanpedini** [comment]
If somebody could try to replicate it on a reproduceable state like in VM with both KDE Plasma and Gnome/Mate for example (also in VM), we could all track this down quicker, I think.
Sorry in advance if I'm proposing something I haven't the time to do by myself (or haven't done already), I'm currently live migrating a server this weekend so no time at all even for beginning to think to do something else...
