### ISSUE TITLE
Alfred workflow for VSCodium

### ISSUE THREAD

**Issue by pat-s** [VSCodium/vscodium#557]
In case some Alfred users (macOS) are using this great project, I created an [Alfred workflow](https://github.com/pat-s/alfred-open-with-vscodium) for VSCodium.

(If such promotion is undesired, feel free to delete the issue.)

**Comment by paulcarroty** [comment]
Cool, maybe worth it to add Readme PR?

**Comment by stripedpajamas** [comment]
Feel free to make a PR to the readme, maybe in a "related projects" section or something.
