### ISSUE TITLE
"Python: Create new blank Jupyter notebook" shows a blank editor in VSCodium 1.51.0. "Uncaught Error: An instance of the VS Code API has already been acquired"

### ISSUE THREAD

**Issue by kirisakow** [VSCodium/vscodium#558]
OS: Ubuntu 20.10
VSCodium version: `1.51.0`
Installed with Snap

1. Started getting this issue right after updating to `1.51.0` earlier today on calling the `Python: Create new blank Jupyter notebook` command.

2. Ran `codium --verbose | grep -Ei 'warning|error|exception'`

3. Noticed the `Uncaught Error: An instance of the VS Code API has already been acquired` error message.

4. Looked it up on the web. As it happens, this is a VSCode issue already reported on 27 October: https://github.com/microsoft/vscode-python/issues/14535

**Comment by kirisakow** [comment]
### Temporary solution
1. Install VSCodium 1.50.1 as a portable app
2. Do not update it, even when it is suggested

**Comment by Maulorian** [comment]
What is vscodium ?

**Comment by najum98** [comment]
I have installed vs codium through snap, it got automatically updated and after that, notebooks are not working in it, they opens and then blank screen appears with no other response

**Comment by kirisakow** [comment]
@najum98 Try the temporary solution suggested above

**Comment by jagdevyadav** [comment]
Already existing jupyter notebook "shows blank screen in vs codium 1.51.0" since I have updated it on Monday November 9, 2020 morning Indist IST time.

**Comment by kirisakow** [comment]
@jagdevyadav Indeed, the same bug affects existing IPython Jupyter notebooks, too. Try the temporary solution above

**Comment by IhorLitvinov** [comment]
`sudo snap revert codium` has helped me (codium  1.50.1   rev91)

**Comment by najum98** [comment]
> `sudo snap revert codium` has helped me (to codium 1.50.1 rev91)

Yes this worked for me, but as @kirisakow mentioned its a temporary solution, VS Codium should fix its latest update

**Comment by kirisakow** [comment]
Problem has been fixed in [v.1.52.1](https://github.com/VSCodium/vscodium/releases/tag/1.52.1)
