### ISSUE TITLE
GTK designer plugin?

### ISSUE THREAD

**Issue by Shadowblitz16** [VSCodium/vscodium#560]
I created an issue on the vs code repo but I am afraid it might become proprietary with the way MS implements it.
I suggest that a quality GTK designer plugin be made to work with both vs codium and vs code so that developers can easily make GTK apps on Linux.

There really is no option out there besides gnome builder that can both support a wide range of languages with good development tools and that supports a gtk designer.

**Comment by GitMensch** [comment]
This issue tracker is for vscodium "a repository of scripts to automatically build Microsoft's vscode repository into freely-licensed binaries with a community-driven default configuration", not about new extensions to vscode. But I actually don't know a place where to ask other than the main vscode repo.
I guess it boils down to [create an extension on your own](https://code.visualstudio.com/api), possibly with some extension author that already has some knowledge in both vsix and in GTK. As this is about a new extension it doesn't match to the repo and is closed to keep the focus, but why do you want to replace gnome builder if it works well for you?

**Comment by Shadowblitz16** [comment]
@GitMensch I was under the assumption gnome builder was still in development

**Comment by GitMensch** [comment]
Hm, and to create a completely new extension would be different?

**Comment by Shadowblitz16** [comment]
@GitMensch  I'm talking about the IDE not the extension.
