### ISSUE TITLE
Follow operating system config location standards

### ISSUE THREAD

**Issue by Siilwyn** [VSCodium/vscodium#561]
It would be great if VSCodium followed the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). Instead of placing the config directory `.vscode-oss` in the home directory it should be placed in the OS specific appropriate directory. Getting the correct directory is easy with a module like [env-paths](https://github.com/sindresorhus/env-paths).

This, among other things, allows a user to specify a directory in which they want all applications to look for their user configurable setting files and keep their home directory clean.

**Comment by stripedpajamas** [comment]
Agreed, it would be great :smile: But since the config location is a build-time setting (inside the `product.json` file), we don't have too much freedom to change it without messing with VSCode internals. As such, I recommend moving this issue to https://github.com/microsoft/vscode/issues.

**Comment by magnus-ISU** [comment]
Don't think it should be reopened, I agree that upstream should be what fixes this.

However, it should be noted that running vscodium (or Visual Studio Code) with the `--extensions-dir` flag does everything you would want, if you care about this, and write-protect your home directory like I do.

[Here](https://github.com/microsoft/vscode/issues/329) is the relevant issue. I do not expect this functionality to change.

**Comment by SafwanLjd** [comment]
> Don't think it should be reopened, I agree that upstream should be what fixes this.
> 
> However, it should be noted that running vscodium (or Visual Studio Code) with the `--extensions-dir` flag does everything you would want, if you care about this, and write-protect your home directory like I do.
> 
> [Here](https://github.com/microsoft/vscode/issues/329) is the relevant issue. I do not expect this functionality to change.

But the .vscode-oss directory doesn't just contain extensions, it has other files (like argv.json); thus, moving the extensions alone won't allow you to get rid of .vscode-oss and it will keep getting created even if you delete it

**Comment by magnus-ISU** [comment]
Yeah I'm an idiot lol. I write-protected code and it crashed, then I ran with that flag and it didn't crash so I assumed it was good when it isn't.
