### ISSUE TITLE
Deb repository not up to date

### ISSUE THREAD

**Issue by dyegoaurelio** [VSCodium/vscodium#562]
**Describe the bug**
Deb repository still on 1.50.1

![image](https://user-images.githubusercontent.com/42411160/98940355-9e6e7e80-24c9-11eb-8eb1-dddd5de9be50.png)

**Desktop (please complete the following information):**
 - OS: Pop!_Os 20.10
 - Architecture  x64

**Comment by cas--** [comment]
Afraid this is the wrong place to report this issue. Issues with debs repository are to be made on [deb/rpm repo](https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/). However have you updated your apt config as per: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/issues/36#note_395793123

**Comment by dyegoaurelio** [comment]
it worked, thanks
