### ISSUE TITLE
Unable to install Swaggerhub VSCode plugin

### ISSUE THREAD

**Issue by pc-magas** [VSCodium/vscodium#563]
I attempted to install the following plugin https://marketplace.visualstudio.com/items?itemName=SmartBearSoftware.vscode-swaggerhub into codium. I tried the following:

1. I pressed Ctrl+P
2. I pasted from website `ext install SmartBearSoftware.vscode-swaggerhub`

I also installed vscode from the oficcial snap package and I tries the steps above. The plugin was available for installation.

For better clarification I provide some screenshots as well:

In Vscodium I see the following screen following the steps above
![Unable to install Plugin in Vscodium](https://user-images.githubusercontent.com/1299750/99065940-d997ad00-25b0-11eb-961c-0528ce83863a.png)

Whilst in normal visual studio code (Microsoft Provided) it is found and listed as is:

![Visual Studio code](https://user-images.githubusercontent.com/1299750/99066124-211e3900-25b1-11eb-96e3-322e456ff745.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3
 - Architecture x64

**Codium Version:**
```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-12T00:31:42.540Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-52-generic snap
```

I noticed the bug in the following version as well:

```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-12T00:31:42.540Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-52-generic
```

**Comment by noonsleeper** [comment]
hey @pc-magas I think this is not a bug, codium use another marketplace see https://github.com/VSCodium/vscodium#extensions-and-the-marketplace

**Comment by pc-magas** [comment]
I think that too @noonsleeper I reckon I think I need to contact the openvsx registry's owners.
