### ISSUE TITLE
CPU Usage +25% in idle context

### ISSUE THREAD

**Issue by xe-nvdk** [VSCodium/vscodium#566]
**Describe the bug**
Working with the latest version, power consumption and CPU usage is triggered. Ver

Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-12T10:30:36.566Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**

1. Open the application
2. Open a .py file or another.
3. No edition or debugging state
3. CPU usage is triggered.

**Expected behavior**
No trigger +25% of CPU usage in an idle situation.

**Screenshots**
![vscodium-bug](https://user-images.githubusercontent.com/64545348/99147263-53d23b00-265e-11eb-9c28-d02fe3139d37.png)

VSCode

![vscodium-bug-2](https://user-images.githubusercontent.com/64545348/99147266-5896ef00-265e-11eb-8d57-d5467fd73ad6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Architecture x64
 - Version 20H2. Build 19042.630

**Additional context**
None. Thank you.

**Comment by enx1998** [comment]
Hi, 
I have a similar issue with 1.52.0 version on MacOS 11.1: VSCodium Helper use about 55% of CPU in idle.
Here the process explorer:
![image](https://user-images.githubusercontent.com/20546217/102607915-5f1af980-4129-11eb-9e78-5383ee4476cb.png)
Thanks Vincenzo

**Comment by enx1998** [comment]
Ok, launching without extensions the CPU use is ok, is there a way to show which extensions is so CPU hungry?

**Comment by dschuessler** [comment]
@enx1998 You can use the new extension bisect feature to troubleshoot extensions: https://code.visualstudio.com/updates/v1_52#_troubleshooting-extension-bisect

**Comment by enx1998** [comment]
Thank you so much @dschuessler, with to your suggestion I find that the extension vscode-html-css was the cause of problem and I find this issue https://github.com/ecmel/vscode-html-css/issues/185 that helped me to solve the problem

**Comment by stripedpajamas** [comment]
@xe-nvdk can you try launch VSCodium without extensions to see if your issue is similar to @enx1998 ?
