### ISSUE TITLE
Multiple extensions stopped working

### ISSUE THREAD

**Issue by jantomicky** [VSCodium/vscodium#567]
**Describe the bug**
Multiple extensions stopped working for me in the last few days/weeks:
1. **File Utils** (https://github.com/sleistner/vscode-fileutils), all commands fail with `Command {name} not found`. Developer tools error:
```
Activating extension 'sleistner.vscode-fileutils' failed: Cannot find module 'brace-expansion'
```
2. **PHP Debug** (https://github.com/felixfbecker/vscode-php-debug), the debugging never starts. The blue "loading bar animation" comes up, but disappears after a bit, silently. No messages, no developer tools errors.
3. **php-cs-fixer** (https://github.com/junstyle/vscode-php-cs-fixer), all commands fail with `Command {name} not found`.

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install said extensions.
2. Try to run commands they provide.
3. See errors, in the case of **PHP Debug** get no information as to what is (not) happening at all.

**Expected behavior**
Extensions work as expected.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Architecture: x86_64
 - Version: (Kernel) 5.8.18-1-MANJARO, all packages fully up to date as of 2020-11-14

**Additional context**
- I am using https://aur.archlinux.org/packages/vscodium-bin
- I am encountering the same issues with the Manjaro repo OSS build **code** (build from https://github.com/VSCodium/vscodium)
- I followed this https://wiki.archlinux.org/index.php/Visual_Studio_Code#Command_%22...%22_not_found to try and solve it, didn't work
- With the MS proprietary build (https://aur.archlinux.org/packages/visual-studio-code-bin) everything works as expected

I wasn't sure where exactly to submit this issue, so apologies in advance if this doesn't belong here.

**Comment by mseri** [comment]
The same is happening for me on MacOS Big Sur after VSCodium updated itself to the latest version

**Comment by Kein** [comment]
Pylance and Python extensions wont start either

**Comment by Kein** [comment]
PHPDebug never worked it seems: https://github.com/VSCodium/vscodium/issues/466

**Comment by stripedpajamas** [comment]
For `fileutils`, it looks like there was a bug regarding the missing `brace-expansion` module: https://github.com/sleistner/vscode-fileutils/issues/286. Should be fixed in latest version of the extension if I'm reading the comments right.

No idea with `php-cs-fixer` -- any other debug info available for that one?
