### ISSUE TITLE
Similar alternative for PowerShell

### ISSUE THREAD

**Issue by impredicative** [VSCodium/vscodium#570]
I don't know who else or where to ask, but is there a similar alternative just to [PowerShell](https://github.com/PowerShell/PowerShell), especially on Linux? I want a maintained PowerShell alternative, one without MS branding/telemetry/licensing. One would think it would be more foundational.

Granted, there exists [nushell](https://github.com/nushell/nushell) but it's not the same and it's not going to be cross-platform.

**Comment by stripedpajamas** [comment]
Unfortunately I'm not aware of any such project. Looks like making such a thing would be very similar to VSCodium :thinking:
