### ISSUE TITLE
Unable to search for or install extensions when I start VSCodium from the terminal

### ISSUE THREAD

**Issue by AhmedHalim96** [VSCodium/vscodium#571]
OS: Linux mint 20 Cinnamon
Terminal: alacritty
VSCodium version: 1.51.1 

So I found this weird "bug" if I start VSCodium from the terminal and try to search for an extension it gives me this error:
 "We cannot connect to the  Extension Marketplace at this time, please try again later"
 but if I opened VSCodium from the menu it works just fine.

**Comment by eonward37** [comment]
Seeing same error on Windows, VSCodium 1.52.1.
The Network panel shows a 503 after hitting https://open-vsx.org/vscode/gallery/extensionquery (seemingly triggered by accessing Extensions)
Any ideas?

**Comment by GitMensch** [comment]
Can't reproduce on Windows VSCodium 1.52.1 when starting from cmd.
