### ISSUE TITLE
/tools folder contains inno_updater.exe

### ISSUE THREAD

**Issue by alexhass** [VSCodium/vscodium#573]
While developing the MSI installer I found that VSCodium-win32-x64-1.51.1.zip contains a tools folder with inno_updater.exe and and vcruntime140.dll that could be required by the inno_updater, too.

I guess this files are not needed if the innosetup is not used? Can you remove this files from the ZIP package if only needed by innosetup, please?

**Comment by alexhass** [comment]
I just see I already removed this files from the vscode setup in past... still not clear to me why this is inside the ZIP files that are non-installer versions.

**Comment by alexhass** [comment]
Have you removed the file from zip?

**Comment by daiyam** [comment]
No, it's still there...

**Comment by daiyam** [comment]
Ok, those files are used to create the `.exe` and are excluded when creating the `.msi`. So there shouldn't be needed in the zip, I think...

**Comment by daiyam** [comment]
Done
