### ISSUE TITLE
There is a file called machineid

### ISSUE THREAD

**Issue by playgithub** [VSCodium/vscodium#576]
`~/.config/VSCodium/machineid`

Better to be without it? Or it is already fake?

Thanks

**Comment by stripedpajamas** [comment]
We haven't found any evidence that it's being used when telemetry is disabled.

https://github.com/VSCodium/vscodium/issues/292#issuecomment-557931449

If you find evidence to the contrary please share.

**Comment by playgithub** [comment]
ok, better if no this file
