### ISSUE TITLE
Embedded Webview depends on proprietary Chrome browser

### ISSUE THREAD

**Issue by s-daveb** [VSCodium/vscodium#577]
**Describe the bug**
If you don't have Google Chrome installed:
When using an extension that loads web content, if your VSCodium instance is set up to use the 'Embedded Webview' browser, you get the following error message, stating that the path to the Google Chrome executable was not found. 

![image](https://user-images.githubusercontent.com/2100425/99583131-100a6900-29b1-11eb-8339-7661448c33f5.png)

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
    - Counterpoint: Yes, this bug also happens in VSCode, but: shouldn't VSCodium search for Chromium rather than Chrome? Otherwise whats the point of stripping analytics out?

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Set your browser in settings to 'Embedded Webview'
2. Open a file or url from VScodium (perhaps through an extension) that would normally open in an external browser.
3. If you don't have Chrome installed, you get the error message in my screenshot above.

**Expected behavior**
- Maybe VSCodium should hardcode the path to the default Chromium install directory?
- Even better: allow users to override the path to the Webview engine via settings.json

**Screenshots**

![image](https://user-images.githubusercontent.com/2100425/99583131-100a6900-29b1-11eb-8339-7661448c33f5.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version  11.0.1 

**Additional context**
Please forgive me if you make it a policy not to change behavior like this for this project - I am just wondering if it's feasible and whether it's been brought to your attention.

**Comment by daiyam** [comment]
Any reference to Google Chrome can be found the source code of Visual Studio Code.
I think it's related to the extension that you are using or that Chrome is your default browser.
