### ISSUE TITLE
Vscodium update file is marked as a Fuery.C!cl by Windows defender.

### ISSUE THREAD

**Issue by Orangian** [VSCodium/vscodium#579]
**Describe the bug**
The file auto downloaded by VsCodium is marked by Windows defender as a virus. It is within my USRDIR\Temp\vscodium-update-system-x64\ and titled CodeSetup-stable-e5a624b788d92b8d34d1392e4c4d9789406efe8f.exe.tmp 

**Please confirm that this problem is VSCodium-specific**
- [X ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Launch VsCodium on a Windows 10 device
2. Have it not open and get an alert from Windows Security warning me of a virus
**Expected behavior**
To have VsCodium open as usual and not get an alert of a virus.

**Screenshots**
![image](https://user-images.githubusercontent.com/9283018/99915878-6ee32180-2cd4-11eb-9402-a7d849dbea7a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 2004 Enterprise
 - Architecture x86_64
 - Version 19041.572

**Additional context**
Never had a virus alert from VsCodium before, so this is a bit strange.

**Comment by stopspazzing** [comment]
```
Edition	Windows 10 Home
Version	20H2
Installed on	‎7/‎18/‎2020
OS build	19042.630
Experience	Windows Feature Experience Pack 120.2212.31.0

```

Same exact issue here.

**Comment by Orangian** [comment]
It might be pertinent for me to add that I was running enterprise edition, if that helps at all.

**Comment by Harry-2100** [comment]
Similar issue here.
![image](https://user-images.githubusercontent.com/74931762/100009996-e77ad880-2dcf-11eb-87f5-3004a73fd8c2.png)

Affected  items:
file: C:\Users\henni\AppData\Local\Temp\vscodium-update-system-x64\CodeSetup-stable-e5a624b788d92b8d34d1392e4c4d9789406efe8f.exe.tmp

**Comment by stripedpajamas** [comment]
Has happened before, despite using the same source code as the official VSCode builds. Most likely code signing the Windows binaries would help, but haven't dug into how to do that yet. There isn't much we can do on the build side of things; I recommend Windows users report a false-positive, if possible.

I'm also unable to get VirusTotal to find anything amiss: 

- VSCodium-win32-x64-1.51.1.zip: https://www.virustotal.com/gui/file/8c2c76a082c1a3f0ec0306b76d1fc8f3e34b727515c9102b8f2acca255aa8274/detection
- VSCodium-win32-ia32-1.51.1.zip: https://www.virustotal.com/gui/file/426b7b39f036b49853292fd351704e1298b85d7856a526ca705383cb842cea2e/detection
- VSCodiumSetup-x64-1.51.1.exe: https://www.virustotal.com/gui/file/3a721b136ae7df1a48c4e0cae7155f2ae9813c3cf3a92d2c22d16ce81659d484/detection
- VSCodiumSetup-ia32-1.51.1.exe: https://www.virustotal.com/gui/file/fd501df8807e9de30f7e499748f5f0e41607ec000df3522f4f8d2f0a08321d1a/detection
- VSCodiumUserSetup-x64-1.51.1.exe: https://www.virustotal.com/gui/file/2ec9d760a8a0c1d81d168fd3bebad340bc05e5ad97e6f24c7b659c6503ed1e7c/detection
- VSCodiumUserSetup-ia32-1.51.1.exe: https://www.virustotal.com/gui/file/380ed61d32e3d28c9caedd38d8031566c53363e2f845b1fb1bac74f77bd86f97/detection

**Comment by aaronhuggins** [comment]
I can report the same issue with Windows Security.
![image](https://user-images.githubusercontent.com/16567111/100023584-d8356400-2daa-11eb-82d3-e8cfce5369fa.png)

Will edit post when false positive successfully reported.
