### ISSUE TITLE
Install local extension with command line using --install-extension doesn't do anything

### ISSUE THREAD

**Issue by CoffeeCrew** [VSCodium/vscodium#580]
**Describe the bug**
If i am using the command line option "--install-extension <filepath>" VSCodium won't install the extension. Also other command arguments like --list-extensions won't work.

**Please confirm that this problem is VSCodium-specific**
- If i run the excact same command with VSCode it works.
code --install-extension myplugin.vsix                 <--- works
vscodium.exe --install-extension myplugin.vsix   <--- doesn't work

**Please confirm that the issue/resolution isn't already documented**
- I have searched through the Github issues and googled but didn't found anything related to my problem.

**To Reproduce**
1. Download a random extension
2. Run the command "vscodium.exe --install-extension path-to-your-plugin.vsix"
3. Look at your installed extensions, maybe even restart VSCodium, but it's not there
4. Run the same command with VSCode to verfiy that the command was right.

**Expected behavior**
I would have expect that the plugin gets installed.

**Desktop (please complete the following information):**
 - OS: Windows
 - Architecture x64
 - Version 1.51.1

**Comment by CoffeeCrew** [comment]
Ok we can delete this. The reason for this behaviour is that the "code" command doesn't start the VSCode.exe and the same is true for VSCodium. What you need to start is the codium inside the /bin folder. That one will accept the command line arguments.

**Comment by GitMensch** [comment]
No deletion, this actually should be more of an FAQ item.
