### ISSUE TITLE
"engine not set" error on Linux with Shift+Ctrl+Back Arrow

### ISSUE THREAD

**Issue by sonic2kk** [VSCodium/vscodium#581]
**Describe the bug**
When pressing Shift+Ctrl+Back Arrow to select a word (though it happens even a file is empty), VSCodium gives me an error saying "engine not set". This only appears to happen on Linux. I have tested with Visual Studio Code and VSCodium on macOS and Linux. The error is only present on Linux **and** only present on VSCodium. Reinstalling has not fixed the issue.

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open or create a new file
2. Press Shift+Ctrl+Back arrow, as if you were going to select a word (though the file can be empty)
3. See error

**Expected behavior**
If the file is empty, nothing should happen. If there is text in a file, the next chunk of text without a space should get highlighted.

**Screenshots**
![Error message](https://i.imgur.com/6YywwTT.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux w/ KDE Plasma
 - Architecture: x86_64
 - Version: 1.51.1, but has been present for months

**Additional context**
Issue is also present on my laptop running Arch Linux w/ KDE Plasma but is not present with the proprietary Visual Studio Code. It is also **not** present on either the proprietary Visual Studio Code or VSCodium on macOS. I am unable to verify if it is present on Windows. Reinstalling VSCodium has not resolved the issue.

**Comment by sonic2kk** [comment]
After browsing the "extensions" and disabling them one at a time, I discovered some strange plugin called "Dendron" was causing the issue. Specifically "dendron" and "Dendron Markdown Notes" - Having one or the other or both installed causes the issue. No idea what this is or why it fixed it, but removing it seems to have helped. Perhaps the Arch Linux vscodium package installs this extension, since it's also installed on my laptop where I rarely use VSCodium. It doesn't seem to be installed with Visual Studio Code on Linux or macOS.

That seems to be it fixed now!

**Comment by vishal590** [comment]
> After browsing the "extensions" and disabling them one at a time, I discovered some strange plugin called "Dendron" was causing the issue. Specifically "dendron" and "Dendron Markdown Notes" - Having one or the other or both installed causes the issue. No idea what this is or why it fixed it, but removing it seems to have helped. Perhaps the Arch Linux vscodium package installs this extension, since it's also installed on my laptop where I rarely use VSCodium. It doesn't seem to be installed with Visual Studio Code on Linux or macOS.
> 
> That seems to be it fixed now!

>you are damn right, thanks
