### ISSUE TITLE
[Bug] Downloading successful, but checksum doesn't match.

### ISSUE THREAD

**Issue by gitSaptarshi** [VSCodium/vscodium#583]
Tried to install vscodium through cli using the guide from https://vscodium.com/. But it shows the following problem and retries downloading the package again. I have tried the Fedora cli method. Here's a screenshot:
![Screenshot from 2020-12-09 10-04-10](https://user-images.githubusercontent.com/37685073/101585892-ba047080-3a06-11eb-874c-ba220b16a76c.png)
**VSCodium version**: `1.51.1-1605141277.el7`

**System Info**
- OS: **Fedora 33 (stable)**
- LSB Version:	:core-4.1-amd64:core-4.1-noarch
- Kernel: 5.8.11-300.fc33.x86_64
- DE: GNOME 3.38.2

**Comment by paulcarroty** [comment]
Already [fixed](https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/issues/30#note_431191545), please edit your config.
