### ISSUE TITLE
Update support for AppImage.

### ISSUE THREAD

**Issue by vitkrn** [VSCodium/vscodium#585]
This is my first time creating an issue, if I make any mistakes please point it out.

Clicking on the "Download update" notification on the gear icon downloads tar.gz of VSCodium when using an AppImage.

1. Use VSCodium appimage.
2. Check for updates from 'Help' menu,
3. Click on the gear icon and "Download update".
4. It downloads .tar.gz of the new version.

**Expected behavior**
AppImage of the newer version should be downloaded when using an AppImage.

**Desktop (please complete the following information):**
 - OS: openSUSE Leap 15.2
 - Architecture: x64
 - Version: 1.51.1

Also, I am using AppImageLauncher and it provides an update mechanism to update appimages using appimageupdate. VSCodium has this option in its context menu but it shows this:
```
Failed to check for updates:

Fetching latest release information from GitHub API
None of the artifacts matched the pattern in the update information. The pattern is most likely invalid, e.g., due to changes in the filenames of the AppImages. Please contact the author of the AppImage and ask them to revise the update information.
Fetching latest release information from GitHub API
None of the artifacts matched the pattern in the update information. The pattern is most likely invalid, e.g., due to changes in the filenames of the AppImages. Please contact the author of the AppImage and ask them to revise the update information.
ZSync URL not available. See previous messages for details.
```

**Comment by stripedpajamas** [comment]
Closing in favor of https://github.com/VSCodium/vscodium/issues/417

As mentioned in #417, it looks like we're creating the necessary zsync file, but not uploading it to the release.
