### ISSUE TITLE
rpm dependencies problem for armv7hl 

### ISSUE THREAD

**Issue by czhehua** [VSCodium/vscodium#588]
**Describe the bug**
rpm dependencies problem for armv7hl, cannot install.

**To Reproduce**
1. # rpm -ivh codium-1.52.0-1607733566.el7.armv7hl.rpm
2. error: Failed dependencies:
	libX11.so.6() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libXcomposite.so.1() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libXcursor.so.1() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libXdamage.so.1() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libXext.so.6() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libXfixes.so.3() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libXi.so.6() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libXrandr.so.2() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libXrender.so.1() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libXss.so.1() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libXtst.so.6() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libasound.so.2() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libatk-1.0.so.0() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libc.so.6() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libcairo.so.2() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libcups.so.2() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libdbus-1.so.3() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libdl.so.2() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libexpat.so.1() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libfontconfig.so.1() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libfreetype.so.6() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libgcc_s.so.1() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libgdk-x11-2.0.so.0() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libgdk_pixbuf-2.0.so.0() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libgio-2.0.so.0() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libglib-2.0.so.0() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libgmodule-2.0.so.0() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libgobject-2.0.so.0() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libgtk-3.so.0() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libm.so.6() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libnspr4.so() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libnss3.so() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libnssutil3.so() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libpango-1.0.so.0() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libpangocairo-1.0.so.0() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libpthread.so.0() is needed by codium-1.52.0-1607733566.el7.armv7hl
	librt.so.1() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libsecret-1.so.0() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libsmime3.so() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libstdc++.so.6() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libxcb.so.1() is needed by codium-1.52.0-1607733566.el7.armv7hl
	libxkbfile.so.1() is needed by codium-1.52.0-1607733566.el7.armv7hl

**Expected behavior**
armv7hl rpm install without dependencies problem.

**Desktop (please complete the following information):**
 - OS: CentOS 7.9 armv7hl (Raspberry Pi 3B)
 - Architecture armv7hl
 - Version 1.52.0

**Additional context**
In armv7hl, libX11 provides libX11.so.6, without (), so all the dependencies must without (), I guess.

**Comment by stripedpajamas** [comment]
Does MS VSCode install properly on your device?

**Comment by paulcarroty** [comment]
https://github.com/VSCodium/vscodium/pull/660
