### ISSUE TITLE
Need of a place to discuss about VSCodium

### ISSUE THREAD

**Issue by FirstWorldSlardar** [VSCodium/vscodium#59]
Hi guys!
Love the initiative, but struggle to find a place to discuss about it without opening issues(like a gitter channel or reddit sub, something like that). It would be nice to have one. Like the name and icon by the way.
Thank you  !

**Comment by stripedpajamas** [comment]
Just setup gitter here: https://gitter.im/VSCodium/Lobby. I'll put a badge on the readme 👍
