### ISSUE TITLE
Built-in Account Extension does not work

### ISSUE THREAD

**Issue by territory-sschneider** [VSCodium/vscodium#590]
**Describe the bug**
It seems like the built-in `vscode.microsoft-authentication` extensions does not work correctly.

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1.Start VSCodium
2. Try to login Microsoft/Github Account

**Expected behavior**
I can log in with Microsoft/Github account to sync settings.

**Screenshots**

![image](https://user-images.githubusercontent.com/73951566/102468547-f1e86500-4051-11eb-9e28-7a7ed62a7aac.png)

**Desktop (please complete the following information):**

VS Code version: VSCodium 1.52.1 (e0c124d19ea91a44e9d1c859fef24865a1e09353, 2020-12-17T09:15:31.680Z)
OS version: Linux x64 5.9.11-3-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx (8 x 1642)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 3|
|Memory (System)|13.61GB (2.32GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|qtile|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|qtile|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by daiyam** [comment]
seems to be related with the issue as #401

**Comment by territory-sschneider** [comment]
I don't think so because vscode.microsoft-authentication is a built-in extension and the extension for that doesn't seem to load properly at all, so you can't even generate an auth link.

**Comment by sks72589** [comment]
> I don't think so because vscode.microsoft-authentication is a built-in extension and the extension for that doesn't seem to load properly at all, so you can't even generate an auth link.

![image](https://user-images.githubusercontent.com/43265495/104142423-8e97eb80-53e1-11eb-888c-35f6df4f9046.png)

If someone reports any bug probably  Authors & developers should have a concern about that.

The issue still remains the same:
 OS: Parrot OS
Architecture: 64 bit.
Will be looking forward to getting this bug fixed.

**Comment by OliverBrotchie** [comment]
Do you think this issue will be fixed at some point??

**Comment by daiyam** [comment]
The `vscode.microsoft-authentication` extension won't be fixed since it's communicating with resources (MS Servers) that expect VSCode. Those resources haven't been released as an open source project. So that extension will need to be disabled.

But `vscode.github-authentication` has been patched to use PAT to make it more easily usable.

**Comment by jjangga0214** [comment]
I cannot login with GitHub account as well.
Because it just show this.
<img width="162" alt="스크린샷 2021-12-19 오후 11 45 17" src="https://user-images.githubusercontent.com/28584151/146679341-63472d1f-0fd8-4eb6-8715-1d5ac6768b52.png">
I cannot search `vscode.github-authentication` from the extension panel, either.
It just does not appear.

**Comment by daiyam** [comment]
@jjangga0214 Can you make a new issue? Your issue isn't related to the original issue. Thx
