### ISSUE TITLE
[VOTE] macOS BigSur app icon update

### ISSUE THREAD

**Issue by hazarek** [VSCodium/vscodium#591]
Will need a vote for big sur icons; will merge this as is for now.
_Originally posted by @stripedpajamas in https://github.com/VSCodium/vscodium/issues/582#issuecomment-748263074_

## Before/After
<img width="187" alt="codium_vote" src="https://user-images.githubusercontent.com/36481442/102703049-14a99200-427b-11eb-937c-416055f4b746.png">

I recommend the optimized version, there will be no visual difference.

ICNS file (629KB  1024x1024 144dpi Multiple size);
https://yadi.sk/d/mIlIdbAL2_gqpg

ICNS file (126KB 512x512 72dpi Optimized version);
https://yadi.sk/d/POI_637hLAgF0g

Yes 👍🏼 
No 👎🏼

**Comment by hazarek** [comment]
Also document icons need to be updated for Big Sur. if you want i can redesign and update them all.
https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/document-icons/

**Comment by hazarek** [comment]
@stripedpajamas The result of the voting is clear. It should be included in the next VScodium build so as not to wait long. If you are not sure about the result, you can pin it on the "Pinned issues"

**Comment by R0LA1mRifcF8yAkk** [comment]
Sorry, how do you mean Yes or No? In reference to what? Yes to what? No to what?

**Comment by stripedpajamas** [comment]
@R0LA1mRifcF8yAkk Yes (:+1:) is a vote to change the VSCodium logo (for Mac users) to the blue square icon in the picture. No (:-1:) is a vote to leave the logo as is (white circle). Note that the latest release still has a green logo but that will change upon next release to logo at the top of the README.

**Comment by hazarek** [comment]
> Sorry, how do you mean Yes or No? In reference to what? Yes to what? No to what?

👎🏼 keep the current icon for macOS Big Sur.
👍🏼 I want the new icon at the bottom for macOS Big Sur.

**Comment by R0LA1mRifcF8yAkk** [comment]
Right. Could there be more than just 1 alternative? How about one with white background but instead of the circle it'd have a square?

The blue background is an almost entirely different visual. Might be difficult to identify or get used to when OS-hopping.

**Comment by hazarek** [comment]
white is too bright for dark mode. but blue is not too dark for light mode. are you designer?

**Comment by R0LA1mRifcF8yAkk** [comment]
Well that's just the icon, not the whole app. I've plenty of light icons whilst using dark mode and I'm perfectly happy.

I once was a designer, yes. Is this relevant?

**Comment by hazarek** [comment]
i dont like this codium leaf icon. too detailes for an ablem. you can read old closed issues. i made this blue icon for dark mode users not for big sur or apple

**Comment by meduzen** [comment]
> white is too bright for dark mode. but blue is not too dark for light mode. are you designer?

Reverse opinion: white is too bright for **light** mode. There’s not enough contrast between the Dock and the icon background. 👼

![image](https://user-images.githubusercontent.com/9340937/103339061-ae91eb80-4a80-11eb-8d00-36b8a91c149f.png)

It’s an icon in the Dock, and macOS doesn’t allow to have dual icons depending on the color scheme, so it should not be a criteria to dismiss or validate an app icon.

**Comment by hazarek** [comment]
# Let’s Do Science!  - WCAG contrast check.

## My new blue emblem

- White tree on blue - [PASS](https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=3166CD)
- Blue background on light background - [PASS](https://webaim.org/resources/contrastchecker/?fcolor=3166CD&bcolor=FFFFFF)
- Blue background on dark background - [PASS](https://webaim.org/resources/contrastchecker/?fcolor=3166CD&bcolor=000000)


## Current round emblem.

- Cyan color of tree gradient on white circle - [FAIL](https://webaim.org/resources/contrastchecker/?fcolor=69BBEC&bcolor=FFFFFF)
  - <img width="228" alt="Ekran Resmi 2020-12-30 14 05 56" src="https://user-images.githubusercontent.com/36481442/103347732-dbf28f80-4aa8-11eb-9bb7-800229841a02.png">
- Blue color of tree gradient on white circle - [PASS](https://webaim.org/resources/contrastchecker/?fcolor=4D91E7&bcolor=FFFFFF)
- White background on light background - [FAIL](https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=FFFFFF)
- White background on dark background - [PASS](https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=000000) ( too bright for eyes )

**Comment by R0LA1mRifcF8yAkk** [comment]
> Reverse opinion: white is too bright for **light** mode. There’s not enough contrast between the Dock and the icon background. 👼

You can still see the icon, which is the important part, as opposed to the background. Apple has made a couple of similar icons, on Big Sur – Pages and Reminders. The background is white and the relevant part of the icon is very noticeable.

> Let’s Do Science! - WCAG contrast check.

The contrast checker tool is intended for text and UI icons. Neither of which is being discussed here.

**Comment by R0LA1mRifcF8yAkk** [comment]
> [...] macOS doesn’t allow to have dual icons depending on the color scheme [...]

Seeing as this is true, is this issue still valid?

The only merit this issue could provide, would be to provide the users with an alternate icon, as has been done before (#4, #472). A user has even created a small [script](https://github.com/chadlavi/vscodium-icon) for simpler substitution.

**Comment by stripedpajamas** [comment]
The vote looks pretty decisive and has been open for about a month. I will approve/merge a PR that replaces the Mac OS icon with the proposed icon.

**Comment by hazarek** [comment]
my related proposal https://github.com/VSCodium/vscodium/discussions/616

**Comment by paulcarroty** [comment]
why this issue is still pinned?

**Comment by trankov** [comment]
How to get back an old icon? This new one looks ugly and scaring for me. Sorry, but true ( Is there any way to do it?

**Comment by R0LA1mRifcF8yAkk** [comment]
Hey @trankov, I believe you'll find what you need in #472.

It's a sad state of affairs when every few months a single user decides to change the logo (!) of the app and the many users who are opposed to the change, are left high and dry.

This vote went down just like the other one — without much publicity beforehand or during. Just the users visiting this repo's issues (!) were able to voice their opinion.

I've marked a couple of my thoughts with an exclamation mark to highlight why this complaint exists.

**Comment by trankov** [comment]
Hello @R0LA1mRifcF8yAkk, thank you very much for your answer! 
I'm absolutely fine with changing an icon manually with every update. It's a free soft, and developers spending their personal time. I'm far from criticise them. The only thing I need is to find the old green logo with the Mobius strip (is it a Mobius strip?) I have no idea where to looking for it. In history of commits maybe.

**Comment by R0LA1mRifcF8yAkk** [comment]
@trankov it exists in the issues as well somewhere, search for "logo".

**Comment by trankov** [comment]
@R0LA1mRifcF8yAkk 
Thanks for advice, finally I've got it )
https://github.com/stripedpajamas/vscodium/raw/0a20f8159a5c6e29866a3df3b99c9bf84ff90fc9/src/resources/darwin/code.icns
