### ISSUE TITLE
Windows icon is low resolution

### ISSUE THREAD

**Issue by TheJaredWilcurt** [VSCodium/vscodium#601]
**Describe the bug**
`.ico` file for Windows is needed with different resolutions. Currently looks blurry/bad

**Please confirm that this problem is VSCodium-specific**
* [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
* [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install on windows

**Expected behavior**
pretty icon :)

**Screenshots**
![icons](https://user-images.githubusercontent.com/4629794/103696646-b6fc9180-4f6c-11eb-8189-64e299d0aedc.png)

**Desktop (please complete the following information):**
 * OS: Win
 * Architecture N/A
 * Version 1.52.1

**Comment by TheJaredWilcurt** [comment]
I'd be happy to do a PR for this if a high quality version of the logo is supplied (high resolution or vector). However the current codebase doesn't seem to have any reference to the new logo. All image files are related to the coral letter press.

**Comment by peter-fb** [comment]
The new old icon is blurry/fuzzy on Windows, at least on Windows 8.1.

![2021-02-07 09_59_40-](https://user-images.githubusercontent.com/7101417/107141771-5b3a7500-692b-11eb-8563-8ad0760dcb6d.png)

**Comment by hazarek** [comment]
@daiyam Daiyam can fix this. related PR https://github.com/VSCodium/vscodium/pull/618

**Comment by daiyam** [comment]
@hazarek The PR #618 doesn't touch that icon `code.ico` (`if [[ $name != 'code' ]]...`). Maybe the issue is maybe due to that the 48px icon is blank...

**Comment by peter-fb** [comment]
I converted the logo to a *.ico file that has several icon layer sizes, that fixed it. I've attached the icon.

[codium.zip](https://github.com/VSCodium/vscodium/files/5939513/codium.zip)

**Comment by daiyam** [comment]
I've updated the script to generate the icon (with all the sizes) based on the linux icon (same design). PR #633

@peter-fb Can you test if the generated icon is ok for you?

**Comment by hazarek** [comment]
> @hazarek The PR #618 doesn't touch that icon `code.ico` (`if [[ $name != 'code' ]]...`). Maybe the issue is maybe due to that the 48px icon is blank...

oh sorry, my mistake.

**Comment by peter-fb** [comment]
@daiyam I've used this icon to test, I hope that's the right one (I'm new to all of this):
https://raw.githubusercontent.com/VSCodium/vscodium/aec3519ea7387ba83a6d792bd35280e25a694fff/src/resources/win32/code.ico

This generated icon is OK.

**Comment by daiyam** [comment]
Ya, it's the one. Thx
