### ISSUE TITLE
Expand the VSCodium project to cover other M$ OS products?

### ISSUE THREAD

**Issue by Kein** [VSCodium/vscodium#602]
PowerShell Core  
Windows Terminal  

Both include telemetry enabled by default. Custom build usually either have it disabled or can disable. What about expanding the scope of original VSCodium project and incorporate a few more?

**Comment by stripedpajamas** [comment]
Also mentioned in #570. I think it's a great idea but I don't personally have time to do it. Happy to help out and/or bring the other projects under the VSCodium org as long as there's a dedicated maintainer.
