### ISSUE TITLE
Version 1.52.1 still contains the old logo

### ISSUE THREAD

**Issue by stefanos82** [VSCodium/vscodium#603]
I've just downloaded the latest available version for my GNU / Debian testing 64-bit and logo is still the old, but on master repository displays the good ol' looking logo that has been reverted on Nov 27, 2020, whereas the generated package was released on Dec 15, 2020.

![image](https://user-images.githubusercontent.com/1777466/103966109-df9cab00-5167-11eb-83c5-0fbe84580620.png)

**Comment by stripedpajamas** [comment]
This is expected. MS hasn't cut a release since the logo revert was merged.

**Comment by stripedpajamas** [comment]
It wasn't reverted in Nov (https://github.com/VSCodium/vscodium/commit/86f076f68cd5bc65befe01db5b14f3c645124112)

**Comment by stefanos82** [comment]
> It wasn't reverted in Nov ([86f076f](https://github.com/VSCodium/vscodium/commit/86f076f68cd5bc65befe01db5b14f3c645124112))

Then what's this?

![image](https://user-images.githubusercontent.com/1777466/104051401-becc6800-51f0-11eb-870c-22082ce562cf.png)

**Comment by daiyam** [comment]
From the PR #582, the logo was reverted on Nov 27 but the PR was merged on Dec 18.
