### ISSUE TITLE
Use of --no-sandbox in the .desktop file (the vscodium launcher)

### ISSUE THREAD

**Issue by mYnDstrEAm** [VSCodium/vscodium#604]
[After researching why I was not getting updates for versions higher than 1.34.0 on Debian10/KDE without getting any errors](https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/issues/50) I found that the .desktop file which is codium's launcher is changed to `/usr/share/codium/codium --no-sandbox --unity-launch %F` for the command and a green icon as a new icon.

I'd like to ask if the change to the command is really needed, how suboptimal it is and suggest changing it. I can still run vscodium sandboxed (with firejail) like this: `firejail --profile=/etc/firejail/vscodium.profile /usr/bin/codium` so it doesn't seem like the --no-sandbox is necessary. I think adding `--no-sandbox` should be avoided whenever possible.

**Should this be changed for VsCodium (if this is not changed by VS Code itself)?**

I can't run codium with firejail when pointing to the path of /usr/share (probably a firejail issue and not a problem of using /usr/share instead of /usr/bin) and that directory is mostly used for documentation instead of binaries but seems to be a good place to put cross-platform software(?)

This may be relevant: https://github.com/microsoft/vscode/issues/112311

And this may be relevant for another way to resolve potential problems circumvented by using --no-sandbox: https://github.com/laurent22/joplin/issues/2246#issuecomment-740126395

**Comment by Moltkex** [comment]
I use the appimage and the `--no-sandbox` flag ins't needed at all. Currently, running VSCodium-1.52.1-1608165473.glibc2.16-x86_64.AppImageon Debian 10 with KDE too.

**Comment by paulcarroty** [comment]
Not officially supported by VSCode yet: https://code.visualstudio.com/updates/v1_53#_progress-on-electron-sandbox
