### ISSUE TITLE
Community Forum

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [VSCodium/vscodium#605]
Sorry for asking this in form of an Issue. But I could not find any other channel for this.

I am looking for kind of an VSCodium user forum, where I can ask more experienced users some details.
A mailinglist would be OK also.

Any suggestions?

I am not interested in the VSCode community or any MS services. But I also looked there. ;) But even the MS VSCode website does not point to any forum like I am looking for.

**EDIT**: I also do not see StackOverflow as an option. Because my problems and questions about the use of VSCodium Interface/GUI. StackOverflow was not invented to replace product support for a big global software company like MS.

**Comment by stripedpajamas** [comment]
Sounds like a great idea and a good thing to have. I don't know of anything like it. If you/others start a forum I'd be happy to link to it from this project.

VSCodium might have a mailing list in the future, but it wouldn't be for user questions/support/discussion, but more for announcements like votes and release notes.

**Comment by hazarek** [comment]
@Codeberg-AsGithubAlternative-buhtz @stripedpajamas You can open the new Discussion feature of GitHub, it actually works like a simple forum.

**Comment by stripedpajamas** [comment]
Ok I turned on the discussion feature. We can try it out.
