### ISSUE TITLE
Blanck screen when trying open Jupyter Notebook

### ISSUE THREAD

**Issue by echidne** [VSCodium/vscodium#606]
**Describe the bug**
Jupyter notebook extension is no more working.
I obtain blanck screen when i try open new Jupyter notebook or existing one.
I have no error message
**Please confirm that this problem is VSCodium-specific**
- [x ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
- 

**Please confirm that the issue/resolution isn't already documented**
- [x ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there. => I did find a close bug report but it says that version 1.52.1 fixed it. I have that current version but the bug is real.

**To Reproduce**
1 )Do 'ctrl + shift +p' choose 'Python : Create a New Blanck Jupyter Notebook' => new 'untitled-x.ipynb' opened but stay blanck and impossible to write in.
2) Opening an existing jupyter noteboock => blanck screen after connecting the kernel

**Screenshots**
on VSCodium: 
![image](https://user-images.githubusercontent.com/65033881/104122340-d3ba1000-5344-11eb-91b2-e5533f4bd008.png)
![image](https://user-images.githubusercontent.com/65033881/104122371-efbdb180-5344-11eb-9ee6-0cf9037e164c.png)
On VSCode:
![image](https://user-images.githubusercontent.com/65033881/104122384-ffd59100-5344-11eb-9e69-678c9aa603a3.png)
![image](https://user-images.githubusercontent.com/65033881/104122397-0ebc4380-5345-11eb-8aa8-ea9ff2fba91a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 19041.685
 - Architecture [x64]
 - Version [e.g. 1.52.1]

**Additional context**

**Comment by jalemann** [comment]
For me uninstalling and reinstalling the Python extension did solve this. Problem didn't reoccur since.

**Comment by stripedpajamas** [comment]
@echidne have you tried uninstalling/reinstalling the Python extension as mentioned by @jalemann ?

**Comment by echidne** [comment]
@stripedpajamas I just tried it now and its working. Look like the update of VS codium corrupted somewaht the Python extension. previously i fixed it in downgrading VS Codium to 1.50.1. 
But for me the issue is still existing since you have to uninstall and reinstall Python to have your jupyter extension working. Something is not working correctly in the udpdate of Vs Codium
