### ISSUE TITLE
https://vscodium.com has the old homebrew install instruction

### ISSUE THREAD

**Issue by iGetSchwifty** [VSCodium/vscodium#607]
**Describe the bug**
When visiting https://vscodium.com I tried to install vscodium through 'brew cask install vscodium'

However, I was unable to do this.

'Error: Calling brew cask install is disabled! Use brew install --cask instead'

The github documentation is updated but not the website.

**To Reproduce**
Go to the install section of https://vscodium.com

**Expected behavior**
'brew install --cask vscodium' should be on the website

**Comment by stripedpajamas** [comment]
Good catch; should be fixed by https://github.com/VSCodium/vscodium.github.io/pull/33. I just merged it and there's some caching, but website will reflect the change shortly.
