### ISSUE TITLE
debsums vscodium

### ISSUE THREAD

**Issue by OhioVR** [VSCodium/vscodium#619]
Dear VSCodium team,

I was doing a debsums command today and I found that 2 of your files fails the debsums command. To reproduce:

debsums vscodium

and I get a couple of "FAILED" responses with codium.desktop and codium-url-handler.desktop files from that package.

The files look innocent enough. This is the only package that is failing with debsums on my system after I fixed everything else. I hate to bother your team with such a trivial issue but it is something I'm curious about.

**Comment by stripedpajamas** [comment]
@paulcarroty would this have something to do with the repository? I'm not sure where debsums gets its source of truth.

**Comment by paulcarroty** [comment]
@stripedpajamas , for [sure](https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo#verification) and this is not a bug.

It will be better to create official vscodium key and sign all packages, but it's another story.
