### ISSUE TITLE
Link to your website in your GitHub repo

### ISSUE THREAD

**Issue by rugk** [VSCodium/vscodium#621]
You should link to your nice website https://vscodium.com/ in your GitHub repo.

It's not linked in the Readme if I see correctly, and IMHO you should also link it in the about-part:
![grafik](https://user-images.githubusercontent.com/11966684/105641143-cd6a7e80-5e82-11eb-9450-3144f2b57853.png)

**Comment by hazarek** [comment]
Also, what does the [32-bit-readme](https://github.com/VSCodium/vscodium/tree/32-bit-readme) branch do? The bottom of the website says it is open source, but there is no up-to-date repository. How can I make a pull request to the website? Also, the site does not support the dark theme.

![image](https://user-images.githubusercontent.com/36481442/105641468-2fcc7a80-5e95-11eb-9950-e5247c07d72e.png)

**Comment by stripedpajamas** [comment]
The website repo is here https://github.com/VSCodium/vscodium.github.io

**Comment by stripedpajamas** [comment]
Pretty sure all non-master branches of this repo can be deleted

**Comment by hazarek** [comment]
> The website repo is here https://github.com/VSCodium/vscodium.github.io

@stripedpajamas then this link is redirecting to the wrong address (https://github.com/VSCodium/vscodium). and Site is not synchronized with README.md.
![image](https://user-images.githubusercontent.com/36481442/105641468-2fcc7a80-5e95-11eb-9950-e5247c07d72e.png)

**Comment by rugk** [comment]
Don't really know what you talk about. This was about a link **from GitHub to the website**.

This is still not resolved.
Just go to https://github.com/VSCodium/vscodium and enter your website there.

**Comment by hazarek** [comment]
Why is a single person directing a project that received 11 thousand likes? I think an administrator team is needed.
