### ISSUE TITLE
No appimage for latest 1.53?

### ISSUE THREAD

**Issue by Moltkex** [VSCodium/vscodium#630]
Hi, just went to the releases page and noticed there is no appimage available for 1.53.0, is it going to be one?

**Comment by stripedpajamas** [comment]
Yeah the Linux x64 build is failing (which includes the AppImage).

**Comment by coxackie** [comment]
@stripedpajamas any ideas why Linux x64 build fails?

**Comment by stripedpajamas** [comment]
Yeah I think vscode updated their build dependencies. I am trying to get my fork to build by updating the build deps and will send PR when I have it working.

**Comment by madeddy** [comment]
> ... noticed there is no appimage available for 1.53.0 ...

Please change the issue title to include other variants. e.g. "Missing builds for 1.53"
