### ISSUE TITLE
Why vscodium is trying to connect with redirector.gvt1.com ?

### ISSUE THREAD

**Issue by undali** [VSCodium/vscodium#631]
I've installed codium 1.52.1 from release section (https://github.com/VSCodium/vscodium/releases/download/1.52.1/codium_1.52.1-1608165462_arm64.deb)

On start codium trying to connect with redirector.gvt1.com. Is it intentionally?

![vscodium](https://user-images.githubusercontent.com/18377097/107137087-32b67900-6933-11eb-956c-3521efd82de7.png)

**Comment by hazarek** [comment]
https://www.systemtek.co.uk/2017/08/what-is-gvt1-com/
https://www.reddit.com/r/linuxmint/comments/aszz9i/redirectorgvt1com_is_this_a_virus_or_not/

**Comment by stripedpajamas** [comment]
I have no idea. More investigation required.

**Comment by o-dka** [comment]
Redirection service used by google

**Comment by hazarek** [comment]
this is not normal. Is it valid for macos and windows?

**Comment by GitMensch** [comment]
Can you verify if version 1.52.0 has the same issue?

**Comment by wolczek** [comment]
The same issue is present in 1.54.3

It looks like the connection is initiated from electron spellchecker
https://github.com/electron/electron/blob/master/patches/chromium/feat_add_support_for_overriding_the_base_spellchecker_download_url.patch#L44

**Comment by daiyam** [comment]
Have you uncheck all the settings for `@tag:usesOnlineServices` or `Online Services Settings`?

**Comment by wolczek** [comment]
Yes, I had everything unchecked.

**Comment by GitMensch** [comment]
Rechecked:

The electron patch is still that way:

https://github.com/electron/electron/blob/184ac2b382e8324a0b3db1944fd17cdd6ccffff9/patches/chromium/feat_add_support_for_overriding_the_base_spellchecker_download_url.patch#L43-L44

It leads to an option to override the URL by a call to `SpellcheckHunspellDictionary::SetBaseDownloadURL`, which is only called by [`SetSpellCheckerDictionaryDownloadURL`](https://github.com/electron/electron/blob/184ac2b382e8324a0b3db1944fd17cdd6ccffff9/patches/chromium/feat_add_support_for_overriding_the_base_spellchecker_download_url.patch#L29-L31) and was added with https://github.com/electron/electron/pull/22382.

Both its use and override option is described at https://github.com/electron/electron/blob/44491b023ac2653538b7ac36bb73f3085a938666/docs/tutorial/spellchecker.md#does-the-spellchecker-use-any-google-services. But: that function is not called in upstream vscode and therefore if SpellcheckHunspellDictionary is used the default URL would be used.

Open next check: where is the SpellcheckHunspellDictionary used can this be disabled already.
