### ISSUE TITLE
Linux x64 builds?

### ISSUE THREAD

**Issue by drupol** [VSCodium/vscodium#632]
Hello,

I noticed that there is no Linux X64 builds in version 1.53.0.

Is there something we can do to help?

**Comment by madeddy** [comment]
A look into other recent issues would have answered this Q as well. #630

**Comment by drupol** [comment]
Hello, 

Obviously, I saw the issue before writing my own.

However, I'm not using AppImage on my distro, so I didn't think that it was the issue that I was looking for, and this is why I wrote the issue.

**Comment by madeddy** [comment]
> Obviously, I saw the issue before writing my own.

Sry, thought you overlooked this.

Anyway, linux builds are mentioned there as well so we have a info for both there. I asked the opener to change title to include other builds so this here _could_ go then. Your choice.
Greets
