### ISSUE TITLE
New logo is awful

### ISSUE THREAD

**Issue by sayem314** [VSCodium/vscodium#636]
Sorry to say that but white background in 2021 makes no sense. Also, the old logo was nice, why change that?

**Comment by peter-fb** [comment]
@sayem314 The "old" logo was actually the new one, the logo that's used now is the really old one. See this issue for details: https://github.com/VSCodium/vscodium/issues/636

And here's the pull request: https://github.com/VSCodium/vscodium/pull/582

**Comment by ralfbiedert** [comment]
I also think the new icon is objectively worse, the picture stolen from #635 outlines why: 

![107163167-aecdb280-696d-11eb-94b1-a99f1304dca8](https://user-images.githubusercontent.com/301288/107241305-2877a600-6a2b-11eb-8103-b53b52774081.png)

- The old, green icon is simple enough that it can be perceived as a single, coherent form given at icon dimensions. You can look at it and immediately grok it's the green "ring-thing".
- The new icon has too many fine details that get lost / aliased. In my task bar it looks like a white circle with blue cracks; rather than the coral shape depicted on the main page. I have to actively tell myself it's Codium.

**Comment by in-in** [comment]
The logo is not awful, but brings up bad associations for me :sob: 
![maxresdefault](https://user-images.githubusercontent.com/8797432/107244470-199aee80-6a3f-11eb-95b8-f8a9a8bacf0c.jpg)

**Comment by peter-fb** [comment]
@ralfbiedert is right, the current logo is problematic for icons in general, especially smaller ones.

Used like this it's OK:

![2021-02-08 17_38_34-Journal - VSCodium](https://user-images.githubusercontent.com/7101417/107251489-ae4c1f00-6a34-11eb-85df-323b89375cf3.png)

It's large enough there.

**Comment by peter-fb** [comment]
The smaller the icon size, the smaller the detail should be. Is it possible to make a version of the current logo with less detail for icons?

**Comment by stripedpajamas** [comment]
We've gone back and forth on the icon over the past 6 months (blue codium -> green mobius -> back to blue codium). I really don't think we'll be officially changing it again for a while; each change causes a huge upheaval. Please look into the previous issues in this repo that show how the icon can be changed locally.

**Comment by rdewolff** [comment]
The new one is amazing ;)

**Comment by workingJ** [comment]
The new one works!

**Comment by arnofly** [comment]
Design logo is part of my job and I am really sorry, but I think also that the new logo is quite awful and looks dated. The old logo was better and really more visible.

**Comment by HydroPlume** [comment]
I understand that a lot of people don't like the green icon, but I honestly can't stand the white coral one.  I was really happy when it was updated, and then really confused when it got switched back.  Is there no way to make both sides happy?

**Comment by tyteen4a03** [comment]
The new logo triggers mild phobia responses for me, whereas the old (green one) doesn't.

**Comment by daiyam** [comment]
For those who don't like the blue icon, the best option would be to create a new one.

**Comment by williamd1k0** [comment]
I like the blue logo, but the white background is very odd.
When the icon appears in the xfce panel or in the thunar context menu, it looks like an empty white circle...
The previous icon was at least simpler to identify.
