### ISSUE TITLE
Add Codium branding to the welcome screen

### ISSUE THREAD

**Issue by baco** [VSCodium/vscodium#639]
The VSCode editor has in its welcome page the branding of the editor, stating in a nice font face: “Visual Studio Code” and below that: “Editing evolved”.

VSCodium could take some of that and state, in similar fonts at least, the editor's name “VSCodium”, or “VS Codium”, or “Visual Studio Codium”; something of the sort.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to 'Help'
2. Click on 'Welcome'
3. The start page appears with no branding, just the start shortcuts

**Expected behavior**
Above the “Start” group of shortcuts, have some branding stating the name of the editor, “VSCodium” for instance.

**Screenshots**
![no_branding_welcome](https://user-images.githubusercontent.com/102958/107280877-ac378f80-6a37-11eb-9886-d0a14cec509e.png)

**Desktop (please complete the following information):**
 - OS: Debian testing
 - Architecture: amd64
 - Version 1.53.0

**Comment by hazarek** [comment]
Also , This icon is wrong.

![107280877-ac378f80-6a37-11eb-9886-d0a14cec509e](https://user-images.githubusercontent.com/36481442/107284630-259ea480-6a6f-11eb-97a5-742a7bc208c0.png)

This icon should have been there.

<img width="275" alt="Ekran Resmi 2021-02-09 00 36 40" src="https://user-images.githubusercontent.com/36481442/107284651-2d5e4900-6a6f-11eb-8d66-1cf42dd765f7.png">

**Comment by Moltkex** [comment]
The release notes for 1.53 reads "Welcome to the January 2021 release of Visual Studio Code" 
![image](https://i.imgur.com/xrNS7rJ.png)

**Comment by hazarek** [comment]
This is not limited to the welcome screen or the release screen. the entire help menu (all screens) same as vscode. URL links belong to VSCode

<img width="368" alt="Ekran Resmi 2021-02-09 04 42 28" src="https://user-images.githubusercontent.com/36481442/107304143-87700600-6a91-11eb-99f4-6a04f9afe257.png">

**Comment by baco** [comment]
Apparently is a matter of zooming, too small screen to display irrelevant information on the welcome screen like the branding.

Zooming out, one or several times, with `Ctrl`+`-` made it appear. Sadly the whole interface gets affected by the zooming out and makes most of the remaining text not suitable for reading on daily basis.
