### ISSUE TITLE
[question] Native Notebook API?

### ISSUE THREAD

**Issue by coxackie** [VSCodium/vscodium#642]
ok, first and foremost: this is not a bug, but a question.

 I am wondering whether there is any (hacky) way to have access to the native notebook API. I do understand that this is a feature only in insiders for the moment, but as vs-codium-insiders is not a thing (at least not yet), I wanted to ask whether there is any way to somehow access the proposed API, for example to be used in the jupyter notebook extension.

 I guess the question is: can the API be exposed in this build by some hacking method (for example, altering `product.json`), or is it the case that the "stable" build does not even contain the proposed API?

**Comment by daiyam** [comment]
The fastest solution would that you compile vscodium ([howto](https://github.com/VSCodium/vscodium/blob/master/docs/build.md)) with the following patch to use the main/dev branch of vscode:
```
diff --git a/get_repo.sh b/get_repo.sh
index 301efdf..9800f11 100755
--- a/get_repo.sh
+++ b/get_repo.sh
@@ -6,7 +6,7 @@ export LATEST_MS_COMMIT=$(echo $UPDATE_INFO | jq -r '.version')
 export LATEST_MS_TAG=$(echo $UPDATE_INFO | jq -r '.name')
 echo "Got the latest MS tag: ${LATEST_MS_TAG}"

-git clone https://github.com/Microsoft/vscode.git --branch $LATEST_MS_TAG --depth 1
+git clone https://github.com/Microsoft/vscode.git --branch main --depth 1

 # for GH actions
 if [[ $GITHUB_ENV ]]; then
```

**Comment by daiyam** [comment]
LOL, I've just seen that you've closed the issue...

**Comment by coxackie** [comment]
yes, sorry, so actually the latest 1.58 anyway supports native notebooks. Many thanks though!
