### ISSUE TITLE
MacOS archives are not signed

### ISSUE THREAD

**Issue by ssbarnea** [VSCodium/vscodium#643]
**Describe the bug**

Apparently the macos binaries are not properly signed. I tried both of them and none of them would start on Big Sur.

I should also mention that I do not see the point / difference between those to blends of builds.

https://github.com/VSCodium/vscodium/releases/download/1.53.2/VSCodium-darwin-x64-1.53.2.zip
https://github.com/VSCodium/vscodium/releases/download/1.53.2/VSCodium.x64.1.53.2.dmg

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**

**Expected behavior**
Be able to start the app.

**Screenshots**

![](https://sbarnea.com/ss/Screen-Shot-2021-02-15-15-12-37.75.png)

**Desktop (please complete the following information):**
 - OS: 11.2
 - Architecture x64
 - Version 1.53.2

**Additional context**

**Comment by hazarek** [comment]
@ssbarnea Signing is not required for open source software. because Apple signing is paid. You can allow it in your macos Security settings.

**Comment by ssbarnea** [comment]
While I do agree with others that Apple and other owners of more or less closed stores are making developer life harder, I do also think that the **main goal is security, and that applies to open-source as well**.

Non-profit organizations can request free developer program access, as documented on https://developer.apple.com/support/membership-fee-waiver/#:~:text=Apple%20Developer%20Program%20membership%20is,their%20annual%20membership%20fee%20waived. -- so we should not use the fee as an excuse for no signing our code. Even if the fee would not be waived, I am also sure that there are multiple open-source foundations which would have no problems sponsoring certification costs. 

Asking users to bypass system security protections in order to run pre-compiled binaries downloaded is a serious security risk, one that I am not longer willing to take. I do prefer to compile stuff from source using brew and have it locally signed instead of bypassing system security.

If we do not adapt to the reality, we may fail to make vscodium more popular and most people will go to vscode, which is signed, but that comes with some strings attached.

**Comment by hazarek** [comment]
vscode is signed but tracking you. i trust vscodium i don't trust vscode.

**Comment by iMonZ** [comment]
Any news here? I would very like to use it without tampering my security!

**Comment by iMonZ** [comment]
> @ssbarnea Signing is not required for open source software. because Apple signing is paid. You can allow it in your macos Security settings.

I would not recommend this to anyone!
This can reduce the security of your system.
It's like disabling the anti-virus software, so don't do that!

**Comment by daiyam** [comment]
@iMonZ You just have to authorize to run **that** application. It's an exception.

The waiver is for a `Non-profit organization` with `a tax ID/national ID`. So it can't apply for small open-source project like this one.

**Comment by iMonZ** [comment]
> While I do agree with others that Apple and other owners of more or less closed stores are making developer life harder, I do also think that the **main goal is security, and that applies to open-source as well**.
> 
> Non-profit organizations can request free developer program access, as documented on https://developer.apple.com/support/membership-fee-waiver/#:~:text=Apple%20Developer%20Program%20membership%20is,their%20annual%20membership%20fee%20waived. -- so we should not use the fee as an excuse for no signing our code. Even if the fee would not be waived, I am also sure that there are multiple open-source foundations which would have no problems sponsoring certification costs.
> 
> Asking users to bypass system security protections in order to run pre-compiled binaries downloaded is a serious security risk, one that I am not longer willing to take. I do prefer to compile stuff from source using brew and have it locally signed instead of bypassing system security.
> 
> If we do not adapt to the reality, we may fail to make vscodium more popular and most people will go to vscode, which is signed, but that comes with some strings attached.

Is it possible to replace the cask with a formula?
This could resolve the problem without any certificate

**Comment by iMonZ** [comment]
> @iMonZ You just have to authorize to run **that** application. It's an exception.
> 
> The waiver is for a `Non-profit organization` with `a tax ID/national ID`. So it can't apply for small open-source projects like this one.

Still, this is something that you shouldn't do

**Comment by daiyam** [comment]
> Still, this is something that you shouldn't do

If Apple was offering waiver even for small open-source projects (like some other companies), only then, I would agree with you :wink:

**Comment by daiyam** [comment]
+1

**Comment by apastuszak** [comment]
So, Apples' website says:

> **Eligibility**
> 
> You can request to have the annual Apple Developer Program membership fee waived if you’re a nonprofit organization, accredited educational institution, or government entity that will distribute only free apps on the App Store and is based in an eligible region. Apple will review your request and contact you to let you know if your request is approved.
> 
> Eligible regions: Australia, Brazil, Canada, China mainland, France, Germany, Israel, Italy, Japan, Mexico, South Korea, United Kingdom, United States.

This sounds like VSCodium would be eligible.

It's really a question os whether the developers want to go through the process of signing the Mac installers.

**Comment by GitMensch** [comment]
@daiyam as this project seems to be most-effected by you, could you please try https://developer.apple.com/support/membership-fee-waiver?

**Comment by GitMensch** [comment]
too bad, so would a sponsoring do the trick, if it is important enough for someone to do that?

**Comment by GitMensch** [comment]
Isn't this "just the (duplicated) bug" for the "todo issue" #324? In this case I'd suggest to close this as duplicate; otherwise - where is the difference?

**Comment by daiyam** [comment]
duplicate of #324
