### ISSUE TITLE
Please create a better icon.

### ISSUE THREAD

**Issue by nestg** [VSCodium/vscodium#645]
Hi, the new icon have not contrast and look as a big white circle, previous icon it was better, I hope that next version have a better icon, thanks.

**Comment by sayem314** [comment]
Some people think that the new icon is extraordinary with all whites so you must bear this for a while #636

**Comment by GitMensch** [comment]
Closing as duplicate of #636, please understand that some people liked the "newer" green one (also [lovely called](https://github.com/VSCodium/vscodium/issues/491#issuecomment-707460782) "green baby potty") and some the newer one. At least for the icon on a shortcut/docker/... you could explicit adjust it yourself.
See also #491 which also includes some icon sets.
