### ISSUE TITLE
codium: command not found

### ISSUE THREAD

**Issue by sayem314** [VSCodium/vscodium#646]
**Describe the bug**
After recent update I have noticed that command `codium .` no longer works. Note that everything was working as expected just before the update.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

![Screenshot 2021-02-18 20:44:03](https://user-images.githubusercontent.com/14138401/108373429-161b1a80-722a-11eb-8bd5-1a551c53495c.png)

**To Reproduce**
1. Install the latest version and try from the command line

**Expected behavior**
Should open vscodium on current folder

**Desktop (please complete the following information):**
 - OS: Pop!_OS
 - Architecture x64
 - Version 20.04 LTS

```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-12T00:32:13.710Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-7642-generic
```

**Comment by frezbo** [comment]
![image](https://user-images.githubusercontent.com/18496730/108482656-c5560100-72bf-11eb-8917-ebaecb7530e3.png)
I have the same issue on PoP!_OS.

OS info:

```bash
Linux <redacted> 5.8.0-7642-generic #47~1612288990~20.10~b8113e7-Ubuntu SMP Wed Feb 3 02:27:26 UTC 2 x86_64 x86_64 x86_64 GNU/Linux


NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

**Comment by Broyojo** [comment]
same issue, running popos 20.04
```bash
DISTRIB_ID=Pop
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Pop!_OS 20.04 LTS"
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**Comment by davidrhoderick** [comment]
Same issue, I didn't do anything but keep codium up-to-date and now I can't use it from the command line.

```
OS: Pop!_OS 20.04 LTS x86_64
Kernel: 5.8.0-7642-generic
Shell: bash 5.0.17
DE: Unity
WM: Mutter
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-12T00:32:13.710Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-7642-generic
```

**Comment by frezbo** [comment]
As a workaround this works `alias codium="/usr/share/codium/bin/codium"`

**Comment by luvicsoura** [comment]
I went with a shell function as a solution. I have tried an alias as suggested by @frezbo , but I needed the terminal to be freed after running the command ( that's why the following snippet is using `nohup` and outputing to `/dev/null`) and I also needed to be able to pass the options forward to the actual binary, which wouldn't have been possible to do if I were to alias the call with `nohup` and `&> /dev/null &`.

```zsh
code () {
	nohup /usr/share/codium/codium "$@" &> /dev/null &
}
```

**Comment by frezbo** [comment]
@luvicsoura  strange, for me the terminal was freed. Glad you have figured it out :muscle:

**Comment by greenfox1505** [comment]
I was using VSCode last week. `code` terminal command stopped working. I came over to VSCodium and added `alias code=codium`. This week `codium` broke terminal command. I believe this is an upstream bug.

**Comment by davidrhoderick** [comment]
Can confirm that the command needs to be aliased often.

**Comment by Grahf0085** [comment]
Just edit .bashrc to include fezbo's line: alias codium="/usr/share/codium/bin/codium" (if you use bash)

**Comment by reap2sow1** [comment]
I had a keyboard shortcut set for where I believe the codium binary previously existed (/usr/bin/codium), so in /usr/bin, I just made a symlink to where it now exists (/usr/share/codium/bin/codium). Easy peasy!

**Comment by daiyam** [comment]
When installing VSCodium 1.54 on Pop!OS 10.4, I get the link `/usr/bin/codium -> /usr/share/codium/bin/codium`. Not sure what happened...

**Comment by yashpalgoyal1304** [comment]
can anyone here post if this issue still exist on the latest codium 1.62.0 ?? i am on 1.61.2 and i did not face this issue.

**Comment by cavcrosby** [comment]
@yashpalgoyal1304 can't comment for version 1.62.0 but with trying version 1.62.3 on Pop!_OS 20.04, it seems to work ok (e.g. I can run codium from a terminal after installing it).

**Comment by yashpalgoyal1304** [comment]
been 4 weeks and the only input received is positive, so, i think this issue can be closed now. @sayem314
