### ISSUE TITLE
What is the minimal version of Mac OS X to run VSCodium?

### ISSUE THREAD

**Issue by GitMensch** [VSCodium/vscodium#648]
Visual Studio Code lists Mac OS X 10.10+ - is it the same for VSCodium? Did I miss some documentation or is this information missing in the docs currently?

Could VSCodium go back more (possibly at least with a manual build, when using the binary in homebrew needs a newer OS)?

**Comment by daiyam** [comment]
VSCode is using Electron 11 which requires macOS 10.10 [Supported Platforms](https://www.electronjs.org/docs/tutorial/support#supported-platforms). 
Electron 4 has dropped the support of macOS 10.9 due to Chromium [Release Notes](https://www.electronjs.org/blog/electron-4-0).

**Comment by GitMensch** [comment]
Thank you for this good answer, the main question is now answered.
The only open issue: should this be noted in our docs and if yes: where?

**Comment by hazarek** [comment]
> Thank you for this good answer, the main question is now answered. The only open issue: should this be noted in our docs and if yes: where?

You can add them to these documents and make a pull request.
here https://github.com/VSCodium/vscodium#supported-os
here https://vscodium.com/#install

@daiyam there is no _macOS 10.10_. It was named _macOS_ after 10.12

- OS X 10 beta: Kodiak - 13 September 2000
- OS X 10.0: Cheetah - 24 March 2001
- OS X 10.1: Puma - 25 September 2001
- OS X 10.2: Jaguar - 24 August 2002
- OS X 10.3 Panther (Pinot) - 24 October 2003
- OS X 10.4 Tiger (Merlot) - 29 April 2005
- OS X 10.5 Leopard (Chablis) - 26 October 2007
- OS X 10.6 Snow Leopard - 28 August 2009
- OS X 10.7 Lion (Barolo) - 20 July 2011
- OS X 10.8 Mountain Lion (Zinfandel) - 25 July 2012
- OS X 10.9 Mavericks (Cabernet) - 22 October 2013
- OS X 10.10: Yosemite (Syrah) - 16 October 2014
- OS X 10.11: El Capitan (Gala) - 30 September 2015
- macOS 10.12: Sierra (Fuji) - 20 September 2016
- macOS 10.13: High Sierra (Lobo) - 25 September 2017
- macOS 10.14: Mojave (Liberty) - 24 September 2018
- macOS 10.15: Catalina (Jazz) - 7 October 2019
- macOS 11: Big Sur - 12 November 2020

**Comment by daiyam** [comment]
@hazarek wtf man! We understand that it's the same thing. If you want to correct people, at least be right yourself (It's was Mac OS X from the beta to 10.7).

**Comment by hazarek** [comment]
> @hazarek wtf man! We understand that it's the same thing. If you want to correct people, at least be right yourself (It's was Mac OS X from the beta to 10.7).

You are right. I missed it while copying it from this site. https://www.macworld.co.uk/feature/os-x-macos-versions-3662757/

## from wikipedia

https://en.wikipedia.org/wiki/MacOS_version_history

Rhapsody Developer Release | Grail1Z4 / Titan1U |   | 32-bit PowerPC | 32-bit PowerPC | 32-bit | January 7, 1997[10] | August 31, 1997 | Un­known | DR2 (May 14, 1998)
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Mac OS X Server 1.0 | Hera |   |   |   |   | Un­known | March 16, 1999 | Un­known | 1.2v3 (October 27, 2000)
Mac OS X Developer Preview | Un­known |   |   |   |   | May 11, 1998[11] | March 16, 1999 | Un­known | DP4 (April 5, 2000)
Mac OS X Public Beta | Kodiak[12] |   |   |   |   | May 15, 2000[13] | September 13, 2000 | March 24, 2001 | N/A
Mac OS X 10.0 | Cheetah | 1.3.1 |   |   |   | January 9, 2001[14] | March 24, 2001 | 2004 | 10.0.4 (4Q12) (June 22, 2001)
Mac OS X 10.1 | Puma | 1.4.1 / 5 |   |   |   | July 18, 2001[15] | September 25, 2001 | 2005 | 10.1.5 (5S60) (June 6, 2002)
Mac OS X 10.2 | Jaguar | 6 | 32/64-bit PowerPC[Note 1] |   |   | May 6, 2002[16] | August 24, 2002 | 2006 | 10.2.8 (October 3, 2003)
Mac OS X 10.3 | Panther | 7 | 32/64-bit PowerPC |   |   | June 23, 2003[17] | October 24, 2003 | 2007 | 10.3.9 (7W98) (April 15, 2005)
Mac OS X 10.4 | Tiger | 8 | 32/64-bit PowerPC and Intel | 32/64-bit[Note 2] PowerPC[Note 3] and Intel |   | May 4, 2004[18] | April 29, 2005 | September 2009 | 10.4.11 (November 14, 2007)
Mac OS X 10.5 | Leopard | 9 |   | 32/64-bit PowerPC[Note 3] and Intel |   | June 26, 2006[19] | October 26, 2007 | June 23, 2011 | 10.5.8 (9L31a) (August 13, 2009)
Mac OS X 10.6 | Snow Leopard | 10 | 32/64-bit Intel | 32/64-bit Intel 32-bit PowerPC[Note 3] | 32/64-bit[20] | June 9, 2008[21] | August 28, 2009 | February 25, 2014 | 10.6.8 (10K549) (July 25, 2011)
Mac OS X 10.7 | Lion | 11 | 64-bit Intel | 32/64-bit Intel |   | October 20, 2010[22] | July 20, 2011 | October 2014 | 10.7.5 (11G63) (October 4, 2012)
OS X 10.8 | Mountain Lion | 12 |   |   | 64-bit[23] | February 16, 2012[24] | July 25, 2012[25] | September 2015 | 10.8.5 (12F2560) (August 13, 2015)
OS X 10.9 | Mavericks | 13 |   |   |   | June 10, 2013[26] | October 22, 2013 | September 2016 | 10.9.5 (13F1911) (July 18, 2016)
OS X 10.10 | Yosemite | 14 |   |   |   | June 2, 2014[27] | October 16, 2014 | August 2017 | 10.10.5 (14F2511) (July 19, 2017)
OS X 10.11 | El Capitan | 15 |   |   |   | June 8, 2015[28] | September 30, 2015 | September 2018 | 10.11.6 (15G22010) (July 9, 2018)
macOS 10.12 | Sierra | 16 |   |   |   | June 13, 2016[29] | September 20, 2016 | October 2019 | 10.12.6 (16G2136) (September 26, 2019)
macOS 10.13 | High Sierra | 17 |   |   |   | June 5, 2017 | September 25, 2017 | December 2020 | 10.13.6 (17G14042) (November 12, 2020)
macOS 10.14 | Mojave | 18 |   |   |   | June 4, 2018 | September 24, 2018 | TBA | 10.14.6 (18G8022) (February 9, 2021)
macOS 10.15 | Catalina | 19 |   | 64-bit Intel |   | June 3, 2019 | October 7, 2019 | TBA | 10.15.7 (19H524) (February 9, 2021)
macOS 11 | Big Sur | 20 | 64-bit Intel and ARM | 64-bit Intel and ARM[Note 4] |   | June 22, 2020 |   |   |
