### ISSUE TITLE
ANSI color sequences behave incorrectly in integrated terminal

### ISSUE THREAD

**Issue by Turysaz** [VSCodium/vscodium#651]
## Important context information
I have seen the same issue in _another_ integrated terminal in _another_ editor as well, so i do _not_ think that VSCodium is causing this, but rather some 3rd-party component that is being used by it.
However, since VSCode behaves correctly, there _must_ be something different with VSCodium, but I haven't found the difference so far.
I have literally copied the VSCode settings-json to VSCodium to make sure that it is not a bad user setting.

Nevertheless, I'll describe the problem with all detail.

## Description
The integrated terminal in VSCodium does not interpret all ANSI color sequences for resetting the attributes correctly.
The sequence for the reset is `\e[0m`. This should reset any font effects, and in VSCode, it does.
In VSCodium however, resetting the attributes also makes the font bold, which would correspond to `\e[1m`.
Sending `\e[1m` on the other hand does not seem to have an effect at all.

But it does not stop there, there is more weird behavior about the font weight.
For example, sending `\e[91m`, which is supposed to make the font red, does _also_ reset the font weight back to normal.
Other color codes do that as well, but I have not investigated which do.

## Demonstration
The following two screenshots show the issue. The first one shows the integrated terminal in VSCode, the second shows VSCodium.

I chose the character 'i' because I think it makes the difference between bold and normal font is easy to see.

### VSCode
![grafik](https://user-images.githubusercontent.com/16538627/108997039-6fa69d80-769f-11eb-847f-5d664ca069ce.png)
As expected:
* The 91-code enables red, but not bold.
* The 1-code enables bold, but does not reset the color.
* The 0-code resets everything.

### VSCodium
![grafik](https://user-images.githubusercontent.com/16538627/108997070-78976f00-769f-11eb-971e-4992567e6e88.png)
Weird:
* 91 enables red and resets the font weight.
* 1 does not have a visible effect.
* 0 resets the color, but makes the font bold.

The prompt is also bold in this screenshot. This is because the $PS1 that was set originally ended by `\e[0m` (in both screenshots) and I obviously cannot get rid of it without turning everything red...
I have tried with other $PS1-values, thought, this **does not cause the problem** for sure.

### Workaround
To have a non-bold font weight, I have (successfully) set
```json
"terminal.integrated.fontWeightBold": "normal"
```
which removes _any_ bold font. This makes the problem less annoying, but it is obviously not a real solution.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
- [x] I have double-checked that the version numbers of VSCode and VSCodium match.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
* Select `bash` as the shell for the integrated terminal. (I use the `bash.exe` that comes with Git4Windows.)
* Execute the sequence
```bash
red="\e[91m"
reset="\e[0m"
bold="\e[1m"
echo -e "${red}i ${bold}i ${reset}i ${red}i ${reset}i ${bold}i"
```

**Expected behavior**
The `\e[0m` code does reset the font weight, the `\e[91m` code (and any other color code) does not. `\e[1m` does set the font bold.

**Screenshots**
see above.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Architecture x64
 - Version
```text
Version: 1.53.2 (system setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-12T00:28:15.302Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Additional context**
see at the top of this issue.

**Comment by daiyam** [comment]
@Turysaz Can you provide your tests in text?

**Comment by Turysaz** [comment]
sure.

```bash
red="\e[91m"
reset="\e[0m"
bold="\e[1m"
echo -e "${red}i ${bold}i ${reset}i ${red}i ${reset}i ${bold}i"
```

**Comment by Turysaz** [comment]
I just checked if I can still reproduce it and - surprise! - the issue seems to be gone now. Apparently, something has changed, although I do not know what it was. Therefore, I'll close the issue.
