### ISSUE TITLE
I can't install Extensions from the Extensions Tab

### ISSUE THREAD

**Issue by ghost** [VSCodium/vscodium#652]
**Describe the bug**
If I want an extension, I can see it in VSCode marketplace, but if I search in Codium, it says it's not available. Not all extensions have this problem, few has like "pomodoro-timer", "vscode-pets", etc. This make me manually install Extension (VSIX) and I have to look in the web every time for any updates. Or will it check for updates automatically.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to 'Extensions tab'
2. Type **vscode-pets** and it will say not available. You can refer the marketplace too.

**Expected behavior**
I don't exactly want Codium to have all extensions inside it unless Codium checks for updates for extension whcih was manually install. If it doesn't check, then this is a problem for me, and also to swirch back to VS-Code.

**Desktop (please complete the following information):**
 - OS: Zorin Lite 15.3
 - 64 Bit
 - Version : 1.53.2-1613089951 (according to the command `sudo apt show codium`)

**Comment by daiyam** [comment]
@superkevin07 It's due to license limitation. Read the [`readme`](https://github.com/VSCodium/vscodium#extensions-and-the-marketplace) for more informations.

**Comment by pmahend1** [comment]
You should ask the creator of the extension/s to release it for VS Codium as well. It ls literally 2 lines of code if it is CI.

**Comment by paulvi** [comment]
@pmahend1 

What exact 2 lines?
I think that should be in README or on https://vscodium.com/ saing that vscodium is using https://open-vsx.org/
and because Microsoft limits its marketplace usage to Microsoft products, so authors should care to release to alternative registries as well.

**Comment by daiyam** [comment]
@paulvi It's on the README

**Comment by paulvi** [comment]
indeed, then this issue should be closed.
