### ISSUE TITLE
codium consumes 100% CPU even with --disable-extensions

### ISSUE THREAD

**Issue by boskamp** [VSCodium/vscodium#653]
This is a fresh install of codium from https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs/ on Ubuntu 16.04.

Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-12T00:32:13.710Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 4.4.0-36-generic

When starting up this version from bash in my home directory as working directory, it starts consuming 100% CPU immediately. This does not improve when launching with --disable-extensions, as shown in the screenshot attached.

When installing vscode via snap, in contrast, and running that, CPU load rarely raises above 5%.

What's wrong?

![codium](https://user-images.githubusercontent.com/4026819/109283134-b078f080-781e-11eb-9df5-6c8b4b5e3d7c.png)

**Comment by neurofreak-alt** [comment]
I've the same situation.

**Comment by paulcarroty** [comment]
@neurofreak-alt create new issue with logs.
