### ISSUE TITLE
[MAC] Install codium command in PATH replaces code 

### ISSUE THREAD

**Issue by pmahend1** [VSCodium/vscodium#654]
**Describe the bug**
[MAC] Install codium command in PATH replaces code

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
Yes

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.
Yes

**To Reproduce**
- Cmd+Shift+P
- Install `codium` command in PATH
- If prompts for permission for running osa script , click Yes 
- go to command line
- type `codium` enter - opens vscodium 
- type `code`  and hit return  - opens vscodium

**Expected behavior**
`code` should open **Visual Studio Code** and not **Codium**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS, Ubuntu 16.04, etc] Mac OS Big Sur
 - Architecture [e.g. x64, ia32, arm64] x64 
 - Version [e.g. 1.33.0] 11.1

**Additional context**

**Comment by daiyam** [comment]
@pmahend1 The PR #655 is fixing the issue.

**Comment by daiyam** [comment]
@pmahend1 Can you run the following commands?
- `ll /usr/local/bin/codium`
- `ll /usr/local/bin/code`
- `which code`

**Comment by pmahend1** [comment]
@daiyam since it was interfering with usage of Code I hard uninstalled it.
Just reinstalled to check if the issue persists.
I do not see issue anymore.

`codium` as linked tp `/Applications/VSCodium/Contents/....vscodim.app` and `code` is linked to  `/Applications/Visual Studio Code/Contents/....code.app`

I do use brew but I had not installed it through brew since it auto-updates.
Thanks for taking time to work on this issue.
