### ISSUE TITLE
Open multiroot Workspace from the command line

### ISSUE THREAD

**Issue by iaeiou** [VSCodium/vscodium#656]
Hi there,

**Objective**: open a multiroot Workspace from the command line.  
It [works with Vscode since 2017](https://github.com/microsoft/vscode/issues/29809) but not with `Vscodium`

- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open a terminal and run `codium myWorkspace.code-workspace`

**Expected behavior**
`Vscodium` should open and apply the settings in `myWorkspace.code-workspace`

**What happens instead**
`Vscodium` open and displays _the content of the file_ `myWorkspace.code-workspace`

**Desktop:**
 - OS: Debian
 - Architecture amd64
 - Version: 10 - Buster

**More details** (from the `Help → About` menu)
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-12T00:32:13.710Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 4.19.0-14-amd64

**Comment by iaeiou** [comment]
It works with `codium -r myWorkspace.code-workspace`

If you want to use this command line in a Linux Desktop launcher, you need to use the complete path (don't use `~/` but `/home/you/`)

**Comment by netizen-ais** [comment]
We're still tied (AFAIK) to this fixed .code-workspace extension. I'd love a command line like `codium --open-workspace-from-file myfile.myrules`

**Comment by GitMensch** [comment]
> It works with `codium -r myWorkspace.code-workspace`

and at least on win32 it also works with `vscodium.exe myWorkspace.code-workspace`, so I'm closing this issue as "magically solved".
