### ISSUE TITLE
Different Menubar Icon

### ISSUE THREAD

**Issue by dan-wenger** [VSCodium/vscodium#657]
**Describe the bug**
On Windows, the icon next to the menubar looks different than the app icon and the start page icon. 

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
On my machine there are no steps to reproduce, I just opened VSCodium and it was there. 

**Expected behavior**
I guess the icon should be the same as used in other places...?

**Screenshots**
![image](https://user-images.githubusercontent.com/18039819/109388814-b0095400-7909-11eb-8882-eb13c5fc6658.png)

**Desktop (please complete the following information):**
 - OS: Windows_NT 
 - Architecture x64 
 - Version 10.0.18363

**Additional context**
I did some googling, the issue seems to have been addressed already ([#104](https://github.com/VSCodium/vscodium/issues/104)) but that's quite some time ago. Is it better to reopen that one instead of opening a new issue here? Sorry for asking, this just is my first bug report and I'm not sure if I'm doing this right^^ Any tips for the next time appreciated!

**Comment by peter-fb** [comment]
I've found a workaround:

Settings > Window > Title Bar Style = native

It's best to use a light theme for it, though.
