### ISSUE TITLE
32-bit Windows packages.

### ISSUE THREAD

**Issue by JL2210** [VSCodium/vscodium#66]
I believe that Windows and Wine users will be happy if we provide 32-bit Windows packages. Any suggestions?

**Comment by pavanagrawal123** [comment]
I'd be willing to work on this if wanted :)

**Comment by JL2210** [comment]
Thank you. That would be much appreciated.

**Comment by Xandernardo** [comment]
Just what I was looking forwards too, as in my work I only have access to a Win7 x86 machine

**Comment by JL2210** [comment]
@pavanagrawal123 Have you started work yet?

**Comment by Thilas** [comment]
@pavanagrawal123, any progress on a 32-bit release? Thanks!

**Comment by stripedpajamas** [comment]
@JL2210 @Xandernardo @Thilas I set up 32-bit Windows builds but can't test them myself. The build process went smoothly. I'll close this out and if anyone has any issues using them we can open up a new issue.

**Comment by Thilas** [comment]
Thanks @stripedpajamas! I quicly tested it and it seems alright to me. VSCodium chocolatey package has also been updated in order to provide this 32-bit version as long with the existing 64-bit one.
