### ISSUE TITLE
RPM for Armv7 won't install on Fedora 33 (for armhfp)

### ISSUE THREAD

**Issue by gbraad** [VSCodium/vscodium#661]
Hi, I have tried to install the Armv7 release of both code as codium on my Fedora 33 installs (on an Arm rockchip based device), but for some reason it won't pull in dependencies/nothing is satisfied.  Forcing the install with nodeps or unpacking the tarball will result in a segfault when trying to run. What is this package meant for?

Note; I have no issues running the release for aarch64 on another device

**Comment by gbraad** [comment]
#118016

**Comment by paulcarroty** [comment]
EOL Fedora 33
