### ISSUE TITLE
does not match sortcut key with vscode. 

### ISSUE THREAD

**Issue by jakbin** [VSCodium/vscodium#662]
vscodium sortcut keys does not match with vscode. and also some sortcut does not working in vscodium. like :- "copy line down " default sortcut key is not  working. please make sortcut keys as vscode if possible.

**Comment by alt-art** [comment]
to copy line down you have to press Shift+Ctrl+Alt

**Comment by jakbin** [comment]
> to copy line down you have to press Shift+Ctrl+Alt

But it's not working.

**Comment by daiyam** [comment]
@jakbin Can you make a screenshot like: 
![Screenshot](https://user-images.githubusercontent.com/587742/112324701-5818ff80-8cb3-11eb-84a0-5147c276300c.png)

**Comment by daiyam** [comment]
@jakbin On Windows, for both VSCode and VSCodium, the shortcut is `Shift+Alt+DownArrow`.

**Comment by jakbin** [comment]
> @jakbin On Windows, for both VSCode and VSCodium, the shortcut is `Shift+Alt+DownArrow`.

I am using parrot os Nowdays.
In parrot os vscodium shortcut keys not working. Like :- copy line down shortcut key.

**Comment by jakbin** [comment]
![Screenshot at 2021-03-24 19-55-48](https://user-images.githubusercontent.com/65591973/112327682-a5a96280-8cdb-11eb-8360-20dd8ddcc0d4.png)

As you can see here copy line up key is (ctrl + shift + alt + up arrow) . buts its not working.

**Comment by daiyam** [comment]
When editing the shortcut, can you reproduce the keybinding? 
Or maybe try https://code.visualstudio.com/docs/getstarted/keybindings#_troubleshooting-keybindings

**Comment by daiyam** [comment]
What was the solution?

**Comment by jakbin** [comment]
Change key binding of shortcut keys
