### ISSUE TITLE
No respect to extensions settings in VSCodium

### ISSUE THREAD

**Issue by Kein** [VSCodium/vscodium#663]
Noticed this while profiling telemetry bullcap from VSCode and then decided to test VSCodium too:
![image](https://user-images.githubusercontent.com/623756/109851774-1d4c1a80-7c65-11eb-9229-d756c501224d.png)

This happens every X days (specific value unknown) when I start VSCodium cold. `settings.json` is equal for both:

```json
    "workbench.settings.enableNaturalLanguageSearch": false,
    "workbench.enableExperiments": false,
    "settingsSync.keybindingsPerPlatform": false,
    "update.showReleaseNotes": false,
    "json.schemaDownload.enable": false,
    "extensions.autoCheckUpdates": false,
    "extensions.showRecommendationsOnlyOnDemand": true,
    "telemetry.enableCrashReporter": false,
    "telemetry.enableTelemetry": false,
    "code-runner.enableAppInsights": false,
    "update.channel": "none",
    "update.mode":"none",
    "extensions.autoUpdate": false,
    "extensions.ignoreRecommendations": true,
```

P.S. The request goes to ms marketplace because it was in `extensionGallery`. It is irrelevant I believe, the issue it still goes to market despite being told not to.
I will keep investigating original builds as well.

**Comment by stripedpajamas** [comment]
Could it be extensions themselves calling home? Does burp show you the content of the requests?

**Comment by stripedpajamas** [comment]
Also curious to know if this same traffic (and disregard for the settings.json) happens in MS build?

**Comment by Kein** [comment]
> Could it be extensions themselves calling home? Can you paste the content for the requests in too?

Sure, that does not change anything though because:
```
    "extensions.autoCheckUpdates": false,
    "extensions.showRecommendationsOnlyOnDemand": true,
    "extensions.autoUpdate": false,
    "extensions.ignoreRecommendations": true,
```

Issue is still here.




> Also curious to know if this same traffic (and disregard for the settings.json) happens in MS build?

I havent caught that kind of traffic yet, but there us this:
