### ISSUE TITLE
Terminal is different in VSCodium compared to VSCode

### ISSUE THREAD

**Issue by ElnuDev** [VSCodium/vscodium#664]
**Describe the bug**

In VSCode, the terminal works perfectly normally, and behaves just like my normal operating system terminal. However, in VSCodium, commands are prefixed with `sh-5.1$` instead of my usual `elnu@pop-os:~$`. Furthermore, there is no highlighting, and some commands don't even work. Typing in `rustc` yields `sh: rustc: command not found`, even though it works just fine in a normal command line. However, commands like `python3` seem to work fine.

I feel like I'm missing something obvious here, but still, I feel like VSCodium's terminal should operate just like VSCode's by default. I don't remember ever changing any settings.

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.10
 - Architecture: x86-64
 - Version: 1.53.2

**Comment by RichardDern** [comment]
Command Palette > Default Shell

I don't think it's a VSCodium bug rather than default shell not selected to what you're used to.

**Comment by alt-art** [comment]
> Typing in `rustc` yields `sh: rustc: command not found`, 

@ElnuDev This is because the folder where these binaries are is not in PATH. Write in your .zprofile or .bashrc or .zshrc this:
`export PATH="$HOME/.cargo/bin:$PATH"`

**Comment by hollisticated-horse** [comment]
I can't seem to set the shell nor profile to have zsh on manjaro...

When following : https://code.visualstudio.com/docs/editor/integrated-terminal#_terminal-profiles

I get : `Command "Terminal: Select Default Profile" resulted in a error (ENOENT: no such file or directory, open "/etc/shells" `

I added the export path in my .zshrc, but that doesn't seem to change anything.

And i'm stuck with bash or javascript debuging

**Comment by daiyam** [comment]
Is your `defaultProfile` correctly set?

**Comment by Teajey** [comment]
I'm having this issue... My user settings look like this:
```json
{
    "terminal.integrated.profiles.linux": {
        "zsh": {
            "path": "/usr/bin/zsh",
            "args": ["-l"]
        }
    },
    "terminal.integrated.defaultProfile.linux": "zsh"
}
```
I also get this result in the VSCodium terminal:
```
sh-5.1$ ls /bin | grep zsh
sh-5.1$
```

As opposed to this in GNOME Terminal:
```
[thomas@thomas-desktop ~] ls /bin | grep zsh
rzsh
zsh
zsh5
[thomas@thomas-desktop ~]
```
When I choose 'Terminal: Select Default Profile' there are no options to select from...

**Comment by Teajey** [comment]
It seems like it's running in some kind of virtual environment? I found zsh at `/run/host/usr/bin/zsh`. Everything that would normally be in the root filesystem is in `/run/host`, but `/home` is still the same. I have `/` mounted in a separate partition from `/home`, so I wonder if that could have something to do with it

**Comment by Teajey** [comment]
Also, yeah, the highlighting's not working when I execute `/run/host/usr/bin/zsh`...
![Screenshot from 2022-02-28 14-32-05](https://user-images.githubusercontent.com/21069848/155910194-9e4f7863-54a1-4015-9d60-b389c05d5825.png)

**Comment by Teajey** [comment]
I'm on Linux Mint. I expected that it might have something to do with Flatpak. So I uninstalled the version that I got from Linux Mint's Software Manager and reinstalled from the releases on this repo and it works fine. I guess Flatpak applications, or those from the Software Manager are put in some kind of playpen
