### ISSUE TITLE
Unable to sign into Live Share extension on 1.53

### ISSUE THREAD

**Issue by absozero** [VSCodium/vscodium#669]
I was unable to sign in with Live Share made by ms-vsliveshare. I need it as I am doing a project with a friend using this extension and I was not able to sign in and use this extension to share. This was troubling to me, since I did not want to use VS code given by Microsoft since I was sure there would be a lot of tracking in it, and the license wasn't friendly. The Live Share extension worked with Codium before, but hasn't worked on the latest release. It keeps loading and never actually signs in, and when I want to log in with github, it states 'Forbidden". Could somebody help?

**Comment by SeanRamey** [comment]
I just installed Codium, and when I click the "accounts" button so that I can sign in to github and sync my extensions, it just says "Loading" and never does anything. This might be the same issue.

**Comment by daiyam** [comment]
https://github.com/VSCodium/vscodium/wiki/Extensions-Compatibility#incompatibility-due-to-licensing
