### ISSUE TITLE
The icon partially covers the title when pinned to the Start menu

### ISSUE THREAD

**Issue by radevm** [VSCodium/vscodium#67]
The new icon covers most of the application title when pinned to the Start menu and resized to medium.

![capture](https://user-images.githubusercontent.com/5891204/50006357-31d56700-ffb6-11e8-869c-6b040fc95dc5.PNG)
VSCodium shortcut between ST3 and VSCode

Window 10 (64-bit Enterprise 1709)

**Comment by JL2210** [comment]
We need to have a black icon instead of a white one. @stripedpajamas?

**Comment by stripedpajamas** [comment]
The issue here is icon size. Need investigation into the difference of icon sizes in this repo vs Microsoft's repo.

**Comment by radevm** [comment]
The sizes are the same as far as I can judge but the size of the "content" is a different (also the background) - see below the official icons placed next to VSCodium icons:

![150x150](https://user-images.githubusercontent.com/5891204/51479733-cdb57800-1d97-11e9-8022-d298bb36deb0.PNG)
![70x70](https://user-images.githubusercontent.com/5891204/51479740-d0b06880-1d97-11e9-928a-0a46b58aad16.PNG)

**Comment by JL2210** [comment]
We could always remove the white background. That might fix the issue.

**Comment by radevm** [comment]
My humble suggestion is to shrink the logo to match the official logo's size.

**Comment by Jackymancs4** [comment]
Hello,
to fix the issue, I prepared two PRs (that I'll submit tomorrow for review).
The final result looks like this:

|Version|Big|Small|
|--|--|--|
|Actual|![or-big](https://user-images.githubusercontent.com/6209647/51501893-03785200-1dd4-11e9-8578-a6a6b0005445.png)|![or-small](https://user-images.githubusercontent.com/6209647/51501892-03785200-1dd4-11e9-8297-e3c72d79ec9d.png)|
|v1|![v2-big](https://user-images.githubusercontent.com/6209647/51501681-45ed5f00-1dd3-11e9-8b05-9e6083112f48.png)|![v2-small](https://user-images.githubusercontent.com/6209647/51501680-45ed5f00-1dd3-11e9-85e5-86d10fb42528.png)|
|v2|![v1-big](https://user-images.githubusercontent.com/6209647/51501683-4685f580-1dd3-11e9-838f-8feddfed09a1.png)|![v1-small](https://user-images.githubusercontent.com/6209647/51501682-4685f580-1dd3-11e9-9829-8a0a48a393c3.png)|

Any feedback/preference is appreciated.

**Comment by JL2210** [comment]
Thanks. `v1` looks good to me.

**Comment by stripedpajamas** [comment]
Thanks so much @Jackymancs4 ! Looking forward to the PRs. We will probably use `v2` as it is the correct sizing of the originally voted-upon icon. Really appreciate you getting it sorted out.

**Comment by stripedpajamas** [comment]
@Jackymancs4 any update on that PR?
