### ISSUE TITLE
VSCodium.com doesn't show info about possible snap installation

### ISSUE THREAD

**Issue by Mi-La** [VSCodium/vscodium#670]
**Describe the bug**
When I was looking for info about installation, I missed info about installation via snap. While actual README.md on https://github.com/VSCodium/vscodium contains the information (Install with snap), the https://vscodium.com seem to be out of date.

**To Reproduce**
Visit https://vscodium.com

**Expected behavior**
I would expect consistent instructions as in readme. (Hopefully the domain belongs to this github project :-))

**Comment by FaresAhmedb** [comment]
Please take a look at https://github.com/VSCodium/vscodium.github.io/pull/42
I think this PR fixes the issue
