### ISSUE TITLE
the directory `~/.vscode-oss` is created

### ISSUE THREAD

**Issue by daiyam** [VSCodium/vscodium#671]
**Describe the bug**

I've tested VSCodium on linux and I found out that it creates the directory `~/.vscode-oss`. It shouldn't do that.

Here the tested distros:
- lastest Arch (arch)
- Fedora 33 (rpm)
- Linux Mint 18.3 (deb)
- PoP! OS 20.04 (deb)

**Comment by daiyam** [comment]
Soon, I will have a PR to fix this issue.

**Comment by paulcarroty** [comment]
Yeah, it's described in [docs](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#migrating-from-visual-studio-code-to-vscodium). So you should fix them too.

**Comment by daiyam** [comment]
Ya, I was doing some testing on Linux and was seeing  the directory being created. And I was asking myself, why that `vscode-oss` is being created since it's `VSCodium`??? I do think it should be changed.

**Comment by stripedpajamas** [comment]
It's from the product.json. I figured that people who built manually (Code OSS) would want to share settings/extensions with VSCodium. Maybe should be a fully separate dir. Any particular problem with it using .vscode-oss though?

**Comment by paulcarroty** [comment]
The problem is lack of clarity. Some users may delete `.vscode-oss` by mistake like I did 😊

For sharing a symlink is enough, but it feels strange as default.

**Comment by paulcarroty** [comment]
Any progress here?

**Comment by janpb** [comment]
Late for the party, but following option can overcome installing extensions in `~/.vscode-oss`. However, it doesn't get rid of the directory itself (unfortunately).   

You can use the `--extensions-dir` option to set the install directory for extension, e.g.

`code-oss  --user-data-dir "$HOME/.config/vscode" --extensions-dir "$HOME/.config/vscode/extensions"'`

This create no extension directory in `~/.vscode-oss`, which has now only the file `argv.json`. 

Hope this helps

**Comment by daiyam** [comment]
I think it should be part of https://github.com/VSCodium/vscodium/pull/293
