### ISSUE TITLE
Activating extension 'msjsdiag.debugger-for-chrome' failed

### ISSUE THREAD

**Issue by AbakumovAlexandr** [VSCodium/vscodium#677]
**Describe the bug**
`Debugger for Chrome` extension cannott be activated after installation.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install `Debugger for Chrome` into VSCodion via `EXTENSIONS` tab.
2. Load your JS\TS project into VSCodion, build it, open in Chrome.
3. Create proper `launch.json` config to attach to Chrome.
4. Try to attach to Chrome via VSCodion's `RUN AND DEBUG` tab using the above created config.
5. It doesn't attach. In VSCodiom Developer Tools, it throws an error:

> Activating extension 'msjsdiag.debugger-for-chrome' failed: Cannot find module '/home/x/.vscode-oss/extensions/msjsdiag.debugger-for-chrome-4.12.6/out/src/extension'
> Require stack:
> - /usr/share/codium/resources/app/out/vs/loader.js
> - /usr/share/codium/resources/app/out/bootstrap-amd.js
> - /usr/share/codium/resources/app/out/bootstrap-fork.js.
> _logMessageInConsole @ workbench.desktop.main.js:1857
> _logOrShowMessage @ workbench.desktop.main.js:1857
> $onExtensionActivationError @ workbench.desktop.main.js:2084
> _doInvokeHandler @ workbench.desktop.main.js:1687
> _invokeHandler @ workbench.desktop.main.js:1687
> _receiveRequest @ workbench.desktop.main.js:1687
> _receiveOneMessage @ workbench.desktop.main.js:1687
> (anonymous) @ workbench.desktop.main.js:1687
> fire @ workbench.desktop.main.js:57
> fire @ workbench.desktop.main.js:76
> _receiveMessage @ workbench.desktop.main.js:76
> (anonymous) @ workbench.desktop.main.js:76
> fire @ workbench.desktop.main.js:57
> acceptChunk @ workbench.desktop.main.js:76
> (anonymous) @ workbench.desktop.main.js:76
> I @ workbench.desktop.main.js:2760
> emit @ events.js:315
> addChunk @ _stream_readable.js:295
> readableAddChunk @ _stream_readable.js:271
> Readable.push @ _stream_readable.js:212
> onStreamRead @ internal/stream_base_commons.js:186

**Expected behavior**
`Debugger for Chrome` attaches to Chrome and works just like in VS Code.

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Architecture arm64
 - Version 1.54.3

**Additional context**
I tried to uninstall  the `Debugger for Chrome` extension. The `/home/x/.vscode-oss/extensions/msjsdiag.debugger-for-chrome-4.12.6/` folder was not removed. I removed it manually and re-installed the extension. It has not helped - the same error when attaching to Chrome.

**Comment by AbakumovAlexandr** [comment]
Just tested on Windows 10 x64 - exactly the same thing:

![image](https://user-images.githubusercontent.com/6968009/112084697-9e5d4a00-8b5f-11eb-9ef2-0a6da876ed44.png)

**Comment by daiyam** [comment]
A sample would be useful.
But the extension is faulty on Open VSX, there is no `out` folder.
But that folder is in the extension on Visual Studio Marketplace...

**Comment by AbakumovAlexandr** [comment]
> A sample would be useful.
1. Could you elaborate, please - sample of what?


> But the extension is faulty on Open VSX, there is no `out` folder.
2. Does Open VSX have a separate issue tracker, so I could notify them as well?


> But that folder is in the extension on Visual Studio Marketplace...
3. Di you mean the best way to work it around is to isntall it via `EXTENSIONS` ->`install from VSIX` and get that VSIX from Visual Studio Marketplace?

**Comment by daiyam** [comment]
1. A project so we can easily test the issue
2. Maybe on their gitter: https://gitter.im/eclipse/openvsx
3. Yes

**Comment by AbakumovAlexandr** [comment]
You can reproduce it without any project.
`launch.json` could be created automatically.
Just  try to attach to Chrome.

**Comment by spoenemann** [comment]
The initial version was contributed to [open-vsx.org](https://open-vsx.org) via [open-vsx/publish-extensions](https://github.com/open-vsx/publish-extensions), that's a script that publishes a list of selected extensions every night. The extension was removed from the list because the namespace has been claimed, but we can add it back since the namespace owner apparently is not going to publish anything.

Could you create an issue at that repository? Also feel free to provide a PR to add the extension to the JSON list. If you do so, please have a close look whether special build steps are necessary in order to get a working extension package.

**Comment by AbakumovAlexandr** [comment]
@spoenemann  thank you, [done](https://github.com/open-vsx/publish-extensions/issues/322#issue-840385801).

**Comment by filiptronicek** [comment]
@AbakumovAlexandr as this extension is now deprecated in favor of the built-in functionality [[1](https://github.com/microsoft/vscode-chrome-debug#rotating_light-important)], is this issue still relevant?
