### ISSUE TITLE
Php language is not recognized (codium 1.54.3 Ubuntu 20.10)

### ISSUE THREAD

**Issue by Cyrille37** [VSCodium/vscodium#679]
**Describe the bug**
Php language is not recognized, not present in laguages list.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**

On an Ubuntu 20.10 with repository : 
```
$ cat /etc/apt/sources.list.d/vscodium.list 
deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main
```

1. `sudo apt install codium`
2. create an empty file "toto.php"
3. open it with `codium`
4. write some php
5. in status bar the file type is "Plain Text"

**Screenshots**

![image](https://user-images.githubusercontent.com/368965/112631034-adc9e500-8e36-11eb-9524-c44777a3ad27.png)

![image](https://user-images.githubusercontent.com/368965/112631304-fed9d900-8e36-11eb-8b24-636c46e30093.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Architecture x64
 - Version 1.54.3

**Additional context**

```
$ codium --version
1.54.3
2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
x64

$ php --version
PHP 7.3.27-9+ubuntu20.10.1+deb.sury.org+1 (cli) (built: Feb 23 2021 15:10:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27-9+ubuntu20.10.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

```

But other languages like json or bash are well recognized
![image](https://user-images.githubusercontent.com/368965/112631824-a951fc00-8e37-11eb-8f68-ddf122027329.png)

**Comment by daiyam** [comment]
I don't have the issue on Ubuntu 20.04. What are your extensions and your config?
Can you try by installing the `.deb` from https://github.com/VSCodium/vscodium/releases ?

**Comment by Cyrille37** [comment]
> I don't have the issue on Ubuntu 20.04. What are your extensions and your config?

Just a fresh install, like shown in my report.

> Can you try by installing the `.deb` from https://github.com/VSCodium/vscodium/releases ?

Ok I do ... Argh, exactly the same problem:

```
sudo dpkg -i ~/Téléchargements/codium_1.54.3-1615854707_amd64.deb
```
![image](https://user-images.githubusercontent.com/368965/112649930-2f2b7280-8e4b-11eb-9735-49814ee6af43.png)

**Comment by daiyam** [comment]
Have tried to remove your `.config/VSCodium`?

**Comment by Cyrille37** [comment]
Argh!! What a beginner I am! What a shame!

I did, it works !! 

```
sudo rm -rf ~/.config/VSCodium/
sudo dpkg -i ~/Téléchargements/codium_1.54.3-1615854707_amd64.deb
codium /home/cyrille/Bureau/toto.php
```
![image](https://user-images.githubusercontent.com/368965/112655441-ac0d1b00-8e50-11eb-9f86-f39d085a7aa8.png)

Please accept my warmest thanks!
