### ISSUE TITLE
What's the deal with VSCodium auto-updates?

### ISSUE THREAD

**Issue by spencerkohan** [VSCodium/vscodium#680]
I got a notification to install an update for VSCodium from inside the app itself.  Where would this update come from?  If I install it, will I just end up with the standard distribution of the editor from MS, i.e. with telemetry turned on?

**Comment by stripedpajamas** [comment]
We implemented the same update api as MS and configure VSCodium to use it. It gets the latest release from this repo. Reference https://github.com/VSCodium/update-api
