### ISSUE TITLE
Php outline pane is empty (Ubuntu 20.10, Codium 1.55.0)

### ISSUE THREAD

**Issue by Cyrille37** [VSCodium/vscodium#684]
**Describe the bug**

The "outline" pane is empty with php language files.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. from APT repository `deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main`
2. `sudo apt purge codium`
3. `rm -rf ~/.config/VSCodium`
4. `rm -rf ~/.vscode-oss`
5. `sudo apt install codium`
6. open a php file
7. Outline pane is empty

**Expected behavior**

Outline pane filled with php symboles.

**Screenshots**

![image](https://user-images.githubusercontent.com/368965/112844599-30a3a780-90a4-11eb-9828-3032f2df8a01.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Architecture x64
 - Version 1.55.0

**Additional context**

Previously got problem "Php language is not recognized #679"

**Comment by Cyrille37** [comment]
I've installed extension "PHP IntelliSense" and disabled "php.suggest.basic" but "outline" pane remains empty.

**Comment by Cyrille37** [comment]
same problem with freshly updated version 1.55.0.

**Comment by Cyrille37** [comment]
Problem persists with 
* Version: 1.55.2
* Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
* Date: 2021-04-14T00:48:08.463Z
* Electron: 11.3.0
* Chrome: 87.0.4280.141
* Node.js: 12.18.3
* V8: 8.7.220.31-electron.0
* OS: Linux x64 5.8.0-50-generic

**Comment by Cyrille37** [comment]
I still have the same problem...

No symbol in outline window when a Php file is open, but got symbols for json and js files.

- VSCodium 1.61.2 (from "deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main")
- Electron 13.5.1
- Node.js 14.16.0
- OS: Ubuntu 21.04 Linux x64 5.11

- No extension
- No error in output log windows

**Comment by PeterPlucinski** [comment]
I have the same issue

OS: Debian 10

PHP Version 7.3.31

Extensions: PHP Intellisense (same thing happens without the extension)

**Comment by Cyrille37** [comment]
VSCodium 1.66.0
Ubuntu 21.10

The outline pane is filled when opened file types:
- .md
- .js
- .json

But is empty with message "No symbols found in document ..." with file types:
- .xml
- .php
- .sql

**Comment by daiyam** [comment]
On either Visual Studio Code or VSCodium, the outline pane is working on PHP files only if the extension `PHP Intelephense` has been installed.
The extension `PHP IntelliSense` doesn't work for me on both editors... maybe a configuration issue.
So I don't think it's an issue with VSCodium itself.
