### ISSUE TITLE
Cannot add VScodium to PATH

### ISSUE THREAD

**Issue by robpedersendev** [VSCodium/vscodium#687]
**Describe the bug**
When I open the program on Ubuntu 20.04 fresh install, no more then 10minutes old, I go to View> Command Palette and the Option to add it to the PATH is not there. 

Something that may or may not be important is that when I installed this OS, I set up a formatted drive to be partitioned  and installed Ubuntu on half of the drive. There is nothing on the other half of the drive. I set up the "/" directory and the swap portion and nothing else then installed Ubuntu. 

**Please confirm that this problem is VSCodium-specific**
I also installed VS Code to see if this is an issue with VSCodium and this is also occurring with VS Code as well. 

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
 go to View> Command Palette and the Option to add it to the PATH is not there. 

**Expected behavior**
 go to View> Command Palette and the Option to add it to the PATH is  available

**Screenshots**
![image](https://user-images.githubusercontent.com/40696979/113124674-ff75c500-91d2-11eb-922e-d93082c84de2.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Architecture amd
 - Version 1.54.3

**Comment by daiyam** [comment]
The command isn't there because `codium` should already be in your `PATH` (by default on Linux).

**Comment by robpedersendev** [comment]
Yup, it is. Thanks.
