### ISSUE TITLE
Icon Problem

### ISSUE THREAD

**Issue by abdurrahmanarikan** [VSCodium/vscodium#697]
**Describe the bug**
The vscodium icon looks ugly when it is searched on macos spotlight 

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. open spotlight (keyboard cmd+space shortcut) on macos
2. type vscodium and wait for a while to see the icon

**Expected behavior**
the icon should be exactly as it is in the application folder

**Screenshots**
![image](https://user-images.githubusercontent.com/24858031/113993157-ce456680-985c-11eb-9ae4-02b9763d5010.png)

**Desktop (please complete the following information):**
 - OS: macos 
 - Architecture : x64
 - Version : 10.15.7

**Additional context**
nothing

**Comment by daiyam** [comment]
It's the icon of Visual Studio Code (middle one) which seems to be corrupted. The one of VSCodium (top one) seems fine.
Anyways it's a spotlight issue: https://discussions.apple.com/thread/5609797

**Comment by abdurrahmanarikan** [comment]
@daiyam thanks for the correction.
