### ISSUE TITLE
Extensions auto update doesn't work

### ISSUE THREAD

**Issue by proninyaroslav** [VSCodium/vscodium#701]
**Describe the bug**
Extensions are not updated automatically, although this is specified in the settings.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
To update extensions, I have to do the following actions:
1. Write an extension name in the search bar. **NOTE:** If I just open the page extension in the extension list, nothing happens.
2. After that, VSCodium will check the availability of updates and offers to update the expansion. 

**Expected behavior**
VSCodium must automatically check the update availability of extensions and update them in the background. 

**Desktop (please complete the following information):**
 - OS: Fedora 32
 - Architecture: x64
 - Version: 1.55.0

**Additional context**
I use Microsoft Marketplace to update extensions: 
```JSON
"extensionsGallery": {
    "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
    "itemUrl": "https://marketplace.visualstudio.com/items",
}
```
My VSCodium settings here: https://gist.github.com/proninyaroslav/91f4fc404a6e726ef1c1a5afdbbb5913

**Comment by pmahend1** [comment]
Using Visual Studio marketplace is a hacky way and [it's not clear whether that will break the licensing policy. ](https://github.com/microsoft/vscode/issues/31168)
Do it at your own risk.

Does it work if you use the default open-vsx URLs?

**Comment by daiyam** [comment]
@pmahend1 Not really hacky, you just have to follow [How to use the VS Code Marketplace](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#howto-vscode-marketplace)
Some extensions aren't up to date on OpenVSX...

**Comment by pmahend1** [comment]
Yeah @daiyam . By hacky I mean *work-around*ish way. Codium is intended to be true OSS with MIT licensing and telemetry OFF. It is linked to open-vsx [because Visual studio marketplace licensing states it is to be used MS products](https://github.com/VSCodium/vscodium#extensions-and-the-marketplace). If someone really wants to use Visual studio marketplace , they might just use VS Code and turn off telemetry.
Or request extension developer to add 2 lines of code to release it to open-vsx as well. 

Expecting Visual Studio marketplace to work seamlessly with Codium is kind of out of scope of this repo I think.

**Comment by daiyam** [comment]
@pmahend1 I agree

**Comment by proninyaroslav** [comment]
>Or request extension developer to add 2 lines of code to release it to open-vsx as well.

Unfortunately, this sounds too optimistic.  Many developers simply ignore it.

**Comment by daiyam** [comment]
@proninyaroslav Were you able to do what you wanted?

**Comment by proninyaroslav** [comment]
@pmahend1 
> Expecting Visual Studio marketplace to work seamlessly with Codium is kind of out of scope of this repo I think.

Support for the VSCode Marketplace is important for Codium, as it draws more user attention to the FOSS project: a user who has worked with VSCode will get a smoother transition to the blobless version, because all his usual extensions will work and receive updates as before. After that, he can start a gradual transition to OpenVSX, when all its extensions become available in OpenVSX.

**Comment by daiyam** [comment]
> work seamlessly

That will be difficult specially with popular extensions from Microsoft like Python, Remote... I don't think they will ever support OpenVSX.
And we can't validate every extensions but maybe we can add a compatibility doc for popular ones...

**Comment by proninyaroslav** [comment]
I know Microsoft extensions are a problem, but there are many others.

**Comment by daiyam** [comment]
I will prepare a compatibility wiki page.

**Comment by daiyam** [comment]
I've started the wiki page: https://github.com/VSCodium/vscodium/wiki/Extensions-Compatibility

The Python extension has to be reviewed...

**Comment by proninyaroslav** [comment]
@daiyam 
How is this relate to auto updates? By the way, it seems in the latest versions of Codium I don't have any problems with auto updates.
