### ISSUE TITLE
Unable to find MS-LiveShare extension

### ISSUE THREAD

**Issue by Perpetuous** [VSCodium/vscodium#707]
**Describe the bug**
Microsofts Live Share extension is unable to be installed, because VSCodium cannot find the extension. This is with product.json updated to use the microsoft marketplace, and having tried three separate ways of installing it (extensions browser, webstore and terminal).

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to the extensions page, or to the web extensions marketplace, or try to install it through the terminal using extension ID.
2. In all of the above cases, the installation fails because it cannot find the extension

**Expected behavior**
It should be installed as normal.

**Screenshots**
[image](https://user-images.githubusercontent.com/12564364/116544361-531d2080-a8ef-11eb-86bb-841449a358ff.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Architecture x64
 - Build 19041.928

**Comment by suffle** [comment]
Codium uses an alternative Extension Marketplace (open vsx) for legal reasons. The LiveShare extension is not part of that marketplace and I don't think Microsoft is interested in changing that. So if you want to use LiveShare, you have two options:
1. Download the extension as vsix form https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare-pack
2. Change the Marketplace to the microsoft marketplace (see https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace)

You also might run into problems signing in to LiveShare after your installation, see https://github.com/VSCodium/vscodium/issues/320#issuecomment-797737954 for a solution

**Comment by stripedpajamas** [comment]
Closing as @suffle has provided the correct answer.
