### ISSUE TITLE
C++ extension's Windows debugging does not work

### ISSUE THREAD

**Issue by jingyu9575** [VSCodium/vscodium#71]
1. Install Microsoft's C/C++ extension;
2. Create a folder with a Hello World C++ program and build it;
3. Debug with the default C++/Windows (cppvsdbg) launch.json.

Expected behavior: (tested in MS VSCode)
The program is launched and can be debugged.

Actual behavior in VSCodium:
This message shows, and then nothing happens.

```
-------------------------------------------------------------------
You may only use the C/C++ Extension for Visual Studio Code with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
```

Is this because of the C/C++ extension's licensing? Is there any way around this?

**Comment by stripedpajamas** [comment]
Hi @jingyu9575 👋 

I only have a Mac and it seems that the extension works properly there (created hello world program; built it; debugged via VSCodium and it printed Hello World in my terminal). Mac debugging uses `cppdbg` though. 

I do not think this is a licensing issue. The licensing is confusing to me in the extension repo (https://github.com/Microsoft/vscode-cpptools), but it looks to me like [the main license file](https://github.com/Microsoft/vscode-cpptools/blob/master/LICENSE.txt) is MIT, which is not restrictive. The message that you are seeing looks more like the text from another license file in that repo (https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/LICENSE.txt) marked as the license for "PRE-RELASE SOFTWARE". It includes the restriction that the extension can only be used in Microsoft products:

```
   You may only use the C/C++ Extension
   for Visual Studio Code with Visual Studio Code, Visual Studio or
   Xamarin Studio software to help you develop and test your
   applications.
```

(Visual Studio Code unfortunately being the non-MIT licensed proprietary MS build of the [vscode](https://github.com/Microsoft/vscode) repo).

Regardless of licensing, I think the problem might be that some path is hard coded in the extension's Windows-specific code. Next steps would be to try to get more information when it crashes about what specifically is failing -- this might be possible by building the extension from source locally, but I don't see instructions for that in their repo.

**Comment by jingyu9575** [comment]
Thank you @stripedpajamas .

About the licensing, the Windows debugger is [proprietary](https://github.com/Microsoft/vscode-cpptools/issues/21#issuecomment-248349017). I checked the developer console when this issue happens, and it shows this error:

```
  ERR Error processing 'configurationDone' request. Unknown Error: 0x89720010: Error: Error processing 'configurationDone' request. Unknown Error: 0x89720010
    at t.handleErrorResponse (file:///C:/Program Files/VSCodium/resources/app/out/vs/workbench/workbench.main.js:2722:35)
    at file:///C:/Program Files/VSCodium/resources/app/out/vs/workbench/workbench.main.js:2721:485
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Searching `0x89720010` provides several other debugging bugs of the C# extension, which is also proprietary, and it seems that Microsoft is actively [preventing the usage](https://github.com/OmniSharp/omnisharp-vscode/issues/1431#issuecomment-297578930) on the free software version of VSCode with [signings](https://github.com/Microsoft/vscode/issues/46270#issuecomment-376422108).

Not sure if we can workaround it here.

**Comment by stripedpajamas** [comment]
Wow that's really unfortunate. Thank you for digging into the issue there. I don't think there are many paths forward, outside of writing an open source extension from scratch.
