### ISSUE TITLE
Remote Explorer is missing in VSCodium

### ISSUE THREAD

**Issue by vraravam** [VSCodium/vscodium#712]
**Describe the bug**
"Remote Explorer" is missing in VSCodium

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open Codium in any folder that is a git repo with a remote upstream branch
2. The 'Remote Explorer' icon on the left sidebar is missing

**Expected behavior**
'Remote Explorer' icon should be visible and show appropriate info when clicked.

**Screenshots**
<img width="43" alt="Screen Shot 2021-05-03 at 10 59 34 AM" src="https://user-images.githubusercontent.com/69629/116843806-b4e6ce80-abfe-11eb-99b6-7c77b75a4af0.png">

**Desktop (please complete the following information):**
 - OS: MacOS BigSur 11.2.3
 - Architecture x86
 - Version 1.55.2

**Additional context**

**Comment by daiyam** [comment]
It's an extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack
And by license, it can only work on Visual Studio Code.
