### ISSUE TITLE
Many VSCode plugins not available in VSCodium

### ISSUE THREAD

**Issue by bserem** [VSCodium/vscodium#713]
Several VSCode plugins are not available in VSCodium. This is true when running `ext install...` and when searching through the extensions tab.

Examples:
- git stash https://marketplace.visualstudio.com/items?itemName=arturock.gitstash
- git patch https://marketplace.visualstudio.com/items?itemName=paragdiwan.gitpatch
- copy relative path https://marketplace.visualstudio.com/items?itemName=alexdima.copy-relative-path
- auto complete tag https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-complete-tag

VSCodium Version: 1.55.2
OS: Linux x64 (Debian Bullseye)
Node.js: 12.18.3

**Comment by paulcarroty** [comment]
https://github.com/VSCodium/vscodium/blob/master/DOCS.md#how-to-use-the-vs-code-marketplace
