### ISSUE TITLE
product.json in %AppData% has no effect on Windows

### ISSUE THREAD

**Issue by rshamsnejad** [VSCodium/vscodium#719]
**Describe the bug**
By following [these instructions](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#howto-vscode-marketplace), I was trying to switch VSCodium to use the Microsoft marketplace. I'm on Windows, and it doesn't work if I make the change in `%AppData%\VSCodium\product.json` that I needed to create. By the way, this is the correct path to AppData I think, because the one indicated in the documentation (`%USER%\AppData\Roaming\VSCodium`) is not valid when pasted in Explorer.

What worked however, was to modify `C:\Program Files\VSCodium\resources\app\product.json`.

I did not have this problem with VSCodium on Arch Linux : modifying `~/.config/VSCodium/product.json` worked correctly.

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Make the change in `%AppData%\VSCodium\product.json`
2. Restart VSCodium, search for an extension that is not in Open VSX (such as `ms-vscode.cpptools`), **it should not show up**
3. Make the change in `C:\Program Files\VSCodium\resources\app\product.json`
4. Restart VSCodium, search for an extension that is not in Open VSX (such as `ms-vscode.cpptools`), **it should show up**

**Expected behavior**
The change in AppData should override the default setting

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Architecture: x64
 - Version: 1.56.0 (system setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-09T16:03:54.032Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by femto-code** [comment]
I can confirm this issue.
Meanwhile many of VS Code extensions seem to be listed in the new market place so I just use that instead. If you cannot find an extension simply download it from MS and install it via file.

**Comment by assange0** [comment]
Same with you

**Comment by bunower** [comment]
Same here

**Comment by raycekar** [comment]
Same here

**Comment by daiyam** [comment]
Can you try with the version 1.57.0 which include the fix?

**Comment by assange0** [comment]
> 
> 
> Can you try with the version 1.57.0 which include the fix?

Test OK, now the product.json works.

Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-18T00:22:40.384Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
