### ISSUE TITLE
Your VSCodium installation appears to be corrupt. Please reinstall.

### ISSUE THREAD

**Issue by SimonBrazell** [VSCodium/vscodium#723]
**Describe the bug**
With the most recent build on MacOS a warning message is now displayed when starting vscodium saying: 

> Your VSCodium installation appears to be corrupt. Please reinstall.

I've tried reinstalling (`brew reinstall vscodium`), the message is still displayed.

There is an option to get more information which takes you to `https://go.microsoft.com/fwlink/?LinkId=828886`.

The editor also displays `[Unsupported]` at the top to the right of the workspace name. 

This message was not present in previous builds.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Occurs upon starting the application.

**Expected behavior**
No warnings should be displayed.

**Screenshots**
![Screen Shot 2021-05-20 at 10 30 58](https://user-images.githubusercontent.com/16571951/118901625-16c16b00-b957-11eb-800e-57bf52bce11d.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 11.2.3 (20D91)
 - Architecture Intel
 - Version: 1.56.2
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-09T15:57:41.650Z (1 wk ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.3.0

**Additional context**
I'm overriding the default extensions gallery and using the original VScode marketplace instead via an edited `product.json` file in `~/Library/Application Support/VSCodium`, just followed the [docs](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#howto-vscode-marketplace) for this.

Let me know if there is anything else I should supply or try, Cheers!

**Comment by Swiftb0y** [comment]
I started having the same issue with the build for fedora.

**Comment by pdfrod** [comment]
Same issue here in Ubuntu 20.10.

**Comment by Swiftb0y** [comment]
I recently figured out what the issue is. If you change the `product.json` file, some package managers won't replace it when upgrading to a new version. In that case, you'll need to replace the changed `product.json` file with the new one and reapply your customizations on top of that.

**Comment by pdfrod** [comment]
Thanks for the tip @Swiftb0y, that lead me in the right direction.

In my case the `product.json` installed by the package manager was fine, but like the OP, I had a custom `product.json` inside my home folder. Apparently I created this custom `product.json` by copying the content from the package version and changing the `extensionsGallery` section, however according to the [instructions](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#howto-vscode-marketplace), the custom `product.json` should only contain the `extensionsGallery` section. Removing all the unnecessary stuff from custom `product.json` fixed the problem for me.

**Comment by SimonBrazell** [comment]
@pdfrod that's it! 

I had a full copy of the `product.json` file in the `~/Library/Application Support/VSCodium` folder that I'd copied and modified from the original package, removing this and using the environment variables instead resolved the problem.

Cheers!
