### ISSUE TITLE
Global Menu missing at launching the application

### ISSUE THREAD

**Issue by singhayushh** [VSCodium/vscodium#724]
**Describe the bug**
Global Menu is not visible at launch. I initially thought that it wasn't supported but I found that if I minimize and then again maximize the window, the global menu appears suddenly.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Launch VSCodium, either through terminal or directly.

**Expected behavior**
Global Menu should appear at launch.

**Screenshots**
1. Just after Launch

![err1](https://user-images.githubusercontent.com/52620158/119226634-bf262980-bb27-11eb-98e9-7bc3969578f9.png)

2. After I minimize and then re-maximize 

![err2](https://user-images.githubusercontent.com/52620158/119226638-c0efed00-bb27-11eb-95db-4934f784d265.png)

**Desktop (please complete the following information):**
 - OS: kubuntu 21.04
 - Architecture: x64
 - Version: 1.56.2

**Additional context**
This behavior doesn't occur with any other applications installed. I have never downloaded any external themes / fonts as well, everything is set to, as default.

**Comment by nepodev** [comment]
Same issue on Manjaro KDE

Operating System: Manjaro Linux
KDE Plasma Version: 5.23.3
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.10.79-1-MANJARO (64-bit)
Graphics Platform: X11

**Comment by nepodev** [comment]
Since using [Window AppMenu](https://github.com/psifidotos/applet-window-appmenu) instead of Global AppMenu, the problem has disappeared
