### ISSUE TITLE
Latest version of extension not installing

### ISSUE THREAD

**Issue by jakbin** [VSCodium/vscodium#727]
**Describe the bug**
When i try to install python extension , its showing me old version of python extension(v2020.10.332292344) , that is too old.
But latest version of python extension is v2021.5.842923320

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**Screenshots**
![2021-05-28_17-02](https://user-images.githubusercontent.com/65591973/119980051-62b88380-bfd9-11eb-9c05-a618e2627eb5.png)

Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-14T00:17:59.109Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.10.0-6parrot1-amd64

**Comment by daiyam** [comment]
Is it related to #726? Linux, v1.56.2, same day...

**Comment by jakbin** [comment]
> Is it related to #726? Linux, v1.56.2, same day...

No

**Comment by daiyam** [comment]
Yep! It's because you are using the default [Open VSX](https://open-vsx.org/extension/ms-python/python) marketplace.
You need to switch to VS Code Marketplace to be able to have the latest version.
Here how to: https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace
