### ISSUE TITLE
code command is not symlinked to homebrew prefix

### ISSUE THREAD

**Issue by kiendang** [VSCodium/vscodium#73]
I think it's a good idea to symlink `VSCodium.app/Contents/Resources/app/bin/code` to Homebrew prefix so users can `code <file-name>` from the command line like they can do it with the original VSCode.

**Comment by stripedpajamas** [comment]
Hi @kiendang -- running `code` from the command line has come up a couple of times before. Refer to https://github.com/VSCodium/vscodium/blob/master/DOCS.md#terminal-support to get it set up (it is no different than the VS Code setup, just the name is different).

**Comment by kiendang** [comment]
Oh thanks. Sorry wasn't looking hard enough. Will close this issue and the other pull request then.
