### ISSUE TITLE
Vscodium can't connect to extensions marketplace

### ISSUE THREAD

**Issue by billyxwn-pixel** [VSCodium/vscodium#733]
Can someone provide some guidance on this issue? I've installed vscodium via Scoop but it doesn't seem to be able to connect with the extensions marketplace.

**Comment by zen0bit** [comment]
same here...

**Comment by daiyam** [comment]
VS Code Marketplace or OpenVSX?
More info at https://github.com/VSCodium/vscodium#extensions-and-the-marketplace

**Comment by pipiscrew** [comment]
@billyxwn-pixel  @zen0bit 

dont know, installing extension is not every day habit. 

what Im doing,  going to [marketplace](https://marketplace.visualstudio.com/) or [openvsx](https://open-vsx.org/), on the right side there is a **download** button on both sites.

then on VSCodium > View > Command Palette > type `Install from VSIX` > choose the .VSIX previous downloaded.

**Comment by heinermann** [comment]
OpenVSX appears to be broken.

<img width="469" alt="2021-06-23 15_56_34-Open VSX Registry" src="https://user-images.githubusercontent.com/1966366/123178234-9d2c0980-d43b-11eb-8a43-d9ea814b34b6.png">

**Comment by daiyam** [comment]
Maybe related to https://www.eclipsestatus.io/incidents/1hs2z6hznqhl

**Comment by stripedpajamas** [comment]
@heinermann is that error still occurring for you? I'm able to install extensions from open-vsx without issue.

@billyxwn-pixel are you still unable to install extensions via your scoop install? If so, please provide more details, like error messages.

**Comment by heinermann** [comment]
Yes, appears to be working again for me since the issue @daiyam posted was resolved.

**Comment by JOduMonT** [comment]
From what I understand, I have no proxy
![image](https://user-images.githubusercontent.com/5204724/124338734-b0756c80-dbd3-11eb-9a42-0c00825ffc88.png)

If I cut and past the address (https://open-vsx.org/vscode/gallery/extensionquery) in firefox, this one could reach but like VSCodium it don't have the right to query
![image](https://user-images.githubusercontent.com/5204724/124338767-d569df80-dbd3-11eb-9ca7-8a40ac294cf4.png)

While I could use their website and download extension
![image](https://user-images.githubusercontent.com/5204724/124338818-182bb780-dbd4-11eb-84ff-c9a92ae5aca6.png)

**Comment by daiyam** [comment]
`If not set, will be inherited from the http_proxy and https_proxy environment variables.` What's in your environment variables?

**Comment by JOduMonT** [comment]
Kubuntu 20.04, ...
You're right, I set up an i2p proxy in my Brave which actually setup it for the whole KDE :)
![image](https://user-images.githubusercontent.com/5204724/124339366-3eebed00-dbd8-11eb-94bc-6749fd47ed35.png)

@daiyam thank you for your quick and accurate remote eyes

**Comment by act28** [comment]
On v1.58, I'm getting a CORS error
![image](https://user-images.githubusercontent.com/6226636/125370278-72412f80-e3c1-11eb-89b2-1fce2b04ffe3.png)
