### ISSUE TITLE
[Enhencment] Discord rich presence

### ISSUE THREAD

**Issue by Nextross** [VSCodium/vscodium#738]
Could you please add discord rich presence like in Visual Studio?

**Comment by stripedpajamas** [comment]
I'm not sure what you mean. Can you explain?

**Comment by Nextross** [comment]
When you open Visual Studio, it will appear next to your profile on discord with time (for how long you have been coding) and other stuff. VSCodium (and other programs) can be added manually, but native support would be better

**Comment by jaydensar** [comment]
That's not native to Visual Studio, it's an extension. [There's also an extension for VSCode](https://marketplace.visualstudio.com/items?itemName=icrawl.discord-vscode), but I'm not sure if it's in the extension gallery VSCodium uses.

**Comment by stripedpajamas** [comment]
It is available in the Open VSX marketplace, the one VSCodium uses https://open-vsx.org/extension/icrawl/discord-vscode
