### ISSUE TITLE
Close Button gets clipped

### ISSUE THREAD

**Issue by git-emil** [VSCodium/vscodium#739]
Hi!

At times the close button of the terminal window gets partially clipped.
I don't know if this occurs on vscode  too.
To reproduce resize the app window with the mouse.
I'm on Windows 20H2 with vscode 1.57.0

![Screenshot](https://user-images.githubusercontent.com/14874959/121897172-9bfb2e00-cd11-11eb-9f64-834d9063b3ce.jpg)

Thanks for reading, Emil

**Comment by daiyam** [comment]
I can't reproduce the bug also on Windows 20H2 and VSCode 1.57.0

**Comment by pmahend1** [comment]
if you resize it is kind of expected, because not everything is responsive.
