### ISSUE TITLE
Missing amd64.deb and el7.x86_64.rpm builds for 1.30.2

### ISSUE THREAD

**Issue by nim-odoo** [VSCodium/vscodium#74]
Hello,

Would it be possible to release the mentioned packages for v1.30.2?

Thanks

**Comment by stripedpajamas** [comment]
Thanks for the heads up @nim-odoo -- looks like that build had an `npm install` issue. I'm rerunning it now.

**Comment by stripedpajamas** [comment]
All good now @nim-odoo 👍

**Comment by nim-odoo** [comment]
Thanks
