### ISSUE TITLE
[1.57.0][AppImage][Debian Buster] `setuid sandbox` error

### ISSUE THREAD

**Issue by daiyam** [VSCodium/vscodium#743]
I tried 1.57.0 in Buster, Bullseye, KDE Neon and openSUSE Leap/Tumbleweed. VSCodium didn't crash, though in Buster I got this: 

```bash
The setuid sandbox is not running as root. Common causes:
  * An unprivileged process using ptrace on it, like a debugger.
  * A parent process set prctl(PR_SET_NO_NEW_PRIVS, ...)
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
Trace/breakpoint trap
```

had to use 

`--no-sandbox` 

Also, a pop-up window with a "vscodium stop working" or some similar message kept showing up over and over, clicked "wait" to close it and the app eventually started responding again.

_Originally posted by @Moltkex in https://github.com/VSCodium/vscodium/issues/330#issuecomment-861742207_

**Comment by daiyam** [comment]
@Moltkex I'm also getting the error with 1.57.0. But I don't get the error with 1.56.2...

**Comment by Moltkex** [comment]
> @Moltkex I'm also getting the error with 1.57.0. But I don't get the error with 1.56.2...

In Buster? Yeah, that's weird. Like I said [there](https://github.com/VSCodium/vscodium/issues/330#issuecomment-861742207 ), this seems to be a problem with Buster's kernel version, 4.19, something about [user namespaces](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898446) which is fixed in Linux 5.10. The weird part is why it happens with 1.57 but doesn't with 1.56. I wonder if installing Linux 5.10 from backports will solve it. I will try when I get the chance and let you know how it went.

**Comment by daiyam** [comment]
Here the log:
```
baptiste@debian:~/Downloads$ uname -r
4.19.0-16-amd64
baptiste@debian:~/Downloads$ ./VSCodium-1.56.2-1620951495.glibc2.16-x86_64.AppImage 

(codium:1904): GLib-GIO-CRITICAL **: 16:26:29.121: g_settings_schema_source_lookup: assertion 'source != NULL' failed
Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.

(codium:1904): GLib-GIO-CRITICAL **: 16:26:29.497: g_settings_schema_source_lookup: assertion 'source != NULL' failed
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)

(codium:1904): GLib-GIO-CRITICAL **: 16:26:29.576: g_settings_schema_source_lookup: assertion 'source != NULL' failed
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[main 2021-06-17T14:26:29.805Z] update#setState idle

baptiste@debian:~/Downloads$ ./VSCodium-1.57.0-1623554025.glibc2.17-x86_64.AppImage 
The setuid sandbox is not running as root. Common causes:
  * An unprivileged process using ptrace on it, like a debugger.
  * A parent process set prctl(PR_SET_NO_NEW_PRIVS, ...)
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
Trace/breakpoint trap
```

**Comment by Moltkex** [comment]
@daiyam I just installed kernel **5.10.0-0.bpo.3-amd64** in my Buster VM, launched VSCodium 1.57, and can confirm that the issue doesn't occur anymore; VSCodium works just fine.

**Comment by daiyam** [comment]
@Moltkex https://github.com/microsoft/vscode/issues/126027

**Comment by daiyam** [comment]
`1.57.1` is fixing the issue
