### ISSUE TITLE
[1.58] Extension marketplace not working

### ISSUE THREAD

**Issue by swinder0161** [VSCodium/vscodium#746]
**Describe the bug**
I built my own vscode for macos using main branch of vscode and extension store is not loading
![image](https://user-images.githubusercontent.com/397543/122681047-147d5580-d210-11eb-9735-37e756740402.png)

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open VSCodium
2. Click on Extensions button from left side bar
3. See error

**Expected behavior**
Extension store should load

**Screenshots**
![image](https://user-images.githubusercontent.com/397543/122681074-3ecf1300-d210-11eb-9446-2c1ee88debd6.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Architecture x64
 - Version [1.58.0]

**Additional context**
NA

**Comment by daiyam** [comment]
`1.58`??? How have you build the app?

**Comment by swinder0161** [comment]
hi @daiyam 

I apply patch below and run ./build/build_macos.sh

diff --git a/get_repo.sh b/get_repo.sh
index 301efdf..9800f11 100755
--- a/get_repo.sh
+++ b/get_repo.sh
@@ -6,7 +6,7 @@ export LATEST_MS_COMMIT=$(echo $UPDATE_INFO | jq -r '.version')
 export LATEST_MS_TAG=$(echo $UPDATE_INFO | jq -r '.name')
 echo "Got the latest MS tag: ${LATEST_MS_TAG}"

-git clone https://github.com/Microsoft/vscode.git --branch $LATEST_MS_TAG --depth 1
+git clone https://github.com/Microsoft/vscode.git --branch main --depth 1

 # for GH actions
 if [[ $GITHUB_ENV ]]; then

**Comment by daiyam** [comment]
Do you have an error in the Developer Tools (`Help` / `Toggle Developer Tools`)?

**Comment by swinder0161** [comment]
Not an expert at it.
please check screenshot and let me know if I need to provide more details

![image](https://user-images.githubusercontent.com/397543/122728688-0245fa80-d296-11eb-85ac-c879590ed8ff.png)

**Comment by swinder0161** [comment]
Information: I built 1.57.1 and in that I see no issues.
Maybe if you can try **main** branch on your side, will get same error.

**Comment by swinder0161** [comment]
@daiyam did you try build the main branch vscode?

**Comment by daiyam** [comment]
No I didn't. Maybe tomorrow...

**Comment by swinder0161** [comment]
Hi @daiyam Did you get a chance to try the main branch from vscode?

**Comment by daiyam** [comment]
Yep, just done so... I'me getting the same issue.

The request headers have been changed between 1.57 and 1.58...

from
```
Accept: application/json;api-version=3.0-preview.1
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US
Connection: keep-alive
Content-Length: 231
Content-Type: application/json
Host: open-vsx.org
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) VSCodium/1.57.0 Chrome/89.0.4389.128 Electron/12.0.9 Safari/537.36
X-Market-Client-Id: VSCode 1.57.0
X-Market-User-Id: 764e9072-f3c1-4813-9703-e198eadc9486
```
to
```
Accept: application/json;api-version=3.0-preview.1
Content-Type: application/json
Referer
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) VSCodium/1.58.0 Chrome/89.0.4389.128 Electron/12.0.13 Safari/537.36
X-Market-Client-Id: VSCode 1.58.0
X-Market-User-Id: 764e9072-f3c1-4813-9703-e198eadc9486
```

**Comment by swinder0161** [comment]
I have no idea about how to fix, anyone in this project who will fix this? @daiyam

**Comment by daiyam** [comment]
Yep, same here. If it becomes an issue on a new release, then I will look around...

**Comment by swinder0161** [comment]
hi @daiyam vscode-1.58 released and has this problem. We need someone to help fix it.

**Comment by daiyam** [comment]
Yep, the issue is there for OpenVSX but not with VS Code Marketplace... I will take a look

**Comment by henrythebuilder** [comment]
Hi,
I've a similar problem with the latest release (1.58.0), same error detected in the 'Network Tool' `Referrer Policy: strict-origin-when-cross-origin` and the _Console_ report this error:

`Access to XMLHttpRequest at 'https://open-vsx.org/vscode/gallery/extensionquery' from origin 'vscode-file://vscode-app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

At the moment the only solution/workaround I have found to have the extensions working is running codium with the 'chrome flag `--disable-web-security` => **`codium --disable-web-security .`** , as the log reports after startup `Warning: 'disable-web-security' is not in the list of known options, but still passed to Electron/Chromium.`
 
Hope this will be helpful in some way

**Comment by stripedpajamas** [comment]
cc @spoenemann -- possibly a change required on the extension server side cors checks?

**Comment by daiyam** [comment]
@stripedpajamas I don't think so since the request headers aren't the same between both marketplace...

**Comment by stripedpajamas** [comment]
Which really doesn't make sense to me 🤔

**Comment by daiyam** [comment]
I was wrong the request headers passed to the `XMLHttpRequest`instance are identical:
```
X-Market-Client-Id: VSCode 1.58.0
X-Market-User-Id: 27ea627c-eac1-4ae6-92fd-d093b80d1ba5
Content-Type: application/json
Accept: application/json;api-version=3.0-preview.1
``` 

Chromium are the same: `89.0.4389.128`
Electron: `12.0.7` -> `12.0.13`
Node: same `14.16.0`

**Comment by daiyam** [comment]
It's an issue with open-vsx.org:

In the console of your browser, try both:
```
(function() {
const xhr = new XMLHttpRequest();

xhr.open('POST', 'https://open-vsx.org/vscode/gallery/extensionquery', true);

xhr.setRequestHeader('X-Market-Client-Id', 'VSCode 1.58.0');
xhr.setRequestHeader('X-Market-User-Id', '27ea627c-eac1-4ae6-92fd-d093b80d1ba5');
xhr.setRequestHeader('Content-Type', 'application/json');
xhr.setRequestHeader('Accept', 'application/json;api-version=3.0-preview.1');

xhr.onload = (e) => {
	console.log(xhr.response);
};

xhr.send('{"filters":[{"criteria":[{"filterType":8,"value":"Microsoft.VisualStudio.Code"},{"filterType":12,"value":"4096"}],"pageNumber":1,"pageSize":50,"sortBy":4,"sortOrder":0}],"assetTypes":[],"flags":950}');
})();
```
and
```
(function() {
const xhr = new XMLHttpRequest();

xhr.open('POST', 'https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery', true);

xhr.setRequestHeader('X-Market-Client-Id', 'VSCode 1.58.0');
xhr.setRequestHeader('X-Market-User-Id', '27ea627c-eac1-4ae6-92fd-d093b80d1ba5');
xhr.setRequestHeader('Content-Type', 'application/json');
xhr.setRequestHeader('Accept', 'application/json;api-version=3.0-preview.1');

xhr.onload = (e) => {
	console.log(xhr.response);
};

xhr.send('{"filters":[{"criteria":[{"filterType":8,"value":"Microsoft.VisualStudio.Code"},{"filterType":12,"value":"4096"}],"pageNumber":1,"pageSize":50,"sortBy":4,"sortOrder":0}],"assetTypes":[],"flags":950}');
})();
```

Just the url are changed. OpenVSX is failing while VisualStudio is doing fine...

**Comment by daiyam** [comment]
I've opened an issue on OpenVSX https://github.com/eclipse/openvsx/issues/306

**Comment by act28** [comment]
I'm getting a CORS PreflightMissingAllowOriginHeader error as well
![image](https://user-images.githubusercontent.com/6226636/125370681-5be7a380-e3c2-11eb-804f-bf1b641bdb81.png)

**Comment by playgithub** [comment]
comfirmed

## Env
* OS: Windows 10
* VSCdoium: 1.58.0 (system setup) / 1.58.0 (user setup)
## Screenshot
![image](https://user-images.githubusercontent.com/3665590/125396298-ef2ed200-e3de-11eb-97c0-c063af397777.png)

**Comment by SunderB** [comment]
Hi,
I've recently installed vscodium on Debian using the official package, and can confirm I'm getting the same CORS related error in the dev console, even when specifying open-vsx explicitly in product.json.
![image](https://user-images.githubusercontent.com/20426079/125692383-ad7bc8f9-6a79-4ee6-915b-c85e72f7133b.png)

**Comment by mas-co** [comment]
VSCodium is not able to install extensions:
Version: 1.58.1 (system setup)
Commit: 2aeda6b18e13c4f4f9edf6667158a6b8d408874b
Date: 2021-07-14T00:20:06.917Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by act28** [comment]
Upgraded to 1.58.1 yesterday, the CORS error has now changed to `HeaderDisallowedByPreflightResponse`

**Comment by konradybcio** [comment]
<img width="550" alt="Screenshot 2021-07-15 at 20 10 56" src="https://user-images.githubusercontent.com/32096130/125836747-0836afee-0a12-4c15-b260-c2434f697cf2.png">

1.58.1, macOS

**Comment by daiyam** [comment]
Ok, I found the change: https://github.com/microsoft/vscode/blob/1.58.0/src/main.js#L177

There is temporary work around:
- in the file `~/.vscode-oss/argv.json`
- add the line: `"enable-browser-code-loading": false`

Sadly, that option will be removed next month... hopefully, open-vsx.org will fully support CORS by then

**Comment by robertarles** [comment]
> Ok, I found the change: https://github.com/microsoft/vscode/blob/1.58.0/src/main.js#L177
> 
> There is temporary work around:
> 
> * in the file `~/.vscode-oss/argv.json`
> * add the line: `"enable-browser-code-loading": false`
> 
> Sadly, that option will be removed next month... hopefully, open-vsx.org will fully support CORS by then
> 
> Before `v1.58.0`, `enable-browser-code-loading": false` was the default value

This didn't fix it for me, even after a restart.  I get a message when I hover over that key that it "is not allowed".

**Comment by daiyam** [comment]
Yep, I also get `Property enable-browser-code-loading is not allowed.` but it's working.
I'm not sure about the path on Windows but there should a folder named `extensions` with all your installed extensions.
Forgot about to restart VSCodium...

**Comment by pmahend1** [comment]
I was trying to understand source code for this issue the other day and I couldn't seem to find something where the URL is changed in this repo.

Also I could see that some changes are just as-is from VSCode .

@daiyam 
>Sadly, that option will be removed next month...  

Do you mean it will be removed at VS Code? if yes, then is it possible to not to do that for VSCodium repo?

**Comment by daiyam** [comment]
@pmahend1 The best solution would be for open-vsx.org to fully support CORS. If by the next version, it's not resolved, I think it's safe to add a patch to revert that change.

**Comment by robertarles** [comment]
> Yep, I also get `Property enable-browser-code-loading is not allowed.` but it's working.
> I'm not sure about the path on Windows but there should a folder named `extensions` with all your installed extensions.
> Forgot about to restart VSCodium...

Follow up -> The temp workaround now works for me (MacOS 11.2.3, Vscodium 1.58.2)  I do not know why it works today and not yesterday, but I did move the `"enable-browser-code-loading": false` entry from the top of the JSON to the last entry.

**Comment by daiyam** [comment]
@robertarles Good, I'm glad it's working...

**Comment by pmahend1** [comment]
@daiyam I figured that. Who takes care of adding CORS changes to open-vsx.org ? 

> 
> 
> @pmahend1 The best solution would be for open-vsx.org to fully support CORS. If by the next version, it's not resolved, I think it's safe to add a patch to revert that change.

**Comment by daiyam** [comment]
@pmahend1 eclipse/openvsx#306

**Comment by r3mis** [comment]
> Hi,
> I've a similar problem with the latest release (1.58.0), same error detected in the 'Network Tool' `Referrer Policy: strict-origin-when-cross-origin` and the _Console_ report this error:
> 
> `Access to XMLHttpRequest at 'https://open-vsx.org/vscode/gallery/extensionquery' from origin 'vscode-file://vscode-app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
> 
> At the moment the only solution/workaround I have found to have the extensions working is running codium with the 'chrome flag `--disable-web-security` => **`codium --disable-web-security .`** , as the log reports after startup `Warning: 'disable-web-security' is not in the list of known options, but still passed to Electron/Chromium.`
> 
> Hope this will be helpful in some way

This is actually a fix that worked for me. I guess this may be a workaround for Windows users.
Thank you so much.

**Comment by madupuis90** [comment]
>     * ~/.vscode-oss/argv.json

![image](https://user-images.githubusercontent.com/76877179/126043250-ed5e3e65-1679-4525-b0ff-7707a02b053a.png)

Is this normal it doesn't seem to work in 1.58.2

**Comment by Dhamma-valence** [comment]
> codium --disable-web-security

This flag actually fixes it for Linux as well (Debian Unstable), though I'm certain it's neither an ideal, nor permanent solution.

**Comment by mas-co** [comment]
while `codium --disable-web-security` makes it possible to access the marketplace, many extensions are not available, such as "pandoc citer".
Am I missing something, or should all of the extensions in the Marketplace be available?  (I'm not going to claim it's not a PEBKAC error.)

**Comment by nickadamson** [comment]
FYI, for anyone looking for a quick and dirty solution, you can still: 
go to the https://marketplace.visualstudio.com page for a plugin -> Resources -> "Download Extension"
That will download a **_.vsix_** file you can install in VSCodium
<details>
  <summary>VS Location</summary>
  
![image](https://user-images.githubusercontent.com/80008674/126200290-1430eb60-8fcf-431f-9261-96f559f8ebd5.png)

</details>

**Comment by daiyam** [comment]
@nickadamson [How to use the VS Code Marketplace](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#howto-vscode-marketplace) is still working fine with `v1.58.x`

**Comment by pavelloz** [comment]
Same issue.
![image](https://user-images.githubusercontent.com/546845/126325545-c0ccef9b-27b6-42dc-ac5e-67eaa80301c7.png)

**Comment by jurisbu** [comment]
@pavelloz did you by any chance meant to patch `product.json`?

Works fine for me with changes applied to `product.json` to use VS Code Marketplace as per https://github.com/VSCodium/vscodium/blob/master/DOCS.md#howto-vscode-marketplace

**Comment by daiyam** [comment]
@jurisbu Thanks for confirming 👍

**Comment by pavelloz** [comment]
@jurisbu yes! I use word project so much i created project.json instead of product.json :)

It works perfectly now on both my machines. Thank you.

**Comment by GGORG0** [comment]
same issue 
![image](https://user-images.githubusercontent.com/51029895/126621563-dd0e3c88-ff6a-47a3-9e8a-5fd8374a1177.png)

**Comment by playgithub** [comment]
When such things happens, I always doubt that there are unfriendly policies there, who can tell me is there?

**Comment by newedgex** [comment]
I have the same problem on Arch Linux with
Version: 1.58.0
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-12T23:51:36.303Z
Electron: 12.0.15
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.12.15-arch1-1`
`

**Comment by ibkindness** [comment]
> > ```
> > * ~/.vscode-oss/argv.json
> > ```
> 
> ![image](https://user-images.githubusercontent.com/76877179/126043250-ed5e3e65-1679-4525-b0ff-7707a02b053a.png)
> 
> Is this normal it doesn't seem to work in 1.58.2
![Screenshot from 2021-07-23 03-57-00](https://user-images.githubusercontent.com/72319855/126729337-a4f26f78-a7a7-496d-bc2e-15c7fa9dd7ab.png)

**Comment by daiyam** [comment]
@ibkindness ??? you have a list of extensions

**Comment by LemmonPa** [comment]
> 
> 
> Hi,
> I've a similar problem with the latest release (1.58.0), same error detected in the 'Network Tool' `Referrer Policy: strict-origin-when-cross-origin` and the _Console_ report this error:
> 
> `Access to XMLHttpRequest at 'https://open-vsx.org/vscode/gallery/extensionquery' from origin 'vscode-file://vscode-app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
> 
> At the moment the only solution/workaround I have found to have the extensions working is running codium with the 'chrome flag `--disable-web-security` => **`codium --disable-web-security .`** , as the log reports after startup `Warning: 'disable-web-security' is not in the list of known options, but still passed to Electron/Chromium.`
> 
> Hope this will be helpful in some way

yeah that sadly works for now.
thanks man
![IUjpy1ucFD](https://user-images.githubusercontent.com/53460243/126775419-59b66188-bd59-44b9-84c2-4085609d11d9.png)

**Comment by r3mis** [comment]
![image](https://user-images.githubusercontent.com/52204908/126775743-9f6b889b-f46e-4d49-b025-9c1704247e97.png)

It works for me now, looks like I didn't put a , on the previous entry.

**Comment by gerroon** [comment]
This stil does not work for me. How did you fix it?

**Comment by PascalMaximus** [comment]
![vs](https://user-images.githubusercontent.com/86281523/126865525-9c9dde33-78bf-4484-b2be-848dfb96b1c9.png)

**Comment by daiyam** [comment]
@PascalMaximus https://github.com/VSCodium/vscodium/issues/746#issuecomment-881049046

**Comment by PascalMaximus** [comment]
> @PascalMaximus [#746 (comment)](https://github.com/VSCodium/vscodium/issues/746#issuecomment-881049046)

I installed using dirty way https://github.com/VSCodium/vscodium/issues/746#issuecomment-882721554

**Comment by esqb** [comment]
> Ok, I found the change: https://github.com/microsoft/vscode/blob/1.58.0/src/main.js#L177
> 
> There is temporary workaround:
> 
>     * in the file `~/.vscode-oss/argv.json`
> 
>     * add the line: `"enable-browser-code-loading": false`
> 
>     * restart VSCodium
> 
> 
> Sadly, that option will be removed next month... hopefully, open-vsx.org will fully support CORS by then
> 
> Before `v1.58.0`, `enable-browser-code-loading": false` was the default value

Worked like a charm for me on Linux! Thank you!

**Comment by NuLL3rr0r** [comment]
@esqb Thank you very much! Saved the day.

**Comment by dhruvrohilla** [comment]
Solution -
https://github.com/VSCodium/vscodium/blob/master/DOCS.md#how-to-use-the-vs-code-marketplace

**Comment by r3mis** [comment]
Yeah, but no.
VSCodium is trying to be Visual Studio Code **without** Microsoft Telematry, and even if using the Microsoft Marketplace could work, people don't really want this. OpenVSX is Open Source instead, that's why many prefer it over the Microsoft's own Marketplace.
As the Eclipse Foundation Open VSX Registry Frequently Asked Questions says:

"_The Open VSX Registry offers a community driven, fully open platform for publishing and consuming VS Code extensions. The Registry is built on Eclipse Open VSX, which is an open source project hosted at the Eclipse Foundation._

_Open VSX is integrated into multiple software applications that support VS Code extensions. There is strong demand for a fully open alternative to the Visual Studio Marketplace, and with hundreds of great extensions already available, it is the intent of the Eclipse Foundation to enable continued and accelerated growth._"

**Comment by daiyam** [comment]
FYI, I'm made the patch #774 in case OpenVSX hasn't fixed CORS when 1.59 is out.

**Comment by lana404** [comment]
> > Ok, I found the change: https://github.com/microsoft/vscode/blob/1.58.0/src/main.js#L177
> > There is temporary workaround:
> > ```
> > * in the file `~/.vscode-oss/argv.json`
> > 
> > * add the line: `"enable-browser-code-loading": false`
> > 
> > * restart VSCodium
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Sadly, that option will be removed next month... hopefully, open-vsx.org will fully support CORS by then
> > Before `v1.58.0`, `enable-browser-code-loading": false` was the default value
> 
> Worked like a charm for me on Linux! Thank you!

Wow,.. Thank you

This work for me

![Screenshot_20210728_075131](https://user-images.githubusercontent.com/39423737/127245997-630d3d3c-816a-401b-98d7-b5d1d76c255e.png)

**Comment by pmahend1** [comment]
Is there a known work around for Mac other than changing product.json with MS VSCode values?

**Comment by erlangga092** [comment]
> Mac workaround:
> 
> If Firefox is the default browser Installing [CORS Ublock](https://addons.mozilla.org/en-US/firefox/addon/cors-unblock/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) fixed it for me on Mac.
> 
> Not sure if other browser is default.
> 
> Credits : @SpacingBat3 [eclipse/openvsx#306 (comment)](https://github.com/eclipse/openvsx/issues/306#issuecomment-877866351)

Thanks sir
Worked for me

**Comment by edurolon** [comment]
is there any final solution for this ????

**Comment by aScordino** [comment]
For now, the ways you can "fix" this erors are:
1) Install extensions manually from source or via the .vsix extension file2) Run VSCodium with --disable-web-security
3) Edit ~/.vscode-oss/argv.json ​and add the line "enable-browser-code-loading": false4) Wait for exlipse to fix this bug5) Switch to Microsoft's Marketplace <https://www.github.com/VSCodium/vscodium/tree/master/DOCS.md>​ <https://www.github.com/VSCodium/vscodium/tree/master/DOCS.md>- Antonino Scordino



2 ago 2021, 22:18 da ***@***.***:

**Comment by daiyam** [comment]
6) Wait until Thursday or Friday for v1.59 to come out with the PR #774.

**Comment by MusheAbdulHakim** [comment]
I just installed the latest version of codium and yet am having this issue. 
This is the stacktrace of my network in the dev tools .

`(anonymous) @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:76
A @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:76
request @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:634
queryGallery @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:639
queryGallery @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:639
query @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:639
(anonymous) @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2839
queryGallery @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2839
queryGallery @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2835
queryGallery @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2835
query @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2835
(anonymous) @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2835
y @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:68
show @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2835
(anonymous) @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2835
onDidAddViewDescriptors @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2835
(anonymous) @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2586
fire @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:60
triggerOnDidAddVisibleViewDescriptors @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2351
onDidChangeContext @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2351
(anonymous) @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2351
fire @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:60
(anonymous) @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:58
fire @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:60
fire @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:60
setContext @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:634
set @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:634
doSearch @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2835
(anonymous) @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2835
(anonymous) @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:68
trigger @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:68
triggerSearch @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2835
(anonymous) @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2835
fire @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:60
(anonymous) @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2110
(anonymous) @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:580
fire @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:60
endDeferredEmit @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:589
pushEditOperations @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:587
_innerExecuteCommands @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:617
executeCommands @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:617
_executeEditOperation @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:616
(anonymous) @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:617
_executeEdit @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:617
type @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:617
(anonymous) @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:618
_withViewEventsCollector @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:618
_executeCursorEdit @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:618
type @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:618
_type @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:654
type @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:654
type @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:652
(anonymous) @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:643
fire @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:60
(anonymous) @ vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:148
`

**Comment by aScordino** [comment]
They didn't even fixed it, he (**daiyam**) said the problem will be resolved when _they will update to 1.59_.

**Comment by edurolon** [comment]
I tried all the options. I did not find a solution.
I had to manually install the extensions from the page with vsix.
Thank you!!

**Comment by dragonDScript** [comment]
To fix we can use nodejs' net module.

**Comment by daiyam** [comment]
`VSCode-1.59` is out. No patch to fix. Extensions marketplace is working (with the patch).
The new release should be out in a couple of hours.

**Comment by daiyam** [comment]
Official `VSCodium-1.59` is out, the extensions marketplace is back! Enjoy :wink:

**Comment by JAicewizard** [comment]
it still doesnt work for me.

**Comment by daiyam** [comment]
@JAicewizard Have you restarted the editor?

**Comment by JAicewizard** [comment]
yes, several times. fix #3 fixes the issue for me, as a workaround.

**Comment by jotoho** [comment]
@JAicewizard Just want to make sure: Are you sure that you're using VSCodium and not some other OpenSource build of VSCode?

Non-VSCodium builds of VSCode using the OpenVSX Marketplace like the VSCode distributed by ArchLinux still require the `enable-browser-code-loading` workaround since the root cause **still** hasn't been fixed by OpenVSX.

**Comment by JAicewizard** [comment]
oh thanks, sorry. I think this might indeed be `vscode`+OpenVSX not vscodium.
I saw the issue on OpenVSX, it is kind of amazing that issue is still open IMHO.

**Comment by GitMensch** [comment]
Does not work for me with:

~~~
Version: 1.59.1 (system setup)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Datum: 2021-08-20T00:21:07.615Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
Betriebssystem: Windows_NT x64 10.0.19042
~~~

@daiyam Does it work for you with 1.59.1?

**Comment by daiyam** [comment]
@GitMensch Yep, it's working. I've a stupid question. Have you restarted VSCodium? If you have just updated and not restarted, you will still have the issue.

**Comment by GitMensch** [comment]
I'm quite sure that I've closed it but who knows if an instance was still open. Did it again, checked for running process, haven't seen anything codium related, started it again, extension search (and foremost updates) work. So finally time for closing :-)

**Comment by dragonDScript** [comment]
> I'm quite sure that I've closed it but who knows if an instance was still open. Did it again, checked for running process, haven't seen anything codium related, started it again, extension search (and foremost updates) work. So finally time for closing :-)

You probably closed and opened again and the assets got cached.

**Comment by MusheAbdulHakim** [comment]
I think if you are still having this issue, you should consider updating your vscodium or reinstalling it altogether.
you can use this command on linux systems. 
```sudo apt update && sudo apt install vscodium```

**Comment by daiyam** [comment]
Bad news, the patch don't work on `v1.60`. I've disabled the Github Actions to avoid to have a VSCodium v1.60 with the same issue...
