### ISSUE TITLE
Am I using proprietary extensions? How do I tell?

### ISSUE THREAD

**Issue by RenaKunisaki** [VSCodium/vscodium#747]
**Describe the bug**
I've just installed (from Artix vscodium AUR package) and gone into extensions from the splash screen. I looked at the Python extension, and at the bottom of the page it mentions telemetry being included. I was under the impression that VSCodium uses a replacement extension repository that removes telemetry. Am I somehow not using that repository, or is this simply an oversight or an obsolete description of the extension?

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to Extensions
2. Select Python (for me, it's the very first one listed) (edit: the button I clicked automatically added the search `@category:"programming languages" @sort:installs `)
3. Scroll to the bottom of its description

**Expected behavior**
1. No mention of telemetry (or some explanation of it being removed, etc)
2. Some easy way to tell that I'm using the replacement extension repository instead of the official one (unless I've just overlooked this)

**Screenshots**
Excerpt from bottom of extension info:
> Data and telemetry
> The Microsoft Python Extension for Visual Studio Code collects usage data and sends it to Microsoft to help improve our products and services. Read our privacy statement to learn more. This extension respects the telemetry.enableTelemetry setting which you can learn more about at https://code.visualstudio.com/docs/supporting/faq#_how-to-disable-telemetry-reporting.

(I interpret this to mean that while VSCodium itself isn't sending telemetry, and has the settings for it disabled by default, the extensions still might be doing naughty things.)

**Desktop (please complete the following information):**
 - OS: Artix Linux
 - Architecture x64
 - Version 1.57.1

**Comment by ericvicenti** [comment]
> I was under the impression that VSCodium uses a replacement extension repository that removes telemetry.

Where did you hear this? I was under the opposite impression- that VSCodium uses Microsoft's repository (which obviously has telemetry).

Although, for the past half day it seems that VSCodium "cannot connect to the Extensions Marketplace." While VSCode still can..

**Comment by daiyam** [comment]
@RenaKunisaki @ericvicenti The Python extension's id is `ms-python.python`. It's a Microsoft's extension so they can do what they like.
In general, VSCodium remove the telemetry included in the core editor but each extension can include their own telemetry.
By default, VSCodium use the [Open VSX Registry](https://open-vsx.org/) instead of the Microsoft's one.

@ericvicenti There is an issue with `v1.58.x`: #746 & eclipse/openvsx#306
