### ISSUE TITLE
Can't open terminal in v1.57.1

### ISSUE THREAD

**Issue by Annmayn** [VSCodium/vscodium#749]
Whenever I open terminal in the latest version of vscodium, I get the error message saying "Path to shell executable bash is not a file of a symlink". However, I can still run tasks which also uses bash.

This bug doesn't occur in v1.55.2. If I update or fresh install v1.57.1, I'll get the aforementioned error.

**To Reproduce**
1. Fresh install or update vscodium
2. Open terminal

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1
 - Architecture: amd64

**Comment by Annmayn** [comment]
![codium_error](https://user-images.githubusercontent.com/24735609/123419183-a18e2900-d5d9-11eb-92ea-fd96230a1453.png)

**Comment by daiyam** [comment]
What your default shell?

**Comment by mattrattus** [comment]
Same problem.
My default shell is ZSH, and I get error:
The terminal process failed to launch: Path to shell executable "zsh" does not exist.
Fresh installation.

**Comment by daiyam** [comment]
@mattrattus Also on Linux Mint?

**Comment by mattrattus** [comment]
No, Arch Linux. Sorry I forgot to mention

**Comment by daiyam** [comment]
I can't reproduce the issue on Arch Linux + fish and on Debian Buster + bash.
Are you getting an error in Developer Tools (Ctrl+Shift+I, Tab Console)?

**Comment by mattrattus** [comment]
I got this error when I use New Terminal (ctrl+shift+`).
As I mentioned - fresh installation from AUR.

I found the solution for me.
Just add **"terminal.integrated.shell.linux": "/usr/bin/zsh"** to the settings.json in ~/.config/VSCodium/User

**Comment by Annmayn** [comment]
> What your default shell?

I'm using bash. Changing **terminal.integrated.shell.linux** like @mattrattus mentioned does work. I was changing **terminal.integrated.automationShell.linux** before smh. 

Could the issue be because of the ongoing deprecation of **terminal.integrated.shell.linux**? The default profile **terminal.integrated.defaultProfile.linux** is set to "bash", which does correspond to the error I'm getting.
