### ISSUE TITLE
Linux tar packages named Vscode

### ISSUE THREAD

**Issue by gerroon** [VSCodium/vscodium#75]
Minor issue but why is the tar package named Vscode instead of Vscodium?

VSCode-linux-x64-1.30.2.tar.gz

**Comment by stripedpajamas** [comment]
Good find, @gerroon... I suspect the name is hardcoded somewhere in the VSCode build process. I'll take a quick look to see if I can find it.

**Comment by stripedpajamas** [comment]
@gerroon actually it looks like I had manually set the zip file and tar files to use VSCode in the name 🤷‍♂️ #75 opened to resolve
