### ISSUE TITLE
What data will telemetry collect?

### ISSUE THREAD

**Issue by playgithub** [VSCodium/vscodium#76]
Thanks.

**Comment by playgithub** [comment]
> Hi @playgithub
> 
> Can you be more specific as to what you're asking? Are you asking what telemetry Microsoft usually collects if it's not disabled?
Yes. I'm considering to switch to FreeBSD or Linux, and tried at least 3 times, but switched back to Windows again now.

**Comment by stripedpajamas** [comment]
Hmmm. Are you wondering what kind of telemetry is collected by Windows itself? I'm not sure.

This project's goal is producing an open source, telemetry-free VSCode. I'm sure Windows collects telemetry on its own, but as it is not open source, there isn't much insight available into disabling/avoiding that.

Going to close this issue out, but feel free to reply if you think there might be something else the VSCodium community can clarify for you and I'll reopen it.

**Comment by playgithub** [comment]
ok, just not enough information. If telemtry data is encrypted, it tends to be dangerous. If not encrypted, analyze the data on the wire is ok. I think the format of telemetry data should be open, then I may feel free to let it be collected.
