### ISSUE TITLE
Visual Studio Code intellicode failed to work

### ISSUE THREAD

**Issue by sanatg** [VSCodium/vscodium#766]
HI, i just switched from vscode to vscodium so installed all the extensions.All of them worked fine but Visual Studio Code intellicode was causing errors here is the full error: 

Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.

i was working with a jupyter notebook with jupyter notebook extension enabled and it's not causing the same problem in vscode.

![vscodium-issues-vscode-intelli](https://user-images.githubusercontent.com/62789975/126068810-7aa782be-d96a-475f-8705-338373421a2c.png)

is anyone facing the same problem

**Comment by pm4rcin** [comment]
Which version of Python Extension do you use?

**Comment by sanatg** [comment]
Hi, @pm4rcin for pylance i use v2021.7.4 and for python intellisense i use v2021.7.1053846006 and for the visual studio intellisense i was using v1.2.14.

**Comment by pm4rcin** [comment]
Take a look at the output window (ctrl + k ctrl + h) and create a gist in Github with log from that window.

**Comment by sanatg** [comment]
@pm4rcin will do that and share the output currently i am going some where

**Comment by sanatg** [comment]
@pm4rcin Hey the intellisense extension worked i figured it out it was because of the github copilot as github copilot is not supported on vscodium and continously gives an error it might trigger some errors in intellisense thanks anyway

**Comment by daiyam** [comment]
@sanatg If the issue is resolved, can you close it? Thx

**Comment by sanatg** [comment]
yeah sure sorry forgot!
