### ISSUE TITLE
PPA instructions on vscodium.com are out of date

### ISSUE THREAD

**Issue by rrthomas** [VSCodium/vscodium#769]
See https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/issues/36

The instructions for using the PPA need to be updated to reflect its current location.

Thanks for Codium!

**Comment by bittner** [comment]
I believe this issue can be closed (GitLab issue 36 already is).

I managed to install the Debian package on Ubuntu 20.04 with the instructions from the website today. There are only a few backslashes too many in the code snippets, to make the experience perfect:

```diff
-wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg \ | gpg --dearmor \ | sudo dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg
+wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | gpg --dearmor | sudo dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg
```
```diff
-echo 'deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs vscodium main' \ | sudo tee /etc/apt/sources.list.d/vscodium.list
+echo 'deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs vscodium main' | sudo tee /etc/apt/sources.list.d/vscodium.list
```

I opened https://github.com/VSCodium/vscodium.github.io/pull/50 to fix that.
