### ISSUE TITLE
Marketplace doesn't work anymore

### ISSUE THREAD

**Issue by 30-silver** [VSCodium/vscodium#771]
**Describe the bug**
The marketplace doesn't work. When you install and open VSCodium, it says "We cannot connect to the Extensions Marketplace at this time, please try again later.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install VSCodium
2. Open it
3. Go to the marketplace

**Expected behavior**
For the marketplace to work

**Desktop (please complete the following information):**
 - OS: Windows and Linux
 - Architecture x64
 - Version: Windows 10, Linux Mint

**Comment by daiyam** [comment]
Hi, it's a duplicate of #746.
