### ISSUE TITLE
Getting boxes instead of text while adding a folder

### ISSUE THREAD

**Issue by dhruvrohilla** [VSCodium/vscodium#777]
When i try to add a folder in vscodium instead of name of the folder i get boxes.
(https://user-images.githubusercontent.com/57870732/126977690-583c7d7a-f05e-45f6-aa68-5504e34f5233.png)

**Comment by daiyam** [comment]
OS? Distro? Installer?

If you have installed the app with `snap`, you will find some solution in https://github.com/VSCodium/vscodium/issues/426

**Comment by dhruvrohilla** [comment]
I used snap to install but after many tries i download .deb file from GitHub and then tried installing now its working
