### ISSUE TITLE
VSCodium and Unity

### ISSUE THREAD

**Issue by MagicLike** [VSCodium/vscodium#778]
A few weeks ago, I tried game design with Unity for the first time.
While I was familiarising myself with Unity, I realised, that there is no support to link VSCodium with Unity _(so that all Unity specific commands, arguments, etc. are directly displayed, suggested & corrected in the code editor)_ like with VSCode.
Does anyone have an idea how to do this, _or is it impossible_?

**Comment by hazarek** [comment]
https://docs.unity3d.com/Manual/Preferences.html#External-Tools
