### ISSUE TITLE
`machineid` not removed or faked

### ISSUE THREAD

**Issue by playgithub** [VSCodium/vscodium#782]
**Describe the bug**

On Windows, the key file: %appdata%\VSCodium\machineid

**Expected behavior**
The file `machineid` should be removed

**Desktop (please complete the following information):**
 - OS: Windows
 - Architecture: x64
 - Version: 1.58.2

**Comment by pmahend1** [comment]
why should it be removed?

**Comment by playgithub** [comment]
> why should it be removed?

Because it has no use, but only for tracking.

**Comment by daiyam** [comment]
@playgithub Yes (in VSCode), but not only:

```
scope

A configuration setting can have one of the following possible scopes:

application - Settings that apply to all instances of VS Code and can only be configured in user settings.
machine - Machine specific settings that can be set in user or remote settings. For example, an installation path which shouldn't be shared across machines.
machine-overridable - Machine specific settings that can be overridden by workspace or folder settings.
window - Windows (instance) specific settings which can be configured in user, workspace, or remote settings.
resource - Resource settings, which apply to files and folders, and can be configured in all settings levels, even folder settings.
language-overridable - Resource settings that can be overridable at a language level.
```
https://code.visualstudio.com/api/references/contribution-points

**Comment by playgithub** [comment]
@daiyam 
For machine settings, a folder/file like "machine-settings" is enough, no need for a machine id.

**Comment by jamcinnes2** [comment]
Is this present on Linux?

**Comment by playgithub** [comment]
> Is this present on Linux?

Yes, the path is `~/.config/VSCodium/machineid`

**Comment by daiyam** [comment]
I've taken on look, `machineid` is used in 2 cases:
- Settings Sync
- Telemetry

**Comment by playgithub** [comment]
OK, I've edited it manually to be a fake id.
