### ISSUE TITLE
After update to 1.59 screen is empty 

### ISSUE THREAD

**Issue by tronta** [VSCodium/vscodium#791]
**Describe the bug**
After updating on 1.59 on Fedora 34 screen is empty, and nothing is responsive/works.

**Please confirm that this problem is VSCodium-specific**
VSCode works

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**

**Expected behavior**
![grafik](https://user-images.githubusercontent.com/5135577/128552596-ac3de406-0296-4046-92b4-90066e1d5bd0.png)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/5135577/128552459-ab01b40d-b695-45da-845d-8709023d0467.png)

**Desktop (please complete the following information):**
 - Fedora 34
 - x64
 - Version 1.59.0

**Comment by daiyam** [comment]
What do you get with the command `codium --verbose`?

**Comment by tronta** [comment]
```
[main 2021-08-06T18:53:36.889Z] Sending env to running instance...
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[433169:0806/205337.136405:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

**Comment by daiyam** [comment]
Nothing else? How did you install it?

I've tested it on Fedora 33 by installing directly the rpm and it's working.

**Comment by daiyam** [comment]
Seems to be an issue with Chromim (https://simpleit.rocks/linux/ubuntu/fixing-common-google-chrome-gpu-process-error-message-in-linux/). `1.59` is using one of the latest  version of Electron maybe that why.
Can you try to add `codium  --disable-gpu --disable-software-rasterizer`? I will try with Fedora 34...

**Comment by tronta** [comment]
Same result + 
`Warning: 'disable-software-rasterizer' is not in the list of known options, but still passed to Electron/Chromium.`

**Comment by daiyam** [comment]
The `libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)` isn't a failing error.
On Arch, I'm getting the following message and it's still working: 
```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[5976:0806/220535.238789:ERROR:viz_main_impl.cc(160)] Exiting GPU process due to errors during initialization
[main 2021-08-06T20:05:35.248Z] Starting VS Code
```

How did you install it?

**Comment by tronta** [comment]
As far as I remember I installed it using the instructions on the page:
Add the GPG key of the repository:
`sudo rpmkeys --import https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg`

Add the repository:
    Fedora/RHEL:
`printf "[gitlab.com_paulcarroty_vscodium_repo]\nname=gitlab.com_paulcarroty_vscodium_repo\nbaseurl=https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg" |sudo tee -a /etc/yum.repos.d/vscodium.repo`

**Comment by daiyam** [comment]
Can you try the `.tar.gz`? (cmd: `bin/codium`) or the AppImage? Have you tried VSCode?

**Comment by tronta** [comment]
I was not able to start `bin/codium` it said error in format of the program (loosely translated).
Yes I installed VScode with the latest provided .rpm file and it worked.
Flatpak also fails to start
```
:flatpak run com.vscodium.codium --verbose
codium-wrapper: Evaluating /usr/lib/sdk/node12/enable.sh
codium-wrapper: Setting up NPM packages
codium-wrapper: Setting up Cargo packages
codium-wrapper: Setting up Python packages
[18:0806/222457.695806:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/share/codium/chrome-sandbox is owned by root and has mode 4755.
```

**Comment by daiyam** [comment]
I don't have the issue with Fedora 34 in my virtualbox...
Can you try the option `--no-sandbox`? Have you a custom product.json?

**Comment by tronta** [comment]
`codium --no-sandbox`  does not produce a different result to `codium`.
I'm not aware of having changed `product.json` to anything specific.

**Comment by gbonline** [comment]
Hi, the same problem with Ubuntu 20.04 or 21.04. 
the same problem is present in vs code from ms..
Temporary fix:  start codium with param --disable-gpu

**Comment by tronta** [comment]
For me `--disable-gpu` has no effect.

**Comment by tronta** [comment]
after a reinstall, it worked
