### ISSUE TITLE
json settings editor

### ISSUE THREAD

**Issue by OneOfOne** [VSCodium/vscodium#794]
With microsoft completely ignoring the voices of the community (shocking, right?), is there any chance you guys can revert that horrible bug they introduced?

https://github.com/microsoft/vscode/issues/125952

**Comment by daiyam** [comment]
Damn! I've really though that the split had removed few months back!! I just found that it's option to check. No wonder that ` it is used very little`... By the way, I'm editing the setting in JSON.

I will have to understand why it has been deprecated and removed in the first place.
When I've started using VSCode, I did like that feature and though that it was nice.

In the meantimes, you are welcome to make a PR.

**Comment by daiyam** [comment]
The old split JSON settings editor is more useful because when searching, the unmatched properties are hidden.

I think the split JSON settings editor should be the default, like 2-3 years ago. The GUI isn't very useful...

**Comment by carlocardella** [comment]
You might want to up vote this issue (not sure it will make any difference but we can try): https://github.com/microsoft/vscode/issues/129594

**Comment by daiyam** [comment]
Here the patch to add back the previous JSON settings editor:
[json-settings-editor.patch.zip](https://github.com/VSCodium/vscodium/files/6986110/json-settings-editor.patch.zip)

I've just copied the old version from `1.58` and fixed the few changes...

**Comment by Crystal-RainSlide** [comment]
To access JSON settings:
<kbd>F1</kbd> or <kbd>Ctrl + Shift + P</kbd> - `> Preferences: Open User Settings (JSON)`

Commands:
- `workbench.action.openSettingsJson`
- `workbench.action.openApplicationSettingsJson`

**Comment by daiyam** [comment]
I don't think we will re-implement the JSON settings editor. It will take too much time.

@Crystal-RainSlide It was when the JSON settings editor was a split editor between the current editor and the reference file with sync search and other....

**Comment by Crystal-RainSlide** [comment]
hmmm

`workbench.settings.useSplitJSON`

![hmmm](https://user-images.githubusercontent.com/16851802/197537510-e96b308d-1a52-4f5e-a29c-57f32ce4de0c.png)

**Comment by daiyam** [comment]
@lonix1 Ya... Sorry Me too, I'm sad.
@Crystal-RainSlide No, not the same... The old one was 1 editor with 1 search. The new is 2 editors with 2 searchs.

**Comment by Crystal-RainSlide** [comment]
hmmm (*2)

This one don't seems like started though

> https://github.com/zokugun/MrCode#split-json-settings-editor

> ### split JSON settings editor

> I will try to add back the split JSON settings editor via an extension.
