### ISSUE TITLE
How to enable C++ auto-completion in cmake project?

### ISSUE THREAD

**Issue by playgithub** [VSCodium/vscodium#795]
## Env
OS: Linux
vscodium: 1.59.0

## Problem
Be default no "Microsoft C/C++ extension" in the extension marketplace.
When using cmake for a C++ project, I found intellisense (e.g. auto-completion) doesn't work properly.

## More Info
```
$ du -hs ~/.cache/vscode-cpptools/ipch
729M ...
```
And there are revelvant ".ipch" files for the project files.

## Question
camke add include dirs in cmake files,  Visual Studio 2019 and Qt Creator know about this, and intellisense works well.
For vscodium, project built by g++, tried as below, no one helps:
* vscodium default installion
* extention clangd
How to let intellisense work? Does "Microsoft C/C++ extension" have to be installed?

**Comment by DrasLorus** [comment]
Hi, I have faced this a while ago.

Intellisense in MS VSCode build a database based on the CMakeLists.txt, but the MS C++ extension is needed indeed. To easily replace that with clangd, you can enable [CMAKE_EXPORT_COMPILE_COMMANDS](https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html) with

``` cmake
set (CMAKE_EXPORT_COMPILE_COMMANDS true)
```

It will export a `compile_commands.json`, which clangd will use as a compilation database (relevant clangd documentation [here](https://clangd.llvm.org/design/compile-commands)). 

The CMakeTools extension also provides similar features.

Intellisense may work like clangd, it is worth trying if clangd does not suite you.

**Comment by playgithub** [comment]
It works, thanks.
