### ISSUE TITLE
[1.59] Extension marketplace not working

### ISSUE THREAD

**Issue by jwaggy** [VSCodium/vscodium#796]
**Describe the bug**
According to a previous issue on github (#746) I was told that the extension bar would be functional after an update to 1.59 and that has not been the case.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open VSCodium
2. Go to Extensions bar
3. Type anything

**Expected behavior**
I expected to see a list of extensions available.

**Screenshots**
![image](https://user-images.githubusercontent.com/24530821/128887681-d70e5372-ccf9-4788-93e7-0fb4c6a8ec04.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Architecture x86_64
 - Version 1.59.0

**Additional context**
N/A

**Comment by jwaggy** [comment]
// This configuration file allows you to pass permanent command line arguments to VS Code.
// Only a subset of arguments is currently supported to reduce the likelihood of breaking
// the installation.
//
// PLEASE DO NOT CHANGE WITHOUT UNDERSTANDING THE IMPACT
//
// NOTE: Changing this file requires a restart of VS Code.
{
	// Use software rendering instead of hardware accelerated rendering.
	// This can help in cases where you see rendering issues in VS Code.
	// "disable-hardware-acceleration": true,

	// Enabled by default by VS Code to resolve color issues in the renderer
	// See https://github.com/microsoft/vscode/issues/51791 for details
	"disable-color-correct-rendering": true,

	// Allows to disable crash reporting.
	// Should restart the app if the value is changed.
	"enable-crash-reporter": true,

	// Unique id used for correlating crash reports sent from this instance.
	// Do not edit this value.
	"crash-reporter-id": "f59c8d85-87ec-48d5-a3ca-d7ded6e6d3e9"
}

**Comment by daiyam** [comment]
Nothing unusual. I've tested the v1.59 on Windows 10 and the extension marketplace is working correctly.
How have install VSCodium? Directly from the github/website or from an app store?

**Comment by daiyam** [comment]
@yattaro `1.59` should not have this issue as I've included a fix for it. This is why I try to understand why @jwaggy is getting it.

**Comment by glhez** [comment]
Hello,

I also encounter the same problem :

```
Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-06T00:09:27.605Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
```

The dev console is showing:

> Access to XMLHttpRequest at 'https://open-vsx.org/vscode/gallery/extensionquery' from origin 'vscode-file://vscode-app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I did install from github as user setup.

**Comment by daiyam** [comment]
@glhez The file `~\AppData\Local\Programs\VSCodium\resources\app\out\main.js` should have a modified date of `August 6`

**Comment by glhez** [comment]
That's the date I have : {{‎vendredi ‎6 ‎août ‎2021, ‏‎00:09:34}}.
The SHA1 is 
```
Nom: main.js
Taille: 8676 octets (8 KiB)
SHA1: 02C2DAD5487E724DBADD8047FA6EE33CFF5FAAB4
```

**Comment by glhez** [comment]
I also tried WinMerge on the X64 ZIP (https://github.com/VSCodium/vscodium/releases/download/1.59.0/VSCodium-win32-x64-1.59.0.zip) and this folder.
All files are identical, apart from these files:

- `%USERPROFILE%\AppData\Local\Programs\VSCodium\resources\app\product.json`
- `%USERPROFILE%\AppData\Local\Programs\VSCodium\unins000.dat`
- `%USERPROFILE%\AppData\Local\Programs\VSCodium\unins000.exe`
- `%USERPROFILE%\AppData\Local\Programs\VSCodium\debug.log`

**Comment by daiyam** [comment]
I have the same SHA1 for `main.js`. It's that file which contains the fix...
What the diffs in `%USERPROFILE%\AppData\Local\Programs\VSCodium\resources\app\product.json`?

**Comment by glhez** [comment]
The file: [product-appdata.txt](https://github.com/VSCodium/vscodium/files/6977441/product-appdata.txt)

Most of the changes are due to format : there is only an additional json attribute: `"target": "user"` at the end of the file (after formatting both file): 
![image](https://user-images.githubusercontent.com/10855953/129243083-705c0522-46cf-44cf-875d-97076ed189f1.png)
(Above is the release ZIP JSON, Below is the AppData JSON).

**Comment by daiyam** [comment]
Can you check if you don't have the argument `__sandbox` in the command line launching VSCodium?
Or if you have the environment variable `VSCODE_BROWSER_CODE_LOADING`?

**Comment by glhez** [comment]
If that may help, here is the complete log when trying to update extensions: 
[vscode-app-1628790229217.log](https://github.com/VSCodium/vscodium/files/6977487/vscode-app-1628790229217.log)

Also, I dig the trace a little and here what the call that fails is doing: this is what the "options" parameter contains when putting a breakpoint at line 12 in request.ts (the line contains `if (options.proxyAuthorization) {`):

- I formatted the value and remove the filters and UUID (I don't know if this information is a personal data but I don't think it is relevant here).
- I am no javascript/typescript expert; as for the HTTP error, we can see no special header.  In the network tab, I can see a `Referrer Policy: strict-origin-when-cross-origin`.


```
{
  "type": "POST",
  "url": "https://open-vsx.org/vscode/gallery/extensionquery",
  "data": {  // I took the liberty to extract the JSON inside data and format it below
    "filters": [
      {
        "criteria": [
          ... some criteria ...
        ],
        "pageNumber": 1,
        "pageSize": 11,
        "sortBy": 0,
        "sortOrder": 0
      }
    ],
    "assetTypes": [],
    "flags": 950
  },
  "headers": {
    "X-Market-Client-Id": "VSCode 1.59.0",
    "User-Agent": "VSCode 1.59.0",
    "X-Market-User-Id": "(some UUID)",
    "Content-Type": "application/json",
    "Accept": "application/json;api-version=3.0-preview.1",
    "Accept-Encoding": "gzip",
    "Content-Length": "902"
  },
  "proxyAuthorization": null
}
```

**Comment by glhez** [comment]
> Can you check if you don't have the argument `__sandbox` in the command line launching VSCodium?
> Or if you have the environment variable `VSCODE_BROWSER_CODE_LOADING`?

In process explorer:

- I don't see anything passed to the command line. So, no `__sandbox` unless you have a way to get the command line that launched vscodium from the console?
- I can see `VSCODE_BROWSER_CODE_LOADING=bypassHeatCheck` in the Environment tab of Process in Process Explorer. However this one is **not** defined in my Environment settings. 

I think I get _my_ problem now: I don't know what defined this environment variable, but it was probably present when I launched VSCodium this morning. Since it proposed an update, I did update: the update restarted vscodium but with the environment variable still present.

A stop and start seems to fix the problem (no error in "Update extension"). 

At least, it resolved for me 👍 

Thanks for the input.

**Comment by daiyam** [comment]
Since `1.58`, the requests are running in chromium which requires CORS. Before and in the "fixed" `1.59`, the requests are done by nodejs which don't require CORS.

Can you try the fix at https://github.com/VSCodium/vscodium/issues/746#issuecomment-881049046? If it's working, there would a cache issue in Windows...

**Comment by daiyam** [comment]
Oh! @glhez Is it fixed? What's your `stop and start`?

**Comment by glhez** [comment]
Simply as said : I stop VSCodium (eg: quit VSCodium), then restart it from the start menu. So : stop and start :)

**Comment by daiyam** [comment]
@glhez Ok, I just wanted to be sure. Thx

**Comment by jwaggy** [comment]
It randomly started working without a restart so I'm not sure what the deal was. I'll close this issue I guess.
