### ISSUE TITLE
snap packge is older (1.56.0)

### ISSUE THREAD

**Issue by salemkode** [VSCodium/vscodium#798]
We are in 1.59 verison 

Why?

**Comment by paulcarroty** [comment]
Ask the maintainers, seems like they abandoned the snap 'cause last build happened in May.

Snap builds can be automated, so PRs are welcome.

**Comment by daiyam** [comment]
It seems like a reorganisation: https://forum.snapcraft.io/t/snapcrafters-reboot/24625

I've asked to become a maintainer of the snap. Will see what happens...

**Comment by daiyam** [comment]
@stripedpajamas I have a working workflow to publish the snap but it requires a Snap account. I have one but I think it shouldn't be published under my name. It would be better you create one or we create a snap store brand account.
If I setup that workflow, I would need to add a secret or to give it to you. We need another way to exchange :wink:

**Comment by stripedpajamas** [comment]
Makes sense, I think I actually made a vscodium snap account a while ago. I will send you the credentials.

**Comment by daiyam** [comment]
You can contact me at daiyam@zokugun.org.

**Comment by paulcarroty** [comment]
Any progress here? Someone asked me about it.

**Comment by daiyam** [comment]
I have to take time to finalize it.

**Comment by daiyam** [comment]
Ya, the transfer has just happened a few hours ago. I've just update pushed the edge version to stable. Necessary updates will come soon.

**Comment by daiyam** [comment]
You can find the changes I'm making at https://github.com/VSCodium/vscodium/pull/942.

**Comment by julian-alarcon** [comment]
I think that this can be closed now

**Comment by daiyam** [comment]
From now on, the workflow `linux_build` is building and publishing the snaps (amd64 & arm64) when the versions of the snaps and of the release are different.
