### ISSUE TITLE
How to debug C++ in vscodium?

### ISSUE THREAD

**Issue by playgithub** [VSCodium/vscodium#799]
By default no `ms-cpptools` in the extension market, any alternatives?
I think it's hard on Windows, what about on Linux?

**Comment by daiyam** [comment]
@playgithub I don't know but the extension is open source and seems to be licensed under MIT. So a rebuild seems possible.

**Comment by playgithub** [comment]
Thanks

**Comment by GitMensch** [comment]
There is no `ms-cpptools`, but [`vscode-cpptools`](https://github.com/Microsoft/vscode-cpptools), which is proprietary. This is also noted in the README under [Proprietary Debugging Tools](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#proprietary-debugging-tools).
This is also the reason that this extension cannot be found in the default extension market.

In general I can highly recommend the Native Debug extension [`webfreak.debug`](https://open-vsx.org/extension/webfreak/debug) which works fine on Linux and Windows with GDB and some other debuggers and depending on your GDB version (on Windows I recommend the gdb-multiarch one from MSY2) you can also cross-debug to different architectures.

**Comment by playgithub** [comment]
> In general I can highly recommend the Native Debug extension [`webfreak.debug`](https://open-vsx.org/extension/webfreak/debug) which works fine on Linux and Windows with GDB and some other debuggers and depending on your GDB version (on Windows I recommend the gdb-multiarch one from MSY2) you can also cross-debug to different architectures.

Thanks very much, prefer it to `vscode-cpptools` if it works properly.

**Comment by YasirAnqa** [comment]
> In general I can highly recommend the Native Debug extension [`webfreak.debug`](https://open-vsx.org/extension/webfreak/debug) which works fine on Linux and Windows with GDB and some other debuggers and depending on your GDB version (on Windows I recommend the gdb-multiarch one from MSY2) you can also cross-debug to different architectures.

Can someone please tell us how to get it to work? I spent weeks trying to understand how to get debugging to work and I just can't figure it out for the life of me. I googled and read the wiki/readme of the extension but nothing it says makes sense. I don't know if that's because I'm using LInux, or because it works differently in VSCodium vs VSCode. Or whether it was explained in an outdated version. All I know is that I did all I could to understand how to set it up properly and failed.

This is probably the wrong place to ask this, but I'm desperate; a simple howto would be appreciated.

**Comment by playgithub** [comment]
The author said

> it might work if you install the C/C++ extension from the marketplace, but this should be fixed with next release

https://github.com/WebFreak001/code-debug/issues/286

**Comment by YasirAnqa** [comment]
> The author said
> 
> > it might work if you install the C/C++ extension from the marketplace, but this should be fixed with next release
> 
> [WebFreak001/code-debug#286](https://github.com/WebFreak001/code-debug/issues/286)

Thank you so much for this!
