### ISSUE TITLE
Where are binaries for Win? (v.1.31)

### ISSUE THREAD

**Issue by WrongBit** [VSCodium/vscodium#80]
Guys, you spend your time to compile for Apple, but didn't make binaries for Windows??? Serious? In what world do you live, Narnia?

**Comment by stripedpajamas** [comment]
Hi @WrongBit 👋

We have spent some time getting Windows binaries, but it looks like the most recent build (1.31) failed. I'm troubleshooting that now but with some luck you should see the Windows binaries for the latest version on the releases page in a short while.

**Comment by stripedpajamas** [comment]
It's up there now
