### ISSUE TITLE
Codium using up too many resources

### ISSUE THREAD

**Issue by wibed** [VSCodium/vscodium#805]
**Describe the bug**
vscode had the issue that until telemetry has been turned off, it started eating up resources aggressively.
so i moved to vscodium. but vscodium shows the same behaviour. without the caps to turn the aggressive process off.

**Please confirm that this problem is VSCodium-specific**
- [ x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. clone repo https://github.com/wibed/ideVScode 
2. run it, it may need some tweeks.
3. watch all cpu cores get exhausted at 99%

**Expected behavior**
to not use up all resources running an ide

**Desktop (please complete the following information):**
 - OS: void linux
 - Architecture amd64-musl
 - Version 1.59.1

**Additional context**
the only thing you need is to have X11 display at /tmp/.X11-unix to run the container
example:
```
make sync && make run
```

**Comment by wibed** [comment]
it seems codium is repeating the following log message ad infinitum, leading to a high cpu usage:
```
[23:0824/031636.378710:INFO:CONSOLE(630)] "%cTRACE color: #888 [File Watcher (node.js)] [CHANGED] /home/user/logs/20210824T031634/renderer1.log", source: file:///usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js (630)
```

i tried starting codium with:
- `--disable-gpu`
- `--disable-renderer-accessibility`
- `--log off/trace`

to no avail

**Comment by daiyam** [comment]
Yep, it's a known issue of VSCode. It is due that the log file is watched and a new log entry is generated to indicate that event. So a perfect loop... By removing the trace level, that behavior is disabled.

**Comment by wibed** [comment]
@daiyam could you explain or linkt to a solution on how to disable it.

**Comment by daiyam** [comment]
Just avoid to launch codium with the option `--log trace`. 
The code source might need to be patched but don't quite remember (I've looked at this problem a few weeks ago).

**Comment by wibed** [comment]
https://github.com/microsoft/vscode/issues/132483#issuecomment-926037356

it seems to be related to this issue

**Comment by daiyam** [comment]
great news!
