### ISSUE TITLE
The command to add the apt key for Debian/Ubuntu does not work on Debian 11

### ISSUE THREAD

**Issue by john01dav** [VSCodium/vscodium#810]
**Describe the bug**

Note that the written key file is empty, and the gpg errors when running the provided command:
```
<redacted>@debian-11:~$ wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg \ | gpg --dearmor \ | sudo dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg
gpg: can't open ' ': No such file or directory
gpg: dearmoring failed: No such file or directory
0+0 records in
0+0 records out
0 bytes copied, 1.0598e-05 s, 0.0 kB/s
<redacted>@debian-11:~$ ls -sh /usr/share/keyrings/vscodium-archive-keyring.gpg 
0 /usr/share/keyrings/vscodium-archive-keyring.gpg
```

**Please confirm that this problem is VSCodium-specific**
N/A, as it is VS Codium's instaler

**Please confirm that the issue/resolution isn't already documented**
- [ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Get Debian 11
2. Install VS Code
3. Fail

**Expected behavior**
I expect the provided command to work, or for another to be provided for Debian 11 in particular.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Architecture x86_64/amd64

More information:
```
$ neofetch
       _,met$$$$$gg.          david@debian-11 
    ,g$$$$$$$$$$$$$$$P.       --------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) x86_64 
 ,$$P'              `$$$.     Host: Z390 M GAMING 
',$$P       ,ggs.     `$$b:   Kernel: 5.10.0-8-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 17 mins 
 $$P      d$'     ,    $$P    Packages: 2246 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.1.4 
 $$;      Y$b._   _,d$P'      Resolution: 1440x900, 1920x1080, 1920x1080 
 Y$$.    `.`"Y$$$$P"'         DE: Plasma 5.20.5 
 `$$b      "-.__              WM: KWin 
  `Y$$                        WM Theme: Breeze 
   `Y$$.                      Theme: Breeze Dark [Plasma], Breeze [GTK2/3] 
     `$$b.                    Icons: breeze-dark [Plasma], breeze-dark [GTK2/3] 
       `Y$$b.                 Terminal: konsole 
          `"Y$b._             CPU: Intel i9-9900K (16) @ 5.000GHz 
              `"""            GPU: Intel CoffeeLake-S GT2 [UHD Graphics 630] 
                              GPU: NVIDIA GeForce GTX 1070 
                              Memory: 1960MiB / 31971MiB 
```

**Additional context**
I'm going to try to find a way to install despite the broken command, but no matter what I find, there is indeed a bug, hence the report.

**Comment by john01dav** [comment]
Manually downloading, dearmoring, then moving the key works, in 3 separate commands:
```
wget https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
gpg --dearmor pub.gpg # writes pub.gpg.gpg
sudo cp ./pub.gpg.gpg /usr/share/keyrings/vscodium-archive-keyring.gpg
rm pub.gpg pub.gpg.gpg
# now proceed as normal, with the given commands
```

**Comment by paulcarroty** [comment]
@john01dav where you found the commands above?

**Comment by john01dav** [comment]
They're from the vs codium home page, under the debian section:
https://vscodium.com/

**Comment by paulcarroty** [comment]
@PalinuroSec revert the https://github.com/VSCodium/vscodium.github.io/commit/732917a587b2a65875b69dc7c40e830b83e42892 , there's no sense to use `\` in one-liner.

**Comment by MarkJeronimus** [comment]
I installed it at home last week and it worked. Today I wanted to install it at work and it didn't work. Apparently some backslashes found it's way into the command:
`wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg \ | gpg --dearmor \ | sudo dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg ` 

should be `wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | gpg --dearmor | sudo dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg`

(also all the commands on the home page seem to have a trailing space for some reason)
