### ISSUE TITLE
Please enhance the repo add commands on https://vscodium.com/

### ISSUE THREAD

**Issue by mlandres** [VSCodium/vscodium#813]
Hi.

Please have a lok at `https://vscodium.com/#install`
Section: `Fedora / Centos / OpenSUSE (rpm package):`
The `printf "[gitlab.com_paulcarroty_vscodium...." ` commands to add repos on fedora / suse should IMO have a trailing `\n`.

We get bugreports after people accidentally executed the command twice:
`gpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg[gitlab.com_paulcarroty_vscodium_repo]`

Due to the missing `\n` it messes up the  vscodium.repo file and it's not usable afterwards.

Thanks.

**Comment by paulcarroty** [comment]
#810
