### ISSUE TITLE
Update menu is missing when building from source

### ISSUE THREAD

**Issue by yinhunfeixue** [VSCodium/vscodium#814]
**Describe the bug**
1. run `build/build_macos.sh`
2. Open the `VSCode-darwin-x64/VSCodium.app`
2. There is no "Update menu"
![image](https://user-images.githubusercontent.com/29660825/132639801-c8524c1d-1f4e-4cfa-b2b4-ed4348689798.png)

**Comment by daiyam** [comment]
The update menu is missing because there is no update url in the product.json. It must be due to that product.json hasn't been correctly updated.

**Comment by yinhunfeixue** [comment]
> The update menu is missing because there is no update url in the product.json. It must be due to that product.json hasn't been correctly updated.

Product JSON has updateurl, It is set in prepare_vscode.sh

![image](https://user-images.githubusercontent.com/29660825/132614243-e5c0864b-5fb9-49d4-b48e-378a50166af7.png)

**Comment by stripedpajamas** [comment]
What do you mean by Update Menu? It wouldn't prompt to update if you've built the latest version. Screenshot?

**Comment by yinhunfeixue** [comment]
visual code
![image](https://user-images.githubusercontent.com/29660825/132616639-f7d415af-a693-40dc-adad-6e534e802ba9.png)


vscodium
![image](https://user-images.githubusercontent.com/29660825/132616684-6ab275d0-b64a-4328-a629-3df180edffe0.png)

**Comment by stripedpajamas** [comment]
I see. As far as I know, the updateUrl property is the only thing required, and it appears you have that set. Perhaps updates are disabled completely in settings.json? Not sure if that is even possible.

**Comment by yinhunfeixue** [comment]
> I see. As far as I know, the updateUrl property is the only thing required, and it appears you have that set. Perhaps updates are disabled completely in settings.json? Not sure if that is even possible.
 
This setting?
![image](https://user-images.githubusercontent.com/29660825/132618790-93b06d34-cf94-4ae4-8459-d8ec5af7b7d2.png)

**Comment by stripedpajamas** [comment]
Yeah. Looks good.

**Comment by daiyam** [comment]
Have you a product.json in `~/Library/Application Support/VSCodium`?

**Comment by yinhunfeixue** [comment]
> Have you a product.json in `~/Library/Application Support/VSCodium`?

no， but directory `/Applications/VSCodium.app/Contents/Resources/app/product.json` has this file

![image](https://user-images.githubusercontent.com/29660825/132639533-f1e4a16d-01c5-440c-86e9-1bc1ad76d7d7.png)
