### ISSUE TITLE
use codium from another linux user ?

### ISSUE THREAD

**Issue by ka223** [VSCodium/vscodium#815]
Hi,

I tried to use codium (version VSCodium-linux-x64-1.59.1) from another user.
OS ubuntu 20.04.3

Switched to another user on terminal with:
	xhost +local:
        su otherUser
```
VSCodium-linux-x64-1.59.1$ ./codium 
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[main 2021-08-31T11:34:23.520Z] Error: listen EACCES: permission denied /run/user/1002/vscode-********-1.59.1-main.sock
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1463:5)
...
```

My current user ID is 1002, the user ID from "otherUser" is some other ID.
I had no problems using other programs by su to another user.

**Comment by GitMensch** [comment]
It seems that libva wants (possibly needs) to create something in your user space - and this doesn't work because you are a different user now. Does it work if you directly login to the machine as another user?

Do you mind if we move that to discussions Q+A?

**Comment by ka223** [comment]
If i am logged in as "otherUser", codium is working fine.
The problem exist in my use-case, when the program is started by another user. 

Yes, if it is not a bug, which only visible in this use-case.

**Comment by GitMensch** [comment]
Ideally you could check if this also happens with VSCode, as then we'd know this is an upstream bug (very likely it is) which should be filed there.

**Comment by ka223** [comment]
Yes, seems to be a VScode problem.
https://github.com/microsoft/vscode/issues/132924

**Comment by GitMensch** [comment]
Thanks for checking, I'm closing this here then and monitor the other issue :-)
