### ISSUE TITLE
The window has crashed (reason: 'crashed', code: '-1073741571')

### ISSUE THREAD

**Issue by justanotheranonymoususer** [VSCodium/vscodium#820]
**Describe the bug**
Window crashes on paste.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to [here](https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/vscode.proposed.d.ts), select all text and copy to clipboard
2. Open VSCode, create new document, paste, go to top
3. Ctrl+F and paste
4. Observe a crash

**Expected behavior**
Anything but a crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/5781692/132118368-df7f5041-830c-4fbb-9feb-120db6d1e680.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Architecture x64
 - Version 1.59.1

**Additional context**
VSCode has a similar issue, but no crash:
https://github.com/microsoft/vscode/issues/132371

**Comment by daiyam** [comment]
@justanotheranonymoususer I'm sorry the bug can't be reproduced

**Comment by justanotheranonymoususer** [comment]
@daiyam after some testing, I found that I can only reproduce it on the 32-bit version, not 64-bit (`VSCodium-win32-ia32-1.59.1`). I used a portable version, if that matters. I can make a video. Still couldn't reproduce it with vscode, even 32-bit.

**Comment by daiyam** [comment]
@justanotheranonymoususer Well that's good. `VSCodium v1.60` should be out tonight.

**Comment by GitMensch** [comment]
The update is out now. @justanotheranonymoususer please test, report and if possible close this issue. Thanks.

**Comment by justanotheranonymoususer** [comment]
It no longer crashes, although as I wrote in the vscode issue, it's probably a coincidence and not truly fixed. But it's on their side in any case.

**Comment by Riazalmahmud** [comment]
![image](https://user-images.githubusercontent.com/45636102/140990141-d1120911-7091-4dcd-a080-13082c65169d.png)
same problem
