### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by cuman098** [VSCodium/vscodium#821]
**Describe the bug**

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS, Ubuntu 16.04, etc]
 - Architecture [e.g. x64, ia32, arm64]
 - Version [e.g. 1.33.0]

**Additional context**

**Comment by daiyam** [comment]
Empty bug report
