### ISSUE TITLE
Missing armhf release?

### ISSUE THREAD

**Issue by drupol** [VSCodium/vscodium#828]
Hi,

Release 1.60.0 has been tagged and it seems that Linux version `armhf` is missing.
Compare [1.60.0](https://github.com/VSCodium/vscodium/releases/tag/1.60.0) with [1.59.1](https://github.com/VSCodium/vscodium/releases/tag/1.59.1) to see it by yourself.

Thanks for letting me know what is going on.

**Comment by daiyam** [comment]
yep, I've a fix for that. The issue was due to a network timeout...

**Comment by daiyam** [comment]
This is weird, I'm getting the error:
- failed, reason: read ECONNRESET ([source](https://github.com/VSCodium/vscodium/runs/3528784478?check_suite_focus=true))
- failed, reason: socket hang up ([source](https://github.com/VSCodium/vscodium/runs/3562354043?check_suite_focus=true))

A network error on the same file...

**Comment by daiyam** [comment]
OK. I've figured out that the first workflow run has adde a blank file. So other runs were failing because the name was already taken... I had to delete that blank file and rerun the workflow to successfully release the file.

**Comment by drupol** [comment]
Thanks! Going to move forward on Nixos now to have this update ;)

**Comment by daiyam** [comment]
The issue is back... not sure why.
I will need to modify the workflow to release only the binaries which haven't been released. I will try to do that today or tomorrow.

**Comment by AdelKS** [comment]
But this time it's `arm64` :thinking:

**Comment by daiyam** [comment]
Oops, it's for arm64...

**Comment by AdelKS** [comment]
I saw that the reason for these problems is a network error. It makes sense that it is not specific to any arch no ?

**Comment by daiyam** [comment]
@AdelKS yes it does. But it's weird that it's just happened 2 times in row for only Linux arm (64 or 32) builds... maybe just bad luck.

**Comment by AdelKS** [comment]
Is the same server/docker, the reason may be worth investigating 🤔

**Comment by etienne1911** [comment]
seems like arm64 is stll not available
cannot find it in releases for 1.60.2 while it is present in 1.60.1 :/

**Comment by daiyam** [comment]
The workflows have been modified to only build unavailable binaries.
`VSCodium-linux-arm64-1.60.2.tar.gz` has been published.

**Comment by AdelKS** [comment]
@daiyam the `armhf` release is missing again on 1.67.0

**Comment by daiyam** [comment]
@AdelKS Yes, I'm not able to built the 32bit versions (linux and windows), yet. I tried several things but can't make it work out. It's an issue with the dependencies.

Here a opened issue about it: https://github.com/VSCodium/vscodium/issues/1072

**Comment by AdelKS** [comment]
Thanks for your feedback and your hard work @daiyam !
