### ISSUE TITLE
Please document how to rebuild locally

### ISSUE THREAD

**Issue by olberger** [VSCodium/vscodium#83]
Even though the purpose may be to release already built packages, I guess it would be better to document the build process, so that one can redo and not fear MitM...

AFAICS the .travis.yml can lead to needed commands ATM.

Hope this helps,

**Comment by stripedpajamas** [comment]
Hi @olberger 👋 

The purpose of this project is only to provide the built packages. Since this isn't a fork, it's just a bunch of automated build scripts, you can follow Microsoft's own build documentation to do it yourself: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run
