### ISSUE TITLE
Download count of extension API doesnt seem to be working

### ISSUE THREAD

**Issue by pmahend1** [VSCodium/vscodium#836]
The download count of extension API doesnt seem to be working anymore. My extension download count is same from months.
 I can surely say there should be atleast 1 increase in the count since at least its me who is updating.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Check extension install count in VSCodium -> Extensions
2. Notice that it wont change after hours/days.

**Expected behavior**
The install count API should return updated install count

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS, Ubuntu 16.04, etc] : NA
 - Architecture [e.g. x64, ia32, arm64] : NA
 - Version [e.g. 1.33.0] : Seems like recent few versions

**Comment by daiyam** [comment]
Well, it's the count from OpenVSX so yes, 89 is quite different than 9871...
By the way, OpenVSX doesn't have the latest version.

**Comment by pmahend1** [comment]
I know it is from OpenVSX, but the count isnt updating from quite some time now.
My extensions are at 89, [2016](https://open-vsx.org/extension/PrateekMahendrakar/prettyxml) from long which seems unusual. 

I know understand this has been filed already at [OpenVSX GitHub](https://github.com/eclipse/openvsx/issues/283)

So I am going to close this one.
