### ISSUE TITLE
Can't select correct Python Interpreter

### ISSUE THREAD

**Issue by OliverGeneser** [VSCodium/vscodium#840]
**Describe the bug**
I'm trying to select my python interpreter in my virtual environment, but it only shows python 3.8.8 even though I have 3.9.5.

VSCodium
![Screenshot from 2021-09-13 20-32-46](https://user-images.githubusercontent.com/32340667/133138423-2f589f46-5ece-4431-9530-5f57d47becc2.png)

VSCode
![Screenshot from 2021-09-13 20-38-30](https://user-images.githubusercontent.com/32340667/133138578-2c5dc2c6-0191-48ac-834c-cfe15636bef2.png)

**Please confirm that this problem is VSCodium-specific**
- [* ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ *] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Click on 'Select Interpreter'
2. Only shows python 3.8.8

**Expected behavior**
I expect to see my install of Python 3.9.5 and the virtual environment.

**Screenshots**
VSCodium
![Screenshot from 2021-09-13 20-32-46](https://user-images.githubusercontent.com/32340667/133138423-2f589f46-5ece-4431-9530-5f57d47becc2.png)

VSCode
![Screenshot from 2021-09-13 20-38-30](https://user-images.githubusercontent.com/32340667/133138578-2c5dc2c6-0191-48ac-834c-cfe15636bef2.png)

**Desktop (please complete the following information):**
 - OS: POP_OS! 21.04
 - Architecture x64
 - Version 1.60.0

**Comment by manero6** [comment]
Same for me.

System:

```bash
python -V
Python 3.10.3

which python
/usr/bin/python
```

VSCodium:

```bash
python -V
Python 3.9.9

which python
/usr/bin/python
```

I suppose this version is the one installed through the ms-python extension (??)
Because I have no other python3 version installed in my system, only 3.10.3

**Comment by manero6** [comment]
I have a similar problem with PyCharm-Community.

I installed both packages using Flatpak.
I think this might be causing the issue, as inside both VSCodium and PyCharm running `echo $PATH` shows a different value than on my system.

**Comment by manero6** [comment]
I just uninstalled the Flatpak package and installed VSCodium using the official rpm repo for Fedora (as described here https://vscodium.com/#install)

The problem is gone! I can now use the correct system python binary.
`echo $PATH` inside VSCodium shows the correct value.

**Comment by paulcarroty** [comment]
Please move/link this issue to vscodium flathub repository.
