### ISSUE TITLE
Unable to write into user settings

### ISSUE THREAD

**Issue by ThomasTraineau** [VSCodium/vscodium#846]
I am having troubles changing some extensions settings.
For example, after installing the "prettier" extension, when I check the "format on save box", I get the error "Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.". But adding '"editor.formatOnSave": true' in the settings.json doesn't seem to take effect (no changes after saving an incorrectly formatted file)

**Comment by daiyam** [comment]
That error is due to that your `settings.json` isn't a valid JSONC (JSON with Comments) file.
Can you check it? If you can't find the error, you can post it here (in a gist or a code block).

**Comment by ThomasTraineau** [comment]
That was indeed the problem, I was missing a coma...
