### ISSUE TITLE
SHA change for 1.60.1 release?

### ISSUE THREAD

**Issue by drupol** [VSCodium/vscodium#847]
Hi,

I contribute to the nixos distribution and we are using tools to detect if a project has been updated or when a new release is published.

Yesterday, that tool created a PR for version 1.60.1: https://github.com/NixOS/nixpkgs/pull/138003

Once that PR is merged, I usually add a specific tag in the PR so the tool can create a PR to update vscodium in another branch: https://github.com/NixOS/nixpkgs/pull/138126

However, that PR failed to build because of a error while checking the sha256: https://github.com/NixOS/nixpkgs/pull/138161

Pretty weird because the issue hasn't been triggered initially... And the build processes are the same.

So this message is to know if the binaries that were uploaded on the release has been updated after the creation of the release.

Thanks for letting us know.

**Comment by daiyam** [comment]
The AppImage was missing so I relaunch the workflow to release it. The side effect was that the linux archives/binaries were recreated and so the hash have changed.
I didn't like that when I've seen that. And, now, it's an issue.
I will try to improve the workflow so it won't re-release existing archives/binaries.

**Comment by drupol** [comment]
Thanks @daiyam ! Mystery solved, case closed, issue closed.
