### ISSUE TITLE
VSCodium isn't responding (M1 mac)

### ISSUE THREAD

**Issue by Demoxing** [VSCodium/vscodium#850]
I have installed the VSCodium.arm64.1.60.1 to my m1 mac, and when I open it, it's not responding forever. I have tried uninstalling the app using Appcleaner and Easyfind and reinstalling it after a restart, but there is no fix! It's not working at all. 

I have freshly installed mac so I never installed vscode before.

And the homebrew is also installing the wrong version of Vscodium. 
Here is the reference: https://www.reddit.com/r/MacOS/comments/pr7bsg/homebrew_problem_with_m1_mac/?utm_source=share&utm_medium=web2x&context=3

VSCodium version: v1.60.1
Architecture: Apple silicon
Filename: VSCodium.arm64.1.60.1.dmg
OS: macOS Big Sur v11.6 (M1)

https://user-images.githubusercontent.com/53024273/133950787-69e66d1b-d759-4343-9db9-907ec7bd7674.mp4

**Comment by daiyam** [comment]
Yes, it was a test. I'm removing the binaries. Please refer to #850 for more details
