### ISSUE TITLE
Release 1.60.2 is missing VSCodium-linux-arm64-1.60.2.tar.gz

### ISSUE THREAD

**Issue by kripton** [VSCodium/vscodium#853]
**Describe the bug**
Release 1.60.2 is missing VSCodium-linux-arm64-1.60.2.tar.gz, although its checksum (VSCodium-linux-arm64-1.60.2.tar.gz.sha256) is there.

**Expected behavior**
VSCodium-linux-arm64-1.60.2.tar.gz should be there.

**Comment by daiyam** [comment]
I'm closing it in favor of #828.

I'm refactoring the VSCodium's workflows so they won't re-publish existing binaries. It should out in few days.
