### ISSUE TITLE
Issue During Update: Digest verification failed for file 'vscodium-1.60.2-x86_64.rpm'

### ISSUE THREAD

**Issue by brownc0** [VSCodium/vscodium#855]
**Describe the bug**
Cannot update VSCodium after installing from official repo under the subsection "Fedora / Centos / OpenSUSE (rpm package)" of the website https://vscodium.com.

When I try to update I get the warning: 

```
Warning: Digest verification failed for file 'vscodium-1.60.2-x86_64.rpm'
[/var/tmp/AP_0xw2nEAY/vscodium-1.60.2-x86_64.rpm]

  expected 83725e1896830ab6150f396cb1197b8bf719569b1fd9244343ccd61006c21a52
  but got  9395423c4e6fd889ea875868538295b5496fd5d7c1221bad86d354dbdae6f4f2

Accepting packages with wrong checksums can lead to a corrupted system and in extreme cases even to a system compromise.
```

**Please confirm that this problem is VSCodium-specific**
- [ * ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ * ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install from official repo for openSUSE as available from the website: https://vscodium.com/#install
2. Try and update `sudo zypper up`
3. See error.

**Expected behavior**
Update VSCodium without warnings or errors.

**Desktop (please complete the following information):**
 - OS: openSUSE Leap 15.3
 - Architecture: x64
 - Version: 1.60.1

**Comment by paulcarroty** [comment]
The fix is provided in above PR, just edit your repository config.
