### ISSUE TITLE
Git Extension Unresponsive!

### ISSUE THREAD

**Issue by Nesh108** [VSCodium/vscodium#859]
- Issue Type: `Bug`
- Extension Name: `git`
- Extension Version: `1.0.0`
- OS Version: `Darwin x64 20.3.0`
- VSCodium version: `1.60.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 120,
		"activateCallTime": 432,
		"activateResolvedTime": 1048,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "vscode.github",
				"_lower": "vscode.github"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Comment by daiyam** [comment]
Yes, it's a know issue of VSCode. I'm closing the issue on favor of #718.
