### ISSUE TITLE
Does not install properly on aarch64

### ISSUE THREAD

**Issue by ashirviskas** [VSCodium/vscodium#865]
**Describe the bug**
When I try installing it via `yay -S vscodium-git` I get a `git` error:

![image](https://user-images.githubusercontent.com/11985242/136409452-4d305404-6349-48ad-8323-67cb1c56fbeb.png)

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. On Arch Linux on aarch64 type `yay -S vscodium-git` 
2. Continue with the prompts

**Expected behavior**
A successful install

**Screenshots**
See above

**Desktop (please complete the following information):**
 It's actually mobile:
 Arch Linux on Snapdragon 865, running in proot mode.

**Comment by GitMensch** [comment]
Can anyone please check if this is fixed now because of getting rid of LFS with #871?

**Comment by daiyam** [comment]
@GitMensch Yes, it's working, now, on x64.

@ashirviskas Can you test on arm64?
