### ISSUE TITLE
[Python extension]Runtime Error: No matching bindings found for serviceIdentifier: Symbol(ILanguageServerActivator) Symbol(ILanguageServerActivator) - named: Jedi

### ISSUE THREAD

**Issue by tomyo** [VSCodium/vscodium#875]
## Environment data
Version: 1.61.0
Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Date: 2021-10-08T22:09:41.030Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.10.68-1-MANJARO

-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

Go to definition and autocomplete works.

## Actual behaviour

Go to definition and autocomplete DOES NOT works.

## Steps to reproduce:

Install python + pylance extensions, 

Extension fails with error:

`No matching bindings found for serviceIdentifier: Symbol(ILanguageServerActivator) Symbol(ILanguageServerActivator) - named: Jedi`

Attaching screenshot od error and extensions installed:
![image](https://user-images.githubusercontent.com/708569/137292102-2012d4b6-2983-4a21-9767-e456ccabbc74.png)

**Comment by daiyam** [comment]
https://github.com/VSCodium/vscodium/wiki/Extensions-Compatibility#partial-compatibility

**Comment by tomyo** [comment]
@daiyam, from your link I understand close source parts will not work.
Then a better error message would be better, as currently this is not obvious by the error message.

**Comment by tomyo** [comment]
Oh, I see, thank you.
Will close the issue.

Any suggestion to how to achieve similar features as on the close source Python extension, appreciated.

**Comment by SebastianGrans** [comment]
> @daiyam is there flag or a way to enable it? I'm willing to trade this bit of proprietary code for convenience

You can make PyLance work by modifying the `product.json` file. See my comment [here](https://github.com/VSCodium/vscodium/issues/892#issuecomment-957850440).
