### ISSUE TITLE
Bad system call

### ISSUE THREAD

**Issue by KNobles** [VSCodium/vscodium#88]
I recently installed Parrot Home KDE edition and configured the task.json, launch.json to work on c++ application and after building and compiling (F5) and get this message :

"[1] + Bad system call            /usr/bin/gdb --interpreter=mi --tty=${DbgTerm} 0</tmp/Microsoft-MIEngine-In-wi527ekr.wtn 1>/tmp/Microsoft-MIEngine-Out-a7nqamb7.6wg

Press any key to continue..."

The thing is when I was using the MATE version everything was running fine.
I'm using the C/C++ extension from Microsft.

**Comment by stripedpajamas** [comment]
Hi @KNobles -- have you tried doing these same steps in Visual Studio Code instead of VSCodium? If the problem also happens there, it probably isn't a VSCodium issue and may be related to the extension itself.

**Comment by KNobles** [comment]
Hello, well I uninstalled vscodium after that issue and downloaded vscode and it doesn't happen on the vscode. One thing though, I booted live with Parrot Home KDE edition and the problem wasn't there, everything was fine, it came after a big update so that's that

**Comment by stripedpajamas** [comment]
Hmm. I wonder if it could have anything to do with https://github.com/VSCodium/vscodium/issues/71 where C++ extension is disallowed for VSCodium?

**Comment by stripedpajamas** [comment]
Any update @KNobles?
