### ISSUE TITLE
[BUG] command 'github.copilot.generate' not found

### ISSUE THREAD

**Issue by rolimans** [VSCodium/vscodium#888]
**Describe the bug**
After installing the extension and setting up my Github account in VSCodium I got a message saying the preview wasn't available for my account. Checking the Copilot website it said I was already in the preview.

I uninstalled and re-installed the extension and now when I try to execute any command from the extension I get that the command was not found.

Running on macOS BigSur on a Mac Pro 13 M1

E.g.

command 'github.copilot.generate' not **found**

**Please confirm that this problem is VSCodium-specific**
- [X ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Download the .vsix extension file for the Github Copilot extension
2. Install the extension and login to github inside vscode
3. In any document press ctrl+enter

**Expected behavior**
Githhub copilot extension should do something

**Desktop (please complete the following information):**
 - OS: MacOS BigSur
 - Architecture: arm64
 - Version 1.61.2

**Comment by j2l** [comment]
Unfortunately, for me, Copilot is only working with M$ VS Code, not VSCodium and I had to switch back :sob:

**Comment by an4s911** [comment]
> Unfortunately, for me, Copilot is only working with M$ VS Code, not VSCodium and I had to switch back sob

Same. I am not able to use Copilot on Codium. It works well on VSCode. It is something to do with the URL Handler thing that is available for VSCode but not available for Codium

**Comment by dran1x** [comment]
Any updates on this?

> When using version 1.1.1909 I get the following output
> 
> ```
> [INFO] [auth] [2021-10-26T21:22:42.982Z] Invalid copilot token: missing token
> [ERROR] [ghostText] [2021-10-26T21:22:42.983Z] Error on ghost text request Error: User not authorized
> ```

This is the exact same thing I'm getting.

**Comment by pranavpk404** [comment]
is github copilot available for vscodium?

**Comment by TheLastZombie** [comment]
> is github copilot available for vscodium?

It is if you [configure VSCodium to use the Visual Studio Marketplace](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#howto-vscode-marketplace).

**Comment by dran1x** [comment]
> > is github copilot available for vscodium?
> 
> It is if you [configure VSCodium to use the Visual Studio Marketplace](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#howto-vscode-marketplace).

I've done exactly this and it still fails to connect to the auth server. I think it has to do with some Microsoft module that VSCodium removed.

**Comment by TheLastZombie** [comment]
> > > is github copilot available for vscodium?
> > 
> > 
> > It is if you [configure VSCodium to use the Visual Studio Marketplace](https://github.com/VSCodium/vscodium/blob/master/DOCS.md?rgh-link-date=2022-03-18T15%3A43%3A31Z#howto-vscode-marketplace).
> 
> I've done exactly this and it still fails to connect to the auth server. I think it has to do with some Microsoft module that VSCodium removed.

Ah, I meant available as in "you can install it". Not much more though at the moment. It's probably a similar situation as with the remote extensions, where Microsoft adds some of the relevant code during the build process.

**Comment by itsmeboy0** [comment]
Too bad, this is the only blocker that keeps me from switching to VSCodium.

**Comment by JoshMayBalGitHub** [comment]
yeah, i had to switch back to ms vscode after finding this issue.

**Comment by GWDx** [comment]
> OS: Ubuntu 20.04
>
> install both VSCode and VSCodium

#### 1

I installed Github Copilot in VSCodium and it said `Invalid copilot token: missing token` . Here is my solution.

> GitHub token from `https://github.com/settings/tokens` and nvim Copilot token can't be used for VSCodium to log in. So I use VSCode Copilot token.

Open **VSCode** Copilot `extension.js` and find where the error raise.

> On my computer, it's on `~/.vscode/extensions/github.copilot*/dist/extension.js` 
>
> Please do not format the js file, or the extension may crash.

```javascript
if (!n.ok || !c.token) return s.info(e, `Invalid copilot token: missing token: ${n.status} ${n.statusText}`), (0, i.telemetryError)(e, "auth.invalid_token", i.TelemetryData.createAndMarkAsIssued({
    status: n.status.toString(),
    status_text: n.statusText
}))
```

`n` is declared several lines before

```javascript
console.log(t);
const n = await e.get(o.Fetcher).fetch("https://api.github.com/copilot_internal/v2/token", {
    headers: {
        Authorization: `token ${t}`
    }
});
```

I add `console.log(t)` before it.

Then start VSCode, open developer window, get the token, which may start with `gho_` .
Copy the token to VSCodium.

#### 2

And then I meet another problem in VSCodium `GitHub Copilot requires VS Code 1.57+.`

> It is noticed that in the developer window, a critical warning mentions `product.json`

```
CRITI Extension 'github.copilot' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): inlineCompletionsNew, inlineCompletionsAdditions
product.json (WINS): inlineCompletions, textDocumentNotebook
```

**Solution**

Update `/usr/share/codium/resources/app/product.json`, add the lost attributes for `GitHub.copilot`

```
"GitHub.copilot": ["inlineCompletions", "inlineCompletionsNew", "inlineCompletionsAdditions", "textDocumentNotebook"],
```

**Comment by LewsTherinTelescope** [comment]
In addition to the above instructions, if you use the nightly extension you may need to set `"GitHub.copilot-nightly"` in `product.json` to the same thing as `"GitHub.copilot"`.

**Comment by rollingmoai** [comment]
Bump

@daiyam @GitMensch
