### ISSUE TITLE
Python autocompletion doesn't work with VS Code Python extenstion (Pylance)

### ISSUE THREAD

**Issue by an4s911** [VSCodium/vscodium#892]
**Describe the bug**
When I am using VS Codium and have the VS Code Python and Pylance extensions installed and enabled, I don't get any autocomplete options or suggestions and it shows `No suggestions`. 

![Screenshot from 2021-10-28 18-56-31](https://user-images.githubusercontent.com/55910194/139293780-d8d3eb42-5f0e-4c18-853c-5d061cecbea7.png)

As you can see I have enabled only the Python extension and it shows `No suggestions`. Now when I disable I get some suggestions but they are not Python suggestions, but rather just suggesting text from other parts of the file.

![Screenshot from 2021-10-28 18-56-53](https://user-images.githubusercontent.com/55910194/139294065-fe3752a2-30d6-4725-8cd1-4e74fcd5b602.png)

But not even this works when the extension is turned on.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**

- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Architecture x64
 - Version 1.61.2

**Comment by SebastianGrans** [comment]
The issue is that Microsoft prevents PyLance from being used in non-official builds. 
A workaround is to modify the `product.json` file, and set `nameLong` to `"Visual Studio Code"`. 

Source: https://www.reddit.com/r/linux/comments/k0s8qw/comment/ggnqes7/

**Comment by ghtmtt** [comment]
@SebastianGrans thanks for sharing but still I don't get the extension working. I've changed the `product.json` file with the instruction of reddit but still nothing

**Comment by SebastianGrans** [comment]
@ghtmtt What does it say in the Python output terminal? 

Before I change `nameLong`: 

```
Starting Pylance language server.
Error 2021-11-02 17:21:36: Failed to start language server, Class name = r, completed in 0ms, has a falsy return value, Arg 1: <Uri:/home/grans/Documents/harvesters_gui/Utils/CameraCalibration.py>, Arg 2: {"sysPrefix":"/usr","envType":"Global","envName":"","envPath":"","path":"/bin/python" [... etc] 
```

After I change, it simply prints: 
```
Starting Pylance language server.
``` 
with no error after it.

**Comment by SebastianGrans** [comment]
@ghtmtt No. What I mean is the output from the Python extension. 

You can see its output by opening a terminal inside Codium, and then go to the output tab, and select Python. See the screenshot below. 
<img width="762" alt="Screenshot 2021-11-02 at 20 57 34" src="https://user-images.githubusercontent.com/10030015/139943404-ca54b1e1-f869-45d4-b407-3d8e21c95fea.png">

**Comment by ghtmtt** [comment]
This is what I have
```
 /bin/python ~/.vscode-oss/extensions/ms-python.python-2021.10.1365161279/pythonFiles/interpreterInfo.py
> /usr/bin/python ~/.vscode-oss/extensions/ms-python.python-2021.10.1365161279/pythonFiles/interpreterInfo.py
> /usr/bin/python3 ~/.vscode-oss/extensions/ms-python.python-2021.10.1365161279/pythonFiles/interpreterInfo.py
> ~/.local/share/r-miniconda/bin/python ~/.vscode-oss/extensions/ms-python.python-2021.10.1365161279/pythonFiles/interpreterInfo.py
> ~/.local/share/r-miniconda/envs/r-reticulate/bin/python ~/.vscode-oss/extensions/ms-python.python-2021.10.1365161279/pythonFiles/interpreterInfo.py
Starting Pylance language server.
```

**Comment by SebastianGrans** [comment]
Could you post your user `settings.json` file? 

It could also be an extension that is interfering, so try disabling all extensions that aren't needed and see if that helps. 
It works for me with these extensions active: 
![extensions](https://user-images.githubusercontent.com/10030015/140044130-9c8d7639-8006-41f2-a753-ad586b463a19.png)

**Comment by ghtmtt** [comment]
> Could you post your user settings.json file?

```
{
    "python.autoComplete.extraPaths": [
        "/home/matteo/dev/qgis-master/output/python/qgis/",
        "/home/matteo/dev/qgis-master/output/python/"
    ],
    "workbench.colorTheme": "Quiet Light",
    "python.autoComplete.addBrackets": true,
    "python.pythonPath": "/bin/python3",
    "explorer.confirmDragAndDrop": false,
    "atomKeymap.promptV3Features": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.formatOnPaste": true,
    "editor.rulers": [
        80
    ],
    "python.formatting.provider": "none",
    "[restructuredtext]": {
        "editor.wordWrapColumn": 80,
        "editor.wordWrap": "on",
        "editor.acceptSuggestionOnEnter": "off"
    },
    "workbench.colorCustomizations": {
        "editor.selectionBackground": "#ced12d",
    },
    "diffEditor.ignoreTrimWhitespace": true,
    "jupyter.interactiveWindowMode": "perFile",
    "jupyter.sendSelectionToInteractiveWindow": true,
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter.notebook.ipynb"
    },
    "autoDocstring.docstringFormat": "sphinx",
    "python.analysis.completeFunctionParens": true,
}
```

I've disable most of the extensions but still nothing. No external API and not standard autocomplete

**Comment by gerroon** [comment]
I have the same issue on Windows 10, VsCodium 1.61.2

I originally was not getting even classes and functions in the outline so I removed Pylance,  which helped with the Outline  but I now have no autocompletion. 

This use work fine in early versions this year but I cant tell the last working version.

**Comment by dimitrov-dimitar** [comment]
> The issue is that Microsoft prevents PyLance from being used in non-official builds. A workaround is to modify the `product.json` file, and set `nameLong` to `"Visual Studio Code"`.
> 
> Source: https://www.reddit.com/r/linux/comments/k0s8qw/comment/ggnqes7/

Thank you, it worked for me too. :+1:

**Comment by ghtmtt** [comment]
> Thank you, it worked for me too. +1

I've already tried this solution but it never worked for me. **BUT** it seems that the combination of 2 different changes in the `product.json` file makes the things working again!

```json
{  
  "nameShort": "Visual Studio Code",
  "nameLong": "Visual Studio Code",
  ...
  ...
  "extensionsGallery": {
    "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
    "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
    "itemUrl": "https://marketplace.visualstudio.com/items"
  },
```

**Comment by brccabral** [comment]
where is "product.json" located?

**Comment by brccabral** [comment]
Found it, need to edit file `prepare_vscode.sh` before compile

**Comment by daiyam** [comment]
The python extension is tricky since it's using a closed source server (pylance).
I do believe that the best course of action would for some python devs to fork that extension and replace the closed source part with a new open source project.

**Comment by clayrisser** [comment]
Use the jedi language server instead of pylance.

**Comment by an4s911** [comment]
> The issue is that Microsoft prevents PyLance from being used in non-official builds. A workaround is to modify the `product.json` file, and set `nameLong` to `"Visual Studio Code"`.
> 
> Source: https://www.reddit.com/r/linux/comments/k0s8qw/comment/ggnqes7/

Thanks. Just like some others have mentioned, this worked for me as well. I think I will close the issue now as the issue is solved for me as well as others. 

If the above mentioned solution didn't work then try the below and it should probably fix it.

> > Thank you, it worked for me too. +1
> 
> I've already tried this solution but it never worked for me. **BUT** it seems that the combination of 2 different changes in the `product.json` file makes the things working again!
> 
> ```json
> {  
>   "nameShort": "Visual Studio Code",
>   "nameLong": "Visual Studio Code",
>   ...
>   ...
>   "extensionsGallery": {
>     "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
>     "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
>     "itemUrl": "https://marketplace.visualstudio.com/items"
>   },
> ```

And I am closing this Issue. Thanks to everyone who helped and contributed ✌

**Comment by asdorsey** [comment]
Sorry for issue necromancy, but I found another potential solution today:
Uninstall the Microsoft Python extension and install the [Pyright](https://github.com/Microsoft/pyright) extension instead.  It's still Microsoft, but it provides auto-completion and error checking, and works on VSCodium out of the box without modification.
