### ISSUE TITLE
View all font ligatures.

### ISSUE THREAD

**Issue by HARDY8118** [VSCodium/vscodium#894]
Hi, I wanted to know if there is any way to see all available or supported `font ligatures`.

Also, is there any way to change/add them in some way.

**Comment by paulcarroty** [comment]
`  "editor.fontLigatures": true` in `settings.json`.

**Comment by HARDY8118** [comment]
I appreciate you taking time and replying.

However this is not even close to what I was asking about.
What I was looking is to find what are the possible ligatures available and is there any way to add some or change them.

Every search made with title of `ligature` would land me to the same answer that you gave and it is not what I was looking for.

**Comment by paulcarroty** [comment]
Ah, sorry. But your question is definitely outside VSC scope anyway. Maybe https://github.com/ToxicFrog/Ligaturizer is what you're looking for.

**Comment by HARDY8118** [comment]
Thanks
Will check it out.
