### ISSUE TITLE
[Suggestion] Simplify Release Name

### ISSUE THREAD

**Issue by lamyergeier** [VSCodium/vscodium#896]
**Describe the bug**
I want to download the deb file for a particular version from github release page. But the names of the release has some additional set of numbers. For example: `codium_1.61.2-1634689349_amd64.deb`.

With every release `1634689349` changes along with version number in the file name. This makes it hard for me to automate the downloading of a particular version.

It would be convenient if you could just rename the deb as `codium_1.61.2_amd64.deb` and so on.

**Comment by daiyam** [comment]
:laughing: :cry:
I've got into a fight more or less over this... (#788)
