### ISSUE TITLE
Add brew cask

### ISSUE THREAD

**Issue by MatiasConTilde** [VSCodium/vscodium#9]

**Comment by stripedpajamas** [comment]
I think this would be great! I don't know much about making brew casks. Because this is not "official" it would have to go into the unofficial casks, right?

**Comment by MatiasConTilde** [comment]
I already went ahead and submitted it myself (https://github.com/Homebrew/homebrew-cask/pull/51727), it wasn't that difficult after all :)

According to the [Finding a Home For Your Cask](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) guide, an Unofficial Cask is
> An allegedly unmodified compiled binary, by a third-party, of a binary that has no existing build by the owner of the source code.

As VSCodium is kind of a fork (so not unmodified), and Microsoft (the owner of the source code) doesn't already build it, I think that it counts as official, but we'll have to wait for the maintainers approval to confirm.

**Comment by vitorgalvao** [comment]
HBC maintainer (and writer of that rule) here.

That rule only applies where the name could lead to confusion. For example, if MS didn’t provide a compiled app but you did **and called it Visual Studio Code**, it would fall under that rule. Basically: if by name alone a user could think they’re installing something official when it’s not, the rule comes into play. As the name is different, the issue doesn’t come up.

**Comment by stripedpajamas** [comment]
`brew cask install vscodium` works now 🎉 

Thanks for your help @MatiasConTilde (and @vitorgalvao). I will update the readme.
