### ISSUE TITLE
linux amd64 1.62.0 release missing

### ISSUE THREAD

**Issue by AdelKS** [VSCodium/vscodium#901]
Hello,

The linux `amd64`/`x64` version of the `1.62.0` release seems to be missing, an issue similar to #828 ?

Thanks!

Adel

**Comment by daiyam** [comment]
Yep, we are still have network errors when pushing the files...

**Comment by daiyam** [comment]
The binaries have been successfully released. I've updated the workflow to re-upload if the upload has failed.
I had the run the workflow 6 times because the uploads were failing...

**Comment by AdelKS** [comment]
Crazy, it would be nice to investigate the reason behind the fails and fix that :dagger: 

Thanks!
