### ISSUE TITLE
Codium not detected by github desktop

### ISSUE THREAD

**Issue by yashpalgoyal1304** [VSCodium/vscodium#907]
### Describe the bug
[Github desktop][ghd] (hereafter as ghd) is not recognising VSCodium on my system

[ghd]: https://desktop.github.com/

### Checklist
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.  
~~sorry, i cant confirm that as i dont use VSCode~~ --> refer my first comment
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

### Steps To Reproduce
1. Open ghd
2. Go to "Files > Options" (<kbd>^</kbd><kbd>,</kbd>)
3. Then go to "Integrations > External Editor"
4. See that VSCodium is not there

### Expected behavior
VSCodium should be there

### Screenshots
![image](https://user-images.githubusercontent.com/19423063/140774219-4e0f5d01-4a14-473f-9355-a020e406c6b5.png)

### Environment
- OS: Windows 10 20H2
- Architecture: x64
- Codium: 1.61.2  
from `VSCodium-x64-updates-disabled-1.61.2.msi` installed in "Program Files" (i.e. i guess for all users)
- Ghd: 2.9.4 in "AppData/Local"
- NP++: 7.9.5 in "Program Files"
- Typora: 0.9.98 (beta) in "Program Files"

### Additional context
Duplicate 🔍 [github desktop](https://github.com/VSCodium/vscodium/issues?q=is%3Aissue+is%3Aopen+github+desktop)

P.S.: issue template's modification inspired mainly by: inkscape inbox's template

**Comment by yashpalgoyal1304** [comment]
hi, both VSCode and VSCodium are supported by ghd ([ref](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/configuring-and-customizing-github-desktop/configuring-a-default-editor#supported-editors) < https://github.com/desktop/desktop/issues/10502#issuecomment-687035726). So, the problem is with my install. but i dont know what it is.

**Comment by LuNeder** [comment]
> both VSCode and VSCodium are supported by ghd ([documentation page](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/configuring-and-customizing-github-desktop/configuring-a-default-editor#supported-editors) <-- [desktop/desktop#10502 (comment)](https://github.com/desktop/desktop/issues/10502#issuecomment-687035726)). So, the problem is with my install. but i dont know what it is.

Happening here too, VSCodium is not detected by gh desktop
I'm on OpenSUSE, Codium snap

Did you manage to find a fix?

**Comment by yashpalgoyal1304** [comment]
hey @LuNeder no, i was not able to find any fix.

* I havent used github desktop for many months now.
* And i dont think it will be fixed either, as MicroSoft owns both github, and VS Code. They will obviously want to shoot VS Codium down by not making their services work on it. Like:
    * Github codespaces does not work on VS Codium either
    * Github Desktop is not recognizing VS Codium
    * The normal issue with extensions
    * ... and more to be discovered

**Comment by LuNeder** [comment]
A workaround that works fine for me:
- Create file `/usr/bin/code`
- Add the following contents to the file: `codium $1`
- Make it executable: `sudo chmod 755 /usr/bin/code`
- GitHub Desktop should now detect "Visual Studio Code", select it and whatever you choose to open will open on Codium.

**Comment by yashpalgoyal1304** [comment]
copying over from fix for windows given by @ safetycar at https://github.com/desktop/desktop/issues/13295#issuecomment-1221590465

> I've been trying to fix this issue for some time.
I was finally able to make it work by using the vscodium's EXE installer instead of the MSI.

**Comment by yashpalgoyal1304** [comment]
i had to uninstall the old install anyway for https://github.com/VSCodium/vscodium/issues/1227

so, i tried installing the exe ( `VSCodiumSetup-x64-1.71.2.22258.exe` ) to try the proposed fix, and it didn't work for me.

**Comment by LuNeder** [comment]
@yashpalgoyal1304 
> hey @LuNeder can you translate your proposed fix to windows?

I don’t use Windows, so unfortunately no idea how to do that.

**Comment by yashpalgoyal1304** [comment]
> As a workaround, you could probably use Linux instead

i so want to do that, but honestly, i don't have enough confidence/competency to do that

**Comment by daiyam** [comment]
@GitMensch They are in https://github.com/VSCodium/vscodium/blob/master/prepare_vscode.sh
The name should be only `VSCodium`.

**Comment by GitMensch** [comment]
Cool, I'll send a PR (it will be untested as I don't use that software, but it likely helps some users, so why not).
I'll reference it here and then close it as "external issue".

**Comment by daiyam** [comment]
Did you install it with MSI?

Before I've done the Insider version, only the `"win32x64UserAppId" "{{2E1F05D1-C245-4562-81EE-28188DB6FD17}"` was used. So it seems to be the primary id.

**Comment by daiyam** [comment]
`application's product code GUID` from https://learn.microsoft.com/en-us/windows/win32/msi/uninstall-registry-key

So it seems you used the MSI which generate a new key for each new installer, which might be wrong.
Yeah, the display name seems to be from the MSI.

**Comment by GitMensch** [comment]
> Did you install it with MSI?

yes, with VSCodium-x64-1.71.2.22258.msi

**Comment by GitMensch** [comment]
> So it seems you used the MSI which generate a new key for each new installer, which might be wrong.

So this is actually a VSCodium issue (installer generation)?

**Comment by daiyam** [comment]
Not only. Before `1.71.0`, only `2E1F05D1-C245-4562-81EE-28188DB6FD17` was unique to VSCodium. The others ids were from Visual Studio Code OSS.
I will need to investigate what the id of a MSI should be. Or if somebody has an experience on that, it will be helpful.

**Comment by GitMensch** [comment]
WIP: https://github.com/GitMensch/desktop/commit/d2e24a69c16dc092ede782fb6a675c5315ba1a79 - as soon as I know what IDs to actually use, I'll amend it with those and a nice commit log, then create the PR

**Comment by daiyam** [comment]
I'm confused by the MSI/WiX docs. There are interchanging the ProductId/ProductCode. Then it seems that some Component need to have the same Guid as the UpgradeCode. Confusing...
By the way, Visual Studio Code doesn't have a MSI installer. Can't we use the EXE installer to fix the current issue?

**Comment by mrrezaie** [comment]
Hi, here is a temporary fix:
https://github.com/desktop/desktop/issues/10446#issuecomment-1319892688
