### ISSUE TITLE
DFSG compliment

### ISSUE THREAD

**Issue by ghost** [VSCodium/vscodium#91]
Is it possible that VSCodium compatible with [DFSG](https://people.debian.org/~bap/dfsg-faq.html)?

It would be nice if the concerned maintainer provide VSCodium builds through debian main repositories.
If not, then I am willing to help. I am not really into legalization, but something nice to have on official repo, which will cover up Ubuntu and it's derivatives too.

It's even mentioned in the [debian wiki](https://wiki.debian.org/WebDevelopment#Visual_Studio_Code_.28VSCodium.29)

**Comment by tribut** [comment]
Note that there is a RFP for vscode: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898259

**Comment by laym4n** [comment]
Hmm, looks like green signal for me.

**Comment by stripedpajamas** [comment]
Hello @b17wise 👋 

I really don't know much of anything about getting a package in to the debian main repositories, but I would support that 100% and help out where possible. Based on the FAQ you linked to, I think VSCodium fits the free definition just fine.

Any help to get this going would be appreciated 🙏

**Comment by VentGrey** [comment]
You can upload your package to mentors.debian.net
there a Debian Developer or contributor can "adopt" your package and push it into the next debian release if you manage to maintain it stable. I maintain the `obsidian-icon-theme` I think I can guide you a little :)

**Comment by stripedpajamas** [comment]
@VentGrey good catch. Currently the build will not work without an internet connection because all the dependencies are not bundled in the source code itself. All the things it downloads are MIT-licensed, but the two extensions it downloads from the marketplace are built behind the curtain so that may pose a problem.

I will read through mentors.debian.net and see if it all makes sense.

**Comment by b17wise** [comment]
> You can upload your package to mentors.debian.net
> there a Debian Developer or contributor can "adopt" your package and push it into the next debian release if you manage to maintain it stable. I maintain the `obsidian-icon-theme` I think I can guide you a little :)
> 
> The only "thing" I noticed is this thing from the README:
> 
> > Microsoft's build process does download additional files. This was brought up in
> > [Microsoft/vscode#49159](https://github.com/Microsoft/vscode/issues/49159) and [Microsoft/vscode#45978](https://github.com/Microsoft/vscode/issues/45978).
> 
> Though I'm not really sure if that's a problem or if there is a way to work around those external downloads.

Good catch. Seems can cause issue here a bit.

**Comment by VentGrey** [comment]
You could try to bind the build to the debian `npm` packages or package those binary dependencies yourself and use them for Codium :thinking:

**Comment by stripedpajamas** [comment]
Would support anyone taking this up, but navigating the downloaded files during builds and the bundled licenses to get this into Debian is outside my current scope/capacity for this project.

Will close this issue for now. Any further discussion around this can happen more efficiently on our Gitter.
