### ISSUE TITLE
Unable to sync my data, log in not working neither extensions

### ISSUE THREAD

**Issue by yonasuriv** [VSCodium/vscodium#910]
I'm trying to migrate all my stuff from vscode to vscodium 
(since everytime I upgrade my packages vscode breaks and I am unable to load it again, I have to downgrade it from version 4.11 to like 1.62)

So when I try to log in in vscodium, the option is unavailable

I tried to use an extension, like settings sync, but doesn't work properly, when installing the page to log in to github doesn't appear and shortcuts doesn't works

How can I keep all my data synced in my vscdium in case I want to use the same account on another vscodium?

**Comment by daiyam** [comment]
You can try my extension [Sync Settings](https://open-vsx.org/extension/zokugun/sync-settings).
