### ISSUE TITLE
Support for open-vsx's open link in client

### ISSUE THREAD

**Issue by yashpalgoyal1304** [VSCodium/vscodium#911]
this issue is based on: https://github.com/eclipse/openvsx/issues/363

Now since the above mentioned issue is not rejected, i think it is accepted. and if so, then it will be nice to have a look for when it actually gets implemented so that vscodium can support that asap.

duplicate 🔍 [open in client](https://github.com/VSCodium/vscodium/issues?q=is%3Aissue+open+in+client)

**Comment by yashpalgoyal1304** [comment]
hey @daiyam this issue is not surely about supporting the `vscode://` protocol. rather about supporting the protocol that eclise/openvsx decides. so, why did u close it? 🤔

**Comment by daiyam** [comment]
It's related. I will replied directly in the openvsx issue.

**Comment by yashpalgoyal1304** [comment]
right, i am guessing that u know the url syntax to open the extensions then. great. looking fwd to ur input there :heart-eyes:
