### ISSUE TITLE
1.32.3 releases located in 1.32.2 folder

### ISSUE THREAD

**Issue by ChrisBaker97** [VSCodium/vscodium#92]
The most-recent `1.32.3` releases are all located at 
`https://github.com/VSCodium/vscodium/releases/download/1.32.2/...`, which is breaking some package manager installs, i.e. [Homebrew](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/vscodium.rb), which is coded to look for releases in `https://github.com/VSCodium/vscodium/releases/download/#{version}/VSCodium-darwin-#{version}.zip`.

**Comment by stripedpajamas** [comment]
Hmm. It looks like MS didn't add a tag for 1.32.3 which is why they are associated with 1.32.2. I think I can just manually make a 1.32.3 tag and move the binaries into it.

**Comment by ChrisBaker97** [comment]
Why is there no 🤞 emoji?
