### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by NoNameMan1231** [VSCodium/vscodium#921]
**Describe the bug**
Tarball validation failed (I'm using arm64 device)

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**Expected behavior**
The SHA256sums validation should be passed

**Screenshots**
![Screenshot_2021_1114_150703](https://user-images.githubusercontent.com/87801676/141671303-cdbe9e0f-dc35-44ce-a68c-89703ee449a7.jpg)

**Desktop (please complete the following information):**
 - OS: [ARCH LINUX ARM]
 - Architecture [arm64]
 - Version [e.g. 1.62.2]

**Comment by paulcarroty** [comment]
Arch packages aren't supported yet, please contact [the maintainers](https://github.com/VSCodium/vscodium#install-on-arch-linux).
