### ISSUE TITLE
Some _ (underscores) are not present / invisible in VScodium terminal

### ISSUE THREAD

**Issue by doom-fr** [VSCodium/vscodium#922]
**Describe the bug**
Some _ (underscores) are not present / invisible in VScodium terminal

**Please confirm that this problem is VSCodium-specific**
- Sorry I don't have Microsoft's Visual Studio Code.

**Please confirm that the issue/resolution isn't already documented**
- I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.
- might be related to https://github.com/microsoft/vscode/issues/85154

**To Reproduce**
1. open a terminal in VScodium
2. type ls
3. notice some _ are not present on filenames
4. compare to same command in native window (_ are there)

**Expected behavior**
file names with underscores : 
![image](https://user-images.githubusercontent.com/7809481/141775044-de881f31-da03-4beb-b7fe-8d18378fb4e9.png)
(from Ubuntu native terminal)

**Screenshots**
![image](https://user-images.githubusercontent.com/7809481/141775177-66f0989b-2f56-4dfb-adbc-02fc07314f3f.png)
Some underscores are missing !!!

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.10]
 - Architecture [x64]
 - Version
 ```
Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-06T12:14:22.604Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.8.0-63-generic
```

```
CPUs	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 3305)
GPU Status	2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: disabled_off opengl: enabled_on rasterization: disabled_software skia_renderer: enabled_on video_decode: disabled_software vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg)	0, 0, 0
Memory (System)	15.37GB (1.03GB free)
Process Argv	--unity-launch
Screen Reader	no
VM	0%
```

**Additional context**

**Comment by daiyam** [comment]
It seems that there is an issue with the font used. Since when the text is bold, the underscore are shown...
