### ISSUE TITLE
"Reload Required" button cannot be focussed via keyboard if only one extension is outdated and needs reload

### ISSUE THREAD

**Issue by heapifyman** [VSCodium/vscodium#923]
**Describe the bug**
It is not possible to focus and press the `Reload Required` button using only the keyboard if there is *exactly one* extension to update.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Using only keyboard (tab, space, enter, arrow keys, etc.), no mouse:

1. Go to extensions view (ctrl+shift+x)
2. Select filter `Outdated`
3. If there is only one extension to be updated update it using `Update` button in the extension list.
4. Once installation has finished `Update` button changes to `Reload Required`
5. Try to focus the `Reload Required` button using only the keyboard

**Expected behavior**
It should be possible to focus and press the `Reload Required` button using the keyboard.

**Desktop (please complete the following information):**
 - OS: Linux x64 5.14.10-1-MANJARO, Gnome 40.4.0, X11
 - Architecture: x64
 - Version: 1.62.2

**Additional context**
Only happens  if there is *exactly one* extension to update. If there are multiple updates it is possible to focus each extension's `Reload Required` button using the keyboard.

**Comment by NovaliX-Dev** [comment]
Is it vscodium specific ? Because you didn't checked the checkbox for specific errors

**Comment by heapifyman** [comment]
I don't have VSCode installed. I can try to reproduce the issue there but I guess then I would have to wait for an extension update.
Any recommendations for an extension that will release an update tomorrow or in the next days?

**Comment by NovaliX-Dev** [comment]
I could try to reproduce the error, in the same environment, but i don't really know how to use VSCode with keyboard only

**Comment by NovaliX-Dev** [comment]
And i can t predict the release date of extension, i think it s not possible

**Comment by NovaliX-Dev** [comment]
There is a complicated option which is to create an extension ourselves, publish it to the marketplace and makes update to it

But i m not really sure you want to do all of this just for a bug

**Comment by daiyam** [comment]
This is an issue of VSCode. It can't be fixed in VSCodium.
But you reload the window with the shortcut named `Developer: Reload Window` and it do the same as you want. Just that, you don't need to focus on that button.
