### ISSUE TITLE
"Extensions: Check for Extension Updates" sometimes shows wrong result

### ISSUE THREAD

**Issue by heapifyman** [VSCodium/vscodium#924]
**Describe the bug**
"Extensions: Check for Extension Updates" result says: "All extensions are up to date." But when opening extensions view (`Ctrl+Shift+x`) the list contains extensions that are outdated and can be updated.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. While in explorer view press `Ctrl+Shift+p`
2. Select `Extensions: Check for Extension Updates` and press `Enter`
3. See result popup: "All extensions are up to date."
4. Press `Ctrl+Shift+x` to open extensions view.
5. See that there are indeed extensions that are outdated and can be updated.

**Expected behavior**
`Extensions: Check for Extension Updates` should report that there are extensions to be updated.

**Desktop (please complete the following information):**
* OS: Linux x64 5.14.10-1-MANJARO, Gnome 40.4.0, X11
* Architecture: x64
* Version: 1.62.2

**Additional context**
```
"extensions.autoUpdate": false,
"extensions.autoCheckUpdates": false,
```

**Comment by daiyam** [comment]
It's because VSCodium is using open-vsx.org while Visual Studio Code is using their own proprietary marketplace.
Since no every extension's author are maintaining their extension on both stores, their versions can differ. Nothing from our end can be done.
You can always ask the extension's author to maintain their extension on open-vsx.org.

**Comment by heapifyman** [comment]
@daiyam please reopen this issue. I now (VSCodium 1.63.2) see the following behaviour:

1. Press `Ctrl+Shift+p`, select `Extensions: Check for Extension Updates`, and press `Enter`
2. Result popup: "All extensions are up to date." but also an indicator on the icon for the extensions view that there is a number of `x` extensions with available updates.
3. Press `Ctrl+Shift+p`, select `Extensions: Check for Extension Updates`, and press `Enter` a *second* time

Result: Extensions View opens up, filter set to `@outdated`, listing a number of `x` extensions with available updates.

I still think that this is a bug because VSCodium shows inconsistent results when checking for extension updates.

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-17T00:20:01.675Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.15.7-1-MANJARO
