### ISSUE TITLE
Missing a space behind the | on the website in the opensuse section!

### ISSUE THREAD

**Issue by ChocoTaco1** [VSCodium/vscodium#925]
Should read
`printf "[gitlab.com_paulcarroty_vscodium_repo]\nname=gitlab.com_paulcarroty_vscodium_repo\nbaseurl=https://download.vscodium.com/rpms/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg" | sudo tee -a /etc/zypp/repos.d/vscodium.repo`
Space before the sudo tee! Gives and error if you don't and you have to manually uninstall the repo!

**Comment by paulcarroty** [comment]
@PalinuroSec ^

**Comment by stripedpajamas** [comment]
Spaces have been added after the pipe in https://github.com/VSCodium/vscodium.github.io/commit/68367c5d24e938cae7f56fc2bb90eac210170b03
