### ISSUE TITLE
wiki.eclipse.org

### ISSUE THREAD

**Issue by G2G2G2G** [VSCodium/vscodium#926]
Why does vscodium `get` this every time it's opened? I can't find any info on it. All extensions are disabled. 
(other than that I have literally no idea where to go/check for it, I grepped some things but that's it... I only use vs for the Go extension (which is disabled to test this wiki.eclipse.org thing))

thanks

Also reading
https://stackoverflow.com/questions/57874263/how-to-disable-internet-access-for-a-particular-vscode-extension-you-dont-trust
is there a way to implement this?

**Comment by daiyam** [comment]
wiki: I don't understand your issue/question...
stackoverflow: I don't think it can be done.

**Comment by G2G2G2G** [comment]
"Why does vscodium `get` this every time it's opened?"
What don't you get about my question? GET is a GET request, it's pulling data from... what does eclipse have to do with vscodium why does it pull it where does it pull it from (in the code if possible?) what info does it need from there?

**Comment by daiyam** [comment]
open-vsx.org is managed by the Eclipse Foundation. So maybe the reverse ip isn't correct...

**Comment by G2G2G2G** [comment]
yea looks like that's it, thanks.
```
open-vsx.org.		30	IN	A	198.41.30.195
195.30.41.198.in-addr.arpa. 30	IN	PTR	wiki.eclipse.org.
```

 I'll continue to run it like `firejail --net=none vscodium` then
