### ISSUE TITLE
 vsc-print cannot be installed while proprietary Microsoft version works

### ISSUE THREAD

**Issue by matkoniecz** [VSCodium/vscodium#928]
**Describe the bug**
PeterWone/vsc-print extensions fails to install.

I am not the first affected person, see https://github.com/PeterWone/vsc-print/issues/116

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to extension tab
2. Search "print"
3. Install "VS Code Printing Free" by pdconsec
4. Type something
5. Mark this text 
6. press right button mouse
7. select "Print"

I get following displayed as text in browser

`/home/mateusz/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8` is existing

/home/mateusz/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/node_modules` is NOT existing

```
Error: ENOENT: no such file or directory, open '/home/mateusz/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/node_modules/highlight.js/styles/default.css'
	at Object.openSync (fs.js:476:3)
	at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
	at Object.readFileSync (fs.js:377:35)
	at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)
	at T (/home/mateusz/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:908842)
	at /home/mateusz/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:906535
	at Generator.next (<anonymous>)
	at /home/mateusz/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:900819
	at new Promise (<anonymous>)
	at a (/home/mateusz/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:900564)
	at /home/mateusz/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:905132
	at /home/mateusz/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:908481
	at /home/mateusz/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:904309
	at Generator.next (<anonymous>)
	at /home/mateusz/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:900819
	at new Promise (<anonymous>)
	at a (/home/mateusz/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:900564)
	at Server.<anonymous> (/home/mateusz/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:904074)
	at Server.emit (events.js:315:20)
	at parserOnIncoming (_http_server.js:874:12)
	at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
```

**Expected behavior**
Some kind of printing happens

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Architecture - standard 64 bit
 - Version 1.62.2

**Additional context**

Reported at https://github.com/PeterWone/vsc-print/issues/116 - author of extension supports only proprietary Microsoft version

**Comment by matkoniecz** [comment]
In my case entire `node_modules` was missing.

It is also missing from VSIX file at https://open-vsx.org/extension/pdconsec/vscode-print

**Comment by matkoniecz** [comment]
he is explicitly not interested in that

>  it's designed and tested and it works just fine with the installer in Microsoft Visual Studio Code. Not the various forks. Non-standard versions of VS Code make up such a tiny portion of the user base that I cannot give this kind of installer problem priority over standard installations.

Maybe it should be reported to whoever published this extension in broken state?

> Published by open-vsx

should I open issue on https://github.com/eclipse/openvsx ?

**Comment by daiyam** [comment]
The main issue is that the file [.vscodeignore](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#advanced-usage) isn't configured.

You could make a PR with the previous file and a [github action](https://github.com/zokugun/vscode-explicit-folding/blob/master/.github/workflows/publish.yml) to automate the publishing process.

If it can't be merged, make a fork of the extension.

**Comment by matkoniecz** [comment]
> The main issue is that the file .vscodeignore isn't configured.

Where? https://github.com/PeterWone/vsc-print/blob/master/.vscodeignore has one

**Comment by daiyam** [comment]
> Where? https://github.com/PeterWone/vsc-print/blob/master/.vscodeignore has one

Oops! I will have change my glasses....

So, yes, you should open on issue on openvsx.

**Comment by matkoniecz** [comment]
In this case openvsx mangled package and VSCodium is not able to magically recreate content.
