### ISSUE TITLE
Transfer list of enabled extensions for every workspace from VSCode

### ISSUE THREAD

**Issue by anishmittal2020** [VSCodium/vscodium#93]
I am using Ubuntu 18.04. 

How can I transfer the list of enabled extensions for every workspace? There should be somewhere 
 Vscode would stores this information.

For the time being I want to keep my Microsoft VS Code binary as well as VSCodium. Is it ok if I symlink the entire User folder `Linux: $HOME/.config/VSCodium/User`  as: 

```
ln -s /home/nikhil/.config/Code/User /home/nikhil/.config/VSCodium/User
```

Also, will it be an issue if I open both VS code and VScodium simultaneously?

**Comment by stripedpajamas** [comment]
Hello @anishmittal2020. As far as I know it should not be a problem to symlink the the folders. And as far as I know it's not a problem to run VSCode and VSCodium simultaneously (I've done this myself many times). _But_, if you are symlinking _and_ running them simultaneously, there may be issues with them fighting over who is writing/reading the configuration files. I don't know, just a warning in case you see unexpected behavior.

In regard to enabled extensions per workspace, I don't have any info on where/if VSCode stores that info. Wherever it is, VSCodium would follow suit. 

In the future, it probably makes more sense to ask questions on [our gitter](https://gitter.im/VSCodium/Lobby) and then if you actually run into an problem, open an issue here. 

Thanks for giving VSCodium a shot 😄
