### ISSUE TITLE
libgio-2.0.so.0: undefined symbol;libselinux.so.1: no version information available;cannot launch appimage

### ISSUE THREAD

**Issue by newyorkthink** [VSCodium/vscodium#930]
![image](https://user-images.githubusercontent.com/87791643/143792667-90da8b92-01d4-495f-ab44-0443d8741a38.png)

system: kali linux
desktop: gnome 41

libgio2.0-cil-dev installed.

![image](https://user-images.githubusercontent.com/87791643/143792757-6945f5ce-47d0-4e83-bf84-05f0aabcc060.png)

cannot launch VSCodium-1.62.3-1637281224.glibc2.17-x86_64.AppImage

**Comment by paulcarroty** [comment]
➡️ #919
