### ISSUE TITLE
Support `vscode://` links (or provide an alternate)

### ISSUE THREAD

**Issue by yashpalgoyal1304** [VSCodium/vscodium#933]
### Checklist
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.  
i cant confirm that as i dont use VSCode, BUT it shouldnt happen with VSC as far as i can guess
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

### Summary
Lack of functionality due to `vscode://` links being not supported

### To Reproduce
**Steps:**
1. Go to any repo on gitlab, example: 
https://gitlab.com/Moini/git_und_gitlab
2. Click Clone
3. Under "Open in your IDE" section, click any of those links
4. If VSCodium is not installed, nothing happens

**Expected:**
* VSCodium supports and open those links correctly

### Desktop
* OS: Win 10 20H2
* Architecture: x64
* Codium: 1.61.2

---
### Details
+ Many sites provide links to make vscode do things like
    * opening extension page [^1]
    * open in IDE for cloning [^2]
+ Those links are not opened with vscodium
+ This results in a broken experience

#### Digging In
0. The link for opening extension page is hidden, so, couldnt find it
1. The link used for "open in IDE" for cloning is in this format:
`vscode://vscode.git/clone?url=<encoded-link>`
2. `<encoded-link>` ended in `.git`
3. `<encoded-link>` were in URL encoding format, so, 
    + `%3A` for `:`
    + `%2F` for `/`
4. I tried replacing `vscode://vscode.git/...` with following in the Browser's Developer/Web-Inspector Tools, but it didnt work
    +  `vscodium://vscodium.git/...`
    + `vscodium://vscode.git/...`
5. So, in my opinion, supporting `vscode://` links right away is a better option rather than doing `vscodium://`. 
This would be similar as Unigram app supports Telegram app's links in desktop, and both apps are shown in "Open with" dialog.[^3]

#### Links Example
So, for vscodium's repo,
* the raw link (HTTPS) is 
`https://github.com/VSCodium/vscodium.git`
* encoded link will become: 
`https%3A%2F%2Fgithub.com%2FVSCodium%2Fvscodium.git`
* using it with `vscode://` protocol and in the given format (point 1), it will become: 
`vscode://vscode.git/clone?url=https%3A%2F%2Fgithub.com%2FVSCodium%2Fvscodium.git`

[eclipse/openvsx#363]: https://github.com/eclipse/openvsx/issues/363
[#911]: https://github.com/VSCodium/vscodium/issues/911

[^1]: in MS-VS-Market. See [#911] and follow the links there 
[^2]: in Gtilab. Screenshot: <br/><img src="https://user-images.githubusercontent.com/19423063/143988083-03918b70-41eb-4e2c-9df0-2ab254185f2b.png" height=220px>
[^3]: See this [video🡭](https://user-images.githubusercontent.com/19423063/140739460-16c19e72-3144-4e2f-91c8-7775211dd36f.mp4) -- from [eclipse/openvsx#363]

**Comment by daiyam** [comment]
I don't think that the `vscode` protocol will ever be supported.
`vscodium://vscode.git/clone?url=https%3A%2F%2Fgithub.com%2FVSCodium%2Fvscodium.git` is working fine...

You might need an extension or Tampermonkey' script to replace `vscode://` with `vscodium://`

**Comment by yashpalgoyal1304** [comment]
i had already tried replacing only `vscode://` with `vscodium://` but that didnt work either. so....

**Comment by daiyam** [comment]
It's because you replaced all `vscode` while the second vscode (`vscode.git`) is the id (which doesn't change between vscode and vscodium) of the extension which is doing the work.

I've just tried it on Windows 10 and it's working.

**Comment by daiyam** [comment]
Just copy/paste the url `vscodium://vscode.git/clone?url=https%3A%2F%2Fgithub.com%2FVSCodium%2Fvscodium.git` into the url bar of your browser.

While changing the url with the dev tools should work, the change might not be picked up if the page is built as an app with react or similar.

**Comment by yashpalgoyal1304** [comment]
> Just copy/paste the url `vscodium://vscode.git/clone?url=https%3A%2F%2Fgithub.com%2FVSCodium%2Fvscodium.git` into the url bar of your browser.

ahhw right, it worked 👍 . niiiiiice. 

but also, so, my faith on dev tools as being ultimate power was blind faith   :childish-cry-emoji: x3

**Comment by daiyam** [comment]
If the url isn't supported directly by the browser, it will confirm it with the user and send the request to the system.

**Comment by daiyam** [comment]
The main reason to not support `vscode` is to avoid any conflict when both VSCode and VSCodium are installed (my case due to the remote extensions).

**Comment by yashpalgoyal1304** [comment]
> to avoid any conflict when both VSCode and VSCodium are installed

umh, i thought about the conflict, but on second thought, that's not an issue since it should pass through open with dialog? or am i wrong regarding this "open with" behaviour?

> my case due to the remote extensions

i didnt understand that

**Comment by yashpalgoyal1304** [comment]
> or am i wrong regarding this "open pick an app" behaviour

oh yeah, i forget that it becomes complicated once "Always use this app" is clicked. it's very hard to erase association in windows 10 to make it to ask/launch "open pick an app" again

i guess this concludes it then from my side. feel free to reopen if someone else has any idea for how can the pros of this suggestion outweigh cons.

**Comment by yashpalgoyal1304** [comment]
> Tampermonkey' script to replace vscode:// with vscodium://

can u share the script?

**Comment by yashpalgoyal1304** [comment]
I am separating out this section from description to separate comment here, just to keep things small sized. this is same old content, nothing new.

----

### Details
+ Many sites provide links to make vscode do things like
    * opening extension page [^1]
    * open in IDE for cloning [^2]
+ Those links are not opened with vscodium
+ This results in a broken experience

### Technical Details
#### Digging In
0. The link for opening extension page is hidden, so, couldnt find it
1. The link used for "open in IDE" for cloning is in this format:
`vscode://vscode.git/clone?url=<encoded-link>`
2. `<encoded-link>` ended in `.git`
3. `<encoded-link>` were in [URL encoding] format, so, 
    + `%3A` for `:`
    + `%2F` for `/`
4. I tried replacing `vscode://vscode.git/...` with following in the Browser's Developer/Web-Inspector Tools, but it didnt work
    +  `vscodium://vscodium.git/...`
    + `vscodium://vscode.git/...`
5. So, in my opinion, supporting `vscode://` links right away is a better option rather than doing `vscodium://`. 
This would be similar as Unigram app supports Telegram app's links in desktop, and both apps are shown in "Open with" dialog.[^3]

#### Links Example
So, for vscodium's repo,
* the raw link (HTTPS) is 
`https://github.com/VSCodium/vscodium.git`
* encoded link will become: 
`https%3A%2F%2Fgithub.com%2FVSCodium%2Fvscodium.git`
* using it with `vscode://` protocol and in the given format (point 1), it will become: 
`vscode://vscode.git/clone?url=https%3A%2F%2Fgithub.com%2FVSCodium%2Fvscodium.git`


[URL encoding]: https://en.wikipedia.org/wiki/Percent-encoding

[^1]: in MS-VS-Market. See [#911] and follow the links there 
[^2]: in Gtilab. Screenshot: <br/><img src="https://user-images.githubusercontent.com/19423063/143988083-03918b70-41eb-4e2c-9df0-2ab254185f2b.png" height=220px>
[^3]: See this [video🡭](https://user-images.githubusercontent.com/19423063/140739460-16c19e72-3144-4e2f-91c8-7775211dd36f.mp4) -- from [eclipse/openvsx#363]

[eclipse/openvsx#363]: https://github.com/eclipse/openvsx/issues/363
[#911]: https://github.com/VSCodium/vscodium/issues/911

**Comment by tennox** [comment]
One way to do it on linux is to add `x-scheme-handler/vscode` to the `codium-url-handler.desktop` file:
```desktop
[Desktop Entry]
Name=VSCodium - URL Handler
Exec=/usr/bin/codium --open-url %U
...
MimeType=x-scheme-handler/vscodium;x-scheme-handler/vscode;
```
