### ISSUE TITLE
python extension doesn't work with pylance.

### ISSUE THREAD

**Issue by HarshilPatel007** [VSCodium/vscodium#934]
**Describe the bug**
python extension doesn't work (no autocomplete, no go to definition, etc.) when pylance is enabled.
after disabling the pylance, it worked. (but, auto-import doesn't worked).
then I've modified `product.json` as per this comment (https://github.com/VSCodium/vscodium/issues/892#issuecomment-957850440) and it worked. but, the same problem happened, no auto-import. :face_with_spiral_eyes: 

**Please confirm that this problem is VSCodium-specific**
- This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
- Sorry, I don't have VS Code installed. (and don't want to install it.)

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**Desktop (please complete the following information):**
 - OS: Arch
 - Architecture: x64
 - Version:
 ```
Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-19T00:20:00.672Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.10.81-1-lts
```

**Additional context**
- probably same problem/issues as [this](https://github.com/VSCodium/vscodium/issues/892#issue-1038694861)

**Comment by paulcarroty** [comment]
Any major difference between #892?

**Comment by daiyam** [comment]
It's an issue with the python extension. I'm closing it since it's similar to #892.

**Comment by HarshilPatel007** [comment]
> Any major difference between #892?

strange behavior, yesterday it was not working since 3-4 days. now, re-setting options to default, it's working fine.
but, @daiyam is right, someone needs to port it and make it FOSS.
