### ISSUE TITLE
AppImage: Not starting (Gio undefined symbol)

### ISSUE THREAD

**Issue by realmazharhussain** [VSCodium/vscodium#936]
**Description**
When trying to run the AppImage, it does not start VSCode. Instead, it shows following error message

```
codium: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full
```

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Download VSCodium version 1.62.3 commit:c71f225 AppImage (currently latest stable release)
2. Mark it as executable
3. (Try to) run the AppImage (in terminal)
4. See the error (Application does not launch at all)

**Expected behavior**
AppImage should run

**Desktop:**
 - OS: Manjaro Linux Gnome Edition (21.2.0)
 - Architecture: x64

**Possible Fix**
Include the required version of GLib inside the AppImage

**Comment by paulcarroty** [comment]
➡️ #919
