### ISSUE TITLE
Update 1.6.3 file path error

### ISSUE THREAD

**Issue by mul44** [VSCodium/vscodium#939]
Update 1.6.3, if the file is stored at c:/Users/Teacher/Documents/house.py, then this last letter does not "see": c:/Users/eacher/Documents/house.py
![Screenshot_26](https://user-images.githubusercontent.com/40139841/145577858-a07dc791-1dc2-4be2-8261-bf4626f4c36e.png)

**Comment by paulcarroty** [comment]
Upstream issue.
