### ISSUE TITLE
Could not open debian-binary

### ISSUE THREAD

**Issue by crazyBaboon** [VSCodium/vscodium#95]
I have downloaded **vscodium_1.32.3-1552960621_amd64**.

On Linux Mint 19.1 I get the following message when doing "sudo gdebi-gtk debian-binary":

> The package might be corrupted or you are not allowed to open the file. Check the permissions of the file.

The permissions I have set for **debian-binary** are the following:
`-rwxr-xr-x`

What is going on here?

**Comment by stripedpajamas** [comment]
Hi @crazyBaboon 👋 

That's rough. I'm not sure what's going on. I don't have a Debian machine to test it myself at the moment, so I'm not sure if that package is corrupt or not. Can you try a v1.31.x download and see if you experience the same issue?

**Comment by JL2210** [comment]
You have to run `sudo gdebi-gtk vscodium_1.32.3-1552960621_amd64.deb`. The `debian-binary` file just lets `dpkg` know that it's a Debian binary.

**Comment by stripedpajamas** [comment]
@crazyBaboon do you still need help with this or does @JL2210's suggestion resolve your issue?
