### ISSUE TITLE
VSCode not show in the list of applications (Snap)

### ISSUE THREAD

**Issue by julian-alarcon** [VSCodium/vscodium#955]
**Describe the bug**

VSCode was recently updated, thanks for that! But after the update, the App is not visible in the Apps section, or even searching for all the apps.
The apps works with no issues when using the terminal or ALT+F2  and execute `codium`

**Please confirm that this problem is VSCodium-specific**
- [X ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install latest version available in https://snapcraft.io/codium or use `sudo snap install codium --classic`
2. Look for all the apps pressing the Super/Win key double times or using the Show Applications button in the dock
3. No VSCode icon app is shown
4. Try searching `vscodium` or `codium`, no app result
5. You can't pin the app to the dock when it's open

**Expected behavior**
The app should be visible.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Architecture: x64
 - Version: `codium                     1.63.2                       235    latest/stable    vscodium        classic`

**Comment by daiyam** [comment]
Yep, the issue is there. I'm rolling back that. I will do further tests with the beta channel (after I've slept...)

**Comment by daiyam** [comment]
@julian-alarcon Hi, can you test the `beta` channel? (`sudo snap install --beta codium --classic`)
I've fixed the missing icons due to the mix up I made between the `snapcraft.yaml` of vscode and snapcrafters...

**Comment by julian-alarcon** [comment]
Thank you! I saw your rollback to v 1.63.0 rev 230.
Not it's working fine!

I will keep the bug open as it's an issue with the point versions.

**Comment by julian-alarcon** [comment]
I just tested the beta version and now it's working fine! Thank you!
`codium                     1.63.2                       240    latest/beta      vscodium        classic`

**Comment by julian-alarcon** [comment]
Fixed by: https://github.com/VSCodium/vscodium/pull/956 and https://github.com/VSCodium/vscodium/pull/957

**Comment by daiyam** [comment]
Thx for confirming
