### ISSUE TITLE
Integrated terminal does not launch

### ISSUE THREAD

**Issue by aeroaks** [VSCodium/vscodium#96]
On launching the integrated terminal, i get the following:
`The terminal process command 'C:\WINDOWS\System32\cmd.exe' failed to launch (exit code: 2)`

I am running the following:
![image](https://user-images.githubusercontent.com/3954144/55162671-9634c480-5168-11e9-9296-84c7268c59d2.png)

**Comment by stripedpajamas** [comment]
Hi @aeroaks 👋

Does it launch fine if you use Microsoft's release instead of VSCodium?

**Comment by aeroaks** [comment]
Hi @stripedpajamas , 

Did not try, there is a reason I chose VSCodium over VSCode ;)

I will try and come back

**Comment by aeroaks** [comment]
I installed and tried VSCode. It works on a fresh install.

**Comment by stripedpajamas** [comment]
Pretty weird. I looked up exit code 2 on Windows and it says that means it can't find the file. Does `C:\WINDOWS\System32\cmd.exe` exist?

**Comment by aeroaks** [comment]
Yes, I can go through `Cmder` and through file system and run `cmd.exe`

**Comment by aeroaks** [comment]
Terminal running in VSCode is installed as follows:
Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299

**Comment by stripedpajamas** [comment]
I'm confused-- are you saying it works when you use the user setup instead of the system setup?

**Comment by stripedpajamas** [comment]
Oh I see-- you're saying it works in VSCode 1.32.3 user setup. Did you try VSCodium user setup as well?

**Comment by aeroaks** [comment]
Terminal seems to open properly for VSCodium user setup.

**Comment by stripedpajamas** [comment]
Ok that's good news. Sorry to ask you to jump through hoops here, but a final step I would check is if the terminal doesn't work properly in VSCode system setup. If it doesn't work there, we aren't dealing with a VSCodium issue anymore. If it does work, something might be awry with our system setup.

**Comment by aeroaks** [comment]
I uninstalled system setup of VSCodium and tried user setup and that works fine now. I can open the Terminal. :)
