### ISSUE TITLE
Confusion over the way readme and docs are worded

### ISSUE THREAD

**Issue by Calandiel** [VSCodium/vscodium#971]
Hello, I'd like so ask, is all of the telemetry disabled by default?
In the ["Why does this exist"](https://github.com/VSCodium/vscodium#why) it's said (in bold letters) that "Telemetry is disabled.", however, in the docs, there is a dedicated section to *disabling* telemetry, with links to pages owned by Microsoft. Since Microsoft's telemetry tends to be rather invasive and sends the data on the first launch, it creates a bit of a confusion over whether or not using vs codium requires further fiddling before launch to prevent uploading any data over to Microsoft.
If that further fiddling is required, perhaps this could be clarified in the "why does this exist" section and the boldface on telemetry dropped.

**Comment by paulcarroty** [comment]
Yeah, check [undo_telemetry.sh](https://github.com/VSCodium/vscodium/blob/master/undo_telemetry.sh).
