### ISSUE TITLE
Build broken due to outdated patches

### ISSUE THREAD

**Issue by jessemartin** [VSCodium/vscodium#974]
**Describe the bug**
The build is currently failing due to outdated patches.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
```./build/build_macos.sh```

**Expected behavior**
Build succeeds.

**Screenshots**
![Screen Shot 2022-01-14 at 22 21 53](https://user-images.githubusercontent.com/1626240/149611668-6f6b55e9-6a6a-4d33-8b2e-2413a5c27673.png)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Architecture [e.g. x64, ia32, arm64]: arm64
 - Version [e.g. 1.33.0]: Latest

**Additional context**
PR on the way.

**Comment by daiyam** [comment]
@jessemartin The patches are fine. Your issue is because your are using an outdated [commit of vscode](https://github.com/microsoft/vscode/commit/7ba09425a) (from `HEAD is now at 7ba09425a add logging`).

**Comment by jessemartin** [comment]
@daiyam thanks for clarifying. Closing this out!
