### ISSUE TITLE
Git Default Extension is slow

### ISSUE THREAD

**Issue by bugsalexander** [VSCodium/vscodium#977]
- Issue Type: `Bug`
- Extension Name: `git`
- Extension Version: `1.0.0`
- OS Version: `Darwin x64 21.2.0`
- VSCodium version: `1.63.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 38,
		"activateCallTime": 478,
		"activateResolvedTime": 1215,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "vscode.git",
				"_lower": "vscode.git"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

### Problem I'm running into

For some reason, my Git extension (installed by default) is extremely slow. I recorded a few second profiler run and saw that the process was spending a long time doing Process.spawn for some reason, not sure if that was related – during the run i just hit return and delete a bunch of times (maybe 10). I'll attach the profiler run as well.

[CPU-20220122T080159.667Z.zip](https://github.com/VSCodium/vscodium/files/7917910/CPU-20220122T080159.667Z.zip)

**Comment by bugsalexander** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 38,
		"activateCallTime": 478,
		"activateResolvedTime": 1215,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "vscode.git",
				"_lower": "vscode.git"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Comment by bugsalexander** [comment]
![Screen Shot 2022-01-22 at 3 20 56 AM](https://user-images.githubusercontent.com/22948432/150630760-e0d33abd-5abe-4e93-b61d-208ecb75ea24.png)

**Comment by daiyam** [comment]
Yes, it's a know issue on macOS (#718). We welcome any help to find the root cause of the issue.

**Comment by bugsalexander** [comment]
Closing, since this is a duplicate
