### ISSUE TITLE
Official vscodium website

### ISSUE THREAD

**Issue by PalinuroSec** [VSCodium/vscodium#98]
Hello, i would like to contribute to the vscodium project by building and hosting a dedicated website for it, to make the whole user experience for vscodium newcomers more appealing.

We (www.parrotsec.org) already use vscodium as the default advanced editor of our GNU/Linux distribution, and our server infrastructure is big enough to host the website for you
https://www.parrotsec.org/docs/weathermap/
https://www.parrotsec.org/blog/the-parrot-cdn/
otherwise github-pages is an awesome alternative to keep all the control in your hands without the overhead of a shared hosting service.

My plan would be to work on a jekyll or mkdocs template, so that anyone can contribute to it by just using git.

**Comment by stripedpajamas** [comment]
Wow thanks so much @PalinuroSec 🙏🙏🙏 

There is a GitHub pages site (skeleton) that you could take over at https://GitHub.com/VSCodium/vscodium.github.io

**Comment by PalinuroSec** [comment]
i found some spare time to work on it and i made a first draft for you to review

i also registered the vscodium.com domain and i'm ready to publish the website with your approval.

p.s.
if you want to have control over the domain i can give you the transfer code, otherwise i would be happy to contribute by taking care of it through the parrot project.

p.p.s.
i'm not a web developer, tips are welcome

**Comment by stripedpajamas** [comment]
@PalinuroSec thanks for the first draft! 

is there a way to 100% tie vscodium.com to the vscodium.github.io github repo? so that merges to master affect it? that would be ideal. I don't really need control over the domain, I'd rather spread the wealth 😸

**Comment by PalinuroSec** [comment]
i can setup a pull cronjob to periodically update the repo from git and rebuild the static files with jekyll

**Comment by stripedpajamas** [comment]
Sounds good. I'll close this issue and work can continue in the website repo. Thanks @PalinuroSec

**Comment by Rondom** [comment]
https://help.github.com/en/articles/quick-start-setting-up-a-custom-domain
