### ISSUE TITLE
Update notes about extensions downloaded from the marketplace

### ISSUE THREAD

**Issue by xsrvmy** [VSCodium/vscodium#980]
A vscode issue brought up that the following four extensions are downloaded from the marketplace during build:
ms-vscode.references-view
ms-vscode.js-debug-companion
ms-vscode.js-debug
ms-vscode.vscode-js-profile-table

Also, related to this, node-debug and node-debug2 are no longer being downloaded.

There is a question right now on the official repo as to whether this violates the marketplace license terms. If it does, the solution is to clear out `builtinExtensions` in `product.json`, or to change the hardcoded link in `build/lib/extensions.ts`. Note that for some reason vscode-js-profile-table is not on openvsx.

**Comment by daiyam** [comment]
Thanks for the update.
