### ISSUE TITLE
Unable to install extension 'ms-vscode-remote.remote-wsl' as it is not compatible with VS Code '1.63.2'.

### ISSUE THREAD

**Issue by eabase** [VSCodium/vscodium#986]
**Describe the bug**

Following [these instructions](https://code.visualstudio.com/docs/cpp/config-wsl), I am trying to install the `Remote WSL` extension:
* https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

IDK, I don't intend to use VSCode.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

Instructions are not clear and json already has the extension there.
* https://github.com/VSCodium/vscodium/blob/master/DOCS.md#proprietary-extensions

**To Reproduce**

Normal extension installation

**Expected behavior**

It would work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS, Ubuntu 20.04, etc]
 - Architecture [e.g. x64, ia32, arm64]
 - Version [e.g. 1.33.0]

**Additional context**

**Comment by daiyam** [comment]
[Incompatibility due to licensing](https://github.com/VSCodium/vscodium/wiki/Extensions-Compatibility#incompatibility-due-to-licensing)
