### ISSUE TITLE
Something happened with VSCodium logo after upgrade to version 1.64.0

### ISSUE THREAD

**Issue by altwarg** [VSCodium/vscodium#989]
**Screenshots**
![image](https://i.postimg.cc/yNctVhQz/Screenshot-2022-02-04-091746.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Architecture: x64
 - Version: 1.64.0

**Comment by daiyam** [comment]
yep, I have also the issue on Linux.

**Comment by daiyam** [comment]
I will make a patch but it's not urgent since we can't release hotfix. It will have to wait for `1.64.1`.

But feel free to participate in the discussion #788 about adding hotfix capability to the project. Thx

**Comment by developomp** [comment]
I want to know how this bug get into the release in the first place. This is not a bug specific to a certain hardware or software. I can only think that nobody does even the simplest testing (opening the application on each OS) before making a release.

**Comment by daiyam** [comment]
Nope, I did open it (for the PR #988). But, by default, it opens the welcome page so I didn't see it.

**Comment by Yush08** [comment]
Please upload this new version to the RPM and Debian repos.

**Comment by daiyam** [comment]
@Yush08 Now, we can't do that until Microsoft releases the `1.64.1` version. But the solution is to add a release number, you can read that discussion at #788. Your opinion would be welcome ;)
