### ISSUE TITLE
Match package.json & product.json formatting

### ISSUE THREAD

**Issue by eabase** [VSCodium/vscodium#990]
It would be helpful to try to match the formatting and layout of the 2 app settings files `package.json` & `product.json`, so that that they can be easily `diff`'ed with official builds. As they are now, many diffs, get confused because of different indentation, different location of the items, and very hard to read because of the huge number of items in the official vscode package.

**Comment by daiyam** [comment]
@eabase Feel free to make a PR to add that functionality ;)

**Comment by eabase** [comment]
@daiyam 
Not sure why this was closed. It says *completed* but with no reference to any PR. 

I'm sorry I was not able to provide a PR at the time. I have since stopped using VSCodium, due to other issues...

**Comment by daiyam** [comment]
I've closed the issue because it would have been difficult and time consuming for an not needed feature.

To close it as completed was a mistake.
