### ISSUE TITLE
Whats the impact of recent telemetry commit?

### ISSUE THREAD

**Issue by eabase** [VSCodium/vscodium#991]
Just today there was an interesting commit for reducing telemetry (probably in order to meet GDPR regulations.)

https://github.com/microsoft/vscode/commit/7cde1becc6ff7cf31e3f950c390566a5c36a8479

What is the impact of this for VSCodium? 
(When can we see this implemented?)

**Comment by paulcarroty** [comment]
Slightly reduced telemetry and middleware cleanup.
