### ISSUE TITLE
Unable to move to new side panel etc. by dragging (1.64) 

### ISSUE THREAD

**Issue by jacksongoode** [VSCodium/vscodium#993]
**Describe the bug**
It looks like the editor, panel dragging behavior (drag to the new side panel) has been broken in 1.64. I just wanted to report this as I wonder if this is OS specific or if its widespread and no one's reported this?

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Drag panel container to the new side panel
or
1. Drag document to side for split view 

**Expected behavior**
Mimic previous version behavior where dragging causes a rearrangement

**Desktop (please complete the following information):**
 - OS: Fedora 35
 - Architecture x64
 - Version 1.64

**Additional context**

**Comment by daiyam** [comment]
I don't have the issue on macOS.

**Comment by daiyam** [comment]
Do you have the issue with VSCode?

**Comment by throwaway69420-69420** [comment]
I haven't installed it at present, do I need to install it? @daiyam 
give me some time

**Comment by throwaway69420-69420** [comment]
@daiyam yup, same issue on official build of vscode when run with `--enable-features=UseOzonePlatform --ozone-platform=wayland` flags, however on running without those flags both vscode and vscodium are able to perform panel drag onto the side panel

I also noted that when `--enable-features=UseOzonePlatform --ozone-platform=wayland` is used with vscode and vscodium, panel dragging to side panel works if I drag it the panel first outside of the vscode/vscodium window then drag it towards the side panel
@jacksongoode have a look here, this might help you

**Comment by throwaway69420-69420** [comment]
@daiyam yup, same issue on official build of vscode when run with `--enable-features=UseOzonePlatform --ozone-platform=wayland` flags, however on running without those flags both vscode and vscodium are able to perform panel drag onto the side panel

I also noted that when `--enable-features=UseOzonePlatform --ozone-platform=wayland` is used with vscode and vscodium, panel dragging to side panel works if I drag it the panel first outside of the vscode/vscodium window then drag it towards the side panel

@jacksongoode have a look here, this might help you

**Comment by jacksongoode** [comment]
> @jacksongoode are you on Wayland with those flags mentioned earlier?

Yes exactly.

**Comment by daiyam** [comment]
Based on https://github.com/VSCodium/vscodium/issues/849#issuecomment-1062188129, it should be fixed soon (maybe, depending on MS). You could also look at the possible workaround.
