### ISSUE TITLE
Can't find theme - lesterlo.monokai-charcoal-full-dark

### ISSUE THREAD

**Issue by frogtile** [VSCodium/vscodium#999]
I wanted to install https://github.com/lesterlo/VSCode-Monokai-Full-Dark-Theme, but I can't find it in via the extension search. I tried to use the cli command, `codium --install-extension lesterlo.monokai-charcoal-full-dark`, but it also says not found.

**Comment by hazarek** [comment]
please read the Docs.   https://github.com/VSCodium/vscodium/blob/master/DOCS.md
